### ISSUE TITLE
Aspect ratio on playback

### ISSUE THREAD

**Issue by k3jd4** [DanielnetoDotCom/YouPHPTube#10]
When playing a video in fullscreen, player does not maintain aspect ratio of the source, the content is stretched to fit whole area. In example "landscape" content is heavily distorted when screen is in portrait mode.

**Comment by DanielnetoDotCom** [comment]
Hi, are u mean on Mobile? or in desktop too?

**Comment by k3jd4** [comment]
Both of them.

**Comment by DanielnetoDotCom** [comment]
Ok, i just find a thing, could you please update your files, clear cache and try again?
it was an css issue

**Comment by k3jd4** [comment]
It's fixed. Thank you.

**Comment by DanielnetoDotCom** [comment]
You very welcome
