### ISSUE TITLE
Error with youtube-dl on centos

### ISSUE THREAD

**Issue by winklov** [DanielnetoDotCom/YouPHPTube#100]
Hi 

i did the installation but im getting this error when im trying to upload a video from youtube 

Im using a centos whm server with root access

We could not get the title of your video (sh: youtube-dl: command not found) go to https://github.com/DanielnetoDotCom/YouPHPTube/wiki/youdtube-dl-failed-to-extract-signature to fix it

**Comment by DanielnetoDotCom** [comment]
Please follow the instruction on the link

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
