### ISSUE TITLE
FFMPEG Encoding

### ISSUE THREAD

**Issue by SpinDry77** [DanielnetoDotCom/YouPHPTube#1003]
Does anyone know how to scale a video down without upscaling lower resolution videos?

This is what I know for FFMPEG how to do this with out double quotes since it will not take it with the current php?

It goes from:
-vf "scale=w=min(iw\,1280):h=-2" 
to
-vf

**Comment by SpinDry77** [comment]
I got it sorted with a lot of trial and error if anyone else has this problem -vf scale='min(1280\,iw):-2'
If anyone knows of a better what I'm all ears.

**Comment by DanielnetoDotCom** [comment]
Maybe is better ask it on the FFMPEG github https://github.com/FFmpeg/FFmpeg

**Comment by SpinDry77** [comment]
I found about 100 ways of doing it on there all include double quotes from what I gathered double quotes not working is unique to how the php is written on youphptube encoder. Instead of how its written for example you would have to use HTML instead of echo for pulling from the DB.

**Comment by DanielnetoDotCom** [comment]
try to put a slash before the double quotes

**Comment by SpinDry77** [comment]
I did but FFMPEG thought I was trying to do some sort of operation and errors out.

**Comment by maxlinux2000** [comment]
put ffmpeg in a script and receive the variables via standard imput, the  run the script from ffmpeg, like:

/usr/loca/bin/myscript.sh $inputVar1 $inputVar2

and the scritp:
-------------------
#!/bin/bash
MyVar1=$1
MyVar2=$2
ffmpeg..... "$Myvar1" ... "$MyVar2"
----------------------------
