### ISSUE TITLE
Purchased Plugins not active - permissions?

### ISSUE THREAD

**Issue by mcuix** [DanielnetoDotCom/YouPHPTube#1004]
I have uploaded the following some plugins to my site, but they don't seem to have access to the database and no changes seem to be registered.

ShareSocialButtonsOnEmbed
MP4ThumbsAndGif
Customize

How do I enable (give permissions) to the new plugins?

**Comment by DanielnetoDotCom** [comment]
What do you mean?
When you install they do not add the tables?

**Comment by mcuix** [comment]
I have uploaded them and followed these instructions:

> 1

 - Use the app plugin button

To use this button, make sure you have the unzip app on your server

sudo apt-get install unzip

You will also need to make the plugin dir writable before upload

chown www-data:www-data /var/www/html/YouPHPTube/plugin/ && chmod 755 /var/www/html/YouPHPTube/plugin/

If you still not sure ho to do it, take a look on this video: https://tutorials.youphptube.com/video/donwloading-and-installing-a-plugin

In the "Installed  Plugins" I have for example for the "Customize" plugin, pressed the "Install tables", after which I can see a "processing" dialogue. After this is finished I attempt to "customize site", but the changes are not registered.

**Comment by DanielnetoDotCom** [comment]
when you say "changes are not registered" do you mean the tables were not created?

What Linux distribution are you using?

**Comment by mcuix** [comment]
Ubuntu 16. "Changes are not registered" mean that the Social Share buttons are still enabled, and that Customize plugin does not save the changes. Same thing with the logo overlay plugin. The only solution I can see is to manually make the changes in the databases.

**Comment by DanielnetoDotCom** [comment]
really strange, can you get any clue from your log file?

**Comment by mcuix** [comment]
I can see nothing in the log files. Which parameters need to be changed in the database to disable the social and share buttons, if I need to do it manually?

**Comment by DanielnetoDotCom** [comment]
try this

![image](https://user-images.githubusercontent.com/18009293/44621185-faf90b00-a877-11e8-8e9e-b5a0c3f7f21f.png)

**Comment by mcuxdk** [comment]
I already have these ticked off:
![share_code](https://user-images.githubusercontent.com/26693767/44621621-72935e00-a8a9-11e8-976b-20ce78bd0e17.png)

![code](https://user-images.githubusercontent.com/26693767/44621620-72935e00-a8a9-11e8-81df-9aeafeb0cf99.png)

and the videos still showing the share as enabled:

![share](https://user-images.githubusercontent.com/26693767/44621622-72935e00-a8a9-11e8-92ee-3b62e2d42809.png)

**Comment by mcuxdk** [comment]
Think that I figured some of it out. I have disabled both Facebook Tube (FBTube) and Gallery (Gallery) and now the ability to Share and Embed are disabled.
