### ISSUE TITLE
Encoder different video resolutions ? Is it possible? 

### ISSUE THREAD

**Issue by sesipod** [DanielnetoDotCom/YouPHPTube#1005]
When a user uploads a video to my page I would like videos to be converted into - 720 / 1080 / 1440 after upload. 
I have changed the _scale=_ below for each section. I don't know if that is the correct way of going about this ? Could someone please help me out finding the best settings to get the above resolutions after upload.

**MP4 Low:** ffmpeg -i {$pathFileName} -vf scale=1280:720 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -y {$destinationFile}

**MP4 SD:** ffmpeg -i {$pathFileName} -vf scale=1920:1080 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -y {$destinationFile}

**MP4 HD:** ffmpeg -i {$pathFileName} -vf scale=2560:1440 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -y {$destinationFile}

**WEBM Low:** ffmpeg -i {$pathFileName} -vf scale=1280:720 -movflags faststart -preset ultrafast -f webm -c:v libvpx -b:v 1M -acodec libvorbis -y {$destinationFile}

**WEBM SD:** ffmpeg -i {$pathFileName} -vf scale=1920:1080 -movflags faststart -preset ultrafast -f webm -c:v libvpx -b:v 1M -acodec libvorbis -y {$destinationFile}

**WEBM HD:** ffmpeg -i {$pathFileName} -vf scale=2560:1440 -movflags faststart -preset ultrafast -f webm -c:v libvpx -b:v 1M -acodec libvorbis -y {$destinationFile}

**Comment by DanielnetoDotCom** [comment]
check the log file, also check if the video file really exists.

**Comment by sesipod** [comment]
( I have made changes to the resolutions since the original posting... )

I am thinking the EE:EE:EE:EE is because the size of the files are exceeding the php allowed max size during encoding. 
My upload size is 900MB and the encoder is making the video files almost 3 times the size??? :o
Here are the results:
LOW: 640x480 @ 122.75MB 
SD:    1280x720 @ 1.41GB
HD:    1920x1080 @ 2.51GB
After the encoding I try to play the video and I get the following... ( The media playback was aborted due to a corruption problem or because the media used features your browser did not support. ) 

Here is the logs. [logs.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2329616/logs.log)
<img width="1052" alt="screen shot 2018-08-28 at 2 07 10 pm" src="https://user-images.githubusercontent.com/1533744/44746797-f7ac8c00-aad0-11e8-9560-12c6d327e6ed.png">

**Comment by DanielnetoDotCom** [comment]
the only thing there should be the HD video not copied.

but should not have a corruption issue, check your log file.

also, make sure this ... https://github.com/DanielnetoDotCom/YouPHPTube/wiki/About-Video-Upload#ram-memory

how much memory do you have?

> There is a script calculation..., your maximum file size can be only 50% of your RAM memory because the script needs to copy files between locations and handles it on the virtual memory.
> 
> In Example, if you want to upload a 4GB file you will need to have at least 8 GB Ram on the server other wise you will have a Memory Leaks - Allowed memory size of # bytes exhausted error.
>

**Comment by sesipod** [comment]
I attached the log file above. If you could have a quick look and let me know the issue ?

-----

> also, make sure this ... https://github.com/DanielnetoDotCom/YouPHPTube/wiki/About-Video-Upload#ram-memory

> how much memory do you have?

> There is a script calculation..., your maximum file size can be only 50% of your RAM memory because the script needs to copy files between locations and handles it on the virtual memory.
> In Example, if you want to upload a 4GB file you will need to have at least 8 GB Ram on the server other wise you will have a Memory Leaks - Allowed memory size of # bytes exhausted error.


I noticed that link before making the post when trying to find a fix. So I currently have php.ini allowed up to 2048mb in upload size. 

Here are the VPS secs:
CPU: 2 CPU
RAM: 4 GB
SSD: 60 GB
BW:   3 TB

**Comment by DanielnetoDotCom** [comment]
I could not see any error but the max upload size.

try to increase it and let me know

**Comment by sesipod** [comment]
So increase the php max upload size over the 50% ram ???
I am currently at 2048mb. I only have 4096 mb of ram.

**Comment by DanielnetoDotCom** [comment]
check this https://github.com/DanielnetoDotCom/YouPHPTube/issues/546

**Comment by sesipod** [comment]
It says I closed it .. woops

So I made the following changes and still the same issue.
It encoded the Low & SD and then gave up on the HD version.

max_execution_time = 9000 (was - 7200)
max_input_time = 1800 (was - 90)
memory_limit = 2048M
post_max_size = 2048M
upload_max_filesize = 2048M

Video file size - 958.1 MB
System Ram: 4096M (4GB)

Here is the log file form this try : 
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2333741/youphptube.log)

**Comment by DanielnetoDotCom** [comment]
I mean try to change the values to ...

post_max_size = 3072M
upload_max_filesize = 3072M

the script could not transfer the file

**Comment by sesipod** [comment]
Looks like that fixed the issue :D . I am going be upgrading to a larger server in a bit so the 4Gb ram limit should be a thing of the past soon! Thank you for your help!

**Comment by DanielnetoDotCom** [comment]
great :)

**Comment by sipero** [comment]
Can someone tell me which file I need to edit please
MP4 Low: ffmpeg -i {$pathFileName} -vf scale=1280:720 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -y {$destinationFile}

MP4 SD: ffmpeg -i {$pathFileName} -vf scale=1920:1080 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -y {$destinationFile}

**Comment by DanielnetoDotCom** [comment]
@sipero , which file you need to edit for what?

Any way, the FFMPEG commands you find here 

![image](https://user-images.githubusercontent.com/18009293/60965478-55625500-a2ec-11e9-997f-093718566752.png)
