### ISSUE TITLE
Can Individual Users Monetize Their Own Videos

### ISSUE THREAD

**Issue by KenRHill** [DanielnetoDotCom/YouPHPTube#1006]
I am trying to figure out if it is possible for individual users of YouPHPTube to be able to monetize their own videos.  I am hoping to allow people to monetize their own videos similar to how YouTube works.  Is this possible on this platform?  Please advise.  Thank you.

**Comment by DanielnetoDotCom** [comment]
We dont have this feature yet, but we will implement it in the future
