### ISSUE TITLE
Add multiple domains as websiterooturl 

### ISSUE THREAD

**Issue by geoasher023** [DanielnetoDotCom/YouPHPTube#1008]
I have multiple domains that I point to my YouPHPTube streamer, so in order for me to get the streamer to function on all those domains I have to put a "/" under websiterooturl in videos/configuration.php so that when someone went on the site as example.com the links wouldnt point to example2.com.
In other words if I would put example.com as my websiterooturl than no matter what domain they use to get to the site all the links, images, videos etc would be on example.com instead the domain they typed.
My question is although putting a "/" instead of example.com works fine for navigation it dosent work with the encoder (I run my own server and encoder), it reads "We could not find your streamer site!" ( / )

**Comment by DanielnetoDotCom** [comment]
maybe you will need to use a dynamic site URL, I never did it before, but I guess it is possible to do. you will need to google for that and put this code on the configuration.php file

**Comment by geoasher023** [comment]
Many of my uploaded videos out of no where become a youtube embedded video,
so they show the right file on the thumbnail but when you click on it it
loads another video that happens to be a youtube embed, have you ever seen
something like this before?

**Comment by DanielnetoDotCom** [comment]
I have never seen this.

can you reproduce it on demo site?
