### ISSUE TITLE
Why are user hashed passwords being used for server url?

### ISSUE THREAD

**Issue by proevilz** [DanielnetoDotCom/YouPHPTube#1009]
Why are users hashed passwords being used as the stream `/livep?=` parameter value?

**Comment by DanielnetoDotCom** [comment]
this parameter is for stream only, that is the way we found to not let anyone stream in your site, only authenticated users will be able to do it.

**Comment by proevilz** [comment]
But surely this is an insecure practise in theory? Why not generate a unique ID hash but just simply not of the password?

**Comment by DanielnetoDotCom** [comment]
Yes, it may be changed in the future, agree, it needs to be changed
