### ISSUE TITLE
I have a few small proposals

### ISSUE THREAD

**Issue by oyjcmyn** [DanielnetoDotCom/YouPHPTube#101]
I have a few small proposals:
1. Add can only display MP4 format video (like 4.0 before the version) (can save a better server disk space, the browser almost all support MP4).
2. Add video playback that can support M3U8 format, and HLS format video encoding (which can save bandwidth and traffic better)
3. When the video title downloaded on YOUTUBE has Chinese characters (and other special characters), it will no longer appear and become blank, causing the URL of the video to become blank or "-". It is recommended to encrypt the video URL, like the YOUTUBE video URL: / watch? V = 8uJnTY0FoPc
4. It is recommended to set whether to send the encoded video file to YouPHPTube - Streamer. When the settings are not sent, a Streamer site can configure multiple Encoder sites and save time on different servers while also sending video files. When there is a lot of video, all the videos are split in different servers, which is more conducive to late expansion.

If you can let it run directly on the nginx, it would be great, so that more people can use it.

I wrote two complete nginx rules (including Streamer and Encoder). Has been able to perfect support, and hope that the author can add it to the version.

[YouPHPTube-nginx.zip](https://github.com/DanielnetoDotCom/YouPHPTube/files/1269820/YouPHPTube-nginx.zip)

**Comment by DanielnetoDotCom** [comment]
Hi Thanks

I like them all

1. Add can only display MP4 format video (like 4.0 before the version) (can save a better server disk space, the browser almost all support MP4).
I will do that, also I will include the option for the user can send an (already MP4 encoded to the server), with out need to encode again

2. Add video playback that can support M3U8 format, and HLS format video encoding (which can save bandwidth and traffic better)
What is that?

3. When the video title downloaded on YOUTUBE has Chinese characters (and other special characters), it will no longer appear and become blank, causing the URL of the video to become blank or "-". It is recommended to encrypt the video URL, like the YOUTUBE video URL: / watch? V = 8uJnTY0FoPc
I will take a look on that, can you give me some youtube URL example with chinese characteres?

4. It is recommended to set whether to send the encoded video file to YouPHPTube - Streamer. When the settings are not sent, a Streamer site can configure multiple Encoder sites and save time on different servers while also sending video files. When there is a lot of video, all the videos are split in different servers, which is more conducive to late expansion.
I am working on that it is not done yet, you can check this out here: http://network.youphptube.com/

**Comment by oyjcmyn** [comment]
Thanks,
> 2. Add video playback that can support M3U8 format, and HLS format video encoding (which can save bandwidth and traffic better)
> What is that?

Support this video format playback, for example: [http: //www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8](http: //www.streambox.fr/playlists/x36xhzz/x36xhzz.m3u8)
In YouPHPTube - Encoder can also set the encoding m3u8 video format (HTTP Live Streaming).
This form of m3u8 is also suitable for PC and mobile side, while it will not play a full video when playing, you can avoid the waste of traffic.

> I will take a look on that, can you give me some youtube URL example with chinese characteres?

Such as YOUTUBE video https://www.youtube.com/watch?v=xqIwem7uPls
Its title is almost all Chinese characters, it is downloaded code, URL only "MV" two English characters.
Is to hope that it can automatically generate a special URL address, to avoid the same characters lead to the same URL address, or into a blank.
Can the following two pictures.
![20170902143310](https://user-images.githubusercontent.com/24839942/29993608-a944ab86-8fee-11e7-8b24-6da42b96549b.jpg)
![20170902143435](https://user-images.githubusercontent.com/24839942/29993610-b1688f26-8fee-11e7-8150-1e6b79289f67.jpg)

Chinese character site: http://mv.loveud.com

**Comment by DanielnetoDotCom** [comment]
Hi, good news for you we have just released a new version of YouPHPTube that allows you to upload an MP4 video without the need to encode.
Also by default YouPHPTube encodes only MP4, if you want WebM encode you need to check the button on encode panel

![image](https://user-images.githubusercontent.com/18009293/30005197-6016c802-90b3-11e7-92f1-7cc361217527.png)


I am still working on other requests

**Comment by oyjcmyn** [comment]
Ok, thanks

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
