### ISSUE TITLE
Apache HTTPS redirect

### ISSUE THREAD

**Issue by proevilz** [DanielnetoDotCom/YouPHPTube#1010]
In order to get the LiveStream to work correctly, I had to disable Apache's autoredirect to https. But how can I make it force https on my site without it affecting the stream?

**Comment by DanielnetoDotCom** [comment]
your stream must be https as well

**Comment by proevilz** [comment]
How? NGINX is set up to use SSL already but that makes no difference

**Comment by DanielnetoDotCom** [comment]
Maybe you are missing something, the demo site works on that way, both apache (port 443) and NGINX (port 444) https on the same server

**Comment by proevilz** [comment]
Could you post your demo site apache & nginx config please?

**Comment by proevilz** [comment]
And how is your Apache set up? I used Certbot on Apache and not NGINX...

**Comment by DanielnetoDotCom** [comment]
I used on both , just stop Apache before run certbot on nginx

**Comment by proevilz** [comment]
Whats your actual config though? Your installation instructions of installing LAMP does not go into configuring Apache so there are no vhosts specifically set up either

**Comment by DanielnetoDotCom** [comment]
Yes I use vhosts and certbot automatically add the ssl configuration

**Comment by proevilz** [comment]
What command do I use for that? I only know how to install it on one or the other.. I don't really need to generate new keys, but rather just install it for nginx from the keys I already have. How did you do it?

**Comment by DanielnetoDotCom** [comment]
Is better you google for that, I can't give ssl installation support

**Comment by RedTapeTV** [comment]
> What command do I use for that? I only know how to install it on one or the other.. I don't really need to generate new keys, but rather just install it for nginx from the keys I already have. How did you do it?

proevilz, did you ever figure out how to do this correctly? This is the only issue I am still having.
