### ISSUE TITLE
Password change by admin only

### ISSUE THREAD

**Issue by HeinziTuberkel** [DanielnetoDotCom/YouPHPTube#1012]
Hi,
I have some videos, I want to show only to a group of people. 
I created one user that has access to these videos and everyone I want to see these videos gets to know the user name and password.
I don't want that user to change his password, or all the others can't access these videos anymore.
Is it possible to configure the user in a way that only I with my admin login can change the password?

**Comment by DanielnetoDotCom** [comment]
no, you can't, what you can do is to create unlisted videos, and only who has the link will be able to see it.
