### ISSUE TITLE
How to ban people

### ISSUE THREAD

**Issue by proevilz** [DanielnetoDotCom/YouPHPTube#1014]
How do you effectively ban people on this platform?

The ban only seems to work when the banned user next re-authenticates. It does not destroy the banned user session immediately... 

If someone is live streaming and getting abuse in chat, what are they supposed to do about it?

**Comment by DanielnetoDotCom** [comment]
I see, your needs.

Sorry, we don't have that feature yet, but will be good to be implemented in the future.

**Comment by DanielnetoDotCom** [comment]
you can inactivate them and only allow authenticated users to use the chat

**Comment by proevilz** [comment]
But does the chat check for authentication on each message or does it suffer the same problem?

**Comment by DanielnetoDotCom** [comment]
I guess it check on every message, each message is linked with the user, but inactivated users will be blocked only on the next login attempt

**Comment by proevilz** [comment]
Then the block feature is basically useless.... There is currently no way to remove abusive people from the platform until the log out. How long does the php user session last for?

**Comment by proevilz** [comment]
If people start streaming illegal content or hate speech or porn, there is no way to deal with it. I know this project is free but how isn't this a basic feature that was implemented on its creation?

**Comment by DanielnetoDotCom** [comment]
session timeout depends on your server configuration.

If you want to band an abusive Livestream you will need to inactivate the user and restart nginx

**Comment by proevilz** [comment]
So we have to take down the entire stream platform just to remove one user...

**Comment by DanielnetoDotCom** [comment]
For now yes

**Comment by DanielnetoDotCom** [comment]
FYI, right after restart all users will be reconnected

**Comment by proevilz** [comment]
I just tested it, restarting nginx doesn't make a difference. Users that are banned can still chat because nginx does not destroy sessions

**Comment by proevilz** [comment]
so it seems not only do you have to take down nginx, but you have to take the entire site offline by restarting apache. This is terrible..

**Comment by proevilz** [comment]
In fact, i just restarted apache and that didn't work either lol

**Comment by DanielnetoDotCom** [comment]
I just sent an update, the nginx restart should work now (I Guess)

**Comment by tgibson1** [comment]
Is the chat plugin open source? Table LiveChat, could be adapted to include an ip address column which is recorded whenever a user posts a comment. This information could be used to effectively ban a user from the server by adding a new iptables rule.

Enter the following rule to block an IP address from accessing your server
iptables -A INPUT -s <IP-ADDRESS of the commentor> -j DROP

**Comment by DanielnetoDotCom** [comment]
Hi

you can use the Chat2 plugin with the User_Controll plugin, this will allow you to ban users and IPs
