### ISSUE TITLE
User location

### ISSUE THREAD

**Issue by Nisarg22** [DanielnetoDotCom/YouPHPTube#1015]
![image](https://user-images.githubusercontent.com/39002772/44789114-741a9a00-abb9-11e8-9385-00431ba21a49.png)

This is what comes after i unzip install.sql file from user location plugin

**Comment by DanielnetoDotCom** [comment]
You prbably didnt install the tables.

Follow the instructions.

![image](https://user-images.githubusercontent.com/18009293/44791446-01d59580-ab78-11e8-9a28-92ad7d3bb8ad.png)

then click on the **install tables** button
