### ISSUE TITLE
Gallery (Gallery)

### ISSUE THREAD

**Issue by roc-lone** [DanielnetoDotCom/YouPHPTube#1016]
Hi,

I'm using the Gallery for the format of the site. At this time when going to the site I have the Gallery set up to display a Big video on the opening page. The video is random but I would like to know if I could have the same video displayed for the Big video every time instead of random videos and if I can what/where is the setting?
Thank you,
roc-lone

**Comment by DanielnetoDotCom** [comment]
Try to suggest videos

![image](https://user-images.githubusercontent.com/18009293/44869973-3d9a5900-ac65-11e8-8345-d4db3d1d91cc.png)

**Comment by roc-lone** [comment]
The Suggest Video seems to work but in looking at your screen shot I noticed something, My Videos settings does not have the options "Upload a Document", "Upload Subtitle" or "Create Subtitle". Should I be see those on my installation?

![danvideos_8-31-2018](https://user-images.githubusercontent.com/41485208/44894674-934b2180-acb6-11e8-8fa9-8dbd02835749.jpg)

![myvideos2a_8-31-2018](https://user-images.githubusercontent.com/41485208/44894698-b07ff000-acb6-11e8-8807-c4e7a1ca54c5.jpg)

**Comment by mikweb2017** [comment]
![subtitile](https://user-images.githubusercontent.com/30271757/44897325-8bfa3700-acfb-11e8-8b71-a3dd8463433d.PNG)
you must buy this plugin

**Comment by roc-lone** [comment]
Ah, ok, thank you for the help.

**Comment by DanielnetoDotCom** [comment]
Yes that is right.

Upload document is a new plugin, it is not on the market yet
