### ISSUE TITLE
keep processing

### ISSUE THREAD

**Issue by Nisarg22** [DanielnetoDotCom/YouPHPTube#1018]
Whenever i try to do anything my site just keep processing and we have to close the site and reopen it to see the result
site http://eduvid.in
can u please check

**Comment by Nisarg22** [comment]
![image](https://user-images.githubusercontent.com/39002772/44911755-8f1a1500-ad45-11e8-95f1-7b304334bf03.png)
![opera snapshot_2018-08-31_174433_eduvid in](https://user-images.githubusercontent.com/39002772/44911791-b2dd5b00-ad45-11e8-8ec3-e0f42570a47a.png)
Whats the problem??

**Comment by DanielnetoDotCom** [comment]
if you disable it you will see the default youtube player

**Comment by Nisarg22** [comment]
whenever i try to embeded link it just keep processing i have close my site and reopen to see it

**Comment by Nisarg22** [comment]
and one more thing as u said to uncheck disable youtubeplayerintegration still it shows
![image](https://user-images.githubusercontent.com/39002772/44940719-0b494280-adb0-11e8-82db-e6e4a8d02858.png)

**Comment by DanielnetoDotCom** [comment]
Hi

Did I said to disable youtubeplayerintegration???

Anyway, I dont think you are able to remove youtube logo on embed videos

**Comment by Nisarg22** [comment]
ok but what about keep processing
