### ISSUE TITLE
Will ffmpeg encoding time benefit from a non Xeon cpu?

### ISSUE THREAD

**Issue by sesipod** [DanielnetoDotCom/YouPHPTube#1020]
I am looking at upgrading form a 2 v core VPS to a new dedicated server. I am wondering if FFMPEG would benefit form a non Xeon type cpu. I am using " -preset medium " for my 720p and 1080p encodings. 

Here are my choices: 1_  Intel Xeon D-1521 (or) 2_  Intel  i7-6700K (or) 3_  i7-7700K...

**Comment by DanielnetoDotCom** [comment]
I am not sure, maybe you can find that answer on FFMPEG repository https://github.com/FFmpeg/FFmpeg

**Comment by sesipod** [comment]
I will do some testing and come back with an update - For now this issue will be closed :)
