### ISSUE TITLE
0 Views

### ISSUE THREAD

**Issue by adinteligenciadigital** [DanielnetoDotCom/YouPHPTube#1022]
Hi Daniel! First of all I would like to thank you for this wonderful project, may God continue to bless you!

So I have a little doubt, the views are not counting, always gets 0 views, can you help me? Thank you, I'm waiting!

**Comment by angelawong** [comment]
Daniel, where are the log files? I am having a similar issue with a very short video. It is only 57 second long but when I view it again, the number of views does not increase. On my longer videos, though, the views go up when I view it again.

**Comment by DanielnetoDotCom** [comment]
Please check here https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by angelawong** [comment]
Thanks Daniel. I found the log file. What errors am I to look for in the log file to indicate that there is an issue with the counter?

**Comment by DanielnetoDotCom** [comment]
If it is regarding a embed video I just made a fix, It will be released soon
