### ISSUE TITLE
User permissions- categories?

### ISSUE THREAD

**Issue by mcuix** [DanielnetoDotCom/YouPHPTube#1025]
I have 30 videos and 3 groups of users A, B and C. Each user would have a group login, instead of individual user accounts. 
How would a configuration look that allowed each group to see a selection of 10 videos each, but be excluded from seeing videos from the other groups. For exam group A can see videos 1 to 10, but not 11 to 30. My idea at the moment is to:
Create an admin
Create three user accounts A, B, C
Where I am in doubt is do I put videos in a category or channel or what?
Is it possible to simple provide a link that would show the restricted group A videos.?

Suggestions appreciated.

**Comment by DanielnetoDotCom** [comment]
Try to use the User groups on the video

![image](https://user-images.githubusercontent.com/18009293/44985930-7d5c8b80-af58-11e8-8d44-875fc044e128.png)
