### ISSUE TITLE
ssl install

### ISSUE THREAD

**Issue by Nisarg22** [DanielnetoDotCom/YouPHPTube#1026]
after installing lets encrypt ssl my site looks like
site with ssl  https://eduvid.in
![screenshot_2018-09-03-12-01-00](https://user-images.githubusercontent.com/39002772/44970934-61191880-af71-11e8-9ca9-092531768d7d.jpg)
http://eduvid.in

**Comment by mikweb2017** [comment]
change  url  an config.php

<?php
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
**$global['webSiteRootURL'] = 'https:';**
