### ISSUE TITLE
Download videos

### ISSUE THREAD

**Issue by Nisarg22** [DanielnetoDotCom/YouPHPTube#1027]
Is it possible that u must login to download videos without login u can't download videos

**Comment by DanielnetoDotCom** [comment]
I see, for now we dont have that option

**Comment by Nisarg22** [comment]
ok whenever i try to download video from my site it shows file corrupt

**Comment by DanielnetoDotCom** [comment]
are you using the secure directory plugin?

**Comment by Nisarg22** [comment]
No i m not using it

**Comment by DanielnetoDotCom** [comment]
is your site live, can I check it?

**Comment by Nisarg22** [comment]
@DanielnetoDotCom  https://eduvid.in

**Comment by DanielnetoDotCom** [comment]
I cant see the download button

**Comment by Nisarg22** [comment]
I enabled it again now u can see it

**Comment by DanielnetoDotCom** [comment]
I cant see

**Comment by Nisarg22** [comment]
Clear cache and try I have enabled cache plugin

**Comment by DanielnetoDotCom** [comment]
I just tested and it works fine

**Comment by Nisarg22** [comment]
Did it get downloaded because in mine it shows corrupt file

**Comment by Nisarg22** [comment]
I have tried in phone and pc in chrome opera and uc browser but problem remains same

**Comment by DanielnetoDotCom** [comment]
I just try your site  https://eduvid.in again on a windows Chrome and Firefox, and works fine on both

Also I tried on a linux Firefox and is fine

**Comment by Nisarg22** [comment]
Mean video is downloading
