### ISSUE TITLE
embed iframe with autoplay

### ISSUE THREAD

**Issue by Edtigoza** [DanielnetoDotCom/YouPHPTube#1028]
Hi, need some help... 
I can not make autoplay an iframe, I have not found any plugin,
does this feature exist on youphptube?
or is still in the development phase.
I tried the tag  `<video autoplay="autoplay"></video> `   for the autoplay and it has not worked either

**Comment by Nisarg22** [comment]
Auto play is already there

**Comment by Edtigoza** [comment]
hi,
how can enable autoplay?

**Comment by DanielnetoDotCom** [comment]
I added an autoplay option on the iframe, please update your files and try now

**Comment by Edtigoza** [comment]
ok, thanks...

**Comment by Edtigoza** [comment]
adding     ?autoplay=1   it works
