### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by KeithGraber** [DanielnetoDotCom/YouPHPTube#103]
Hello

I've look around but not found any source of the correct method of updating YouPHPTube and YouPHPTube-Encode.

My install method was with git.  When I run the git command a 2nd time I receive an error about the directory not being empty.

The reason for the upgrade is for the option to not have to re encode a .MP4 on upload (my first .MP4 upload  jumped from 265Mb to over 600Mb).

I'm running v4.0.

Thanks!

**Comment by DanielnetoDotCom** [comment]
Did you try to go to the youphptube dir ant type `git pull`
Also there is a video that may help you https://tutorials.youphptube.com/video/how-to-update-your-youphptube-version

**Comment by KeithGraber** [comment]
Thanks for the tips!  I missed the video in my searches.

I ran the git pull in my YouPHPTube directory and received the following error:

Updating e92ca78..f3441e0
error: Your local changes to the following files would be overwritten by merge:
        .htaccess
Please, commit your changes or stash them before you can merge.
Aborting

I don't remember changing the .htaccess file, but I've slept since I did the original install :-)

I did a eyeball compare between my .htaccess file and what is here in the git repository but they look the same.  Should I just remove the .htaccess file and re-pull?

**Comment by DanielnetoDotCom** [comment]
try this https://stackoverflow.com/questions/1125968/how-do-i-force-git-pull-to-overwrite-local-files

**Comment by KeithGraber** [comment]
Thank you, I'll take a look at the link.
