### ISSUE TITLE
I just installed the software and page loads just fine but not avalable to any internal links on the menu

### ISSUE THREAD

**Issue by mlatino** [DanielnetoDotCom/YouPHPTube#1031]
I can;t access any option on the menu from login to contact here the error message:

Not Found
The requested URL /user was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by DanielnetoDotCom** [comment]
Check your mod rewrite and please check if your .htaccess file is there

**Comment by mlatino** [comment]
I did and still facing  same issue

**Comment by DanielnetoDotCom** [comment]
must be something regarding your mod_rewrite, what OS and web server are you using?

**Comment by mlatino** [comment]
easy apache 4

**Comment by DanielnetoDotCom** [comment]
IDK easy apache 4

And for me CentOS is unpredictable, usually, you have Cpanel and other things.
For sure the error is regarding mod_rewrite , but I cant help you more then that.

The best OS to install it is ubuntu

**Comment by mlatino** [comment]
I noticed if I install the software in the youphptube folder the software runs good but the issue I'm facing only if I intall software on root


________________________________

**Comment by DanielnetoDotCom** [comment]
Take a look on it and see if it helps 
https://tutorials.youphptube.com/video/fix-youphptube-url-after-move-server-location-and-ip
