### ISSUE TITLE
Advertising banner on right

### ISSUE THREAD

**Issue by jeffvdo** [DanielnetoDotCom/YouPHPTube#1032]
Hi 

Can we add one more banner (or non-adsense banner) in up next section on the rightblike your demo? Which file should we paste the advertising code?

https://demo.youphptube.com/video/the-jungle-book-amazing-new-360-video-2016-

Thanks.

**Comment by DanielnetoDotCom** [comment]
it was made for Google Ad sense, but you can use other Ads scripts, to customize it you will need to look into the code, there is no ready solution for it yet

**Comment by hltibbs** [comment]
https://user-images.githubusercontent.com/63832376/103596745-9ed53580-4ecc-11eb-896a-3d4363b0c835.mov

**Comment by hltibbs** [comment]
Ok, how do I get a MOV file to work in the software?
