### ISSUE TITLE
question on updating to newest version

### ISSUE THREAD

**Issue by loso20p** [DanielnetoDotCom/YouPHPTube#1033]
whats the newest version?
can i just update from an old version (5.2)to the latest verison 
or gotta update one by one until i get to the latest version?

**Comment by DanielnetoDotCom** [comment]
You must update one by one, and the latest version is the master github files. just make a git pull to update all files

**Comment by loso20p** [comment]
a git pull?

you dont have a list of all there releases thats been updated

**Comment by DanielnetoDotCom** [comment]
Check here how to update correctly  https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-Update-your-YouPHPTube
