### ISSUE TITLE
Little language-checker (Windows)

### ISSUE THREAD

**Issue by TLCReuver** [DanielnetoDotCom/YouPHPTube#1036]
Simple language checker (Windows).

[Translate.zip](https://github.com/DanielnetoDotCom/YouPHPTube/files/2357849/Translate.zip)

Because youPHPtube language files are modified during updates and i don't want te check every line i made a little programm that check my language files and shows me in color the modifications. The program need 3 arguments to start and are stored in translate.ini file.

1. Inputfile = us.php
   This must be the original file from which arrays will be read (normally us.php)
2. Replacefile = nl.txt
   This file hold the arrays which you once translated and they replaces the arrays in the Inputfile (us.php)
   When you translate an array from us.php you have to put that translated array in this file.
3. Outputfile = nl.php
   This is your language file where the changes are stored.

So, all arrays from Replacefile found in Inputfile will be replaced and are stored in Outputfile. In this way no array will be lost in your language file.

Colors
======
When you start the programm you see every array two times. The first line is the original array (green & yellow).
The second line shows if this array is modified (cyan) or not (gray). This way you can scroll back to see which arrays are not translated.

APPENDfile
==========
Sometimes there are arrays you can not find in us.php because these arrays will be added in a future update.
Some examples are:
$t['Sign In'] = "Inloggen";   
$t['Sign Out'] = "Uitloggen";
$t['Sign out'] = "Uitloggen";

In translate.ini you can find the 4th argument 'Appendfile = nl_append.txt'. All arrays strored in the Appendfile will be appended to the Outputfile (In my case nl.php)

CHANGED ARRAY's
===============
When an array in the Replacefile (nl.txt) is not found in the Inputfile (us.php) you will be notified in red like:

Lines not found in Replace-file:
================================
$t['Total users'] = "Totaal Gebruikers";

In this example the array ['Total users'] does not exist anymore in Inputfile (us.php). During update is this array deleted or changed in ['Total Users']  (with capital U).

Best regards,

Theo

![snap1](https://user-images.githubusercontent.com/39981177/45171021-9dfb3e80-b201-11e8-9b8c-c57cf4528142.jpg)
![snap2](https://user-images.githubusercontent.com/39981177/45171028-a3f11f80-b201-11e8-861d-44cdb3b5cf0f.jpg)

**Comment by DanielnetoDotCom** [comment]
Great, I will take a deep look later
