### ISSUE TITLE
Embed FaceBook and LikeLeak

### ISSUE THREAD

**Issue by kerchhow** [DanielnetoDotCom/YouPHPTube#1037]
Is it possible to embed FaceBook and LikeLeak videos?

**Comment by kerchhow** [comment]
I have it pulls all the information through like the title and video thumbnail but not the actual video itself. Just shows a black screen. I tried a public video from both FaceBook and LiveLeak.

**Comment by DanielnetoDotCom** [comment]
Can you please share some the links you are using here?
I want to make some tests.

**Comment by kerchhow** [comment]
Sure try this URL 
https://www.facebook.com/musicnew111/videos/725252001142579/

**Comment by DanielnetoDotCom** [comment]
Hi

I just tried it, and looks like facebook block embed items.

I found this error on the code 

![image](https://user-images.githubusercontent.com/18009293/45774306-00513780-bc23-11e8-851a-5de076461520.png)

And I got this answer on the web

https://stackoverflow.com/questions/27358966/how-to-set-x-frame-options-on-iframe
