### ISSUE TITLE
Offline Connection "Interupted"

### ISSUE THREAD

**Issue by pedroboneto** [DanielnetoDotCom/YouPHPTube#1038]
Hi,

I'm install YouPHPTube 5.6 and nginx in a Ubuntu-Server 16.04.

Ok, i'm trying to stream a video, from obs, and the connection is ok, when I go to Live page, is online, but, when I play the video, the image is a thumbnail like: OFFLINE Connection Interupted.

![offline](https://user-images.githubusercontent.com/43045531/45177407-376a2680-b1e9-11e8-8ecd-eba9e91d3e48.png)

Anybody?

Tks!

**Comment by DanielnetoDotCom** [comment]
Probably you could not connect with the nginx server and you are mixing http and https.

Try to check your browser network log.
