### ISSUE TITLE
TopMenu plugin

### ISSUE THREAD

**Issue by iscriptor** [DanielnetoDotCom/YouPHPTube#1039]
Hello,

Please, is there anyway to make TopMenu plugin pages  search engine friendly URLs? for 
example domain.com/policy rather than this domain.com/plugin/TopMenu/?id=1

Regards.

**Comment by Criptos** [comment]
You would need to add it to your .htaccess file directly the mod_rewrite instruction you need statically,  from the firendly url to the url expected by TopMenu....

**Comment by DanielnetoDotCom** [comment]
It is a great idea, I will think about something.

**Comment by iscriptor** [comment]
Thanks, I will find solution for it.

**Comment by DanielnetoDotCom** [comment]
I think @Criptos will take care of it.

Thanks @Criptos
