### ISSUE TITLE
Can avoid direct download from Backblaze?

### ISSUE THREAD

**Issue by jeffvdo** [DanielnetoDotCom/YouPHPTube#1040]
Hi,

I'm using backblaze plugin but have a big problem. The backblaze direct link is easily found and visitors can direct download my MP4 files. That should cost us a lot in long term.

I tried to set private in backblaze but cannot play the video in my web too. Any settings can avoid or make it harder to find the video link?

Thanks.

**Comment by DanielnetoDotCom** [comment]
Hi

I just add an token feature on the B2 plugin.

now you can make your bucket private, each request will create an authorization code that by default expire in 12 hours.

you will be able to change it on the new presignedRequestSecondsTimeout parameter.

Download again your BlackBlaze plugin you will get the update

**Comment by jeffvdo** [comment]
Great with thanks.

But found another problem. Backblaze Class C transactions increase very fast. It counts even I visit non-backblaze video page and reach my 100% quota in few hours.

https://www.backblaze.com/b2/b2-transactions-price.html

**Comment by DanielnetoDotCom** [comment]
I think it is related with this https://github.com/DanielnetoDotCom/YouPHPTube/issues/1052

I will release some news about it today

**Comment by DanielnetoDotCom** [comment]
Can you please download the plugin again. I made so many updates that may fix it.
