### ISSUE TITLE
WARN: videojs.plugin() is deprecated; use videojs.registerPlugin()

### ISSUE THREAD

**Issue by Edtigoza** [DanielnetoDotCom/YouPHPTube#1041]
HI
I have a waning message in google console
WARN: videojs.plugin() is deprecated; use videojs.registerPlugin()

![image](https://user-images.githubusercontent.com/17506671/45221131-831adf80-b27e-11e8-93e2-6063b32b1b37.png)

the platform Younphptube works well, I have no problems, I suppose it is not serious

**Comment by DanielnetoDotCom** [comment]
yes, dont worry, it is just a warning.
