### ISSUE TITLE
the media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by aarna63** [DanielnetoDotCom/YouPHPTube#1042]
Hi,

I had installed and configured YOUPHPTUBE with encoder and it was running fine. Yesterday I bought the plugin Blackblaze.com B2 and started to upload few videos. Configured it and it started the upload and also it synchronized with the blackblaze account.

Now when I start playing the video on the youphptube, the videos are not playing.

I am getting the below message on the player.

the media could not be loaded, either because the server or network failed or because the format is not supported.

Kindly help on priority.

**Comment by DanielnetoDotCom** [comment]
Hi, is not working the old videos or the new videos?

FYI only the new videos will go to the B2.

Also I just release an update for this plugin, you may want to get it.

I allow you to use private buckets
