### ISSUE TITLE
Your configurations has NOT been updated!

### ISSUE THREAD

**Issue by idealsud** [DanielnetoDotCom/YouPHPTube#1043]
I still don't understand why i can't save modification.
Same issue when i'm trying to change user category... i'm stuck with PROCESSING window.
Is it about www-data rights ?

Thanks for your help friend

**Comment by DanielnetoDotCom** [comment]
Usually, when I see this error it is regarding permissions.

**Comment by idealsud** [comment]
You talk about linux folder permissions i presume ?
Which folders need permissions ? www-data ? root ?
Thanks Daniel

**Comment by idealsud** [comment]
![capture d ecran 2018-09-07 a 21 44 59](https://user-images.githubusercontent.com/969160/45240041-93b37000-b2e7-11e8-99ee-3bffeaa09a0c.png)

I just wanted to add the 4th category to this user and it's fstuck on processing.
I don't understand what i have to change to make it work.

**Comment by DanielnetoDotCom** [comment]
here: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by idealsud** [comment]
Prepare failed: (1054) Unknown column 'canViewChart' in 'field list'

**Comment by DanielnetoDotCom** [comment]
I guess, maybe you skip some update, probably ver 5.7

you can not skip any update

check this https://github.com/DanielnetoDotCom/YouPHPTube/issues/878

and this https://github.com/DanielnetoDotCom/YouPHPTube/issues/619

**Comment by idealsud** [comment]
ok i didn't know i have to update every version.
Where can i find previous version, i use Git Pull method here : https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

Thanks
