### ISSUE TITLE
Server resource usage..

### ISSUE THREAD

**Issue by inferno-prime** [DanielnetoDotCom/YouPHPTube#1044]
I have a question about the amount of resources the encoder mite use. I am currently with Arvixe for my host and am using another video sharing script called CumulusClips and like it. But after I found yours and said it only needed ffmpeg for video conversion I want to make sure it won't strain the server since its shared. And I will not be in a hurry to convert the videos either. 

Any thoughts and thanks.

**Comment by inferno-prime** [comment]
I understand that I made sure to read everything but I just wanted to double check. 

Do I really need the Encoder ?. Is there anyway I could just convert the file myself then upload with a thumbnail ?.

**Comment by DanielnetoDotCom** [comment]
Please check this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/About-Video-Upload

**Comment by DanielnetoDotCom** [comment]
Maybe this 

![image](https://user-images.githubusercontent.com/18009293/45489926-24e97300-b73c-11e8-8ade-7a047387478b.png)

**Comment by inferno-prime** [comment]
You have been amazingly helpful and thank you for that. I have a few more questions if thats alright.
 
1.From what the page you gave to me about uploading videos I see that there is an option to upload video without encoding is this true ?

2. I also read the area about the ram memory. I will only be uploading a max of 500mb files if even that I will include the server specs if this helps.

Specs:Dual Quad Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz 32GB of DDR3 RAM

Mind you I am sharing this.

Again thanks you have been a big help.

**Comment by DanielnetoDotCom** [comment]
> 1.From what the page you gave to me about uploading videos I see that there is an option to upload video without encoding is this true ?

Yes, if it is a MP4 file you can

> 2. I also read the area about the ram memory. I will only be uploading a max of 500mb files if even that I will include the server specs if this helps

I have the same specs on my encoder site. should work similar

**Comment by inferno-prime** [comment]
Just wanted to again say a big thanks for all you help. 

I have another question. Is there anyway to organize the videos when in the ftp instead of just a folder with a bunch of videos with random numbers ?

**Comment by DanielnetoDotCom** [comment]
Sorry, I dont understand your question.

**Comment by inferno-prime** [comment]
I mean when the video is uploaded there is a folder called videos on the ftp where the videos are stored. 

I just wanted to know if I could create folders with specific names and have the videos I want stored in those folders.

**Comment by DanielnetoDotCom** [comment]
Sorry, the default video directory is videos

**Comment by inferno-prime** [comment]
No problem. A few more things popped up.

1.Where can I find the theme files for the layout and such.

2.Do I need all the folders like the Docker folder ?.

**Comment by DanielnetoDotCom** [comment]
> 1.Where can I find the theme files for the layout and such.

If you want to copy and Edit the Gallery plugin to create a new plugin and customize the front end layout

> 2.Do I need all the folders like the Docker folder ?.

If you dont use Docker, I think you can remove it

**Comment by inferno-prime** [comment]
1. I just want to know where all the theme files are for the entire site.

2.What other files can I delete that I do not need.

**Comment by DanielnetoDotCom** [comment]
To allow upload other formats, you will need to change the PHP code.

I don't know where to change, you will need to find out.

But probably you will not be able to play videos in other formats on the browser.

**Comment by inferno-prime** [comment]
The only reason I ask is because you tube has also introduced the playback of Webm & the VP8-9 codec that goes with it. You will notice it if you right click on the flash window and go to stats for nerds. 

But its no problem I still want to say a big thanks that you have been more helpful then any of the other video sharing script forums.

PS I would also like to ask if you plan on adding anymore features to this script for free or will I have to pay for them.

**Comment by DanielnetoDotCom** [comment]
Hi

We will be always adding new features on it, some will be free and some will be commercial.

We will never stop :)

**Comment by inferno-prime** [comment]
I have another question. Before you click on a video to go to the watch it page there is a red description box to click. I would like to adjust the the text size + How to remove it.

This is for in the event I need to do something.

Thanks.

**Comment by DanielnetoDotCom** [comment]
what red description?
