### ISSUE TITLE
Facebook Video Thumbnails

### ISSUE THREAD

**Issue by KenRHill** [DanielnetoDotCom/YouPHPTube#1045]
Awhile back I added in some metatags to /view/index.php so that Facebook would pick up a custom site thumbnail image.  I am not sure what happened, but when I try to share a video to Facebook, the video thumbnail is stripped away and replaced by that image instead, so I am sure the problem lies somewhere in there.

What I am trying to accomplish is that I am trying to make it so when people post the link to the website, it will show the custom thumbnail image I have for the site, but if people share a video from the site I want it to use the video thumbnail image for that video instead.  

What controls each video thumbnail that is displayed to Facebook when sharing videos?  
I notice that on the demo site for YouPHPTube, the function seems to work correctly, because it is showing the image of the video thumnail.
 
Please see photos for reference on what is happening or visit the URL.  Can you lend a suggestion on how I might fix this?  Any help is extremely apperciated.  My site URL is https://www.videorefuge.com

![sharingthumb2](https://user-images.githubusercontent.com/37643777/45259346-75994e80-b37f-11e8-8a71-9b529c2f52f4.jpg)

![sharingthumb](https://user-images.githubusercontent.com/37643777/45259347-77fba880-b37f-11e8-9080-014492afb1fa.jpg)

**Comment by DanielnetoDotCom** [comment]
We use the default metatags for most of social medias.

we use the video poster as the main image.

I am not sure what is facebook considering related to the image, I cant help you with that.

**Comment by KenRHill** [comment]
I reverted back to the default og metatags.  It looks like the og metatags that control the video thumbnail display are located in the modeYoutube.php file.  If I share a video by using the share button the correct thumbnail is generated with the default metatags.

I am curious if there is a way that I can put some form of custom og metatags some place where if somebody types in just the website root URL on a social media platform that it will pull a specific image, but still make it possible for the social media platform to pull the video thumbs when sharing a video URL.

**Comment by DanielnetoDotCom** [comment]
Try on the head code 

![image](https://user-images.githubusercontent.com/18009293/45374226-d31fdc00-b5c7-11e8-918b-7f13afd952ce.png)
