### ISSUE TITLE
Video.JS Error

### ISSUE THREAD

**Issue by pjaxed** [DanielnetoDotCom/YouPHPTube#1048]
Hi Daniel.  Great work you are doing here. I am trying to set up a local video streamer.  Video upload and play fine.  The challenges is with streaming.  All ports are open, yet I cannot open the stream.  The stats page display the stream details, but I cannot open the live view on port 444.  I am only viewing over http, not https.  Using the Chrome dev tools I fould 2 error which I do not knoiw how to resolve.  Are you able to give direction? 
![image](https://user-images.githubusercontent.com/43064900/45263647-a2a43a80-b42d-11e8-94b7-80cb5e3084f8.png)

**Comment by DanielnetoDotCom** [comment]
if yous Livestream (Nginx) is http, your Streamer (Apache) must be http as well

**Comment by pjaxed** [comment]
All working now.  Thank you for your assistance. Just purchased the send recorded to encoder plug in.
