### ISSUE TITLE
admin login name

### ISSUE THREAD

**Issue by janusz66** [DanielnetoDotCom/YouPHPTube#1049]
I installed the youphptube on shared hosting service. All went good except for the admin user name. The installer never asked me for username only for password. Is ther default user name for admin?

**Comment by janusz66** [comment]
Well, I use default for Linux "root" and now stuck in "processing". What I am doing wrong?. The shared host  is tmdhosting where I have running the Clipbucket.

**Comment by DanielnetoDotCom** [comment]
@janusz66 yes the default username is admin
