### ISSUE TITLE
I made a docker image for YouPHPTube V4.0

### ISSUE THREAD

**Issue by leejoneshane** [DanielnetoDotCom/YouPHPTube#105]
Maybe someone is interested.
https://hub.docker.com/r/leejoneshane/youphptube/

**Comment by DanielnetoDotCom** [comment]
This is great, thanks.
If I can help you in something, please let me know

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
