### ISSUE TITLE
Too Slow while running the video

### ISSUE THREAD

**Issue by aarna63** [DanielnetoDotCom/YouPHPTube#1052]
Hi, 

I have attached the BlackBlaze with my site and all the files are now being uploaded to the Blackblaze storage.

The problem I am facing is, whenever, we are trying to play a video, it does not start immediately, it takes few seconds to retrieve and then the video pages gets open and the video gets played.

The slow performance is hampering us a lot.

Kindly let us know how to get this resolved.

**Comment by DanielnetoDotCom** [comment]
Just to confirm 

Was not like that when the bucket was public right?

I guess it is because now we are requesting an access token to B2 before play the video .

I have some idea what to do.

I will cache that token , so we will no longer need to request it Everytime .

I will release it today and I will ping you here when it is done to download it again

**Comment by DanielnetoDotCom** [comment]
Can you please download the plugin again. I made so many updates that may fix it.

**Comment by DanielnetoDotCom** [comment]
@aarna63 does it work fine?

**Comment by aarna63** [comment]
I installed the new plugin, but it is not working properly.
I added the plugin and tried to upload a video, the video is uploading to the bucket but I am not able to play. When I try to see my videos panel, I am not able to view any videos there.

When I switch off the plugin, then I am able to view the list of video list.

Kindly get this resolved.

**Comment by DanielnetoDotCom** [comment]
Sure I will do my best to fix it.

can you please check your error log file?

if you want I can do some tests with you here or if you prefer to share your server credentials with me I will try to check direct into your server what is the problem.

**Comment by aarna63** [comment]
Kindly get this checked at your end and let me know.

**Comment by DanielnetoDotCom** [comment]
on my end, it works fine. I made some tests and it is faster now.

I guess it may be something regarding to the /tmp dir writing permissions, can you please check it?

**Comment by aarna63** [comment]
can you specify me the complete path of the tmp file

**Comment by DanielnetoDotCom** [comment]
That is not a hardcoded path, it is a PHP variable, that is why I need you to check your log file. the error should be there

please delete your log file, try to see the videos page and share the log here https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by DanielnetoDotCom** [comment]
developer@youphptube.com

**Comment by aarna63** [comment]
Have shared the relevant detail on the email.

**Comment by jeffvdo** [comment]
Thanks your update. But the issue is still here. The transactions used up over 2500 times in my 10-15mins testing.

May I suggest that to add something like encryption the mp4 URL instead of token?

PS. Just give u some idea. Maybe it does not work. :)

**Comment by DanielnetoDotCom** [comment]
Hi, are you sure you got the latest plugin version?

not there is a cache for the download request, it will be requested only once every 12 hours (default value)

**Comment by aarna63** [comment]
Still the streaming is slow compared to the videos uploaded on the server folder.

**Comment by DanielnetoDotCom** [comment]
Sorry to hear that, but now I think is a problem on the BackBlaze connection.

the videos on your site are played directly to backblaze host.

you may try to setup a CDN on backblaze to have your content fast delivered.
