### ISSUE TITLE
Disable_youtubeupload

### ISSUE THREAD

**Issue by charliedaps1** [DanielnetoDotCom/YouPHPTube#1053]
Hello,

I modified the file configuration.php line 267 to remove the button Upload to Youtube in the page mvideos but it does not work.

`    function setDisable_youtubeupload($disable_youtubeupload) {
        $this->disable_youtubeupload = ($disable_youtubeupload == 'true' || $disable_youtubeupload == '1') ? 1 : 0;`

Do you have an idea
Thank you

**Comment by DanielnetoDotCom** [comment]
Try the CustomizeAdvanced plugin 
![imagem](https://user-images.githubusercontent.com/18009293/45300740-911e6980-b4e5-11e8-8305-459de6d97201.png)

**Comment by charliedaps1** [comment]
Thank you for your answer but it does not change anything.

This is the fa fa-upload button that I would like to remove.

Thank you

**Comment by DanielnetoDotCom** [comment]
it supposes to change, make sure your plugin is enabled.

**Comment by charliedaps1** [comment]
Always on the screen :( 

![capture 001](https://user-images.githubusercontent.com/43135969/45302617-115bc380-b514-11e8-85ce-c5c97d5a8617.PNG)

Do you think I have to put the code of configuration.php as originally

Thanks for your help.

**Comment by DanielnetoDotCom** [comment]
Hoo I see, go to site configurations

![imagem](https://user-images.githubusercontent.com/18009293/45302908-e4df8180-b4ea-11e8-879e-cf8b53606235.png)

**Comment by DanielnetoDotCom** [comment]
Check your log file and permissions.

**Comment by charliedaps1** [comment]
How do we that ?
Sorry but the vps I do not know much.

**Comment by DanielnetoDotCom** [comment]
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by charliedaps1** [comment]
Great.  Thanks a lot.

**Comment by charliedaps1** [comment]
I find this for disable youtube

'04:32:49 America/New_York] PHP Fatal error:  Cannot redeclare Configuration::setDisable_youtubeupload() in /var/www/html/YouPHPTube/objects/configuration.php on line 267'

I understend why.
In the file the line is true.

function setDisable_youtubeupload($disable_youtubeupload) { $this->disable_youtubeupload = ($disable_youtubeupload == 'true' || $disable_youtubeupload == '1') ? 1 : 0;

But no idee for the problem to change the "Authenticated users can upload videos"

Thanks

**Comment by charliedaps1** [comment]
Is there way to go in the sql database to go change Authenticated users can upload videos ?

Thanks

**Comment by charliedaps1** [comment]
I have just install phpmyadmin but i have

 #1045 - Access denied for user 'admin'@'localhost' (using password: YES)

Thanks for your help

**Comment by DanielnetoDotCom** [comment]
Great

**Comment by charliedaps1** [comment]
Not great.  I can't access.

**Comment by DanielnetoDotCom** [comment]
All database modification I do, I do using command line.

You may be able to find how to do it on google.

**Comment by charliedaps1** [comment]
It's ok.  Just a problem in one file.

On more question.  

I see in My videos the possibility to drag and drop files (vidéo files) but i find not the solution to do that.

Thanks

**Comment by charliedaps1** [comment]
It's OK it's import the mp4 file.

I have this option ;)
