### ISSUE TITLE
processing

### ISSUE THREAD

**Issue by janusz66** [DanielnetoDotCom/YouPHPTube#1054]
I wipe out old installation and reinstall again. Log in and all what I get is blue bar moving and " processing".
What I am doing wrong?. Thank you

**Comment by DanielnetoDotCom** [comment]
check the log file please

**Comment by janusz66** [comment]
Could you please tell me what log file?. My installation is http://myfunnyvideos.net/tube
I have Clipbacket running at /clip and works well for now, but I am limited to mp4 only that get converted.

**Comment by DanielnetoDotCom** [comment]
This log file https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube
