### ISSUE TITLE
encoding

### ISSUE THREAD

**Issue by janusz66** [DanielnetoDotCom/YouPHPTube#1055]
Just a question. I was able to upload one video 13Mb in mp4. How long supposed to be encoding. 10min and still encoding. Thank you.

**Comment by DanielnetoDotCom** [comment]
It depends of your hardware

**Comment by janusz66** [comment]
I have the some hardware  for my web site as with Clipbucket and too less than min to be able to play.
Please, do not get me wrong. I do not want to glorify the clipbucke as I am trying to get away from it. 
What I am doing wrong that take long time to encode?. Something wrong with my settings,permissions? .
Thank you.

**Comment by DanielnetoDotCom** [comment]
you can use direct upload if you want do use your MP4 file without encode.

Encoder generate 3 different resolutions and extract images.

**Comment by janusz66** [comment]
Is that under import local videos? If that is the link than that is what I did. I choose a file from my hd.
Did I do the "wrong way". I can not find a menu for any other way to upload. Thank you

**Comment by DanielnetoDotCom** [comment]
Please take a look on this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/About-Video-Upload
