### ISSUE TITLE
Video problem

### ISSUE THREAD

**Issue by Nisarg22** [DanielnetoDotCom/YouPHPTube#1056]
![image](https://user-images.githubusercontent.com/39002772/45334953-cb960e00-b59a-11e8-9052-524d62bc1b7b.png)
this comes after i uploaded video from encoder and videos which are not showing time are not able to play
i have checked in encoder and they are uploaded and been removed from que in encoder

**Comment by DanielnetoDotCom** [comment]
Hi, I saq a large video from your site on public encoder. it was over 1 GB after encoded. that is why it was not transfered and complete

**Comment by DanielnetoDotCom** [comment]
The encoder will always need FFMPEG.
