### ISSUE TITLE
Bulk request for thumbnails

### ISSUE THREAD

**Issue by AsaTyr2018** [DanielnetoDotCom/YouPHPTube#1057]
Good day,
i Uploaded a lot of Videos. but for some reasons some of it didn´t create the thumbs on upload.
now i need to request file after file again.
is there a way to get this as bulk action?

**Comment by DanielnetoDotCom** [comment]
If you have the MP4ThumbsAndGif you can request the image only

![image](https://user-images.githubusercontent.com/18009293/45374074-73293580-b5c7-11e8-96b6-4312b7b2a8c4.png)

**Comment by AsaTyr2018** [comment]
Good day,
Yes i allready got it. but there are around 80 videos thst didn‘t get one.

A bulk „request“ button would be really great =)

Mit Freundlichem Gruß

Hauke Lenz
Administrator
Lenz-Services
________________________________

**Comment by DanielnetoDotCom** [comment]
I see, maybe we will improve it in the future
