### ISSUE TITLE
Encoder Installation Issues

### ISSUE THREAD

**Issue by Teen287** [DanielnetoDotCom/YouPHPTube#1058]
I have installed the encoder for my website, so I didnt have to use the public encoder, and the installation was successful, but when I try to login to the encoder, it states that my username and password CANNOT be blank.

In all reality, I HAVE entered my username and password, along with the  Streamer site information, and it keeps telling me that my user name and password CANNOT be blank. 

I dont uderstand why it doesnt see that I am entering my username and password. Any ideas?

**Comment by DanielnetoDotCom** [comment]
I am not sure why. I have never seen this error.

can you please check your log file?

also check if there is an JS error
