### ISSUE TITLE
ID facebook

### ISSUE THREAD

**Issue by charliedaps1** [DanielnetoDotCom/YouPHPTube#1060]
Hello,

I activated the login by facebook?
It must indicate id and key.

I do not understand how and where to find this information.

Thank you in advance for your help.

Regards

Dimitri

**Comment by ChrisSlS** [comment]
![get](https://user-images.githubusercontent.com/37787071/45355896-f5166000-b5c1-11e8-862d-0b26d7b67904.png)

Get Facebook ID and Key : https://developers.facebook.com/apps

**Comment by charliedaps1** [comment]
Thank you for your answer.

I already have a facebook account. Do I need to create one specifically for development?

I do not understand how it works.

Thank you

**Comment by ChrisSlS** [comment]
Just follow the link. No need to do another one, use your current account.

**Comment by DanielnetoDotCom** [comment]
Check this https://tutorials.youphptube.com/video/enable-facebook-login-and-making-a-video-private

**Comment by charliedaps1** [comment]
Thanks you
