### ISSUE TITLE
Send mail to registration

### ISSUE THREAD

**Issue by charliedaps1** [DanielnetoDotCom/YouPHPTube#1061]
Hello,

Is it possible that an email is sent when a person registers on the site so as to check his email directly?

Thank you

Regards

Dimitri

**Comment by ChrisSlS** [comment]
![get2](https://user-images.githubusercontent.com/37787071/45356225-f5fbc180-b5c2-11e8-9a6a-a4702e8a4929.png)

**Comment by ChrisSlS** [comment]
plugins--->CustomizeAdvanced :
![get2](https://user-images.githubusercontent.com/37787071/45356234-00b65680-b5c3-11e8-9c9c-af9ac06c9526.png)

Strangely, on my side this does not work, no email verification is sent and the user directly connected.

**Comment by charliedaps1** [comment]
Thanks for your anwser.  I have the same problem.  Connection possible and no mail.

**Comment by Criptos** [comment]
You want to send the verification email at the moment the user registers?

**Comment by charliedaps1** [comment]
Hello criptos,

YES, at this moment.

**Comment by DanielnetoDotCom** [comment]
@Criptos has already send us this good update
