### ISSUE TITLE
Upload notification

### ISSUE THREAD

**Issue by weesnaw1** [DanielnetoDotCom/YouPHPTube#1064]
Is there a setting for notificAtion for every upload?

Yes I want an email notification for each and every upload reguardless if user.

Thanks!

**Comment by mikweb2017** [comment]
for example, you can do it with RSS feeds and IfTTT for each video upload you receive an e-mail

**Comment by DanielnetoDotCom** [comment]
what about this plugin?

![image](https://user-images.githubusercontent.com/18009293/45425314-56e0d380-b66f-11e8-9d98-00018488e28a.png)

**Comment by weesnaw1** [comment]
I cannot find the description for the plugin...
Link?

**Comment by DanielnetoDotCom** [comment]
What do you mean "description for the plugin"?

We dont have a help wiki yet
