### ISSUE TITLE
Problem with mail

### ISSUE THREAD

**Issue by charliedaps1** [DanielnetoDotCom/YouPHPTube#1065]
In the majority of cases, I have problems with emails.

Some do not arrive others.

and here is the message that I have while the mails are set on a domain name and not gmail.

I receive
"Your IP: XXX : Your domain gmail.com is not allowed in header From"

And in any case, the contact form does not work while the site indicates that the message is sent

Thanks for your help

**Comment by DanielnetoDotCom** [comment]
Try to google for that, I cant reproduce this error.

**Comment by charliedaps1** [comment]
In the forumlaire contact or anywhere, as soon as we indicate a gmail address, this is the message.

"Your IP: XXX : Your domain gmail.com is not allowed in header From"


no problem with other addresses that are not gmail.

**Comment by DanielnetoDotCom** [comment]
Sorry, did you find a solution on google?

**Comment by charliedaps1** [comment]
No I did not find anything but it seems that it is an IP problem as it is not the same between the VPS and my hosting that manages the mail.
Some DNS changes and obviously it's better.

**Comment by Criptos** [comment]
I belive that is a relay domain issue, the VPS which hosts  the email, cant send email on behalf of gmail (which is good).... 
 
Have you tried to send an email using a valid email from mail server?
