### ISSUE TITLE
Stuck by "Processing"

### ISSUE THREAD

**Issue by VictorLi0213** [DanielnetoDotCom/YouPHPTube#1066]
Here is my website: https://varomy.com/
Whenever I make some change, such as changing the username or installing a plugin, it keeps saying "Processing" for a long time.
What should I do?
Thanks!

**Comment by DanielnetoDotCom** [comment]
Check your log file for errors

**Comment by VictorLi0213** [comment]
Do you mean this: https://varomy.com/videos/youphptube.log

**Comment by DanielnetoDotCom** [comment]
Do you know how to access your database?

You need to make your Customize plugin inactive (Direct into the database)

![image](https://user-images.githubusercontent.com/18009293/45429664-1fc3ef80-b67a-11e8-98cc-4aa3a9781535.png)

then install the tables before enable it

**Comment by VictorLi0213** [comment]
Oh I see. Thanks!
And how about I cannot logging into my website where I am stuck with "Processing"?

**Comment by DanielnetoDotCom** [comment]
It should be fixed after you fix the plugin

**Comment by VictorLi0213** [comment]
Ok, thank you so much!
