### ISSUE TITLE
CloneSite Error

### ISSUE THREAD

**Issue by siniztr** [DanielnetoDotCom/YouPHPTube#1067]
I currently have two sites set up. Server1 which is my dev site, and server2 which is now going to be the live site. I enabled CloneSite on both sites, and clicked on Install Tables on both. On server2 I then went to Edit Parameters and added the address for server1, following the instructions by https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Clone-Site-Plugin.

Now done, on server2 I click on Clone Now. I get two screens, one is a big red X and a message: Sorry Clone Server Unknow Error. Second screen has the following lines:
Clone: Clone Start
Clone (1 of 7): Asking the Server the database and the files
Clone: Server Unknow ERROR.

Will add screenshots.
![youphptube clonesite error](https://user-images.githubusercontent.com/22732606/45452817-4e27e600-b6df-11e8-8c49-b3824279e532.jpg)

**Comment by siniztr** [comment]
While going through the Firefox inspector, I did come across these errors:
![errors](https://user-images.githubusercontent.com/22732606/45486232-a8b25800-b75a-11e8-81bd-86aeda24fa43.jpg)

**Comment by DanielnetoDotCom** [comment]
try to check the log file from both sites.

**Comment by siniztr** [comment]
Ok indeed on the master side I am getting the following error
[master_server_error.txt](https://github.com/DanielnetoDotCom/YouPHPTube/files/2379818/master_server_error.txt)
I will have a look at the database to see if the tables were installed correctly, but I did tell the master and the slave servers to install tables.

**Comment by siniztr** [comment]
Both master and slave servers have the tables, but seem to be empty on both. Is that correct?
![master server](https://user-images.githubusercontent.com/22732606/45496634-32235380-b776-11e8-8b73-1fe366a9c98a.jpg)
![slave server](https://user-images.githubusercontent.com/22732606/45496635-32235380-b776-11e8-9077-c7437c31e07c.jpg)
And no, they are not the same screenshot, they are actually from two different instances of phpMyAdmin

**Comment by siniztr** [comment]
I don't know what happened now, but suddenly the master server is no longer showing up, and I am getting:
[13-Sep-2018 16:52:53 Europe/Amsterdam] PHP Fatal error:  Class 'ObjectYPT' not found in /var/www/html/objects/plugin.php on line 8
I have a few hundred of these, pretty much once a minute for the last two hours.

**Comment by siniztr** [comment]
OK got that fixed. But still having the same issue as above.

**Comment by DanielnetoDotCom** [comment]
About :  PHP Fatal error: Class 'ObjectYPT' 
Looks like you have an old installation somewhere or you did not update your files properly


About  Prepare failed: (1146) Table 'youtube22.clone_SitesAllowed'
Looks like you didn't install the tables on the clone plugin

![image](https://user-images.githubusercontent.com/18009293/45506918-0cdb1900-b767-11e8-806e-0d12e4ab4c7b.png)

**Comment by siniztr** [comment]
I did install the tables on both sites, but I updated the master site after installing the tables. What fixed it for me is going into phpMyAdmin, deleting the SitesAllowed table, and then in the plugin screen on the master server clicking on Install Tables again. Once I did those steps, the site cloned just fine. I was successful in cloning the site. Thank you for your help.
