### ISSUE TITLE
Live Streaming

### ISSUE THREAD

**Issue by louisyssel** [DanielnetoDotCom/YouPHPTube#1068]
Hi there,

I have the full YouPHPTube installed and working 100%, however, I need to get a live stream into the server for our church who phoned me in a panic just now and they have to stream an event tonight.

I have a Matrox Maevex 6150 Encoder with 4 X HDMI inputs and IP output.

Is there a step by step guide to get a live stream into the server for people to connect and watch.

I am really sorry this is at such short notice, I am also trying to assist them.

Thank you kindly!

**Comment by siniztr** [comment]
I am a user, just like you, not a developer or someone from the youPHPtube, so I am just answering from my perspective.
If your encoder can send directly to a RTMP server, then you will need the website for the stream and a stream key. These you enter into the encoder and enable the stream. 
Or you will need a software to send the stream to the website. There is free software for this, think on [OBS](https://obsproject.com/) for example. With OBS you need to set up the stream (you will need the link for the RTMP server and a streaming key) and then start the stream, which will then live stream to the site if it is configured properly for live streaming with an RTMP server. 

Hope this helps.

**Comment by louisyssel** [comment]
Thanks for wanting to help, but this is not my problem. My encoder already sends out the RTMP stream to the URL. The problem seems to be that the Streaming plugin on my YouPHPTube server is not working correctly. The host is not even listening on port 1935. So I need to get the server working properly for streaming, and everything else works on my installation, so I am very cautious to not break something.

**Comment by louisyssel** [comment]
No I do not, that is what I am worried about, as the rest of the services are all running through HTTPD. I guess the question is: Is it safe to follow this tutorial on my existing very nicely working system?

**Comment by louisyssel** [comment]
And these instructions is for Ubuntu, while my server is running on Centos 7

**Comment by DanielnetoDotCom** [comment]
you will need a RTMP server to be able to livestream.

I always recommend Ubuntu, you can also install any RTMP server in other server and use Livelinks to make it appear in your page

**Comment by louisyssel** [comment]
Which one do you recommend as a straight RTMP server that is quick and simple, as I am running out of time.

**Comment by DanielnetoDotCom** [comment]
I would recommend you to use NGINX because it is free, but you can use wowza as well.

But the safest way is to follow the default installation with Streamer and nginx on the same server.

We also offer an server + installation here https://www.youphptube.com/services

We can deploy it in couple hours

**Comment by louisyssel** [comment]
It would help a lot, my only problem is that I am doing this as an urgent favour for the church, and I do not really have too much budget to spend on services here. I would ultimately want the YouPHPTube service complete and working within itself rather than with other elements.

**Comment by louisyssel** [comment]
And how much would you charge me to just add the streaming part, as the rest is working fine already?

**Comment by DanielnetoDotCom** [comment]
I dont think you can properly compile the NGINX in a centos.

I guess you will need another server with Ubuntu

**Comment by DanielnetoDotCom** [comment]
As I mentioned above, the safest will be to put the streamer and the Nginx on the same server.

I am not sure how will you work with them separately.

It should work, but it is highly tested all on the same server.

**Comment by louisyssel** [comment]
If I build a new Ubuntu machine from scratch and provide you with the clean machine and SSH access, how long will it take and how much will it cost to get the YouPHPTube set up with streamer and all up and running? I need to be there in two hours to commence testing.

**Comment by DanielnetoDotCom** [comment]
I can do it for 70 USD, and it also takes 2 hours.

You will also need a domain or subdomain pointing to the server.

**Comment by louisyssel** [comment]
OK, I am busy building the machine now, I will send you the credentials as soon as the machine is up in about 15 minutes. Please send the payment instructions, so I can get it done in the mean time. Is Ubuntu 16.04 fine, or do you need bionix (18.04)

**Comment by DanielnetoDotCom** [comment]
use ubuntu 16 , get the full installation here https://www.youphptube.com/services 

and then email me the credential developer@youphptube.com

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/45492906-ddff7b80-b743-11e8-8c36-5c9c66f2d983.png)

**Comment by louisyssel** [comment]
All done, payment made and credentials emailed. The server is ready for installation as per the email.

Thanks

**Comment by louisyssel** [comment]
Daniel, did you get everything, and are you OK?

**Comment by DanielnetoDotCom** [comment]
Yes I am ok.

BTW how is this vps hardware ?


Em qui, 13 de set de 2018 12:16, Louis Yssel <notifications@github.com>
escreveu:

**Comment by louisyssel** [comment]
It is a virtual environment on VMWare, but it has 16 vCPU and 32GB RAM with 200GB disk space

**Comment by louisyssel** [comment]
My previous YouPHPTuve infrastructure ran on the same platform, but on Centos 7

**Comment by louisyssel** [comment]
I can see that the server is running, but no information about the installation, no email or anything. Please urgently provide credentials for database, web access and other as well as a status on the installation please.

I have had no update, and this was extremely urgent.

**Comment by DanielnetoDotCom** [comment]
Please check your email

**Comment by louisyssel** [comment]
I have no email from you. not in Junkmail either. Did you respond to one of my previous messages?

**Comment by DanielnetoDotCom** [comment]
I already answer you twice .and sent you many messages regarding the server 
Yes I answer you on your preview messages 

I will put the answer here, just make sure you change the admin password 

The user is admin and the pass is 123 


You need to open some ports on your server to make nginx works, ports  8080, 444 and 1935

**Comment by louisyssel** [comment]
Thanks, I do not know why the emails are not coming through. Thanks for this, I will change the passwords now.

**Comment by DanielnetoDotCom** [comment]
Ok

Thanks

**Comment by louisyssel** [comment]
Daniel, I have now opened the required ports on the firewall, and when I restart the machine, everything starts up, but then nginx fails after about a minute, and I am not getting the stream up.

**Comment by louisyssel** [comment]
Also nothing in the nginx logs.
Console output on status is:
Sep 14 07:35:51 streams polkitd(authority=local)[1261]: Registered Authentication Agent for unix-process:1626:26006 (system bus name :1.9 [/usr/bin/pkttyagen
Sep 14 07:35:55 streams polkitd(authority=local)[1261]: Operator of unix-process:1626:26006 successfully authenticated as unix-user:streamer to gain ONE-SHOT
Sep 14 07:35:55 streams systemd[1]: Stopped A high performance web server and a reverse proxy server.
-- Subject: Unit nginx.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit nginx.service has finished shutting down.
Sep 14 07:35:55 streams systemd[1]: Starting A high performance web server and a reverse proxy server...
-- Subject: Unit nginx.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit nginx.service has begun starting up.
Sep 14 07:35:55 streams systemd[1]: nginx.service: PID file /run/nginx.pid not readable (yet?) after start: No such file or directory
Sep 14 07:37:25 streams systemd[1]: nginx.service: Start operation timed out. Terminating.
Sep 14 07:37:25 streams systemd[1]: Failed to start A high performance web server and a reverse proxy server.
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit nginx.service has failed.
-- 
-- The result is failed.
Sep 14 07:37:25 streams systemd[1]: nginx.service: Unit entered failed state.
Sep 14 07:37:25 streams systemd[1]: nginx.service: Failed with result 'timeout'.
Sep 14 07:37:25 streams polkitd(authority=local)[1261]: Unregistered Authentication Agent for unix-process:1626:26006 (system bus name :1.9, object path /org

**Comment by DanielnetoDotCom** [comment]
I will take a look in 2 hours

Em sex, 14 de set de 2018 02:40, Louis Yssel <notifications@github.com>
escreveu:

**Comment by louisyssel** [comment]
Thanks

**Comment by DanielnetoDotCom** [comment]
I just checked and looks like the ports still not opened 

https://live.uc-x.net:444/stat

http://live.uc-x.net:8080/

you should be able to access the addresses above

**Comment by louisyssel** [comment]
I am checking with the SP on the firewall

**Comment by louisyssel** [comment]
OK, Confirmed, the above links are now accessible.

**Comment by DanielnetoDotCom** [comment]
I cant access them from here

**Comment by DanielnetoDotCom** [comment]
I see, you right

I just start NGINX with sudo /usr/local/nginx/sbin/nginx

it shoud start when you reboot , for some reason does not

can you try a live stream now?

**Comment by DanielnetoDotCom** [comment]
Let me know if it works

**Comment by louisyssel** [comment]
No, I cannot seem to stream to it. When I try OBS Studio, and I use the information on the YouPHPTube Device Stream info, I get an error:
Cannot access the specified channel or Stream Key.

When I try the hardware encoder with the smae Device information, I also do not get the stream through.

**Comment by louisyssel** [comment]
OK, done

**Comment by DanielnetoDotCom** [comment]
Sorry was my bad

I guess is working now

![image](https://user-images.githubusercontent.com/18009293/45550725-1e253380-b802-11e8-93be-ed507b074cf9.png)

**Comment by louisyssel** [comment]
Daniel,

I get your stream, but when I stream, OBS now reports that it is streaming fine, but on YouPHPTube, it still shows offline, and I cannot get the media through. What do you use to stream, so I can compare parameters.

**Comment by louisyssel** [comment]
OK, OBS Streaming is now working.

The hardware encoder however only sends through audio, not video as well

**Comment by DanielnetoDotCom** [comment]
About the offline, make sure you select the  "Listed Transmition"
![image](https://user-images.githubusercontent.com/18009293/45551918-ae18ac80-b805-11e8-9dc4-4029f420a021.png)

About the audio, you may check your OBS source, I am also using OBS and the audio is fine, you can check it

**Comment by louisyssel** [comment]
I agree, my OBS also works fine, it is the hardware decoder that does not work with video, only audio. That is what confuses me.

**Comment by louisyssel** [comment]
At least now I know the platform works, I will work with the decoder and get the streams through. Thanks a lot for your help.

How do I allow users to view the live stream when they are not logged on?

**Comment by DanielnetoDotCom** [comment]
the NGINX does not decode the video, it retransmits the raw video.
try to change the parameters on OBS

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/45552386-33509100-b807-11e8-9dbb-76a59430abfa.png)

**Comment by louisyssel** [comment]
Thank you!

**Comment by pkapoor86** [comment]
Hi, 
I have set the stream for the public still shows offline, & also check the ports 444, 8080 they also not running on server, Please help what mistake i am doing
