### ISSUE TITLE
Bug on Share a video by mail

### ISSUE THREAD

**Issue by charliedaps1** [DanielnetoDotCom/YouPHPTube#1069]
Hello,

When I want to send an email to a person to share a video, it is not the email address that I indicated who receives the email but the email address of the site.

Thanks for your help.

**Comment by DanielnetoDotCom** [comment]
sorry, can you please screenshot an sample?

**Comment by charliedaps1** [comment]
![capture](https://user-images.githubusercontent.com/43135969/45493990-57ad5e80-b770-11e8-8c7f-306d188c573d.PNG)

The mail is send too the admin's email and not too the email completed by the user

**Comment by DanielnetoDotCom** [comment]
It is not clear to me what are you expecting.

the email Address is the destination.

The sender will be the site email (on site configurations menu)

**Comment by Criptos** [comment]
I think he refers that the email arrives from:

siteadmin@<mydomain>. 
 
Instead of 

usersharig@<myregisteredemail> 
 
For a start, is not convenient to 'forge' the email  of the user sending the email due to spam and relaying rules. 
 
maybe better send it from no-reply@<mydomain> ?
