### ISSUE TITLE
PHP Fatal error while loading homepage

### ISSUE THREAD

**Issue by alegiovannelli** [DanielnetoDotCom/YouPHPTube#107]
Hi,
after a new installation, the homepage is not fully loaded and the following error is reported between the logs:.

` PHP Fatal error:  Uncaught Error: Call to undefined function _() in /var/www/html/youtube/view/modeYoutube.php:427
Stack trace:
#0 /var/www/html/youtube/view/index.php(24): require()
#1 {main}
  thrown in /var/www/html/youtube/view/modeYoutube.php on line 427
`

Thank you in advance for your help.

**Comment by DanielnetoDotCom** [comment]
are you sure did you copy all files?
specially YouPHPTube/locale/function.php

**Comment by alegiovannelli** [comment]
All the files are up to date.
I have found that the problem, is that in the homepage is only displayed the last uploaded video, this only happens if I have logged in.
If I browse the home without logging in, I will see everything fine
I noticed that when logging in, the option of choosing a language is no longer displayed in the top right corner.
Thank you in advance.
![immagine](https://user-images.githubusercontent.com/29068703/30251924-c5a27890-9669-11e7-8477-9daef44f0e72.jpg)

**Comment by DanielnetoDotCom** [comment]
Your page looks fine for me

![image](https://user-images.githubusercontent.com/18009293/30274570-6d37dfb8-96d4-11e7-8ec5-a323621dbd32.png)

**Comment by alegiovannelli** [comment]
This image is when you see the site without login.
If you login with a user the error appear.

Maybe I found the error in the code.

In the file **view/modeYoutube.php** at line 427 before ("I would like to share this video with you:") there is one only placeholder _ instead of two __.

`<textarea class="form-control" name="comment" placeholder="<?php echo __("Message"); ?>"><?php **echo _**("I would like to share this video with you:"); ?> <?php echo $global['webSiteRootURL'], $catLink; ?>video/<?php echo $video['clean_title']; ?></textarea>`
                                                       
Now I can see the right site homepage with user logged in.

I hope this is useful.

Thank you.

Giovannelli Alessandro

**Comment by DanielnetoDotCom** [comment]
Really?
wow, thanks.
