### ISSUE TITLE
Live stream on YouPHPFlix

### ISSUE THREAD

**Issue by iscriptor** [DanielnetoDotCom/YouPHPTube#1070]
Hello,

Please, how can I featured live stream on YouPHPFlix plugin (home page)
/var/www/YouPHPTube/plugin/YouPHPFlix/view/firstPage.php

Regards.

**Comment by DanielnetoDotCom** [comment]
For now, we have it only on Gallery plugin

**Comment by iscriptor** [comment]
Hello,

It will easily done if little tip. 

Regards.

**Comment by DanielnetoDotCom** [comment]
I do not have a tip to easily done it.

**Comment by iscriptor** [comment]
Hello,

Thanks. We already made some customization in YouPHPFlix plugin.

Regards.

**Comment by Andiweb87** [comment]
can i see what do you made ?

**Comment by iscriptor** [comment]
I will share it as plugin in due time.

Regards.

**Comment by iscriptor** [comment]
> can i see what do you made ?

You can send me your email
