### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by jeanfrancoisvarin** [DanielnetoDotCom/YouPHPTube#1076]
Hi,

Let me explain what I'm facing.
I have some issues regarding the encoding.

When I send large batches to the encoder (roughly 200 files), I find a very strange behavior in the clean_title in the videos table.
It is getting so big that I suspect it to generate some of the error messages I receive as the field is limited.

I changed the field size to 500 and the error appeared as well but later.

Is it normal or is there any fix ?

Thanks for your answer.

Example : thormontbou-2018123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899100101102

Plus
![image](https://user-images.githubusercontent.com/43242560/45585392-cb23ad00-b8e3-11e8-94bb-435788460761.png)

and
![image](https://user-images.githubusercontent.com/43242560/45585405-02925980-b8e4-11e8-80f5-75c67aef52a9.png)

**Comment by DanielnetoDotCom** [comment]
I never saw this before.

the clean title add a number at the end automatically in case the clean title is already in use.

I don't know how is the file names you are submitting. but maybe is regarding it.

**Comment by jeanfrancoisvarin** [comment]
Hello Daniel,

What I understand is that instead of incrementing the clean_title field, the number concatenates.

After a while, the field being too short, it pops up in an error, which makes sense to me and was proven by resizing the field.

According what you say, the clean_title should be the file name ?

So what I see is that when in the Encoder page in the From File tab I type in Title, Description and choose the category, the title goes in the clean_title field, the description goes nowhere and the category is fine.

It all I can describe to you.

Thanks anyway for your quick answer.

Best regards,

Jean-François


De : YouPHPTube <notifications@github.com>
Envoyé : dimanche 16 septembre 2018 15:34
À : DanielnetoDotCom/YouPHPTube <YouPHPTube@noreply.github.com>
Cc : Jean-François Varin <jfvarin@karefil.org>; Author <author@noreply.github.com>
Objet : Re: [DanielnetoDotCom/YouPHPTube] Encoding issue (#1076)


I never saw this before.

the clean title add a number at the end automatically in case the clean title is already in use.

I don't know how is the file names you are submitting. but maybe is regarding it.

**Comment by DanielnetoDotCom** [comment]
> According what you say, the clean_title should be the file name ?

Yes, should be the filename after remove special chars

**Comment by jeanfrancoisvarin** [comment]
I can ensure you, this is not the case. 
File name is replaced by Title and instead of item number incrementation there is a incremented number concatenation.

My file names are : DJI_nnnn or 100_nnnn or 2018_09_02_12_02_48

As you can see in the result thormontbou-20181234567891011121314 : Thormontbou-2018 is the title (in put in the encoder form) and the rest is the concatenation (in this case, up to 14).

I hope it helps.

**Comment by jeanfrancoisvarin** [comment]
I did some other tests by downloading a Youtube video and everything is fine.
I also tried to make some changes in the Encoder.php files adding 'XYZ' as description. and wether or not the description field is empty, it puts 'XYZ' in the description field. Which tells me that it never reaches teh $_POST['description'] line.

If it helps.
JF

    static function sendFile($file, $videos_id, $format, $encoder = null, $resolution = "") {
        global $global;
        global $sentImage;

        $obj = new stdClass();
        $obj->error = true;
        $obj->format = $format;
        $obj->file = $file;
        $obj->resolution = $resolution;
        $obj->videoDownloadedLink = $encoder->getVideoDownloadedLink();

        $duration = static::getDurationFromFile($file);
        if (empty($_POST['title'])) {
            $title = $encoder->getTitle();
        } else {
            $title = $_POST['title'];
        }
        if (empty($_POST['description'])) {
            if (!empty($obj->videoDownloadedLink)) {
                $description = $encoder->getDescriptionFromLink($obj->videoDownloadedLink);
            } else {
                $description = "XYZ";
            }
        } else {
            $description = $_POST['description'];
        }
        if (empty($_POST['categories_id'])) {
            $categories_id = 0;
        } else {
            $categories_id = $_POST['categories_id'];
        }

**Comment by DanielnetoDotCom** [comment]
I see the problem, 

it is clear now, I am sending a fix, can you please test it for me?

**Comment by jeanfrancoisvarin** [comment]
With pleasure ;-)

**Comment by DanielnetoDotCom** [comment]
Also I just send some bug fix, just in case you already update

**Comment by jeanfrancoisvarin** [comment]
Didn't receive anything yet.

I'm I normal ?

**Comment by DanielnetoDotCom** [comment]
You need to update your files https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

**Comment by jeanfrancoisvarin** [comment]
Hello Daniel, 
I just git pulled and replayed my tests.
Numbering works now fine. Description field is still empty even after filling it in the encoder form.

But, as I did some manual changes in the Encoder.php file, I recieved the "Please, commit your changes or stash them before you can merge" message and applied the procedure.

As my Encoder folder was renamed to Tube-Encode, how can I check the pull request was complete.

Thanks for your patience, I'm a bit of a newbie.

**Comment by DanielnetoDotCom** [comment]
About your manual changes you will loose them https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-Update-your-YouPHPTube#problems

**Comment by jeanfrancoisvarin** [comment]
Merci Daniel,

I followed up your how-to and it worked fine for the file numbering (could be more easy to read with a "-" after the name and before the number). But it works and that's cool.

The only remaining issue is that when you fill the description in the encoder form, it doesn't go to the description field of the database (it works when you import a Youtube video).

Many thanks in advance for your help.

JF

**Comment by DanielnetoDotCom** [comment]
@jeanfrancoisvarin I Agree with you about the "-", I just sent a fix.

Also thanks for the donation. :)

**Comment by jeanfrancoisvarin** [comment]
You're welcome. 

I hope it can help you a bit ;-)
