### ISSUE TITLE
Awesome tool for which I have a small suggestion

### ISSUE THREAD

**Issue by william-1066** [DanielnetoDotCom/YouPHPTube#108]
Absolutely loving this software which installed amazingly easily and just works.

I am using this as a tool to watch high quality videos from YouTube even though I have a very slow (0.7 Mbit/s at best) internet link.  I do see the potential of this software to make available YouTube videos to rural schools etc with very slow links.

Adding the ability to restrict the time when videos are downloaded (in my case 11pm to 7am) would be very useful.

**Comment by DanielnetoDotCom** [comment]
Thanks, you like it.
The restrict time download/encode is a great idea. it is something to do on the encoder site.
I will think about it

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
