### ISSUE TITLE
Category Headings?

### ISSUE THREAD

**Issue by KenRHill** [DanielnetoDotCom/YouPHPTube#1081]
Is there a way to display a heading in each category when a user browses to that category?  I am using the Gallery Plugin and I am trying to figure out if there is a way to have a heading that displays for each Category when a user selects that Category from the menu and browses to that categories Gallery page.

**Comment by DanielnetoDotCom** [comment]
Can you please "Photoshop" an example?

**Comment by KenRHill** [comment]
Sure.  No problem.  Thank you for the response.  

Basically with the example provided here.  If a user selects a category from the menu to browse, I am wondering if there is a way where they can be presented with the title of the category they are in dynamically based on whatever category they choose to browse to.  Sort of like a page heading as shown in this make believe example.  In this creation, the user has decided to browse the Animals category of the site. 

![categorytitles](https://user-images.githubusercontent.com/37643777/45599240-c7079600-b99c-11e8-99fa-50dfa58b2d5a.jpg)

**Comment by DanielnetoDotCom** [comment]
I see, 

this is possible to create and may be updated in the future.
