### ISSUE TITLE
plugin

### ISSUE THREAD

**Issue by jonathanpecany** [DanielnetoDotCom/YouPHPTube#1082]
So I just installed some plugins that been added on but realize it just hid all of them and than I removed them to turn them into .zips and went back to check and saw the page couldn't be found and I did this before as well and it didn't happen. What could be wrong with it. I don't feel like going into the code. And yes I have made it my own style which I like a lot and is less buggy than youtube. but that isn't it because haven't messed with it ever since.

**Comment by DanielnetoDotCom** [comment]
Sorry, I dont understand what happened.
and please take a look on it: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-To-Install-a-new-Plugin

**Comment by DanielnetoDotCom** [comment]
Did you check if your server is not removing the plugin directory or file?

The plugin is encrypted some time the server antivirus remove php encrypted files

**Comment by jonathanpecany** [comment]
I got it to work but now I don't understand one thing and that is to download the unzip app onto my server which is "sudo apt-get install unzip" but I don't know where to type it at.

**Comment by DanielnetoDotCom** [comment]
This should be typed on the ssh terminal.

this is to allow you to upload the zip file direct into your server

**Comment by jonathanpecany** [comment]
Okay then...mind helping me of why it keeps crashing or closing please?

**Comment by DanielnetoDotCom** [comment]
what is keeping crashing?

can you please check your log file?
