### ISSUE TITLE
How does email verification work?

### ISSUE THREAD

**Issue by VictorLi0213** [DanielnetoDotCom/YouPHPTube#1083]
Hi, I wonder how the email system works.
Can I let the system send the verification email to the user at the moment when he signed up?

**Comment by DanielnetoDotCom** [comment]
This function was just updated this weekend

![image](https://user-images.githubusercontent.com/18009293/45618928-d7c41480-ba4d-11e8-8997-3d377ab78e86.png)

**Comment by VictorLi0213** [comment]
Ok thank you.
