### ISSUE TITLE
Video issue

### ISSUE THREAD

**Issue by Nisarg22** [DanielnetoDotCom/YouPHPTube#1087]
![screenshot_20180917-102354](https://user-images.githubusercontent.com/39002772/45606593-077e1700-ba64-11e8-98f3-9a5fc0c9a61e.jpg)
Before user login.
![screenshot_20180917-102412](https://user-images.githubusercontent.com/39002772/45606609-28df0300-ba64-11e8-9c90-2912cbdc459b.jpg)
after user log in

**Comment by DanielnetoDotCom** [comment]
???

**Comment by Nisarg22** [comment]
Problem is my site shows videos if users log in otherwise it shows no videos or audios found

**Comment by Nisarg22** [comment]
But I don't want users should be logged in to watch I want that they can watch even without having account

**Comment by Criptos** [comment]
Are you assigning the users who uploads the video to a group?

**Comment by DanielnetoDotCom** [comment]
Looks like you dont have public videos
