### ISSUE TITLE
Facebok login

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#1088]
hi Daniel,
Faceboklogin don  t wornk anymore 
Can you Chek Why?

This  is  demo  site

![fb-login](https://user-images.githubusercontent.com/30271757/45609244-583b4300-ba57-11e8-9e91-106c154e209a.PNG)

**Comment by DanielnetoDotCom** [comment]
Thanks for notice it, I sent an update
