### ISSUE TITLE
detect of mod_rewrite issue

### ISSUE THREAD

**Issue by laweschan** [DanielnetoDotCom/YouPHPTube#109]
Hi Daniel,

   great work and I really love it, I have give it a try and here has some update for the mod_rewrite issue.

    by default Apache will use mod_php so mod_rewrite.c has been detected by the scripts, however, for other platform changes eg. mod_php vs fastcgi vs php-fpm, the script seems not fully detect and always prompt for mod_rewrite failure during installation.

   I have make some change (as base on Fedora OS), I have just update the functions.php , this will use shell command to detect the loaded modules as bellow

   _function modRewriteEnabled() {
    if (!function_exists('apache_get_modules')) {
        ob_start();
        #phpinfo(INFO_MODULES);
        #$contents = ob_get_contents();
        ob_end_clean();
        return (strpos(shell_exec('/usr/sbin/httpd -M'), 'rewrite_module') !== false);
        #return (strpos($contents, 'mod_rewrite') !== false);
    } else {
        return in_array('mod_rewrite', apache_get_modules());
    }
}_

   as I am not a programmer, I can only update it with my logical mind, may be it can write in much smart way but it can prove to work after changed under apache + php-fpm env. 

   I may get a new try on nginx later and hope youphptube can get much better

   thanks

Regards,
Lawes

**Comment by DanielnetoDotCom** [comment]
This is great, can u make a pull request on YouPHPTube?

**Comment by laweschan** [comment]
ok ..... any instruction ? seems a little complex to me ..

Lawes

**Comment by DanielnetoDotCom** [comment]
To be honest I do not have much experience with this either, but it is very common users to send this pull request where I accept them and automatically they are marked as contributors of this project https://github.com/DanielnetoDotCom/YouPHPTube/graphs/contributors
Take a look here to see if it helps
https://help.github.com/articles/creating-a-pull-request/

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
