### ISSUE TITLE
Changing the Mysql User

### ISSUE THREAD

**Issue by VictorLi0213** [DanielnetoDotCom/YouPHPTube#1090]
When I was installing youphptube, I used root as the user of the mysql database. Now I think that it is not safe, so I want to change it.
Do I just go to the /videos/configuration.php to change the value? Is that all I need to do or do I need to do something else?
And how about the encoder? I also want to change the user for the encoder database.
Thanks!

**Comment by Criptos** [comment]
The encoder has it's own configuration.php file and yes, you simple change the values at videos/configuration.php at your streamer and that's all...
