### ISSUE TITLE
Issue with site search

### ISSUE THREAD

**Issue by KenRHill** [DanielnetoDotCom/YouPHPTube#1092]
Hi Daniel,

I cut and paste the original search code from the navbar.php file that displays the search box at the top of the page and I moved pasted it into the index.php file in the view folder.  If I am browsing and searching from the sites /view/index.php search works as it should.  If I were to navigate to page 2 of my site gallery and try to search again from page two, the search will not yeild any results and only refreshes the main page. 

What do I need to do in order to make it search properly regardless of what page I am on if I were on page 2 or 3 or whatever?  I am totally stumped why this can't work.  If you browse over to the site at https://www.videorefuge.com and search from index.php you will see it works properly and displays search results.  If you scroll down to the bottom of the landing page and click page 2 or 3 or 4 and try searching, it refreshes page one and does bring up results.  Please advise.

**Comment by KenRHill** [comment]
`<div` align="center">
`<form` class="navbar-form navbar-middle" id="searchForm" action="<?php echo `$global['webSiteRootURL'];` ?>">
`<div` class="input-group">
`<div` class="form-inline">
`<input` class="form-control" type="text" value="" name="search" placeholder="Search" style="width: `325px;">`
`<button` class="input-group-addon form-control hidden-xs" style="width: 50px;" `type="submit"><span` class="glyphicon glyphicon-search"></span></button>
`</div>`
`</div>`
`</form>`
`</div>`

**Comment by KenRHill** [comment]
I just figured it out.  For use to fix your own search try using `action="<?php` echo $_SERVER['PHP_SELF']; ?>; 
instead of `action="<?php` echo $global["webSiteRootURL']; ?>;

**Comment by DanielnetoDotCom** [comment]
Great
