### ISSUE TITLE
help with a few issues please - the title part doesn't show the image .... 

### ISSUE THREAD

**Issue by joey2354** [DanielnetoDotCom/YouPHPTube#1093]
hi ... I would like a little help please on a few issues i have.

1: the title image part of the track on the home page is missing https://i.imgur.com/HsLbT59.png

2: my plugins won't upload, i see them all in the templates but i get this error 

Customize (1).zip: SyntaxError: Unexpected token < in JSON at position 0

Warning:  exec() has been disabled for security reasons in /home/u278774143/public_html/home/objects/pluginImport.json.php on line 42

{"uploaded":false,"filename":"Customize _1_.zip","destination":"\/home\/u278774143\/public_html\/home\/plugin\/"}

thank you :)

**Comment by DanielnetoDotCom** [comment]
The correct plugin file name should be Customize.zip instead Customize (1).zip, it is important to upload it

> Warning: exec() has been disabled for security reasons in /home/u278774143/public_html/home/objects/pluginImport.json.php on line 42

Looks like you are in a shared server. your encoder will not work

**Comment by joey2354** [comment]
ok well renamed to customize and it didn't work ...  what do you mean it will not work ?

**Comment by DanielnetoDotCom** [comment]
I mean you will need resources that a shared server will not provide to you.

You need a VPS or an Ubuntu

About the plugin: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-To-Install-a-new-Plugin
