### ISSUE TITLE
Sign in page not found.

### ISSUE THREAD

**Issue by xXRobman2016Xx** [DanielnetoDotCom/YouPHPTube#1094]
I got YouPHPTube to install finally after carefully reinstalling things. But for some reason when I go to click sign in I get this.
_____________________________

Not Found
The requested URL /YouPHPTube/user/ was not found on this server.

______________________________
Is there some way I can fix this?

**Comment by Criptos** [comment]
can you tell us your domain, document root? 
check your videos/configuration.php  
Also, did you have mod_rewrite enabled at your apache?

**Comment by xXRobman2016Xx** [comment]
My domain atm is this http://104.196.115.188/MeSquareVideos

I did allow mod_rewrite

The only issue is the user part like sign in, and going into my account and such. @Criptos

**Comment by Criptos** [comment]
![image](https://user-images.githubusercontent.com/4574233/45699704-36fa5580-bb30-11e8-9aff-2d8c8a4072e6.png)
??
 
is user with out the final  /

**Comment by Criptos** [comment]
Oh sign in.. my mistak.. wait

**Comment by xXRobman2016Xx** [comment]
I'm confused. It wasn't working before

**Comment by Criptos** [comment]
![image](https://user-images.githubusercontent.com/4574233/45699831-90628480-bb30-11e8-90cb-4cdc2290da78.png)
not, everything works fine pal... 
I just added an account and logged in... 

Clean up your cache.. and disable the cache plugin meanwhile, if enabled...

**Comment by xXRobman2016Xx** [comment]
Ok

**Comment by Criptos** [comment]
did it work now?

**Comment by xXRobman2016Xx** [comment]
I never had cache enabled so idk what was going on with it.
