### ISSUE TITLE
Encoder questions

### ISSUE THREAD

**Issue by weesnaw1** [DanielnetoDotCom/YouPHPTube#1096]
1. Is it possible to not show other users encoder queues to each other?

2. Is it possible to speed up encoder? Server monitor shows minimal resources being used with queue list of over 100 videos waiting...

I imagine if 1000 users uploaded 10 videos at the same time it would take a week for them all to upload.... 

3. Plugin parameter : “videos inactive after upload”. Can we have “videos UNLISTED” instead?

**Comment by DanielnetoDotCom** [comment]
>     Is it possible to not show other users encoder queues to each other?

No, the default behavior is to show the queue to everyone 

>     Is it possible to speed up encoder? Server monitor shows minimal resources being used with queue list of over 100 videos waiting...
> I imagine if 1000 users uploaded 10 videos at the same time it would take a week for them all to upload....

the encoder will encode only one video at a time. but you can have multiple encoders (one in each server)


>     Plugin parameter : “videos inactive after upload”. Can we have “videos UNLISTED” instead?

maybe in the future

**Comment by weesnaw1** [comment]
Thanks!

Can you explain one encoder for each server?  

Currently I have the site on 1 server and the encoder on another server.

How do i add more servers just for encoder?

**Comment by DanielnetoDotCom** [comment]
take a look on it https://network.youphptube.com/

https://github.com/DanielnetoDotCom/YouPHPTube-Encoder-Network

you can handle multiple encoders with it

**Comment by timmayy** [comment]
ok so how do I install it correctly?

i read the wiki page but all it doesnt say how to install..

**Comment by DanielnetoDotCom** [comment]
yes, the network is a new feature, it is working, but still under development.
