### ISSUE TITLE
Video Ad "Skip" not working

### ISSUE THREAD

**Issue by KenRHill** [DanielnetoDotCom/YouPHPTube#1098]
Hey there again,

I am running YouPHPTube version 5.01 and I just added a test advertisment videov to the "Default" Category with a 3 second delay before the Skip Ad button appears.  No matter how many times I click Skip Ad, it will not skip and keeps playing.  

https://www.videorefuge.com/cat/default-/video/20180912-124635# 

Also providing screen capture of the ad settings.  What do you suppose I should check to see why this doesn't skip when clicked?  What file contains the codes that deal with the skip ad button?  Not sure what is happening.  Could you give it a look and let me know?  Please and thank you.

![skip](https://user-images.githubusercontent.com/37643777/45730214-4e176280-bb85-11e8-9e13-1bca71f76ac4.JPG)

**Comment by DanielnetoDotCom** [comment]
Sorry, we support only latest version.
