### ISSUE TITLE
Random video category

### ISSUE THREAD

**Issue by weesnaw1** [DanielnetoDotCom/YouPHPTube#1099]
For gallery view can we have a random video category?

**Comment by DanielnetoDotCom** [comment]
Yes, select the suggested videos 

https://github.com/DanielnetoDotCom/YouPHPTube/issues/939

**Comment by timmayy** [comment]
that is not a category. 

I want this too., I have suggested videos already 

I use gallery plugin, I want a set of videos that are random just like the " recent and most watched" sections...

**Comment by DanielnetoDotCom** [comment]
I see.

Sorry when don't have that
