### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by satube0** [DanielnetoDotCom/YouPHPTube#110]
When I have Installed This Script then shows this Problem..
Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /home/smallres/public_html/encoding/objects/include_config.php:9 Stack trace: #0 /home/smallres/public_html/encoding/objects/include_config.php(9): DateTime->__construct() #1 /home/smallres/public_html/encoding/videos/configuration.php(18): require_once('/home/smallres/...') #2 /home/smallres/public_html/encoding/view/index.php(10): require_once('/home/smallres/...') #3 {main} thrown in /home/smallres/public_html/encoding/objects/include_config.php on line 9

**Comment by DanielnetoDotCom** [comment]
This is because no timezone has set in php configuration.

Add the following line of code to top of your php.ini file

date.timezone = "US/Central"
And restart web server

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
