### ISSUE TITLE
Is live plugin works?

### ISSUE THREAD

**Issue by DarkHostDH** [DanielnetoDotCom/YouPHPTube#1100]
I tried youPHPTube 4.8 and latest.

First problem solved. I had error in my nginx front-end config.

The second problem is stream from nginx. I tried to play my RTMP stream in vlc, stream works fine. But if i add "on_publish http://bla-bla-bla/plugin/Live/on_publish.php" string to nginx config file, i get error in youphptube.log
```
[19-Sep-2018 12:24:34 Europe/Moscow] Array
(
    [scheme] => rtmp
    [host] => 192.168.138.210
    [path] => /live
)
[19-Sep-2018 12:24:34 Europe/Moscow] PHP Notice:  Undefined index: query in /var/www/YouPHPTube/plugin/Live/on_publish.php on line 15
[19-Sep-2018 12:24:34 Europe/Moscow] Array
(
)
[19-Sep-2018 12:24:34 Europe/Moscow] Stream Publish error, Password not found
[19-Sep-2018 12:24:34 Europe/Moscow] Publish denied
```
The next try
```
root@youtube.hq:/etc/nginx# curl -i http://192.168.138.210/plugin/Live/on_publish.php
HTTP/1.1 401 Unauthorized
Date: Wed, 19 Sep 2018 09:29:59 GMT
Server: Apache/2.4.18 (Ubuntu)
Set-Cookie: PHPSESSID=175tgnojghmic7i766odfm9hi1; expires=Wed, 19-Sep-2018 10:29:59 GMT; Max-Age=3600; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Vary: Accept-Encoding
Content-Length: 0
Content-Type: text/html; charset=UTF-8
```
I did not find any information in the manual/wiki about required GET parameters.

**Comment by DanielnetoDotCom** [comment]
Check this https://tutorials.youphptube.com/video/youphptube-video-stream-with-obs-and-vmix

**Comment by DarkHostDH** [comment]
I'm not using those programs. I have cam with rtsp stream and nginx as rtsp to rtmp converter.
`ffmpeg -i rtsp://webcam.example.com:8557/h264 -c copy -f flv -bsf:a aac_adtstoasc rtmp://192.168.138.210/live/5ba100e33d718?p=c6179a9f94358d1708c6f4a21758e79c`
If `on_publish` is unset, stream works fine(i used `plugin/Live/sample-player` as vhost for test). If `on_publish` is set
`on_publish http://example.com/plugin/Live/on_publish.php;`
i get error
```
[19-Sep-2018 17:18:25 Europe/Moscow] Stream Publish error, Password not found
[19-Sep-2018 17:18:25 Europe/Moscow] Publish denied
[19-Sep-2018 17:18:25 Europe/Moscow] Array
(
)

[19-Sep-2018 17:18:25 Europe/Moscow] Array
(
    [app] => live
    [flashver] => 
    [swfurl] => 
    [tcurl] => rtmp://192.168.138.210/live
    [pageurl] => 
    [addr] => 192.168.138.210
    [clientid] => 123139
    [call] => publish
    [name] => 5ba100e33d718
    [type] => live
    [p] => c6179a9f94358d1708c6f4a21758e79c
)

[19-Sep-2018 17:18:25 Europe/Moscow] stdClass Object
(
    [error] => 1
)
```
I see no one GET params is received, but only POST request contain any params. Ok, no problem. I changed line 17 to on_publish.php `elseif (!empty($_GET['p']) || !empty($_POST['p']))`, added condition `if ($_POST['p'] === $user->getPassword())` and...i got it. My stream is work!

But...it's not all. One problem is still presents.
My road map is nginx(frontend) -> apache(backend)+YouPHPTube. If i'm using domain name(request sends via nginx to apache host), site is work fine(videos,streams) but Live button does not work. I get error "You can not stream live videos". But i do not get this error if i use my backend ip instead of domain name.
My nginx config:
```
server {
  listen 80;
  server_name example.com;
  access_log off;
  location / {
    proxy_pass http://192.168.138.210:80/;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
  }
}
```
