### ISSUE TITLE
User invalid after update

### ISSUE THREAD

**Issue by Ezerbeth** [DanielnetoDotCom/YouPHPTube#1101]
Hello,

I updated to 5.9 and after logout, I couldn't login again.

What happened:
- I changed the "admin" username to another one.
- Some time passed
- I updated to 5.9

Now my username is back to admin, so obviously I couldn't login with the changed username. I'm not sure why it reverted it back, but it should probably be investigated.

Note that all videos are still properly associated, so no real harm has come out of this. However it may cause headaches to other admins upgrading.

Edit: I updated using git, then the script told me to update the DB, which I did by pressing the button. It succeeded.

**Comment by DanielnetoDotCom** [comment]
There is no reason to the script update the admin username

**Comment by Criptos** [comment]
If they have the field modified updated, then it was done within the application, meaning someone changed the user. 
 
The 5.9 script only adds a field to the plugins table, so it wasn't that.

**Comment by Ezerbeth** [comment]
You're correct. The modified field was because I had to reset everything in the admin account after the update since it had lost all privileges and became unverified.

**Comment by Criptos** [comment]
Extremely weird, I reviewd the code for the update and re do it, and wasn't able to replicate your issue

**Comment by Ezerbeth** [comment]
I have a backup. I'll restore it and try it again to see if I can replicate it. Thanks for verifying.
