### ISSUE TITLE
Permissions issues?

### ISSUE THREAD

**Issue by slthomason** [DanielnetoDotCom/YouPHPTube#1102]
Hi there,

I am running YouPHPTube on Ubuntu 16.04.5.  I have the streaming installed.  I am trying to broadcast an rtmp stream from Wirecast to my YouPHPTube server.  However, each time I do wirecast gives this error:

"Cannot publish the stream.  Verify the stream name and if you have provided any credentials/tokens that they are up to date. [-4020]"

Here is the section from the error logs during the time that it tried to hit:

2018/09/19 13:59:17 [info] 1667#0: *111 client connected '192.168.108.72'
2018/09/19 13:59:17 [info] 1667#0: *111 connect: app='live' args='p=8c728e685ddde9f7fbbc452155e29639' flashver='Wirecast/FM 1.0 (compatible; MS' swf_url='' tc_url='rtmp://192.168.111.121/live?p=8c728e685ddde9f7fbbc452155e29639' page_url='' acodecs=1026 vcodecs=128 object_encoding=0, client: 192.168.108.72, server: 0.0.0.0:1935
2018/09/19 13:59:17 [info] 1667#0: *111 createStream, client: 192.168.108.72, server: 0.0.0.0:1935
2018/09/19 13:59:17 [info] 1667#0: *111 publish: name='5ba09cf8b86f6' args='' type=LIVE silent=0, client: 192.168.108.72, server: 0.0.0.0:1935
2018/09/19 13:59:17 [info] 1667#0: *111 notify: publish '192.168.111.121/plugin/Live/on_publish.php', client: 192.168.108.72, server: 0.0.0.0:1935
2018/09/19 13:59:17 [info] 1667#0: *111 disconnect, client: 192.168.108.72, server: 0.0.0.0:1935
2018/09/19 13:59:17 [info] 1667#0: *111 deleteStream, client: 192.168.108.72, server: 0.00:1935

Here is what my config page looks like:

![image](https://user-images.githubusercontent.com/1905522/45781440-ce38d900-bc14-11e8-9645-bb91bd7ca3f2.png)
and
![image](https://user-images.githubusercontent.com/1905522/45781463-df81e580-bc14-11e8-85c6-9aa8b68c193d.png)

Help!  :p

**Comment by slthomason** [comment]
I also tried with OBS:
![image](https://user-images.githubusercontent.com/1905522/45783901-f972f680-bc1b-11e8-8854-a84536a749f7.png)

and here is the output in the logs:
2018/09/19 14:53:16 [info] 1305#0: *45 client 192.168.111.121 closed keepalive connection
2018/09/19 14:53:18 [info] 1305#0: *46 client connected '192.168.110.192'
2018/09/19 14:53:18 [info] 1305#0: *46 connect: app='live' args='p=8c728e685ddde9f7fbbc452155e29639' flashver='FMLE/3.0 (compatible; FMSc/1.0)' swf_url='rtmp://192.168.111.121/live?p=8c728e685ddde9f7fbbc452155e29639' tc_url='rtmp://192.168.111.121/live?p=8c728e685ddde9f7fbbc452155e29639' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 192.168.110.192, server: 0.0.0.0:1935
2018/09/19 14:53:18 [info] 1305#0: *46 createStream, client: 192.168.110.192, server: 0.0.0.0:1935
2018/09/19 14:53:18 [info] 1305#0: *46 publish: name='5ba2bafc68a94' args='' type=live silent=0, client: 192.168.110.192, server: 0.0.0.0:1935
2018/09/19 14:53:18 [info] 1305#0: *46 notify: publish '192.168.111.121/plugin/Live/on_publish.php', client: 192.168.110.192, server: 0.0.0.0:1935
2018/09/19 14:53:18 [info] 1305#0: *46 disconnect, client: 192.168.110.192, server: 0.0.0.0:1935
2018/09/19 14:53:18 [info] 1305#0: *46 deleteStream, client: 192.168.110.192, server: 0.0.0.0:1935
2018/09/19 14:53:26 [info] 1305#0: *48 client 192.168.111.121 closed keepalive connection

that was without auth.  With trying auth, I get:
2018/09/19 14:55:26 [info] 1305#0: *60 client 192.168.111.121 closed keepalive connection
2018/09/19 14:55:36 [info] 1305#0: *61 client 192.168.111.121 closed keepalive connection
2018/09/19 14:55:45 [info] 1305#0: *62 client connected '192.168.110.192'
2018/09/19 14:55:45 [info] 1305#0: *62 connect: app='live' args='p=8c728e685ddde9f7fbbc452155e29639' flashver='FMLE/3.0 (compatible; FMSc/1.0)' swf_url='rtmp://192.168.111.121/live?p=8c728e685ddde9f7fbbc452155e29639' tc_url='rtmp://192.168.111.121/live?p=8c728e685ddde9f7fbbc452155e29639' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 192.168.110.192, server: 0.0.0.0:1935
2018/09/19 14:55:45 [info] 1305#0: *62 createStream, client: 192.168.110.192, server: 0.0.0.0:1935
2018/09/19 14:55:45 [info] 1305#0: *62 publish: name='5ba2bafc68a94' args='' type=live silent=0, client: 192.168.110.192, server: 0.0.0.0:1935
2018/09/19 14:55:45 [info] 1305#0: *62 notify: publish '192.168.111.121/plugin/Live/on_publish.php', client: 192.168.110.192, server: 0.0.0.0:1935
2018/09/19 14:55:45 [info] 1305#0: *62 disconnect, client: 192.168.110.192, server: 0.0.0.0:1935
2018/09/19 14:55:45 [info] 1305#0: *62 deleteStream, client: 192.168.110.192, server: 0.0.0.0:1935
2018/09/19 14:55:46 [info] 1305#0: *64 client 192.168.111.121 closed keepalive connection

**Comment by slthomason** [comment]
Where do the error_log() calls log to?  I have added some to the php files and I am not seeing them in /usr/local/nginx/logs/error.log.  Where do these go?

**Comment by DanielnetoDotCom** [comment]
Your error_log should be apache not Nginx

also make sure your 192.168.111.121/plugin/Live/on_publish.php is accessible

**Comment by djirving82** [comment]
Just wanted to leave a comment about my fix for a similar issue. When setting up Certbot I set it to redirect (http to https), and it prevented live streams from showing up on the main page. I had to comment out the redirect (RewriteRule) in the virtual host of the config (/etc/apache2/sites-enabled/avideo.conf). Hopefully this will help people fix this in less than the two days it took me. :)
