### ISSUE TITLE
AD_Server (AD_Server)  error 

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#1103]
Dear Mr. Daniel,

Please check below issue

If enable AD_Server_Location (AD_Server_Location) 
advertising manager showing issue please see attached image 
![ads server](https://user-images.githubusercontent.com/35865505/45833244-4be40e00-bd15-11e8-80db-697ef1298942.jpg)

**Comment by gujarraju** [comment]
and also database table installed

**Comment by DanielnetoDotCom** [comment]
make sure you install the User_Location plugin database

**Comment by gujarraju** [comment]
ohh also need User_Location 
ok 
thanks
