### ISSUE TITLE
see who is currently logged in?

### ISSUE THREAD

**Issue by timmayy** [DanielnetoDotCom/YouPHPTube#1104]
for those of us with abuse/spam issues how do we;

1. see who is currently logged in?
2. see any type of user analytics such as IP address browser info, etc

thanks for all that you do its really an awesoime script!

**Comment by DanielnetoDotCom** [comment]
Thanks , I am glad you like it.

For this we use Google analytics .

**Comment by timmayy** [comment]
have google analytics but im unable to see user specific details.. such as:

1. who is CURRENTLY logged in.
2. said users IP address
3. what about IP address of user upoon signup?

my point is i have issues with spammers uploading nonsense and I have no way of tracking it unless I delete the videos retroactively which is BEYON impossible with lots of users...

i need a way to identify which isers are logged in and what thier IP addresses are... at the least

**Comment by DanielnetoDotCom** [comment]
I see and agree with you.

For now we don't have that but pay attention on the audit plugin.

That plugin track all delete , update and inserts on your site

**Comment by timmayy** [comment]
ok ill check it out thank you!

**Comment by timmayy** [comment]
is there a description or guide on how to use audits plugon?

**Comment by timmayy** [comment]
the audit plugin is pretty good for now it helps alot thank you!

**Comment by DanielnetoDotCom** [comment]
great :)
