### ISSUE TITLE
Live Stream > There is no streaming now

### ISSUE THREAD

**Issue by siniztr** [DanielnetoDotCom/YouPHPTube#1107]
I have installed the RTMP server following the given instructions, and got to the point that I can connect with OBS to the server, and the video shows in the youPHPtube live screen, but it shows as offline, and the button for the live streams shows There is no streaming now. 

![live-streaming](https://user-images.githubusercontent.com/22732606/45917050-d476c180-be6f-11e8-860b-ded0118a1513.jpg)

Inside the Live page, the video does show, but when I go to the link given, I get a You are not allowed to see this streaming. 

![error](https://user-images.githubusercontent.com/22732606/45917021-5b776a00-be6f-11e8-89d9-d95eb3fc9a87.jpg)

**Comment by siniztr** [comment]
OK I figured out why I was getting the second part. I had it set to show in groups. Turning that off made it available to anyone. But video still shows as offline, even watching the video.
The live chat works as well.
I did notice though that in Firefox one of the CSS files is not loading. But in Chrome and IE it works fine.

**Comment by DanielnetoDotCom** [comment]
How looks like your stat nginx file?

take a look on the demo stat https://youphptube.com:444/stat

**Comment by siniztr** [comment]
The stats page shows fine when I have a stream operating. Right now it is empty.

**Comment by siniztr** [comment]
![stats-empty](https://user-images.githubusercontent.com/22732606/46251423-768b4080-c452-11e8-8900-4f16492acab2.jpg)
![stats-1stream](https://user-images.githubusercontent.com/22732606/46251424-768b4080-c452-11e8-83da-aace394e3ad2.jpg)

**Comment by siniztr** [comment]
Top is empty, no streams. Bottom is with 1 stream live.

**Comment by DanielnetoDotCom** [comment]
I see, 

I saw that before, I am not sure where is misconfigured but the livestream name should be something else 


![image](https://user-images.githubusercontent.com/18009293/46292865-58afff80-c568-11e8-8c39-e909979803b1.png)

**Comment by siniztr** [comment]
Is that something that I can change? Or is that something that will have to come in an update?

**Comment by DanielnetoDotCom** [comment]
Make sure you have compiled the right nginx version with no errors.

also if you can share your nginx.conf

**Comment by siniztr** [comment]
[nginx.conf.txt](https://github.com/DanielnetoDotCom/YouPHPTube/files/2439093/nginx.conf.txt)
It is the script from your instructions, only changes that I made is to add the SSL keys. You can see from my screenshots of the Stats page what version of the Nginx RTMP module I am using and what version of Nginx I have.

**Comment by DanielnetoDotCom** [comment]
YouPHPTube uses the Livestream name to detect it is online.

For ubuntu 16 I use nginx-1.12.0

For Ubuntu 18 I use nginx-1.13.8

**Comment by siniztr** [comment]
I have tried installing nginx1.12 using your guide, but get compile errors. Trying [the install guide](https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Set-up-my-own-Stream-Server) step 2 again using 1.13.8 instead of 1.12.0. Will comment later if this works.

**Comment by siniztr** [comment]
I have installed NGINX 1.13.8 for UBUNTU18.04, and followed the rest of the script, but the stat.xml still shows as in my previous screenshot.
![](https://user-images.githubusercontent.com/22732606/49442195-09d15100-f7c9-11e8-9eb6-19bb80441294.jpg)

This is just compiled and installed.

**Comment by DanielnetoDotCom** [comment]
Sorry, I dont know what are you doing different.

you can try to find help on the NGINX RTMP official repository https://github.com/arut/nginx-rtmp-module

**Comment by DanielnetoDotCom** [comment]
If you find a solution, please share with us

**Comment by siniztr** [comment]
Could it maybe have something to do with this?
nginx: [emerg] invalid port in url "https://www.xxxxxxxxxx.xxx./plugin/Live/on_publish.php" in /usr/local/nginx/conf/nginx.conf:23

If I try to place https instead of http in:
```on_publish http://www.iamsxm.sx/plugin/Live/on_publish.php;
on_play http://www.iamsxm.sx/plugin/Live/on_play.php;
on_record_done http://www.iamsxm.sx/plugin/Live/on_record_done.php;```

With http it works, with https I get the above mentioned error.

**Comment by DanielnetoDotCom** [comment]
Yes you right, that is another point, this URL must be http, NOT HTTPS

**Comment by siniztr** [comment]
@MalcolmMerlyn Are you using Ubuntu 18.04? I think it is a SSL issue, at least mine seems to be. I found an article on the NGINX RTMP issue page that says it is possible to offload the connection via HAproxy and it will work then, but I have not yet gotten it working. Once I do, I will update this article and send @DanielnetoDotCom an overview on what I have done so (if needed) he can create an article for it. I am not home at the moment so I can't post the link to the article I found. Once I get home I will do so.

**Comment by siniztr** [comment]
My problem is, I am not able to downgrage or run a clean install of a lower version of Ubuntu, as the website is already live. To take it down and start over will take time, and that is time I currently don't have. So will give the HAproxy or maybe Apache2 proxy SSL offloading and see if I can get it working like that.

**Comment by DanielnetoDotCom** [comment]
@siniztr thanks.

but why do you need to downgrade?

**Comment by siniztr** [comment]
I have reset the SSL to load the site and the stream via HTTP, but the stream still shows the link with HTTPS. How can I change this? That once I add stream using the key, that it shows in STATS with HTTP and not HTTPS?

**Comment by nightstryke** [comment]
@siniztr If you're using Ubuntu did you install via apt-get or apt instead of building nginx from source?
If you want to use SSL with nginx you have to set it on a separate port than standard 443 it'll need to go to port 444. You'll need an SSL Certificate to get nginx to work with https, I use let's encrypt.

@DanielnetoDotCom Daniel I can confirm the building of nginx with RTMP Module works with the latest NGINX stable (nginx-1.14.2) as that's what's running on my dedicate server.

**Comment by DanielnetoDotCom** [comment]
I just fix a very similar problem on a costumer.

the problem was because he added a redirect rule on .htaccess, so he redirects everything to his www URL.

After remove the redirect rule it starts to work perfectly

**Comment by itraxAdmin** [comment]
Is there any solution for this problem? My .htaccess is the original from the installation. I did not change it. I can see the stream on stat page, but not on frontend.

![image](https://user-images.githubusercontent.com/359220/56338275-ced02880-617f-11e9-8a77-4cc03672b5c9.png)

![image](https://user-images.githubusercontent.com/359220/56338291-e4dde900-617f-11e9-8546-21df57c90cc7.png)

I'm not using https anywere.

What can I do here? 
Thank you.

**Comment by DanielnetoDotCom** [comment]
@itraxAdmin your installation looks fine.

make sure you have the Listed transmition option checked

https://github.com/YouPHPTube/YouPHPTube/issues/1537

**Comment by itraxAdmin** [comment]
Thanks Daniel for you answer.
Where did I check this option I could not find it on site settings.

There is another piece of information. The http://my-site:8080/live url is responding with a "403 Forbiden" error. I make sure to give all permisions to the /HLS/live folder.

My nginx configuration file is exactly like this one:

https://github.com/YouPHPTube/YouPHPTube/wiki/Configure-NGINX-Stream-Resolutions

Of course I'd put my site url where it is demanded.

I'd notice that when I start a live transmition a file is created on HLS/live folder.

Should be this the problem?

Thanks again.

**Comment by itraxAdmin** [comment]
Hi Daniel, I found to "Listed transmition" option on the LIVE page.  I checked and now it is working, I can see my transmition on main page.

![image](https://user-images.githubusercontent.com/359220/56378439-729ef000-61e3-11e9-81eb-3ec1d2dfb43a.png)


I have two questions. 
1. I'm broadcastin with the cell phone on landscape orientation and the video is being transmited on portrait orientation. I'm using your app to broadcast. Is there some configuration to fix that?

2. Which is the hardware and network requirement to run a broadcast test? The video is taking too long to start and has about 1 minute delay and freezes all the time. My cell phone was using WIFI during the test.

Thanks

**Comment by DanielnetoDotCom** [comment]
1. It may be improved in the future
2. you will need to test some OBS configurations to find out the most suitable, check this https://github.com/YouPHPTube/YouPHPTube/wiki/YouPHPTube-hadware-requirements
3. it is probably a problem on your publisher or video source
