### ISSUE TITLE
video overlay plugin

### ISSUE THREAD

**Issue by timmayy** [DanielnetoDotCom/YouPHPTube#1108]
Can it be so the logo actually stays on the video when downloaded?

I thought it would stay there after download before I bought it...

**Comment by Criptos** [comment]
For the logo to 'live' on the video, you would need to add it and  transcode it. 

The advantage of that plugin is exactly that, you don't need to reencode each video to have it with the logo inside the platform...  is just an 'inexpensive' in terms of reencoding...

**Comment by timmayy** [comment]
> 
> 
> For the logo to 'live' on the video, you would need to add it and transcode it.
> 
> The advantage of that plugin is exactly that, you don't need to reencode each video to have it with the logo inside the platform... is just an 'inexpensive' in terms of reencoding...

to "add and transcode" is that anything my site can do? or somethign seperate?

**Comment by timmayy** [comment]
how would i incorporate this into my youphptube?

**Comment by Criptos** [comment]
humm... it would be to include it at the encoder... needs development... 

You could setup a bounty if want it developed for you and help the community...

**Comment by chinli12** [comment]
Can this script look like YouTube on mobile and I want plugin pay par view
