### ISSUE TITLE
Is there a site version to version upgrade guide?

### ISSUE THREAD

**Issue by KenRHill** [DanielnetoDotCom/YouPHPTube#1109]
Hi there again.  I am currently running YouPHPTube 5.01 but I want to upgrade my entire site to the latest version.  Is there a guide that can walk me step by step through the upgrade process so that I don't mess anything up.  I would like to keep my site contents intact and working.  I just want to make the upgrade from 5.01 to 5.9 and I am really cautious about doing it.  Could you point me in the right direction?  I have never performed a version upgrade yet so I am new to the process.  Please advise.

**Comment by KenRHill** [comment]
Hi Criptos,

I am not familiar with the process of database modification.  I was hoping to find something in the line of a walkthrough guide that would allow me to make it through the whole process.  Thanks for trying to help.

**Comment by DanielnetoDotCom** [comment]
Hi, 

1. the first step is to make a git pull to update all your files.
details how to do that are here https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

1. Login as admin and go to the admin menu -> Update Version

![image](https://user-images.githubusercontent.com/18009293/45948736-8bd61a00-bfcf-11e8-947f-cdbaf67b7ac6.png)

1. IMPORTANT, DOT NOT SKIP ANY UPDATE, if you want to go 5.01 to 5.9 you must update 
5.01->5.2
5.2->5.3
5.3->5.4
5.4->5.5
5.5->5.6
5.6->5.7
5.7->5.8
5.8->5.9

**Comment by KenRHill** [comment]
I am confused about step 3.  What do I need to do specifically to update between each version?
