### ISSUE TITLE
View count and clear statistics issue

### ISSUE THREAD

**Issue by laweschan** [DanielnetoDotCom/YouPHPTube#111]
Hi,

  it seems strange when setting in "Youtube" in First Page Mode, when open either using of firefox, IE or chrome, it will automatically count + 1 for the newest post, even just reload the page.

  that will caused as an invalid view number value and it should only count up when playing, behind, how can we clear the statistic such as view , access chart and comment ?

  thanks

Regards,
Lawes

**Comment by DanielnetoDotCom** [comment]
Yeah, if you open the page it already count 1, we can improve the code to count only if it is playing.
To clear statistic you have to truncate videos_statistics table manually.

**Comment by laweschan** [comment]
thx, it seems a bug and look forward for the update

Regards,
Lawes

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
