### ISSUE TITLE
Video related problem

### ISSUE THREAD

**Issue by guidence2juniors** [DanielnetoDotCom/YouPHPTube#1110]
After upload , video is not playing even after the videos had been uploaded perfectly..

**Comment by DanielnetoDotCom** [comment]
how did you upload?

direct upload or encoder?

uploaded perfectly, does not mean the video has the correct format.

Please read this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/About-Video-Upload

**Comment by guidence2juniors** [comment]
i m uploading it on respberry pi 3 , i check encoder , encoder is processing but still after upload there is no video is in videos folder , i directlty upload the site on my ubuntu is working fine ... i don't understand now how to overcome this issue .. can you give me some suggestion please.

**Comment by guidence2juniors** [comment]
log file is showing the error : 
PHP  fatel error: require_once( ): Failed opening required 'videos/configuration.php' (include_path = '. : /usr/share/php: / usr/share/pear') in /var/www/html/folder_name/index.php on line 126

**Comment by guidence2juniors** [comment]
i m using apache server and os is raspbian , i install php and mysql separately but i guess there is a problem in php as my database folder showing some error. do i need to install php again to resolve the error on the raspbian os .

**Comment by DanielnetoDotCom** [comment]
Sorry, but I dont know. I have never installed it on raspbian os
