### ISSUE TITLE
Load Test

### ISSUE THREAD

**Issue by timmayy** [DanielnetoDotCom/YouPHPTube#1112]
has anyone ever done a load test to see how many users an instance can handle?

**Comment by ChrisSlS** [comment]
I do not know if this is related to your question, but on my YouPHPTube, if more than 70 users are online the website takes a very long time to load, yet my server configuation is good.

**Comment by ChrisSlS** [comment]
Yes of course, I set it as on the demo site, 30 seconds

**Comment by Criptos** [comment]
Have you done a speed profile with the:
https://developers.google.com/speed/pagespeed/insights/

I haven't done any profiling yet, but this tools helps me improve the sites...

**Comment by ChrisSlS** [comment]
Thanks to you @Criptos 

![stat](https://user-images.githubusercontent.com/37787071/46031403-0e0e2d80-c0f9-11e8-90ba-4a865dab504e.png)

Most of the users are on smartphone, is this the root cause of the slowdown of the site beyond 50-70 online?

**Comment by Criptos** [comment]
Other thing you can do, is excecute the developer tools, put chrome with the image ratio of a cellphoen and reload thepage, checkou the network tab and look out what elements take too long to load...

**Comment by timmayy** [comment]
only 70 users causes lag?

yikes.....

**Comment by Criptos** [comment]
I think it may have something to the the server where the service is, maybe is a low bandwith service... 
youphptube can be massive with the network...

**Comment by timmayy** [comment]
> 
> 
> I think it may have something to the the server where the service is, maybe is a low bandwith service...
> youphptube can be massive with the network...

but no general ideas on how much?

is there any legitimate way to test how many users it can hanlde?

**Comment by timmayy** [comment]
ive goot decent hardware dual xeon 24 cores total 64gb ram 5tb total sas 

really just curious more than anyting

**Comment by Criptos** [comment]
I would create some vm, and use 'smaller' servers, to restrict hardware so I can rule out bandwidth...  also you could 'load balance' your load between those smaller servers... sometimes 2 smaller servers give more performance than 1 big server. 

My youphptube right now is in 4gb ram 2 core server... and it work just fine... 
 
iostat and mpstat are also your friends... maybe you have IO bottleneck, people is really 'consuming' a lot of different content...

**Comment by ChrisSlS** [comment]
Thank you very much for your answer @Criptos 

In my case, I am limited to 19 MB/s, and currently a fifty person are connected and the bandwidth is practically used entirely. I will have to ask more or migrate elsewhere.

**Comment by Criptos** [comment]
Actually, youphptube isn't very cpu intensive.. is bandwidth intensive.... for example a lot of optimization can be done with the memcached session handler and the opcache from zend.... database isn't huge neither, with so much ram I would configure mysql to have al the tables on memory...
