### ISSUE TITLE
Permission error on SendRecordedToEncoder

### ISSUE THREAD

**Issue by pjaxed** [DanielnetoDotCom/YouPHPTube#1114]
Hi Daniel,

Kindly assist with the following PHP Warning:
copy(/tmp/5b991aaff3f45-26-Sep-18-12:15:53.flv): failed to open stream: No such file or directory in /var/www/html/YouPHPTube/plugin/SendRecordedToEncoder/SendRecordedToEncoder.php(14) : eval()'d code(1) : eval()'d code on line 49
[26-Sep-2018 12:16:04 UTC] on_record_done ERROR: could not copy or move file  /tmp/5b991aaff3f45-26-Sep-18-12:15:53.flv to /var/www/html/YouPHPTube/videos/original_LiveStream1080on26Sep18121553_YPTuniqid_5bab7884bef9c2.82549996
[26-Sep-2018 12:16:04 UTC] on_record_done END

The stream is recorded in flv format in /tmp/xxx.flv.  It does not get uploaded to the Encoder.  I made sure all folders have the correct permissions, but that does not appear to help.

Regards,

Jako
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2419684/youphptube.log)

**Comment by DanielnetoDotCom** [comment]
if you follow this correctly: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Record-Live-Stream

try to change the location where NGINX saves its videos

1. Create a dir on your videos directory like **/var/www/html/YouPHPTube/videos/tmp**
2. change your record_path param on nginx.conf to **record_path /var/www/html/YouPHPTube/videos/tmp;** 
3. restart nginx

**Comment by pjaxed** [comment]
Thank you for your prompt assistance.  Greatly appreciated.  All working correctly now.
