### ISSUE TITLE
Can't get into my profile!

### ISSUE THREAD

**Issue by Lucikos666** [DanielnetoDotCom/YouPHPTube#1115]
Hello!After registering as the administrator can't log in to your profile.Constantly hangs at the Processing... New users can't register,permanently not suitable captcha.
![screenshot_4](https://user-images.githubusercontent.com/43613706/46089948-4fb1dd80-c1b8-11e8-8425-7f94e7e06e11.png)

![screenshot_5](https://user-images.githubusercontent.com/43613706/46090090-9c95b400-c1b8-11e8-8a96-cf023557fe8d.png)

**Comment by Criptos** [comment]
Can you tell us your setup, apache version, php, os? 
Seems weird...

**Comment by DanielnetoDotCom** [comment]
Also can you please check your log file?
