### ISSUE TITLE
To remove the language.

### ISSUE THREAD

**Issue by Lucikos666** [DanielnetoDotCom/YouPHPTube#1118]
Hi. How can I remove extra languages from the selection?

![screenshot_6](https://user-images.githubusercontent.com/43613706/46140468-df5b9880-c259-11e8-8c15-8ea29ac7e7a4.png)

**Comment by DanielnetoDotCom** [comment]
You can delete the lang files from https://github.com/DanielnetoDotCom/YouPHPTube/tree/master/locale
