### ISSUE TITLE
Please check Error 

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#1119]
Hi Sir,

http://www.test.com/v/829/page/3

Not Found

The requested URL /v/829/page/3 was not found on this server.
Apache/2.4.18 (Ubuntu) Server at www.test.comPort 80

**First Page video OK but second page error showing.**

**Comment by DanielnetoDotCom** [comment]
can you reproduce it on the demo site?

**Comment by gujarraju** [comment]
sure please check
CustomizeAdvanced (CustomizeAdvanced) Plugins
if use -usePermalinks

https://demo.youphptube.com/v/214/page/3

**Comment by gujarraju** [comment]
yes know working fine 

thanks.
