### ISSUE TITLE
Questions about Posters and Sorting

### ISSUE THREAD

**Issue by KeithGraber** [DanielnetoDotCom/YouPHPTube#112]
Good day!

A few questions:

How do I generate the Poster.jpg and the Mouse Over Poster .gif when uploading a .MP4 file using the "Upload a MP4 video" button instead of the encoding site?

Is there a way to sort or change the display order of uploaded videos / audio files?  I have a number of videos that I'm planning on uploading (recorded meetings that go back a number of years) and if I mess up when doing the uploads I'd hate to have to delete and then upload / re-encode again.  (I can just see myself uploading 10 videos and discovering I missed one that needs to be placed as the 2nd video in the series, causing me to delete 9 videos).

Is there a way of disabling comments and account sign up's.  I'm not planing on having end user feedback, so the comment section isn't needed.  And I only need one account for video uploads so the new account sign up form isn't needed.

Thanks for your help and work on this project!

**Comment by DanielnetoDotCom** [comment]
> How do I generate the Poster.jpg and the Mouse Over Poster .gif when uploading a .MP4 file using the "Upload a MP4 video" button instead of the encoding site?
If you use the encoder this is automatic created, it you just upload, you have to do it manually.
If you already have the jpg and gif file just edit the video and upload the image files
![image](https://user-images.githubusercontent.com/18009293/30280058-29f3d6e2-96e5-11e7-960d-bfab8946e614.png)

> Is there a way to sort or change the display order of uploaded videos / audio files? I have a number of videos that I'm planning on uploading (recorded meetings that go back a number of years) and if I mess up when doing the uploads I'd hate to have to delete and then upload / re-encode again. (I can just see myself uploading 10 videos and discovering I missed one that needs to be placed as the 2nd video in the series, causing me to delete 9 videos).

I understand this, by now, we do not have this kind of sort option, but i will think about for future versions

**Comment by KeithGraber** [comment]
Thanks for the feedback.  I saw the option to upload the 2 image files, but was hoping there was a button to press to have YouPHPTube generate them.

**Comment by DanielnetoDotCom** [comment]
We need FFMPEG to generate, and only the encoder uses FFMPEG

**Comment by KeithGraber** [comment]
Can the Encoder site be set to just create the 2 image files if the uploaded video is already in .MP4 format?  And/or create the WEBM file at the same time (without re-encoding the MP4)?

**Comment by DanielnetoDotCom** [comment]
Not now, but it is a good idea to be implemented on the future

**Comment by KeithGraber** [comment]
Thanks for thinking about adding these options.
