### ISSUE TITLE
Description area improvement

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#1121]
Hi Sir,

Please add in description area SHOW more SHOW LESS 
Please check below image. 
![show](https://user-images.githubusercontent.com/35865505/46208369-8bc17b80-c33b-11e8-9c69-71de7c054c36.jpg)

**Comment by gujarraju** [comment]
> 
> 
> Hi Sir,
> 
> Please add in description area SHOW more SHOW LESS
> Please check below image.
> ![show](https://user-images.githubusercontent.com/35865505/46208369-8bc17b80-c33b-11e8-9c69-71de7c054c36.jpg)

**Comment by gujarraju** [comment]
Hi Daniel, 
Please try to fix

**Comment by DanielnetoDotCom** [comment]
Hi

This is not a fix, it is an improvement.
This is really a good idea and may be improved in the future.
If you are willing to pay we can improve it now.
please email me if you want to rush this improvement. developer@youphptube.com
