### ISSUE TITLE
PHPMailer issue

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#1124]
Hi...Sir,

Today i tried to configure smtp (gmail secure app also allow) server but showing error i tried ssl or tls both but not working.
please check attached image.
![php](https://user-images.githubusercontent.com/35865505/46259710-e995c500-c4ed-11e8-8ceb-de4c81cfc2c9.jpg)

**Comment by DanielnetoDotCom** [comment]
Probably is something on your SMTP settings or SMTP server configuration.

I have the SMTP options enabled and working in many sites

**Comment by lucassica** [comment]
http://hotelhoster.com/<http://hotelhoster.com/upload/cb_install/>
________________________________

**Comment by gujarraju** [comment]
ok so which smtp server (mail) working..

**Comment by DanielnetoDotCom** [comment]
I use gmail with no problem 

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Setting-up-YouPHPTube-to-send-emails

**Comment by gujarraju** [comment]
ok
thanks
