### ISSUE TITLE
The requested URL /YouPHPTube/user was not found on this server.

### ISSUE THREAD

**Issue by anzaldomartin** [DanielnetoDotCom/YouPHPTube#1125]
Hi! I see other issues closed with this problem and i cant fix my instalation.
I have the .htaccess file and de rewrite mode OK. Can you help me? Thankssss

![imagen](https://user-images.githubusercontent.com/37669255/46266230-0b9a4200-c504-11e8-8c9e-9af1c1854555.png)

**Comment by DanielnetoDotCom** [comment]
Please check this https://github.com/DanielnetoDotCom/YouPHPTube/issues/872

**Comment by anzaldomartin** [comment]
Thanks but it did not work, I had already read that issue. I made a new installation, renamed the file, the rewrite mode was already active and I still can not use it. Thanks again and greetings!

![imagen](https://user-images.githubusercontent.com/37669255/46346738-71c7b780-c61f-11e8-8e0d-1550ea70f6f9.png)

**Comment by DanielnetoDotCom** [comment]
definitely, something is wrong with your directories, looks like you moved them and miss some hidden files.

I am saying this because you moved the classic.htaccess from html dir into YouPHPTube dir, this file should be inside YouPHPTube dir.

But I can't tell you what is wrong.
