### ISSUE TITLE
Look like youtube on moble and new plugin

### ISSUE THREAD

**Issue by chinli12** [DanielnetoDotCom/YouPHPTube#1128]
I want the script to look like YouTube design on mobile and I want pay par view plugin

**Comment by chinli12** [comment]
I am from Nigeria strip payment is good

**Comment by chinli12** [comment]
What about the template

**Comment by rahmediahouse** [comment]
I would like to know that in YouPHPTube, how pay per view works.
Or in case, I want to make my videos in a subscription mode, how can it be done.

**Comment by rahmediahouse** [comment]
@Criptos 

Can you also look into hooking the wallet platforms like google pay, amazon pay, paytm and etc.

In today's market, these everyone is carrying these wallets.

**Comment by DanielnetoDotCom** [comment]
I am working on a membership plugin.
should be released in a couple weeks

**Comment by rahmediahouse** [comment]
We are eagerly waiting for the membership plugin.

**Comment by rahmediahouse** [comment]
can you let us know the status about the membership plugin and from where can we enable it.

**Comment by DanielnetoDotCom** [comment]
You can see it working here https://netflix.youphptube.com/

It is done, but it is not on the market yet. if you want earlier access, email me developer@youphptube.com.

The plugin cost will be 200 USD
