### ISSUE TITLE
embed direct video link not working

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#1129]
Hi..

Please check embed direct video link not working.

**Comment by gujarraju** [comment]
If enable AD_Server embed direct video link not Playing only rounding showing.

**Comment by DanielnetoDotCom** [comment]
can you share a sample link of what are you trying to embed?

**Comment by gujarraju** [comment]
**Please  Check Below Link and Enabled Ad Server not Working. If  disable Ad server working fine.**

https://demo.youphptube.com/video/rishta-dilon-ka-tode-na-toote-jaanwar-songs-akshay-kumar-shilpa-shetty-sunidhi-chauhan-mp4

**Comment by DanielnetoDotCom** [comment]
This link does not work, we refresh the site many times every day.

**Comment by gujarraju** [comment]
Please Embed as a direct video link then AD-server  Should be on after check.

https://drive.google.com/uc?export=download&id=1PbYZxwA61a7hLivSAHtiYJ_XA7XLMZlx

**Comment by DanielnetoDotCom** [comment]
You can not embed this link.
it is a download link, not a direct video file

**Comment by gujarraju** [comment]
check screen recorded video.

https://demo.youphptube.com/video/youphptube

**Comment by DanielnetoDotCom** [comment]
can you please share it on your site?
