### ISSUE TITLE
Encoding video not working.

### ISSUE THREAD

**Issue by eshita321** [DanielnetoDotCom/YouPHPTube#1130]
I installed youphptube in centos6.10 platform. everithing seems perfect but encode video not work and play . here is the log error show. not only installed encoder working but also not work public encoded video .  
![log](https://user-images.githubusercontent.com/36513168/46485597-c9cc0d00-c81d-11e8-9453-ebb1f2220579.png)
![video](https://user-images.githubusercontent.com/36513168/46485606-d05a8480-c81d-11e8-9036-144d39987baf.png)

**Comment by DanielnetoDotCom** [comment]
It does not help much about the error, try to share with us your encoder log and your streamer log
