### ISSUE TITLE
Can u gude me how can i place my adsense add on my website perfectly 

### ISSUE THREAD

**Issue by jamalmahmud** [DanielnetoDotCom/YouPHPTube#1131]
Can u gude me how can i place my ad sense add on my website perfectly 

on sidebar and 
single page sidebar

**Comment by DanielnetoDotCom** [comment]
Should be on your site configuration menu.

You can check how we did it on our demo site https://demo.youphptube.com/

![image](https://user-images.githubusercontent.com/18009293/46502807-692dd780-c7ff-11e8-9432-bd8bc4f768c0.png)


But for a more specific answer please paste here your site address and the code you are using
