### ISSUE TITLE
videos dont seem to play on my new iphone

### ISSUE THREAD

**Issue by joey2354** [DanielnetoDotCom/YouPHPTube#1132]
hi there ... the videos dont seem to play on my new phone, they work on my android just so you know.

would u care to have a quick look please ? thxs ✌️

**Comment by DanielnetoDotCom** [comment]
Hi, any video play? even videos on demo site?

can you send us a link of the video is not working on your phone?

**Comment by joey2354** [comment]
hi ... its all of them buddy https://probeatz-vids.ga

**Comment by DanielnetoDotCom** [comment]
Sorry, I can not reproduce this error, so I need you to help me to identify it.

I need you to try to play with your iPhone videos  on this site https://demo.youphptube.com/, and let me know if it works

I also need to know how you are uploading the videos.

Direct Upload? (mp4)
Encoder?
Embed?

**Comment by joey2354** [comment]
it's all the embed links from youtube ... they work on my android phone just so you know, but not on my iphones.

https://www.youtube.com/watch?v=8JnfIa84TnU  this one doesn't work on my iphone, no of them do just so we're clear :)

**Comment by DanielnetoDotCom** [comment]
ok, only embed videos, but other types of videos do works correct?

**Comment by joey2354** [comment]
yes just the embed links, all the uploaded vids work fine

**Comment by DanielnetoDotCom** [comment]
Please check this option and let me know

![image](https://user-images.githubusercontent.com/18009293/46921333-633eb000-cfd0-11e8-8ac3-2c7239012ba2.png)

**Comment by joey2354** [comment]
fixed thxs
