### ISSUE TITLE
Remove HELP Menu from the sidebar

### ISSUE THREAD

**Issue by rahmediahouse** [DanielnetoDotCom/YouPHPTube#1133]
Hi,

The Help Menu which is coming in the left side bar, I want to get this disable/invisible for all my users.

Let me know the procedure to get this done, or is there any checkbox for this in the customizeavanced plugin.

Kindly revert.

**Comment by ChrisSlS** [comment]
Hello,

Remove line 640-645 of view/include/navbar.php

**Comment by rahmediahouse** [comment]
Thanks
