### ISSUE TITLE
Gallery Plugin

### ISSUE THREAD

**Issue by rahmediahouse** [DanielnetoDotCom/YouPHPTube#1135]
Hi,

In the gallery plugin, under the edit parameters, we have BigVideo option which chooses the latest video and makes it big.

I would like this option to work like a netflix homepage, where few videos from multiple category keeps on rolling on after other in few for few seconds.

**Comment by DanielnetoDotCom** [comment]
I will work on that soon

**Comment by rahmediahouse** [comment]
Hi,

Thanks for the update.

I updated the version and enabled the YouPHPFlix2 plugin.

The Big Video images are coming now.

Issues:
1. When you load the page, the footer comes on the top. Once the page gets loaded fully, the footer goes down.
2. I disabled the Page dots, but still it is coming.
3. Empty Categories, where videos are not present, are being shown, without videos.
4. Page dots increase as much you increase the number in maxvideo. In case you put 200 in maxvideo, same number of dots appears in the screen.

**Comment by rahmediahouse** [comment]
Big Video should have atleast 3 screen/video, also only the bigthumbnail should appear, currently the title, button, everything is being shown.

The video should play on the click of the image.

**Comment by DanielnetoDotCom** [comment]
> 1. When you load the page, the footer comes on the top. Once the page gets loaded fully, the footer goes down.

I can not fit it now. but may be fixed on the future

> 2. I disabled the Page dots, but still, it is coming.

fixed

> 3. Empty Categories, where videos are not present, are being shown, without videos.

fixed

> 4. Page dots increase as much you increase the number in maxvideo. In case you put 200 in maxvideo, same number of dots appears in the screen.

Now you can disable them

> 5. Big Video should have atleast 3 screen/video, also only the bigthumbnail should appear, currently the title, button, everything is being shown.

yes, that is the propose 

> 6. The video should play on the click of the image.

for now you must click on play button

I still working on it, but here is the YouPHPFlix demo https://netflix.youphptube.com/

**Comment by DanielnetoDotCom** [comment]
clear your videos/cache dir

**Comment by rahmediahouse** [comment]
Thanks.

Working now.

In your netflix version, you have a thumbnail and a trailer in your big video. How to enable that.

**Comment by rahmediahouse** [comment]
and how to enable a big thumbnail.

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/46967836-128a8e00-d088-11e8-996e-ba9270de55ea.png)
