### ISSUE TITLE
User Form - Restrict Upload Video by User

### ISSUE THREAD

**Issue by rahmediahouse** [DanielnetoDotCom/YouPHPTube#1136]
Hi,

When I create a user, i disable the feature of video feature, but still after getting it logged as a user, I am able to embed or upload the video in the portal as a end user.

![image](https://user-images.githubusercontent.com/43905917/46578504-af618180-ca1f-11e8-95e4-47fe7e359eb6.png)

Let me know how to get this resolved.

**Comment by rahmediahouse** [comment]
Hi,

Kindly revert on this.

**Comment by rahmediahouse** [comment]
Yes I am sure.

None of the functions are working expect I think, Is Admin.

**Comment by DanielnetoDotCom** [comment]
can you also verify it on the demo site?
can you create a user and test it? https://demo.youphptube.com/

**Comment by DanielnetoDotCom** [comment]
Try to disable 
![image](https://user-images.githubusercontent.com/18009293/46672794-b965ba80-cbae-11e8-9c73-c76dde434c2b.png)

**Comment by rahmediahouse** [comment]
It worked.

Thanks.
