### ISSUE TITLE
Direct import/direct upload multiple pre encoded videos with various resolutions

### ISSUE THREAD

**Issue by giaur500** [DanielnetoDotCom/YouPHPTube#1138]
Because my server resources are rather limited, I want to avoid server side encoding. Instead, I prepared 3 files with 1080, 720 and 640 resolutions. Now I want to direct upload all of them to my server and get these 3 video qualities visible as list to choose when watching video.

How to do that?

**Comment by giaur500** [comment]
Any plans to make it possible?

**Comment by DanielnetoDotCom** [comment]
maybe you can manually rename the files on videos directory.

add a suffix _SD, _HD or _Low on the file name

![image](https://user-images.githubusercontent.com/18009293/46670988-fc715f00-cba9-11e8-967b-731f26145ba2.png)

**Comment by giaur500** [comment]
It does not work, maybe I need to update database also?

**Comment by DanielnetoDotCom** [comment]
you don't need to update the database, it the file exists the script will recognize, you just need to add the suffix.

**Comment by giaur500** [comment]
![image](https://user-images.githubusercontent.com/26817206/46785916-8567d200-cd33-11e8-8393-e8bff2e1e433.png)

But sitll player does not allow to choose quality. Am I missing something?

**Comment by DanielnetoDotCom** [comment]
Do you have the video resolution plugin?

is it enabled?

**Comment by giaur500** [comment]
No I don't. I also realized it's not free, need to pay. I didn't know that functionality requires additional plugin.

**Comment by DanielnetoDotCom** [comment]
Yes this is a commercial plugin

**Comment by nightstryke** [comment]
> No I don't. I also realized it's not free, need to pay. I didn't know that functionality requires additional plugin.

I'm using the plugin, I would seriously recommend getting it because what you're describing right now, I'm already doing with my current YouPHPTube install, the only difference is I'm also allowing 480p.

**Comment by Zixim** [comment]
i'm trying the same thing...moving pre-encoded files into the\videos directory, and adding the suffix _HD, plus some jpg bitmaps & thumbnails.
The script doesn't seem to discover these new videos/files.

Could you say at what frequency the script checks the folder for new files ?

**Comment by DanielnetoDotCom** [comment]
if you upload with the right name and suffix if should find it with no problem

**Comment by Zixim** [comment]
i copied the video file `test_HD.webm` into the videos folder, and it never got added to the web interface.

**Comment by DanielnetoDotCom** [comment]
are you sure "test" is your filename?
usually YouPHPTube uses an unique ID as a file name, this name must match with the filename field on the database

**Comment by Zixim** [comment]
oh wait...we're not on the same page.
I thought the OP was regarding _copying_ a file into the videos folder.
In fact the OP is about doing a direct upload of a file through the webif.

**Comment by DanielnetoDotCom** [comment]
@Zixim sorry I do not understand

**Comment by DanielnetoDotCom** [comment]
I see, thanks for the feedback
