### ISSUE TITLE
Encoder issue 

### ISSUE THREAD

**Issue by nilesh111091** [DanielnetoDotCom/YouPHPTube#1139]
I am having encoder issue:

In my localhost it works after logging in but when i put on live it does not allow me to login. 
It just says user or password can not be blank. 

Can you rectify this issue ?

**Comment by nilesh111091** [comment]
I think the issue is having with this function: 
function url_get_contents($Url, $ctx = "") {
    if (empty($ctx)) {
        $opts = array(
            "ssl" => array(
                "verify_peer" => false,
                "verify_peer_name" => false,
                "allow_self_signed" => true
            )
        );
        $context = stream_context_create($opts);
    } else {
        $context = $ctx;
    }

    // some times the path has special chars
    if (!filter_var($Url, FILTER_VALIDATE_URL)) {
        if (!file_exists($Url)) {
            $Url = utf8_decode($Url);
        }
    }

    if (ini_get('allow_url_fopen')) {
        try {
            fetch_http_file_contents($Url);
        } catch (ErrorException $e) {
            try {
                $tmp = @file_get_contents($Url, false, $context);
                if ($tmp != false) {
                    return $tmp;
                }
            } catch (ErrorException $e) {
                error_log("Error on get Content");
            }
        }
    } else if (function_exists('curl_init')) {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $Url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $output = curl_exec($ch);
        curl_close($ch);
        return $output;
    }
    return @file_get_contents($Url, false, $context);
}
Not sending to youphptubeurl with required parameters.

**Comment by DanielnetoDotCom** [comment]
what does your log file say?

**Comment by nilesh111091** [comment]
Okay. Encoder is working now but how to use bulk encode its not working.

**Comment by DanielnetoDotCom** [comment]
what is the error?

log file?

**Comment by nilesh111091** [comment]
Error was in curl request on youphptube url.  And how to encode multiple
videos?

**Comment by DanielnetoDotCom** [comment]
try this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Bulk-Upload-Videos

**Comment by nilesh111091** [comment]
Clicking on listFiles I can not see any output.

**Comment by nilesh111091** [comment]
in your case its "/playList" how to check it .

**Comment by nilesh111091** [comment]
Also I need to encode when any user is uploading their video please explain
me that also how to acheive this ?

**Comment by DanielnetoDotCom** [comment]
sorry, I don't understand what is your question.

**Comment by DanielnetoDotCom** [comment]
anonymous user cannot upload, to be able to upload must be an authenticated user.

**Comment by nilesh111091** [comment]
yes I mean to say that one authenticated user and I wish that videos should
also be encoded from there too.

**Comment by DanielnetoDotCom** [comment]
I really don't understand what is the problem.

please detail a bit more and add some screenshots if is possible

**Comment by nilesh111091** [comment]
Step 1 User logs into their account.
Step 2 User clicks on upload video button.
step 3 Upload video screen shows to user.
Step 4 User clicks on upload video button and choose the files to be
uploaded.
step 5 this uploading video should have to convert into three parts sd hd
and low from frontend as we are doing from encoder.

**Comment by DanielnetoDotCom** [comment]
Direct upload is different from encode video.

please check this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/About-Video-Upload

**Comment by nilesh111091** [comment]
and if i want to do that then what procedure i need to follow?

I am thinking that I drop an entry to the encoder queue when user uploads a
video how about that

?

**Comment by DanielnetoDotCom** [comment]
I cant teach you how to do that. If you know how to use PHP you will need to figure out it.

**Comment by nilesh111091** [comment]
Is encoder working on cron ?

**Comment by DanielnetoDotCom** [comment]
No it does not

**Comment by nilesh111091** [comment]
If i close the encoder then , will the encoder work which ever files i set
on queue ?

**Comment by DanielnetoDotCom** [comment]
Yes

**Comment by nilesh111091** [comment]
Encoder is too slow in encoding can we do fast encoding ?

**Comment by DanielnetoDotCom** [comment]
to fast encode you will need a better CPU.

try to get a better/faster server

**Comment by nilesh111091** [comment]
We have Amazon lightsail vps.
