### ISSUE TITLE
Login button stopped working

### ISSUE THREAD

**Issue by jarredmoore** [DanielnetoDotCom/YouPHPTube#1140]
My login button stopped submitting for some reason so I'm not able to login??
I restarted my server and Mysql incase I had to many failed attempts but nothing worked.
Any suggestions??

**Comment by jarredmoore** [comment]
I got it! looks like I just had to clear my cache.
I had to shh to ../video/cache/ and clear it out using sudo rm ../video/cache/*

**Comment by DanielnetoDotCom** [comment]
great
