### ISSUE TITLE
Generating sitemap fails - 500 error on objects/configurationGenerateSiteMap.json.php

### ISSUE THREAD

**Issue by JedMeister** [DanielnetoDotCom/YouPHPTube#1141]
This is not a super important issue to me, I was just clicking around checking out the interface and options. I am somewhat concerned though, that there is something I'm missing (php dependency?) or have configured improperly and this is just a symptom...

----

OS: Debian 9/Stretch
YouPHPTube: v6.0 (master branch: commit 674d39b7).

FWIW, I was experiencing this in v5.9 - updated to check that it hadn't already been fixed.

To recreate:
In Chrome, logged in as admin, browse to "Site configurations" >> "Advanced configuration" and click "Generate sitemap". Page hangs with progress bar "Processing". The chrome dev console notes that it's a 500 error on `objects/configurationGenerateSiteMap.json.php`

YouPHPTube log confirms:
```
[09-Oct-2018 05:11:27 UTC] youphptube.log deleted by update
[09-Oct-2018 05:11:45 UTC] PHP Fatal error:  Uncaught Error: Class 'Category' not found in /var/www/youphptube/objects/configurationGenerateSiteMap.json.php:62
Stack trace:
#0 /var/www/youphptube/objects/configurationGenerateSiteMap.json.php(105): siteMap()
#1 {main}
  thrown in /var/www/youphptube/objects/configurationGenerateSiteMap.json.php on line 62
```

Any other info you require, please ask.

**Comment by DanielnetoDotCom** [comment]
I dont know how this happen, but I sent an update to make sure it will works
