### ISSUE TITLE
locale file - new words not changing   

### ISSUE THREAD

**Issue by rahmediahouse** [DanielnetoDotCom/YouPHPTube#1143]
Hi,

I want to add few translations in the locale file, I entered few of the words in the locale file, but the language change is not affecting.

Let me know, where all in the application I need to add it.

**Comment by DanielnetoDotCom** [comment]
add the translations on the lang file should be enough

**Comment by rahmediahouse** [comment]
I added it but its not reflecting, let me know will the language change for the Categories.

**Comment by rahmediahouse** [comment]
i have added few more words in the file, and for those words I have created the category. But still those category shows mean in english language.

I wanted that the category also gets changed when the language is changing.

**Comment by DanielnetoDotCom** [comment]
the words on the file are predefined on the code.
the words on the Category comes from the database. they will not be translated

**Comment by rahmediahouse** [comment]
ok.

Thanks.
