### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by rahmediahouse** [DanielnetoDotCom/YouPHPTube#1145]
There is file missing in the objects folder, the file name is videoAndroid.json.php.

Kindly share me this file.

**Comment by DanielnetoDotCom** [comment]
How do you know that?
Can you share the error?

**Comment by rahmediahouse** [comment]
It says videoAndriod.json is missing.

**Comment by DanielnetoDotCom** [comment]
What Android version?

**Comment by rahmediahouse** [comment]
Please find the below URL.

https://github.com/DanielnetoDotCom/YouPHPTube-Android

**Comment by DanielnetoDotCom** [comment]
this is not an official android app, this does not work.

I will remove this project
