### ISSUE TITLE
Need help setting up ssl from namecheap..

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1147]
I have ssl for my domain puyodead1-development.me, i got YouPHPTube and the encoder setup and working, but how do i add ssl to everything?

**Comment by Puyodead1** [comment]
i want to be able to stream

**Comment by DanielnetoDotCom** [comment]
You should ask namecheap to help you with the SSL, I dont think it is an issue related to YouPHPTube

**Comment by Puyodead1** [comment]
i already have ssl setup, what i mean is i need help setting up YouPHPTube to use ssl with live streaming

**Comment by Puyodead1** [comment]
the site uses ssl, but how do i configure live streaming?

**Comment by DanielnetoDotCom** [comment]
On the plugin parameters 

![image](https://user-images.githubusercontent.com/18009293/46973481-bd567880-d097-11e8-9f2e-bcd0cc02a6e7.png)

**Comment by Puyodead1** [comment]
Thanks
