### ISSUE TITLE
Slowness while AD_Server is enabled

### ISSUE THREAD

**Issue by rahmediahouse** [DanielnetoDotCom/YouPHPTube#1148]
Hi,

I have analyzed that when the AD_Server is enable the video performance goes slow, and when it is disabled, the video performance is faster.

**Comment by DanielnetoDotCom** [comment]
what performance?

client side performance right?

**Comment by rahmediahouse** [comment]
Yes, the client side performance.

**Comment by rahmediahouse** [comment]
Let me know how to get this improved

**Comment by DanielnetoDotCom** [comment]
I dont know if I can do much about it. 

I use google IMA https://github.com/googleads/videojs-ima on the client side

You may find help with them
