### ISSUE TITLE
Embedded Video in AD_Server

### ISSUE THREAD

**Issue by rahmediahouse** [DanielnetoDotCom/YouPHPTube#1149]
Hi,

I have embedded a video in my channel and would like to play that embedded video as an ad through the AD_Server.

I am able to add the video in the campaign, but it never runs as an AD in any of my videos across the platform.

**Comment by DanielnetoDotCom** [comment]
you can not use embed videos as ad

**Comment by rahmediahouse** [comment]
Can you do this in your next version.

**Comment by DanielnetoDotCom** [comment]
I dont think so, it is not possible.

we need direct file access to use VAST
