### ISSUE TITLE
Feature Request - Live Streaming.

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#115]
Congratulations for your work. This platform is getting very good.
My suggestion (and at the same time need) is to have a platform for Live Streaming ... similar to Youtube Live ... where you can even see direct transmissions.
In the first place, you can write this option, with in the YouPHPTube Encoder that, with the help of Nginx, can create an RTMP live streaming server (and using different clients like Adobe Flash Media Live Encoder or Wirecast, Vmix ... that point to the RTMP - YouPHPTube Encoder ) then with FFmpeg (that also this, is in YouPHPTube Encoder)  you can also transcode and record on HDD. I have an acquaintance who is using this technique with success ... but does not want to lend to others ...

  At the same time, I wonder if it is possible to embed it from other platforms such as Ustream, Youtube, Liveastram, rather than using HDD-registered files ... and grouping them, creating different live or recorded channels with different thematic.
Thanks in advance.

**Comment by DanielnetoDotCom** [comment]
I am working in a RTMP streaming.
I am having a hard time to find any webcam capture that also works on mobile devices.
I found few of them in flash, but there are some softwares that transmit mobile camera over RTMP protocol. 
If you have any suggestion about webcam capture for RTMP I will apprecciate

**Comment by tgd1973** [comment]
A bit of live streaming theory:
[Streaming theory](https://flashphoner.com/stream-rtmp-video-stream-from-the-live-encoder-on-webrtc/)

A flash player to test the links:
[Wowza test player](https://www.wowza.com/testplayers)

A database with links ... not all seem to work:
http://database.freetuxtv.net/site/index

and a link that certainly works ...
[rtmp://s5.alfaomega.tv/alfaomega/alfaomega2.sdp](url)

As I said earlier: the idea would be to have incoming rtmp connectivity from client (Wirecast, AFML, vMIX ...)  then in the server inside, to use a transcoder that at the same time transcode in mp4 format for the HTML5 player but also store the mp4 file and then play it, even after, in YouPHPTube. More or less if you can get a YouTube account on the live streaming section ... you can see the same things.

**Comment by DanielnetoDotCom** [comment]
Hi I have made some implements for Live stream, go to the demo site, login with any user.
you will se a button on the top right.
please test it and let me know what you think.
it is a beta test version :)

**Comment by tgd1973** [comment]
Hi! I just tried live webcam ... the live part about FMLE / Wirecast can not be accessed because your server give me an private address IP ... 192.168.x.x
Overall it seems very promising ... You have to find the way to do, the system for recording and sorting the video  as private / not in list / in list, of the channel.
For now I do not find your plug nowhere, so I can install it (also to be tested in live for my church). 
For me it would be more interesting to be able to install with the encoder to not stress, so much, the basic web server.
Anyway congratulations for the little time in which it was successful to do this plug.

**Comment by DanielnetoDotCom** [comment]
Hi, Thanks for your feed back.

Did you try to stream to demo site? 
if you mean 192.80.190.54 IP it is not private, it is a public one.
Recording, and make the stream private, will be also made.
The live plugin is with the full installation of YouPHPTube

Let me know if you need any help to configure it.

**Comment by tgd1973** [comment]
Hello! Right now I'm streaming Live ... and it works !!!
What I can not do from this page (https://demo.youphptube.com/plugin/Live/?u=teste) is to embed the player on another page for example another site / blog. Trying on android, the display shows ... "No compatible source was found for this media". I think that's because it sends direct rtmp which is for flash player ... without any conversion to mp4 to make it go to HTML5 player. Conversion, as I said, can be done (consuming the resources of the system with) FFmpeg. Always with FFmpeg,  can also record the broadcast.  Congratulations again for the good work !!!

**Comment by DanielnetoDotCom** [comment]
Thanks for that, I will work on it to enable it on HTML5 streaming.
very Thanks for the tips

**Comment by mikweb2017** [comment]
very Nice !

**Comment by DanielnetoDotCom** [comment]
I was looking on this article https://www.vultr.com/docs/setup-nginx-on-ubuntu-to-stream-live-hls-video
its HLS example uses a swf player as well.
I think we will be going to the same problem as RTMP.

Do you think with FFmpeg we will be able to stream to a HTML5 player?

**Comment by tgd1973** [comment]
Hello again. For some time I've talked to a guy who has this site bisericilive.com and does it for work (it offers streaming professional to churches) ... he did not tell me all he did (keeps it for him only and did not show me the code) but in great, he explained that he uses it as a relay for his services, nginx with input to RTMP ... and FFmpeg for transcoding in MP4 and saving them the file gets two flv and mp4 formats right away.  Mp4 at the time of transcoding is generated with two or three qualities then distributed with the help of a .m3u8 file, which in this way creates HLS option and is played in the Clappr player that has all these plugs loaded ... then to not force too much the web server, the Clappr player, first tries to play in flv, if it fails, use the .m3u8 file as a backup with the Clappr player with plugin for HTML5. He uses Clappr as a multi-format player. After live transmission, if  activate the DVR function, from the control panel, can record the files and the same player, until the next live broadcast, plays the saved file.
Here is an example of his player in an archive for each separate customer so in thi way can embed the archive on other sites: http://archives.bisericilive.com/gallery?cid=bisericabetelcom  e qui il player ( clappr ): 
http://embed.bisericilive.com/fullplayer?cid=bisericabetelcom&feat=archive&entry=2017/02/26.2  
If you can see something in this code you can inspire ...  Unlike this friend, I wanted to create a site for churches, with live services at no cost, similar to YouTube, which is currently being used more and more.

**Comment by DanielnetoDotCom** [comment]
Very great idea, you can count on me.
BTW, i just test the HLS / HTML5 player with success
I am just not sure what to do with the recorded file, for example some one can leave streaming a video all day long it will fill my hard drive.
any ideas?

**Comment by tgd1973** [comment]
Yes, it's true ...  but you can program a DVR function duration for a maximum length of time that can be imposed from the admin panel.

**Comment by DanielnetoDotCom** [comment]
I have tried to broadcast without record a file and for some reason it stops to work.
do you have any idea if the record file is necessary for HLS?
Also if it is necessary I will not be able to stop the DVR funciton

**Comment by tgd1973** [comment]
The MP4 file can be composed of the small files collected together in the .m3u8 file which, when exceeded a certain size, can be deleted automatically with a script ...  Here is an example of .m3u8 files that can be played in HLS mode:
 `#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=481000,CODECS="avc1.4d001f,mp4a.40.2",RESOLUTION=480x270
bisericabetelcom1/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=982000,CODECS="avc1.4d001f,mp4a.40.2",RESOLUTION=800x450
bisericabetelcom2/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1816000,CODECS="avc1.4d001f,mp4a.40.2",RESOLUTION=1280x720
`bisericabetelcom3/index.m3u8`

and this file, recalls fragments, which I said before, with different qualities, according to the customer's request from the player ...

`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:10
#EXT-X-PROGRAM-DATE-TIME:2017-02-26T17:59:38+02:00
#EXTINF:9.909,
1488124778000.ts
#EXTINF:9.944,
1488124785000.ts
#EXTINF:9.943,
1488124795000.ts
#EXTINF:9.776,
1488124805000.ts
#EXTINF:9.944,
1488124815000.ts
#EXTINF:5.972,
1488124825000.ts
#EXTINF:9.944,
1488124831000.ts
#EXTINF:9.609,
1488124841000.ts
#EXTINF:7.207,
1488124851000.ts
#EXTINF:9.944,
1488124858000.ts
#EXTINF:9.943,
1488124868000.ts 
...
...`

**Comment by DanielnetoDotCom** [comment]
Hi i could stream with out record the file, record will be an option.
The only 'issue' (not real one), is in a internal network the latency is between 15 and 30 seconds.
over the web the latency may be almost 1 minute

**Comment by tgd1973** [comment]
Now I'm using a streaming server prof. Flussonic and lag has also this server. Doing transcoding is impossible, to not have an delay in live broadcasting.

**Comment by mikweb2017** [comment]
congratulations for your work I tried on the demo site i saw your test streaming on a android phone. but in my sever it does not work yet

**Comment by DanielnetoDotCom** [comment]
Hi, I just make it work with HLS .
Like @mikweb2017 said, it is on demo site.
I will do my best to document it and make easy to others to make it running too.
It is a little bit different then RTMP

Problems I found.

1. The flash webcam streamer is not working anymore. but any other stream tool works fine.
2. The latency is much bigger then the RTMP
3. We can not count how many connected clients the server has. it regarding this: https://github.com/arut/nginx-rtmp-module/issues/420

**Comment by mikweb2017** [comment]
You have for demo site  in to plugin //live.youphptube.com:8080/stat"}  port 8080 but 

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Set-up-my-own-Stream-Server


{"button_title":"LIVE","server":"rtmp://[nigix-server]/live","playerServer":"https://[nigix-server]:444/live","stats":"http://[nigix-server]:81/stats"}"

ist port 81 ?

in your nginx conf you configured port 8080
in my server by default it works tomacat server.
can I change the port to my liking?

**Comment by DanielnetoDotCom** [comment]
I have change the ports because I have Apache and Nginx on the same server.
At the first time I have changed the Nginx HTTP port to 81, then I decide to use 8080 (it is more common). I have to update it on Wiki
HTTPS port is 443 (also used with apache), then I change Nginx HTTPS port to 444.
That is why it is so confusing.
I hope it helps you

**Comment by mikweb2017** [comment]
Tried again tomorrow here in Germany is time to sleep

**Comment by mikweb2017** [comment]
![bildschirmfoto 2017-09-24 um 19 37 57](https://user-images.githubusercontent.com/30271757/30785016-1bc125fe-a160-11e7-888b-98c9a333caaf.png)do you have any idea streaming does not work i missed something?

**Comment by DanielnetoDotCom** [comment]
I Think is becaus you mixing https with http
I can see in you address you do not have https, so just use http
for playerServer use http://live.mikweb.eu:81/

**Comment by DanielnetoDotCom** [comment]
Congratulation it is working.
just fix the playerServer and you will be fine:
I can see u :)
![image](https://user-images.githubusercontent.com/18009293/30785105-7016e202-a137-11e7-82b1-36f346dc976d.png)

**Comment by mikweb2017** [comment]
now it works thanks I tried before even with https contudo di nuvo because it does not work with https

**Comment by mikweb2017** [comment]
and edit the lines:

on_publish httpS://[YouPHPTubeURL]/plugin/Live/on_publish.php;

on_play httpS://[YouPHPTubeURL]/plugin/Live/on_play.php;

on_record_done httpS://[YouPHPTubeURL]/plugin/Live/on_record_done.php;

for  https I also have to be right here?

**Comment by DanielnetoDotCom** [comment]
yes, you right, as long you are not using https, you need to edit those lines too

**Comment by mikweb2017** [comment]
You could post the nginx.config for https I can not figure out where I'm wrong

**Comment by tgd1973** [comment]
Congratulations for the good work done !
I watched the wiki for "Set-up-my-own-Stream-Server" that brings me to a question:
Can I install the Nginx Streaming server on another PC? in order to handle the load of the main web server.

 It would be even more interesting if in the admin menu, registered users appears a line  from which admin, can choose, for each user to which streaming server to use (if there are 2 or more streaming servers ).
The issue is very important for a site in production ... to handle the loads that user generate it. One user can have 10 visitors for live streaming and another one can have 1000 ... so, for do not have buffers need to migrate some users from one server to another ...
This option can be done by creating another row in the database (row to handle from the main server admin config), with all the variables to store IPs and other parameters to use for the live streaming option,  and then assigned to each user from the  administration user menu.
![live server ](https://user-images.githubusercontent.com/15127860/30797312-c6e1f2e0-a1d5-11e7-905e-6fd4189d2eb9.png)

**Comment by DanielnetoDotCom** [comment]
I did not try yet, but I guess nginx can be in a different server.

And you idea for load balance is very good. but for future implementations :)

**Comment by mikweb2017** [comment]
when you have time i would like if i could share your configuration for SSL i tried many things but unfortunately i did not succeed.

**Comment by DanielnetoDotCom** [comment]
I have used lets encrypt .
I setup only http and the certbot tool setup the ssl for me

**Comment by mikweb2017** [comment]
Mmm i used lets encript .
Have your nginx.conf only http  setup?

**Comment by mikweb2017** [comment]
{"button_title":"LIVE","server":"rtmp://192.80.190.54/live","playerServer":"https://live.youphptube.com:444/live","stats":"http://live.youphptube.com:8080/stat"}
I dont understand  player server run https and stats run http . i m confused  sorry for to many questions

**Comment by DanielnetoDotCom** [comment]
```
 worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            hls_fragment 10s;
                            on_publish http://192.80.190.54/plugin/Live/on_publish.php;
                            on_play http://192.80.190.54/plugin/Live/on_play.php;
                            on_record_done http://192.80.190.54/plugin/Live/on_record_done.php;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name youphptube.com live.youphptube.com;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"
                    location /stats {
                            stub_status;
                    }
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }

        listen 444 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/live.youphptube.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/live.youphptube.com/privkey.pem; # managed by Certbot
            include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot

        }
    }




```

**Comment by mikweb2017** [comment]
Thanks for share your nginx.conf  i tried tomorrow .i Think i have Syntax error of my conf.ngix.

**Comment by mikweb2017** [comment]
it would be nice if you could save the livestrem and then save on the videos.

Also interesting is the ability to send an automatic post via faceboock twitter when a livestream starts

**Comment by DanielnetoDotCom** [comment]
Those are great idea, may be implemented in the future :)

**Comment by someguyincali** [comment]
Awesome work on this project.  Truly appreciate the enormous amount of time and effort this has taken.  I eagerly look forward to the ability to live stream with rtsp.  I would really like to use an RTSP streaming app for live rather than the browser.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
