### ISSUE TITLE
GoogleAds_IMA not working

### ISSUE THREAD

**Issue by aarna63** [DanielnetoDotCom/YouPHPTube#1150]
The GoogleAds_IMA plugin is installed in my website, but it is not working.

I have added the google adsense code in the site configuration , script code, but my website is still not having ads.

Kindly help.

**Comment by DanielnetoDotCom** [comment]
Hi

Does it work with the ima test URL?

You can get it on our demo site.

What is the URL you are using?

What is your website?

**Comment by DanielnetoDotCom** [comment]
Hi

Does it work with the ima test URL?

You can get it on our demo site.

What is the URL you are using?

What is your website?

**Comment by DanielnetoDotCom** [comment]
Hi

Does it work with the ima test URL?

You can get it on our demo site.

What is the URL you are using?

What is your website?

**Comment by DanielnetoDotCom** [comment]
Hi

Does it work with the ima test URL?

You can get it on our demo site.

What is the URL you are using?

What is your website?

**Comment by DanielnetoDotCom** [comment]
Hi

Does it work with the ima test URL?

You can get it on our demo site.

What is the URL you are using?

What is your website?

**Comment by DanielnetoDotCom** [comment]
Try this URL https://googleads.g.doubleclick.net/pagead/ads?ad_type=video&client=ca-video-pub-4968145218643279&videoad_start_delay=0&description_url=http%3A%2F%2Fwww.google.com&max_ad_duration=40000&adtest=on

**Comment by DanielnetoDotCom** [comment]
Try this URL https://googleads.g.doubleclick.net/pagead/ads?ad_type=video&client=ca-video-pub-4968145218643279&videoad_start_delay=0&description_url=http%3A%2F%2Fwww.google.com&max_ad_duration=40000&adtest=on

**Comment by aarna63** [comment]
I added the above URL in the plugin and in the script I have added the below code.

Attached snapshot.
![image](https://user-images.githubusercontent.com/43074792/46906633-3f259500-cf24-11e8-80c6-ea23fd8ea9a7.png)

But I am not able to view any ads box in the upper or any other side.

**Comment by DanielnetoDotCom** [comment]
What is your URL ?

**Comment by DanielnetoDotCom** [comment]
What is your site URL ?

**Comment by aarna63** [comment]
http://bhojflix.com/

**Comment by aarna63** [comment]
Kindly update

**Comment by DanielnetoDotCom** [comment]
Hi

I could not full test your site , I will only be able to do it on monday

But I could notice you are using the youphpflix2 plugin this plugin does not have AdSense on the first page but you should be able to see video AdSense before play your videos .

**Comment by ChrisSlS** [comment]
On my side IMA does not work either, with the same mistakes as on #994

**Comment by DanielnetoDotCom** [comment]
Can you guys please update (download again) you IMA plugin.

I released some updates some time ago.

**Comment by ChrisSlS** [comment]
It works for me, thank you !

**Comment by DanielnetoDotCom** [comment]
Great

**Comment by rahmediahouse** [comment]
I have downloaded the latest plugin and uploaded the same in my site.

Still I am not able to view ads in my videos and on the pages.

**Comment by aarna63** [comment]
I have downloaded the latest plugin and uploaded the same in my site.

Still I am not able to view ads in my videos and on the pages.

**Comment by aarna63** [comment]
Kindly open this issue

**Comment by DanielnetoDotCom** [comment]
Hi, you can add this code on the plugins parameter 

![image](https://user-images.githubusercontent.com/18009293/47152967-8b6e2d80-d2b4-11e8-808c-88da870e1279.png)

**Comment by aarna63** [comment]
videos ads are coming now but banners are still not being displayed.

**Comment by DanielnetoDotCom** [comment]
Try this code on your adsense field on the site configuration menu
```

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- YouPHPTube -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8404441263723333"
     data-ad-slot="3904005408"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>

```

**Comment by aarna63** [comment]
This code is able to put banner, but in this the client id and slot is yours.

I am putting the below code, what is the issue in this.

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="fluid"
     data-ad-layout-key="-fb+5w+4e-db+86"
     data-ad-client="ca-pub-1856925645031751"
     data-ad-slot="4049595574"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>

**Comment by aarna63** [comment]
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="fluid"
     data-ad-layout-key="-fb+5w+4e-db+86"
     data-ad-client="ca-pub-1856925645031751"
     data-ad-slot="4049595574"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>

**Comment by aarna63** [comment]
![image](https://user-images.githubusercontent.com/43074792/47218235-b5187900-d3c8-11e8-8c77-496a1f027ae7.png)

**Comment by DanielnetoDotCom** [comment]
Sorry, what code are you using?

You Placed 3 of them here

**Comment by aarna63** [comment]
The last one

**Comment by DanielnetoDotCom** [comment]
If it works with the code a provide and it is not working with yours, you need to check your google ads configuration. you may need to ask google support to resolve it.

**Comment by DanielnetoDotCom** [comment]
I cant guide you on that. this is google side.

But I can tell you for my codes I got both on Google Ad Sense page 

for banners that is my screen
![image](https://user-images.githubusercontent.com/18009293/47267932-9f1dcc00-d520-11e8-905f-b686ca08aa18.png)


About IMA https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Plugin:-GoogleAds_IMA---Videos-Ads-on-your-page

**Comment by aarna63** [comment]
Mine status is still as New.

I think it should be active for the ads.
