### ISSUE TITLE
Root domain installation!

### ISSUE THREAD

**Issue by fturner19** [DanielnetoDotCom/YouPHPTube#1153]
Has anyone successfully installed YouPHPTube in their root domain ("https://example.com") instead of a subdomain like the way it's installed from the script ("https://example.com/YouPHPTube")? It would be more user-friendly SEO wise with the script installed on the root domain after going through the configuration.

This is the preferred way it should be installed
![1](https://user-images.githubusercontent.com/280993/47110121-fe789500-d21d-11e8-8fc1-ffc3b170e5f5.png)

The current way it's installed from the script.
![2](https://user-images.githubusercontent.com/280993/47110179-1f40ea80-d21e-11e8-8bc1-444b495ab314.png)

Thanks in advance
Fred Turner

**Comment by nightstryke** [comment]
I have it running in my root domain just fine.

Change the **System Path to Application:**
--------------------------------------
**From:**
/var/www/html/YouPHPTube/

**To:**
/var/www/html/YouPHPTube/

**Comment by fturner19** [comment]
Greetings NightStryke,

So you're also moving the script files to: /var/www/html/ ?

Thanks in advance

**Comment by nightstryke** [comment]
Yeah just move everything in the YouPHPTube folder to the /var/www/html/ folder and it should run and install, you do not need it to run in a folder or subdomain if you don't want to.

Granted my setup is customized, but I have created a local network server before with success just following the install instructions. I seriously recommend following every step of the install instructions of the wiki here on Github before going out and experimenting with customization or customized installs.

I'm running a Web Hosting Control Panel (Similar to cPanel) to help manage apache,php, and mysql, but that's a story for another day.

**Comment by fturner19** [comment]
Thanks,
I'm about to get everything set up in a few on this puppy here.

**Comment by nightstryke** [comment]
Good Luck!
