### ISSUE TITLE
How to save user picture and channel background

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1154]
as title says i can "upload the image" but there is no way to save information in the "My Account" section.
http://prntscr.com/l83xrw

**Comment by DanielnetoDotCom** [comment]
Hi

Make sure after you select the images, you click on the save button

![image](https://user-images.githubusercontent.com/18009293/47244253-26f1c200-d3cb-11e8-9a7c-66f8cd6be9c2.png)

**Comment by Puyodead1** [comment]
i dont have a save button
![download 2](https://user-images.githubusercontent.com/14828766/47244787-c5c6f000-d3c4-11e8-990a-bcfeaf14b614.png)

**Comment by DanielnetoDotCom** [comment]
Also, I can notice you don't have the footer, looks like something is crashing

can you please check your log file at the moment you access this page?

**Comment by Puyodead1** [comment]
its working on other pages.. http://prntscr.com/l84lwu

**Comment by DanielnetoDotCom** [comment]
I mean something is crashing.

Check your log file https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by Puyodead1** [comment]
[code][19-Oct-2018 17:55:13 America/New_York] Array
(
    [0] => Array
        (
            [file] => /var/www/html/tube/objects/mysql_dal.php
            [line] => 103
            [function] => log_error
            [args] => Array
                (
                    [0] => [sqlDAL::readSql] (mysqlnd) Prepare failed: (144) Table './youPHPTube1/ip2location_db3' is marked as crashed and last (automatic?) repair failed<br>
SELECT distinct(country_name) as cn FROM  ip2location_db3 WHERE country_name != '-' ORDER BY country_name
                )

        )

    [1] => Array
        (
            [file] => /var/www/html/tube/plugin/User_Location/Objects/IP2Location.php
            [line] => 52
            [function] => readSql
            [class] => sqlDAL
            [type] => ::
            [args] => Array
                (
                    [0] => SELECT distinct(country_name) as cn FROM  ip2location_db3 WHERE country_name != '-' ORDER BY country_name
                )

        )

    [2] => Array
        (
            [file] => /var/www/html/tube/view/userPersonalInfo.php
            [line] => 52
            [function] => getCountries
            [class] => IP2Location
            [type] => ::
            [args] => Array
                (
                )

        )

    [3] => Array
        (
            [file] => /var/www/html/tube/view/user.php
            [line] => 64
            [args] => Array
                (
                    [0] => /var/www/html/tube/view/userPersonalInfo.php
                )

            [function] => include
        )

)

[19-Oct-2018 17:55:13 America/New_York] [sqlDAL::readSql] (mysqlnd) Prepare failed: (144) Table './youPHPTube1/ip2location_db3' is marked as crashed and last (automatic?) repair failed<br>
SELECT distinct(country_name) as cn FROM  ip2location_db3 WHERE country_name != '-' ORDER BY country_name[/code]

**Comment by Puyodead1** [comment]
`[19-Oct-2018 17:55:13 America/New_York] Array
(
    [0] => Array
        (
            [file] => /var/www/html/tube/objects/mysql_dal.php
            [line] => 103
            [function] => log_error
            [args] => Array
                (
                    [0] => [sqlDAL::readSql] (mysqlnd) Prepare failed: (144) Table './youPHPTube1/ip2location_db3' is marked as crashed and last (automatic?) repair failed<br>
SELECT distinct(country_name) as cn FROM  ip2location_db3 WHERE country_name != '-' ORDER BY country_name
                )

        )

    [1] => Array
        (
            [file] => /var/www/html/tube/plugin/User_Location/Objects/IP2Location.php
            [line] => 52
            [function] => readSql
            [class] => sqlDAL
            [type] => ::
            [args] => Array
                (
                    [0] => SELECT distinct(country_name) as cn FROM  ip2location_db3 WHERE country_name != '-' ORDER BY country_name
                )

        )

    [2] => Array
        (
            [file] => /var/www/html/tube/view/userPersonalInfo.php
            [line] => 52
            [function] => getCountries
            [class] => IP2Location
            [type] => ::
            [args] => Array
                (
                )

        )

    [3] => Array
        (
            [file] => /var/www/html/tube/view/user.php
            [line] => 64
            [args] => Array
                (
                    [0] => /var/www/html/tube/view/userPersonalInfo.php
                )

            [function] => include
        )

)

[19-Oct-2018 17:55:13 America/New_York] [sqlDAL::readSql] (mysqlnd) Prepare failed: (144) Table './youPHPTube1/ip2location_db3' is marked as crashed and last (automatic?) repair failed<br>
SELECT distinct(country_name) as cn FROM  ip2location_db3 WHERE country_name != '-' ORDER BY country_name`

**Comment by Puyodead1** [comment]
https://pastebin.com/11rtD9ac

**Comment by DanielnetoDotCom** [comment]
I can see that 

```
(144) Table './youPHPTube1/ip2location_db3' is marked as crashed and last (automatic?) repair failed<br>
SELECT distinct(country_name) as cn FROM  ip2location_db3 WHERE country_name != '-' ORDER BY country_name
```

try to drop that table and reinstall it thru the plugin 

![image](https://user-images.githubusercontent.com/18009293/47245748-f0b74100-d3d0-11e8-9e56-56051e701196.png)

**Comment by Puyodead1** [comment]
its fixed :) must have been something with ip2location

**Comment by Puyodead1** [comment]
Fixed, Thank you so much!

**Comment by thushy07** [comment]
@Puyodead1 
I am getting the same. i am new to this database thing,
Did you fix this issue? if you did, please let me know how did you do it? If you can paste the code to how to drop the table?
Thank you

**Comment by DanielnetoDotCom** [comment]
this is not a issue, just click on the install button and you will be fine
