### ISSUE TITLE
Cant play videos

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1155]
![screenshot_18](https://user-images.githubusercontent.com/14828766/47244811-e4c58200-d3c4-11e8-96b8-8d215a43cc4e.png)
![screenshot_19](https://user-images.githubusercontent.com/14828766/47244820-f149da80-d3c4-11e8-8fba-c87c122d4b4f.png)

**Comment by Puyodead1** [comment]
Not sure if this is related to changing the Channel name or not

**Comment by DanielnetoDotCom** [comment]
Hi, it is not related to the channel name.

It is about your SecureVideosDirectory  plugin

maybe you are not using autoplay, and the token is expiring too soon, try to increase the timeout to 60 seconds

![image](https://user-images.githubusercontent.com/18009293/47245531-109a3500-d3d0-11e8-8ed4-be83af8a7d01.png)

**Comment by Puyodead1** [comment]
Same result :/

**Comment by DanielnetoDotCom** [comment]
can you please try to disable the SecureVideosDirectory  plugin, just to make sure that is the problem?

**Comment by Puyodead1** [comment]
yes

**Comment by Puyodead1** [comment]
works without it

**Comment by Puyodead1** [comment]
![screenshot_20](https://user-images.githubusercontent.com/14828766/47246069-e9d90000-d3c9-11e8-9a80-e1da5b212f22.png)

**Comment by Puyodead1** [comment]
![screenshot_21](https://user-images.githubusercontent.com/14828766/47246076-f9584900-d3c9-11e8-9aa5-665e7cf61677.png)

**Comment by DanielnetoDotCom** [comment]
yes, you need to install xsendfile to use this plugin
that was the problem

**Comment by Puyodead1** [comment]
i did install it

**Comment by DanielnetoDotCom** [comment]
I see you installed it. what OS are you using?

can you please give me a temporary access to your site?

**Comment by Puyodead1** [comment]
Ubuntu Server 18.04, yes i can
https://puyodead1-development.me

**Comment by DanielnetoDotCom** [comment]
For some reason, I can not sign up
I will need a user

**Comment by Puyodead1** [comment]
try again, i restarted apache2

**Comment by DanielnetoDotCom** [comment]
I just notice that when you select userMustBeLoggedIn you can not sign up

**Comment by Puyodead1** [comment]
disabled it

**Comment by DanielnetoDotCom** [comment]
your video works here

**Comment by DanielnetoDotCom** [comment]
also I sent a fix for the userMustBeLoggedIn  option

**Comment by Puyodead1** [comment]
ok, i had the token stuff disabled

**Comment by Puyodead1** [comment]
when i have tried to re install the database, the whole site locks up

**Comment by DanielnetoDotCom** [comment]
It is a large database, if you do not have a good memory (at least 2 GB, you should disable it)

**Comment by Puyodead1** [comment]
i can try and re install it, maybe it just takes some time,i have about 8gb

**Comment by DanielnetoDotCom** [comment]
To give you an invalid token you should have something on your log file.

It is really strange.

Do you have any kind of CDN on it?

**Comment by Puyodead1** [comment]
nope

**Comment by DanielnetoDotCom** [comment]
I have the same plugin on https://demo.youphptube.com and it is enabled and working.

something is wrong. maybe cache on your server?

I dont know!

I have to step out now, 

if you want to share your SSH credentials on my email I can try to fix this issue with SecureVideosDirectory plugin. I will be able to look on it tomorrow

developer@youphptube.com

**Comment by Puyodead1** [comment]
Ok, thank you, i will send you an email with ssh login

**Comment by Puyodead1** [comment]
i am going to disable SecureVideoDirectory for now

**Comment by Puyodead1** [comment]
also, just to make you aware, this is showing in the log
`[19-Oct-2018 18:40:45 America/New_York] PHP Notice:  Undefined variable: destination in /var/www/html/tube/locale/de.php on line 65
[19-Oct-2018 18:40:45 America/New_York] PHP Notice:  Undefined index: format in /var/www/html/tube/locale/de.php on line 65
`

**Comment by Puyodead1** [comment]
it also wont let me stream now. obs says it cant find the channel and to check the stream key. idk if thats something with the ssl in the nginx config

**Comment by DanielnetoDotCom** [comment]
About your videos, does not play when you enable SecureVideoDirectory plugin.
It was caused because you have changed your .htaccess. 

You should tell me this first. It would save me a lot of time. 

I dont know what else your .htaccess changes may be affected.

about the NGINX ssl. you can hire me to install it for you here https://www.youphptube.com/services

**Comment by Puyodead1** [comment]
i edited the .htaccess as the SecureVideoDirectory told me to. sorry :/

**Comment by DanielnetoDotCom** [comment]
No problem, but it was wrong :) 

you added new lines instead just uncomment :)

**Comment by Puyodead1** [comment]
ahhhhhhhh ok
how can i hire you for the live stream setup?

**Comment by Puyodead1** [comment]
also, i can still right click and download videos :/

**Comment by Puyodead1** [comment]
is there a way to delete users besides via mysql?

**Comment by Puyodead1** [comment]
I also sent payment for basic setup, email stopscammersnow2018@gmail.com

**Comment by DanielnetoDotCom** [comment]
Great, I will email you on private

**Comment by DanielnetoDotCom** [comment]
About delete users, you can not delete. you can only inactivate them.

I do not recommend you to delete them, even if you are using direct mysql commands

**Comment by DanielnetoDotCom** [comment]
Done :)

![image](https://user-images.githubusercontent.com/18009293/47261843-ff742580-d4ae-11e8-8b9d-4667e6dd9e29.png)

**Comment by Puyodead1** [comment]
My encoder is stuck like this: 
![screenshot_1](https://user-images.githubusercontent.com/14828766/47269577-068e4880-d52e-11e8-8e74-35ba9cf7e8c3.png)
