### ISSUE TITLE
is Chrome on Android requesting/receiving the .webm version of a video ?

### ISSUE THREAD

**Issue by Zixim** [DanielnetoDotCom/YouPHPTube#1159]
Hi,

I have these versions of a video stored on the server : 
`_YPTuniqid_5bcdb209e13c07.47842070_HD.mp4
_YPTuniqid_5bcdb209e13c07.47842070_HD.webm`

When i play the video in Chrome for Android, I get an error 'The media playback was aborted due to a corruption problem or because the media used features your browser did not support.'

I remove the .mp4 from '/var/www/html/YouPHPTube/' directory, so that only the .webm version is present.
When i play the video again, on the Android device, the video plays normal, without error.

So, I'm guessing that Chrome for Android is trying to play the mp4 instead of the webm, and the error is occuring...

Is there a log file that would show which video file is being served ? 

Thx,
Tom.

**Comment by Zixim** [comment]
indeed, the video you linked won't play in Firefox, while the content plays perfect in Chrome.

What I would like to know and see with my own eyes is : 
_which file is being offered to the browser ?
or, which file is the browser requesting ?_

Because, normally, Chrome on Android would be asking for the webm version, but i am certain that it is being given the MP4 version.

Either way, my quick & dirty workaround is removing all the mp4 versions in the video directory.
While this works fine for an intranet usage case such as mine, this work-around would be nightmare for general usage.

**Comment by DanielnetoDotCom** [comment]
@Zixim can you please confirm if on the HTML source generated by YouPHPTube, on the video tag, it includes the webm file?

I guess it does, but I dont check it for a long time.

**Comment by Zixim** [comment]
`	<source src="http://192.168.11.139/YouPHPTube/videos/_YPTuniqid_5bd1c21179a007.30107990_HD.mp4" type="video/mp4">
	<source src="http://192.168.11.139/YouPHPTube/videos/_YPTuniqid_5bd1c21179a007.30107990_HD.webm" type="video/webm">
`

both versions are present,
Chrome is capable of mp4 playback, so the first source option would be played back.

Then the question becomes 'Why are all of my mp4 clips pruducing an error in Chrome, and not in Firefox.'

A simple fix could be to change the order of the sources, webm is the more modern codec after all. 🤔

**Comment by DanielnetoDotCom** [comment]
change order can be a solution.

but in my case only some MP4 files are crashing.

I changed the order, can you update your script and test it?

**Comment by Zixim** [comment]
it works....hopefully this won't introduce an issue for other browsers.
