### ISSUE TITLE
Video storage location

### ISSUE THREAD

**Issue by 4m3x** [DanielnetoDotCom/YouPHPTube#116]
Hi there.
Absolutely the best piece of software I have come accross in a very log time. Well done! You did extremely well.

Please help:
1. When you install, it forces you to use '/var/www/html/example.com/videos' as data folder for video storage. How can I change this? I want all my videos to be stored on a seperate volume....ie /dev/sda2/phpyoutube/videos/

2. How can I sort videos by trending(sort by most likes recently)  and popular(sort by most viewd)

Thank you in advance

**Comment by laweschan** [comment]
I guess you are using Linux as the running platform , so without change in the code (perhaps developers will do it, I not sure...) you can:
i. after installation, present the a new harddisk and mount it with the same mount point path
ii. ensure you have set the same permission, as I test, 777 mode is necessary in that moment
iii. ensure you have backup and restore the configuration.php in that mount point
iv. restart http service, done

behind this change, I would suggest for much improvement, as currently the videos just store in a flat depth path under videos/ . the filing will be complex after mass videos upload, eg. the relationship between videos, front jpg,and gif related to videos,

it would better to make a tree-organization structure, or allow selective path per categories store

Lawes

**Comment by 4m3x** [comment]
@laweschan - That would probably work as an interim, however ideally you would want to specify your own data directory...even at a stage where your site grows, and you need to move to a distributed storage architecture.

**Comment by laweschan** [comment]
@4m3x yup that's what I want, here I just replied your query "......want all my videos to be stored on a seperate volume....."
I not too famous in distributed storage .... but it would be great if path can be control (whatever per video or per category), let post it as an suggestion or enhancement and hope it can be list in roadmap by developers

cheers

**Comment by DanielnetoDotCom** [comment]
Hello everyone, thank you for the support and the ideas.
make the storage of videos one more layer, it's an idea that I already have, but however there is still time to implement it.
It will not be implemented by me yet, but who knows in the future.
But all help and ideas are welcome.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by DanielnetoDotCom** [comment]
I have find way to fix it:
take a look on that. https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Moving-videos-directory-and-securing-files-from-direct-access-to-the-video-source-file

I could with success move the videos dir.
