### ISSUE TITLE
4K Support?

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1161]
Does youphptube support 4K Videos?

**Comment by ChrisSlS** [comment]
I don't sure, but there is that : https://demo.youphptube.com/video/surrounded-by-wild-elephants-in-4k-360

**Comment by DanielnetoDotCom** [comment]
@Puyodead1 yes it does.

But you will need to configure your encoder to encode videos in 4K 

For example the public encoder encode HD videos in 720p

![image](https://user-images.githubusercontent.com/18009293/47377385-84d42180-d6cb-11e8-9486-5d13406c118e.png)

**Comment by Puyodead1** [comment]
You are not allowed see this streaming, what causes this message for users not logged in?

**Comment by DanielnetoDotCom** [comment]
- To restream you will need to do it on your NGINX configuration
- config tab , you must be an encoder admin. the first user you configure on encoder is the admin. if you miss it you will need to modify it on the database
- You are not allowed see this streaming, I guess you select the stream to be for a specific user group

Please next time create 3 issues instead use the same issue for multiple different questions

**Comment by Puyodead1** [comment]
:ok_hand:
