### ISSUE TITLE
AD manager

### ISSUE THREAD

**Issue by gchenfly** [DanielnetoDotCom/YouPHPTube#1162]
When i press the Adversing manager button, appear this error:
SELECT distinct(country_name) as cn FROM ip2location_db3 WHERE country_name != '-' ORDER BY country_name \nError : (1146) Table 'youphptube.ip2location_db3' doesn't exist

**Comment by ChrisSlS** [comment]
You need to install the tables.

![installtables](https://user-images.githubusercontent.com/37787071/47364718-485bf200-d6da-11e8-9b09-940fd15694e7.png)

**Comment by DanielnetoDotCom** [comment]
@ChrisSlS is right, you need to install the tables first

**Comment by gchenfly** [comment]
Yes.Thanks a lot.

**Comment by gchenfly** [comment]
Hi. I have new problem.
I can create ad campaign. but i can not set video ads. there seem no ad form when i want to edit videos.
![2018-10-24 7 29 11](https://user-images.githubusercontent.com/34537998/47427764-e8da1100-d7c3-11e8-8579-d1d591f104e6.png)
![2018-10-24 7 28 50](https://user-images.githubusercontent.com/34537998/47427768-ed062e80-d7c3-11e8-8510-53ddfce528f3.png)

**Comment by DanielnetoDotCom** [comment]
Did you click on the green button "Add Video" on the campaign editor?

**Comment by gchenfly** [comment]
Yes.  I have click the green button "Add Video", and add the video which uploaded.
But there is no ads display on the video. Or the video on campaign is ads video content?

**Comment by DanielnetoDotCom** [comment]
Follow this here https://github.com/DanielnetoDotCom/YouPHPTube/issues/1174#issuecomment-433200808
