### ISSUE TITLE
[6.1] ERR_RESPONSE_HEADERS_TOO_BIG on /locale/

### ISSUE THREAD

**Issue by ChrisSlS** [DanielnetoDotCom/YouPHPTube#1163]
Hey,

Can not access the url  /locale/, an error occurs.

This error is also present on the demo site:

http://demo.youphptube.com/locale/
![locale](https://user-images.githubusercontent.com/37787071/47366652-6c213700-d6de-11e8-9d9e-536ce51d80c1.png)

**Comment by DanielnetoDotCom** [comment]
Thanks

I have to take a deeper look at it, but I guess I will need to disable this function (or part of it). because now we have too many files for the script handle it
