### ISSUE TITLE
Top menu plugin error

### ISSUE THREAD

**Issue by chinli12** [DanielnetoDotCom/YouPHPTube#1164]
![screenshot_2018-10-23-15-40-08](https://user-images.githubusercontent.com/29612076/47368852-56aa0e00-d6da-11e8-818d-75b0ee71335e.png)
 If I create a menu when I click it,it will give error check the image

**Comment by ChrisSlS** [comment]
Did you install the base tables ?

**Comment by DanielnetoDotCom** [comment]
Also, make sure you update your files on github. I have fixed a similar issue couple days ago

**Comment by chinli12** [comment]
I install the table and the script is updated

**Comment by DanielnetoDotCom** [comment]
Ok, I think I found and fix this bug, I am sending updates
