### ISSUE TITLE
YouTube logo showing error 

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#1165]
Hi,

YouTube logo showing in videos but yesterday working fine no logo showing 
Pleased check attached image. 
![screenshot_20181023_223354](https://user-images.githubusercontent.com/35865505/47382831-4020a880-d714-11e8-877c-6b7e6af1f4c4.jpg)

**Comment by DanielnetoDotCom** [comment]
I have no control about youtube logo.

it is an embed video. only youtube can remove it

**Comment by gujarraju** [comment]
But before 2 days no logo showing after update logo again showing

**Comment by gujarraju** [comment]
hi,
please check 
embeded file working fine.
<iframe src="https://www.youtube.com/embed/WqUXVw0WlXc?modestbranding=1&amp;showinfo=0 frameborder=" width="560" height="315" allowfullscreen="allowfullscreen"><span style="display: inline-block; width: 0px; overflow: hidden; line-height: 0;" data-mce-type="bookmark" class="mce_SELRES_start">﻿</span></iframe>

**Comment by gujarraju** [comment]
PLEASE ADD THIS CODE IN EMBED VIDEO LIKE THIS
https://www.youtube.com/embed/WqUXVw0WlXc?**modestbranding=1&amp;showinfo=0**

**Comment by DanielnetoDotCom** [comment]
I didnt know I will send a fix

**Comment by gujarraju** [comment]
<div class="video-container">

    <iframe src="https://www.youtube.com/embed/riyqQmBHDgE?rel=0&modestbranding=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

</div

**Comment by nightstryke** [comment]
> ok, thanks

I think what he's getting at is the code `?modestbranding=1&amp;showinfo=0` added to the end of a embedded youtube video in youphptube can remove the YouTube branding. `youtube.com/embed/videoID` **to** `youtube.com/embed/videoID?modestbranding=1&amp;showinfo=0`

**Comment by gujarraju** [comment]
Not working..

**Comment by DanielnetoDotCom** [comment]
Try disable it 

![image](https://user-images.githubusercontent.com/18009293/48011533-b3f08700-e0fe-11e8-954d-c6f4688bf453.png)
