### ISSUE TITLE
Error after choosing theme

### ISSUE THREAD

**Issue by dobestar** [DanielnetoDotCom/YouPHPTube#1166]
I enabled the theme plugin, then loaded the front page and chose a Netflix theme - though I also had to choose from one of the bootswatch themes - and now the site won't load at all, and serves me a HTTP 500 eror.

**Comment by Engineer-of-Stuff** [comment]
Have you checked ligs?

**Comment by Puyodead1** [comment]
Check the logs for the error

**Comment by DanielnetoDotCom** [comment]
I recommed you to disable this plugin, it will be removed in the future
