### ISSUE TITLE
Android App not loading videos

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [DanielnetoDotCom/YouPHPTube#1167]
I've set up a server/encoder and uploaded some videos. I can confirm it works.

I connected the Android app to my account on the server. I see the videos uploaded.

When I tap on a video to watch it opens the video but does not play it. Where the video is supposed to be it is blank white.

When I tried the demo site it worked.

**Comment by DanielnetoDotCom** [comment]
did you use encoder to submit your videos?

or you direct upload them?

I recommend encoder https://github.com/DanielnetoDotCom/YouPHPTube/wiki/About-Video-Upload

**Comment by Engineer-of-Stuff** [comment]
Uploaded via the separate encoder.

**Comment by DanielnetoDotCom** [comment]
You should have no problem, I can't see a reason.
maybe is your network

**Comment by Engineer-of-Stuff** [comment]
Tried wifi and cellular. Is there anything that might be interfering?

**Comment by Puyodead1** [comment]
Check the YouPHPTube Logs on the server for errors. https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube
