### ISSUE TITLE
Distributed service

### ISSUE THREAD

**Issue by maverick74** [DanielnetoDotCom/YouPHPTube#117]
I would like to start discussions about how to make YouPHPTube work as a Distributed service beside the centralized way (based on a server).

Differences between Centralized, Decentralized and Distributed services:
![imagem](https://user-images.githubusercontent.com/14912461/30487590-cabdb55e-9a2b-11e7-9584-86c6ca29fed3.png)

a few extra links about this are:

https://decentralizedweb.net/

https://ipfs.io/

The idea is to discuss if it's possible to make it a Distributed service and, if yes, how could this be made to work...

fire away :)

**Comment by 4m3x** [comment]
@maverick74 I'd be very keen to explore changing the data storage location to an IPFS type file system.

**Comment by maverick74** [comment]
i believe it is important to not reinvent the wheel (or in another words: instead of creating a specific file system and then have the burden of maintain it, rely on one the the great projects already available)

So it becomes important to study and choose carefully one of the available services.

It would be interesting beside basing the entire software on such system, to also have a centralized edition for whoever wants to use it in that way.

Think of it as a: centralized is a short-term solution. Distributed is a medium-long term vision ;)

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by soapstreams** [comment]
Any progress on incorporating IPFS or some other decentralized file system into YouPHPTube? I wouldn't think it would too hard to incorporate ipfstube into this code. Am I wrong? Thanks.

https://ipfstube.erindachtler.me/
https://github.com/download13/ipfstube

**Comment by DanielnetoDotCom** [comment]
sorry, there is no progress on that way yet
