### ISSUE TITLE
Adding more resolution options to encoder and Switch resolution plugin

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1170]
Is there a way to add more resolution options like youtube? 
![screenshot_2](https://user-images.githubusercontent.com/14828766/47457407-fe8c0e00-d7a4-11e8-9e1b-e681ff1d07cb.png)

**Comment by DanielnetoDotCom** [comment]
Sorry, for now we support only 3 resolutions

**Comment by Puyodead1** [comment]
:( okay

**Comment by Puyodead1** [comment]
Would it be difficult to hard code more in? i have some php knowledge and the only thing that i dont understand is these parts:
```if (
            empty($advancedCustom->doNotShowEncoderResolutionLow) && empty($advancedCustom->doNotShowEncoderResolutionSD) && empty($advancedCustom->doNotShowEncoderResolutionHD)) {
        return array("mp4" => 80, "webm" => 87);
    }```
