### ISSUE TITLE
can not delete videos

### ISSUE THREAD

**Issue by gchenfly** [DanielnetoDotCom/YouPHPTube#1173]
Why i can not delete videos which has uploaded.
It bogged down in processing while delete any video.

**Comment by Puyodead1** [comment]
Check the log for errors

**Comment by gchenfly** [comment]
where is the log file?

**Comment by Puyodead1** [comment]
in the videos directory

**Comment by gchenfly** [comment]
Thanks a lot.
I find the error log:
[24-Oct-2018 17:37:57 America/Los_Angeles] Error in writeSql : (1451) Cannot delete or update a parent row: a foreign key constraint fails (`youphptube`.`vast_campaigns_has_videos`, CONSTRAINT `fk_vast_campaigns_has_videos_videos1` FOREIGN KEY (`videos_id`) REFERENCES `videos` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION), SQL-CMD:DELETE FROM videos WHERE id = ?.

And how to solve it?

**Comment by Puyodead1** [comment]
nope... i have seen that error many times also, try deleting from mysql. Although it will probs be the same error :/

**Comment by gchenfly** [comment]
Thanks.
I know the why.:)

**Comment by Puyodead1** [comment]
If solved you can close the issue

**Comment by DanielnetoDotCom** [comment]
This error means you have a ad campaign with the video you tried to delete.
you need to delete the campaign first

**Comment by gchenfly** [comment]
Yes.
But another problem, why there is no ads display on the videos which is on campaign?

**Comment by DanielnetoDotCom** [comment]
Follow this here https://github.com/DanielnetoDotCom/YouPHPTube/issues/1174#issuecomment-433200808
