### ISSUE TITLE
YouPHPTube Stream Server Installation

### ISSUE THREAD

**Issue by aermike** [DanielnetoDotCom/YouPHPTube#1176]
When try install YouPHPTube Stream Server Installation have this error: checking for zlib library ... not found ./configure: error: the HTTP gzip module requires the zlib library. You can either disable the module by using --without-http_gzip_module option, or install the zlib library into the system, or build the zlib library statically from the source with nginx by using --with-zlib=<path> option.

**Comment by DanielnetoDotCom** [comment]
try to google for that

**Comment by lunar54** [comment]
zlib1g-dev should be noted as a requirement for isntall
