### ISSUE TITLE
Weird GIF on videos...... VANGUARD

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1179]
![screenshot_4](https://user-images.githubusercontent.com/14828766/47528168-783dfd80-d872-11e8-9ef6-c33501b228c5.png)
This just creeps me out...

**Comment by DanielnetoDotCom** [comment]
Hi

this happen when the animated gif was not created yet.

create an animated gif takes time

if you want you can replace that image on encoder https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/blob/master/view/img/notfound.gif

**Comment by Puyodead1** [comment]
Creepy 🤣 thanks
