### ISSUE TITLE
Install On Godaddy

### ISSUE THREAD

**Issue by VlogSense** [DanielnetoDotCom/YouPHPTube#1181]
We want to install on Goddady, just for people to share videos from youtube etc.

No live streaming or upload, just links from video networks.

What hosting on Godaddy do we need for now?

And where is the installation instructions?

**Comment by DanielnetoDotCom** [comment]
Get at least a VPS with 2 GB RAM and 2 Cores.

Do not get a shared server

more details https://github.com/DanielnetoDotCom/YouPHPTube/wiki/YouPHPTube-hadware-requirements

**Comment by VlogSense** [comment]
I think you misunderstood. We DON'T need the live stream, just we need for people to drop video links from youtube hosted videos etc.

**Comment by DanielnetoDotCom** [comment]
You will need a encoder to extract youtube videos.
If you will use encoder you will need a VPS.

**Comment by VlogSense** [comment]
So Godadd'ys plan VPS
 2 GB memory
60 GB storage^
Unmetered bandwidth 
3 dedicated IPs
Free 1-year SSL certificate∞

will work?

How much to install and set up?

**Comment by tvmanus** [comment]
I use OVH VPS hosting. Works really well, just don't expect their support
handholding you for configuring your software.

**Comment by VlogSense** [comment]
OVH has a lot of bad reviews and bad customer support reviews.

What about bluehost? They are number one, godaddy is number 6 because of page load speed. See charts from tests since 2015 https://hostingfacts.com/

**Comment by DanielnetoDotCom** [comment]
@VlogSense 

It does work

If you hire me to install it for you I will install for you a free SSL (Letsencrypt)
You don't need 3 IPS
and If you can increase the 60 GB storage

About the installation services, please take a look here https://www.youphptube.com/services
Will be a pleasure install it for you.

**Comment by VlogSense** [comment]
will this work:
2x 2.1GHz Dedicated AMD Opteron
8GB Dedicated RAM
500GB SATA HDD
Unlimited Bandwidth (1 Gbps1)
99.9% Guaranteed Availability
1Port connection is shared with all server instances.
CentOS 7  Ubuntu 16.04 LTS
Plesk Web Admin Edition or cPanel1
Apache 2.4
MariaDB 5.5 (Plesk)
MariaDB 10.0 (cPanel)
PHP 5.6 and 7
Perl 5.16
Python 2.7

...and do i need cpanel too

**Comment by VlogSense** [comment]
No sorry, don't like the unanswered help topics they have sitting there for months.

I like LIVE 24/7.

Searching still.

**Comment by VlogSense** [comment]
wow! Bluehost turns 29.00 per month to 88.00 month after everything!

**Comment by VlogSense** [comment]
TMD has 
65GB SSD Space
4TB Bandwidth
2 CPU Cores
4GB DDR4 RAM
Fully Managed
Premium Support
cPanel/WHM

will that work?

**Comment by VlogSense** [comment]
Okay so since you will install anyways, please tell us what hosting to order from https://www.ovh.com/ca/en/vps/ ??

1. Make sure encoder for video links from other sites.

2. Have you plugin to remove the floating video?

**Comment by DanielnetoDotCom** [comment]
I don't understand your last post, but I definitely recommend Ubuntu instead Centos.

Streamer can be installed on any Server, including Windows, but the encoder and Livestream should work fine on any Linux distribution. However we recommend Ubuntu 16+ without any kind of control panel. The problem with cPanel, Plesk, Webmin, VestaCP, etc. It's because we need full root access to install some libs, and maybe compile them. Another important point is that to make Livestream work, we need to compile Nginx and the control panels often prevent us from running the commands forcing the installation available only on your panel.

**Comment by VlogSense** [comment]
Okay, what monthly VPS plan from OVH should I get, tell me which one.

I dont want to overspend, just what we need for now.

**Comment by VlogSense** [comment]
But they are Europe, if the heavy traffic will be from the USA wouldn't we be best for USA based server?

**Comment by tvmanus** [comment]
Pick Canada location. I like to use SSD VPS with 4GB of RAM. it is under
$8/mo
Keep in mind that support will handle platform related issues only, no
how-to questions will be answered. I also used SoYouStart dedicated
servers. Under $50/mo you get 2TB of storage 16GB of RAM and 4 cores of
xeon cpu.

**Comment by tvmanus** [comment]
They are physically in Canada and well connected to US segment. If you need
Europe, pick locations in France.

**Comment by VlogSense** [comment]
Ok we will pick Canada. Do you have a link so we dont get wrong package? We should go with "SSD VPS with 4GB of RAM. it is under
$8/mo" ...is that 2 core too? Well you should know, you have a site on that package?

**Comment by VlogSense** [comment]
WILL THIS WORK? 
VPS SSD 3
OpenStack KVM
2 vCore(s)
2.4 GHz
8 GB RAM
80 GB SSDNEW
Local RAID

**Comment by tvmanus** [comment]
Yes, it will work functionally. Scalability is another question.

**Comment by VlogSense** [comment]
Okay confused. Guess i have to find a programmer that can tell me what is best. thanks.

**Comment by tvmanus** [comment]
You should have no expectations to run large scale operation on a single
VPS. I use it as a private video service with 2-3 users. So you can deploy
and run it on said configuration, just don't expect take over the world
with it.
I would say you can run about a couple of dozens of streams at the same
time, in fact streaming is not using a whole lot of resources. The actual
web interface interactions are taxing the processor the most.

**Comment by VlogSense** [comment]
Ok, as i have mentioned, we just want for users to bring over links from other networks, youtube, vimeo etc so need encoder. 

No live streaming or upload for now.

So just a starter network for now.

**Comment by nightstryke** [comment]
@tvmanus is right about one thing, if you don't have a lot of HDD Space like 2TB to 3TB of Disk Space at least there's no scalability, which means if you use a 65GB SSD you could only host a few videos as your OS (Operating System i.e. Windows, Linux, etc.) takes about 20GB to 30GB which is half the drive, you'll only be able to host maybe about 100 videos as 720P videos are at the least the standard HD definition where as full HD 1080P are 3 to 4 times the filesize of 720P videos.

**Comment by VlogSense** [comment]
I don't know how many times I have to post this, looks like a dead end.

You would probably sell more services if you answered the questions.

I stated i want just for members to use their own video links, ...damn I give up.

Currently, we are on Ning.com now. 

Looks like we stay there. this youphptube doesn't want to help .

Bye.

**Comment by DanielnetoDotCom** [comment]
@VlogSense sorry, I don't understand what question is unanswered?

**Comment by nightstryke** [comment]
> Ok, as i have mentioned, we just want for users to bring over links from other networks, youtube, vimeo etc so need encoder.
> 
> No live streaming or upload for now.
> 
> So just a starter network for now.

If I get this correctly you don't want to upload videos to your server?
Even if this is the case you're still going to need a decent enough VPS while a 60GB SSD is alright I would still recommend finding something like 120GB SSD just because of Operating System Updates. If you're going to just link by YouTube and Vimeo it's possible, but you will have to manually disable direct upload. You wouldn't necessarily need to use the encoder either, but if that's what you want to do go for it.

**Comment by VlogSense** [comment]
We buy clip-bucket instead, tanks for good reply us.

**Comment by nightstryke** [comment]
> We buy clip-bucket instead, tanks for good reply us.

Clip-Bucket is a joke.
