### ISSUE TITLE
Thumbnail display issues

### ISSUE THREAD

**Issue by lucadeci** [DanielnetoDotCom/YouPHPTube#1182]
Hello everyone,
first of all congratulations for the wonderful work.

i'm trying to upload a thumbnail for embed video, upload is ok but i can't display in Back or Frontend

firefox say: image can not be displayed because it contains errors

i changed all permission from ftp but nothing 

i don't know how to fix it. 

i don't have apache, i have litespeed

Thanks in advance

**Comment by DanielnetoDotCom** [comment]
check your log file for errors

**Comment by lucadeci** [comment]
i checked but i didn't see anything 
i can upload the file youphptube.log?

**Comment by Puyodead1** [comment]
correct

**Comment by lucadeci** [comment]
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2520095/youphptube.log)

**Comment by DanielnetoDotCom** [comment]
can you please share your site URL?

https://vcstream.to is not working

**Comment by lucadeci** [comment]
www.internetmoviecafe.com

**Comment by lucadeci** [comment]
Yes the video working is the same with openload

Il giorno Ven 26 Ott 2018, 19:30 YouPHPTube <notifications@github.com> ha
scritto:

**Comment by lucadeci** [comment]
i have the same issue with direct upload or youtube link, i don't know

**Comment by lucadeci** [comment]
i don't know how to install php GD in in my host, is litespeed

i did 
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2520624/youphptube.log)

**Comment by lucadeci** [comment]
the user photo and background is ok
only the video upload jpg

**Comment by lucadeci** [comment]
GD library is ok 
i asked to host support

**Comment by lucadeci** [comment]
is the .htaccess, if i put an empty file works, but i lost other components

**Comment by lucadeci** [comment]
can you tell me what i have to change in .htaccess to ability rewrite? 
thanks

**Comment by DanielnetoDotCom** [comment]
Sorry, I never saw this error before and I can not reproduce it.

can you check what happens with this image? http://www.internetmoviecafe.com/videos/_YPTuniqid_5bd36c73c7f1a3.52525269.jpg

does it exist?

**Comment by lucadeci** [comment]
i changed all,
I installed it again and if i let the .htaccess empty shows image, but the other section obviously: error404 

i tried to change .htccess but nothing 

http://www.internetmoviecafe.com/videos/_YPTuniqid_5bd44682267614.53624100_portrait.jpg?0.0544754530769096

**Comment by DanielnetoDotCom** [comment]
but does this file exists?

what is the file size?

I guess the problem is not on your YouPHPTube, it is on your apache configuration

**Comment by lucadeci** [comment]
it doesn't exists.

i don't understand, i'm crazing, if i create an empty .htaccess works

The size is 124Kb 
resolution 620x310 


![narcos-episodio-1-stagione-1](https://user-images.githubusercontent.com/44500872/47604986-fd571d00-da00-11e8-82f1-53fa5ab8c434.jpg)

**Comment by DanielnetoDotCom** [comment]
please be clear. if the file does not exist it should not display whatever .htaccess you have.

but anyway. it is your server configuration problem.

try to install apache instead litespeed

**Comment by lucadeci** [comment]
Sorry, but i don't understand, if the problem is on server it doesn't work always.

i try to explain if you can help me. 

if i use the .htaccess in the folder youphphtube.master doesn't work
if i delete that .htaccess and i create a new empty .htaccess shows the image, but the other button doesn't work. 

i think there is something in the .htaccess (youphptube's .htaccess i mean) that i have to change but i don't know what

**Comment by DanielnetoDotCom** [comment]
I just realize one thing ...
try to comment or remove this line https://github.com/DanielnetoDotCom/YouPHPTube/blob/c6a687a649655a64c14a3ca82b21382a2501d137/.htaccess#L218

put a sharp character at the begin
`# RewriteRule ^videos/([A-Za-z0-9-_.]+)$ view/xsendfile.php?file=$1 [QSA]`

**Comment by lucadeci** [comment]
Hello, 
Sorry for the late, Now it's working but i have another problem with embed link.

When i add an openload link doesn't work, the player buffering only

**Comment by DanielnetoDotCom** [comment]
What is the embed link URL are you trying?

id it the same result on demo site?

**Comment by lucadeci** [comment]
like this:
https://openload.co/embed/qKhFWn9Mr6c/Animali_fantastici_e_dove_trovarli_%5BHD%5D_%282016%29_Bluray_1080p.mp4

is possible?

**Comment by lucadeci** [comment]
yes on demo site the same

**Comment by DanielnetoDotCom** [comment]
Try to remove the .mp4 from the link

try this https://openload.co/embed/qKhFWn9Mr6c/Animali_fantastici_e_dove_trovarli_%5BHD%5D_%282016%29_Bluray_1080p

if you leave the .mp4 the app will think it is a direct mp4 file instead a embed link

**Comment by lucadeci** [comment]
yes it's working! 
Thanks a lot 

another question: 
Is possible to create tv serie and manage episodes and see only the first in the home page?

**Comment by DanielnetoDotCom** [comment]
Sorry, I dont understand what are you asking.

please open a new issue and place details there

**Comment by lucadeci** [comment]
ok thanks
