### ISSUE TITLE
live stream online/offline not working again

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1186]
Says offline, i checked all the settings and logs and its all fine

**Comment by DanielnetoDotCom** [comment]
can you please share with me an offline stream link?

**Comment by Puyodead1** [comment]
https://puyodead1-development.me/plugin/Live/?c=Puyodead1

**Comment by DanielnetoDotCom** [comment]
Looks like fine for me

![image](https://user-images.githubusercontent.com/18009293/47648914-4a9ad200-db5a-11e8-8392-5e6a212e8ae9.png)

**Comment by Puyodead1** [comment]
![screenshot_8](https://user-images.githubusercontent.com/14828766/47654407-21317480-db61-11e8-8517-4c5f6df20b84.png)

**Comment by Puyodead1** [comment]
Thats really weird

**Comment by Puyodead1** [comment]
When i am logged out it works correctly

**Comment by LightRO** [comment]
Hello, everyone,

I'm doing pretty well so far. The stream is running and I see it too, but it remains displayed offline. I have already thinned through the other contributions, but none of them brought a solution. I use completely SSL and also the certificates. As I said, everything else works even the livestream says that it is offline, although it is not so.

Many greetings,
LightRO

**Comment by DanielnetoDotCom** [comment]
Hi, please share here your nginx rtmp stats

for example, the demo site stats is this

https://youphptube.com:444/stat

**Comment by kasunjayasinghe** [comment]
I have the same issue. Were you able to resolve this. Its streaming but shows offline
