### ISSUE TITLE
last update with unreachable page error

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#1187]
last update with unreachable page error.

logs

27-Oct-2018 16:58:30 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getPage() on boolean in /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/plugin/YouPHPTubePlugin.php:180
Stack trace:
#0 /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/plugin/YouPHPTubePlugin.php(194): YouPHPTubePlugin::firstPage()
#1 /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/view/index.php(23): YouPHPTubePlugin::getFirstPage()
#2 {main}
  thrown in /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/plugin/YouPHPTubePlugin.php on line 180
[27-Oct-2018 16:58:36 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getPage() on boolean in /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/plugin/YouPHPTubePlugin.php:180
Stack trace:
#0 /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/plugin/YouPHPTubePlugin.php(194): YouPHPTubePlugin::firstPage()
#1 /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/view/index.php(23): YouPHPTubePlugin::getFirstPage()
#2 {main}
  thrown in /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/plugin/YouPHPTubePlugin.php on line 180
[27-Oct-2018 16:59:13 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getPage() on boolean in /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/plugin/YouPHPTubePlugin.php:180
Stack trace:
#0 /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/plugin/YouPHPTubePlugin.php(194): YouPHPTubePlugin::firstPage()
#1 /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/view/index.php(23): YouPHPTubePlugin::getFirstPage()
#2 {main}
  thrown in /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/plugin/YouPHPTubePlugin.php on line 180

**Comment by DanielnetoDotCom** [comment]
I have never seen this error before, and I don’t know what cause it.
 
But I am sending an update to make sure it will not happen anymore.

**Comment by mikweb2017** [comment]
thanks  now  works  fine
