### ISSUE TITLE
how to add tow website in configuration.php

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#1189]
please check this is correct.
$global['webSiteRootURL'] = 'https://www.test.com/'; 'https://www.test1.com/';

**Comment by DanielnetoDotCom** [comment]
Sorry I dont understand what do you need

**Comment by gujarraju** [comment]
I want add 2 website in configuration.php file 

<?php
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
$global['webSiteRootURL'] = 'https://www.test.com/'; 'https://www.test1.com/';
$global['systemRootPath'] = '/var/www/html/YouPHPTube/';
$global['salt'] = '5b98ecced3faa';


$mysqlHost = 'localhost';
$mysqlPort = '3306';
$mysqlUser = 'root';
$mysqlPass = 'root';
$mysqlDatabase = 'youPHPTube';

/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';

**Comment by DanielnetoDotCom** [comment]
try to use this code 

```
// get the subdirectory, if exists
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);

$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
```

It should allow you to use it in any URL

**Comment by gujarraju** [comment]
Thanks
