### ISSUE TITLE
TopMenu editing issue

### ISSUE THREAD

**Issue by claudiovenezia** [DanielnetoDotCom/YouPHPTube#1191]
I update to the latest version, i gt the following error when trying to edit a new menu, and I cannot save it,

 TypeError: $(...).iconpicker is not a function @ line 1066 in file ...plugin/TopMenu/page/editor.php

I've just created the tables by running manually the script

**Comment by DanielnetoDotCom** [comment]
try to delete your videos/cache dir and clear your browser cache

**Comment by claudiovenezia** [comment]
tried without success,

it seems the browser is unable to download several css and js files used by html/plugin/TopMenu/page/editor.php,

specifically it looks for them in html/ whereas they are inside the folder html/view,

does it give you any clue?

**Comment by DanielnetoDotCom** [comment]
please check your log file
