### ISSUE TITLE
mail issue contact not working correct 

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#1192]
Hi,

Today i open contact 
https://demo.youphptube.com/contact
filled the from
![test1](https://user-images.githubusercontent.com/35865505/47667856-7486df80-dbc0-11e8-8e18-d6d725990fff.jpg)
after sent you. But why received  in my mail box
![test2](https://user-images.githubusercontent.com/35865505/47667929-9aac7f80-dbc0-11e8-9eb4-e87905baa7b8.jpg)

**Comment by DanielnetoDotCom** [comment]
You are right sorry.
The problem was because I use the same script to share videos and send the contact form.

It is fixed now, thanks

**Comment by ChrisSlS** [comment]
Hey @DanielnetoDotCom 

Problem, the message is still sent on the e-mail of the sender. However, if we replace the address on the form, it works.

![bog](https://user-images.githubusercontent.com/37787071/47689246-66998480-dbe9-11e8-827a-6fca9428981f.png)

There is a bug with the admin user. If the mail account is different from the mail used for SMTP, it does not work and it is sent to the e-mail of the sender.

I do not understand, it worked well before, is it doing something wrong? Still, I did not touch the configuration (SMTP works fine).

**Comment by ChrisSlS** [comment]
I just realized that if an unauthenticated user sends a message, it works. Otherwise, he receives his own message, as explained above (see the screen)

**Comment by DanielnetoDotCom** [comment]
You right, sorry sending another fix

**Comment by ChrisSlS** [comment]
Thanks  :+1:
