### ISSUE TITLE
[Suggestion] select or upload custom thumbnail

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1193]
As title says, a custom thumbnail would be cool.

**Comment by DanielnetoDotCom** [comment]
It exists on the video manager 

![image](https://user-images.githubusercontent.com/18009293/47725933-493fd700-dc38-11e8-90d9-50c06007b58c.png)

**Comment by Puyodead1** [comment]
0_0 nice
