### ISSUE TITLE
Missing Save Button on Profile Page

### ISSUE THREAD

**Issue by gillesps01** [DanielnetoDotCom/YouPHPTube#1194]
There is no save button on the My Account page.  Have tried Firefox, Chrome and IE.

**Comment by DanielnetoDotCom** [comment]
Probably you have an error. I can see that when people miss to install the user Location plugin

`cd /var/www/html/Dropbox/htdocs/YouPHPTube/plugin/User_Location/install && unzip install.zip`

then click on the install button

**Comment by gillesps01** [comment]
That fixed my problem.  Thank you for the quick reply.
