### ISSUE TITLE
No direct upload

### ISSUE THREAD

**Issue by gchenfly** [DanielnetoDotCom/YouPHPTube#1197]
Something weird!
When i want to upload video direct from my pc,
There is no direct upload menu in the dropdown suddenly.
But several days ago, it existed!

**Comment by DanielnetoDotCom** [comment]
@Puyodead1 is correct

![image](https://user-images.githubusercontent.com/18009293/47785789-819eee00-dce8-11e8-9539-67c14396c9e1.png)

**Comment by gchenfly** [comment]
Yes, thanks.
New problem, now i can not change site logo response in Site Configurations page.

**Comment by DanielnetoDotCom** [comment]
make sure you clear your browser cache after change the logo
