### ISSUE TITLE
I can't upload videos and audios as a regular user!!

### ISSUE THREAD

**Issue by meiti** [DanielnetoDotCom/YouPHPTube#12]
Hi

When I login as a regular user and click on "Video and Audio Upload" link, it opens user profile page.

Is it a bug or am I doing something wrong?

**Comment by DanielnetoDotCom** [comment]
Hi, thanks for your comment.
By default only admin can upload videos. but you can change that on the site configuration page.
Open the menu ...
![image](https://cloud.githubusercontent.com/assets/18009293/26003153/48a44d0c-3708-11e7-9f46-ff786fa8f799.png)

in the regular configuration tab, change the option (Authenticated users can upload videos) to Yes

![image](https://cloud.githubusercontent.com/assets/18009293/26003222/757372fe-3708-11e7-8f1d-4f6d8d35757a.png)

I Hope it help you

**Comment by meiti** [comment]
Thank you.
