### ISSUE TITLE
Youtube downloader installion

### ISSUE THREAD

**Issue by afgtube** [DanielnetoDotCom/YouPHPTube#120]
Hello 
How to install youdtube dl on cpanel. I have account from arvixe,
 Can someone help me.

**Comment by DanielnetoDotCom** [comment]
you need an ssh and root access to install youtube-dl

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
