### ISSUE TITLE
Audio Playback Issues

### ISSUE THREAD

**Issue by JSY-Ben** [DanielnetoDotCom/YouPHPTube#1200]
Hi There! First of all, thanks for such a great product, we use it at our local Media College and have bought a few of the plugins, and it works great.

Just a small issue though. Since we updated to 6.1 (We were on one of the 5.* versions before, i forget which one) audio playback is now an issue. We can upload MP3s either direct, or through the encoder and they encode, and go to the videos directory correctly, and play back fine in a file browser, however when we try to play them back on the site, the player doesn't appear. The following errors appear in the browser console.....

<img width="2546" alt="screenshot 2018-10-31 at 2 25 26 pm" src="https://user-images.githubusercontent.com/13555701/47794905-508ae180-dd19-11e8-989d-093d7137a46a.png">
<img width="2550" alt="screenshot 2018-10-31 at 2 36 12 pm" src="https://user-images.githubusercontent.com/13555701/47795359-5a611480-dd1a-11e8-9dd3-c00510d2adb6.png">

The obvious one to notice it that it says it can't find the Wavesurfer plugin, but it's definitely there. However even if i disable Wavesurfer, this appears instead.

<img width="317" alt="screenshot 2018-10-31 at 2 30 39 pm" src="https://user-images.githubusercontent.com/13555701/47795069-a8c1e380-dd19-11e8-91c1-f886f0d0fdb3.png">

The media file itself is fine, and already uploaded audio files that did work in previous versions come up with the same error now. I did empty the caches folder as was suggested. the .log files don't report anything wrong.

Any ideas?

Many thanks :)

**Comment by mikweb2017** [comment]
i have same issue...

**Comment by JSY-Ben** [comment]
> i have same issue...
> 
> but if it takes embed link it works.
> 
> https://you-tube.eu/vEmbed/50

Oh yeah same here! The embed link does play back properly. Well noticed!

**Comment by JSY-Ben** [comment]
Hello

Sorry to bump this thread, but we are still having this issue and our college is really needing this facility to work soon. I am happy to donate to the project if this will allow this to be looked at :)

**Comment by DanielnetoDotCom** [comment]
Hi @JSY-Ben 

can you please detail how are you submitting the audio files?

Direct upload? Encoder?

what file format?

**Comment by JSY-Ben** [comment]
Hi again :)

Every way possible. Direct upload as MP3 or WAV, which appears as audio in the video manager, but then won't play and shows the errors as seen above. I'll use the encoder to upload an MP3, and it will upload and attempt to encode. It will appear in Video Manager as a video, and is stuck on 'Encoding'. Same if i press the 'Extract Audio' button on the encoder. This is the same on my installation and i tested it on your demo site and the same :)

Many thanks, 
Ben

**Comment by JSY-Ben** [comment]
Oh sorry one more thing to add, as seen above, if you do a direct upload as MP3, it will play in an embedded iframe that you get from the share button, just not on the main player itself.

**Comment by DanielnetoDotCom** [comment]
I sent a fix, please try now.

**Comment by DanielnetoDotCom** [comment]
Please try again

**Comment by JSY-Ben** [comment]
This is now all working perfectly. Thank you very much for your quick help :) Expect a donation from me in a few minutes. Thanks again.

**Comment by DanielnetoDotCom** [comment]
Donation received, thanks for supporting us
