### ISSUE TITLE
streming no work after update

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#1201]
sorry daniel now new issue
after update streming  no wok 

Nginx restart and  key update  on OBS 

![bildschirmfoto 2018-10-31 um 18 04 14](https://user-images.githubusercontent.com/30271757/47805484-b4bc9e00-dd37-11e8-874c-639a5feddc36.png)

logs

2018/10/31 18:03:51 [error] 3461#0: *169 open() "/HLS/live/5bd9e07778c85/index.m3u8" failed (2: No such file or directory), client: 91xxxxxxxx, server: you-tube.eu, request: "GET /live/5bd9e07778c85/index.m3u8 HTTP/1.1", host: "you-tube.eu:444", referrer: "https://you-tube.eu/plugin/Live/"
2018/10/31 18:03:52 [error] 3461#0: *169 open() "/HLS/live/5bd9e077ab98f/index.m3u8" failed (2: No such file or directory), client: 91.xxxxxxxx server: you-tube.eu, request: "GET /live/5bd9e077ab98f/index.m3u8 HTTP/1.1", host: "you-tube.eu:444", referrer: "https://you-tube.eu/plugin/Live/"
2018/10/31 18:03:52 [error] 3461#0: *169 open() "/HLS/live/5bd9e0785865e/index.m3u8" failed (2: No such file or directory), client: 91.xxxxxxxx server: you-tube.eu, request: "GET /live/5bd9e0785865e/index.m3u8 HTTP/1.1", host: "you-tube.eu:444", referrer: "https://you-tube.eu/plugin/Live/"
2018/10/31 18:03:53 [error] 3461#0: *169 open() "/HLS/live/5bd9e078f0167/index.m3u8" failed (2: No such file or directory), client: 91.xxxxxxx, server: you-tube.eu, request: "GET /live/5bd9e078f0167/index.m3u8 HTTP/1.1", host: "you-tube.eu:444", referrer: "https://you-tube.eu/plugin/Live/"
2018/10/31 18:04:09 [info] 3461#0: *223 client connected '91xxxxxxxxx'
2018/10/31 18:04:09 [info] 3461#0: *223 connect: app='live' args='p=422bd6c43a9aeab238590ca4cb9207c5' flashver='FMLE/3.0 (compatible; FMSc/1.0)' swf_url='rtmp://you-tube.eu/live?p=422bd6c43a9aeab238590ca4cb9207c5' tc_url='rtmp://you-tube.eu/live?p=422bd6c43a9aeab238590ca4cb9207c5' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 91.xxxxxxx server: 0.0.0.0:1935
2018/10/31 18:04:09 [info] 3461#0: *223 createStream, client: 91.xxxxxxxxxserver: 0.0.0.0:1935
2018/10/31 18:04:09 [info] 3461#0: *223 publish: name='5bd9e078f0167' args='' type=live silent=0, client: 91.65.186.233, server: 0.0.0.0:1935
2018/10/31 18:04:09 [info] 3461#0: *223 notify: publish 'you-tube.eu/plugin/Live/on_publish.php', client: 91.xxxxxxxxxx, server: 0.0.0.0:1935
2018/10/31 18:04:09 [info] 3461#0: *223 disconnect, client: 91.65.186.233, server: 0.0.0.0:1935
2018/10/31 18:04:09 [info] 3461#0: *223 deleteStream, client: 91.65.186.233, server: 0.0.0.0:1935
2018/10/31 18:12:24 [info] 3461#0: *342 client connected '91.65.186.233'
2018/10/31 18:12:24 [info] 3461#0: *342 connect: app='live' args='p=422bd6c43a9aeab238590ca4cb9207c5' flashver='FMLE/3.0 (compatible; FMSc/1.0)' swf_url='rtmp://you-tube.eu/live?p=422bd6c43a9aeab238590ca4cb9207c5' tc_url='rtmp://you-tube.eu/live?p=422bd6c43a9aeab238590ca4cb9207c5' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 91.xxxxxxx, server: 0.0.0.0:1935
2018/10/31 18:12:24 [info] 3461#0: *342 createStream, client: 91.xxxxxxxx, server: 0.0.0.0:1935
2018/10/31 18:12:24 [info] 3461#0: *342 publish: name='5bd9e078f0167' args='' type=live silent=0, client: 91xxxxxxxxxxx, server: 0.0.0.0:1935
2018/10/31 18:12:24 [info] 3461#0: *342 notify: publish 'you-tube.eu/plugin/Live/on_publish.php', client: 91.xxxxxxxx, server: 0.0.0.0:1935
2018/10/31 18:12:24 [info] 3461#0: *342 disconnect, client: 91.xxxxxx, server: 0.0.0.0:1935
2018/10/31 18:12:24 [info] 3461#0: *342 deleteStream, client: 91xxxxxx, server: 0.0.0.0:1935
2018/10/31 18:12:33 [info] 3461#0: *347 client connected '91.xxxxxxxxx
2018/10/31 18:12:33 [info] 3461#0: *347 connect: app='live' args='p=422bd6c43a9aeab238590ca4cb9207c5' flashver='FMLE/3.0 (compatible; FMSc/1.0)' swf_url='rtmp://you-tube.eu/live?p=422bd6c43a9aeab238590ca4cb9207c5' tc_url='rtmp://you-tube.eu/live?p=422bd6c43a9aeab238590ca4cb9207c5' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 91xxxxxxxx, server: 0.0.0.0:1935
2018/10/31 18:12:33 [info] 3461#0: *347 createStream, client: 91.xxxxxxxxx, server: 0.0.0.0:1935
2018/10/31 18:12:33 [info] 3461#0: *347 publish: name='5bd9e078f0167' args='' type=live silent=0, client: 91.65.186.233, server: 0.0.0.0:1935
2018/10/31 18:12:33 [info] 3461#0: *347 notify: publish 'you-tube.eu/plugin/Live/on_publish.php', client: 91.65.186.233, server: 0.0.0.0:1935
2018/10/31 18:12:33 [info] 3461#0: *347 disconnect, client: 91.xxxxxxxx, server: 0.0.0.0:1935
2018/10/31 18:12:33 [info] 3461#0: *347 deleteStream, client: 91xxxx, server: 0.0.0.0:1935

**Comment by mikweb2017** [comment]
you have fixed with version 3.0

**Comment by DanielnetoDotCom** [comment]
Sorry, I was about to write you this
