### ISSUE TITLE
DB Upgrade v.4.9 fails

### ISSUE THREAD

**Issue by birdie60** [DanielnetoDotCom/YouPHPTube#1202]
I tried to upgrade YPT, but got an error while upgrading DB from 4.8 to 4.9.
I was able to recognise the reason:
In file updatedb/updateDb.v4.9.sql there is a "`ALTER TABLE` `configurations``"missing, just before the CHANGE lines.
Please fix that, as it may prevent upgrade for some people.
Thx for all your hard work!
Siegfried

**Comment by DanielnetoDotCom** [comment]
you right thanks for notice it
