### ISSUE TITLE
"My Videos" don't show anyting

### ISSUE THREAD

**Issue by birdie60** [DanielnetoDotCom/YouPHPTube#1203]
When I open <site name>/mvideos, there are no files shown. I'm logged in and site administrator. In the list area, a message is dispayed "No results found!".
Am I the only one with this error? All other views show correctly.

**Comment by DanielnetoDotCom** [comment]
check your log please

**Comment by DanielnetoDotCom** [comment]
I have no idea, must be something on your log file

make sure you checked the right log https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by birdie60** [comment]
Yes, I checked that log. I disabled Themes Plugin to see if it's related.
Now I have these lines at the end of this file:
[01-Nov-2018 19:56:20 Europe/Berlin] Start Login Request
[01-Nov-2018 20:30:43 Europe/Berlin] Plugin Not Found: CountryRedirect
[01-Nov-2018 20:38:14 Europe/Berlin] Plugin Not Found: CountryRedirect
[01-Nov-2018 20:39:06 Europe/Berlin] Plugin Not Found: CountryRedirect
[01-Nov-2018 20:39:39 Europe/Berlin] Plugin Not Found: CountryRedirect

/mvideos in list area first shows "loading...", then after a while "no results found". But I have hundreds of video files. Can you tell me what backend function should populate this list?

**Comment by birdie60** [comment]
Maybe the youphptube.js.log is of interest here. I have many lines like this:
`[01-Nov-2018 20:51:59 Europe/Berlin] [aEC] JS-Err: Uncaught ReferenceError: loadPlayLists is not defined @ line 2 in file (mysitename)/view/js/jquery-3.3.1.min.js at visit on /cat/doku/?firstPage=Default`

**Comment by ChrisSlS** [comment]
on your site, you change languages by default (us) ? If so, it may come from that, because some time ago I had the same problem and by modifying my language file it was working again.

**Comment by birdie60** [comment]
Thank you for the hint, Chris. Yes, my site has "de" as default language.
I changed language in the frontend to "us", logged out and in again, but still no luck with /mvideos :-(

Another test I did was to set property "isAdmin" to 0 in the database. Still no videos shown in /mvideos. So, no, it has nothing to do with being administrator.

Another idea: Could it be that some misformatted content in the video database cause the problem? E.g. some German Umlaute (äöü) in title or filename or description? Or a blank or apostrophe at the wrong place? How would I find out the root cause of this error?

**Comment by ChrisSlS** [comment]
Indeed.

With admin, what do you see in /charts ?

**Comment by birdie60** [comment]
In /charts, an administrator would see everything he could think of, and then some more! :-)
It really is only in /mvideos where there is problem. Even view /objects/videos.txt.php?type=seo (Download your videos list) has all video URLs.
What else could I do to find the culprit?

**Comment by birdie60** [comment]
New input, so someone can solve this puzzle:

I started a AJAX debugger in my browser, when I clicked "My Videos". Then I looked for the line
`POST videos.json.php`

This is the result I got:
**SyntaxError: JSON.parse: unexpected character at line 1 column 54 of the JSON data**
`{  "current": 1,"rowCount": 10, "total": 651, "rows":}`

So backend script videos.json.php does not produce any rows and stops unexpectedly instead.
The question is why?

**Comment by birdie60** [comment]
OK I investigated this issue further and could find and solve the problem.

It had to do with misformatted video titles and descriptions in the database (wrong character set), that led to error `JSON_ERROR_UTF8` of `json_encode()` function in `videos.json.php`, which is not handled by the code in v.6.1.

My quick  workaround was to `utf8_encode()` title and description, before call to `json_encode()`. Better will be to convert all titles and description to the right character set.

Hope this helps someone with same problem.

**Comment by DanielnetoDotCom** [comment]
I see, thanks

can you please specify what was the character that makes your videos list fail?

I would like to make some tests

**Comment by birdie60** [comment]
Sure. One question first, @DanielnetoDotCom, if I may. What are the settings in ConfigurationAdvanced plugin for, called `utf8Encode `and `utf8Decode `for? When would you set these? I did not find any documentation in https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Advanced-Customization-Plugin

The problematic characters are all German Umlaute, e.g. äöüÄÖÜ and ß, as well as some apostrophes. As the strings in the database are in character set ISO-8859-1 (I think), and AJAX / javascript wants all strings in UTF8, there needs to be some encoding.

I had best results for the video title in videos.json.php when I did this:
`$videos[$key]['title'] = utf8_encode(htmlentities($videos[$key]['title']));`

Then, the title would display correctly in /mvideos.
