### ISSUE TITLE
Your post_max_size is 0, it must be at least 100M

### ISSUE THREAD

**Issue by birdie60** [DanielnetoDotCom/YouPHPTube#1204]
In configuration check in site Configurations I get:
`Your post_max_size is 0, it must be at least 100M`"

According to PHP documentation in php.ini file, this is wrong. "Its value may be 0 to disable the limit."
So you should check for 0 and regard it as OK (green).

**Comment by DanielnetoDotCom** [comment]
I see, thanks, to proceed the installation just ignore it and install
