### ISSUE TITLE
Security breach in videos.json.php

### ISSUE THREAD

**Issue by birdie60** [DanielnetoDotCom/YouPHPTube#1207]
In an AJAX debugger I found that password hashes are sent over the wire inadvertently. Please fix that, as it compromises security.

My patch in file `videos.json.php` , version v.6.1, is:

```
foreach ($videos as $key => $value) {
    // unset($value['password']);
    // unset($value['recoverPass']);
    $videos[$key]['password'] ='';
    $videos[$key]['recoverPass'] = '';
```
unset seems not to work as expected here.

**Comment by DanielnetoDotCom** [comment]
Thanks for noticing it, I am sending a fix

**Comment by birdie60** [comment]
Thanx for fast reaction, @DanielnetoDotCom.
You should remove the two existing `unset` lines, too, just after:
```
foreach ($videos as $key => $value) {
    unset($value['password']);
    unset($value['recoverPass']);
```
