### ISSUE TITLE
Fullscreen button missing from the player

### ISSUE THREAD

**Issue by takleung** [DanielnetoDotCom/YouPHPTube#1208]
Hi,

When I tried to embed the vimeo video link, it supposes fullscreen mode should be enabled. But the button is missing after embed. Could you help on this?

https://vimeo.com/298132369

<iframe src="https://player.vimeo.com/video/298132369" width="640" height="352" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

Thanks,
Ray

**Comment by DanielnetoDotCom** [comment]
Hi

I don't think it is regarding YouPHPTube

https://help.vimeo.com/hc/en-us/articles/115015759768-Fullscreen-button-missing-from-the-player

**Comment by takleung** [comment]
Hi Daniel,

Thank you for your quick replied. I've checked those 5 points setting are fine as well. But it is still not working. May I know if I should use function of "Embed a video link" and key in "https://vimeo.com/298132369" be good enough?

![screen shot 2018-11-05 at 11 12 36 pm](https://user-images.githubusercontent.com/208190/48006760-1ecaae00-e151-11e8-99f4-ed191d9cea56.png)

Thanks,
Ray

**Comment by DanielnetoDotCom** [comment]
Try to check this option

![image](https://user-images.githubusercontent.com/18009293/48010966-69bad600-e0fd-11e8-8584-934db445a9f0.png)
