### ISSUE TITLE
email / smtp configuration

### ISSUE THREAD

**Issue by ekc-fr** [DanielnetoDotCom/YouPHPTube#1209]
hi 
first thanks for this application .

I have a problem with the smtp configuration:
I use a centos7.4 server (with php7.1 and mariadb 5.5)
Postfix version 2.10.1 (with a smtp relay on my private network) 
I can send email in command line with root

i can't find the configation to send mail with localhost as smtp server
I try this configuration but it doen't work:
![2018-11-05_163406](https://user-images.githubusercontent.com/44778782/48007832-b3fd8080-e118-11e8-8a5a-eee5baaadd1c.png)

the email doen't arrive 

what's the configuration of youphptube for using postfix on localhost ?

**Comment by DanielnetoDotCom** [comment]
Hi

SMTP, try this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Setting-up-YouPHPTube-to-send-emails

**Comment by ekc-fr** [comment]
this is the wiki to configure postfix, i am ok with postfix, it works on my server
but i don't know how to configure the smtp in youphptube for using localhost

**Comment by DanielnetoDotCom** [comment]
Sorry, we do not support email server configuration.

**Comment by sharad22gupta** [comment]
> this is the wiki to configure postfix, i am ok with postfix, it works on my server
> but i don't know how to configure the smtp in youphptube for using localhost

Hey did you find the solution to this?
