### ISSUE TITLE
can nginx install ?

### ISSUE THREAD

**Issue by xuelainiao** [DanielnetoDotCom/YouPHPTube#121]
my web have run nginx , I want to install this project with nginx

**Comment by DanielnetoDotCom** [comment]
I have never install in on Nginx, but some users already made it: https://github.com/DanielnetoDotCom/YouPHPTube/issues?utf8=%E2%9C%93&q=nginx
they may help you

**Comment by DanielnetoDotCom** [comment]
check this: https://github.com/DanielnetoDotCom/YouPHPTube/issues/25

**Comment by xuelainiao** [comment]
nice！ thank you ~~~~~~

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by polfejs** [comment]
Hi Lads,

Can be installed on nginx or apache only ? 

I have issues with nginx install and ports. I was able to install youphptube on apache but livestream not working with apache

Please help

**Comment by DanielnetoDotCom** [comment]
The livestream requires a compiled version of Nginx
