### ISSUE TITLE
Cannot save youtube-dl in usr/local/bin

### ISSUE THREAD

**Issue by RapFan89** [DanielnetoDotCom/YouPHPTube#1211]
Hi,
i'm using a vps without root access, so i don't have write permissions on certain folders.
Can i instruct the YouPHP-Encoder to search youtube-dl into a different path?

Thanks.

**Comment by DanielnetoDotCom** [comment]
you will need root access.

to change path you will need to inspect the php code to see where to change (NOT recomended)
