### ISSUE TITLE
Don't know what I did: video urls now are this way: /v/132

### ISSUE THREAD

**Issue by Criptos** [DanielnetoDotCom/YouPHPTube#1213]
I really don't know what I did, biut now my video urls instead of nice friendly urls are like that... 
 
Which one is the option to re enable nice urls?

**Comment by DanielnetoDotCom** [comment]
I guess you checked this 

![image](https://user-images.githubusercontent.com/18009293/48300218-27f0ad80-e4b8-11e8-80cd-09dce846c361.png)
