### ISSUE TITLE
Encoder Processes Different Video

### ISSUE THREAD

**Issue by jimmyk1** [DanielnetoDotCom/YouPHPTube#1214]
Why is it when I load a youtube video into the encoder or go live the results are an entirely different video as the output? Any tips??

**Comment by DanielnetoDotCom** [comment]
can you please give more details what is the problem?

**Comment by harismaqsood** [comment]
hi can some tell me how can add encoder in youphptube

**Comment by DanielnetoDotCom** [comment]
what do you mean add?
try this https://tutorials.youphptube.com/video/streamer-and-encoder

**Comment by jimmyk1** [comment]
I go to the encoder and choose share videos, from web and put in a youtube link and click share. It goes through the process to convert but the video is different from one I put in. Same with going live. I go live and the results are a different video from what I was doing live. I can't figure out why. Is there a cache I should clear or something?

**Comment by DanielnetoDotCom** [comment]
you probably are using a wrong link, share the link here and also test it on encoder

**Comment by harismaqsood** [comment]
some videos extension not supported youphptube like.. mkv etc so i want to
install encoder for movie
