### ISSUE TITLE
Video search by hidden keywords

### ISSUE THREAD

**Issue by takleung** [DanielnetoDotCom/YouPHPTube#1215]
Hi,

Will it be possible to input some keywords can search video but those keywords hidden by viewers?

Thanks,
Ray

**Comment by DanielnetoDotCom** [comment]
I see, and understand now.

I am thinking to improve in the feature adding tags support on YouPHPTube, I guess it will work the way you described.

**Comment by takleung** [comment]
Thank you Daniel, so currently work around. I need to add keywords on description field. Correct me if I am wrong.

**Comment by DanielnetoDotCom** [comment]
yes, it may work, but users will be able to see it when the access the video

**Comment by takleung** [comment]
Get it and thanks Daniel

Ray
