### ISSUE TITLE
AWS S3 not working error 500

### ISSUE THREAD

**Issue by benjaminlecerf** [DanielnetoDotCom/YouPHPTube#1217]
hello

when i upload a video to my server is work but don't upload to my S3 and the picture of the videos is "404 not found" and when i test this link : http://tubee.fr/plugin/AWS_S3/test.php i have a error 500 and in command line with php command : "PHP Notice:  Undefined index: SERVER_NAME in /var/www/html/videos/configuration.php on line 7" and my config : http://prntscr.com/li1r0i.

thank you and sorry for my bad english i am french

**Comment by DanielnetoDotCom** [comment]
Hi, 

I do not think the problem on the SERVER_NAME is causing this.

try to replace your line 7 on your configuration file for this:

`$global['webSiteRootURL'] = 'http://tubee.fr/';` Then the PHP Notice should gone.

please share your log file, we may find the error there

**Comment by benjaminlecerf** [comment]
Hello,

is working a little now is show you must to be admin , i log in and refresh and error 500, Where is the error log ? I am on apache2

thank you

**Comment by benjaminlecerf** [comment]
my config file
[apache2.zip](https://github.com/DanielnetoDotCom/YouPHPTube/files/2579704/apache2.zip)

**Comment by DanielnetoDotCom** [comment]
Hi

I need to see your error log file, the conf does not help much.

Please try this: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by benjaminlecerf** [comment]
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2580564/youphptube.log)
 my log file
thank you

**Comment by benjaminlecerf** [comment]
I have tested on a S3 aws but not working
"[Bucket] must be a string or an object that implements __toString(). Found bool(true) in /var/www/html/plugin/AWS_S3/aws/Aws/Api/Validator.php:65"
and the bucket_name on the panel is : bendevphp

**Comment by DanielnetoDotCom** [comment]
how is your plugin configuration?

please remove the endpoint configuration

**Comment by benjaminlecerf** [comment]
Hello

thank you i have reinstall the plugins and it's work now

thank you

**Comment by DanielnetoDotCom** [comment]
that is great, thanks for the feed back
