### ISSUE TITLE
Error when i try to install 

### ISSUE THREAD

**Issue by alidz1982** [DanielnetoDotCom/YouPHPTube#122]
Hello, im trying to install but i get this error

**Comment by alidz1982** [comment]
Sorry!
Error creating admin user: Unknown column 'user' in 'field list'

**Comment by DanielnetoDotCom** [comment]
could you please update your files from github, drop your database and try again?

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
