### ISSUE TITLE
Error accessing the encoder

### ISSUE THREAD

**Issue by OSGAJim** [DanielnetoDotCom/YouPHPTube#1220]
Hey Daniel.

We have been struggling to get the Gamblersworld.com server all working properly. We do have the YouPHPTube program working . . . for the most part.

When we try to upload a video using the Encode Video and Audio option we get the following error:

SELECT f., e. FROM encoder_queue e LEFT JOIN formats f ON f.id = formats_id WHERE (status = 'encoding' OR status = 'downloading' OR status = 'queue' OR status = 'error') ORDER BY priority ASC, e.id ASC \nError : ()

Using the direct import local video option, does not seem work at all. 

You can however, Embed a video link and it works. All videos do play flawlessly.

This was all working and seems to have broken recently.

Thanx
Jim

**Comment by DanielnetoDotCom** [comment]
Really strange I have never seen this error before.

try to update your files and try again
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

if still error please share your error log
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by OSGAJim** [comment]
Hi Daniel.

We have played around with this some more and still cannot get it to use our Encoder. The program does work with the Encoder located at YouPhPTube.com. 

[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2650797/youphptube.log)

**Comment by DanielnetoDotCom** [comment]
the only thing I can see is that:

mysqli::__construct(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES) in /var/www/html/YouPHPTube/Encoder/objects/include_config.php on line 8

make sure you have mysql proper configured
