### ISSUE TITLE
embeded video name automatic changed 

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#1221]
Hi,

Today i found error if i embed video from youtube after rename description or video name and save it 
then video name automatic change.
![error](https://user-images.githubusercontent.com/35865505/48548687-0abc4480-e8e7-11e8-89ad-c8e6d26758ab.jpg)

**Comment by DanielnetoDotCom** [comment]
You right, thanks I just sent a fix
