### ISSUE TITLE
Where to find documentation on free plugins?

### ISSUE THREAD

**Issue by birdie60** [DanielnetoDotCom/YouPHPTube#1222]
Hello Daniel,

is there any documentation about your free plugins? 
I enabled Theater Button plugin, but I could not see any effect on the website. What is that plugin supposed to do?

TIA.

**Comment by DanielnetoDotCom** [comment]
Hi

You can find documentation for some plugins, look for the help button...
![image](https://user-images.githubusercontent.com/18009293/48613849-95468780-e96b-11e8-9bb8-b3caa3af0d8d.png)

About the theater Button, you can find it on the player, it looks like the fullscreen button

![image](https://user-images.githubusercontent.com/18009293/48613976-e3f42180-e96b-11e8-9c00-4629e2e53889.png)

**Comment by birdie60** [comment]
Ah, OK, thanks for your clarification, @Daniel. I did not see that mentioned anywhere!

**Comment by DanielnetoDotCom** [comment]
What didnt u see mention?

**Comment by birdie60** [comment]
Thanks again!
