### ISSUE TITLE
Sign in and sigh up error

### ISSUE THREAD

**Issue by CorpCaleCloud** [DanielnetoDotCom/YouPHPTube#1224]
When I try and sign in it just refreshed the page and doesn't sign me in and when I try and sign up a new account I get a captcha error not matter how many times i change the captcha

![error - capcha - 2](https://user-images.githubusercontent.com/25417743/48589102-e043a900-e931-11e8-8c4c-d734de50db9e.PNG)

code to a new one so know  i cannot use the site at all. i can view current content but cannot login to amend or create new content

**Comment by CorpCaleCloud** [comment]
i had an a backup VM which resolved the issues once i restored it however i would like to know what course the issues for future reference. i will update the server and check if any of the updates interfered with the system

**Comment by CorpCaleCloud** [comment]
restored backup VM

**Comment by DanielnetoDotCom** [comment]
Hi, I never saw this error before, but I am glad you could restore.

If appear again check your log file

**Comment by CorpCaleCloud** [comment]
Whenever I try to update the server it appears again so might needs to reinstall it

**Comment by DanielnetoDotCom** [comment]
how are you updating?

what version are you?

do not forget to update the database after update your files

**Comment by CorpCaleCloud** [comment]
Updating the OS in general and then it crashes the application 




Get Outlook for Android







On Fri, Nov 16, 2018 at 10:15 AM +0000, "YouPHPTube" <notifications@github.com> wrote:












how are you updating?


what version are you?


do not forget to update the database after update your files



—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DanielnetoDotCom/YouPHPTube","title":"DanielnetoDotCom/YouPHPTube","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/DanielnetoDotCom/YouPHPTube"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DanielnetoDotCom in #1224: how are you updating?\r
\r
what version are you?\r
\r
do not forget to update the database after update your files"}],"action":{"name":"View Issue","url":"https://github.com/DanielnetoDotCom/YouPHPTube/issues/1224#issuecomment-439347252"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1224#issuecomment-439347252",
"url": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1224#issuecomment-439347252",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [DanielnetoDotCom/YouPHPTube] Sign in and sigh up error (#1224)",
"sections": [
{
"text": "",
"activityTitle": "**YouPHPTube**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@DanielnetoDotCom",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{
\"commandName\": \"IssueComment\",
\"repositoryFullName\": \"DanielnetoDotCom/YouPHPTube\",
\"issueId\": 1224,
\"IssueComment\": \"{{IssueComment.value}}\"
}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1224#issuecomment-439347252"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{
\"commandName\": \"MuteNotification\",
\"threadId\": 412059646
}"
}
],
"themeColor": "26292E"
}
]

**Comment by DanielnetoDotCom** [comment]
I have it installed in ubuntu 16, 17 and 18.

also some Centos servers. 

But I do not use to upgrade versions.

**Comment by CorpCaleCloud** [comment]
Ok, standard install and leave it be ok.




Get Outlook for Android







On Sat, Nov 17, 2018 at 6:47 PM +0000, "YouPHPTube" <notifications@github.com> wrote:












I have it installed in ubuntu 16, 17 and 18.


also some Centos servers.


But I do not use to upgrade versions.



—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DanielnetoDotCom/YouPHPTube","title":"DanielnetoDotCom/YouPHPTube","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/DanielnetoDotCom/YouPHPTube"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DanielnetoDotCom in #1224: I have it installed in ubuntu 16, 17 and 18.\r
\r
also some Centos servers. \r
\r
But I do not use to upgrade versions."}],"action":{"name":"View Issue","url":"https://github.com/DanielnetoDotCom/YouPHPTube/issues/1224#issuecomment-439638780"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1224#issuecomment-439638780",
"url": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1224#issuecomment-439638780",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [DanielnetoDotCom/YouPHPTube] Sign in and sigh up error (#1224)",
"sections": [
{
"text": "",
"activityTitle": "**YouPHPTube**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@DanielnetoDotCom",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{
\"commandName\": \"IssueComment\",
\"repositoryFullName\": \"DanielnetoDotCom/YouPHPTube\",
\"issueId\": 1224,
\"IssueComment\": \"{{IssueComment.value}}\"
}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1224#issuecomment-439638780"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{
\"commandName\": \"MuteNotification\",
\"threadId\": 412059646
}"
}
],
"themeColor": "26292E"
}
]
