### ISSUE TITLE
Failed opening required '../videos/configuration.php'

### ISSUE THREAD

**Issue by dn1987p** [DanielnetoDotCom/YouPHPTube#1225]
Hello,

I have this kinda weird unknown error when configuring my site's settings and clicking on the submit button.

My apache2 error log states

`PHP Fatal error:  require_once(): Failed opening required '../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/html/core/objects/login.json.php on line 7, referer: ...`

While the installer doesnt show any misconfiguration and any similar related github issues only were caused by different errors.

I'm using Ubuntu 18.04 with 
Apache 2.4.29
mysql  Ver 14.14 Distrib 5.7.24
PHP 7.2.10

I tried both the master branch and the latest release (5.0)

I'm grateful for any further hints, thanks in advance.

Daniel

**Comment by DanielnetoDotCom** [comment]
This is really weird, I have no clue what is going on. maybe you are missing some files?

Try to use `git clone` command to install your youphptube instead upload files

**Comment by tonk42** [comment]
I have a similar error when installing. I downloaded a zip first from github, then did git clone afterwards to double check. 

From /videos/youphptube.log:
>PHP Warning:  require_once(videos/configuration.php): failed to open stream: No such file or directory in /srv/www/[hostname]/index.php on line 126
>PHP Fatal error:  require_once(): Failed opening required 'videos/configuration.php' (include_path='.:/usr/share/php') in /srv/www/[hostname]/index.php on line 126

From Apache error log:
>PHP Notice:  Undefined variable: global in /srv/www/[HOSTNAME]/install/index.php on line 21, referer: https://[HOSTNAME]/install/index.php

I tryed copying configuration.php from /objects/ to /videos/, but to no help.

**Comment by DanielnetoDotCom** [comment]
the configuration is automatically created by the installation script.

if the file does not exist you may have a problem on your installation.

**Comment by thx-network** [comment]
I also have the same problem, but unfortunately, I haven't been able to find a solution either. If you have any further insights or suggestions, please feel free to share them. It's a bit frustrating, but sometimes, issues like these can be quite tricky to troubleshoot.
