### ISSUE TITLE
can't load page  insde app

### ISSUE THREAD

**Issue by DavisGuohua-xie** [DanielnetoDotCom/YouPHPTube#1226]
Not sure if it is even an issue, apologize in advance. if it is working as expected.
Hosted this amazing app on AWC. and invited friend to try out. but they couldn't get it to work inside the app, however it works fine in the browser. Here is a pic they send back to me. 
Wondering what happened exactly? 
<img width="444" alt="screen shot 2018-11-16 at 12 43 03 am" src="https://user-images.githubusercontent.com/7245722/48610249-74fdd500-e939-11e8-8a5d-868b1590ea70.png">
   
![image](https://user-images.githubusercontent.com/7245722/48613201-f0628500-e93f-11e8-9518-ea5888b30263.png)

**Comment by DanielnetoDotCom** [comment]
I just try it with demo site and works fine.

try to encode your videos instead direct upload them
