### ISSUE TITLE
I cant install Error in mysql when i try to install

### ISSUE THREAD

**Issue by lamadya** [DanielnetoDotCom/YouPHPTube#1228]
Hi! I cant install Error in mysql when i  try to install on ubuntu 16.04 
![youphptube](https://user-images.githubusercontent.com/22813957/48646782-bd70cd80-e9e1-11e8-8ca2-1e6a5639f447.png)

**Comment by DanielnetoDotCom** [comment]
make sure your user has rights to create table.

**Comment by goldeniws** [comment]
i have the same problem
and user has rights to create table.

**Comment by goldeniws** [comment]
if import database
Error
Static analysis:

3 errors were found during analysis.

A symbol name was expected! A reserved keyword can not be used as a column name without backquotes. (near "ADD" at position 749)
Unexpected beginning of statement. (near "`users_id`" at position 805)
Unrecognized statement type. (near "REFERENCES" at position 822)
SQL query:

-- ----------------------------------------------------- -- Table `categories` -- ----------------------------------------------------- CREATE TABLE IF NOT EXISTS `categories` ( `id` INT NOT NULL AUTO_INCREMENT, `name` VARCHAR(45) NOT NULL, `clean_name` VARCHAR(45) NOT NULL, `description` TEXT NULL, `nextVideoOrder` INT(2) NOT NULL DEFAULT '0', `parentId` INT NOT NULL DEFAULT '0', `created` DATETIME NOT NULL, `modified` DATETIME NOT NULL, `iconClass` VARCHAR(45) NOT NULL DEFAULT 'fa fa-folder', `users_id` INT(11) NOT NULL DEFAULT 1, `private` TINYINT(1) NULL DEFAULT 0, PRIMARY KEY (`id`), INDEX `fk_categories_users1_idx` (`users_id` ASC), UNIQUE INDEX `clean_name_UNIQUE` (`clean_name` ASC), ADD CONSTRAINT `fk_categories_users1` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE = InnoDB

MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ADD CONSTRAINT `fk_categories_users1`
    FOREIGN KEY (`users_id`)
    REFEREN' at line 19

**Comment by DanielnetoDotCom** [comment]
you right, I sent a fix. thanks for notice it.
