### ISSUE TITLE
Embed video link cant not change.

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#1229]
Hi Daniel,

I found the issue. I was embed any video as a direct link before. but now not showing direct link of embed video.

![embed](https://user-images.githubusercontent.com/35865505/48658456-77f0e680-ea5b-11e8-9554-c3d2a3031f1b.jpg)

**Comment by DanielnetoDotCom** [comment]
You do not need that, it will be auto-detected. if the extension is mp4 or WebM will be a video, mp3 or Ogg and audio otherwise will be embed
