### ISSUE TITLE
logical break at plugin

### ISSUE THREAD

**Issue by laweschan** [DanielnetoDotCom/YouPHPTube#123]
Hi,

  before behavior, we can change the first page mode {youtube/gallery}, but now change in gallery has no luck unless enable gallery in plugin, but this will also lock down the youtube mode. 

   this is strange, if plugin is the upcoming future module, then it should be enable either one {youtube/gallery} and remove the first page mode option.

  please advise

Regards,
Lawes

**Comment by DanielnetoDotCom** [comment]
Yes, you right, plugins just come out of the oven, that is why it is not 100% yet, but gallery and facebook first page are working fine.
the page mode is not available any more and will be removed.
