### ISSUE TITLE
add-on so that users can monetize their videos

### ISSUE THREAD

**Issue by kiaraxx** [DanielnetoDotCom/YouPHPTube#1233]
add-on so that users can monetize their videos.

there will be some complement like that, as youtube has.

This is the system that allows you to earn money on youtube.

**Comment by Puyodead1** [comment]
There already is the YPTWallet plugin

**Comment by DanielnetoDotCom** [comment]
Also, check the free plugin MonetizeUsers 

This plugin will reward your users based on their videos view, each view will affect the user's walled balance

![image](https://user-images.githubusercontent.com/18009293/48840661-11770b80-ed6e-11e8-94b9-d203e71da912.png)
