### ISSUE TITLE
Some guide or api of the youphptube script

### ISSUE THREAD

**Issue by kiaraxx** [DanielnetoDotCom/YouPHPTube#1234]
Some guide or api of the youphptube script.

because I'm going to make her application for android but I can not find documentation about it.

with documentation I mean how to call functions and things like that that facilitate the creation of an application for android.

I know there is an application that sells, but the price is very high and there are programmers who do it for $ 200.

**Comment by Puyodead1** [comment]
There already is an app for android

**Comment by Puyodead1** [comment]
https://play.google.com/store/apps/details?id=mobile.youphptube.com
https://www.youphptube.com/mobile/
https://demo.youphptube.com/video/youphptube-android-application

**Comment by DanielnetoDotCom** [comment]
About API docs we do not have it yet 
But the code is very clear you may be able to understand.
Also take a look on that if you want to upload from your app https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Upload-videos-from-third-party-applications
