### ISSUE TITLE
Cant Upload 2.43 GB File

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1235]
My friend is trying to upload to my site (which is set to 6gb in both max upload and max post) the file is 2.43 gb and it keeps resetting the upload, the RAM usage was at 98% and the browser was using it all (firefox). He has attempted many times, he has tried the Public encoder with no luck

**Comment by DanielnetoDotCom** [comment]
Does it work on public encoder?

How much ram do you have?

**Comment by Puyodead1** [comment]
16gb ram but it didnt work on my encoder, public encoder, or direct upload. same problem with a 1.4GB file

**Comment by DanielnetoDotCom** [comment]
if you upload to the demo site, does it work?

there is something on the log file?

**Comment by Puyodead1** [comment]
i will ask him to try the demo site, let me check the logs

**Comment by Puyodead1** [comment]
nothing in logs

**Comment by DanielnetoDotCom** [comment]
if there is nothing in the log, maybe your upload is not completing.

are you using a CDN or any kind of security?

maybe is something else blocking the upload limit.

**Comment by Puyodead1** [comment]
https and Fail2ban are the only things, after reinstalling the site and using the public encoder, it seems to be working ok now
