### ISSUE TITLE
Live Chat keeps crashing

### ISSUE THREAD

**Issue by nightstryke** [DanielnetoDotCom/YouPHPTube#1236]
@DanielnetoDotCom I keep having an issue where the Live Chat keeps crashing or stops running, do you know where I can find the logs to try and figure out why it stops working?

Would it be better to setup the Live Chat in a Cronjob and tell it to restart the Chat every hour?

**Comment by DanielnetoDotCom** [comment]
I am also trying to find a way to detect why it is crashing . Find a way to reproduce the failure.

Cronjob is not a solution but may restart your chat in case it fail

**Comment by DanielnetoDotCom** [comment]
I see, @Tarrantx  that may be the problem.

The MySQL timeout because the chat is always connected.

Maybe I need to think about what will be the best chat solution.

**Comment by nightstryke** [comment]
> I see, @Tarrantx that may be the problem.
> 
> The MySQL timeout because the chat is always connected.
> 
> Maybe I need to think about what will be the best chat solution.

It's frustrating, I've even tried to run the nohup without having it create the nohup.out file and still nothing.
A lot of my users use Live Streaming and Live Chat is an integral part of the Live Streaming experience.

**Comment by Puyodead1** [comment]
```[13-Jan-2019 17:31:06 America/New_York] Error in writeSql : (1452) Cannot add or update a child row: a foreign key constraint fails (`PuyoTube`.`videos_statistics`, CONSTRAINT `fk_videos_statistics_users1` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE), SQL-CMD:INSERT INTO videos_statistics ( `id`,`when`,`ip`,`users_id`,`videos_id`,`created`,`modified`,`lastVideoTime` ) VALUES ( NULL ,  '2019-01-13 05:31:06' ,  NULL ,  '0' ,  '22' ,  now() ,  now() ,  '920' )``` is the error i get when trying to start the chat server
