### ISSUE TITLE
18.X Installation Issue

### ISSUE THREAD

**Issue by bensservice** [DanielnetoDotCom/YouPHPTube#1238]
Maybe its because I'm kinda new to Ubuntu but I'm getting the following when trying to run the install command from the following link: 

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-YouPHPTube-version-4.x-or-newer

I've read a thread on a similar issue but its not clear to me on exactly what the fix was. I did run "sudo get-apt upgrade" and "sudo get-apt update". I'm not sure where to go from here to install YouPHPTube. Any assistance would be appreciated. Thanks

Ubuntu Version I'm using: 18.04.1 LTS

{username}@mediaserver:~$ sudo apt-get install apache2 php libapache2-mod-php php-mysql php-curl php-gd php-intl mysql-server mysql-client ffmpeg git libimage-exiftool-perl && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube.git && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube-Encoder.git && sudo apt-get install python && sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && sudo chmod a+rx /usr/local/bin/youtube-dl && sudo a2enmod rewrite
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package ffmpeg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package php-intl
E: Package 'ffmpeg' has no installation candidate
E: Unable to locate package libimage-exiftool-perl
{username}@mediaserver:~$

**Comment by DanielnetoDotCom** [comment]
You probably need a different version of PHP
You will need to google to find out how to install the dependencies.

**Comment by Puyodead1** [comment]
im using 18.04 and it works just fine, try php7.2 instead of php and make sure to apt-get update && apt-get upgrade
