### ISSUE TITLE
PHP Notice:  Undefined index: comments_id

### ISSUE THREAD

**Issue by birdie60** [DanielnetoDotCom/YouPHPTube#1241]
I have this in my logfile:
`PHP Notice:  Undefined index: comments_id in web/objects/comments_like.json.php on line 19`

**Comment by DanielnetoDotCom** [comment]
You should not be accessing this page if you do not have a comments_id

maybe someone is trying to hack you

**Comment by birdie60** [comment]
OK, what can I do?

**Comment by DanielnetoDotCom** [comment]
check your access log to see what IP made that access
