### ISSUE TITLE
CSS still not loading inconsistently on https www url's after I cleared Cache

### ISSUE THREAD

**Issue by jarredmoore** [DanielnetoDotCom/YouPHPTube#1242]
I've notice my style sheets doesn't load completely on certain url's (www, https) and It's in consistent. I've search through a few issues and found some suggestions to clear cache in /videos/cache dir which I did but it's still happening. 

Is there something else I'm missing?? Maybe the cerbot redirects need to be forced?? I'm at lost and I have this site in production so any quick help will be greatly appreciated..

**Comment by DanielnetoDotCom** [comment]
Hi

Make sure in your configuration.php you are using https and not http

**Comment by jarredmoore** [comment]
<img width="352" alt="screen shot 2018-11-23 at 7 08 31 pm" src="https://user-images.githubusercontent.com/7459434/48963224-cdddf680-ef53-11e8-8504-ad932418320e.png">
There are two rules. Should I uncomment the one with the entire web address or add an s to the global rule in place???

**Comment by Puyodead1** [comment]
If I’m not mistaken, it should be the first one, I haven’t seen that second one before in my setup 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DanielnetoDotCom** [comment]
the second should work for any URL
the first one is to force https. if you uncomment the first one you should comment the second.

**Comment by jarredmoore** [comment]
Okay, Thanks I uncommented the first rule and commented the second; it seems to be working fine. 

I do think it was the cache. Is there a way to control the size of that dir and/or how often I have to clear it?? I'm using the button in the advance config panel and rm ../video/cache/* on command line

**Comment by DanielnetoDotCom** [comment]
For now, we have no control over it.
