### ISSUE TITLE
strange sql error in logs

### ISSUE THREAD

**Issue by ankoran** [DanielnetoDotCom/YouPHPTube#1243]
was browsing around the logs since lately when i go to upload and encode it uploads fine but is not encoding anything. I came across this first error in the youphptube.log for the streamer.

[22-Nov-2018 21:01:57 UTC] [sqlDAL::readSql] (mysqlnd) Prepare failed: (1064) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')  ORDER BY name ASC' at line 1<br>

in phpmyadmin i also get the following

Warning in ./libraries/sql.lib.php#613
 count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/sql.lib.php#2128: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#2079: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string 'deshflix',
string 'categories',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `categories`',
NULL,
NULL,
)
./sql.php#221: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string 'deshflix',
string 'categories',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `categories`',
NULL,
NULL,
)

i get that in phpmyadmin no matter what table i select from the youphptube db and the encoder db 

mysql version is mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64) using  EditLine wrapper
ubuntu 18.04
nothing else in any logs as to what is going on.

**Comment by ChrisSlS** [comment]
Fix with: https://devanswers.co/problem-php-7-2-phpmyadmin-warning-in-librariessql-count/

Search for Google errors like this (Warning in ./libraries/sql.lib.php#613). For my part, I do not have this problem since the modification of the file.

**Comment by DanielnetoDotCom** [comment]
Also this error is not related to YouPHPTube
