### ISSUE TITLE
Cant show video under same category at admin console, my video

### ISSUE THREAD

**Issue by ykhuat** [DanielnetoDotCom/YouPHPTube#1244]
Hi, 
Daniel, thank you for great software.

I have few category setup on server, but i have a issue on admin console, my video.

the default is list all movie files they, I try to select category comic that i create and already have some video inside, but it cant be display out.

Please have a look on it..

Thank You.
Sorry for my bad English, hope you can understand.

**Comment by DanielnetoDotCom** [comment]
thanks, we may create some filters in the future
