### ISSUE TITLE
A problem related to the activation of the "Facebook Tube (FBTube)"

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#1245]
Hello! I noticed the same problem also at demo.youphptube.com :   When you click on to the plugin "Facebook Tube (FBTube)"  to activate it, it remains in processing forever... If you go to the DB and activate manually You get a problem of formatting  the first page that is wrong if the plugin "CustomizeAdvanced (CustomizeAdvanced)" is actived.

I do not know how to solve it, long ago it worked normally.

Another thing that is not strictly linked with problem from before it would be the autoplay that makes me exit automatically from the full screen each time when starting a new video from autoplay.

Thanks in advance.

**Comment by DanielnetoDotCom** [comment]
Thanks for notice, I sent a fix
