### ISSUE TITLE
Deleting user accounts

### ISSUE THREAD

**Issue by Tarrantx** [DanielnetoDotCom/YouPHPTube#1246]
Sorry if this has been asked before, but is there a way for Admins to delete user accounts?  I can't see any way in the GUI?

**Comment by Puyodead1** [comment]
No

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Puyodead1** [comment]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DanielnetoDotCom** [comment]
you can only inactivate users, not delete them
