### ISSUE TITLE
install configuration.php problem with https

### ISSUE THREAD

**Issue by OhioVR** [DanielnetoDotCom/YouPHPTube#1249]
Hello,

After filling out the forms at  the beginning I am confronted with this screen display:
![screen shot 2018-11-26 at 11 03 24 am](https://user-images.githubusercontent.com/10637800/49026191-38b54a80-f16b-11e8-980e-41dbfa0cdabd.png)

Which is being caused by mixed ssl content. I looked into the configuration.php file and I get this after the installer:

`<?php
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
//$global['webSiteRootURL'] = 'https://youphptube.flieble.com/';
// get the subdirectory, if exists
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;

$global['systemRootPath'] = '/var/www/html/';
$global['salt'] = '5bfc18e57ae09';

$mysqlHost = 'db';
$mysqlPort = '3306';
$mysqlUser = 'root';
$mysqlPass = 'kaib5IeraW2Zeiceez4Vohghohmaidae';
$mysqlDatabase = 'youPHPTube';

/**
 * Do NOT change from here
 */
`

If I uncomment 

`//$global['webSiteRootURL']`

and change 

`
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
`
to 
`
$global['webSiteRootURL'] = "https".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
`
it is working ok.

Is there something I am doing wrong? It used to work fine without having to edit the configuration file.

**Comment by DanielnetoDotCom** [comment]
probably your cache directory saw created using http.

if you force https you can delete your cache and let the script create it again.

Uncomment this: 

` $global['webSiteRootURL'] = 'https://youphptube.flieble.com/';`

And comment this

`//$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;`
