### ISSUE TITLE
'mysql' not found 

### ISSUE THREAD

**Issue by kazkix** [DanielnetoDotCom/YouPHPTube#125]
I got "Unknow error" in the error log.
So I installed  php-mysql, but it does not fix it.

「[Sun Sep 24 12:56:31.092083 2017] [:error] [pid 13306] [client localhost:51802] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/install/checkConfiguration.php:16\nStack trace:\n#0 {main}\n  thrown in /var/www/html/install/checkConfiguration.php on line 16, referer: http://localhost/install/index.php」

**Comment by DanielnetoDotCom** [comment]
Try 

sudo apt-get install php7.0-mysqlnd php7.0-mysql

**Comment by kazkix** [comment]
I installed that but written erros log
[Mon Sep 25 08:06:39.885262 2017] [:error] [pid 1137] [client 192.168.0.8:54685] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/install/checkConfiguration.php:16\nStack trace:\n#0 {main}\n  thrown in /var/www/html/install/checkConfiguration.php on line 16, referer: http://192.168.0.7/install/index.php

**Comment by DanielnetoDotCom** [comment]
please delete the log file and restart apache and try again

**Comment by kazkix** [comment]
I restarted apache and delete logfile
but it didn't install

**Comment by DanielnetoDotCom** [comment]
What is your log file after that?

**Comment by DanielnetoDotCom** [comment]
hi I guess I found an error that may cause this issue. could you please update your files and try again?

**Comment by kazkix** [comment]
Is it files what youphptube is called?　or other?

**Comment by DanielnetoDotCom** [comment]
Update your files from GitHub files, I have released new updates today

**Comment by kazkix** [comment]
I don't know how to update youphptube in github on command line
I do not know anything about github, I'm sorry

**Comment by DanielnetoDotCom** [comment]
Take a look on this video https://tutorials.youphptube.com/video/how-to-update-your-youphptube-version

**Comment by kazkix** [comment]
Thank you! Update succeeded

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
