### ISSUE TITLE
unable to edit configuration e.g. change images, etc

### ISSUE THREAD

**Issue by CorpCaleCloud** [DanielnetoDotCom/YouPHPTube#1250]
I'm having general issues e.g. unable to login with edge, unable to change default images on system configure. i had issue so i reverted back to a fail-safe and back up and now the issues are happening again.

need someone to look at the configuration to ascertain why this is happening. server hasn't been touch for months once initial config was set-up and everything seemed fine but as i try to add clients and amend user accounts, etc i having saving and login issues

**Comment by DanielnetoDotCom** [comment]
Is this happening only in edge or in any browser?

really strange, if you want to hire us, feel free to send us an email. developer@youphptube.com

**Comment by CorpCaleCloud** [comment]
properties of the file 
![properties](https://user-images.githubusercontent.com/25417743/49124781-96ee4480-f2b5-11e8-9253-cb5f41fb9b20.PNG)

**Comment by DanielnetoDotCom** [comment]
It works on my Firefox.
what version are you using?

**Comment by Puyodead1** [comment]
browser is most likely outdated

**Comment by CorpCaleCloud** [comment]
All updated, every browse can't  be out of date.  When i upload i get the error as you see, also i went to a third party website and tested same image and same result also login is an issue where it doesn't recognise or just loops.




I have to close the browser to see changes which wasn't an issue before. 4 browser can all be wrong




Get Outlook for Android







On Wed, Nov 28, 2018 at 5:42 PM +0000, "Riley" <notifications@github.com> wrote:












browser is most likely outdated



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DanielnetoDotCom/YouPHPTube","title":"DanielnetoDotCom/YouPHPTube","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/DanielnetoDotCom/YouPHPTube"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Puyodead1 in #1250: browser is most likely outdated"}],"action":{"name":"View Issue","url":"https://github.com/DanielnetoDotCom/YouPHPTube/issues/1250#issuecomment-442538285"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1250#issuecomment-442538285",
"url": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1250#issuecomment-442538285",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [DanielnetoDotCom/YouPHPTube] unable to edit configuration e.g. change images, etc (#1250)",
"sections": [
{
"text": "",
"activityTitle": "**Riley**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Puyodead1",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{
\"commandName\": \"IssueComment\",
\"repositoryFullName\": \"DanielnetoDotCom/YouPHPTube\",
\"issueId\": 1250,
\"IssueComment\": \"{{IssueComment.value}}\"
}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{
\"commandName\": \"IssueClose\",
\"repositoryFullName\": \"DanielnetoDotCom/YouPHPTube\",
\"issueId\": 1250
}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1250#issuecomment-442538285"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{
\"commandName\": \"MuteNotification\",
\"threadId\": 416150374
}"
}
],
"themeColor": "26292E"
}
]

**Comment by DanielnetoDotCom** [comment]
does the same happen on the demo site?

what is your domain?
