### ISSUE TITLE
i want to install youphptube on my vps with Apache but how to install rtmp on apache

### ISSUE THREAD

**Issue by lamadya** [DanielnetoDotCom/YouPHPTube#1251]
Hi
I have Vps running with Apache on ubuntu I follow this tutorial 
`[How to install LAMP, FFMPEG and Git on a fresh Ubuntu 16.x For YouPHPTube version 4.x or newer
](https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x-For-YouPHPTube-version-4.x-or-newer)`  
But how can you make a live 
You can install nginx and apache together
apache for web anad nginx for streaming

**Comment by DanielnetoDotCom** [comment]
To install your live stream please use this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Set-up-my-own-Stream-Server

**Comment by lamadya** [comment]
this tutorials Works with Apache well

**Comment by DanielnetoDotCom** [comment]
also you will need to install nginx and apache on the same server (in different ports)

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/YouPHPTube-hadware-requirements#what-ports-do-i-need-to-open

**Comment by lamadya** [comment]
But when installing With Apache Get  'this operation, 541 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Abort.'
why my vps on contabo 400Gb SSD 16GB Ram 
and AWS Amazone Get  Abort 
see my screanshot
http://i.is.cc/X6Ojd0k.png

**Comment by Puyodead1** [comment]
just run the command again

**Comment by nightstryke** [comment]
> But when installing With Apache Get 'this operation, 541 MB of additional disk space will be used.
> Do you want to continue? [Y/n] Y
> Abort.'
> why my vps on contabo 400Gb SSD 16GB Ram
> and AWS Amazone Get Abort
> see my screanshot
> http://i.is.cc/X6Ojd0k.png

Run the command again and instead of using a **lower-case y** try using an **upper-case Y** like it asks for.
