### ISSUE TITLE
guessable url´s

### ISSUE THREAD

**Issue by kinimodmeyer** [DanielnetoDotCom/YouPHPTube#1253]
hello,

nice software!

is there a option that the video/category urls are not guessable?
i mean i only need to loop over xy.de/v/1 , xy.de/v/2 ... to get all unlisted videos.

how can i hide videos better? (which should get only accessable via e.g. secret code)
(not with user groups)

**Comment by DanielnetoDotCom** [comment]
I see, we do not have that option yet.

maybe in the future, we add an option to disable the permalink
