### ISSUE TITLE
Problem Getting youtube Video

### ISSUE THREAD

**Issue by john-helyar** [DanielnetoDotCom/YouPHPTube#1254]
Hi there hope you can help 

Just set this all up and its working great been able to upload videos and it all works with my encoder on the server so that side of it is great

When i try and do it direct from youtube it goes through all the motions creates the thumbnail but video wont play the time on the video displays EE:EE:EE and thats it tried a few vids but no luck.

Have i missed something 

Cheers in advance 

John

**Comment by DanielnetoDotCom** [comment]
make sure what is your upload limit between your encoder and streamer.
Maybe a firewall or CDN or an apache limiting the upload

**Comment by john-helyar** [comment]
I can increase the upload limit i have that set at 512mb and it was a 5min video to test with.
Dont have a CDN anywhere and i can check the Firewall out what ports are needed to be open for this to work so i can check them out.

As everything else is fine just the youtube part of it

**Comment by DanielnetoDotCom** [comment]
Just make sure the RAM limit https://github.com/DanielnetoDotCom/YouPHPTube/wiki/YouPHPTube-hadware-requirements#how-should-the-ram-be

**Comment by DanielnetoDotCom** [comment]
I guess still the upload size limit problem

**Comment by john-helyar** [comment]
Ok Low and SD work HD dont if i download the Video in HD its only 42mb and i have uploaded videos 3 times bigger then that with no problem

**Comment by DanielnetoDotCom** [comment]
yes, 42 mb is very low, so something else is blocking the file transfer
I am not sure what do you have enabled on your server or network. maybe some security.

**Comment by john-helyar** [comment]
Its a Clean install of Ubuntu 18 and followed your install guide nothing else is on that at all.

Looking at the resources while its doing it is the CPU usage is high but memory is very low

**Comment by DanielnetoDotCom** [comment]
Did you try it on public encoder?
how much memory do you have?
how long is the video?
Are you sure the HD version is only 52MB?

**Comment by john-helyar** [comment]
I havent tried in on a Public Encoder but i can.
Have 4gb Ram on our server
Video is 4min and 8sec
When i donwloaded the 720p HD version it came down about 52mb 
I have uploaded larger files

**Comment by DanielnetoDotCom** [comment]
the encoded HD video does not mean will have the same size as the file you download.
Check the size of your SD and low video files.

I dont know what is blocking you.

**Comment by john-helyar** [comment]
I will see what i can do i will run the test again as removed them so will do the SD one again and check

Also i just tried to upload a much larger file direct its 166mb about 25min long but when i drag in on the text goes red in the encoder but if i do a smaller file its ok about 90mb yet all my uploads are currently set to 512mb any idea as it may be linked

**Comment by DanielnetoDotCom** [comment]
I am almost sure you have a CDN enabled, maybe cloudflare.

**Comment by john-helyar** [comment]
Yeap seems to be capped at 100mb anything bigger then wont do anything i have increased file sizes to 2048M in php.ini and restarted
So at the bottom of the Encoder now says 
The encoder Max File Size is: 2.00GB The Streamer Max File Size is: 2.00GB

**Comment by DanielnetoDotCom** [comment]
what is your domain?

**Comment by john-helyar** [comment]
Its running of this http://video.ubegaming.co.uk
and yes i did have Cloudflare on but i have just disabled that for this DNS record may take a min to update but will keep an eye out

**Comment by john-helyar** [comment]
ok that seems to of sorted it i hang my head in shame 

Cheers for all your help on this though very quick and helpful

**Comment by DanielnetoDotCom** [comment]
I told you about the CDN on my first post here

**Comment by john-helyar** [comment]
Oh i do have one other question.

When you link to the youtube video in the encoder ie Tab "From Web" does this download a copy to my server or is it just a link to the youtube video

**Comment by DanielnetoDotCom** [comment]
download for your server

**Comment by john-helyar** [comment]
Awesome gonna give it a go now and make sur eit works ok.

**Comment by john-helyar** [comment]
ok just did a HD video and it worked fine think i will can Cloudflare more trouble then its worth 

Again thank you for all your help.

Great system

If i have some thoughts and ideas that may make things easier is there a suggestion box anywhere?

**Comment by DanielnetoDotCom** [comment]
For those who want to use CDN/Cloudflare https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Using-CDN-for-Videos-Only
