### ISSUE TITLE
How to add categories to the Gallery Front Page 

### ISSUE THREAD

**Issue by john-helyar** [DanielnetoDotCom/YouPHPTube#1255]
Hi there again

I am using the Gallery Plugin as it is a nice clean layout and disabled all the bits i dont want but what i would like to do is list the Categories so like the Data Added or Most Popular i would like to have them below so its easier to find videos in those categories

As i cant seem to find a why of making play list as the reason being i am using this to collect training videos together for different things so would like to make it easy to find a video on Modeling or Texture work rather then having to claw through loads of videos

The option to show categories is on the netflix plugin but doesnt layout as nice and clean any advice would be great

Cheers

**Comment by DanielnetoDotCom** [comment]
We may improve it in the feature, thanks for the idea
