### ISSUE TITLE
Full Screen not now working when click on play back

### ISSUE THREAD

**Issue by CorpCaleCloud** [DanielnetoDotCom/YouPHPTube#1256]
When i try and use full screen it does nothing. theater works and so the popup window however just full screen dosent work 

![full scrren not working](https://user-images.githubusercontent.com/25417743/49125212-27795480-f2b7-11e8-9930-d13ae33a401f.PNG)

**Comment by DanielnetoDotCom** [comment]
based on the lens icon, I guess you are using an old version.

can you please update your files?

**Comment by CorpCaleCloud** [comment]
How do i update??




Get Outlook for Android







On Wed, Nov 28, 2018 at 11:44 AM +0000, "YouPHPTube" <notifications@github.com> wrote:












based on the lens icon, I guess you are using an old version.


can you please update your files?



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DanielnetoDotCom/YouPHPTube","title":"DanielnetoDotCom/YouPHPTube","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/DanielnetoDotCom/YouPHPTube"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DanielnetoDotCom in #1256: based on the lens icon, I guess you are using an old version.\r
\r
can you please update your files?"}],"action":{"name":"View Issue","url":"https://github.com/DanielnetoDotCom/YouPHPTube/issues/1256#issuecomment-442418632"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1256#issuecomment-442418632",
"url": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1256#issuecomment-442418632",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [DanielnetoDotCom/YouPHPTube] Full Screen not now working when click on play back (#1256)",
"sections": [
{
"text": "",
"activityTitle": "**YouPHPTube**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@DanielnetoDotCom",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{
\"commandName\": \"IssueComment\",
\"repositoryFullName\": \"DanielnetoDotCom/YouPHPTube\",
\"issueId\": 1256,
\"IssueComment\": \"{{IssueComment.value}}\"
}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{
\"commandName\": \"IssueClose\",
\"repositoryFullName\": \"DanielnetoDotCom/YouPHPTube\",
\"issueId\": 1256
}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1256#issuecomment-442418632"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{
\"commandName\": \"MuteNotification\",
\"threadId\": 417004152
}"
}
],
"themeColor": "26292E"
}
]

**Comment by DanielnetoDotCom** [comment]
Please check this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-Update-your-YouPHPTube
