### ISSUE TITLE
Hi There question about Top Menu

### ISSUE THREAD

**Issue by john-helyar** [DanielnetoDotCom/YouPHPTube#1257]
Hi

Just wondered if there is a way to add a drop-down menu displaying Categories i know its on the sidebar but would really like a way of having it as a drop-down on the top bar as well if you can help or advise that would be great thank you

**Comment by john-helyar** [comment]
Does anyone have an idea how to do this?

**Comment by DanielnetoDotCom** [comment]
You will need to code for that.

If you want you can hire us to develop it for you.

email us the details to developer@youphptube.com and we will quote for you.
