### ISSUE TITLE
Live Streaming Error

### ISSUE THREAD

**Issue by nightstryke** [DanielnetoDotCom/YouPHPTube#1259]
Some of my users are complaining that live streams aren't working.
Says it gives them this error
 ` This is a modal window.HLS playlist request error at URL:https://domainname.org:444/live/5abcdef4/index.m3u8 `

**Comment by DanielnetoDotCom** [comment]
I am not sure what happened, but make sure your ssl is valid.

**Comment by nightstryke** [comment]
SSL is valid, but I don't get this error, but some of my users do. It's very frustrating.

**Comment by DanielnetoDotCom** [comment]
maybe they are in a network what is blocking port 444 (what is not a standard port)

**Comment by nightstryke** [comment]
> maybe they are in a network what is blocking port 444 (what is not a standard port)

Hmm that might be possible, though there is a firewall on my server and port 444 is allowed so I'm not sure what else to do.

**Comment by DanielnetoDotCom** [comment]
there is nothing else to do if the blocking is on their network
