### ISSUE TITLE
How to delete encoded files?

### ISSUE THREAD

**Issue by ikehays83** [DanielnetoDotCom/YouPHPTube#126]
Hi there, is there any way I can delete all encoded videos automatically in order to free some space on my encoded server? thank you

**Comment by DanielnetoDotCom** [comment]
We keep the video files in case you want to resend or reencode the video.
But if you delete it from queue, the video is also deleted

![image](https://user-images.githubusercontent.com/18009293/30787096-df40658e-a157-11e7-9ef8-b5b30e152768.png)

**Comment by ikehays83** [comment]
Thank you very much for your quickest response, but I am referring to my own encoder that I have installed. I have installed a separate Encoder Server with a limited disk space.

Thank you

**Comment by ikehays83** [comment]
Thank you very much for your quickest response, but I am referring to my own encoder that I have installed/built. 

Basically, I would like all videos/audio to be deleted from my server after transferring the encoded video/audio onto the Stream Site. Should the be any way to do that?

Thank you.

**Comment by DanielnetoDotCom** [comment]
sorry but this option is not implemented yet.
Maybe in the future
