### ISSUE TITLE
proccesing when login

### ISSUE THREAD

**Issue by alifazeli** [DanielnetoDotCom/YouPHPTube#1263]
hi

i install youphptube based on this
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-YouPHPTube-version-4.x-or-newer
but when i want to signin youphptube hang on processing.
any idea about the problem?
![image](https://user-images.githubusercontent.com/45519108/49331183-6c9ad080-f5ae-11e8-853b-3834a9b356f8.png)
tnx

**Comment by alifazeli** [comment]
![capture2](https://user-images.githubusercontent.com/45519108/49699688-945ee980-fbe9-11e8-8024-3f87c6cef4a8.JPG)

**Comment by DanielnetoDotCom** [comment]
looks like you have a problem in some PHP libs 

Also I can not see any error related to YouPHPTube on this log

**Comment by Puyodead1** [comment]
not sure if this is solved or not, but also looks like there are permission errors:
![image](https://user-images.githubusercontent.com/14828766/50118761-ba564080-021e-11e9-9517-56fef7fa69de.png)

**Comment by alifazeli** [comment]
tnx guys
i reinstall youphptube step by step and it works now :)

**Comment by DanielnetoDotCom** [comment]
Great
