### ISSUE TITLE
Configuration cannot be saved

### ISSUE THREAD

**Issue by takleung** [DanielnetoDotCom/YouPHPTube#1265]
Hi,

I tried to save configuration but it keeps "processing" window. I checked web server log file but nothing goes wrong. Could you please advise?

![screenshot 2018-12-03 at 12 38 12 am](https://user-images.githubusercontent.com/208190/49342645-0474e900-f699-11e8-94dc-1921382e00a1.png)

[Dec-2018.smartvdotest.tar.gz](https://github.com/DanielnetoDotCom/YouPHPTube/files/2637170/Dec-2018.smartvdotest.tar.gz)

Thanks,
Ray

**Comment by DanielnetoDotCom** [comment]
check your log file

also check your video directory permissions.

apache must be able to write on it including all files under it
