### ISSUE TITLE
install/checkConfiguration.php

### ISSUE THREAD

**Issue by g0053** [DanielnetoDotCom/YouPHPTube#1266]
After installation web page shown as this:
![image](https://user-images.githubusercontent.com/18383477/49368917-56952900-f6f0-11e8-9642-4acac937b2d7.png)

URL/install/checkConfiguration.php

![image](https://user-images.githubusercontent.com/18383477/49368960-7593bb00-f6f0-11e8-8fb3-0f00d578c755.png)

I'm using turnkey_youphptube image...

**Comment by g0053** [comment]
### # lsb_release -a
No LSB modules are available.
Distributor ID: TurnKey
Description:    TurnKey GNU/Linux 9.6 (stretch)
Release:        9.6
Codename:       stretch

**Comment by DanielnetoDotCom** [comment]
Sorry, I  can not support you this image

try to get support on the official TurnKey repository

**Comment by g0053** [comment]
Thanks for reply, I have fixed it. 
Your script is really nice! Thanks for inventing it!

**Comment by DanielnetoDotCom** [comment]
Great I am glad you like it.

**Comment by g0053** [comment]
1 question regarding rtmp streaming.


for live i use this rtmp url:

rtmp://10.10.10.1/live?p=5806b0ab80b19d574f5726f5cd90e2b5/KEY

/////////
What rtmp url should I use for live event?
![image](https://user-images.githubusercontent.com/18383477/49524216-a409c580-f8ab-11e8-92ae-7c972854be9b.png)



I have tried these 3:


rtmp://10.10.10.1/live?p=TEST1
rtmp://10.10.10.1/live/TEST1
rtmp://10.10.10.1/live/TEST1/TES1

Thanks in advance!

**Comment by g0053** [comment]
Sorry for silly question, now I assume that you can have only 1 live rtmp stream per user ?

My scenario is to stream 3 /dev/video devices via 1 (admin) user. is it possible ?

10x!

**Comment by g0053** [comment]
to be short, I need something like this:
ffmpeg -re -i /dev/video0 -f flv -i "rtmp://10.10.10.1/live?p=TEST1"
ffmpeg -re -i /dev/video1 -f flv -i "rtmp://10.10.10.1/live?p=TEST2"
ffmpeg -re -i /dev/video2 -f flv -i "rtmp://10.10.10.1/live?p=TEST3"

**Comment by DanielnetoDotCom** [comment]
For live links you should use `https://yoursite.com:444/live/5bf507e50e39b/index.m3u8`

It is not related to YouPHPTube but to stream using your FFMPEG

`nohup ffmpeg -re -stream_loop -1 -i /root/video.mp4 -c copy -f flv rtmp://yoursite.com/live?p=098f6bcd4621d373cade4e832627b4f6/YourStreamKey &`
