### ISSUE TITLE
Embed Stream load unsafe scripts

### ISSUE THREAD

**Issue by lamadya** [DanielnetoDotCom/YouPHPTube#1268]
Hi
I have a virtual host on Apache with ssl but when I use embedding video stream in Chrome browser is not safe because my nginx rtmp does not use ssl
Can you help me install ssl for nginx rtmp on ip or domain name 
thank you

**Comment by DanielnetoDotCom** [comment]
We use https://letsencrypt.org/ to install ssl on nginx on port 444.

Because it is not related to YouPHPTube app, we can not support you on this installation but you can hire us to install it for you here https://www.youphptube.com/services
