### ISSUE TITLE
Logo cannot be updated

### ISSUE THREAD

**Issue by takleung** [DanielnetoDotCom/YouPHPTube#1269]
Hi Daniel,

When i clicked "save", it says succeed. But logo still keep the same "youphptube". For the rest configuration parameters can be saved successfully. Kindly advise

![screenshot 2018-12-05 at 7 41 58 pm](https://user-images.githubusercontent.com/208190/49511459-34550400-f8c6-11e8-888a-fdbd03d44d9f.png)

Thanks,
Ray

**Comment by DanielnetoDotCom** [comment]
probably is your browser cache.

just clear it and you will be fine
