### ISSUE TITLE
Problem with Encoder in 4.1

### ISSUE THREAD

**Issue by winklov** [DanielnetoDotCom/YouPHPTube#127]
Good Day

I have a problem with my encoder

Attach is screenshots.

Can you help please

![pip](https://user-images.githubusercontent.com/18721141/30972592-43eb947a-a46b-11e7-8785-0bcc6b1e24e9.png)
![youphptube encoder 1](https://user-images.githubusercontent.com/18721141/30972591-43ea4232-a46b-11e7-98f6-1391c4f97f12.png)

**Comment by mikweb2017** [comment]
try 
sudo pip install youtube-dl
sudo pip install --upgrade youtube-dl

**Comment by winklov** [comment]
its install and up to date but im still getting that error

**Comment by winklov** [comment]
how do i set the LC_ALL environment

**Comment by winklov** [comment]
any help

**Comment by DanielnetoDotCom** [comment]
Hi sorry for delay, can you please. try again and paste your encoder, error log here?
should be in the [encoder-path]/videos/youphptube.log

**Comment by winklov** [comment]
[02-Oct-2017 08:27:23 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/plugin/Live/Live.php:82
Stack trace:
#0 /var/www/html/plugin/Live/Live.php(77): Live->get_data('http://noticias...')
#1 /var/www/html/plugin/Live/stats.json.php(18): Live->getStatsObject()
#2 {main}
  thrown in /var/www/html/plugin/Live/Live.php on line 82

**Comment by winklov** [comment]
We could not get the title of your video (WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.) go to to fix it

**Comment by winklov** [comment]
[02-Oct-2017 09:49:01 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/plugin/Live/Live.php:82
Stack trace:
#0 /var/www/html/plugin/Live/Live.php(77): Live->get_data('http://noticias...')
#1 /var/www/html/plugin/Live/stats.json.php(18): Live->getStatsObject()
#2 {main}
  thrown in /var/www/html/plugin/Live/Live.php on line 82

**Comment by DanielnetoDotCom** [comment]
for sure you need to fix this "Call to undefined function curl_init()"

> If you're on Windows:
> 
> Go to your php.ini file and remove the ; mark from the beginning of the following line:
> 
> ;extension=php_curl.dll
> After you have saved the file you must restart your HTTP server software (e.g. Apache) before this can take effect.
> 
> For Ubuntu 13.0 and above, simply use the debundled package. In a terminal type the following to install it and do not forgot to restart server.
> 
> sudo apt-get install php-curl
> Or if you're using the old PHP5
> 
> sudo apt-get install php5-curl

https://stackoverflow.com/questions/6382539/call-to-undefined-function-curl-init

just one thing, if you are using PHP7, you may use this command: `sudo apt-get install php7.0-curl`

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by martinustrinc** [comment]
Hello,
I have a problem with this log..
Anyone can help me?
[26-Apr-2018 16:44:24] PHP Fatal error:  Uncaught Error: Call to undefined function imagecreate() in /var/www/html/YouPHPTube/objects/captcha.php:23
Stack trace:
#0 /var/www/html/YouPHPTube/objects/getCaptcha.php(10): Captcha->getCaptchaImage()
#1 {main}
  thrown in /var/www/html/YouPHPTube/objects/captcha.php on line 23
