### ISSUE TITLE
Tv series and episodes 

### ISSUE THREAD

**Issue by lucadeci** [DanielnetoDotCom/YouPHPTube#1270]
Hi, 
in netlfix "clone" is possible to add a series? 
create and manage episodes related to a series?

**Comment by lucadeci** [comment]
Ok, if i create a playlist is public? Everyone see the playlist? 

In your opinion is possible to add a script to organize videos in series?

**Comment by DanielnetoDotCom** [comment]
> Ok, if i create a playlist is public? Everyone see the playlist?

Yes

> In your opinion is possible to add a script to organize videos in series?

The play list is already possible to sort videos
