### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by angelawong** [DanielnetoDotCom/YouPHPTube#1272]
I cannot seem to get Google Analytics to analyze the traffic going to my site. This is what I have done:

**I have commented out the following codes under /view/include/head.php:**
```
<!--script>
    // YouPHPTube Analytics
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-96597943-1', 'auto', 'youPHPTube');
    ga('youPHPTube.send', 'pageview');
</script-->
```

**And added the following codes recommended by Google Analytics**
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=MyOwnUANumber"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'MyOwnUANumber');
</script>
```

What am I missing? Any advice would be most appreciated.  Thank you.

**Comment by ChrisSlS** [comment]
hello, add it from your site configuration (admin user).

**Comment by DanielnetoDotCom** [comment]
There is an option on the site configuration to disable the youphptube Google analytics and also a place to put your code

**Comment by angelawong** [comment]
ChrisSIS, thanks! That did the trick. How could I have missed that? Thanks so much!

Daniel, thank you to you as well. To Disable the YouPHPTube Google analytics I turn that to ON (blue), correct? The default is OFF (gray).

**Comment by angelawong** [comment]
Maybe I spoke too soon. It worked for a quick second and then it stopped. I have placed my google analytics code under Site Configuration > Script Code. 

I also went to Advanced Configuration and Disabled the YouPHPTube Google Analytics (it is ON now).

When I go to my site, I do not see an active user in my google analytics. Am I still missing something?

**Comment by Andiweb87** [comment]
Site Configuration > Script Code > Head Code 

Put in the Head Code section the code for analytic and will work,  for me work.

**Comment by angelawong** [comment]
Thank you so much, everyone. Yes, adding the head code did work. I was just being too impatient. Google Analytics did register my site's activities.
