### ISSUE TITLE
Stretches the image

### ISSUE THREAD

**Issue by TTcam** [DanielnetoDotCom/YouPHPTube#1273]
1) Video uploaded by phone. Changing the video resolution stretches the image. What can be done?

![capture-1](https://user-images.githubusercontent.com/45658270/49581874-65841180-f964-11e8-856f-c462791ad148.jpg)
![capture-2](https://user-images.githubusercontent.com/45658270/49581879-674dd500-f964-11e8-9aae-1141e93d211e.jpg)

2)  How soon can we expect capture from a webcam?

**Comment by DanielnetoDotCom** [comment]
you is your encoder configuration?

**Comment by TTcam** [comment]
Yes. Encoder on my site. Installed your service.

**Comment by DanielnetoDotCom** [comment]
I guess only the image is Stretched.

It will be improved in the future
