### ISSUE TITLE
Information about the plug "FTP_Storage"

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#1274]
Hello! A few days ago I saw this plug appeared in the list of plugins to buy. Can you explain in more detail how the plug works? ... maybe if you can do a tutorial to detail how to install and what the plug can do.
Interested if the plugin can in idea that I install it on the server streamer, and the files: mp4, gif, jpeg ... remain on another ftp server.
The next question is how does it work with the transfer from the encoder to the FTP server that hosts all the multimedia files that are usually inside the videos folder from the server streamer?
Thank you.

**Comment by DanielnetoDotCom** [comment]
Hi

It works on the same way as S3 and B2 plugins.

Only videos and audio files will be stored on the FTP, image files will be stored on the streamer server.

you can use the FTP plugin on the demo site to make tests.

I will build a help tutorial on the future.

**Comment by tgd1973** [comment]
Thanks for the reply. I wanted to ask if at the time of browsing the web server streamer ... the files are transmitted from the ftp server? no more from the streamer as before the activation of the plug ...

In the case that it is from ftp, it is possible to make a sort of load balancing? so it can possible to have more ftp servers with the streamer at the same time?

**Comment by DanielnetoDotCom** [comment]
Yes, they are transmitted from FTP server

This plugin for now allow only 1 FTP server.
