### ISSUE TITLE
direct upload issue

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#1278]
Hi,

If i upload direct 100Mb file it will ok 
but if i upload 200,300 like this error showing
 i checked php.ini file is there allow 2gb

**Comment by DanielnetoDotCom** [comment]
Looks like you are using Cloudflare

Check this : https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Using-CDN-for-Videos-Only

**Comment by gujarraju** [comment]
Thsnks
