### ISSUE TITLE
Comment system broken

### ISSUE THREAD

**Issue by gamizard** [DanielnetoDotCom/YouPHPTube#128]
Comment dialog appears when not logged in. But when logged in, comment box doesn't appear.

**Comment by DanielnetoDotCom** [comment]
I just try it on demo site and it works fine:
![image](https://user-images.githubusercontent.com/18009293/30994005-0a5593e2-a488-11e7-9c97-54edeb7ba0c0.png)

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
