### ISSUE TITLE
um... cant login! md5 error?

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1282]
So i just updates all my files and went to login, nobody can login, i did some experimenting and Mysql is fine, i hashed my password manually and entered it in the password field, and it worked.... so it wants the actual hash of the password....

**Comment by DanielnetoDotCom** [comment]
there is a new hash for more security.

but the old hash still work.

please make sure you update your streamer and encoder.
also, make sure you update with today's changes.

**Comment by jeanfrancoisvarin** [comment]
Well, I updated everything and it was after updating that it arrived.

At the moment there is still no update.

JF

**Comment by DanielnetoDotCom** [comment]
can you please check the log?

if you want try to reset your password with md5('your password') and it should work

**Comment by DanielnetoDotCom** [comment]
try this ...

if you have the latest files you should be able to get your password hash here https://your site .com/objects/encryptPass.json.php?pass=your pass

for example on demo site https://demo.youphptube.com/objects/encryptPass.json.php?pass=yourpass

check if the generated hash match with the hash on the database

**Comment by jeanfrancoisvarin** [comment]
I just tried something different.
I encoded my password with the link and copied it into the databas and it works.

And it is realy MD5 different.

**Comment by DanielnetoDotCom** [comment]
MD5 should always work, if does not the problem should be something else, not the hash

your site can have a different hash then the demo site. you now can use the salt. it makes your hash more secure but will work only on your site

![image](https://user-images.githubusercontent.com/18009293/49762967-1adb0000-fcaa-11e8-90b6-a56c3d6a2cd7.png)

**Comment by jeanfrancoisvarin** [comment]
I kept my site as simple as possible (unsalted) as it is for friend use only.
And I confirm, encoded MD5 with phpmyadmin doesn't work.

If you want, I can give you the full hand on the machine for you to check... If it helps.

**Comment by DanielnetoDotCom** [comment]
yes, it will help, please send me the credentials if you can developer@youphptube.com

**Comment by jeanfrancoisvarin** [comment]
Done ;-)

**Comment by Puyodead1** [comment]
Like i said, it was after the update that this happened, its using the actual hash as the password, lets say my password was "apple", instead of apple working, the has for apple works

**Comment by DanielnetoDotCom** [comment]
for apple your hash on the database would be the MD5 what is: 1f3870be274f6c49b3e31a0c6728957f

or the new hash what is without salt : 21cdf388e9c12a695b8492a645216fa0

you can check here https://demo.youphptube.com/objects/encryptPass.json.php?pass=apple

**Comment by DanielnetoDotCom** [comment]
@jeanfrancoisvarin I update your files with the latest and now it works from MD5 hashes

@Puyodead1 I sent some updates that will help debug in case the login fail. if you can please update your files and if the error persists share your log here.

**Comment by mili21** [comment]
Hi Daniel, i have the same issue, I just did a fresh install and i can`t login... i tried to change manual the md5 password in database, nothing... :(

**Comment by jeanfrancoisvarin** [comment]
Hello Daniel,

I just checked and it works now.

Could you please tell us what was (is) wrong and if the next git pull update will recreate the same issue.

Best regards,

JF

**Comment by DanielnetoDotCom** [comment]
@mili21 please check your log, should have some clue there 

@jean I just update your files and it was fine

**Comment by mili21** [comment]
Daniel, i just found out... apparently i can log and the website is working fine when i`m using another computer or my phone, but when i`m using my pc doesn`t login. I tried to clean all cokies, browsing history.
Any idea?

**Comment by DanielnetoDotCom** [comment]
Clear cookies is the idea. Otherwise I can see no reason to that

**Comment by Puyodead1** [comment]
Seems a recent update fixed it, i just make a video then updated.
