### ISSUE TITLE
Fatal PHP error (Simple Router)

### ISSUE THREAD

**Issue by birdie60** [DanielnetoDotCom/YouPHPTube#1283]
I have this fatal PHP error in my logfile:

```
PHP Fatal error:  Uncaught exception 'Pecee\SimpleRouter\Exceptions\NotFoundHttpException' with message 'Route not found: "/index.php/"' in /var/www/clients/client1/web2/web/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300
Stack trace:
#0 /var/www/clients/client1/web2/web/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/clients/client1/web2/web/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/clients/client1/web2/web/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300
```

**Comment by DanielnetoDotCom** [comment]
In what OS are you installing it?

**Comment by birdie60** [comment]
Hi Daniel,
my OS is Debian 8, Jessie. My YPT installation works fine, no problem with it.
Just do not know why this error happended in my logfile.

**Comment by birdie60** [comment]
I always made sure to have .htaccess in the root directory.
Above error occurred with .htaccess in place.
I just do not know why.

**Comment by DanielnetoDotCom** [comment]
is your mod rewrite enabled?

**Comment by birdie60** [comment]
Yes, that mod_rewrite module is enabled. All other routes are working fine.
And above error I only got once in my log for a long time.

**Comment by DanielnetoDotCom** [comment]
but, is your site working?

**Comment by birdie60** [comment]
Hi Daniel,
yes, my YPT installation works fine, no problem with it, except this error in log file.
