### ISSUE TITLE
How to hide only some categories?

### ISSUE THREAD

**Issue by RapFan89** [DanielnetoDotCom/YouPHPTube#1285]
Hi,
i'm going to explain better:
We have some videos  grouped into a categories and we have a lot categories, so we need to hide all the categories and show just one a time. 
At the beginning no one can view the videos inside those categories, then during the next months we want to unveil a category a time.

I hope the concept is clear.

**Comment by DanielnetoDotCom** [comment]
Hi, sorry but we do not have such feature

**Comment by RapFan89** [comment]
Ok, sorry to read that.
You should think to use that video platform in conjuction with a e-learning website. It would be cool.

**Comment by DanielnetoDotCom** [comment]
You can inactivate the videos .

This will make your categories be hidden
