### ISSUE TITLE
Multiple upload directories?

### ISSUE THREAD

**Issue by l3lackShark** [DanielnetoDotCom/YouPHPTube#1286]
Is it possible to make 2 (or more) video upload directories in YouPHPTube? I have real HP servers and they have pretty small hard drives (around 200gigs) I used to use a different platform called Streama in the past and there was a feature that let me had 2 different upload directories. I am currently looking for a similar solution in YouPHPTube since I moved. Thanks in advance. 
![24d195c8d4 1](https://user-images.githubusercontent.com/20248967/49909471-ed0bdc00-fea0-11e8-92b5-c3be5cbb4bc2.png)
 

If it is not possible, then I'm at least looking for some go-around solution for my case. I need to spread out upload files between different hard drives somehow.

**Comment by birdie60** [comment]
My suggestion: A very welcome future feature would be to allow subdirectories under /videos!
