### ISSUE TITLE
Live Streaming Issue

### ISSUE THREAD

**Issue by MalcolmMerlyn** [DanielnetoDotCom/YouPHPTube#1287]
I installed YouPHPTube and everything is working correctly except streaming. I installed nginx and I configured it according to the tutorial posted here, my website has an SSL certificate. OBS is able to connect to the server and start transmitting, the stats page works but the live player doesn't, it just says: The media could not be loaded, either because the server or network failed or because the format is not supported.

- This is my plugin configuration: <img width="705" alt="capture0" src="https://user-images.githubusercontent.com/23439395/49917704-368f0380-fe6e-11e8-846e-95d9386f3c9b.PNG">

- This is my nginx configuration: <img width="1011" alt="capture2" src="https://user-images.githubusercontent.com/23439395/49917706-3a228a80-fe6e-11e8-9f18-22a34070df4b.PNG">

- I have the FTP storage plugin and the video files are stored on another server, I am not sure if this has an impact on anything, it shouldn't.

**Comment by RedTapeTV** [comment]
> your NGINX must use SSL as well, configure your HTTPS on port 444

How is this done?

**Comment by DanielnetoDotCom** [comment]
@RedTapeTV The SSL configuration is not a YouPHPTube issue. you can try to find how to do it on google or you can hire us to configure it for you if you dont know how to do SSL https://www.youphptube.com/services
