### ISSUE TITLE
Help After site move

### ISSUE THREAD

**Issue by john-helyar** [DanielnetoDotCom/YouPHPTube#1289]
Hi there

I have recently set this up on a subdomain and it worked fine i have now changed the URL to a dedicated URL and after following the video it pretty much works but i am having one problem

when i go to my URL it always points to the YouPHPTube folder even though i have everything set as the root folder being html now if i do my URL/index.php the site loads and i can move around no problem

but how can i get it to stop going back to the default folder of YouPHPTube 

Cheers in advance

**Comment by shivan** [comment]
If you move from http to https like me, you have to enable openssl in php.ini and add the intermediate (CA) certificate in the apache configuration. (Errors will show up in youphptube.log)
