### ISSUE TITLE
Search in Mobile Site

### ISSUE THREAD

**Issue by JinZhuXing** [DanielnetoDotCom/YouPHPTube#129]
I can't use search box in mobile site.
When I use my own YouPHPTube site on android system, I can't see search box in chrome browser.

**Comment by DanielnetoDotCom** [comment]
Yes it is proposital, to make it fit on small devices

**Comment by nightstryke** [comment]
DanielnetoDotCom, it would probably be best to look into some way to detect mobile devices such as smartphones and force the website to push a mobile theme to the mobile device.

**Comment by DanielnetoDotCom** [comment]
Yeah, the mobile layout needs to be improved. I am accepting help :)

**Comment by JinZhuXing** [comment]
Thanks

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
