### ISSUE TITLE
Slack Integration Documentation

### ISSUE THREAD

**Issue by WillH1983** [DanielnetoDotCom/YouPHPTube#1290]
Hello, I am looking into using slack for notification for users.  I see there is some code to enable this, however I am having trouble configuring YouPHPTube.  Is there documentation somewhere on how to integrate Slack?  Thanks in advance for your help.

**Comment by DanielnetoDotCom** [comment]
Hi

I dont know slack.

can you please be clear?

**Comment by DanielnetoDotCom** [comment]
I see, we do not have this integration yet.

**Comment by Puyodead1** [comment]
#1303

**Comment by WillH1983** [comment]
Thanks @Puyodead1!  I was thinking about creating a plugin, and you beat me to it!  I'll review.

**Comment by WillH1983** [comment]
@Puyodead1 It looks like your changes to the file did not make it to the master branch some how.  Can you check it out and see what happened?

**Comment by WillH1983** [comment]
It looks like it was deleted as part of 32897a200b094f05354ef7122557e1ef2af58b94

**Comment by Puyodead1** [comment]
let me check

**Comment by Puyodead1** [comment]
#1309
