### ISSUE TITLE
Video Duration EE:EE:EE

### ISSUE THREAD

**Issue by gseiki** [DanielnetoDotCom/YouPHPTube#1291]
My YouPHPTube is encoding and playing videos well, but I recently uploaded my longest video, 120 minutes, and it encodes but doesn't play.  Duration time on my site is EE:EE:EE.  The video format is mp4 and its size is 287MB.  On the encoder, max encoder size is 800MB and my server has 18GB of ram.  Any advice.

**Comment by gseiki** [comment]
The video I mentioned above was ripped from DVD with HandBrake.  I just tried to rip another video using handbrake with the same result.  Sent video to encoder.  Duration is EE:EE:EE.  Video GIF shows up on YouPHPTube, but won't play.  The DVD's are educational videos being used by teachers at my school to teach students.  If anyone has any insight into how I can fix this, I would greatly appreciate your help.

**Comment by DanielnetoDotCom** [comment]
check your max upload limit.
looks like you could not transfer the video from encoder to your streamer.

**Comment by gseiki** [comment]
Thanks for responding.  I now have the following settings configured in /etc/php/7.0/apache2/php.ini 

post_max_size 1000M
upload_max_filesize 1000M
max_execution_time from 7200
memory_limit from 1000M

I've restarted apache after configuration change, but it still doesn't work.  Is there anywhere else that I should change upload size?

**Comment by Puyodead1** [comment]
no, just php.ini

**Comment by gseiki** [comment]
Do I have to change upload_max_filesize somewhere else too?

**Comment by Puyodead1** [comment]
i just said, read my comment

**Comment by RapFan89** [comment]
i'm encountering the same issue here it is the log and my ini settings:

> The encoder Max File Size is: 1.00GB 
> The Streamer Max File Size is: 1.00GB 
> The Streamer Max Video Storage Limit is: Unlimited



> [20-Dec-2018 17:04:48 UTC] ReceiveImage: Files Received for video 408: 2018-11-16-16-32-24-ok
> [20-Dec-2018 17:05:14 UTC] Encoder receiving post
> **[20-Dec-2018 17:05:14 UTC] Do not need update duration: Video Object**
> (
>     [id:Video:private] => 408
>     [title:Video:private] => 2018-11-16-16-32-24-ok
>     [clean_title:Video:private] => 2018-11-16-16-32-24-ok
>     [filename:Video:private] => _YPTuniqid_code
>     [description:Video:private] => 
>     [views_count:Video:private] => 0
>     [status:Video:private] => a
>     **[duration:Video:private] => EE:EE:EE**
>     [users_id:Video:private] => 1
>     [categories_id:Video:private] => 1
>     [old_categories_id:Video:private] => 
>     [type:Video:private] => video
>     [rotation:Video:private] => 0
>     [zoom:Video:private] => 1
>     [videoDownloadedLink:Video:private] => 
>     [videoLink:Video:private] => 
>     [next_videos_id:Video:private] => NULL
>     [isSuggested:Video:private] => 0
>     [videoGroups:Video:private] => 
>     [trailer1:Video:private] => 
>     [trailer2:Video:private] => 
>     [trailer3:Video:private] => 
>     [rate:Video:private] => 0
>     [youtubeId:Video:private] => 
>     [user] => admin
>     [name] => *user*
>     [email] => *censored*
>     [password] => *censored*
>     [created] => 2018-12-20 17:04:42
>     [modified] => 2018-12-20 17:04:48
>     [isAdmin] => 1
>     [photoURL] => videos/userPhoto/photo1.png
>     [lastLogin] => 2018-12-20 17:05:13
>     [recoverPass] => 
>     [backgroundURL] => videos/userPhoto/background1.png
>     [canStream] => 0
>     [canUpload] => 0
>     [canViewChart] => 0
>     [about] => 
>     [channelName] => ChannelName
>     [emailVerified] => 1
>     [analyticsCode] => 
>     [externalOptions] => YTowOnt9
>     [first_name] => 
>     [last_name] => 
>     [address] => 
>     [zip_code] => 
>     [country] => 
>     [region] => 
>     [city] => 
>     [order] => 1
>     [next_title] => 
>     [next_clean_title] => 
>     [next_filename] => 
>     [next_id] => 
>     [category_id] => 1
>     [iconClass] => fab fa-angular
>     [category] => Category
>     [clean_category] => category
>     [category_description] => 
>     [category_order] => 1
>     [videoCreation] => 2018-12-20 17:04:42
>     [likes] => 0
>     [dislikes] => 0
>     [myVote] => 
>     [groups] => Array
>         (
>         )
> 
>     [progress] => Array
>         (
>             [percent] => 0
>             [lastVideoTime] => 0
>         )
> 
> )

**Comment by DanielnetoDotCom** [comment]
@RapFan89 I can not see any problem on your Log file

**Comment by RapFan89** [comment]
Ok, why i get EE instead of time?

**Comment by DanielnetoDotCom** [comment]
I guess it is regarding the "file size" X "upload limit"

**Comment by DanielnetoDotCom** [comment]
my public encoder handles up to 6 GB

do you use Cloudflare? if you do your max file size is limited by them, and it is 100 MB only

**Comment by RapFan89** [comment]
i don't know i have to ask to my service provider. But i'm uploading small videos (around 10 mb of size), so i'm a lot under the 100 mb upload limit. The problem should not appear at all.

**Comment by DanielnetoDotCom** [comment]
you are uploading 10 MB, but maybe after encode it it get bigger then 100 MB.

sounds like you are using a shared server. I guess it is your provider limitation.

**Comment by RapFan89** [comment]
i have a vps (4 vCPU, 16 gb of ram, and 300 gb of ssd), and i am able to change ini settings selectively for each subdomain. It is a bit strange, because i've tested before on a raspberry pi 3 b+ and everything worked flawlessly.

**Comment by gseiki** [comment]
Daniel you are correct.  Encoder can make file much larger in size than original.  I increased my max upload.   Videos finally started working.  When I ssh into my server and use 'ls -lhS' to check file sizes in /var/www/html/YouPHPTube/Videos, I see that my video is three times the size of my original.   

I previously assumed that if my original was 500MB, that my max upload size needed to by 500MB.  But now I know that if my video is 500MB, my max upload size my need to be 3-4 times larger because after encoding the file may become much bigger. 

Thanks again for your help.

**Comment by DanielnetoDotCom** [comment]
@gseiki yes, it depends what resolution are you encoding.

I am glad you findout

**Comment by RapFan89** [comment]
I was not able to solve the issue, so i decided to create a bash script to "fix" the error. Basically it uses ffprobe to extract the duration time of videos inside youphptube's videos folder (you have to put the script there) and connect to database to update the wrong values. I hope it could be useful for someone like me. To run rename the script extension with sh in place of txt and give executions permissions then simply type ./extract-duration.sh dbuser dbpassword dbname.

[extract-duration.txt](https://github.com/DanielnetoDotCom/YouPHPTube/files/2890279/extract-duration.txt)

Warning: This will work only on HD videos, if you want to do with all resolution simply change the string into line 9.

**Comment by veljkostanar** [comment]
I'm having the same problem but i'm also having another complication. 
The php.ini file has the following. 
post_max_size = 2000M
upload_max_filesize = 2000M
max_execution_time = 7200
memory_limit = 1280M
I have restrated apachie i have even restarted the server but i can't get the below to change. 

All converted files will be submited to the streamer site http://schooltube/nws/
The encoder Max File Size is: 500.00MB The Streamer Max File Size is: 500.00MB The Streamer Max Video Storage Limit is: Unlimited The Streamer Current Video Storage is: 0.00 Minutes

I firmly under the impression this is why i'm getting EEE on my larger videos why isn't the server reflecting what the php.ini file has?

**Comment by DanielnetoDotCom** [comment]
Check your log file

**Comment by kemoi-kiptoo** [comment]
how do i check log file?

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
