### ISSUE TITLE
Playlist stuck processing forever

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [DanielnetoDotCom/YouPHPTube#1296]
I am working with a very large number of videos. When I get to the last video on a page when working under "My Channel", and set a playlist, it freezes forever every single time. I have to refresh the page in order to clear this screen.

This is the video on the very top of the page whereas all the rest of the videos are listed in rows below. At this video it freezes every time.

**Comment by The-Do-It-Yourself-World** [comment]
![playlists-freezing-on-last-video](https://user-images.githubusercontent.com/45924889/50060077-ef9a5a00-015c-11e9-954a-42e9ff875487.jpg)

**Comment by DanielnetoDotCom** [comment]
please check your log file at the time this play list get sucked.

should have some clue there 
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by The-Do-It-Yourself-World** [comment]
I cannot find such a log file on my server.

/videos/youphptube.log does not exist. At least I cannot see it with filezilla

The issue keeps recurring though.

**Comment by DanielnetoDotCom** [comment]
you must have a log file.

Just to make it clear the correct directory is not **/videos/youphptube.log** is **/[your path to your site]/videos/youphptube.log**

**Comment by DanielnetoDotCom** [comment]
try to follow this and use SSH to access the log file https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube
