### ISSUE TITLE
French translation - non escaped quotes

### ISSUE THREAD

**Issue by ledshark24** [DanielnetoDotCom/YouPHPTube#13]
Hi,

I stumbled upon non escaped quotes in the french translation that broke some interfaces. See error in "mvideos" view for example, my local fix is not perfect (deleted a single quote in "locale/fr.php" I may have missed many others. 

`$t['Re-encode Image'] = "Recodifier l'image"; ` corrected in `$t['Re-encode Image'] = "Recodifier l image";
`
please do note hesitate to ask me for more details I may look more into this if I have time but it is unlikely.

thks for the (very) good work.

**Comment by DanielnetoDotCom** [comment]
Thanks to notice it, I will take a look on that. 
It may be fixed by tomorrow

**Comment by DanielnetoDotCom** [comment]
It is fixed, i just upload a new version that fix it.
Thanks, if you find more issues, please letme know.

**Comment by ledshark24** [comment]
Hi, I confirm it : this bug is fixed. I do not notice any other problems. Thanks a lot.
