### ISSUE TITLE
Error in mysql when i try to install

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#130]
Hi!  I've tried searching on wikis and other materials but I do not find the answer.
All wikis refer to an installation on a new Ubuntu server, but I would like to install YouPHPTube on a production server (already existing) that runs CentOS with a KloxoMR control panel, so I go to the kloxomr menu and create the database with user / pass ...
![kloxomr](https://user-images.githubusercontent.com/15127860/31044063-17b7107e-a5c8-11e7-9130-6a2f18d1be37.png)

returning and entering the data into the setup menu, I get this error, for all three options, for the installation,  for writing the db ...
![error](https://user-images.githubusercontent.com/15127860/31044080-544ae704-a5c8-11e7-9e8a-bd52b3d13637.png)

I do not understand why the installation process must erase a table ...

**Comment by mikweb2017** [comment]
choose create table only i think you have chosen create database and table

**Comment by tgd1973** [comment]
I tried in all three ways and it does not work (create db and table/ create only table/ do not create any)
the answer is unique:  "Error deleting user: Table 'ckrh_vidforsky.users' doesn't exist".
Can you tell me the permissions file required for installation? Maybe it's the script install that can not run for inappropriate permissions ?

**Comment by DanielnetoDotCom** [comment]
the database user you are using have permition to **create tables and databases**?

**Comment by ThejeswarReddy** [comment]
Okay I got this,  earlier I had the same issue even the host provider couldn't solve it but here is the solution

You created database 
You created database user with password credentials 

But you didn't add user to the database 

Try adding database user to database (don't create a new user but link  the present user to database)

This will definitely work.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
