### ISSUE TITLE
Cannot upload channel background image

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [DanielnetoDotCom/YouPHPTube#1304]
I keep trying to upload a background image but it reverts to the blank image again after I save and refresh the screen. When I go back to my channel the image is gone.

Also what are the best dimensions and file type for a background image? I cant find any information on this.

What are the best dimensions for "photo" as well.

**Comment by DanielnetoDotCom** [comment]
Please check your log file to see what is happening with the save process.

The profile photo is 150x150 pixels
The background is 1250x250

**Comment by The-Do-It-Yourself-World** [comment]
Got it working. Thanks.
