### ISSUE TITLE
disable email showing 

### ISSUE THREAD

**Issue by thushy07** [DanielnetoDotCom/YouPHPTube#1306]
how to disable the email not to show in there

![screenshot from 2018-12-19 00-16-26](https://user-images.githubusercontent.com/44659184/50200377-a6e0cd80-0323-11e9-9a7d-68c68987d71d.png)

**Comment by DanielnetoDotCom** [comment]
Try those

![image](https://user-images.githubusercontent.com/18009293/50213903-b7159e80-035d-11e9-8888-9752b86dfcbc.png)

**Comment by thushy07** [comment]
Thank you, it worked
