### ISSUE TITLE
How to Add an external Live Link

### ISSUE THREAD

**Issue by u2nasir** [DanielnetoDotCom/YouPHPTube#1307]
I tried to add an M3U8 link. Its showing in External Live Links but I not found it in anywhere in playlists and not able to find any way how to play it.

Let me know how to use the plugin  Add an external Live Link

**Comment by Andiweb87** [comment]
Do you have put date and hours correct ?? when starts and when will end ?? you can show with an screenshot how you add the m3u8 link

**Comment by u2nasir** [comment]
All properties set but can you please let me know after adding links where we can watch these links as we not found in on video list etc.

**Comment by Andiweb87** [comment]
Can you put the date of yesterday in the start ? Try this and tell me

**Comment by u2nasir** [comment]
I did same already. But I don't know how its not showing anywhere. As we declare it as Public so it should be displayed somwhere in list.

![image](https://user-images.githubusercontent.com/24270998/50307263-beea5580-04b9-11e9-917c-2f0d04d41d62.png)

**Comment by Andiweb87** [comment]
Can you activate the plugin **Live** ? you can find it in the plugin section  , i see is missing in your screenshot

**Comment by Andiweb87** [comment]
also your test link is not working , i have just tested in my site

**Comment by DanielnetoDotCom** [comment]
That is right, activate the live plugin.

**Comment by u2nasir** [comment]
Yes I did both its activated and still not working.

**Comment by DanielnetoDotCom** [comment]
can you please share the link you are trying to use here?

Also add this link on the demo site and see if works.

**Comment by praiseworld3d** [comment]
I was able to get this working, however the stream was not recorded. Is there a way to do this?

**Comment by DanielnetoDotCom** [comment]
you can only record streams that you transmit directly to Nginx.
