### ISSUE TITLE
polish locale

### ISSUE THREAD

**Issue by extranet-internet-creator** [DanielnetoDotCom/YouPHPTube#1308]
I have translated "us" locale to "pl" (polish). How can I contribute it?

with command "git push [...]" I'm getting an error:
remote: Permission to DanielnetoDotCom/YouPHPTube.git denied to [...].
fatal: unable to access 'https://github.com/DanielnetoDotCom/YouPHPTube.git/': The requested URL returned error: 403

**Comment by DanielnetoDotCom** [comment]
Hi, thanks for your contribution.

you will need to have a fork of this code, then you upload your changes for your fork. then you can make a pull request. https://help.github.com/articles/about-pull-requests/

**Comment by extranet-internet-creator** [comment]
Hallo,

I send you polish locale in attachment.

Best greetings

-- 
Dominik Raś
Kierownik Działu IT
tel. bezp. +48 733 533 090
gg: 5147145
e-mail: dominik.ras@extranet.pl

extranet internet creator
ul. Wielki Rów 40B, 87-100 Toruń
tel. +48 665 590 268
e-mail: biuro@extranet.pl
https://www.extranet.pl
=========================================================
Uwaga: Jeżeli nie jest Pani/Pan adresatem tej wiadomości prosimy o poinformowanie nadawcy o jej otrzymaniu oraz niezwłoczne usunięcie treści wiadomości. Ta wiadomość może zawierać informacje poufne.
Uprzejmie informujemy, iż kopiowanie, ujawnianie, dystrybuowanie, udostępnianie lub inne wykorzystywanie wiadomości jest zabronione i może rodzić konsekwencje prawne dla osoby naruszającej zakaz.

W dniu 2018-12-21 o 10:46, YouPHPTube pisze:

**Comment by DanielnetoDotCom** [comment]
The attachment does not come.

please send it to developer@youphptube.com
