### ISSUE TITLE
Hostinger

### ISSUE THREAD

**Issue by PlayxPE** [DanielnetoDotCom/YouPHPTube#131]
Opa , sempre que tento colocar meu site na hostinger.com da algum erro na MySQL exemplo u283839_you.users não existe

**Comment by Kickassd** [comment]
Don't use crappy hosting services for video encoding and streaming.

**Comment by tgd1973** [comment]
But what about hosting? Personally I have my own server through OVH France - with CentOS and a control panel and 8 domains and I have the same problem ...

**Comment by PlayxPE** [comment]
Ok,vou pegar
 uma vps linux
