### ISSUE TITLE
Set playlist to show first video set on top

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [DanielnetoDotCom/YouPHPTube#1312]
I am working with a huge amount of videos. Some are seasons which must occur in series from the first to the last.

Problem is that when you click "play all" the playlist starts with the last video entered instead of the first video entered. Then the next video seems to be random somewhere in the middle of the playlist. Down further it gets all randomized and jumbled up no matter how the videos are organized in the playlist.

1. It would be nice if the playlist showed the first video entered on "My channel" page, followed by the next and so on rather than me manually dragging them around all the time.

2. Play back on the list should be in order, but seems horribly random.

![playlist-problems](https://user-images.githubusercontent.com/45924889/50309101-7441ec80-046b-11e9-908b-6ef78be279f2.jpg)

**Comment by The-Do-It-Yourself-World** [comment]
Trying to sort playlist now but they do not all fit on the page at one time. Therefore when I try to move a video, they all jump all over the place on me. Its like playing with a living, moving puzzle. I have 66 videos on a single playlist for example. It is impossible to get them to go into the right places.

**Comment by The-Do-It-Yourself-World** [comment]
https://www.diytube.video/channel/The-Movie-Source

**Comment by DanielnetoDotCom** [comment]
Did you close it by mistake or it was resolved?
