### ISSUE TITLE
Using youphptube as video archive.

### ISSUE THREAD

**Issue by inferno-prime** [DanielnetoDotCom/YouPHPTube#1314]
I have a few questions about changing youphptube to work for my needs. First is I only want people to leave comments and be able to watch videos that's pretty much it. Which means I will have to start removing things like the sign in box (which I want to try to use the back-end to sign in for admin) and remove any links that could lead to pages I don't want them visiting not for anything bad just that I am not using that part.

that's first any good idea's let me know and big thanks for your work and time. :)

**Comment by DanielnetoDotCom** [comment]
I think you can remove all your need on the customizeAdvanced and customizeUser plugin.

take a look on it

**Comment by DanielnetoDotCom** [comment]
@inferno-prime sorry I am not sure what are you trying to do

**Comment by inferno-prime** [comment]
Basically I want people to be able to watch and leave comments that's all

**Comment by DanielnetoDotCom** [comment]
It works that way already.

but to leave comments they need to have an account.

**Comment by inferno-prime** [comment]
That is what I am asking do you know how if not I have another way I would like to ask you about.

**Comment by DanielnetoDotCom** [comment]
Sorry, I don't understand what are you looking for.

**Comment by inferno-prime** [comment]
Well then I guess I will only allow them to watch the videos and that's it. I Don't want anyone to be able to see the sign in screen is there a way to turn the front end part off so I can login from the backend ?.

**Comment by DanielnetoDotCom** [comment]
please check the CustomizeUser plugin 

![image](https://user-images.githubusercontent.com/18009293/50636318-5fb62780-0f34-11e9-8632-502599b877e4.png)

**Comment by inferno-prime** [comment]
Ok so I guess no one will be able to log in after doing so. If that's the case Where are the templates located as there are area's not listed in the customizeuser plugin that I want to edit.

**Comment by inferno-prime** [comment]
I know this mite be off topic but this is a bit of a hassle for me. first is will you be combining the streamer and encoder into plugins in the future ? for me this would be easier. If not I normally encode the video myself then upload but it there a simple way of just adding the file association for the media type you want to upload without the encoder ?.

**Comment by DanielnetoDotCom** [comment]
You can directly upload the files. 

just make sure this option is enabled on the customAdvanced plugin -> 
doNotShowUploadMP4Button (uncheck it)

**Comment by inferno-prime** [comment]
Could you refer this question about what code to change to add more video formats to upload to the coder since I am unable to pm him on github or will that be a problem ?.

Thanks again for your help and understanding.

**Comment by DanielnetoDotCom** [comment]
sorry, what do you mean " add more video formats"?

**Comment by inferno-prime** [comment]
I mean .webm .avi etc

**Comment by DanielnetoDotCom** [comment]
this should work on the encoder, but if you want direct upload them it will not happen, because those formats are not HTML5 compatible.

but if you have some PHP skills you may be able to find somewhere to hardcode and accept those formats
