### ISSUE TITLE
user#personalInfo now working

### ISSUE THREAD

**Issue by thushy07** [DanielnetoDotCom/YouPHPTube#1316]
there is no save button in the personalinfo 
and you can't click on 
![2](https://user-images.githubusercontent.com/44659184/50323044-dd465600-04a5-11e9-8297-9c254286aa83.jpg)

the from basic info to pewrsonal info

![1](https://user-images.githubusercontent.com/44659184/50323047-e20b0a00-04a5-11e9-9407-3a905c7cd079.jpg)

**Comment by DanielnetoDotCom** [comment]
Probably your script crashes.

please check you log file and make sure you update the plugins.

**Comment by thushy07** [comment]
where can i find this log file ?
Thank you for your help

**Comment by thushy07** [comment]
Located in the /videos/youphptube.loc


[23-Dec-2018 21:17:34 UTC] [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'youPHPTube.ip2location_db3' doesn't exist<br>
SELECT * FROM ip2location_db3 WHERE INET_ATON(?) <= ip_to LIMIT 1
[23-Dec-2018 21:17:34 UTC] PHP Notice:  Undefined index: country_code in /var/www/html/plugin/User_Location/User_Location.php on line 45

**Comment by thushy07** [comment]
I fixed it 
Thank you, please close this ticket

**Comment by ZizzyDizzyMC** [comment]
For comment: I fixed this issue by referring to #1154 

>>Even if you don't have user_location enabled, the ip2location table is still required to enable user save.

**Comment by oynatbakalim** [comment]
I can't help save the user save button  oynatbakalim.org


![sss](https://user-images.githubusercontent.com/46442783/50762565-f60c8500-1275-11e9-92c9-83cbe9ea5fc4.jpg)

**Comment by DanielnetoDotCom** [comment]
@oynatbakalim , sorry I don't understand

**Comment by thushy07** [comment]
try restart the mysql and see

**Comment by oynatbakalim** [comment]
How to restart

**Comment by DanielnetoDotCom** [comment]
if you do not have the save button your PHP is crashing before the finish, check your log file.

**Comment by DanielnetoDotCom** [comment]
did you check your log file?

**Comment by oynatbakalim** [comment]
# #

[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2742475/youphptube.log)

**Comment by DanielnetoDotCom** [comment]
Hi

I do not think you have a correct installation 

Table 'bizdenal.plugins' doesn't exist
Table 'bizdenal.videos' doesn't exist

I found those on your log file, does not looks like it is installed

**Comment by oynatbakalim** [comment]
from where can I give them information from which file

**Comment by DanielnetoDotCom** [comment]
sorry what?

**Comment by Puyodead1** [comment]
Just a comment for future, you need to install the User Location tables from the Plugins tab
