### ISSUE TITLE
video upload error

### ISSUE THREAD

**Issue by KenRHill** [DanielnetoDotCom/YouPHPTube#1317]
When uploading a 12.23MB .mp4 video file, I receive the following error popup.  My site just started doing this, but has been working as far as I know for months.  I did not make any configuration changes within the last month, and this is the first time I've seen this error happen.  It does not matter which .mp4 file I try to upload I get the same error.

The error reads:  "Sorry!  File extension error (OneShot.mp4), we allow only ()"

Please advise.  Thank you.

**Comment by DanielnetoDotCom** [comment]
Is it on Encoder or Streamer?

if is encoder check this on your configuration.php

![image](https://user-images.githubusercontent.com/18009293/50373668-24753980-05c1-11e9-8ab6-0acb503cd2d7.png)

**Comment by KenRHill** [comment]
Hi Daniel,

It is happening on the encoder when I try to upload a file.  The file uploads successfully, but the encoding never takes place.  It pops up with the already mentioned error.  I checked the configuration.php file and it does have all of the file extensions listed, but still won't proceed to encode the videos.  Please advise if you can think of anything else to check.

**Comment by KenRHill** [comment]
Here is the youphptube.log text from the encoder after uploading a video.  I can't make heads or tails of it, but I see that others post their logs when they need help, so I figured I would do the same.

[24-Dec-2018 20:45:53 UTC] https://www.videorefuge.com/ == https://www.videorefuge.com/
[24-Dec-2018 20:45:53 UTC] Verification Start https://www.videorefuge.com/
[24-Dec-2018 20:45:53 UTC] Verification GetFrom Cache https://www.videorefuge.com/
[24-Dec-2018 20:45:53 UTC] Verification Response (): {"msg":["Start","https:\/\/www.videorefuge.com\/ Site verified"],"verified":true,"status":"a"}
[24-Dec-2018 20:46:16 UTC] PHP Notice:  Undefined index: allowed in /var/www/html/encoder/view/upload.php on line 13
[24-Dec-2018 20:46:16 UTC] PHP Warning:  in_array() expects parameter 2 to be array, null given in /var/www/html/encoder/view/upload.php on line 13
[24-Dec-2018 20:46:16 UTC] PHP Notice:  Undefined index: allowed in /var/www/html/encoder/view/upload.php on line 14
[24-Dec-2018 20:46:16 UTC] PHP Warning:  implode(): Invalid arguments passed in /var/www/html/encoder/view/upload.php on line 14

**Comment by DanielnetoDotCom** [comment]
for sure is something regarding the extensions array

if you can, please share your config file here

**Comment by KenRHill** [comment]
I assume the config file you are speaking of is the configuration.php file from the objects directory on the streamer site.  I could not find a configuration.php file on the encoder side.  What directory would it be located in if there is one for the encoder? I will copy and paste the text from the configuration.php file from the streamer since I am unable to upload the file. for some reason.

**Comment by KenRHill** [comment]
<?php
global $global, $config;
if(!isset($global['systemRootPath'])){
    require_once '../videos/configuration.php';
}
require_once $global['systemRootPath'] . 'objects/user.php';
require_once $global['systemRootPath'] . 'objects/functions.php';

class Configuration {

    private $id;
    private $video_resolution;
    private $webSiteTitle;
    private $language;
    private $contactEmail;
    private $users_id;
    private $version;
    private $authCanUploadVideos;
    private $authCanViewChart;
    private $authCanComment;
    private $head;
    private $logo;
    private $logo_small;
    private $adsense;
    private $mode;
    // version 2.7
    private $disable_analytics;
    private $disable_youtubeupload;
    private $allow_download;
    private $session_timeout;
    private $autoplay;
    // version 3.1
    private $theme;
    //version 3.3
    private $smtp;
    private $smtpAuth;
    private $smtpSecure;
    private $smtpHost;
    private $smtpUsername;
    private $smtpPassword;
    private $smtpPort;
    // version 4
    private $encoderURL;

    function __construct($video_resolution = "") {
        $this->load();
        if (!empty($video_resolution)) {
            $this->video_resolution = $video_resolution;
        }
    }

    function load() {
        global $global;
        $sql = "SELECT * FROM configurations WHERE id = 1 LIMIT 1";
        //echo $sql;exit;
        // add true because I was not getting the SMTP configuration on function setSiteSendMessage(&$mail)
        $res = sqlDAL::readSql($sql, "", array(), true);
        $result = sqlDAL::fetchAssoc($res);
        sqlDAL::close($res);
        if ($res && !empty($result)) {
            $config = $result;
            //var_dump($config);exit;
            foreach ($config as $key => $value) {
                $this->$key = $value;
            }
        } else {
            return false;
        }
    }

    function save() {
        global $global;
        if (!User::isAdmin()) {
            header('Content-Type: application/json');
            die('{"error":"' . __("Permission denied") . '"}');
        }
        $this->users_id = User::getId();



        $sql = "UPDATE configurations SET "
                . "video_resolution = '{$this->video_resolution}',"
                . "webSiteTitle = '{$this->webSiteTitle}',"
                . "language = '{$this->language}',"
                . "contactEmail = '{$this->contactEmail}',"
                . "users_id = '{$this->users_id}',  "
                . "authCanUploadVideos = '{$this->authCanUploadVideos}',"
                . "authCanViewChart = '{$this->authCanViewChart}',"
                . "authCanComment = '{$this->authCanComment}',"
                . "encoderURL = '{$global['mysqli']->real_escape_string($this->getEncoderURL())}',"
                . "head = '{$global['mysqli']->real_escape_string($this->getHead())}',"
                . "adsense = '{$global['mysqli']->real_escape_string($this->getAdsense())}',"
                . "mode = '{$this->getMode()}',"
                . "logo = '{$global['mysqli']->real_escape_string($this->getLogo())}',"
                . "logo_small = '{$global['mysqli']->real_escape_string($this->getLogo_small())}',"
                . "disable_analytics = '{$this->getDisable_analytics()}',"
                . "disable_youtubeupload = '{$this->getDisable_youtubeupload()}',"
                . "allow_download = '{$this->getAllow_download()}',"
                . "session_timeout = '{$this->getSession_timeout()}',"
                . "autoplay = '{$global['mysqli']->real_escape_string($this->getAutoplay())}',"
                . "theme = '{$global['mysqli']->real_escape_string($this->getTheme())}',"
                . "smtp = '{$this->getSmtp()}',"
                . "smtpAuth = '{$this->getSmtpAuth()}',"
                . "smtpSecure = '{$global['mysqli']->real_escape_string($this->getSmtpSecure())}',"
                . "smtpHost = '{$global['mysqli']->real_escape_string($this->getSmtpHost())}',"
                . "smtpUsername = '{$global['mysqli']->real_escape_string($this->getSmtpUsername())}',"
                . "smtpPort = '{$global['mysqli']->real_escape_string($this->getSmtpPort())}',"
                . "smtpPassword = '{$global['mysqli']->real_escape_string($this->getSmtpPassword())}'"
                . " WHERE id = 1";


        return sqlDAL::writeSql($sql);
    }

    function getVideo_resolution() {
        return $this->video_resolution;
    }

    function getUsers_id() {
        return $this->users_id;
    }

    function getVersion() {
        if (empty($this->version)) {
            return " 0.1";
        }
        return $this->version;
    }

    function getWebSiteTitle() {
        return $this->webSiteTitle;
    }

    function getLanguage() {
        if ($this->language == "en") {
            return "us";
        }
        return $this->language;
    }

    function getContactEmail() {
        return $this->contactEmail;
    }

    function setVideo_resolution($video_resolution) {
        $this->video_resolution = $video_resolution;
    }

    function setWebSiteTitle($webSiteTitle) {
        $this->webSiteTitle = $webSiteTitle;
    }

    function setLanguage($language) {
        $this->language = $language;
    }

    function setContactEmail($contactEmail) {
        $this->contactEmail = $contactEmail;
    }

    function currentVersionLowerThen($version) {
        return version_compare($version, $this->getVersion()) > 0;
    }

    function currentVersionGreaterThen($version) {
        return version_compare($version, $this->getVersion()) < 0;
    }

    function currentVersionEqual($version) {
        return version_compare($version, $this->getVersion()) == 0;
    }

    function getAuthCanUploadVideos() {
        return $this->authCanUploadVideos;
    }

    function getAuthCanViewChart() {
        return $this->authCanViewChart;
    }

    function getAuthCanComment() {
        return $this->authCanComment;
    }

    function setAuthCanUploadVideos($authCanUploadVideos) {
        $this->authCanUploadVideos = $authCanUploadVideos;
    }

    function setAuthCanViewChart($authCanViewChart) {
        $this->authCanViewChart = $authCanViewChart;
    }

    function setAuthCanComment($authCanComment) {
        $this->authCanComment = $authCanComment;
    }

    function getHead() {
        return $this->head;
    }

    function getLogo() {
        if (empty($this->logo)) {
            return "view/img/logo.png";
        }
        return $this->logo;
    }

    function setHead($head) {
        $this->head = $head;
    }

    function setLogo($logo) {
        $this->logo = $logo;
    }

    function getLogo_small() {
        if (empty($this->logo_small)) {
            return "view/img/logo32.png";
        }
        return $this->logo_small;
    }

    function setLogo_small($logo_small) {
        $this->logo_small = $logo_small;
    }

    function getAdsense() {
        return $this->adsense;
    }

    function setAdsense($adsense) {
        $this->adsense = $adsense;
    }

    function getMode() {
        if (empty($this->mode)) {
            return 'Youtube';
        }
        return $this->mode;
    }

    function setMode($mode) {
        $this->mode = $mode;
    }

    // version 2.7
    function getDisable_analytics() {
        return $this->disable_analytics;
    }

    function getDisable_youtubeupload() {
        return $this->disable_youtubeupload;
    }

    function getAllow_download() {
        return $this->allow_download;
    }

    function getSession_timeout() {
        return $this->session_timeout;
    }

    function setDisable_analytics($disable_analytics) {
        $this->disable_analytics = ($disable_analytics == 'true' || $disable_analytics == '1') ? 1 : 0;
    }

    function setDisable_youtubeupload($disable_youtubeupload) {
        $this->disable_youtubeupload = ($disable_youtubeupload == 'true' || $disable_youtubeupload == '1') ? 1 : 0;
    }

    function setAllow_download($allow_download) {
        $this->allow_download = ($allow_download == 'true' || $allow_download == '1') ? 1 : 0;
    }

    function setSession_timeout($session_timeout) {
        $this->session_timeout = $session_timeout;
    }

    function getAutoplay() {
        return $this->autoplay;
    }

    function setAutoplay($autoplay) {
        $this->autoplay = ($autoplay == 'true' || $autoplay == '1') ? 1 : 0;
    }

    // end version 2.7

    static function rewriteConfigFile() {
        global $global, $mysqlHost, $mysqlUser, $mysqlPass, $mysqlDatabase;
        if(empty($global['salt'])){
            $global['salt'] = uniqid();
        }
        $content = "<?php
\$global['disableAdvancedConfigurations'] = 0;
\$global['videoStorageLimitMinutes'] = 0;
\$global['webSiteRootURL'] = '{$global['webSiteRootURL']}';
\$global['systemRootPath'] = '{$global['systemRootPath']}';
\$global['salt'] = '{$global['salt']}';

\$mysqlHost = '{$mysqlHost}';
\$mysqlUser = '{$mysqlUser}';
\$mysqlPass = '{$mysqlPass}';
\$mysqlDatabase = '{$mysqlDatabase}';

/**
 * Do NOT change from here
 */

require_once \$global['systemRootPath'].'objects/include_config.php';
";

        $fp = fopen($global['systemRootPath'] . "videos/configuration.php", "wb");
        fwrite($fp, $content);
        fclose($fp);
    }

    function getTheme() {
        if (empty($this->theme)) {
            return "default";
        }
        return $this->theme;
    }

    function setTheme($theme) {
        $this->theme = $theme;
    }

    function getSmtp() {
        return intval($this->smtp);
    }

    function getSmtpAuth() {
        return intval($this->smtpAuth);
    }

    function getSmtpSecure() {
        return $this->smtpSecure;
    }

    function getSmtpHost() {
        return $this->smtpHost;
    }

    function getSmtpUsername() {
        return $this->smtpUsername;
    }

    function getSmtpPassword() {
        return $this->smtpPassword;
    }

    function setSmtp($smtp) {
        $this->smtp = ($smtp == 'true' || $smtp == '1') ? 1 : 0;
    }

    function setSmtpAuth($smtpAuth) {
        $this->smtpAuth = ($smtpAuth == 'true' || $smtpAuth == '1') ? 1 : 0;
    }

    function setSmtpSecure($smtpSecure) {
        $this->smtpSecure = $smtpSecure;
    }

    function setSmtpHost($smtpHost) {
        $this->smtpHost = $smtpHost;
    }

    function setSmtpUsername($smtpUsername) {
        $this->smtpUsername = $smtpUsername;
    }

    function setSmtpPassword($smtpPassword) {
        $this->smtpPassword = $smtpPassword;
    }

    function getSmtpPort() {
        return intval($this->smtpPort);
    }

    function setSmtpPort($smtpPort) {
        $this->smtpPort = intval($smtpPort);
    }

    function getEncoderURL() {
        global $advancedCustom;
        if(!empty($advancedCustom->useEncoderNetworkRecomendation) && !empty($advancedCustom->encoderNetwork)){
            if (substr($advancedCustom->encoderNetwork, -1) !== '/') {
                $advancedCustom->encoderNetwork .= "/";
            }
            $bestEncoder = json_decode(url_get_contents($advancedCustom->encoderNetwork."view/getBestEncoder.php"));
            if(!empty($bestEncoder->siteURL)){
                $this->encoderURL = $bestEncoder->siteURL;
            }
        }
        
        if (empty($this->encoderURL)) {
            return "https://encoder.youphptube.com/";
        }
        if (substr($this->encoderURL, -1) !== '/') {
            $this->encoderURL .= "/";
        }
        return $this->encoderURL;
    }

    function setEncoderURL($encoderURL) {
        $this->encoderURL = $encoderURL;
    }

}

**Comment by KenRHill** [comment]
I found the configurations.php file in the objects folder of the encoder.  I will paste it below.  The above one is from the streamer site under the objects directory.

**Comment by KenRHill** [comment]
<?php

if (!class_exists('Configuration')) {

    class Configuration extends ObjectYPT {

        protected $allowedStreamersURL, $defaultPriority, $version, $autodelete;

        static function getSearchFieldsNames() {
            return array('allowedStreamersURL');
        }

        static function getTableName() {
            return 'configurations';
        }

        function __construct() {
            $this->load(1);
        }

        function getAllowedStreamersURL() {
            return $this->allowedStreamersURL;
        }

        function getDefaultPriority() {
            return $this->defaultPriority;
        }

        function setAllowedStreamersURL($allowedStreamersURL) {
            $this->allowedStreamersURL = $allowedStreamersURL;
        }

        function setDefaultPriority($defaultPriority) {
            $this->defaultPriority = $defaultPriority;
        }

        function getVersion() {
            return $this->version;
        }

        function setVersion($version) {
            $this->version = $version;
        }

        function getAutodelete() {
            return $this->autodelete;
        }

        function setAutodelete($autodelete) {
            if (empty($autodelete) || strtolower($autodelete) === 'false') {
                $autodelete = 0;
            } else {
                $autodelete = 1;
            }
            $this->autodelete = $autodelete;
        }

        function currentVersionLowerThen($version) {
            return version_compare($version, $this->getVersion()) > 0;
        }

        function currentVersionGreaterThen($version) {
            return version_compare($version, $this->getVersion()) < 0;
        }

        function currentVersionEqual($version) {
            return version_compare($version, $this->getVersion()) == 0;
        }

    }

}

**Comment by DanielnetoDotCom** [comment]
no, the configuration I am talking about must be inside videos directory

path-to-youphptube/videos/configuration.php

**Comment by KenRHill** [comment]
I will paste the code from my /videos/configuration.php file, however this file contains sensitive password information which I will change in the post and use **** in place of the password.

**Comment by KenRHill** [comment]
<?php
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
$global['webSiteRootURL'] = 'https://www.videorefuge.com/';
$global['systemRootPath'] = '/var/www/html/';
$global['salt'] = '5bb42bd2b0b3a';

$mysqlHost = 'localhost';
$mysqlUser = 'root';
$mysqlPass = '********';
$mysqlDatabase = 'VR_Site';

/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';
require_once $global['systemRootPath'].'objects/include_config.php';

**Comment by DanielnetoDotCom** [comment]
Question, this error happened on the encoder correct?
Did you include the configuration.php from your streamer right?

**Comment by DanielnetoDotCom** [comment]
is it fixed now?

**Comment by KenRHill** [comment]
It seems to be functioning using Version 6.2 at this time.  Thanks for your help.
