### ISSUE TITLE
Index Page Configured wrong 

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#1318]
You can access your site in two ways: http://example.com or http://example.com/index.html(or .php). Only one way should be used. Both ways is incorrect.

Ex. https://demo.youphptube.com/index.php
    https://demo.youphptube.com

**Comment by Andiweb87** [comment]
index.html its not in the files of the site

**Comment by Puyodead1** [comment]
yeah? theres nothing wrong with that, thats how it is supposed to be.

**Comment by Zixim** [comment]
the current behavior is perfectly normal.

**Comment by gujarraju** [comment]
its ok
