### ISSUE TITLE
Videos larger than 1G does not work

### ISSUE THREAD

**Issue by CyberPool** [DanielnetoDotCom/YouPHPTube#1319]
I can not perform uploads of videos bigger than 1G, I have already verified in all the settings I put limits of 5G and it still will not.
What can it be? can you help me?

Thank you

**Comment by Puyodead1** [comment]
any errors in youphptube log? are you using your own encoder? if so, check the encoder youphptube log

**Comment by DanielnetoDotCom** [comment]
Are you using any CDN? cloudflare or something?

how much ram you have?

As @Puyodead1 said, check your log file for errors

**Comment by Puyodead1** [comment]
I seem do be having this issue with 2.26 gb movies, after they encode and are sent to the streamer, it just sits there loading, no errors, if i download the mp4 file from the videos tab it takes like a second and is unplayable

**Comment by Puyodead1** [comment]
i have my streamer at 6gb max_upload and max_post

**Comment by DanielnetoDotCom** [comment]
how big is the video after encode?

it may be bigger than 2.26 GB

**Comment by jadirj** [comment]
I believe I have the same problem. Issue #1822
