### ISSUE TITLE
how to translate language 

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#1320]
Hi..

how to translate language before is there option but not showing.

**Comment by Puyodead1** [comment]
![image](https://user-images.githubusercontent.com/14828766/50378464-d3853580-0600-11e9-936d-c96c8df21dd6.png)
If you do not see this, then you should check your log file (https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube)

**Comment by Puyodead1** [comment]
if solved please close the issue

**Comment by DanielnetoDotCom** [comment]
I removed that option because we start to have many files and the script was crashing.
but you still can manually translate files. just copy one lang file and you will be fine
