### ISSUE TITLE
Media Server (netflix clone system)

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1321]
So heres what i want to do....
I just setup the youphptube site and configured netflix style.
i have a system setup to download movies from torrents using CouchPotato and Transmission, what i want to do is after the download from Transmision is done to upload the video file to the site.

The videos are stored in /var/lib/transmission-daemon/downloads/{movie title}/{movie.mkv}.
what is the best way to do this?

**Comment by DanielnetoDotCom** [comment]
if you upload it to your encoder server, you can try the bulk encode
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Bulk-Upload-Videos
