### ISSUE TITLE
Live Streaming Issue

### ISSUE THREAD

**Issue by l3lackShark** [DanielnetoDotCom/YouPHPTube#1322]
OK, So I've setted up rtmp server and it works great on rtmp://xx.xx.xx.xx/live/stream-key
However, if I set it up in YouPHPTube, it will add index.m3u8 at the end which makes the page inaccessible which leads to an offline stream in YouPHPTube. How can I remove that index.m3u8? Thanks in advance.
![image](https://user-images.githubusercontent.com/20248967/50379903-79748680-0679-11e9-91d7-9edfad679ac1.png)
![image](https://user-images.githubusercontent.com/20248967/50379907-a163ea00-0679-11e9-9728-de47645bf47d.png)

**Comment by DanielnetoDotCom** [comment]
To be honest, I do not understand what @l3lackShark means.

m3u8 files are to be opened with live players only
