### ISSUE TITLE
Live Stream Not Playing

### ISSUE THREAD

**Issue by RedTapeTV** [DanielnetoDotCom/YouPHPTube#1325]
I am having an issue playing live stream videos in Chrome. The issue is with using both SSL and just HTML. It does work in Safari, just not Google Chrome. Below is the errors I am getting in chrome.

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
player.css:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
video-js.min.css:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
jquery.webui-popover.min.css:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
jquery-ui.min.css:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
videojs.ads.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
video.js:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
jquery-ui.min.js:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
?c=5c1bbbb3b4685:761 Uncaught TypeError: Cannot read property 'bridge' of undefined
    at ?c=5c1bbbb3b4685:761
jquery.webui-popover.min.js:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
bootstrap-list-filter.min.js:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
video.js:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
videojs-contrib-hls.min.js:2 Uncaught TypeError: Cannot read property 'EventTarget' of undefined
    at Object.<anonymous> (videojs-contrib-hls.min.js:2)
    at Object.9 (videojs-contrib-hls.min.js:2)
    at r (videojs-contrib-hls.min.js:1)
    at videojs-contrib-hls.min.js:1
    at Object.<anonymous> (videojs-contrib-hls.min.js:7)
    at Object.77 (videojs-contrib-hls.min.js:7)
    at r (videojs-contrib-hls.min.js:1)
    at e (videojs-contrib-hls.min.js:1)
    at videojs-contrib-hls.min.js:1
2videojs.persistvolume.js:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
jquery.webui-popover.min.js:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
bootstrap-list-filter.min.js:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
jquery-3.3.1.min.js:2 jQuery.Deferred exception: videojs is not defined ReferenceError: videojs is not defined
    at HTMLDocument.<anonymous> (http://redtape.tv/plugin/Live/?c=5c1bbbb3b4685:714:9)
    at l (http://redtape.tv/view/js/jquery-3.3.1.min.js:2:29375)
    at c (http://redtape.tv/view/js/jquery-3.3.1.min.js:2:29677) undefined
w.Deferred.exceptionHook @ jquery-3.3.1.min.js:2
jquery-3.3.1.min.js:2 Uncaught ReferenceError: videojs is not defined
    at HTMLDocument.<anonymous> (?c=5c1bbbb3b4685:714)
    at l (jquery-3.3.1.min.js:2)
    at c (jquery-3.3.1.min.js:2)
?c=5c1bbbb3b4685:790 A Javascript-error happend. Please tell your admin to clear the folder videos/cache. 
 If this doesn't help, attach these infos to a github-pull-request: 
 Msg:Uncaught ReferenceError: videojs is not defined 
 Url: http://redtape.tv/view/js/jquery-3.3.1.min.js, line: 2, Address: /plugin/Live/?c=5c1bbbb3b4685
video-js.min.css:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
player.css:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
jquery.webui-popover.min.css:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
jquery-ui.min.css:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by DanielnetoDotCom** [comment]
Looks like you have somewhere in your code using http instead https
