### ISSUE TITLE
rtl support

### ISSUE THREAD

**Issue by alifazeli** [DanielnetoDotCom/YouPHPTube#1327]
Hi
i want to use youphptube for an arabic-persian website, is there any rtl theme for youphptube or easy way to make it right to left?

tnx

**Comment by DanielnetoDotCom** [comment]
Hi

did you try the css? https://www.w3schools.com/CSSref/pr_text_direction.asp

try to add on site configurations->head code

**Comment by MiRHaDi** [comment]
this is good , if it change automaticly with languages
