### ISSUE TITLE
Can't upload more theMB files 

### ISSUE THREAD

**Issue by thushy07** [DanielnetoDotCom/YouPHPTube#1329]
I have set to 500 MB file to upload, but i can't even upload 250 MB files, any help will be appreciated , eventually i am planing to upload  3000 MB

![big file](https://user-images.githubusercontent.com/44659184/50459624-482add80-093b-11e9-9140-3a8ad6de1193.jpg)

Thank you

**Comment by DanielnetoDotCom** [comment]
Please read the CDN section https://github.com/DanielnetoDotCom/YouPHPTube/wiki/About-Video-Upload#know-problems

**Comment by thushy07** [comment]
Yes, i was using the Cloudflare, i remove  Cloudflare DNS and connected directly, it's working fine now
you can close this ticket now
