### ISSUE TITLE
Notificação de inscritos 

### ISSUE THREAD

**Issue by PlayxPE** [DanielnetoDotCom/YouPHPTube#133]
Sempre que vou notificar os inscritos aparece esse erro

Sorry!
Message could not be sent Could not execute: /usr/sbin/sendmail -t -i

**Comment by DanielnetoDotCom** [comment]
no servidor que vc está usando vc tem um servidor de email configurado?
talvez você possa usar um email SMTP en configurações

![image](https://user-images.githubusercontent.com/18009293/31056473-85d36c66-a6a8-11e7-9dc0-d5d95374e4e3.png)

**Comment by PlayxPE** [comment]
Obrigado pela Ajuda
