### ISSUE TITLE
Broken images on channels page

### ISSUE THREAD

**Issue by takleung** [DanielnetoDotCom/YouPHPTube#1330]
Hi,

When I go to embed Vimeo video, no thumb images can be displayed. For the rest the thumb images is fine.

![screenshot 2018-12-27 at 11 24 46 pm](https://user-images.githubusercontent.com/208190/50485071-b1d7e400-0a2e-11e9-98b7-5b86642c730e.png)
![screenshot 2018-12-27 at 11 21 21 pm](https://user-images.githubusercontent.com/208190/50485072-b1d7e400-0a2e-11e9-9ee8-2a8bdc55731d.png)

Thanks,
Ray

**Comment by DanielnetoDotCom** [comment]
I am not sure what happened.

can you access the image direct into the browser?

if you put the Image URL does it open?

**Comment by takleung** [comment]
Hi, Thanks replied, cannot be displayed on the following image URL

http://smartvdobeta.smartlinkmul.com/videos/_YPTuniqid_5c24e470b9ed64.45659127_thumbsV2.jpg

will redirect to

http://smartvdobeta.smartlinkmul.com/view/img/image404.php?notFound=1

I also checked with physical folder, prefix "_thumbsV2" not exists as well.

![image](https://user-images.githubusercontent.com/208190/50498000-0f445300-0a78-11e9-8e98-aa9301c6c9be.png)


Ray

**Comment by DanielnetoDotCom** [comment]
I guess you miss a php lib to generate images, check your log file, you probably miss the GD lib for PHP

**Comment by takleung** [comment]
Hi,

you are right, can see images now after installing php5.6-gd. Thank you very much!

Ray
