### ISSUE TITLE
New Download Button on Play page doesn't work with Audio

### ISSUE THREAD

**Issue by JSY-Ben** [DanielnetoDotCom/YouPHPTube#1332]
Hi there :)

Sorry, hopefully a relatively simple one. The new download button you put on the video play page doesn't work with Audio/MP3. The button opens, but there are no download options. It does work on the Gallery search page.

Thank you for your help :)

**Comment by DanielnetoDotCom** [comment]
can you please screenshot what button are you talking about?

**Comment by JSY-Ben** [comment]
Hi there again. of course :)

When you press download button while viewing a movie you get the options as seen here

<img width="1083" alt="screenshot 2018-12-28 at 13 08 23" src="https://user-images.githubusercontent.com/13555701/50516271-c903e980-0aa1-11e9-822f-c1db3d2875b7.png">

When you do the same on playback of audio, the window opens, but there are no download options.

<img width="1249" alt="screenshot 2018-12-28 at 13 08 38" src="https://user-images.githubusercontent.com/13555701/50516284-d620d880-0aa1-11e9-9e62-636aaf40e92d.png">

However on the 'Gallery' page where you are searching for items, the download button lets you get an MP3 or an MP4 depending on what is the clip.

<img width="245" alt="screenshot 2018-12-28 at 13 10 25" src="https://user-images.githubusercontent.com/13555701/50516308-00729600-0aa2-11e9-958d-7cf985d7f862.png">
<img width="232" alt="screenshot 2018-12-28 at 13 10 35" src="https://user-images.githubusercontent.com/13555701/50516309-023c5980-0aa2-11e9-843a-a764ad71a56b.png">

Many thanks again :)

**Comment by DanielnetoDotCom** [comment]
Thanks, I sent a fix

**Comment by DanielnetoDotCom** [comment]
Thanks, I appreciate your donation and support :)
