### ISSUE TITLE
Direct Upload MKV from server (bulk upload from direct upload)

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1334]
Is there a way to just use the files i already have with out encoding? i just want the server to play the files downloaded in /var/www/Downloads/Complete without encoding

**Comment by DanielnetoDotCom** [comment]
Your browser supports only MP4 and WEBM , both if they have the right codec.

You can directly upload those files (MP4/WEBM) but not MKV

please read this
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/About-Video-Upload
