### ISSUE TITLE
Mobile App not showing thumbnails

### ISSUE THREAD

**Issue by KenRHill** [DanielnetoDotCom/YouPHPTube#1335]
The mobile app is not showing thumbnails. I have tried from two different mobile phones and two separate carriers as well as on my home wireless network. Can't get the thumbnails to load in the android YouPHPTube app.  Even if I wait for several minutes, none of the video thumbs show up. What might cause this issue? I have provided a screen capture for visual reference.

![screenshot_20181229-002906_ypt mobile](https://user-images.githubusercontent.com/37643777/50535634-cedce780-0b00-11e9-81a5-c081badb070e.jpg)

**Comment by DanielnetoDotCom** [comment]
if you connect on the demo site, the same happened?

it is working on my side

**Comment by KenRHill** [comment]
The demo site is working. It appears it is just my site that is affected. Not sure what the cause is.

**Comment by DanielnetoDotCom** [comment]
Did you also update your encoder?
