### ISSUE TITLE
Failed to upload channel background images

### ISSUE THREAD

**Issue by takleung** [DanielnetoDotCom/YouPHPTube#1336]
Hi,

I failed to update channel background image. profile pic is fine to update. I checked youphptube.log and showing the following. See if any insight on it and many thanks!

![image](https://user-images.githubusercontent.com/208190/50536214-f37ea100-0b8c-11e9-967b-921df9cdfcb4.png)

![image](https://user-images.githubusercontent.com/208190/50536211-e5308500-0b8c-11e9-90bb-4beeb8876182.png)

Thanks,
Ray

**Comment by DanielnetoDotCom** [comment]
clear your browser cache and make sure it was not updated.

about the error log, make sure you have the latest files

**Comment by takleung** [comment]
I tried to use another computer with private browser and I keep to tail the youphptube log file. Image still not update and the error log keep to same error message like the attached.

**Comment by takleung** [comment]
Hi, I saw the background image updated finally. Thank you very much! On the other hand, it seems those images is cached. May I know any way can disable first?

**Comment by DanielnetoDotCom** [comment]
the images cache is your browser/network configuration. if you want to disable it you have to do it on your side.
