### ISSUE TITLE
Change stors video broke web site

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/YouPHPTube#1337]
Hello, 
i install a new frech instance of youPHPTUBE on my raspberry, 

like u now raspberry have only 16gb sd disque, so we need to a shared directory to store video.
so i used a fstab mount 
and he look likes works, my problem on the web site, some many thinks of the site is not found : 

so when i go on my website : 
![image](https://user-images.githubusercontent.com/32466950/50537654-d6cd7380-0b62-11e9-846c-ab6581fc3711.png)

if i look log i see this ! 

![image](https://user-images.githubusercontent.com/32466950/50537674-109e7a00-0b63-11e9-8c39-c43cc25a6327.png)

if u look the link generate by youPhptube, is adding my  symbolic link on the url of all image of youPhptube, it"s a problem, do u know how fix this please

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Can-I-store-my-videos-in-another-location%3F

**Comment by DanielnetoDotCom** [comment]
did you try to directly access the css file to make sure the file is there?

**Comment by DanielnetoDotCom** [comment]
Yes, I know what is going on ...

the configuration creates the $global['webSiteRootURL'] dynamicly based on the configuration location.

For example, my configuration.php is this ...

```
<?php
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
//$global['webSiteRootURL'] = 'https://demo.youphptube.com/';
// get the subdirectory, if exists
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;

$global['systemRootPath'] = '/var/www/YouPHPTube/';
$global['salt'] = '5bf449299a0be';

$global['disableAdvancedConfigurations'] = 1;

$mysqlHost = 'localhost';
$mysqlPort = '3306';
$mysqlUser = 'root';
$mysqlPass = '*****';
$mysqlDatabase = 'youPHPTube';

/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';

```

to force the correct URL change the variable 


```
<?php
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
$global['webSiteRootURL'] = 'https://demo.youphptube.com/';

$global['systemRootPath'] = '/var/www/YouPHPTube/';
$global['salt'] = '5bf449299a0be';

$global['disableAdvancedConfigurations'] = 1;

$mysqlHost = 'localhost';
$mysqlPort = '3306';
$mysqlUser = 'root';
$mysqlPass = '*****';
$mysqlDatabase = 'youPHPTube';

/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';

```

so leave only the commented line in place of the code 

Replace this ...

**$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;**

for this

**$global['webSiteRootURL'] = 'https://demo.youphptube.com/';**

**Comment by gamersalpha** [comment]
Hello

works i changed in videos/configuration files : 
`
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;`

by this : 

`$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME']."/"`

and now works thanks

**Comment by DanielnetoDotCom** [comment]
Yes, it also works, it will ignore the subdirectory
