### ISSUE TITLE
Porblem with Update  of 6.4

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#1339]
every time I update the database I have problems with the server you can possibly check your script.

average load to 12 ! 

I do not know what happens again. I have to suspend the server and go back 2 or 3 times each time

![bildschirmfoto 2018-12-28 um 21 02 32](https://user-images.githubusercontent.com/30271757/50538550-99241700-0b71-11e9-91a6-5683bfac664e.png)

**Comment by DanielnetoDotCom** [comment]
try to manually run the update sql script ;

maybe PHP is not able to handle that

**Comment by mikweb2017** [comment]
ok, thanks to the next update I try it
