### ISSUE TITLE
Language 

### ISSUE THREAD

**Issue by PlayxPE** [DanielnetoDotCom/YouPHPTube#134]
Como eu removo a linguagem e coloco o sinal de notificação

**Comment by DanielnetoDotCom** [comment]
Como assim?

**Comment by PlayxPE** [comment]
Na demo do site não tem a opeção de linguagem, no lugar tem um sino de notificação , gostaria de colocar

**Comment by DanielnetoDotCom** [comment]
Here is working 
![image](https://user-images.githubusercontent.com/18009293/31075385-a094209c-a74b-11e7-9839-3e2e42df3f6f.png)

**Comment by PlayxPE** [comment]
Eu gostaria de removelo

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
