### ISSUE TITLE
There is a bug in the page linking to clean_title when entering the channel

### ISSUE THREAD

**Issue by AmesianX** [DanielnetoDotCom/YouPHPTube#1343]
If you click a video on the list on page 2 after entering the channel, the URL is wrong with clean_title. It does not link to the video.

For example:
http://example.com/video/clean_title?channelName=xxxxx/page/2

I hope to fix the bug quickly.

**Comment by DanielnetoDotCom** [comment]
I try what you described on demo site and I could not reproduce this error
