### ISSUE TITLE
Bug with playing trailers in netflix mode

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1344]
http://server2.puyodead1-development.me/img/u/20.00.10-30.12.18.png
![image](https://user-images.githubusercontent.com/14828766/50553094-bccc8780-0c6d-11e9-854a-78e329ac9a9d.png)
cant access the controls

**Comment by DanielnetoDotCom** [comment]
that is know problem, e are working to find a solution.

this is because of the screen resolution

**Comment by Puyodead1** [comment]
👌
