### ISSUE TITLE
Secure Videos Plugin not working

### ISSUE THREAD

**Issue by ermitchell78** [DanielnetoDotCom/YouPHPTube#1346]
I purchased the secure videos plugin however when trying to configure it i get the following error.

[31-Dec-2018 22:07:25 UTC] PHP Warning:  file_get_contents(http://52.200.55.165/YouPHPTube/videos/X-Sendfile.test): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /var/www/html/YouPHPTube/plugin/SecureVideosDirectory/SecureVideosDirectory.php(14) : eval()'d code(1) : eval()'d code on line 23
[31-Dec-2018 22:09:19 UTC] PHP Warning:  file_get_contents(http://52.200.55.165/YouPHPTube/videos/X-Sendfile.test): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /var/www/html/YouPHPTube/plugin/SecureVideosDirectory/SecureVideosDirectory.php(14) : eval()'d code(1) : eval()'d code on line 23

I have verified that all folders have the correct permissions.

**Comment by DanielnetoDotCom** [comment]
Hi, 

Did you see that tutorial?

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Moving-videos-directory-and-securing-files-from-direct-access-to-the-video-source-file

**Comment by ermitchell78** [comment]
Yes I followed that. I cannot see where the X-Sendfile.txt is created. Your script is calling for it but it is not being created.

**Comment by DanielnetoDotCom** [comment]
please double check if you uncomment the .htaccess line 

<IfModule mod_xsendfile.c>
    **RewriteRule    ^videos/([A-Za-z0-9-_.]+)$ view/xsendfile.php?file=$1    [NC,L]**
</IfModule>

**Comment by ermitchell78** [comment]
i have triple checked it. Out of the box it was never commented.

**Comment by ermitchell78** [comment]
# It must be before image not found
    <IfModule mod_xsendfile.c>
       RewriteRule    ^videos/([A-Za-z0-9-_.]+)$ view/xsendfile.php?file=$1    [QSA]
    </IfModule>

This is how it looks

**Comment by ermitchell78** [comment]
which steps was that in or how can i check.

**Comment by DanielnetoDotCom** [comment]
Install apache xsendfile

sudo apt-get install libapache2-mod-xsendfile && sudo a2enmod xsendfile 

Configure your apache XSendFile

sudo nano /etc/apache2/apache2.conf <Directory /var/www/YouPHPTube/> Options Indexes FollowSymLinks XSendFile on XSendFilePath /var/www/YouPHPTube/ AllowOverride All Require all granted Order Allow,Deny Allow from All </Directory>

**Comment by ermitchell78** [comment]
That has been done as well. As I said I followed the instructions.

**Comment by ermitchell78** [comment]
ubuntu@ip-10-11-1-247:~$ sudo apt-get install libapache2-mod-xsendfile && sudo a2enmod xsendfile
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libapache2-mod-xsendfile is already the newest version (0.12-2).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
Module xsendfile already enabled

<Directory /var/www/html/YouPHPTube/>
    Options Indexes FollowSymLinks
    XSendFile on
    XSendFilePath /var/www/html/YouPHPTube/
    AllowOverride All
    Require all granted
    Order Allow,Deny
    Allow from All
</Directory>

**Comment by DanielnetoDotCom** [comment]
Please if you can send the ssh credentials and the admin password of your site  to developer@youphptube.com

I will take a look tomorrow .

I am out of ideas for now

**Comment by DanielnetoDotCom** [comment]
Also make sure you restart Apache

**Comment by ermitchell78** [comment]
yup done that several times as well as rebooting the whole mess.

**Comment by ermitchell78** [comment]
ill send you the password and ssh cert

**Comment by DanielnetoDotCom** [comment]
notify me here when you send it

**Comment by ermitchell78** [comment]
Just sent the information.

**Comment by DanielnetoDotCom** [comment]
What I found so far was ...

Problem: You had S3 plugin enabled but not configured
Solution: I disabled it

You miss the HTML work from the path
![image](https://user-images.githubusercontent.com/18009293/50587354-58234f80-0e5c-11e9-862a-ad395154bbe2.png)


As long as you are not using the autoplay function, you should increase the timeout, I user 300 (5 minutes)

you changed the .htaccess original file, I change it back

![image](https://user-images.githubusercontent.com/18009293/50587545-1a72f680-0e5d-11e9-8a5b-72ca8f7d7214.png)

You should be all set now

**Comment by ermitchell78** [comment]
I just tried it out and nope still not working. I went ahead and moved the /var/www/html/YouPHPTube/videos. to just /videos as a test it everything breaks. The site doesnt even display correcly

**Comment by DanielnetoDotCom** [comment]
I will try to fix for you again, but it was working, do not need to change anything.

**Comment by DanielnetoDotCom** [comment]
It is back to work.

please try again.

**Comment by ermitchell78** [comment]
what did you do to fix it and why will it not let me change the videos folder as the plugin is supposed to do

**Comment by ermitchell78** [comment]
also you may want to update https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Moving-videos-directory-and-securing-files-from-direct-access-to-the-video-source-file as the corrections above with the missing html and .htaccess came from those instructions.

**Comment by DanielnetoDotCom** [comment]
the plugin needs a full path to the videos directory

if you want to move the location, you need to create a symbolic link, maybe you missed that part.

but it is only necessary if you have another storage drive on your server. I do not think it is your case

**Comment by ermitchell78** [comment]
i did create a symbolic link just not to another drive but to another directry

**Comment by ermitchell78** [comment]
sudo ln -s /videos /var/www/html/YouPHPTube/videos

**Comment by DanielnetoDotCom** [comment]
I do not recommend you to do it just to change location.

it worth only if you have a different storage drive

**Comment by ermitchell78** [comment]
I mounted a new EBS sand did the move and it worked. Awsome thanks for your help. Just wandering have you ever tried using NFS for the move. Now on to S3
