### ISSUE TITLE
Admin send emails to all members and not just subs

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [DanielnetoDotCom/YouPHPTube#1347]
Members can send emails to all their subscribers but admin cannot send a message to all subs at this time.

Can we please set it up so the admin can send email to ALL members?

**Comment by DanielnetoDotCom** [comment]
Thanks, it may be improved in the future.

**Comment by The-Do-It-Yourself-World** [comment]
I have been asking for this for a year now.
