### ISSUE TITLE
Google left side adsense showing on top and side

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [DanielnetoDotCom/YouPHPTube#1348]
When I turn on google adsense under customized advanced and then "showAdsenseBannerOnLeft" the ads show up on the top of the website AND the right side next to a video. This messes things up badly, pushing the entire website down.

**Comment by DanielnetoDotCom** [comment]
Did you try to uncheck this ?

![image](https://user-images.githubusercontent.com/18009293/50572696-45e5da80-0da4-11e9-962c-bc883229438d.png)

**Comment by The-Do-It-Yourself-World** [comment]
Yes of course. I am only talking about the left side one. It shows up on top and left side. If I check both, I get two ads on top and one on the left side.

**Comment by DanielnetoDotCom** [comment]
So probably you have an unnecessary ad code somewhere.

it is duplicating the code. make sure you have only one adsense code. 

check the customizeAdvanced plugin and the site configurations

**Comment by The-Do-It-Yourself-World** [comment]
I was only using the adsense built into the site. There is only one single place for adsense code to be put in.

When I click the button next to show adsense on left side, it shows on the left side and the top.

I have fought with this for a year and it is always the same.

Forget it anyway. Yesterday I found the locations of the code and am hard coding my own adsense into the site. Works beautifully now.

**Comment by DanielnetoDotCom** [comment]
I am glad you find a solution
