### ISSUE TITLE
new player

### ISSUE THREAD

**Issue by zebmak** [DanielnetoDotCom/YouPHPTube#135]
how to add new player?
how to install new theme?

**Comment by DanielnetoDotCom** [comment]
To add a new player, needs to create a plugin, (some coding).

To use a different theme you can mix the plugins (Gallery and Fabebook)

![image](https://user-images.githubusercontent.com/18009293/31056528-77b460bc-a6a9-11e7-89cc-d05aa2d83101.png)

And go to Themes on Configurations 

![image](https://user-images.githubusercontent.com/18009293/31056534-95ecbcd2-a6a9-11e7-908c-400517f196c6.png)

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
