### ISSUE TITLE
Cant get audio uploads to work

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [DanielnetoDotCom/YouPHPTube#1350]
I enabled the direct audio upload under customize advanced. Uploaded an audio file. It worked fine. Went to My Videos and edited the description and made it active.

Went to the audio menu and found the file. Nice.

Opened the audio to play it and got a youphptube logo as the stock image. Not good.

Clicked on play and then a cool looking player opened up but there were no controls. nothing. No sound and no controls to do anything. It just sat there looking cool.

**Comment by DanielnetoDotCom** [comment]
please, make sure you have the latest files updated, we recently sent some updates regarding audio files,
