### ISSUE TITLE
Top Menu problem

### ISSUE THREAD

**Issue by Andiweb87** [DanielnetoDotCom/YouPHPTube#1353]
Im using the Top menu plugin and created page like the images show

https://snag.gy/8iN3Ko.jpg

but the problem is when im try to edit the page created im not see them , i choose Livescore and after click Menu Items or Edit Menu Items, the menu items pages are missing and i cant edit them.

https://snag.gy/xhBcun.jpg

**Comment by DanielnetoDotCom** [comment]
can you please reproduce it on demo site?

**Comment by DanielnetoDotCom** [comment]
try to update your files to the latest

**Comment by Andiweb87** [comment]
i made it just 2 hours ago , same

**Comment by DanielnetoDotCom** [comment]
check if there is any Javascript error

**Comment by Andiweb87** [comment]
fixed, an javascript code i have put in the page make an conflict with top menu. Thank you Daniel :)
