### ISSUE TITLE
 Secure Videos Plugin STILL not working see #1346 

### ISSUE THREAD

**Issue by ermitchell78** [DanielnetoDotCom/YouPHPTube#1355]
Can you please give me a list of what all you did. I have recreated the steps with a mounted drive on my second test system and it breaks everything. You had to do more than just the html missing and the .htaccess

**Comment by DanielnetoDotCom** [comment]
Please check your videos/configuration.php file 

There is a dynamic script to create the path

I have changed it too.

Put it manually/static the path to your installation

**Comment by ermitchell78** [comment]
Can you provide an example

**Comment by DanielnetoDotCom** [comment]
I just update the comment above, but if you paste your configuration.php here I can tell you how it should looks like

**Comment by ermitchell78** [comment]
<?php
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
//$global['webSiteRootURL'] = 'http://34.207.174.2/YouPHPTube/';
// get the subdirectory, if exists
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;

$global['systemRootPath'] = '/var/www/html/YouPHPTube/';
$global['salt'] = '5c2cf3bd79b5e';

**Comment by ermitchell78** [comment]
<?php
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
//$global['webSiteRootURL'] = 'http://34.207.174.2/YouPHPTube/';
// get the subdirectory, if exists
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;

$global['systemRootPath'] = '/var/www/html/YouPHPTube/';

**Comment by ermitchell78** [comment]
global['systemRootPath'] = '/var/www/html/YouPHPTube/';
$global['salt'] = '5c2cf3bd79b5e';

**Comment by DanielnetoDotCom** [comment]
please look for the **$global['webSiteRootURL']** variable as I mention above

**Comment by ermitchell78** [comment]
global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;

**Comment by DanielnetoDotCom** [comment]
Please read above https://github.com/DanielnetoDotCom/YouPHPTube/issues/1355#issuecomment-450931002

remove the dynamic line ....
`global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;`

and manually create the variable ...

`$global['webSiteRootURL'] = 'https://yoursite.com/';`

**Comment by ermitchell78** [comment]
//$global['webSiteRootURL'] = 'http://34.207.174.2/YouPHPTube/';
// get the subdirectory, if exists
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
$global['webSiteRootURL'] = 'https://34.207.174.2/';

this is what i have now and its still not working. If i go to http://34.207.174.2/YouPHPTube its just a jumbled mess. If I go to Https:// it gives unable to connect

**Comment by ermitchell78** [comment]
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
//$global['webSiteRootURL'] = 'http://34.207.174.2/YouPHPTube/';
// get the subdirectory, if exists
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
$global['webSiteRootURL'] = 'https://34.207.174.2/';

**Comment by ermitchell78** [comment]
ok this is what it looks like currently

<?php
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
//$global['webSiteRootURL'] = 'http://34.207.174.2/YouPHPTube/';
$global['webSiteRootURL'] = 'https://34.207.174.2/';

$global['systemRootPath'] = '/var/www/html/YouPHPTube/';
$global['salt'] = '5c2cf3bd79b5e';

**Comment by ermitchell78** [comment]
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
//$global['webSiteRootURL'] = 'http://34.207.174.2/YouPHPTube/';
$global['webSiteRootURL'] = 'https://34.207.174.2/';

$global['systemRootPath'] = '/var/www/html/YouPHPTube/';
$global['salt'] = '5c2cf3bd79b5e';

**Comment by ermitchell78** [comment]
It still is not working

**Comment by DanielnetoDotCom** [comment]
You are missing something , I just notice you put https instead http on your url

Try $global['webSiteRootURL'] = ' http://34.207.174.2/YouPHPTube/ ';

**Comment by ermitchell78** [comment]
I had to change ip addresses. so it looks like that lets the site kinda of work but after that change i can no longer get the secure videos plugin. It just sits and spins after clicking on the configuration button.
<img width="1285" alt="screen shot 2019-01-02 at 1 52 50 pm" src="https://user-images.githubusercontent.com/46095137/50609609-ccc6b000-0e95-11e9-8711-6baf951f63cd.png">

**Comment by DanielnetoDotCom** [comment]
Also looks like your server on http://34.207.174.2 is not working

**Comment by ermitchell78** [comment]
here is the config file
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
//$global['webSiteRootURL'] = 'http://3.82.10.143/YouPHPTube/';
$global['webSiteRootURL'] = ' http://3.82.10.143/YouPHPTube/';

$global['systemRootPath'] = '/var/www/html/YouPHPTube/';
$global['salt'] = '5c2d0a52babb3';

**Comment by DanielnetoDotCom** [comment]
You will need to check your log file

**Comment by ermitchell78** [comment]
[02-Jan-2019 19:55:55 UTC] PHP Notice:  Undefined index: host in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 66
[02-Jan-2019 19:55:55 UTC] PHP Notice:  Undefined index: host in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 69
[02-Jan-2019 19:55:55 UTC] PHP Notice:  Undefined index: scheme in /var/www/html/YouPHPTube/plugin/LiveChat/LiveChat.php on line 49
[02-Jan-2019 19:55:55 UTC] PHP Notice:  Undefined index: host in /var/www/html/YouPHPTube/plugin/LiveChat/LiveChat.php on line 54
[02-Jan-2019 19:56:02 UTC] PHP Notice:  Undefined index: scheme in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 58
[02-Jan-2019 19:56:02 UTC] PHP Notice:  Undefined index: host in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 65
[02-Jan-2019 19:56:02 UTC] PHP Notice:  Undefined index: host in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 66
[02-Jan-2019 19:56:02 UTC] PHP Notice:  Undefined index: host in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 69
[02-Jan-2019 19:56:02 UTC] PHP Notice:  Undefined index: scheme in /var/www/html/YouPHPTube/plugin/LiveChat/LiveChat.php on line 49
[02-Jan-2019 19:56:02 UTC] PHP Notice:  Undefined index: host in /var/www/html/YouPHPTube/plugin/LiveChat/LiveChat.php on line 54
[02-Jan-2019 19:56:09 UTC] PHP Notice:  Undefined index: scheme in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 58
[02-Jan-2019 19:56:09 UTC] PHP Notice:  Undefined index: host in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 65
[02-Jan-2019 19:56:09 UTC] PHP Notice:  Undefined index: host in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 66
[02-Jan-2019 19:56:09 UTC] PHP Notice:  Undefined index: host in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 69
[02-Jan-2019 19:56:09 UTC] PHP Notice:  Undefined index: scheme in /var/www/html/YouPHPTube/plugin/LiveChat/LiveChat.php on line 49
[02-Jan-2019 19:56:09 UTC] PHP Notice:  Undefined index: host in /var/www/html/YouPHPTube/plugin/LiveChat/LiveChat.php on line 54


All about live which is weird nothing on the secure files

**Comment by ermitchell78** [comment]
none of the live plugins are enabled

**Comment by ermitchell78** [comment]
if you want the admin pass and cert are the same i sent you.  Just please let me know everything that you change

**Comment by ermitchell78** [comment]
[02-Jan-2019 19:48:11 UTC] [aEC] JS-Err: Error: Syntax error, unrecognized expression: http://3.82.10.143/YouPHPTube/plugin/SecureVideosDirectory/page/check.php @ line 2 in file http://3.82.10.143/YouPHPTube/view/js/jquery-3.3.1.min.js at visit on /YouPHPTube$

**Comment by ermitchell78** [comment]
This is the error

**Comment by DanielnetoDotCom** [comment]
Sorry, looks like your installation is all messed up

**Comment by ermitchell78** [comment]
in which way

**Comment by ermitchell78** [comment]
That is a fresh install.  Im sorry but from what i have seen there is no way to justify purchasing services from you. So far the installation instructions are wrong. The plugin instructions are wrong. we have already purchased plugins and of the 2 we have tested neither work. I appreiciate the help from this morning but you must have changed something that you are not telling us about in what i am guessing is an attempt to get us to purchase services. Im sorry but if there is going to be any more money spent it will be on a different product

**Comment by DanielnetoDotCom** [comment]
I understand your point but this morning I fix your server 2 times and described everything what was wrong .

I still don't understand why you drop that servers and start it over again.

Also never seen the errors you are showing here before and there is no way for me to guess what is wrong.

Can you make it work if you disable all plugins?

That is the first step, then you can try to enable the plugins

**Comment by ermitchell78** [comment]
I have disabled and reenable the only plugins that we are using. I do appreciate your help this morning but will say that no where in your instructions does it say anything about changing the config file for the secure videos server also the missing html in the apache config as well as the .htaccess where identical to your online instructions which are wrong. I changed the server because the one you were on is in a test environment. I have to be able to recreate it for production and also to make sure that you hadnt made any changes that we did not know of (which it looks like has happened.) Our policy is nothing goes on production that has had unkown users with admin access it.

**Comment by DanielnetoDotCom** [comment]
Is the live plug-in enabled?

**Comment by DanielnetoDotCom** [comment]
Is the live plug-in enabled?

**Comment by ermitchell78** [comment]
no it is not nor has it ever been

**Comment by DanielnetoDotCom** [comment]
I just login in your site and test it.

and it is working fine, with the secure plugin enabled.

what is the error?

I also tried to connect in your server and I could not. I guess you changed the key

**Comment by ermitchell78** [comment]
[02-Jan-2019 19:48:11 UTC] [aEC] JS-Err: Error: Syntax error, unrecognized expression: http://3.82.10.143/YouPHPTube/plugin/SecureVideosDirectory/page/check.php @ line 2 in file http://3.82.10.143/YouPHPTube/view/js/jquery-3.3.1.min.js at visit on /YouPHPTube$

**Comment by ermitchell78** [comment]
The above is the issue. If you login click on plugin and then plugin configuration button you just get the spinning wheel. It not long shows or allows to change the path

**Comment by DanielnetoDotCom** [comment]
I did that and I could edit and save the plugin

**Comment by ermitchell78** [comment]
You dont get the spinning wheel with no instructions or anything.i

**Comment by ermitchell78** [comment]
Or are you saying to just ignore the wheel and php errors and go ahead and move the folder

**Comment by DanielnetoDotCom** [comment]
Sorry, I just see what spinning are you talking about.

to be honest, I never seen this error before, you can ignore it and try.

**Comment by ermitchell78** [comment]
I went ahead a did the move. It is still kicking the php errors but it did work.

**Comment by DanielnetoDotCom** [comment]
I am glad it is working.
