### ISSUE TITLE
Apply group at logon

### ISSUE THREAD

**Issue by JohnnySSH** [DanielnetoDotCom/YouPHPTube#1356]
Hi, I wonder if it is possible to apply a group at user logon or signup?

What I would like to achieve is to have a private section and public section. I have currently achieved this by using groups; so any video tagged with a group needs a user to be logged in and part of that group.

I am using Facebook authentication to log users in. Is there a way to automatically add these users to the group rather then having to manually do it?

Thanks.

**Comment by DanielnetoDotCom** [comment]
I see, but for now, we do not have that option.
It may be added in the future, but if you are interested we can create that feature for you now if you are willing to pay.
If you want a quote, please email us the feature details: developer@youphptube.com
