### ISSUE TITLE
SQL error on translate

### ISSUE THREAD

**Issue by JohnnySSH** [DanielnetoDotCom/YouPHPTube#1357]
I'm getting this error in the log when trying to run the translate on the locale page:

[code]
[sqlDAL::readSql] (mysqlnd) Prepare failed: (1064) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND v.clean_title = 'test-qual-1'  LIMIT 1' at line 1<br>
SELECT u.*, v.*,  nv.title as next_title, nv.clean_title as next_clean_title, nv.filename as next_filename, nv.id as next_id, c.id as category_id,c.iconClass,c.name as category,c.iconClass,  c.clean_name as clean_category,c.description as category_description,c.nextVideoOrder as category_order, v.created as videoCreation,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = 1 ) as likes,  (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = -1 ) as dislikes , 0 as myVote  FROM videos as v LEFT JOIN categories c ON categories_id = c.id LEFT JOIN users u ON v.users_id = u.id LEFT JOIN videos nv ON v.next_videos_id = nv.id  WHERE 1=1  AND  (SELECT count(id) FROM videos_group_view as gv WHERE gv.videos_id = v.id ) = 0  AND v.status IN ('a','xmp4','xwebm','xmp3','xogg') AND v.users_id =   AND v.clean_title = 'test-qual-1'  LIMIT 1
[/code]

Following this guide: https://tutorials.youphptube.com/video/how-to-translate-youphptube-to-another-language

nothing appears in the "array" column.

Youphptube version is 6.3 and Mariadb server is: 10.0.37

**Comment by DanielnetoDotCom** [comment]
Hi, this tutorial is obsolete, for now, you need to directly edit the file
