### ISSUE TITLE
How to Download  embed video 

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#1359]
Hi,

I have embed YouTube video links in my website but if try to download I can not download

**Comment by DanielnetoDotCom** [comment]
It is not possible to download , also if the download link is appearing it is not correct , it will be removed

**Comment by gujarraju** [comment]
Dear please check below link.

https://blog.usejournal.com/how-to-download-youtube-videos-in-python-a48701e70389
