### ISSUE TITLE
Traduzir 

### ISSUE THREAD

**Issue by PlayxPE** [DanielnetoDotCom/YouPHPTube#136]
Onde esta localizada a pasta que posso esta traduzindo as seguintes mensagens para o pt_br

Showing 0 to 0 of 0 entries

No results Found

**Comment by DanielnetoDotCom** [comment]
Este texto faz parte do bootgrid, se nao me engano la tem já os textos traduzidos, por tanto tem que mudar algum código para ele pegar estes textos

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
