### ISSUE TITLE
Exploring YouPHPTube on personal or user video's

### ISSUE THREAD

**Issue by TLCReuver** [DanielnetoDotCom/YouPHPTube#1360]
Hi Daniel,

The command https://demo.youphptube.com//info?modified=2015-01-02 users can see a list of video's that are hidden or for personal usage. Is there a way to block this ?

I mean, if you find http://demo.youphptube.video/videos/_YPTuniqid_5bf459cd2a28c4.35344266_thumbsSmallV2.jpg you can change it to *.mp4 etc. (mostly resulting in token_error) but still have access to the pictures.

Best Regards, Theo

**Comment by DanielnetoDotCom** [comment]
I see, images you probably will still have access, but the videos you will not be able to access if you properly block it.

for now I can not remove this feature

**Comment by DanielnetoDotCom** [comment]
Yes you can catch this on .htaccess
