### ISSUE TITLE
i can't upload any videos after enable plugins 

### ISSUE THREAD

**Issue by thushy07** [DanielnetoDotCom/YouPHPTube#1362]
just enable few Plugins after that i can't even update anything like under script code or even upload any videos , If it's plugin issue how can i revert them back or disable the plugin. Looks like Mysql got some issues? i added the log file too. Please help me

[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2730933/youphptube.log)
![error](https://user-images.githubusercontent.com/44659184/50742326-54cef180-11d7-11e9-9d7d-5ef495ad454f.jpg)

**Comment by thushy07** [comment]
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2733522/youphptube.log)


just added the log file, it's say something about the plugins, i think not too sure. i am not expert on this

**Comment by DanielnetoDotCom** [comment]
I can see this in your log file 

`[sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'youPHPTube.ip2location_db3' doesn't exist<br>`

make sure you install the user location table

![image](https://user-images.githubusercontent.com/18009293/50832683-b2755200-132d-11e9-932a-7e552157e838.png)
