### ISSUE TITLE
Video Resolution Switcher Plugin Error

### ISSUE THREAD

**Issue by RedTapeTV** [DanielnetoDotCom/YouPHPTube#1363]
I bought the Video Resolution Switcher plugin but am getting the following error in the logs when trying to play a video. The button is not showing on the video. 

[06-Jan-2019 23:45:50 UTC] PHP Notice:  Undefined index: fileName in /var/www/html/YouPHPTube/plugin/VideoResolutionSwitcher/VideoResolutionSwitcher.php(14) : eval()'d code(1) : eval()'d code on line 42

**Comment by DanielnetoDotCom** [comment]
Hi

Do you have the latest Youphptube files? Version 6.4?

**Comment by RedTapeTV** [comment]
Correct everything is up to date. 
<img width="434" alt="screen shot 2019-01-06 at 6 59 30 pm" src="https://user-images.githubusercontent.com/45922853/50743393-4daee000-11e5-11e9-938b-409459d5dc1e.png">

**Comment by DanielnetoDotCom** [comment]
When did you download the plug-in?

**Comment by RedTapeTV** [comment]
I got the issue resolved by deleting the plugin then re-uploading it. Not sure what the issue was but working now. Thanks for your help!
