### ISSUE TITLE
Audio playback view count not working

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [DanielnetoDotCom/YouPHPTube#1366]
The audio playback works but the view count does not increase when an audio file has been listened to.

**Comment by DanielnetoDotCom** [comment]
Try to uncheck the wavesurfer

![image](https://user-images.githubusercontent.com/18009293/50833591-742d6200-1330-11e9-89f6-b2e33fefd180.png)

It is crashing for some reason, we are trying to find the problem
