### ISSUE TITLE
Tip: Fast start MP4

### ISSUE THREAD

**Issue by TLCReuver** [DanielnetoDotCom/YouPHPTube#1368]
I noticed that some *.mp4 are not direct streaming so  they are waiting for a few seconds showing the content.

I found "MP4 Faststart" utility (freeware) that modify my *.mp4 files  for web-streaming on:
http://www.datagoround.com/lab/

"MP4 FastStart fixes the files so they can be streamed. It adjusts the MP4's metadata to allow for Flash players to play them right away (Fast Start), while it progressively downloads"

Best regards, Theo

[mp4_FastStart.zip](https://github.com/DanielnetoDotCom/YouPHPTube/files/2735738/mp4_FastStart.zip)

**Comment by DanielnetoDotCom** [comment]
we have a faststart set on the FFMPEG command, so if you encode the file, it should start fast.

if you direct upload we have no control
