### ISSUE TITLE
Tip: Using Tags

### ISSUE THREAD

**Issue by TLCReuver** [DanielnetoDotCom/YouPHPTube#1369]
At de bottomline I add by every video a tag line with tags starting with # like:

Tags: #Footbal, #Sport, #Something, #Holland

When i search for a tag i place it in the searchbar and it is really fast (tested with 700 video's).

Best Regards, Theo

**Comment by DanielnetoDotCom** [comment]
Thanks, we should add a tag support on youphptube soon
