### ISSUE TITLE
I try many times to run the program, but failed, please me .

### ISSUE THREAD

**Issue by xuelainiao** [DanielnetoDotCom/YouPHPTube#137]
I use lnmp and lnmpa lamp from lnmp.org to try this program ,but failed...
could u private one environment that can run it good . 
thanks~~~

**Comment by DanielnetoDotCom** [comment]
YouPHPTube was first designed to run in a private environment and also works on a public one.

**Comment by xuelainiao** [comment]
ok~ thanks~~~

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
