### ISSUE TITLE
Better View LiveLinks

### ISSUE THREAD

**Issue by Andiweb87** [DanielnetoDotCom/YouPHPTube#1370]
Its possible to change the view of Live Links in main page ??? because if i add more then 10 livelinks in same time the img generated from this livelinks also with the images from video embedet or uploadet in main page, take to much time to download all those images in same time, i was thinking some options to solve this,if possible to change....  thank you

**Comment by DanielnetoDotCom** [comment]
try to disable the gifs

![image](https://user-images.githubusercontent.com/18009293/50869013-05342580-1391-11e9-95b1-6ee1d5dbe93e.png)

**Comment by Andiweb87** [comment]
better , thanks Daniel , also nice the youtube style you have added but is possible to make also the video view like youtube https://www.youtube.com/watch?v=B1Vs2IwxaK8 , i mean with option to se the video like youtube or like the original, and about mobile whe open the new style youtube all the screen is closed with the menu in the left.

**Comment by DanielnetoDotCom** [comment]
can you please screenshot what are you talking about for me?
