### ISSUE TITLE
OBS failed to connect to server 

### ISSUE THREAD

**Issue by angelognanamuthu** [DanielnetoDotCom/YouPHPTube#1371]
Hello, I have an active site, and I am having trouble in live streaming. I installed the server and followed all the steps. But I am getting this error in OBS if I hit start streaming: Failed to connect to the server.
The connection timed out. Make sure you've configured a valid streaming service, and no firewall is blocking the connection. 
![obs error](https://user-images.githubusercontent.com/38923573/50925350-ba112580-1417-11e9-886a-30e4f8f01baa.jpg)

**Comment by DanielnetoDotCom** [comment]
can you make a telnet to the port 1935 for RTMP connection?

are you sure your NGINX is running?

**Comment by angelognanamuthu** [comment]
How do I check if my NGINX is running?

**Comment by Ishi-k2** [comment]
terminal: ps aux

**Comment by angelognanamuthu** [comment]
how do I make a telnet to the port 1935 for RTMP connection?

**Comment by Ishi-k2** [comment]
start up nginx:  
cd /usr/local/nginx/sbin/
./nginx

**Comment by angelognanamuthu** [comment]
Do I do that in the ssh terminal?

**Comment by Ishi-k2** [comment]
yes

**Comment by angelognanamuthu** [comment]
Do you know how to make a telnet to the port 1935 for RTMP connection

**Comment by Ishi-k2** [comment]
i dont know how to use telnet maybe Daniel know

**Comment by angelognanamuthu** [comment]
ok I used the command you gave and it said could not open the file permission denied.

**Comment by angelognanamuthu** [comment]
what does that mean?

**Comment by Ishi-k2** [comment]
do you have Steam ? It's easy to text chat on steam

**Comment by angelognanamuthu** [comment]
no I do not

**Comment by Ishi-k2** [comment]
now thats hard. it looks like you dont have Super user or root access to the server

**Comment by angelognanamuthu** [comment]
Ohh so what do I need to do? Can you help me, please?

**Comment by Ishi-k2** [comment]
you have vps with root access ?

**Comment by angelognanamuthu** [comment]
I used AWS EC2 instance as my server.

**Comment by Ishi-k2** [comment]
I use this Ubuntu-16.04-x86_64 server. You need to reinstall the server to Ubuntu-16.04-x86_64

**Comment by angelognanamuthu** [comment]
yes I have that as my server.

**Comment by Ishi-k2** [comment]
I will upload some file to you via mediafire

**Comment by angelognanamuthu** [comment]
Yes sure my name is angelosamuel1999

**Comment by Ishi-k2** [comment]
http://www.mediafire.com/file/vys1rppyyfuzyi8/youphptube.zip/file

**Comment by angelognanamuthu** [comment]
do I upload this to my terminal?

**Comment by Ishi-k2** [comment]
no. unzip it to  your deaktop and read

**Comment by DanielnetoDotCom** [comment]
For AWS EC2 you must make sure the port is open.

to make a telnet, you should be able to find instructions on google.

make sure you will make a telnet from your PC to the server 

telnet [yourServerIP] [port]

Something like that:

`telnet 123.123.123.123 1982`

**Comment by angelognanamuthu** [comment]
So do you know anyone who is using your code for their website and it's active?

**Comment by Ishi-k2** [comment]
I don't know if some other is using my nginx.conf
I format my ubuntu twice yesterday.Youphptube installed twice too and my conf working just fine all the time.

**Comment by angelognanamuthu** [comment]
Hey so I opened port 1935 in AWS EC2 instance, and I can connect to the server and OBS is streaming. But I am not getting any output in the site. When I tried to connect the telnet to port 1935, I am getting a message stating "Connection closed by foreign host." What does this mean? Could you kindly help me, please?

**Comment by Ishi-k2** [comment]
Set on obs Setting/Output rescale output: 640x360, rate control: cbr

**Comment by DanielnetoDotCom** [comment]
@angelognanamuthu you may find something on your javascript log

**Comment by angelognanamuthu** [comment]
Hey so what do you mean by javascript log?

**Comment by DanielnetoDotCom** [comment]
@angelognanamuthu try to look your browser console.

try to google how to do that

**Comment by angelognanamuthu** [comment]
So this is what my javascript log is showing? Can you please help me.  
![e](https://user-images.githubusercontent.com/38923573/52528189-bc2c0580-2c9d-11e9-91cc-3d703c8b5677.jpg)

**Comment by angelognanamuthu** [comment]
this is the browser console 
![e2](https://user-images.githubusercontent.com/38923573/52528308-3447fa80-2ca1-11e9-8045-dc26cccd5525.jpg)
