### ISSUE TITLE
GIFs are blurry

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1374]
![image](https://user-images.githubusercontent.com/14828766/50994903-7c7dcc80-14eb-11e9-8f7c-1266b7e5e11f.png)

**Comment by DanielnetoDotCom** [comment]
I see gifs are in lower resolution than the jpeg.

We will do our best to make a good quality

**Comment by Puyodead1** [comment]
Thank you
