### ISSUE TITLE
Can't edit Analytics code

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1375]
![image](https://user-images.githubusercontent.com/14828766/51001815-46e2de80-14ff-11e9-93b6-9c174ffe6037.png)

**Comment by Puyodead1** [comment]
Temp solved by removing `style="display: none !important;"` from html in inspect element

**Comment by DanielnetoDotCom** [comment]
This is not happening on my side

![image](https://user-images.githubusercontent.com/18009293/51032339-679e4900-157e-11e9-80b3-1c7edaebb3cf.png)

**Comment by Puyodead1** [comment]
It might be the theme
