### ISSUE TITLE
Ads not showing

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1376]
![image](https://user-images.githubusercontent.com/14828766/51002975-ff5e5180-1502-11e9-898c-c56bf8989ef5.png)
![image](https://user-images.githubusercontent.com/14828766/51002981-02594200-1503-11e9-9ff6-3e2fa66a5a52.png)

**Comment by DanielnetoDotCom** [comment]
Please provide more details of where are you testing

if you are locally this error is expected due the CORS rules

**Comment by Puyodead1** [comment]
its on my VPS
http://server2.puyodead1-development.me:83
