### ISSUE TITLE
All links  is not linked to targets.

### ISSUE THREAD

**Issue by silentltu** [DanielnetoDotCom/YouPHPTube#1377]
Hello, so i decided to try YouPHPTube, and after installation found that cannot even login, becouse link is broken. for example it tagging to "lochalhost/user" but real location is: "localhost/view/user.php"
is it buggy index and menu? or my installation corupted?

**Comment by DanielnetoDotCom** [comment]
You should use mod_rewrite and the  "lochalhost/user" is the right path
