### ISSUE TITLE
Report a problem to the YouTube plugin ...

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#1379]
I wanted to report a problem to the YouTube plugin (last on the list of plugins) ...
`YouTube (YouTube) Version: @1.0free firstPage YouTube | Make the first page works as a YouTube`

It seems very annoying to me that every time I click on each movie the YouTube menu should appear from the left. Not even at the site of Youtube, this menu does not come out in this way.
I suggest to make sure that it is closed by default ... or at least put in the settings of this plug the possibility to be closed by default ...
Thank you.

**Comment by DanielnetoDotCom** [comment]
I agree, I will try to find a solution

**Comment by tgd1973** [comment]
This update seems to solve the problem.
If there are any other problems related to this plug, I will write here.
For now, thank you.

**Comment by tgd1973** [comment]
I write again and thank you for the good work ....
 If you can improve, you should be able to create the possibility that if the menu on the left,  choose to keep it open, stay open, even while browsing the site ... that memorize in a way, maybe with the cooke, if want to keep it closed ... that it stays closed ...

Another thing:  if want to imitate Youtube ... just on Trending menu ... you have to keep it open ... How can you keep it open only for Trending?
Thank you.

**Comment by Andiweb87** [comment]
Add live link and Live buttons are missing in the youtube skin

**Comment by tgd1973** [comment]
Everything is fine with my YouTube plug there are no problems with the buttons ... indeed changing the color, now the bar seems a cross between Youtube and FB style ... only if there was the possibility of making it narrower in width.

![example](https://user-images.githubusercontent.com/15127860/51084098-f51b9d80-1724-11e9-8dda-301ebc911da4.jpg)
