### ISSUE TITLE
Online but The media could not be loaded

### ISSUE THREAD

**Issue by Ishi-k2** [DanielnetoDotCom/YouPHPTube#1380]
The media could not be loaded, either because the server or network failed or because the format is not supported.
<a href="https://imgur.com/KTMTGcL"><img src="https://i.imgur.com/KTMTGcL.png" title="source: imgur.com" /></a>

Where is the log file. I'm kinda noob

**Comment by DanielnetoDotCom** [comment]
I guess you are mixing https and http, make sure apache and ningx use the same protocol (NOT MIX)

**Comment by Ishi-k2** [comment]
I use your nginx.conf but i should remove https on apaches conf ?

**Comment by Ishi-k2** [comment]
Is this normal ?

<a href="https://imgur.com/xD6Yx9M"><img src="https://i.imgur.com/xD6Yx9M.png" title="source: imgur.com" /></a>
