### ISSUE TITLE
LiveChat ws 403

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#1381]
I have my server setup to 403 everything except things i allow, i am getting a 403 error with the websocket
![image](https://user-images.githubusercontent.com/14828766/51037898-98cb4900-157f-11e9-95f0-6709ddf87629.png)

**Comment by DanielnetoDotCom** [comment]
if you are on a https make sure you follow this 

Edit your proxy

`sudo nano /etc/apache2/mods-available/proxy.conf`

Add this line

```
<IfModule mod_proxy.c>
        ProxyPass /wss/ ws://127.0.0.1:8888/
</IfModule>
```

and enable the module

`sudo a2enmod proxy_wstunnel && sudo /etc/init.d/apache2 restart`


On the LiveChat plugin configuration

 {"websocket":"wss://[yourServer]/wss/"}

also make sure the chat is running 

`nohup php /var/www/html/YouPHPTube/plugin/LiveChat/chat-server.php &`

**Comment by MPTMG** [comment]
If you are having problems with your integration I built a TurnkeyLinux appliance  that has been accepted and published at https://www.turnkeylinux.org/.  It can be deployed easily with fully functioning live stream, live chat, and encoder (once you enable the features in YouPHPTube).

https://www.turnkeylinux.org/youphptube

Although DanielnetoDotCom provides excellent instructions this might save you some config hassles.

**Comment by Puyodead1** [comment]
@MPTMG Thanks but i have had this working, I only transfered servers. @DanielnetoDotCom I am not on https but i might just go back to https because it was working that way :/
