### ISSUE TITLE
livestream is on, but not listed on website

### ISSUE THREAD

**Issue by gryjump** [DanielnetoDotCom/YouPHPTube#1382]
hello, any idea?
 
installed youphptube with encoder on a fresh Ubuntu 18.04.
tube and encoder work, no problems - great.

i start my livestream, conneting and i see stream here:
http://***.***.***.***/YouPHPTube/plugin/Live/?c=************

also RTMP stats work
http://***.***.***.***:8080/stat

Generated by nginx-rtmp-module 1.1.4, nginx 1.14.1, pid 1229, built Jan 11 2019 10:24:46 gcc 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04) 

my problem:
http://***.***.***.***/YouPHPTube/
"there is no streaming now"

my running lievstream is not on my portal webseite available.

do you know, what i forget? 
i just followed your tutorial and there were no errormassages while install

greetings
michael

**Comment by gryjump** [comment]
sure, "Listed Transmition" on ....plugin/Live/ is turned on

**Comment by DanielnetoDotCom** [comment]
How your stats page looks like?

check the demo stats https://youphptube.com:444/stat

the Livestream name is important to be the Key. for some reason, some installations are not. I do not know what users did differently to get it

![image](https://user-images.githubusercontent.com/18009293/51073480-2c6c4a80-1650-11e9-9c0c-117a18278019.png)

**Comment by gryjump** [comment]
hi,
stats do not sho the stream, but it counts bytes on every refrech of the page.
stream is running and embeded code on another site works fine

**Comment by gryjump** [comment]
my stat is
*****:8080/stat
maybe a port problem, but i do not know where to seek

**Comment by gryjump** [comment]
/usr/local/nginx/conf/nginx.conf

   worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://*.*.*.*/YouPHPTube/plugin/Live/on_publish.php;
                            on_play http://*.*.*.*/YouPHPTube/plugin/Live/on_play.php;
                            on_record_done http://*.*.*.*/YouPHPTube/plugin/Live/on_record_done.php;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }   
            }
}
rtmp {
    server {
         listen 9080;
         chunk_size 4096;

         application live {
                 live on;
                 record off;                    
                 on_publish http://*.*.*.*/YouPHPTube/Live/on_publish.php;
         }
    }
 }

**Comment by DanielnetoDotCom** [comment]
but how does your stats page look like?

**Comment by gryjump** [comment]
![php1](https://user-images.githubusercontent.com/46596625/51075400-2778bc80-168b-11e9-9e4e-4f2f9953e057.jpg)

**Comment by DanielnetoDotCom** [comment]
you have no stream listed there, you must have something.

I cant help you to fix it, maybe you can find help on it on the NGINX RTMP repository 
https://github.com/arut/nginx-rtmp-module

**Comment by gryjump** [comment]
stream is running, but not listed, that´s the problem.
thanks a lot for your time, i think easiest was is a complete new installation trying to avoid this error.
i will start a complete new server with your tutorials.

greetings
michael

**Comment by DanielnetoDotCom** [comment]
I just fix a very similar problem on a costumer.

the problem was because he added a redirect rule on .htaccess, so he redirects everything to his www URL.

After removing the redirect rule it starts to work perfectly
