### ISSUE TITLE
Suggestion about LiveLinks

### ISSUE THREAD

**Issue by Andiweb87** [DanielnetoDotCom/YouPHPTube#1383]
Hi Daniel i have an suggestion about showing in the main page the livelinks video,

see the screenshot -- > https://snag.gy/jvRx3g.jpg

i think is better make with something like tabs to show the livelinks videos in main page this for 2 reasons : 

1) Save to much time to download all the images generated from the livelinks (if we put more than 20 livelinks in same time, and images from videos uploaded or embeded.
2) It will make an diference from images livelinks and video embedet or uploaded show in the main page.

also an countdown timer when the event starts like in the screenshot.

thank you

**Comment by DanielnetoDotCom** [comment]
Agree, maybe a version without images

**Comment by Andiweb87** [comment]
yes , will save also some space in the main page :)
