### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by PlayxPE** [DanielnetoDotCom/YouPHPTube#139]
Meu site está com bugs , não aparece o autoplay nem area de comentários quando esta logado , ja quando nao esta logado mostra o autoplay e para fazer login para comentar 

Esta asim por que o  Mod Rewrite Não esta ativado?

Site:alexs123.5gbfree.com

Faca uma conta e veja voce mesmo

**Comment by DanielnetoDotCom** [comment]
Muito estranho, mas acessei seu site e você tem apenas um video, logo o autoplay nem deve aparecer mesmo.
Quanto aos comentários, este é só para quem está logado mesmo.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
