### ISSUE TITLE
push stream to social media

### ISSUE THREAD

**Issue by lamadya** [DanielnetoDotCom/YouPHPTube#1391]
hi 
i want to push my stream to social media like facebook youtube or custom rtmp
without edit  config file nginx.conf to add push  because I dont need to restart my nginx 
So that the rest of my sites do not stop
thank you for any one help me

**Comment by DanielnetoDotCom** [comment]
Sorry, but the only way I know is editing the nginx.conf

you can also try to do it using the FFMPEG command on your terminal
