### ISSUE TITLE
issue about TheaterButton plugin

### ISSUE THREAD

**Issue by Andiweb87** [DanielnetoDotCom/YouPHPTube#1394]
Hi Daniel , this is an old request :) , but i see you have added it in the video bar only , can you please add an option also to see the video like this ??

https://snag.gy/Xom4vd.jpg

thank you

**Comment by Andiweb87** [comment]
sorry i see , you have addet it before TheaterButton (TheaterButton)

**Comment by Andiweb87** [comment]
https://www.goalgoal24.com/video/manchester-city-3-0-wolverhampton-wanderers 

i dont know ,what is the problem for the space created under the video

**Comment by Andiweb87** [comment]
i think is an issue , https://snag.gy/OPAShX.jpg

**Comment by Andiweb87** [comment]
is possible to fix it ??

**Comment by Andiweb87** [comment]
just tested in demo site , still same issue 

https://snag.gy/Xr5hsf.jpg

**Comment by DanielnetoDotCom** [comment]
demo site is not updated yet, I will update it soon

**Comment by Andiweb87** [comment]
understand , i will update me files now , and i will tell you

**Comment by Andiweb87** [comment]
thank you

**Comment by Andiweb87** [comment]
same Daniel, i have just updatet the files

**Comment by DanielnetoDotCom** [comment]
I guess it is fixed now
