### ISSUE TITLE
Cannot start live stream

### ISSUE THREAD

**Issue by darthdaniel16** [DanielnetoDotCom/YouPHPTube#1396]
Hi,

I recently got YouPHPTube running from the YouPHPTube virtualbox vdi. I build and configured nginx (confirmed its running when I check the stats URL) but when I click the "LIVE" button, the status says "offline" and the player is either stuck with a loading animation or says "The media could not be loaded, either because the server or network failed or because the format is not supported"

My button parameters are:

{"button_title":"LIVE","server":"rtmp://192.168.43.140/live","playerServer":"http://192.168.43.140:80/live","stats":"http://192.168.43.140:8080/stat","disableGifThumbs":false,"useLowResolution":false,"experimentalWebcam":false}

And my nginx conf rtmp settings are:

rtmp {
    server {
         listen 1935;
         chunk_size 4096;

         application live {
                 live on;
                 record off;                    
                 on_publish http://192.168.43.140/YouPHPTube/plugin/Live/on_publish.php;
         }
    }
 }

![tube](https://user-images.githubusercontent.com/16773933/51242397-ee915e00-1990-11e9-9584-d917d4a95413.png)

**Comment by Puyodead1** [comment]
Are you streaming anything? you have to be steaming something for it to work...

**Comment by darthdaniel16** [comment]
> Are you streaming anything? you have to be steaming something for it to work...

No. Havent managed to stream anything yet

**Comment by DanielnetoDotCom** [comment]
please check here https://github.com/DanielnetoDotCom/YouPHPTube/issues/1107

**Comment by darthdaniel16** [comment]
hi @DanielnetoDotCom ,thanks for the response. I am currently setting up SSL for nginx then will edit nginx conf file and retry

**Comment by darthdaniel16** [comment]
Hi@DanielnetDotCom, I have confirmed that the connection is established between nginx and YouPHPTube. With OBS, when i start a stream the "live" notification  is updated (offline to online, etc) and the image changes from "Offline" to "On Air" no video feed is coming through

**Comment by darthdaniel16** [comment]
Sorted it out. There was an error in my nginx conf file
