### ISSUE TITLE
Some videos not playing and give an error

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [DanielnetoDotCom/YouPHPTube#1398]
Some videos on the site (many across the entire site) are not playing at all and just give an error. Some play a few seconds and freeze with this error.

A perfect example is a brand new video on the homepage: https://www.diytube.video/v/8041

It plays a few seconds and gives the error then freezes.

Attached is a screen shot.

**Comment by The-Do-It-Yourself-World** [comment]
![video-play-error](https://user-images.githubusercontent.com/45924889/51275978-6c5d6580-19a1-11e9-962d-a3b0b1f25866.jpg)

**Comment by Puyodead1** [comment]
Check logs

**Comment by The-Do-It-Yourself-World** [comment]
I cannot access the logs since Daniel updates our site and has changed the ownership of many files. I cannot even see them.

**Comment by DanielnetoDotCom** [comment]
@The-Do-It-Yourself-World you should be able to access the log if you access it with your SSH credentials

I can see, the error you mention. I could not find the cause. I still think what may it be. I guess is something related to the video file/encoder

If someone else has an idea what may it be I will appreciate

**Comment by SubjectXXX** [comment]
Interesting enough, I got this error on first upload:
[31-Jan-2019 12:11:54 UTC] [aEC] JS-Err: TypeError: player is undefined @ line 594 in file http://212.235.181.172/video/uvod-v-pravo-socialne-varnosti-grega-strban at visit on /video/uvod-v-pravo-socialne-varnosti-grega-strban
[31-Jan-2019 13:41:50 UTC] [aEC] JS-Err: TypeError: player is undefined @ line 472 in file http://212.235.181.172/video/zdravstveno-zavarovanje-grega-strban at visit on /video/zdravstveno-zavarovanje-grega-strban

for only this two clips that are erroring, not getting same error on reuploading them..

**Comment by SubjectXXX** [comment]
Also, if you check the preview gif from these two videos, they are some vanguard thinfoil cap shit.. Is this some default gif?

**Comment by DanielnetoDotCom** [comment]
If you are direct upload the video you probably have a wrong codec

**Comment by SubjectXXX** [comment]
I once found a settings page where you could fine tune ffmpeg commands for encoding for different formats and qualities... Where can I find that page?

**Comment by SubjectXXX** [comment]
I did everything the same with all 7 movies, only 2 turned out defective..

All 7 original videos are encoded with same codecs, on same machine in same (handbrake) queue. Queue order when encoding here doesnt matter. One out of two videos was encoded 4th in the queue, one last in the queue..

**Comment by SubjectXXX** [comment]
After reuploading/re-encoding both video clips couple of times (6 times to be exact), I managed to get them working properly.

Not sure why tho..

**Comment by DanielnetoDotCom** [comment]
you can try to manually make a ffmpeg command to see the output, and if it will works.

the commands can be founded here

![image](https://user-images.githubusercontent.com/18009293/52118114-3b616f80-25f4-11e9-862c-eb0587229859.png)

also I am not sure why it happends

**Comment by SubjectXXX** [comment]
AHA, this is the view I'm looking for. I dont have tabs Configurations, Update and Streamers when I open encoder..

I git pulled both encoder and streamer freshly.

Is there some setting?
I'm logged in with admin..

**Comment by DanielnetoDotCom** [comment]
check on the encoder database -> streamer table

there is one column "isAdmin"

**Comment by SubjectXXX** [comment]
Yes, it was set to 0. 

I corrected it, thank you.

Now will try to fiddle with ffmpeg settings, maybe I can find a culprit there somewhere..

**Comment by The-Do-It-Yourself-World** [comment]
If you figure it out, please let me know. I have thousands of corrupt videos on my site now. I dont understand the ffmpeg stuff so I would not have any idea how to try it out myself.

**Comment by SubjectXXX** [comment]
You gonna have to reencode them in any case, even if I manage to figure it out what went wrong.

If you have access to original files, then just try to reencode them straight away, dont wait for me. It just takes a couple of tries. 

If you dont have originals, then your thousands are lost anyway..

**Comment by The-Do-It-Yourself-World** [comment]
Its a problem for me because many people are uploading themselves. I can fix my own but not for others. But I sure hope you find the problem.

**Comment by SubjectXXX** [comment]
I totally understand, thats why I'm testing my system so much and reporting so many error or looking for answers before I put the installation into production..

**Comment by SubjectXXX** [comment]
Interesting: my coworker had same problems with videos that I already reencoded and were working for me..
