### ISSUE TITLE
Only one video

### ISSUE THREAD

**Issue by Knah-Tsaeb** [DanielnetoDotCom/YouPHPTube#14]
Hi, when i upload a video, YouPHPTube keep original file, encode file in MP4 and WEBM. For each file i have 3 files.

I don't want original and mp4 version of video. I just want a WEBM version.
Have you a proper solution for me.

I just start play with YouPHPTube, it's very good app, congratulation !!!
The look and feel are pretty good, i have a lot of suggestion for you 😄

**Comment by DanielnetoDotCom** [comment]
Thanks i am happy you like it.
You can delete the original file but you will need the mp4 video file for browser compatibility

![image](https://cloud.githubusercontent.com/assets/18009293/26111944/e916683e-3a2c-11e7-98fb-55f898f379ba.png)

**Comment by Knah-Tsaeb** [comment]
Huuummmm, not really satisfaction solution. I need to be automatic, if for each video upload, i need delete manually file, it' made me crazy 😄.

For compatibility with browser not supporting webm, is not my problem, is our. Of course is not really true, but i prefer share in webm, is my preference.

For be honest with you, a few year ago a make a app (https://sovigall.knah-tsaeb.org)  for copy video from other source (via youtube-dl) for save, backup and share  video. But is very ugly (code and visual). When i look YouPHPTube, i think is better than my homemade tools. And if your app can have same function like mine, i directly replace my apps by your. I have no time for remake my app from scratch, or contribute at your. That's reason for all my demand.

Have a nice day.

**Comment by DanielnetoDotCom** [comment]
I will work for the next release put an option to choose the encode format.

**Comment by DanielnetoDotCom** [comment]
Now there is an option to choose what file you want to encode

![image](https://cloud.githubusercontent.com/assets/18009293/26697575/ee9ed6f6-46e8-11e7-8944-96f91ef49c59.png)

**Comment by DanielnetoDotCom** [comment]
This is regarding an old version (before encoder), this page does not exists anymore.

what you looking for should be on encoder page.
