### ISSUE TITLE
user signup

### ISSUE THREAD

**Issue by gryjump** [DanielnetoDotCom/YouPHPTube#1400]
if a new user wants to SignUp, there is no "E-Mail" Tab? so, he would never get a verification mail.

on "send" error appears "Must Fill out all fields"
but there is no more (email) field to fill

on your demo, a user can`t Signup, too (without socialnetwork)

maybe i am blind, but i find no way to activate the registration and there is no "disallow" activated.

can you give me a hint?

many thanks
michael

**Comment by DanielnetoDotCom** [comment]
I sent a fix, can you please check

**Comment by gryjump** [comment]
Works!
fantastic, thanks

many thanks
michael

**Comment by gryjump** [comment]
but now another problem which was not there yesterday:
no save button anymore to save uploaded avatar or headerpicture of a user on profile-page.

michael

**Comment by DanielnetoDotCom** [comment]
check your log file, your script should be crashing somewhere

**Comment by gryjump** [comment]
hi daniel,
ich had a look to the sourcecode in my browser at http://my-domain/user
it broke with an error at tables of plugin User_Location

i installed User_Location and activated it.

save bar is know visible and works.

thanks again

but again my question:
i did not found 2 basically community-functions:
1. Admin should be able to delete unwanted user (and there contents)
2. a user should be able to delete his own account

maybe this could be good features in future?

have a nice day
michael

**Comment by DanielnetoDotCom** [comment]
you can not delete any user, regarding the database relation, but you can inactivate an account.

you right, In the future I will improve the code to let users inactivate them selfs.
