### ISSUE TITLE
Going to link after logging in...

### ISSUE THREAD

**Issue by JSY-Ben** [DanielnetoDotCom/YouPHPTube#1402]
Not really a major issue, just more of a feature request.

I send out a lot of links to videos on our youphptube, but i have it set to require login before you can even see the videos. But once you've logged in, it forgets the link and goes straight to the homepage. Is there an easy way to fix that so that after login it goes to the original clicked on link.

Thanks again for your work :)

**Comment by DanielnetoDotCom** [comment]
Hi

sorry, I did not understand what was the problem, can you please detail a bit more and get some screenshots

**Comment by JSY-Ben** [comment]
Of course :)

If i send out a link to one of our videos via email or whatever, say for example this:

https://media.highlands.ac.uk/hightube/video/collaborative-project-pitch-18th-january-2019-team-goose

If i'm logged in, the link works of course. But because i have this setting ticked in CustomizeAdvanced

<img width="200" alt="screenshot 2019-01-19 at 13 38 07" src="https://user-images.githubusercontent.com/13555701/51427403-9efc9d80-1bef-11e9-9a56-191ab030ccb0.png">

(Which is deliberate, as we don't want anyone without a login to see the videos)

If i click on that link when not logged in, it will ask to login of course

<img width="613" alt="screenshot 2019-01-19 at 13 40 10" src="https://user-images.githubusercontent.com/13555701/51427419-c3587a00-1bef-11e9-9fb3-1cd640da392a.png">

When I log in, instead of going to the video i originally clicked on, it goes straight to the Gallery homepage. So to get to the video, i have to click on the link again.

This is not a BIG problem, but i get a lot of user feedback saying the link i sent them doesn't work because of this.

If it helps, our login uses the LDAP Plugin to login, the standard login and registration is turned off.

Many thanks :)

**Comment by DanielnetoDotCom** [comment]
I see, thanks, I will investigate

**Comment by jeanfrancoisvarin** [comment]
I have the same needs as I wish to send direct links to videos to my friends without them to need authentication.

**Comment by DanielnetoDotCom** [comment]
@jeanfrancoisvarin you can use unlisted videos 

![image](https://user-images.githubusercontent.com/18009293/51597946-3eb17880-1edb-11e9-94fd-f6c42eb38339.png)
