### ISSUE TITLE
server streaming and rtmp on separate servers

### ISSUE THREAD

**Issue by luciomor** [DanielnetoDotCom/YouPHPTube#1403]
I've installed youphptube on one server and rtmp on another. the obs sends the streaming and I can watch through the link in vlc normally, but the youphptube does not receive the streaming, says that it is offline. on statistics is ok. what can I do?

**Comment by DanielnetoDotCom** [comment]
please check this https://github.com/DanielnetoDotCom/YouPHPTube/issues/1107

**Comment by luciomor** [comment]
Yes, I had seen this information before. I researched a lot before asking. In the same server runs everything right, more separating the stream does not show online nor the video appears.

**Comment by luciomor** [comment]
I will ask you another question, the encoder in the first installation I made was opening fast, I had to reinstall ubuntu and every system again, but now, the encoder takes to open, about 5 minutes. What can it be?

**Comment by DanielnetoDotCom** [comment]
yes, I am brazilian.

how your NGINX stats looks like? can you screenshot?

about your slowness, I don't know what is it.

**Comment by luciomor** [comment]
a estatística abre rápido, mais não sei o que há com o encoder muito lento. veja aí: encoder.megahd.com.br, site streaming normal veja: xflix.megahd.com.br

![stats](https://user-images.githubusercontent.com/39665478/51476706-726e9000-1d6d-11e9-8731-6d5b0afe4dc0.png)

**Comment by luciomor** [comment]
how to start nginx along with ubuntu? every time I reboot I have to activate it manually.

**Comment by DanielnetoDotCom** [comment]
Does your encoder is slow to start or to encode? if is to encode you should add more CPUs on your server.

about start with the system you should google for it.

but it should be on your crontab or init.d or something else

**Comment by luciomor** [comment]
the encoder is slow to start the page

**Comment by DanielnetoDotCom** [comment]
make sure your encoder can open/query external pages, can you ping www.youphptube.com from your encoder server?

**Comment by luciomor** [comment]
Yes, all right, respond. so much so that the streaming opens normal very fast, the problem is only in the site of the encoder that it takes to open. more after it opens works fine. nobody else will have the patience to wait about 2 minutes until the site responds.

**Comment by DanielnetoDotCom** [comment]
check your encoder log file for errors

**Comment by luciomor** [comment]
shows no error, just the same delay. Look:

[21-Jan-2019 15:03:59 America/Sao_Paulo] http://xflix.megahd.com.br/ == http://x                                                                                        flix.megahd.com.br/
[21-Jan-2019 15:05:59 America/Sao_Paulo] Verification Start http://xflix.megahd.com.br/
[21-Jan-2019 15:05:59 America/Sao_Paulo] Verification Creating the Cache http://xflix.megahd.com.br/
[21-Jan-2019 15:06:01 America/Sao_Paulo] Verification Response (https://search.youphptube.com/verify.php?url=http%3A%2F%2Fxflix.megahd.com.br%2F): {"msg":["Start","http:\/\/xflix.megahd.com.br\/ Site verified"],"verified":true,"status":"a"}

**Comment by DanielnetoDotCom** [comment]
ok, looks like it takes 2 min

are the encoder and streamer on the same server?

can you ping from encoder on the URL xflix.megahd.com.br ?

**Comment by luciomor** [comment]
yes, same server, yes I can ping

**Comment by luciomor** [comment]
problem of slow encoder to log in to the streamer resolved. The server was going through a proxy, I released the server's access pass through the proxy and the problem was resolved. I'm posting here, because it might serve someone in the future.

**Comment by DanielnetoDotCom** [comment]
thanks for the feedback
