### ISSUE TITLE
Not responsive enogh

### ISSUE THREAD

**Issue by chinli12** [DanielnetoDotCom/YouPHPTube#1406]
If the home page will have one video per row it will look nice and be able to compete with most other script
![screenshot_2018-06-15-05-10-16](https://user-images.githubusercontent.com/29612076/51427434-35cd5800-1bf8-11e9-87f9-d51963528d78.png)

**Comment by DanielnetoDotCom** [comment]
soon I will upload a update that you can choose how many cols do you want for each type of resolution 

![image](https://user-images.githubusercontent.com/18009293/51484113-73a5ba00-1d79-11e9-8136-9b1fb419fbc3.png)

**Comment by chinli12** [comment]
OK so it will look like the screenshot

**Comment by DanielnetoDotCom** [comment]
yes, it should looks like

**Comment by chinli12** [comment]
Like how long from now

**Comment by DanielnetoDotCom** [comment]
It is there 7 hours ago https://github.com/DanielnetoDotCom/YouPHPTube/commit/fe60a5a92c8f52a00b66c58c54fe8aefcd1abb1f

**Comment by chinli12** [comment]
How can I access it

**Comment by chinli12** [comment]
Have seen it your great you will be the best programmer in the world

**Comment by chinli12** [comment]
One more things if the description will have a button showmore it will have great impact

**Comment by DanielnetoDotCom** [comment]
maybe in the future, I will add this
