### ISSUE TITLE
Stop Livestream

### ISSUE THREAD

**Issue by mrtick2002** [DanielnetoDotCom/YouPHPTube#1407]
Ive got some dude spamming livestreams on my install. They have literally been going for over a week. Is there a way to limit the length of a livestream or to end them from the admin?

**Comment by DanielnetoDotCom** [comment]
sorry, the only way now to stop a stream is stopping the nginx server

**Comment by mrtick2002** [comment]
So is there a way to restart the nginx server to stop them? I mean like can I reboot it someway to turn them off I guess is what I'm asking.

**Comment by DanielnetoDotCom** [comment]
only on the terminal

should be `/usr/local/nginx/sbin/ningx -s stop`
