### ISSUE TITLE
"Cannot play, unknown media" on Smart TV

### ISSUE THREAD

**Issue by birdie60** [DanielnetoDotCom/YouPHPTube#1408]
I use an LG Smart TV with webOS. It has a built-in web browser that cannot be changed or upgraded. Until recently, I could navigate to my YouPHPTube server and play my video files just fine.

Since I upgraded to YouPHPTube Version 6.1, I always get error "Cannot play, unknown media" on the Smart TV, which is a nuisance.
On other browsers on my PC, all is working fine.

Could it be that v.6.1 changed the media player? Is it possible to revert to the older player?
Or what else could I try to do here?

**Comment by DanielnetoDotCom** [comment]
We didnt change anything.

you can try to disable all plugins to see if it works again

**Comment by birdie60** [comment]
I only had these three plugins enabled:

- CustomizeAdvanced (CustomizeAdvanced)
- Gallery (Gallery)
- MP4ThumbsAndGif (MP4ThumbsAndGif)

After disabling them all, I still get this error on the Smart TV (and only there):
"The media could not be loaded, either because the server or network failed or because the format is not supported."

I never had this error in earlier versions of YPT. Don't know what's going on.

**Comment by DanielnetoDotCom** [comment]
can be something on your server

**Comment by birdie60** [comment]
No, it is the YPT script. I just tested demo.youphptube.com on this Smart TV, and I get the same error!

Here is information from LG, the makers of my Smart TV. Do you see any red lights for YPT here, @DanielnetoDotCom?

> Your LG Smart TV browser is a fully functioning web browser that will work in a similar way to that of a web browser on a PC. With this being a TV based browser it does have its limitations.
> You will not be able to open certain websites. Due to the version of Flash Player that LG’s TVs have incorporated into their systems (Flash Lite) certain website formats will not be supported. For example, you will not be able to stream videos from certain sites, any Flash based games will not work, etc. The version of Flash player is not updatable due to it being placed on the boards upon manufacture.
> 
> You will also not be able to download software, pictures, videos or music off of websites; this is due to the hardware constraints within the TV. 
> 
> Only HTML5 media is supported & not Flash Plug-in.

**Comment by birdie60** [comment]
Another observation: The error only occurs on https sites. When I remove enforcement of https on my site, I can stream my videos on the Smart TV.

**Comment by Puyodead1** [comment]
Sounds like a server issue, check youphptube logs

**Comment by birdie60** [comment]
No, it is the YPT script for sure. I get the same error on Demo site https://demo.youphptube.com on my Smart TV. So its not my server config.
And I do not get this error with other sites, that are not YPT based.
It has something to do with content delivery or player on https.

**Comment by DanielnetoDotCom** [comment]
Hi, the videos are delivered directly from Apache, it is an HTML5 player (Browser native)

maybe your TV cannot handle HTML5 players over https

**Comment by DanielnetoDotCom** [comment]
FYI, there is no difference in the script for http and https, the code is exactly the same.

the only difference is the server protocol, maybe you can investigate the protocol signature

**Comment by birdie60** [comment]
I could not find misconfigurations on the YPT installation or script. And I could not find documentation about flaws in the Smart TV's browser.
So my work-around was to force http:// for my Smart TV in .htaccess, and https:// for all the other user agents. No more problems so far.
