### ISSUE TITLE
Support for getUserMedia to access device cameras directly

### ISSUE THREAD

**Issue by darthdaniel16** [DanielnetoDotCom/YouPHPTube#1409]
Hi,

I am trying to set up a streamer site where whether on desktop or mobile device, the device camera (webcam etc) is accessed directly/automatically and pushes the stream to media server when the "Play" is clicked. I am currently testing the getUserMedia library and wanted to know if you had heard of any successful implementations of getUserMedia with YouPHPTube?

**Comment by DanielnetoDotCom** [comment]
sorry, you are the first one I am hearing that is trying to use
