### ISSUE TITLE
Sorry! Unknown Error!

### ISSUE THREAD

**Issue by XxTWMLxX** [DanielnetoDotCom/YouPHPTube#1410]
I copied all the files to my apache2 webserver, Made the sql database and imported the .sql file. 
When I go to example.com it redirects to example.com/install. 

Then after I put in all details it says "Sorry! Unknown Error!" in a pop up box.

The database is reachable and able to login to it via terminal on the apache machine.
all the directories are owned by correct owners and have the right chmod permissions.

where are the log files I need to start diagnosing this?

**Comment by DanielnetoDotCom** [comment]
why didn't you use the installation script instead manually import?

to find errors: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by XxTWMLxX** [comment]
i choose the option that says i already imported, as i tried both create db/tables and just create tables. both didnt work so i dont think its a database issues, i used the sql file included with the youphptube installation to do the import.

**Comment by XxTWMLxX** [comment]
i got it to install, turns out to be how my nginx server was setup that is actually serving the content.
i have a proxy_pass on nginx to load the apache & youphptube from another VM to the main website/domain. it was serving parts and blocking others thus causing errors when youphptube tried to install as it thought it didnt have all needed files. 

and im doing it this was because it says it wont install on ngnix, and i dont feel like modifying youphptube to make it work on nginx. as i googled and some have done.

**Comment by zhenniqi** [comment]
Thanks

**Comment by zhenniqi** [comment]
I don't know but i still be unable to finish the installation, i do have nginx listening on port 443 and 80,but my apacha with php was listening on port 8010 and i don't they conflit with each other ,but still unknown error ...
