### ISSUE TITLE
Move video files to different location

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1413]
I cannot find any setting that controls where all the videos and mp3 and whatnot is stored.

My installation partition is too small for storing larger files, thus I attached network drive (Fiberchannel SAN, no performance issues!) to my virtual machine and mounted a folder onto it.

But I cannot tell software, that everything is moved or at least stored onto this larger mounted folder.

I did found videosCDN setting in advanced config, is this it?

**Comment by DanielnetoDotCom** [comment]
try to move your directory and create a symbolic link replacing the videos directory

there is a similar procedure here: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Moving-videos-directory-and-securing-files-from-direct-access-to-the-video-source-file

**Comment by SubjectXXX** [comment]
Ahh, of course, symbolic link.. Always forget about that.

Thank you!

**Comment by SubjectXXX** [comment]
Please close this issue :)
