### ISSUE TITLE
Playlists run off the screen. I cannot select my playlists anymore

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [DanielnetoDotCom/YouPHPTube#1415]
I have a lot of playlists but now I cannot select them. They run off the screen on me and I cant scroll high enough to select them.

what can I do now?

Screen shot attached.

**Comment by The-Do-It-Yourself-World** [comment]
![playlist problem](https://user-images.githubusercontent.com/45924889/51613673-fb163900-1ef1-11e9-8ea8-6fa17100822c.jpg)

**Comment by The-Do-It-Yourself-World** [comment]
When trying to edit a video playlist through "my videos" I cannot select any playlists at all. This part does not function at all. Screen shot follows.

**Comment by The-Do-It-Yourself-World** [comment]
![playlist-problem](https://user-images.githubusercontent.com/45924889/51614439-a96eae00-1ef3-11e9-9372-b5d0c0f9089f.jpg)

**Comment by The-Do-It-Yourself-World** [comment]
I cant scroll up to select the playlist.

**Comment by DanielnetoDotCom** [comment]
We will need to improve the playlist support.

we do not have a solution for that yet.

**Comment by The-Do-It-Yourself-World** [comment]
I have 2,000 videos on my one channel and everything is on hold until I can fix this. I cannot upload any more videos because it is becoming chaotic and messy without putting videos into playlists.

**Comment by DanielnetoDotCom** [comment]
Hi

the playlists were improved some time ago, not there is a scroll to not let the list overflow the page
