### ISSUE TITLE
after configuring ssl, live video does not work.

### ISSUE THREAD

**Issue by luciomor** [DanielnetoDotCom/YouPHPTube#1416]
boy, I use haproxy to distribute domains between servers ok. remembering that it is working ok ssl on all sites included in youphptube. Plus the problem is that the only thing that does not work is live video. if I open the site without https then the video works again. what can I do?

**Comment by Puyodead1** [comment]
Check youphptube logs for errors

**Comment by DanielnetoDotCom** [comment]
remember if your site is https your livestream must be https too

**Comment by luciomor** [comment]
so, how do I get nginx to listen to ssl on port 444? because if I enter the ssl address with port 444 it gives error: ERR_SSL_PROTOCOL_ERROR

**Comment by DanielnetoDotCom** [comment]
you have to edit your nginx config file

**Comment by luciomor** [comment]
the only way I found to access port 444 through an ssl connection was to create a subdomain and through the reverse proxy point it to port 444. So by accessing https: //rtmp.XXXX.XXX.XX/stat or / live caina nginx port 444 and so live and statistics run right.

**Comment by luciomor** [comment]
tem um bug. quando o arquivo é só de áudio, não consigo avançar, a barra de progresso desaparece.

**Comment by luciomor** [comment]
é possível criar uma opção para enviar vários arquivos de uma só vez para uma playlist?

**Comment by DanielnetoDotCom** [comment]
@luciomor , desculpe não entendi

**Comment by luciomor** [comment]
uma opção para importar os vídeos do youtube em massa. por exemplo digitamos um título de um vídeo do youtube e seu sistema busca todas as respostas relacionadas a esta pesquisa, então poderemos escolher alguns vídeos ou todos para importar automático do youtube entende? ao invés de termos que adicionar um por um.

**Comment by DanielnetoDotCom** [comment]
entendo, mas no momento não temos esta opção
