### ISSUE TITLE
[Solved] Installation Error - MySQL 1045

### ISSUE THREAD

**Issue by bobbyrabbit** [DanielnetoDotCom/YouPHPTube#1417]
I am installing on an openvz VPS. All parts are inputted correctly and everything has a green light.
On clicking submit I am receiving error....
Access denied for user ''@'localhost' (using password: NO)

I also tried creating a new DB and user granting all privileges and entering those details, with the Create Only Tables option

I installed on another OpenVZ VPS without any errors. I am using:
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

Thanks

**Comment by DanielnetoDotCom** [comment]
the problem is your mysql user, make sure your user is correct and can create tables

**Comment by bobbyrabbit** [comment]
Thanks for the reply Daniel.
I know users root and the new user I created have passwords and privileges are set as ALL.
The part that is confusing me is:
user ''

The user is blank?

**Comment by bobbyrabbit** [comment]
OK..After some more swotting I managed to fix this.
Be careful when using a Mac to SSH to your VPS using iTerm2.
The locales are automatically set by iTerm2, in my case "en_GB.UTF-8". This caused a problem writing to the the database.

**Comment by DanielnetoDotCom** [comment]
I see, thanks for the update
