### ISSUE TITLE
Content Protection / Watermarking

### ISSUE THREAD

**Issue by Wasca** [DanielnetoDotCom/YouPHPTube#1418]
I'm considering using this project but would like to know if I can watermark my videos like you can at VDOCipher - https://www.vdocipher.com/blog/2014/12/add-text-to-videos-with-watermark/

Also is there a way to prevent users from easily scraping video content. I'm hoping this project can work like this. https://www.vdocipher.com/page/securevideo

Is there a whitelisting option for where videos can be embedded? (IP or domain based)

Thanks for your help.

**Comment by SubjectXXX** [comment]
Whitelisting option would be nice to have, indeed..
