### ISSUE TITLE
Upgrading Version Unavailable

### ISSUE THREAD

**Issue by Dradden** [DanielnetoDotCom/YouPHPTube#142]
Currently running version 3.4.

"git pull" works fine and things are updated. But YouPHPTube does not see there is an updated version. I have no option for next version(s) in upgrade version section.

No errors in logs about this.

**Comment by DanielnetoDotCom** [comment]
Hi
After `git pull` did you run the youphptube update?
take a look on this video https://tutorials.youphptube.com/video/how-to-update-your-youphptube-version

**Comment by Dradden** [comment]
On my update page it simply says system is up to date, there is no option to upgrade unfortunately.

**Comment by DanielnetoDotCom** [comment]
you may have skip some updates (I am not sure)
then the best option is to edit the database configuration table to downgrade the system to where it was before you do the first upgrade and then update all steps and do not skip any of it.
if you have troubles to do that get the player configuration services I can fix it for you https://www.youphptube.com/services

**Comment by Dradden** [comment]
There is not really anything to skip from what I see it consists of:

git pull
navigate to upgrade version page and upgrade.

Did I miss something? I am not sure if it matters but I have never upgraded this install since I installed it until now.

**Comment by DanielnetoDotCom** [comment]
There is no git pull skipped.
What do you expect to see in your page and you are not seeing?

**Comment by nightstryke** [comment]
Dradden,
If you want the latest version you're going to have to reinstall and install the separate website and encoder in order to get it working. I tried upgrading from the way you described, it was a no go.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
