### ISSUE TITLE
Google analytics per user count

### ISSUE THREAD

**Issue by takleung** [DanielnetoDotCom/YouPHPTube#1425]
Hi,

Any way I can know specified login user behavior from google analytics?

Thanks,
Ray

**Comment by takleung** [comment]
i had tried to use different GA ID but not working for the "user form" one.
![screenshot 2019-01-25 at 2 33 11 pm](https://user-images.githubusercontent.com/208190/51729373-5b51da00-20ae-11e9-81e8-89e324598dcc.png)
![screenshot 2019-01-25 at 2 32 53 pm](https://user-images.githubusercontent.com/208190/51729377-6147bb00-20ae-11e9-8cff-1d113cb687f9.png)

**Comment by takleung** [comment]
Hi,

I also found the following on Google Analytics, it seems to resolve my problem. If yes, may I know where/how should I place the code? Thank you!

![screenshot 2019-01-25 at 3 03 11 pm](https://user-images.githubusercontent.com/208190/51730472-935b1c00-20b2-11e9-8701-9b3195e6085b.png)

Thanks,
Ray

**Comment by DanielnetoDotCom** [comment]
I am not sure, I have never tried it before, but I guess to make the code with user_id, you will need to do it on the PHP side.

the USER_ID can only be grabbed by PHP

**Comment by takleung** [comment]
Hi Daniel,

Thank you for you replied. I am thinking of the gtag is set "user_id" same as "$_POST['user_id']" or "$_GET['user_id']". In such of the case, may i know?

1. is that correct if php store user id in using "user_id"?
2. will it be possible to collect current login user id?
3. any workaround can do the same way per user tracking?

Thanks,
Ray

**Comment by DanielnetoDotCom** [comment]
I do not know how to use user_id on Google Analytics for tracking

If you really want to modify the PHP you should be able to understand the code and how to grab the ID. sorry but I can not teach you this

**Comment by takleung** [comment]
no problem and thank you Daniel, let's try it out!
