### ISSUE TITLE
Unable to logout

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1426]
I have logged in via LDAP, user is created. 

When I click on My account link in top right avatar menu, that avatar becomes inactive, nothing happens when I click on it again.

Page:
![bug_user_info](https://user-images.githubusercontent.com/2082595/51734030-9985d400-2083-11e9-805a-5e1a93345402.png)

Also some js errors happens when I open My account page.

Link on logo on top left corner is still active.

**Comment by DanielnetoDotCom** [comment]
looks like you have something else crashing the page.
look your log file

**Comment by SubjectXXX** [comment]
Problem is purely with missing iplocation tables. Once I installed that plugin (unzipped .sql file and installed tables) it started working.

You have some core dependencies on plugin..

**Comment by DanielnetoDotCom** [comment]
That was recently fixed. thanks for notice
