### ISSUE TITLE
Enhancement: Sign in, top right avatar

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1429]
Enhancement idea: if user is not logged in, that avatar should have direct link to login form, not a link where a menu appears on click with only one item: Sign in.

Also, push avatar a bit (5px) away from right edge of the screen, easier to hit, nicer to see.

**Comment by DanielnetoDotCom** [comment]
Agree, it needs some tweaks.

I will release some soon
