### ISSUE TITLE
Cant upload 100MB+ video

### ISSUE THREAD

**Issue by jinansy2** [DanielnetoDotCom/YouPHPTube#143]
Hey!
I've set my 
memory_limit = 512M
post_max_size = 500M
upload_max_filesize = 256M
But still im unable to upload videos larger than 100mb.
Can you please help?

**Comment by nightstryke** [comment]
try setting post_max_size and upload_max_filesize to the same number as well as changing the max_execution_time to 7200

So like this:
`post_max_size = 500M
upload_max_filesize = 500M
max_execution_time = 7200`

**Comment by jinansy2** [comment]
I've made changes as you suggested but still no luck.

**Comment by mikweb2017** [comment]
you are sure to have modified the right ini.php 
<?PHP
phpinfo ();
?>
 can verify if you upload an info.php file on your site's web site to verify the parameters

**Comment by jinansy2** [comment]
I've double checked everything and phpinfo also tells the same numbers as I paste above.

**Comment by nightstryke** [comment]
Are you running this on your own server or a shared server?

**Comment by jinansy2** [comment]
my own dedicated server.

**Comment by nightstryke** [comment]
Make sure you're editing the .ini file directly and not through an .htaccess file.

Try this:
`memory_limit = 512M`
`upload_max_filesize = 256M`
`post_max_size = 256M`
`max_execution_time = 7200`

Additional things to try:
`file_uploads = On`
`;max_input_time =`
`;upload_tmp_dir =`

**Comment by DanielnetoDotCom** [comment]
I have the same recommendations as @nightstryke

**Comment by nightstryke** [comment]
You could also try these configurations:
`max_input_time = -1`
`upload_tmp_dir = /tmp/`

-1 means unlimited input time,it is a little overkill but your situation is unique.

**Comment by jinansy2** [comment]
Tried everything but no luck. Im afraid there is some issue with the script?

**Comment by DanielnetoDotCom** [comment]
Hi, did you try to upload on demo site?
Yesterday I uploaded a 100 MB file to there with no problem.
Also I have an suggestion to encode big files.

If you run your own encoder you have en option to use bulk encode.
This option will encode videos from your hard drive.

![image](https://user-images.githubusercontent.com/18009293/31543391-34bf1422-afec-11e7-9e95-3b8bc6ae2cf2.png)

I have one costumer that uses Dropbox to sync his videos, then use the bulk encode.

I hope it helps you

**Comment by mikweb2017** [comment]
I found my solution I added ini_set ('memory_limit', '1024M'); on Encoder.php .
i thing you have  same problem
https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/issues/10

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
