### ISSUE TITLE
Where can I delete user?

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1430]
I cannot find where I can delete user.
You know, GDPR and stuff..

Is setting user inactive same as disabling user? Ergo: does that prevent him login and creating account with same email again?

**Comment by DanielnetoDotCom** [comment]
yes, you right

the problem to delete is because you will lose some statistics, like views and likes and dislikes of videos

**Comment by Andiweb87** [comment]
a solution is  disable the user to enter in the site , so will save the statistics
