### ISSUE TITLE
Time Problem

### ISSUE THREAD

**Issue by kkerimov** [DanielnetoDotCom/YouPHPTube#1433]
Hello dears.
I have a time problem in my script. We have 4 hours difference. When i just upload the video it show 4 hours back. Let say i have upload video in 13:00 PM it shows 9:00 AM. (Azerbaijan have a +4 GMT)
Where i can change the script time?

**Comment by Puyodead1** [comment]
Php.ini

**Comment by DanielnetoDotCom** [comment]
Also you can try to change your server time

**Comment by elias2k1** [comment]
Server time, php.ini timezone and also update the mysql timezone. But we have 5 hours difference.
