### ISSUE TITLE
video ads not showing on mobile devices (only PC)

### ISSUE THREAD

**Issue by quangtan13** [DanielnetoDotCom/YouPHPTube#1434]
hi team!
i also tested your demo website on mobile devices , but the video ads not showing and working.
it's running on PC only
pls check it

**Comment by DanielnetoDotCom** [comment]
The script was made by Google, so as long as I understand the script if it can not load the video on the specific time the ad does not play.

it plays only if the connection is good enough to fast load it

**Comment by quangtan13** [comment]
i got a black screen with this messenge : The media could not be loaded, either because the server or network failed or because the format is not supported (android 7 galaxy s7 edge - officcal web browser) , it run well on mobile chrome browser . hope team support more android web browser.       One more question is : if i embed a video code on another website post , can the video ads show on that post?

**Comment by DanielnetoDotCom** [comment]
this message was in your ads or in your video?

does demo site play fine on your mobile?

FYI the browser player works fine here

**Comment by quangtan13** [comment]
![51001561_411875619554458_8012236347949449216_n](https://user-images.githubusercontent.com/46710137/51893235-e399ed00-23d6-11e9-981f-2fc8c89ee40c.jpg)
![51513573_411875662887787_7640033580134957056_n](https://user-images.githubusercontent.com/46710137/51893236-e399ed00-23d6-11e9-9753-fa0eb33016d1.jpg)

i tested on android 5 + 7 (asus zenfone 2 + galaxy s7 edge) both of them got that error , it's running well when i download and open on mobile chrome browser app.

**Comment by DanielnetoDotCom** [comment]
Sorry, I am not able to reproduce this error.
so I can not fix it.

try to check your mobile network

**Comment by quangtan13** [comment]
my mobile network work fine , because when i open on another web browser , it's running well (got error when using native android browser )

**Comment by DanielnetoDotCom** [comment]
I have an android, and I have only a chrome browser on it.

**Comment by gregorymcewanmarriot** [comment]
have same issue on PC, tried chrome and AVAST browser also edge - ads wont show

The media could not be loaded, either because the server or network failed or because the format is not supported
