### ISSUE TITLE
Video not playing

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#1435]
HI..Daniel,

Today i found one issue i have ftp plugin before working fine.
but today i enabled GoogleAds_IMA plugin after video automatic pause.

**Comment by DanielnetoDotCom** [comment]
sorry what?

**Comment by gujarraju** [comment]
I am using ftp storage but if i enable GoogleAds_IMA plugin videos not playing..

**Comment by gujarraju** [comment]
embedded video working fine.. ads also working
but ftp video not playing

**Comment by gujarraju** [comment]
Please Check attached video file.

https://drive.google.com/open?id=1Ewj47wWm7MbnyTrmGWJHKtZ-UtOTmeBz

**Comment by tgd1973** [comment]
I tried to use the FTP plug with a
  other server (mine) on which I have installed FreeNAS ... Incoming the videos are uploaded on servers with FTP and in return to my site YouPhpTube Srtreamer I use the WebDAV service.
Everything works fine ... Of course, now I have no more space problems, because on the FreeNAS I can put hdd as many as I need (RAID).

**Comment by DanielnetoDotCom** [comment]
@gujarraju please check your javascript error at the time you try to watch a video?

also does this happen only if you enable the Google_IMA but works if it is disabled?

can you please make sure you have the latest version of the streamer and Google_IMA?

Google_IMA was recently updated

**Comment by DanielnetoDotCom** [comment]
The VAST response document is empty.


What vast link are you using?

**Comment by gujarraju** [comment]
http://googleads.g.doubleclick.net/pagead/ads?ad_type=video&client=ca-video-pub-4968145218643279&videoad_start_delay=0&description_url=http%3A%2F%2Fwww.google.com&max_ad_duration=40000&adtest=on

**Comment by gujarraju** [comment]
Same issue..

VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead
747b35fd8caf18d9ce274ef4c4b2e85c.js.pagespeed.jm.x2CWxkWWX4.js:1:1537

VIDEOJS: ERROR: videojs-contrib-ads has not seen a loadstart event 5 seconds after being initialized, but a source is present. This indicates that videojs-contrib-ads was initialized too late. It must be initialized immediately after video.js in the same tick. As a result, some ads will not play and some media events will be incorrect. For more information, see http://videojs.github.io/videojs-contrib-ads/integrator/getting-started.html

**Comment by DanielnetoDotCom** [comment]
ok, but now I see `VIDEOJS: ERROR: videojs-contrib-ads has not seen a loadstart event 5 seconds after being initialized, but a source is present. This indicates that videojs-contrib-ads was initialized too late.`

This happens on some devices, maybe it is too slow to load the script. this is a script limitation.
if I find a better solution in the future I will update the script

**Comment by gujarraju** [comment]
ok thanks
