### ISSUE TITLE
Unsafe hashing algorithms

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1436]
Just to let you know, you have some unsafe hashing algorithms in your code, specially around password creation and DB password storage.

Namely talking about sha1 and md5.. Its not hard to substitute them with more modern sha3-512 for example.

Just a heads up :)

**Comment by DanielnetoDotCom** [comment]
Hi

I disagree, the hash algorithm combines some hashes:

`md5(hash("whirlpool", sha1($password)));`

also if you want more security you can change your salt on the configuration.php file and enable it on the customizeAdvanced plugin.

you can check the code here:

https://github.com/DanielnetoDotCom/YouPHPTube/blob/efac0aa71d552936d7ea9dde7d7bff5bc224cdfa/objects/functions.php#L1255
