### ISSUE TITLE
Something borked autologin to encoder

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1438]
It worked until recently, but now, when I click on Encode video and audio, new window opens and says that Your user or password is wrong!.

If I enter then same username and password I used to login to streamer, it logs me in.

How can I debug this one?

**Comment by SubjectXXX** [comment]
When encoder encodes movie, it is correctly pushed to streamer..

**Comment by SubjectXXX** [comment]
Its a fresh install from yesterday..

**Comment by DanielnetoDotCom** [comment]
Are  the encoder and streamer up to date ?

They both must be the latest version .

I also made fresh installation of both yesterday and I found no problem

**Comment by SubjectXXX** [comment]
Hmm, yes, I had to git pull again and it works. .htaccess was overwritten, probably culprit was in there..

Please close this ticket.

**Comment by DanielnetoDotCom** [comment]
Great!

**Comment by SubjectXXX** [comment]
Nope :(

Error is back. Can you reopen this ticket please? I didnt change anything. It was working in between. I didnt even git pull..

So again, when I click Encode video and audio, new window with encoder url opens and says wrong username or password.

Only difference I have from your default installation is that I put YouPHPTube-Encoder into /var/www/html/YouPHPTube/ folder (because I have virtual host for port 80 that shows directly into this YouPHPTube folder ).

**Comment by SubjectXXX** [comment]
[31-Jan-2019 13:38:49 UTC] Start Login Request
[31-Jan-2019 13:38:49 UTC] Password check new hash pass does not match, trying MD5
[31-Jan-2019 13:38:49 UTC] Password check Old encoded pass
[31-Jan-2019 13:38:49 UTC] Password check Old not found
[31-Jan-2019 13:38:51 UTC] Start Login Request
[31-Jan-2019 13:38:51 UTC] Password check new hash pass does not match, trying MD5
[31-Jan-2019 13:38:51 UTC] Password check Old encoded pass
[31-Jan-2019 13:38:51 UTC] Password check Old not found
[31-Jan-2019 13:38:55 UTC] Start Login Request

**Comment by SubjectXXX** [comment]
If I enter same user/pass like on main page, it lets me through..

**Comment by DanielnetoDotCom** [comment]
Just to make it clear, only the autologin is failing?

**Comment by SubjectXXX** [comment]
Yes. But its confusing for end user..

**Comment by DanielnetoDotCom** [comment]
I really not sure 

do you have the encrypted salt enabled?

**Comment by SubjectXXX** [comment]
not manually, didnt change anything there..

**Comment by SubjectXXX** [comment]
OK, OK, found out something new: If I logout of streamer and log back in, then auto login to encoder works. If I close encoder window and try to encode another video by opnening encoder again, I get this error.

So something is wrong with session handling then?

**Comment by DanielnetoDotCom** [comment]
The only thing I can imagine is if the password the streamer is sending to the encoder is wrong.
I still can not reproduce it here

**Comment by SubjectXXX** [comment]
How could I debug this?

**Comment by DanielnetoDotCom** [comment]
try to check what password is the streamer submitting to the encoder, and check if it matches with the password on the database.

otherwise, you will need to add some code on the encoder to debug

**Comment by SubjectXXX** [comment]
Password is the same, only difference is, parameter encodedPass = true when error happens and false when I manage to get logged in. Streamer sends encodedPass = true..

**Comment by DanielnetoDotCom** [comment]
this is correct, if you send a encodedPass, this parameter is correct

**Comment by SubjectXXX** [comment]
Yes, but I still dont get logged in.

I checked with encoder's streamers table, user admin exists and pass is the same as in users table on streamer side.

**Comment by SubjectXXX** [comment]
Is problem that streamer sends password unencoded but param encodedPass= true?

Because I can see my password not being sent encoded when streamer calls encoder login..

**Comment by SubjectXXX** [comment]
Interesting, Firefox sends encoded password, Chrome doesnt..

I guess it has something to do with cache in chrome, but didnt know that chrome caches php calls..

**Comment by DanielnetoDotCom** [comment]
the unencoded pass should not happen, for me is working in both browsers.
we agree that must be something on your browser. maybe the autocomplete.
I just sent an update to disable autocomplete on that form, please update and check

**Comment by DanielnetoDotCom** [comment]
I guess your browser is auto-completing the password fields, replacing the information PHP is adding on it.

I have added autocomplete="off"  on the inputs but looks like is not working.

do you have any plugin that may be filling it up?

**Comment by SubjectXXX** [comment]
No plugins directly..

I have removed this site from Chrome's saved passwords and it started working..

So that autocomplete="off" isnt on the right spot? :)
