### ISSUE TITLE
Footer not on the bottom of page

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1439]
Cosmetics.

Footer with Powered by.. doesnt stick to bottom of page.
![footer](https://user-images.githubusercontent.com/2082595/52050356-9c376c00-2550-11e9-9d41-18a1d805123c.png)

**Comment by DanielnetoDotCom** [comment]
it may be fixed now

**Comment by DanielnetoDotCom** [comment]
Sorry, I had to roll back the changes, it breaks some layouts

**Comment by SubjectXXX** [comment]
Hehe, no worries, just let me know when new commit is available..
