### ISSUE TITLE
Remember Log in Information

### ISSUE THREAD

**Issue by JinZhuXing** [DanielnetoDotCom/YouPHPTube#144]
I want to use remember login option.
Now, when I use our site, I must log in manually everytime.
Most websites support "remember me" option in Sign in page.
I want to use it in our YouPHPTube site.
Thanks.

**Comment by DanielnetoDotCom** [comment]
Yeah, you right, we will make it soon.

**Comment by JinZhuXing** [comment]
Thanks

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
