### ISSUE TITLE
Questions about css and modifications

### ISSUE THREAD

**Issue by charliedaps1** [DanielnetoDotCom/YouPHPTube#1440]
Hello everyone,

I would like to remove the border from the frame of the homepage of the videos.

I found the border in .list-group-item of bootstrap.css but it does not change anything when I remove the border: 1px solid #dddddd;

I deleted the files in / videos / cache but nothing works.

My browser also finds me a border line in the file list-group.less but I can not find this file on my server ???

Thank you in advance for your help.

**Comment by DanielnetoDotCom** [comment]
try to add the CSSs you want on the head code

![image](https://user-images.githubusercontent.com/18009293/52117959-cc841680-25f3-11e9-9cb5-75d7620d401b.png)

**Comment by charliedaps1** [comment]
Thanks for your anwser.

I have find the solution in the css code.

**Comment by DanielnetoDotCom** [comment]
you welcome
