### ISSUE TITLE
 Strict Standards: Non-static method YouPHPTubePlugin::getAllVideosExcludeVideosIDArray() should not be called statically

### ISSUE THREAD

**Issue by TechBill** [DanielnetoDotCom/YouPHPTube#1442]
I installed the script and I am getting this error message 

<img width="1235" alt="screen shot 2019-01-31 at 1 24 04 pm" src="https://user-images.githubusercontent.com/945103/52079583-85e2dd80-255b-11e9-86ed-e1b40d8b701b.png">

**Comment by DanielnetoDotCom** [comment]
fixed, thanks for notice it
