### ISSUE TITLE
Categories not visible

### ISSUE THREAD

**Issue by EatBananas** [DanielnetoDotCom/YouPHPTube#1443]
Hi,

I made a fresh YouPHPTube Installation, uploaded some Videos for testing and assigned the videos categories which I created before. On the front page all the videos are visible and available to watch. But all the categories i create are not visible in the menu even tough they are set to "public".

Thanks and kind regards

**Comment by DanielnetoDotCom** [comment]
They will be visible only if they have videos in it

**Comment by EatBananas** [comment]
Yes, i know that, but in my case it is strongly depending. Normally i don't see any categories, even tough they have videos in it. But if i switch a video from one category into the other they are suddenly visible until i log-off and log-on again, then they are disappeared again.

**Comment by DanielnetoDotCom** [comment]
so you are saying there are videos on the category but it is not visible?

**Comment by EatBananas** [comment]
Yes i have multiple videos in a category but the category is not visible. But if i have a open session as an admin and i switch the category of a video into a other category all the categories suddenly get visible until i log-off and log-on again.

**Comment by DanielnetoDotCom** [comment]
Please check if you have the cache plugin enabled.
if you direct login as admin can you see them all?
does this happen only with regular users?

**Comment by EatBananas** [comment]
Yes, cache plugin is disabled .
Yes, if i login as user "admin" i can see all the categories, but if it is a other user with admin rights not.
The problem appears only with users created by the LDAP-Plug-In(most of the users) and not with users which have been created manually in the admin interface.

**Comment by EatBananas** [comment]
Yes, but if i give an LDAP-User all the rights available he can still not see the categories, even tough the videos on the frontpage are visible.

**Comment by DanielnetoDotCom** [comment]
this is really strange behavior.

Does this happen only with LDAP users?

can you please try to update your files and see if the error persist?

**Comment by EatBananas** [comment]
Yes, it only happens with LDAP users, i just created another non-ldap-testuser and enabled him to watch the existing videos and there were no problem at all.

I pulled all the files, but the problem persists.

**Comment by DanielnetoDotCom** [comment]
I really can not see a reason for that.

the LDAP plugin creates a user just like a regular one.

check if the LDAP users have the same groups as your new use have.

**Comment by EatBananas** [comment]
Hi,
Sorry for not answering for such a long time. I just did an update and now everything works fine. I can't explain why it didn't work before but at least it works now.
Thanks a lot
