### ISSUE TITLE
Top menu creation error

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1444]
![menus](https://user-images.githubusercontent.com/2082595/52122026-ed636080-2621-11e9-8cfd-2ef7ad3c3b1e.png)
Happens as soon as I open settings for top menu creation..

**Comment by DanielnetoDotCom** [comment]
please make sure you have the tables installed

**Comment by SubjectXXX** [comment]
Interesting, I had to restart server for that button to start working. I guess some problems with mysql server instance.
