### ISSUE TITLE
Streaming videos

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1445]
Lets say I dont want/can't use iframe embed to html. Is there a way to server these videos via something else, to stream them in player on the other site, like Moodle?

Can I use videos from this site with <video> tags on other side? Maybe to include video in VideoJS player on 3rd party site?

**Comment by SubjectXXX** [comment]
https://rwdy15.wordpress.com/category/ffmpeg/

**Comment by DanielnetoDotCom** [comment]
the only way I can see now is directly accessing the mp4 file.

**Comment by SubjectXXX** [comment]
Can you not trigger ffmpeg to stream to IP like you trigger ffmpeg to encode stuff?

Or if you really really dont want to use ffmpeg, this is the solution: https://videojs.github.io/http-streaming/ ?

**Comment by DanielnetoDotCom** [comment]
For sure in the future, I will improve youphptube to use HLS videos as VOD.

**Comment by SubjectXXX** [comment]
In the future!

**Comment by SubjectXXX** [comment]
I'm seeing some HLS settings around in latest pull. Are you working on this already? We will get any notice and instructions how to set that up?

**Comment by DanielnetoDotCom** [comment]
Yes, I am working and just finishing the tests.
It will be a paid plugin.
if you look into the demo site, all videos are HLS encrypted. so I guess you can not download it anymore.
