### ISSUE TITLE
The configuration settings are not getting saved

### ISSUE THREAD

**Issue by TechBill** [DanielnetoDotCom/YouPHPTube#1447]
I wanted to make the website only for logged in members before they can see any videos or any part of the site.

I go to General settings and toggle on "userMustBeLoggedIn" but I still can see everything as a guest so I went back and noticed that the enable toggle never get saved.  I save it again and it won't be saved. It goes back as disable toggle again when I return to general settings.

**Comment by DanielnetoDotCom** [comment]
try to check your error log, should be some clue there

**Comment by SubjectXXX** [comment]
Check youphptube.log file in /var/www/html/youPHPTube/videos/ folder (or similar..) OR open inspector (f12 in Chrome) and check in console if there are any errors.

**Comment by TechBill** [comment]
There is nothing in error log or Chrome console after I save the setting.  I check the apache log and I do see this 

[05/Feb/2019:12:17:34 -0600] "POST /testone/admin/save.json.php HTTP/1.1" 200 34 "http://proscoops.com/testone/admin/?page=general_settings" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"

So when I check the error log on same timeframe and nothing is shown in it that matches the same timeframe or around that timeframe.  All other domain errors are shown so I know it's logging errors.

**Comment by TechBill** [comment]
You can try and test it at http://proscoops.com/testone/
 
httpd lock u/p 
u: test
p: 123test456!

youphptube admin u/p
u: admin
p: 123admin456!

The whole setup will be delete in a day or so, feel free to change anything on there to test it.

**Comment by SubjectXXX** [comment]
Yeah, I have already reported this kind of bug to author. Problem is, core functionality is depended on a toggable plugin, in your case, customizeUser plugin. Once enabled, settings are saved.

@DanielnetoDotCom : we already explored this kind of situation with another of my tickets. I guess you'll have to add some checks if plugins are enabled when showing settings around your page.

**Comment by TechBill** [comment]
@SubjectXXX   I saw someone enable it but I still can see videos without logging in.   Is it suppose to show only log in box when enabled?

**Comment by SubjectXXX** [comment]
I dont use this functionality, but I guess yeah, if you enable userMustBeLoggedIn, only login box should be available.. Daniel will have to shed some light onto this..

**Comment by kiran7306** [comment]
Hello,
I am using YouPHPTUBE in my local server am facing a lot of problems like 
1. I am  unable to upload videos in it . 
2. In admin panel options are not saving and up on refresh they are getting Undo
3.when i imported video from YouPHPTube-encoder ,the video still in downloading stagae and it is not uploaded in my server
Can you please help me in solving these issues and I Will be thankful to you.
I am uploading the picture please go through it
![yophptube](https://user-images.githubusercontent.com/50979249/58776399-1acc1500-85e8-11e9-8b16-950a64e7062c.png)
**Thanks in advance**

**Comment by SubjectXXX** [comment]
I would suggest opening new ticket.

**Comment by judouk** [comment]
As mentioned above, the problem is that on an initial install, customizeUser plugin is not enabled.
It is a little buried in the configuration but once I enabled that, the settings could be saved.
