### ISSUE TITLE
Not showing anything

### ISSUE THREAD

**Issue by thereskinner** [DanielnetoDotCom/YouPHPTube#1448]
I just deleted the install file (as I was told) and now this is all I see

![image](https://user-images.githubusercontent.com/47253114/52136113-54c6e380-2615-11e9-9ca7-25331beaae73.png)

How do I fix this ?

**Comment by Andiweb87** [comment]
where  you have read to remove the install file ??

**Comment by DanielnetoDotCom** [comment]
check your error log.

you can try to place the install files again on place

**Comment by thereskinner** [comment]
I just tried and it didn't work so now I'm extracting the files again

> upload again the folder install

**Comment by Andiweb87** [comment]
can you past here your url ?

**Comment by thereskinner** [comment]
> can you past here your url ?

Which one ?

**Comment by Andiweb87** [comment]
your url site

**Comment by thereskinner** [comment]
It's not live yet it's on wamp server. I just tried doing it again and I'm still getting the same error.

**Comment by Andiweb87** [comment]
you have upload again the install files in the same place ? also try to clean cookies

**Comment by thereskinner** [comment]
Yes I put them back in the same place. I just cleared the cookies and still the same thing.

**Comment by Andiweb87** [comment]
strange , please can you check the log files and post them here ?

**Comment by thereskinner** [comment]
I don't know how to do that

**Comment by Andiweb87** [comment]
open -->  /var/www/html/YouPHPTube/videos  

in this place you will find **youphptube.log** file , open it see what show there or past here

**Comment by thereskinner** [comment]
I don't see those folders or files.

**Comment by Andiweb87** [comment]
can you see the folder videos ?? if yes open it

**Comment by thereskinner** [comment]
Okay I did

**Comment by Andiweb87** [comment]
open the file youphptube.log

**Comment by thereskinner** [comment]
I don't see that file

**Comment by thereskinner** [comment]
Maybe that's what's wrong. I have a few folder that contain the text "youphptube.log" but the file itself isn't in there.

**Comment by Andiweb87** [comment]
youphptube.log is only on videos folder, look can you make a fresh install ? i think will be better and dont remove the install folder, make an new installation from start or wait when Daniel see this issue.

**Comment by thereskinner** [comment]
Okay

**Comment by Andiweb87** [comment]
do you renamed the folder YouphpTube ??

**Comment by thereskinner** [comment]
No do I have to ?

**Comment by Andiweb87** [comment]
No no just asking

**Comment by SubjectXXX** [comment]
First of all, he is using Windows.
Secondly, I think there is a problem with his php installation.

@thereskinner : what version of Wamp you using?

**Comment by DanielnetoDotCom** [comment]
Sorry I can not support windows., I agree with @SubjectXXX
