### ISSUE TITLE
4 videos per line on the home page

### ISSUE THREAD

**Issue by charliedaps1** [DanielnetoDotCom/YouPHPTube#1449]
Hello,

How can I do to put 4 videos per line instead of 6 planned origins.

I found in the plug in gallery this but it does not change anything.

I managed to put 4 videos per line but it works more.

Thanks for your help.

**Comment by DanielnetoDotCom** [comment]
It should work, I just test it

![image](https://user-images.githubusercontent.com/18009293/52164387-594fd280-26cf-11e9-88ca-d2868361b8ed.png)

**Comment by charliedaps1** [comment]
Thank you for your reply.

So yes it worked but I changed something in the file functions.php and it does not work anymore.

I changed the css

And on my other site, I do not have this option.

How to have it? I have gallery but I can not put X columns.

Thanks

**Comment by DanielnetoDotCom** [comment]
Update your YouPHPTube with the latest files
