### ISSUE TITLE
Monetização 

### ISSUE THREAD

**Issue by PlayxPE** [DanielnetoDotCom/YouPHPTube#145]
Gostaria de colocar uma área de monetização no meu site poderia adicionar essa opeção futuramente

**Comment by DanielnetoDotCom** [comment]
como assim?
se for o google ads, já tem um lugar pra isso.
também você pode colocar seus próprios videos

**Comment by PlayxPE** [comment]
Uma área para monetizar o vídeo e ganhar dinheiro

**Comment by DanielnetoDotCom** [comment]
Já temos o google ads https://tutorials.youphptube.com/video/make-money-with-youphptube-enable-google-adsense

e vídeos próprios do sistema https://tutorials.youphptube.com/video/how-set-a-video-gallery-and-set-video-ads

o que mais vc procura?

**Comment by winklov** [comment]
How can we integrate adesense for video into the platform

**Comment by DanielnetoDotCom** [comment]
here: https://tutorials.youphptube.com/video/make-money-with-youphptube-enable-google-adsense

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by jonathanpecany** [comment]
I have a similar question and a feedback on this so first I am going to show you my feedback on this.
I love this and it is mainly the only one 100% working on github.

Now my question is how can I monetize my videos on it with videos already on it if you know what I mean if not than i'll give an example. 
(ex. Youtube has some ads of videos that's already on youtube so how can I do that on YouPHPtube?)

**Comment by DanielnetoDotCom** [comment]
You can use the GoogleAds_IMA plugin to use google adsense .
Or you ca use the built in ads system to monetize, that uses your own video as an advertise
