### ISSUE TITLE
Request help for a new function: < embeded channel in external iframe page >

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#1450]
Hello!  
I am writing to ask for help regarding the possibility of completing a work that I have tried to realize with this ebedding of a channels. I duplicated then modified two files from the inside of the folder "view" I called them: embedchannel.php and embedchannelBody.php then I added a rule in htaccess: 
`RewriteRule    ^embedchannel/([^/]+)/?$ view/embedchannel.php?channelName=$1    [QSA]` 

[embedchannel.php+embedchannelBody.php.zip](https://github.com/DanielnetoDotCom/YouPHPTube/files/2825673/embedchannel.php%2BembedchannelBody.php.zip)

The embed channel can be called from the browser like this:  https://www.abc.net/embedchannel/5b0c45c35xxx

What I should do again is to insert a script inside the embedchannelBody.php that usually pops up a player to the embededchannel page when you click on the thumbnail from the page ... instead of redirecting to another page (player page) as in the example of below that someone has already done:
http://archives.bisericilive.com/gallery?cid=bisericabetelro#

It could be useful if in these embedded pages of the channels there would be an option to filter content so that for all videos that is put on YouPhpTube is apply the rule that the upload videos are unlisted and that for each chanale is create a group with the same name, and that the  only this channel  displays videos of that group ... so that on the server of Streamer YouPhpTube are not visible all videos of the channels so as is to not create confusion. 
So every church that wants to transmit or upload videos in their channel  ... the contents of the channel is visible in the iframe embeded page that they can attach to their blog / site that represents their church.

A big thank you in advance.

**Comment by DanielnetoDotCom** [comment]
I see, and I agree with you it is a good feature.

It may be done in the future we do not have it now.

but as I understand you already start to do, but I do not understand what do you need to finish it?

**Comment by tgd1973** [comment]
My intent was to insert a videojs player, directly inside one of the two .php files in order to make the embededchannel similar to this example:
http://archives.bisericilive.com/gallery?cid=bisericabetelro#
 to work with the videojs player that coming over the embed page without redirecting to another page. The problem is that I'm not so good with javascript and the parameters that I have to resume from the file embededchannelBody.php to be able to make them communicate to make videos play ...

**Comment by DanielnetoDotCom** [comment]
did you see the playlist embed code?

it is a new feature and you can grab them from your channel page

**Comment by DanielnetoDotCom** [comment]
sorry, we do not have the option yet to embed the full channel page.

it may be add in the future

**Comment by tgd1973** [comment]
Hello! I'm sorry to disturb again ... but you closed this ticket but could not say anything about the way in which the channelBody.php script works, especially with the code starting from the line 77-78:
`<?php`
`createGallerySection($uploadedVideos, "", $get);`
`?>`
from your YouPHPTube.
Kindly can you tell me something about it?  I do not understand where is going to refer this code that makes me populate the page with thumbnails that then each one has its address by clicking.
Thank you.

**Comment by DanielnetoDotCom** [comment]
it uses a Gallery function to create the little videos squares, with videos links and information.

whatever you change on that function will reflect on the gallery and on the channel
