### ISSUE TITLE
changing font

### ISSUE THREAD

**Issue by charliedaps1** [DanielnetoDotCom/YouPHPTube#1451]
Hello,

how can i change the font of the site ?

Thanks for your help

Have a good day.

**Comment by DanielnetoDotCom** [comment]
Yes, using CSS.

Add your CSS you should put on site configurations -> script code -> head code

**Comment by charliedaps1** [comment]
Do you have more information please ?

I try to add

`<style>

@font-face {
    font-family: 'Linotte-SemiBold';
    src: url('../fonts/Linotte-SemiBold.eot');
    src: url('../fonts/Linotte-SemiBold.eot?#iefix') format('embedded-opentype'),
    url('../fonts/Linotte-SemiBold.woff') format('woff'),
    url('../fonts/Linotte-SemiBold.ttf') format('truetype'),
    url('../fonts/Linotte-SemiBold.svg#Tungsten-Medium') format('svg');
    font-weight: normal!important;
    font-style: normal;
}

</style>
`

But there is not modification of the font.

Thanks by advance for your help

**Comment by DanielnetoDotCom** [comment]
I am not sure and not tested, but try

```
<style>
* {
font-family: 'Linotte-SemiBold';
src: url('../fonts/Linotte-SemiBold.eot');
src: url('../fonts/Linotte-SemiBold.eot?#iefix') format('embedded-opentype'),
url('../fonts/Linotte-SemiBold.woff') format('woff'),
url('../fonts/Linotte-SemiBold.ttf') format('truetype'),
url('../fonts/Linotte-SemiBold.svg#Tungsten-Medium') format('svg');
font-weight: normal!important;
font-style: normal;
}
</style>
```

**Comment by charliedaps1** [comment]
Something is happening weird.

The Linotte-SemiBold font works fine, but when I want to set another font, it does not work.

I upload in the directory the 4 files of the new font, I set font-face code with the name of the font but it does not work.

Do you have an idea of ​​the problem ?

Thank you

**Comment by DanielnetoDotCom** [comment]
maybe the font path, sorry, but I can not support you on that

please take a look on this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Site-Design-and-Templates

**Comment by charliedaps1** [comment]
I continue to look for a solution to this problem of font.

Except the code to put in the script? Should we change something else in the css or in the html?

Thanks

**Comment by charliedaps1** [comment]
I continue to look for a solution to this problem of font.

Except the code to put in the script? Should we change something else in the css or in the html?

**Comment by DanielnetoDotCom** [comment]
Not, sure, how your CSS looks like, I never test it. and also I can not support you on your design
