### ISSUE TITLE
iFrame and Moodle -> Internal server error 500

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1453]
With iFrame embed code copied directly from youphptube into source code of Moodle HTML, when I open the page, I get 500.

Logs on youphptube server dont show anything..
Both sites running cert and https.

How can I debug this?

**Comment by SubjectXXX** [comment]
Embedding iFrame with difference source works on the same page so I guess its not Moodle's fault?

**Comment by SubjectXXX** [comment]
Even if I put src url into browser, I get 500.. So something is wrong with videoEmbed function i guess...

**Comment by DanielnetoDotCom** [comment]
I just sent an update to make sure it will not happen

sorry and thanks
