### ISSUE TITLE
Improvement: embed code 

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1456]
I dont know how to make a pull request, so here it is:

in /view/modeYoutube.php, line 455 should look like this:
    $code = '<iframe width="640" height="360" style="max-width: 100%;max-height: 100%; border:none;" src="' . Video::getLink($video['id'], $video['clean_title'], true) . '" frameborder="0" allowfullscreen="allowfullscreen" allow="autoplay" scrolling="no">iFrame is not supported!</iframe>';
    
Explanation:
- height="360" -> to keep most used 16:9 format resolution without black borders on top and bottom of iframe
- border:none is substitute for frameborder="0" which is obsolete in HTML5
- scrolling="no" -> disable/hide scrollers
- text in <iframe> tag -> If iframes are disabled (missing https protocol) or forbidden, its nice to notify user about this. Also, easier to copy this embed code into text editors that require at least one content character in their input field (Moodle's page for example).

Next step would be to implement dynamic height/width of iframe according to video proportions. ffmpeg allows to query video and return its resolution. Calculating the ratio between height and width you could determine exact values for height and width for optimal iframe size.

Not sure if same applies to /plugin/FBTube/view/getVideos.php@342.

**Comment by DanielnetoDotCom** [comment]
I pull request will be the best, because you will be as an official contributor of the project.

to make a pull request, you will need to fork the code into your account, make the changes, upload it to your fork and then make a pull request

let me know if you will try then I will wait

**Comment by SubjectXXX** [comment]
OK, let me try, need to learn something new every day!

**Comment by SubjectXXX** [comment]
Hmm, did I do it correctly?

**Comment by DanielnetoDotCom** [comment]
I still not received your pull request. try google to see the step by step how to do it.

**Comment by DanielnetoDotCom** [comment]
Perfect! https://github.com/DanielnetoDotCom/YouPHPTube/graphs/contributors
