### ISSUE TITLE
Logo size

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1457]
More control on logo height on top of the page would be nice.

Atm, if I use supplied functionality, image is always resized to 70px height, but that makes my logo unreadable. I have to fix css in /view/css/custom/default.css and ftp correct size picture to /videos/userPhoto to keep it readable.

But that breaks every time I git pull the code.

Few ideas in order of awesome from best to worst case:
- give us option to set height of logo and/or top bar
- set height of top bar same as image that resides there and get rid of 70px limit/conversion
- rename default.css into example_default.css so when pulling from git, user's custom default.css is not overwritten

**Comment by DanielnetoDotCom** [comment]
Agree with you, I will need to add mor customizations on it.

Thanks

**Comment by SubjectXXX** [comment]
Can you for now just rename default.css to example_default.css and write instruction to rename example_default.css if needed?

So when I do git pull on code, my default.css in custom is not overwritten....

**Comment by DanielnetoDotCom** [comment]
why dont you add the customized css on the sites -> configuration -> head code?

**Comment by SubjectXXX** [comment]
Will have to check. I tried it once but I think it gets included before the rest of css get included, thus some changes were overwritten by default/core css..

Will test again..

**Comment by DanielnetoDotCom** [comment]
I see, can u try to use the !important.

I know it is the best solution, but may work

**Comment by SubjectXXX** [comment]
!important worked I guess. Will close ticket for now.
