### ISSUE TITLE
SMTP issues - main FIX included

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1458]
I've found multiple tickets with SMTP issues here so I decided to investigate a little further.
I found few problems that should get fixed as soon as possible:

1. remove that catpcha from testing email settings. Its pointless, only admin is gonna test this and I really dont need captcha control here.

2. Hardcoded testing email: can we please get at least email param to the one that site email is set, that is, admin email? I would like to see that email sent, sending it to teste@teste.com is pointless. I have hardcoded mine into code, but can you solve this on a general level? File /view/sonfigurations_body.php@590

3. /objects/functions.php@410: you hardcoded $mail->SMTPAuth = true; yet you have a setting Enable smtpAuth. This is the reason why my mail was not working. I had setting smtpAuth in DB set to false, yet it wanted to auth towards the server. Changing this to be read from DB solved the issue:
$mail->SMTPAuth = $config->getSmtpAuth();

I hope issues are gonna be fixed before I have to pull from git next time to avoid overwriting my own solutions :)

**Comment by DanielnetoDotCom** [comment]
> * remove that catpcha from testing email settings. Its pointless, only admin is gonna test this and I really dont need captcha control here.

If you remove it the objects/sendEmail.json.php will be vulnerable, anyone will be able to use it to send emails

> * Hardcoded testing email: can we please get at least email param to the one that site email is set, that is, admin email? I would like to see that email sent, sending it to [teste@teste.com](mailto:teste@teste.com) is pointless. I have hardcoded mine into code, but can you solve this on a general level? File /view/sonfigurations_body.php@590

It is not clear to me, but by default the sender is the email from configurations. only the test email has a different sender

> * /objects/functions.php@410: you hardcoded $mail->SMTPAuth = true; yet you have a setting Enable smtpAuth. This is the reason why my mail was not working. I had setting smtpAuth in DB set to false, yet it wanted to auth towards the server. Changing this to be read from DB solved the issue:
>   $mail->SMTPAuth = $config->getSmtpAuth();

I see your SMTP does not require authentication?

**Comment by SubjectXXX** [comment]
1. Just make a check if user is logged in and his role is admin, then trigger send().

2. Yes, but even test email would be nice to receive. ATM, its hardcoded to teste@teste.com. Can you not access to $config['site_email'] or wherever you saved that site email?

3. Nope, because we have it tied to IPs (IPs are whitelisted), so no need for auth.

**Comment by SubjectXXX** [comment]
1. yes, just logged on is not enough, but user also has to be admin. I saw that you already have isAdmin() check somewhere in your code. Use it here for sending test emails instead of captcha..

2. yes, either this email or a text box where we can select where to send test email. Both have its pros and cons. First one is less work for testing, with second solution you can test if exact user, that doesnt need to be me, can receive emails from this site..

3. No, just use $mail->SMTPAuth = $config->getSmtpAuth(); instead of $mail->SMTPAuth = true; . You already have this option for SMTPAuth implemented and its correctly saved in database, you are just ignoring it by hardcoding $mail->SMTPAuth = true;.. Or am I missing something?

**Comment by SubjectXXX** [comment]
1. Yes, I know.. I have get to know your big project quite good so far :) So the question remains: do we really need captcha on a section that only admin can and should use? Can we just check if user, who is triggering $mail->send() is loggedIn AND isAdmin?

2. I dont see a problem with that. You never sent a email to yourself with some task or notification? :)

3. Good :)

**Comment by DanielnetoDotCom** [comment]
1. I think I understand you now, if isAdmin, do not need to check captcha, otherwise, check it
I sent a partial update for it

2. done

I think we are all done on it :)

thanks

**Comment by SubjectXXX** [comment]
Just a follow up on first point: Latest pull removed the need for captcha being entered, but it left us with BLACK captcha and textbox is still present, which could confuse somebody..

![captcha](https://user-images.githubusercontent.com/2082595/52555602-7af53c00-2dea-11e9-8b48-86dfce113596.png)

**Comment by DanielnetoDotCom** [comment]
Agree, that is why I said it is a partial solution.

**Comment by BartManX** [comment]
> Just a follow up on first point: Latest pull removed the need for captcha being entered, but it left us with BLACK captcha and textbox is still present, which could confuse somebody..
> 
> ![captcha](https://user-images.githubusercontent.com/2082595/52555602-7af53c00-2dea-11e9-8b48-86dfce113596.png)

i was stumped on this ... for a long time.

**Comment by DanielnetoDotCom** [comment]
It was removed from email configuration page
