### ISSUE TITLE
Cannot add Adsense code

### ISSUE THREAD

**Issue by winklov** [DanielnetoDotCom/YouPHPTube#146]
Hi

I cannot add my adsense code in ver 4.1

**Comment by winklov** [comment]
im trying to get adsense and adsense for video up and running

**Comment by winklov** [comment]
Can we get Adsense for video integrate on the platform

**Comment by DanielnetoDotCom** [comment]
did you try this way? https://tutorials.youphptube.com/video/make-money-with-youphptube-enable-google-adsense

It is working normally in all youphptube sites I manage

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by hypedboss** [comment]
please what does the video adsense look like. does it appear as banners on the video or as instream skip ads?
