### ISSUE TITLE
Cpu usage

### ISSUE THREAD

**Issue by inferno-prime** [DanielnetoDotCom/YouPHPTube#1462]
Hello I know i mite have already asked this but things have changed. my host has a policy on the shared usage of the cpu. I will not be using the encoder for now because of this and am only worried about the streaming part. I will not be allowing accounts to keep resources free.

Here is what my host says but I want your take on this : 

Acceptable load average on shared average:
10% CPU Usage
5% Memory Usage or 512 MB Memory
50 Running Processes
15 Minute Max Execution Time

**Comment by DanielnetoDotCom** [comment]
The problem is on Livestream (Uses RAM) and Encode (Uses CPU)

just stream VOD videos does not consume much, only bandwidth

**Comment by DanielnetoDotCom** [comment]
Watch VOD videos does not consume much resources, only bandwidth
