### ISSUE TITLE
Other software running besides this.

### ISSUE THREAD

**Issue by inferno-prime** [DanielnetoDotCom/YouPHPTube#1466]
I will be running other software besides this will that be alright ?.

**Comment by DanielnetoDotCom** [comment]
Sorry, I do not understand what do you mean.

**Comment by SubjectXXX** [comment]
He probably means, that he is going to use apache for some other applications.

Which is fine @inferno-prime , if you know how to configure your application with different ports for example or know how to use virtual hosts..

**Comment by DanielnetoDotCom** [comment]
Sure you can use the same apache to host other sites.

I agree with @SubjectXXX , virtual hosts are the best option to configure multiple sites on it.
