### ISSUE TITLE
Disable modal

### ISSUE THREAD

**Issue by charliedaps1** [DanielnetoDotCom/YouPHPTube#1467]
Hello,

How can I do so that the modal of the video does not appear.

When we start a video and we go down the page, the video is displayed in small. How to disable this feature?

Thank you

Ok i have fund.   Float video

**Comment by Andiweb87** [comment]
You have to go in --> Plugin --> Float Video , enable it and go to **Edit parameteres** , after click  in **donotfloatvideo** like the screenshot , Saves changes and you done

https://snag.gy/C87Ygm.jpg

**Comment by charliedaps1** [comment]
Thanks Andiweb87.

It works ;)
