### ISSUE TITLE
Logo Play and movie on the gallery

### ISSUE THREAD

**Issue by charliedaps1** [DanielnetoDotCom/YouPHPTube#1468]
Hello,

Still 2 questions please.

- How to change the PLAY logo in the middle of the video?

- How to make that when hover on the video of the gallery, the video starts.

I saw on the Demo website that it was possible.

Thanks for your help.

**Comment by SubjectXXX** [comment]
Logo in the middle is changed with different theme. Check there..

Hovering ussualy plays gif, that is like a moving thumbnail. I dont think whole video is played only with hover..

**Comment by charliedaps1** [comment]
Thanks.  I try ;)

**Comment by SubjectXXX** [comment]
No problemos!

**Comment by DanielnetoDotCom** [comment]
@SubjectXXX has completely clarified this issue. thanks
