### ISSUE TITLE
Private videos - non-public videos

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1469]
When I encode new video, or upload it, doesn't matter, if I deselect Public video and I dont push it into any category, this video should be hidden from all users.

Its not the case tho. I made it non-public, not in any category, and its still visible on a fresh user on frontpage.

**Comment by SubjectXXX** [comment]
Yes, Unlisting helps, but thats just confusing. Non-public videos should be .. not public, ergo, only seen by those, that I want..

Even more.. If I deselect Public video option, groups pop down. If I dont select any group and save video settings, Public video option turns back on.. Leave it off please!

**Comment by SubjectXXX** [comment]
To elaborate even more, sorry :)

Ordinary user should have option to create group with people that he can assign video to.
So, a create group button should popup a text box into which you enter user's emails (I would advise against listing all users on site to cherry pick group members) or user's usernames, if they exists, they are added to the group (maybe request each member to confirm into the group addition?).

**Comment by DanielnetoDotCom** [comment]
This is an awesome concept. and we will probably update it in the future. but for now, it requires too many changes.

**Comment by razyalov** [comment]
Is there a workaround that can be used to hide videos from the public homepage? If not, can you explain what is the hard part so maybe we can try to help with a PR for this issue?

**Comment by DanielnetoDotCom** [comment]
Are you looking for this?

![image](https://user-images.githubusercontent.com/18009293/61172144-fc4a2980-a556-11e9-853c-64e04ac5f3f7.png)

**Comment by razyalov** [comment]
Not sure. It is set on my deployment and still shows up. Does this affect the YouTube theme?

**Comment by DanielnetoDotCom** [comment]
If you are using the YouTube theme you must use the YouTube plugin

![image](https://user-images.githubusercontent.com/18009293/61182900-47744300-a610-11e9-9b2f-20cede80d36e.png)

**Comment by razyalov** [comment]
This worked. 

I think it will make sense to show the theme configuration option within the theme selection UI.

**Comment by DanielnetoDotCom** [comment]
I see, thanks we may add this in the future.
