### ISSUE TITLE
Inscrições 

### ISSUE THREAD

**Issue by PlayxPE** [DanielnetoDotCom/YouPHPTube#147]
Em breve  deixe disponível a contagem de inscrições para os visitantes

**Comment by DanielnetoDotCom** [comment]
Como assim?

**Comment by PlayxPE** [comment]
Desculpe o Google Tradutor está traduzindo errado 

Quero ver a contagem de inscrições de um canal sempre que entra nele

E possível você adicionar isso futuramente?

**Comment by DanielnetoDotCom** [comment]
Sim, é possível sim, só não está implementado ainda

Atenciosamente

Daniel Neto

PHP ZEND 4/5 Certified Engineer
PHP Zend Certification - Authentication
http://zend.com/zce.php?c=ZEND001318&r=209210010

Programming in HTML5 with JavaScript and CSS3 Specialist (MCP 70-480)
https://mcp.microsoft.com/authenticate/ValidateMCP.aspx
Transcript ID (1040640) and the Access Code (danielNeto)

**Comment by DanielnetoDotCom** [comment]
Sim, é possível sim, só não está implementado ainda

**Comment by PlayxPE** [comment]
Ok

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
