### ISSUE TITLE
 Warning! We have not found any videos or audios to show. 

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#1472]
Hi Daniel,

Please check below issue.
If i enable filterUserChannel after next video does not play in the second list
![filter](https://user-images.githubusercontent.com/35865505/52581588-8ffeb900-2e44-11e9-9fc8-f2544740e476.jpg)
![filter1](https://user-images.githubusercontent.com/35865505/52581604-95f49a00-2e44-11e9-8633-934824988df7.jpg)

Warning! We have not found any videos or audios to show.

**Comment by gujarraju** [comment]
Hello

**Comment by DanielnetoDotCom** [comment]
can you make the same thing on the demo site?

if you do let me know I will check there. thanks

**Comment by gujarraju** [comment]
Please check attached file.

[Video23.zip](https://github.com/DanielnetoDotCom/YouPHPTube/files/2873065/Video23.zip)

**Comment by DanielnetoDotCom** [comment]
I just sent a fix

[46a75eb](/DanielnetoDotCom/YouPHPTube/commit/46a75eb912da7e0c209bc98afe553e06d5065079)

**Comment by millzee01** [comment]
Hi can u advise fix for this please as this is happening on my test site as well.
