### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by inferno-prime** [DanielnetoDotCom/YouPHPTube#1473]
I just want to say a big thank you for making this script. And the fact that you are not forcing others to use 6 different tools but kindly only use one. I used to use clip bucket and I cant tell you how sad it is that they turned into money grubbers the script barely ever comes with any plugins. I mean I know you want to earn some on the side. 

Anyway a big thanks and I hope the script will always use the same tools (ffmpeg) and still be free with all the plugins.

**Comment by DanielnetoDotCom** [comment]
Thanks, I appreciate your words.

It helps me to keeping going.

**Comment by Andiweb87** [comment]
yes a big thanks for Daniel for this project , is to simple to use and evrything looks clean and modern, need also to give some more support for him, all this project cost time and money. thank you

**Comment by ChrisSlS** [comment]
Thanks to Daniel mainly, as well as contributors. This project will have allowed me to learn more, I love!

The most important thing is not money, but to share knowledge. So things go on, and beautiful things happen to us.

Thank you !

**Comment by DanielnetoDotCom** [comment]
@ChrisSlS @Andiweb87 @inferno-prime 

Thanks guys, I really appreciate your comments
