### ISSUE TITLE
current version cannot login 404 error

### ISSUE THREAD

**Issue by nfsiv** [DanielnetoDotCom/YouPHPTube#1474]
good day,

today, i reinstalled my youphptube, installation and configuration all working well, after the configuration done, i jump to the main page, it also find, but when i try to login, the browser says no such page.

my site is http://42.159.88.173/, click the login it will jump to http://42.159.88.173/user but not accessable.

do not know is my mistake or something not correct in the code.

thanks.

**Comment by SubjectXXX** [comment]
Seems like you didnt copy everything correctly.

Did you install it via git pull or archive?

**Comment by nfsiv** [comment]
i use the git clone to get the code, and compare with the github, directory structure and file size, i believe i copy everything already

**Comment by SubjectXXX** [comment]
two options then: 
1. something is borked with your access rights (chmod and chown solution for your apache user (you are on linux, right?)) to this folder
2. your config is not set up correctly.

Please copy your config (ommiting password ofc) here..

**Comment by DanielnetoDotCom** [comment]
do you have mod rewrite enabled?

**Comment by nfsiv** [comment]
thanks all, after a2enmod rewrite, i can see the login page.
