### ISSUE TITLE
Encoder can download from Youtube but can't upload files.

### ISSUE THREAD

**Issue by travisjayfloyd** [DanielnetoDotCom/YouPHPTube#1476]
Files won't even begin uploading when I try to upload a file.  I have tried both the dragging method and browse method.  The file shows up and says uploading but doesn't actually upload.  I checked the logs to see what was going on and nothing new appears when I try to upload from file.  I can upload from Youtube and it comes across perfectly and the Encoder log updates but when I try to upload from file nothing.  The screenshot I took was taken a couple of hours after I tried uploading the file.  Thank you for your help!  
![screen shot 2019-02-12 at 9 01 35 am](https://user-images.githubusercontent.com/42880409/52649406-85c0d700-2ea5-11e9-9f25-43bd8eafeb30.png)

**Comment by travisjayfloyd** [comment]
I just found out that it does show that it uploads if I go to upload file directly on the main page rather than going to the Encoder page.  However, it does just stick on saying encoding on the status.

**Comment by DanielnetoDotCom** [comment]
can you please check your log file?

**Comment by travisjayfloyd** [comment]
Yeah I have looked through it and can't see anything that looks like is error with file uploads but I might be missing something.  I am doing a long video from Youtube and it is working which you can probably see in the log but at the end I tried uploading the video both directly from my youphptube site and through the youphptube-encoder site. 
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2857198/youphptube.log)

**Comment by DanielnetoDotCom** [comment]
I could not see any error as well.

you need to try to grab the error at the upload time. delete this log and upload again.
also look for javascript errors

**Comment by travisjayfloyd** [comment]
So I cleared it then tried reupping it and this is all I get.  I did try both ways to see if anything would show up.  
[youphptube (2).log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2857455/youphptube.2.log)

**Comment by travisjayfloyd** [comment]
When I do a direct upload this is what shows up on the videos page.  
![screen shot 2019-02-12 at 1 06 43 pm](https://user-images.githubusercontent.com/42880409/52664771-2247a100-2ec7-11e9-9280-c325827995f7.png)

**Comment by DanielnetoDotCom** [comment]
I can not see any problem on YouPHPTube, check if you do not have a network problem. like, proxy, CDN, firewall, etc.

**Comment by travisjayfloyd** [comment]
So I switched over to the classic.htaccess and it seems to be working now.  Fingers crossed.  I will let you know if that works.  Thank you!
