### ISSUE TITLE
Pay-Per-View Videos

### ISSUE THREAD

**Issue by mrtick2002** [DanielnetoDotCom/YouPHPTube#1477]
On the Netflix clone demo, there is the option to purchase4 PPV access to videos, how did you set that up? Is it up the discretion of the content creator? How does the payment system work?

**Comment by DanielnetoDotCom** [comment]
Hi

The PPV is a new plugin, it was not on the market until now, I just add the PPV plugin on the plugins page https://www.youphptube.com/plugins/
It is a commercial plugin.

the discretion you can set it up editing the video and telling the R Rate

![image](https://user-images.githubusercontent.com/18009293/52787587-1b429f00-303d-11e9-8a2a-f912bdd98615.png)

Also, take a look at your customizedAdvanced options

![image](https://user-images.githubusercontent.com/18009293/52787684-5ba21d00-303d-11e9-9935-d93064a1757e.png)

**Comment by TTcam** [comment]
Where can I find out the details of the plugin?

**Comment by DanielnetoDotCom** [comment]
With The Pay-per-view (PPV) plugin you can let your users purchase exclusively contents for a certain amount of time.

you can define the price and how long it will take to expire

I will add this plugin on the demo site, so you can take a look at all its feature

**Comment by chinli12** [comment]
Please pay per view plugin need to upgrade, if user clicks on the video it should show user a link to purchase the video not asking the user to click on the above to add money to the wallet, some user will not understand it,

**Comment by DanielnetoDotCom** [comment]
for now, all purchases on the youphptube will require a wallet.

we may improve it to avoid some clicks
