### ISSUE TITLE
not show the thumbnails of the videos on the scrollable tape

### ISSUE THREAD

**Issue by codelabinf** [DanielnetoDotCom/YouPHPTube#1479]
Hi, I installed everything with the theme flatly and the netflix view but it does not show the thumbnails of the videos on the scrollable tape. Please, I need help with this. Thank you so much.

**Comment by DanielnetoDotCom** [comment]
I am not sure what is your problem but please try to update your files again, I just sent some fixes regarding images on Netflix

**Comment by codelabinf** [comment]
Hi, this is the problem:
![problema netflix theme](https://user-images.githubusercontent.com/33943401/52805857-45f51d80-3066-11e9-8458-1c1a9bbda0cb.png)

**Comment by DanielnetoDotCom** [comment]
did you update your files?

**Comment by codelabinf** [comment]
Yes, the files are updated, I deleted them and loaded them again one by one. Is this resolved by buying a plugin or should the free version work well? Thanks for your time.

**Comment by codelabinf** [comment]
If I buy a plugin, can I install it only in one youphptube server or can I install it on two or more? I have one of test and I want to put one in production.

**Comment by codelabinf** [comment]
Apologies, I forgot to say that there are videos uploaded in mp4 from my PC and videos imported from youtube but in all cases this happens in the same way

**Comment by DanielnetoDotCom** [comment]
@codelabinf that is a important info.
so videos from the encoder are in the same way?

On your netflix parameters screen, is landscapePosters checked or unchecked?

**Comment by codelabinf** [comment]
yes, the videos from the encoder are in the same way.

"On your netflix parameters screen, is landscapePosters checked or unchecked?"

I tried both ways and the result is the same.

**Comment by DanielnetoDotCom** [comment]
can you reproduce this error on demo site?

**Comment by codelabinf** [comment]
Hi, I could not reproduce the problem on the demo site. But I installed everything again this time on a real machine and not on a virtual one and now it works well. I also changed from linux mint to ubuntu server 18.04.2

**Comment by codelabinf** [comment]
In the photo that I attach where the cursor is seen instead of playing a video or gif there is a static photo. How can this be changed? Thank you
![foto2](https://user-images.githubusercontent.com/33943401/52956201-64605f00-336d-11e9-959b-48ec804f0759.png)

**Comment by DanielnetoDotCom** [comment]
maybe you are looking for a trailer.

edit your video and add a trailer on it.

**Comment by codelabinf** [comment]
Thank you so much

**Comment by codelabinf** [comment]
Hello, I could not change the color of the header (the place where the logo is displayed) and I need to change it to 0a2447 in the netflix theme. Is it possible to do that from a php file? Thanks for your help!

**Comment by DanielnetoDotCom** [comment]
try to do adding a CSS on the header 

site configuration->head code

**Comment by codelabinf** [comment]
Hi, I tried to do it but I could not, even in the online simulator, but neither. I did it using the code on this page:  https://work.smarchal.com/twbscolor/4.0.0/css/0a2447261ae8ecf0f1ecdbff1

The code is:

.navbar {
  background-color: #0a2447;
}
.navbar .navbar-brand {
  color: #ecf0f1;
}
.navbar .navbar-brand:hover,
.navbar .navbar-brand:focus {
  color: #ecdbff;
}
.navbar .navbar-text {
  color: #ecf0f1;
}
.navbar .navbar-text a {
  color: #ecdbff;
}
.navbar .navbar-text a:hover,
.navbar .navbar-text a:focus {
  color: #ecdbff; 
}
.navbar .navbar-nav .nav-link {
  color: #ecf0f1;
  border-radius: .25rem;
  margin: 0 0.25em;
}
.navbar .navbar-nav .nav-link:not(.disabled):hover,
.navbar .navbar-nav .nav-link:not(.disabled):focus {
  color: #ecdbff;
}
.navbar .navbar-nav .dropdown-menu {
  background-color: #0a2447;
  border-color: #261ae8;
}
.navbar .navbar-nav .dropdown-menu .dropdown-item {
  color: #ecf0f1;
}
.navbar .navbar-nav .dropdown-menu .dropdown-item:hover,
.navbar .navbar-nav .dropdown-menu .dropdown-item:focus,
.navbar .navbar-nav .dropdown-menu .dropdown-item.active {
  color: #ecdbff;
  background-color: #261ae8;
}
.navbar .navbar-nav .dropdown-menu .dropdown-divider {
  border-top-color: #261ae8;
}
.navbar .navbar-nav .nav-item.active .nav-link,
.navbar .navbar-nav .nav-item.active .nav-link:hover,
.navbar .navbar-nav .nav-item.active .nav-link:focus,
.navbar .navbar-nav .nav-item.show .nav-link,
.navbar .navbar-nav .nav-item.show .nav-link:hover,
.navbar .navbar-nav .nav-item.show .nav-link:focus {
  color: #ecdbff;
  background-color: #261ae8;
}
.navbar .navbar-toggle {
  border-color: #261ae8;
}
.navbar .navbar-toggle:hover,
.navbar .navbar-toggle:focus {
  background-color: #261ae8;
}
.navbar .navbar-toggle .navbar-toggler-icon {
  color: #ecf0f1;
}
.navbar .navbar-collapse,
.navbar .navbar-form {
  border-color: #ecf0f1;
}
.navbar .navbar-link {
  color: #ecf0f1;
}
.navbar .navbar-link:hover {
  color: #ecdbff;
}

@media (max-width: 575px) {
  .navbar-expand-sm .navbar-nav .show .dropdown-menu .dropdown-item {
    color: #ecf0f1;
  }
  .navbar-expand-sm .navbar-nav .show .dropdown-menu .dropdown-item:hover,
  .navbar-expand-sm .navbar-nav .show .dropdown-menu .dropdown-item:focus {
    color: #ecdbff;
  }
  .navbar-expand-sm .navbar-nav .show .dropdown-menu .dropdown-item.active {
    color: #ecdbff;
    background-color: #261ae8;
  }
}

@media (max-width: 767px) {
  .navbar-expand-md .navbar-nav .show .dropdown-menu .dropdown-item {
    color: #ecf0f1;
  }
  .navbar-expand-md .navbar-nav .show .dropdown-menu .dropdown-item:hover,
  .navbar-expand-md .navbar-nav .show .dropdown-menu .dropdown-item:focus {
    color: #ecdbff;
  }
  .navbar-expand-md .navbar-nav .show .dropdown-menu .dropdown-item.active {
    color: #ecdbff;
    background-color: #261ae8;
  }
}

@media (max-width: 991px) {
  .navbar-expand-lg .navbar-nav .show .dropdown-menu .dropdown-item {
    color: #ecf0f1;
  }
  .navbar-expand-lg .navbar-nav .show .dropdown-menu .dropdown-item:hover,
  .navbar-expand-lg .navbar-nav .show .dropdown-menu .dropdown-item:focus {
    color: #ecdbff;
  }
  .navbar-expand-lg .navbar-nav .show .dropdown-menu .dropdown-item.active {
    color: #ecdbff;
    background-color: #261ae8;
  }
}

@media (max-width: 1199px) {
  .navbar-expand-xl .navbar-nav .show .dropdown-menu .dropdown-item {
    color: #ecf0f1;
  }
  .navbar-expand-xl .navbar-nav .show .dropdown-menu .dropdown-item:hover,
  .navbar-expand-xl .navbar-nav .show .dropdown-menu .dropdown-item:focus {
    color: #ecdbff;
  }
  .navbar-expand-xl .navbar-nav .show .dropdown-menu .dropdown-item.active {
    color: #ecdbff;
    background-color: #261ae8;
  }
}

.navbar-expand .navbar-nav .show .dropdown-menu .dropdown-item {
  color: #ecf0f1;
}
.navbar-expand .navbar-nav .show .dropdown-menu .dropdown-item:hover,
.navbar-expand .navbar-nav .show .dropdown-menu .dropdown-item:focus {
  color: #ecdbff;
}
.navbar-expand .navbar-nav .show .dropdown-menu .dropdown-item.active {
  color: #ecdbff;
  background-color: #261ae8;
}


Thank you for your time and apologies for so many questions.

**Comment by codelabinf** [comment]
Finally I could solve it, I used this command: find /var/www/html/YouPHPTube/ -name *.* -exec sed -i 's/2c3e50/0a2447/g' {} \;

sed: Stream EDitor
    -i: in-place, in the place
    s: command replace
    2c3e50: source chain, to replace
    0a2447: destination chain
    g: global, replaces all occurrences of the source chain by destination
    *.*: text file in which to search and replace, in this case in all, you can specify: * .php, * .ini * .css * .txt, etc.

and I could change the color for the one I needed. Thank you so much!!!!
