### ISSUE TITLE
Strict standards: Static function Object::getTableName() should not be abstract

### ISSUE THREAD

**Issue by Syedwaheed** [DanielnetoDotCom/YouPHPTube#148]
hi,
Can anyone of you help me with this. I m getting the above error after installing it locally.
![capture](https://user-images.githubusercontent.com/14071753/31546130-817a07a0-b03b-11e7-90ba-d97ad439562b.JPG)

**Comment by DanielnetoDotCom** [comment]
Please I Just release a fix that may resolve this problem, can u please update with newer files?

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
