### ISSUE TITLE
VideoTags

### ISSUE THREAD

**Issue by TLCReuver** [DanielnetoDotCom/YouPHPTube#1480]
Hi Daniel,

Is the plugin "VideoTag" operational ? 
If yes, how to enable/select these tags ?

![videotags](https://user-images.githubusercontent.com/39981177/52748866-f112c200-2fe7-11e9-9cc2-def10ea4483d.jpg)

**Comment by DanielnetoDotCom** [comment]
Yes, it is. are you facing any problem

**Comment by TLCReuver** [comment]
How to add Tag "112" to this video example ? There is an input field under "112" but i don't know what to put  into that field to enable tag 112 for this video.

**Comment by DanielnetoDotCom** [comment]
You just type something and press enter
it should turn into a blue text.

**Comment by TLCReuver** [comment]
Thanks for reply

I've done that but in don't see the tags in the Video like YouTube or does it work on a different way ?
![snap2](https://user-images.githubusercontent.com/39981177/52862761-4c52ca80-3136-11e9-9134-c1e06f9ec431.jpg)

**Comment by Andiweb87** [comment]
yes is a good idea to show them under the video.

**Comment by TLCReuver** [comment]
It work perfect.
Thank you very very much for the fast update.

![snap1](https://user-images.githubusercontent.com/39981177/52912333-539de380-32b0-11e9-8a1f-13fab8525173.jpg)

**Comment by TLCReuver** [comment]
Hi Daniel,

Before i/ going to tag 2000 video files i have a last question about it;
How many tag phrases can be stored in each Tag Type and how many Tag Types can be made ?

Thanks for reply & i'm very very happy with this feature.

**Comment by DanielnetoDotCom** [comment]
It is unlimited
