### ISSUE TITLE
landing page is broken

### ISSUE THREAD

**Issue by guldam1234** [DanielnetoDotCom/YouPHPTube#1482]
I have succeeded in installing youPHPtube, but the landing page I saw is broken like below
![2019-02-14 18-22-29](https://user-images.githubusercontent.com/47220576/52776828-caa36400-3085-11e9-96ec-4cec99985493.png)

How can i proceed?

**Comment by DanielnetoDotCom** [comment]
Not sure what is, make sure you have mod rewrite enabled.
and also check your configuration.php file

**Comment by SubjectXXX** [comment]
And /videos/youphptube.log of course..

**Comment by Puyodead1** [comment]
same problem on fresh install, log file:
```[15-Feb-2019 20:31:21 America/New_York] PHP Warning:  require_once(/var/www/html/YouPHPTube/plugin/Customize/Objects/ExtraConfig.php): failed to open stream: No such file or directory in /var/www/html/YouPHPTube/view/include/head.php on line 6
[15-Feb-2019 20:31:21 America/New_York] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/YouPHPTube/plugin/Customize/Objects/ExtraConfig.php' (include_path='.:/usr/share/php') in /var/www/html/YouPHPTube/view/include/head.php on line 6
```

**Comment by Puyodead1** [comment]
another fresh install on older commit doesnt have a log file and has a browser error 
![image](https://user-images.githubusercontent.com/14828766/52892635-3e1aa380-3162-11e9-96de-270e4e7eb8ac.png)

**Comment by DanielnetoDotCom** [comment]
Looks like you are missing files from plugin Customize

**Comment by guldam1234** [comment]
Thank you for your kind attention. I have solved my problem by just downgrading to Linux 16.04 LTS and install corresponding youPHPTube..

**Comment by DanielnetoDotCom** [comment]
I am glad it works, but it was a strange solution
