### ISSUE TITLE
Show a white square instead of the gif or a png with a video capture in Netflix Theme

### ISSUE THREAD

**Issue by codelabinf** [DanielnetoDotCom/YouPHPTube#1484]
Hi, this is the problem:
![imagen](https://user-images.githubusercontent.com/33943401/52808480-bd2db000-306c-11e9-8bc2-a658ce91947b.png)

**Comment by DanielnetoDotCom** [comment]
it is in another post https://github.com/DanielnetoDotCom/YouPHPTube/issues/1479
