### ISSUE TITLE
SMTP Not Working 

### ISSUE THREAD

**Issue by mrtick2002** [DanielnetoDotCom/YouPHPTube#1485]
I am trying to figure out the problem with email notifications. I am using AWS SES for email sending, but I can't seem to get it to work. I changed the site email to match the domain, but that didn't help either.

Also, I have tried to change themes a few times but the captcha code will not show using any of them. 

Trying to recover password - http://prntscr.com/ml6tho

Trying to send test email - http://prntscr.com/ml6wft

**Comment by SubjectXXX** [comment]
Could be lots of things.

For start, I dont think AWS SES supports SMTP login?

Why using paying mail option when there is multiple free ones?

**Comment by DanielnetoDotCom** [comment]
For myself I use mailgun

they offer 10K free email/month

**Comment by KenRHill** [comment]
Daniel, 

Do you have a tutorial for setting up YouPHPTube with SMTP using Mailgun?

**Comment by DanielnetoDotCom** [comment]
Sorry, I do not have it. I did it a while ago and it was very simple
