### ISSUE TITLE
file name contain none English char will be messy

### ISSUE THREAD

**Issue by nfsiv** [DanielnetoDotCom/YouPHPTube#1486]
good day Daniel,

yesterday i rebuild my YPT platform, last night i tried to upload some videos, with all English file name is OK, but if file name contains non english or all not in english, the non english part will become messy for example:

file name "open TCP 16000 port for ASA.avi" will be always correct.
file name "ASA开通TCP16000.avi“ the title of the video will become "ASAå¼éTCP16000"

at beginning i think maybe because of default locale is us, but even i change to cn, it will still be messy. and all translations can be displayed correctly.

i am not quite sure if something i forget to do, please help. thanks

**Comment by nfsiv** [comment]
an update.
i went to "CustomizeAdvanced" plugin, i found utf8encode and utf8decode were checked, i tried un-check those, the file name can be displayed correctly. 

but the day before yesterday, even above 2 checked, file name also can be correct.

and i do not know if other language, please other country help to check

**Comment by SubjectXXX** [comment]
Did you try to upload them directly or via encoder?

**Comment by nfsiv** [comment]
i upload the video via encoder, which is another server.

**Comment by SubjectXXX** [comment]
Problem could be on another server, does it support utf8 encoding? That server was probably update and not reconfigured or something like that..

**Comment by nfsiv** [comment]
actually, these 2 server are same config, all come from default Azure images, nothing changed, by locale command, i can see C.UTF-8 is there and the day before yesterday the locale output are same.
