### ISSUE TITLE
Migrando site

### ISSUE THREAD

**Issue by PlayxPE** [DanielnetoDotCom/YouPHPTube#149]
Estou migrando meu site para outra vps e queria saber quais pastas devo salvar 

Tirando

Videos
E o banco de dados

**Comment by DanielnetoDotCom** [comment]
isso mesmo, depois confere o arquivo videos/configuration.php

**Comment by PlayxPE** [comment]
Beleza

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
