### ISSUE TITLE
I cant create Category in Bangla Language 

### ISSUE THREAD

**Issue by jamalmahmud** [DanielnetoDotCom/YouPHPTube#1490]
Hello , 

I can easily create category in english . But i want to make this website in Bangla language and problem is i cant create Category in Bangla like - শিরক , বিদআত, সুন্নাহ, তাওহীদ   । ইত্যাদি 

Can u please check this issues for me . ?

**Comment by jamalmahmud** [comment]
Hello ,

I can easily create category in english . But i want to make this website in Bangla language and problem is i cant create Category in Bangla like - শিরক , বিদআত, সুন্নাহ, তাওহীদ । ইত্যাদি

Can u please check this issues for me . ?

admin
123
website https://hilfulfuzul.tv/

**Comment by DanielnetoDotCom** [comment]
Mabe I know what it is

check the clean name, it must be unique.

try to manually enter a clean name with no special chars 

![image](https://user-images.githubusercontent.com/18009293/52952370-13e40400-3363-11e9-97da-100590ef28f1.png)

**Comment by DanielnetoDotCom** [comment]
Also I am sendig a fix for it
