### ISSUE TITLE
Works very well overall, but here's one small issue

### ISSUE THREAD

**Issue by Tarrantx** [DanielnetoDotCom/YouPHPTube#1491]
After settling with my initital setup, YouPHPtube has been working well for our organisation for a few months now.

Some things fail to transcode, but direct upload works in these cases.

With I could get Ldap working, but it's not necessary.

Our setup hangs when using the wrong password.  It doesn't hit an error screen, just lags...

Otherwise this is a really great peice of open source software.  The issues here suggest it is buggy, and maybe it is a bit but, overall it is very well done and very reliable.  

Along with others, this is now a must have server for me.

**Comment by SubjectXXX** [comment]
For debugging your login issue, have you checked logs?
