### ISSUE TITLE
Backblaze vs. Wasabi

### ISSUE THREAD

**Issue by soapstreams** [DanielnetoDotCom/YouPHPTube#1492]
Which is better? I saw in a thread last year that Daniel Neto said that the problem with Wasabi is that the connection is unstable. Is that a problem with Backblaze as well? Has the issue with Wasabi been worked out or is the stream still unstable? If you were running a VoD site using YouPHPTube, but storing videos with a 3rd party like Backblaze or Wasabi, which would you pick? Is there an alternate S3-compliant storage company you'd recommend? Thanks.

**Comment by soapstreams** [comment]
Additionally, do either of these options allow for bulk uploads? For example, can I place multiple video files into a bucket at either Backblaze or Wasabi and have them available at my site or do I have to manually link each individual file? Thanks.

**Comment by soapstreams** [comment]
Is there any way you can install these plugins on your demo so users can try it out for themselves? I am not sure which to buy and would like to check each one before making a decision. Thanks.

**Comment by DanielnetoDotCom** [comment]
**BackBlaze B2**

1. Stability - OK
2. Video Play -Bad,  when you try to skip a video on the timeline, for example, if you scape from 5 seconds to 4 min, looks like the script tries to download all video to play it. 
3. Price - OK

**Wasabi S3**

1. stability - Bad, fail almost everyday
2. videos play - Ok
3. price - Very Nice

**AWS S3**

1. stability - Ok
2. videos play - Ok
3. price - Bad


There is a new video format that YouPHPTube supports but it is not on the market yet.
it is the HLS format, this format will resolve the skipping problem on Backblaze.

**Comment by soapstreams** [comment]
3 questions:

1. Is the problem you describe with Backblaze and Wasabi related to volume or stream quality? In other words, if one person streams a video it is fine, but if a 100 try it skips or fails?

2. Are you aware of any s3 compliant alternatives that are better?

3. How long before HLS is available?

Thanks..

**Comment by DanielnetoDotCom** [comment]
1. The skip problems happen 100% of the time if the video is MP4. the wasabi offline problem happen 10% of the time
2. now I used only AWS and Wasabi
3. I am not sure, The HLS video will be a commercial plugin for 60 USD but if you want earlier access I can sell you now, and help you to configure the Backblaze solution with it.

**Comment by soapstreams** [comment]
I don't see the HLS plugin available right now. All my videos are mp4 files--will I need to convert them to HLS? Or does the site push mp4 from Backblaze, then stream over my site in HLS? Will I need to buy both the HLS plugin and the Backblaze plugin? Or just the HLS plugin that works with Backblaze? Thanks.

**Comment by DanielnetoDotCom** [comment]
As I said the HLS plugin is not available for sale yet, but you can get it from me.

you will need to send all your files to the encoder, and It will be encharged of encoding your MP4 files to HLS

HLS, for now, can only be stored on Local or on BackBlaze, yes you will need to get both plugins

**Comment by soapstreams** [comment]
Is there any way you can set it up on your demo site so I can try it and see how it streems?

**Comment by DanielnetoDotCom** [comment]
you have the HLS and the Backblaze plugin on the demo, you can try to set up your account there to see how it works

**Comment by soapstreams** [comment]
Can this be set up such that when any user uploads a video to my site, it automatically gets stored in a bucket at Backblaze (or Wasabi, if necessary)? If not, can the plugin be adapted to do this? Obviously, the biggest hurdle most users have is paying for storage. Backblaze is quite affordable at only one-half a cent per GB per month, and no more than 2 cents for every 5,000 API calls. I can afford Backblaze cloud storage and a VPS to host the stie, but it gets expensive paying for local storage of video files. Thanks.

**Comment by soapstreams** [comment]
Unable to log into your demo site as admin to test backblaze app settings.

**Comment by DanielnetoDotCom** [comment]
Hi, 

"automatically gets stored in a bucket at Backblaze"
this is exactly how works, after encoding HLS, it will be submitted to backblaze.

About the credentials, some times users change the password. but we reset this site 4 times a day, can you please try again?
