### ISSUE TITLE
Twitter Login Issue

### ISSUE THREAD

**Issue by JoshWho** [DanielnetoDotCom/YouPHPTube#1493]
I created my Twitter app for the login and when I add the callback url https://www.joshwhotv.com/objects/login.json.php?type=Twitter

Twitter says queries are not allowed.

If I just use my domain I get a message that says 

Signed API request has returned an error. HTTP error 403. Raw Provider API response: <?xml version=1.0 encoding=UTF-8?><errors><error code=415>Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>.

SO what are you supposed to use?

**Comment by DanielnetoDotCom** [comment]
try to google it, but it is probably because you didnt put your call back URL on our twitter API

**Comment by JoshWho** [comment]
![0](https://user-images.githubusercontent.com/39392449/52970900-1e11fc80-337b-11e9-8551-efba05ae932a.png)
![1](https://user-images.githubusercontent.com/39392449/52970902-1e11fc80-337b-11e9-834d-b506ac5b9f69.png)
![download](https://user-images.githubusercontent.com/39392449/52970904-1eaa9300-337b-11e9-9904-7e151fb05e74.png)

**Comment by DanielnetoDotCom** [comment]
on twitter remove the query parameter "?type=Twitter"

**Comment by JoshWho** [comment]
TY Daniel. Problem SOLVED.
![3](https://user-images.githubusercontent.com/39392449/52978667-dcdc1580-3397-11e9-8665-acdefb51ed35.png)
