### ISSUE TITLE
Reception email

### ISSUE THREAD

**Issue by charliedaps1** [DanielnetoDotCom/YouPHPTube#1496]
Hello,

Since a few days the sending of mail does not seem to work.

The sending of the mail test works perfectly.

But when a new user registers, he does not receive the validation email.

Same problem regarding the request when the password is lost.

Do you have an idea ?

Thank you

**Comment by SubjectXXX** [comment]
What does logs say?

**Comment by charliedaps1** [comment]
Hello,

Thanks for your anwser.

I do 

tail -n 200 -f /var/www/YouPHPTube/videos/youphptube.log

in putty 

I receive a error "No such file or directory"

Thanks for your help

**Comment by SubjectXXX** [comment]
search for php logs, mail logs, usually in /var/logs/

**Comment by charliedaps1** [comment]
There is many files.

I take the mail.log

A part of the file

`Feb 18 06:31:24 snp postfix/smtpd[23701]: disconnect from unknown[185.234.XXX.XX] helo=1 commands=1
Feb 18 06:31:35 snp postfix/smtpd[23701]: connect from WimaxUser36210-18.wateen.net[110.36.210.18]
Feb 18 06:31:36 snp postfix/smtpd[23701]: lost connection after EHLO from WimaxUser36210-18.wateen.net[110.36.210.18]
Feb 18 06:31:36 snp postfix/smtpd[23701]: disconnect from WimaxUser36210-18.wateen.net[110.36.210.18] ehlo=2 starttls=1 commands=3
Feb 18 06:33:28 snp postfix/smtpd[23776]: connect from unknown[185.234.217.188]
Feb 18 06:33:28 snp postfix/smtpd[23776]: lost connection after AUTH from unknown[185.234.217.188]
Feb 18 06:33:28 snp postfix/smtpd[23776]: disconnect from unknown[185.234.217.188] ehlo=1 auth=0/1 commands=1/2
Feb 18 06:36:43 snp postfix/anvil[23539]: statistics: max connection rate 1/60s for (smtp:185.234.217.188) at Feb 18 06:26:43
Feb 18 06:36:43 snp postfix/anvil[23539]: statistics: max connection count 1 for (smtp:185.234.217.188) at Feb 18 06:26:43
Feb 18 06:36:43 snp postfix/anvil[23539]: statistics: max cache size 2 at Feb 18 06:29:06
Feb 18 06:38:17 snp postfix/smtpd[24004]: connect from unknown[185.234.217.222]
Feb 18 06:38:19 snp postfix/smtpd[24004]: lost connection after AUTH from unknown[185.234.217.222]
Feb 18 06:38:19 snp postfix/smtpd[24004]: disconnect from unknown[185.234.217.222] ehlo=1 auth=0/1 commands=1/2
Feb 18 06:41:39 snp postfix/anvil[24006]: statistics: max connection rate 1/60s for (smtp:185.234.217.222) at Feb 18 06:38:17
Feb 18 06:41:39 snp postfix/anvil[24006]: statistics: max connection count 1 for (smtp:185.234.217.222) at Feb 18 06:38:17
Feb 18 06:41:39 snp postfix/anvil[24006]: statistics: max cache size 1 at Feb 18 06:38:17

`

Many thanks

**Comment by SubjectXXX** [comment]
Well, I always suggest renaming log file and triggering errors again. This is the way to get fresh log file and you always know that it really was an error that you triggered..

As far as log is concerned, that unkown is strange. Did you double check the config? Did you update ypt recently?

**Comment by charliedaps1** [comment]
Thanks for the advise.  I do that.

Yes update yesterday.

Config OK.  I receive the test mail.

**Comment by SubjectXXX** [comment]
Do you save after testing email?

**Comment by charliedaps1** [comment]
Yes i save.

I find a another problem.

When you try to reset the password, there is this information.

"Recover password could not be saved!"

**Comment by charliedaps1** [comment]
There is the last log

`
Feb 18 06:54:23 snp postfix/smtpd[24727]: connect from unknown[185.234.217.222]
Feb 18 06:54:23 snp postfix/smtpd[24727]: lost connection after AUTH from unknown[185.234.217.222]
Feb 18 06:54:23 snp postfix/smtpd[24727]: disconnect from unknown[185.234.217.222] ehlo=1 auth=0/1 commands=1/2
Feb 18 06:55:05 snp postfix/pickup[24213]: C37EF14F60482: uid=33 from=<contact@snp.tv>
Feb 18 06:55:05 snp postfix/cleanup[24761]: C37EF14F60482: message-id=<6cd9e12758054c24f5b066bd1ad13d74@www.snp.tv>
Feb 18 06:55:05 snp postfix/qmgr[543]: C37EF14F60482: from=<contact@snp.tv>, size=1084, nrcpt=1 (queue active)
Feb 18 06:55:49 snp postfix/smtp[24763]: C37EF14F60482: to=<contact@snp.tv>, relay=mail.snp.tv[185.61.154.25]:25, delay=44, delays=0.13/0.01/21/23, dsn=2.0.0, status=sent (250 OK id=1gvhWV-002k5d-R7)
Feb 18 06:55:49 snp postfix/qmgr[543]: C37EF14F60482: removed
Feb 18 06:57:43 snp postfix/anvil[24729]: statistics: max connection rate 1/60s for (smtp:185.234.217.222) at Feb 18 06:54:23
Feb 18 06:57:43 snp postfix/anvil[24729]: statistics: max connection count 1 for (smtp:185.234.217.222) at Feb 18 06:54:23
Feb 18 06:57:43 snp postfix/anvil[24729]: statistics: max cache size 1 at Feb 18 06:54:23
Feb 18 06:58:35 snp postfix/smtpd[24874]: connect from unknown[185.234.217.188]
Feb 18 06:58:35 snp postfix/smtpd[24874]: lost connection after AUTH from unknown[185.234.217.188]
Feb 18 06:58:35 snp postfix/smtpd[24874]: disconnect from unknown[185.234.217.188] ehlo=1 auth=0/1 commands=1/2
`

**Comment by SubjectXXX** [comment]
Try looking into this: connect from unknown[185.234.217.222]

**Comment by charliedaps1** [comment]
It's Ireland IP adress and i'm not in Ireland but may be the VPS.  I don't know.

**Comment by SubjectXXX** [comment]
What do you enter as SMTP host?
Do you use AUTH?

Its really really strange, that youphptube.log doesnt pick up this errors tho..

**Comment by charliedaps1** [comment]
I don't changing the configuration and before the update, it works.

Auth
SSL
465
And all information.

I receive the test mail in my box.

**Comment by DanielnetoDotCom** [comment]
if the youphptube.log does not exist it is already one problem.
check the directory and file permissions

**Comment by charliedaps1** [comment]
Hi Daniel,

The video directory is 755

Can you give more information please?

Thanks

**Comment by DanielnetoDotCom** [comment]
I can not tell you what is wrong, but the log file must exists

**Comment by charliedaps1** [comment]
OK thanks
