### ISSUE TITLE
Top Menu does not stay open

### ISSUE THREAD

**Issue by datasurgeservers** [DanielnetoDotCom/YouPHPTube#1497]
Hi,

On my site, the menu does not stay open on the left side. You have to keep clicking the menu drawer icon on the upper left to expand the menu. I believe the menu should always stay open, kind of like YouTube. Or at least have an option to pin the menu so it stays open.

**Comment by Andiweb87** [comment]
you can choose to use the YouTube (YouTube) view with left menu open, is in the plugin section is the last plugin.

**Comment by Andiweb87** [comment]
https://snag.gy/EF2toJ.jpg

**Comment by datasurgeservers** [comment]
I only see the YouTube view, not YouTube with left menu open.

**Comment by Andiweb87** [comment]
can you send a link

**Comment by Andiweb87** [comment]
activate the youtube view

**Comment by datasurgeservers** [comment]
https://streaming.datasurgeservers.com

**Comment by Andiweb87** [comment]
can you check in the plugins maybe is another view like Gallery activatet >??  if yes deactivate.

**Comment by datasurgeservers** [comment]
I installed a fresh copy of everything on another server to test, and get the same results.

**Comment by DanielnetoDotCom** [comment]
what is your screen resolution?

try a larger screen resolution
