### ISSUE TITLE
Issue with redirecting videos save path

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1498]
I tried following your guide how to move bulk folder with videos somewhere else: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Can-I-store-my-videos-in-another-location%3F

and suddenly, page stopped working (I moved files and created link from /var/www/html/YouPHPTube/videos to /www/videos). 

OK, there is a config moved to another folder, altough linked, if I typed my domain name where page resides, it redirected to https://my.domain.name/www/user which returned 404. 
I had to remove 

    ".$subDir" 
in 

    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir; 
line in configuration.php, but then it pointed to https://my.domain.nameuser. OK, I added ".'/'" in the same line and now it works..

**Could there be any other problems down the timeline because of this bug?**

**Comment by DanielnetoDotCom** [comment]
Sorry, it was not clear for me, is it working or not?

**Comment by SubjectXXX** [comment]
Its working now, but I had to change some more stuff to get it working. Maybe mention this in your tutorial, that I linked or fix it in core, that it does not depend a folder path (which is really really strange if you ask me..).

**Comment by DanielnetoDotCom** [comment]
I see, I will think of something. probably fix the code

**Comment by thaidh1907** [comment]
> Its working now, but I had to change some more stuff to get it working. Maybe mention this in your tutorial, that I linked or fix it in core, that it does not depend a folder path (which is really really strange if you ask me..).

Hi bro, can you tell me ? how to fix it ?

**Comment by SubjectXXX** [comment]
The solution is in OP..
