### ISSUE TITLE
Add origin of video

### ISSUE THREAD

**Issue by Knah-Tsaeb** [DanielnetoDotCom/YouPHPTube#15]
When a video is download from other site, i would like to show the origin of video.

Maybe after the description like :
Origin : https://otherSite.com/video=#4587911

**Comment by DanielnetoDotCom** [comment]
Hi

Thanks for your comment.
We show the video origin only on My Videos.
![image](https://cloud.githubusercontent.com/assets/18009293/26111761/60abdccc-3a2c-11e7-8deb-945afe83cafc.png)


The URL  https://otherSite.com/video=#4587911 didnt open. But anyway, we always try to make the layout youtube like. but you can add the source on the video comments

**Comment by Knah-Tsaeb** [comment]
Yeah, i see you save a url of video in database. A option for show or not link, directly under a video without manually add source of video in description can be nice.

A option like : 
Always show the video origin (if video come from other site) [ ]

**Comment by DanielnetoDotCom** [comment]
I will work for the next release this opption be on the road

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
