### ISSUE TITLE
Livestream autostrat

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#150]
![bildschirmfoto 2017-10-14 um 20 38 50](https://user-images.githubusercontent.com/30271757/31578368-38e12c18-b120-11e7-82ac-19695bdcb1d8.png)

I still have not found how to start the stream automatically a visit must always click play?

**Comment by nightstryke** [comment]
You mean auto play on page load? Maybe ask if @DanielnetoDotCom can make that a feature?

**Comment by DanielnetoDotCom** [comment]
Try to turn on the autoplay option on configuration

![image](https://user-images.githubusercontent.com/18009293/31610389-3fba551c-b24e-11e7-815f-e391ecdc0482.png)

**Comment by mikweb2017** [comment]
Thanks
