### ISSUE TITLE
Number of views does not work for short videos

### ISSUE THREAD

**Issue by angelawong** [DanielnetoDotCom/YouPHPTube#1500]
I have a video that is 56 seconds long. When people replay it, the number of views does not change. For longer videos, the counter works fine. Is it because the video is too short? If I block my site's cookie from on my computer, then the counter for the short video works as normal. Is there a way to get the counter to work normally without having to mess with browser cookies? Any help would be most appreciated.

**Comment by DanielnetoDotCom** [comment]
I really do not know about it

can you upload this video to demo site and check if the same happens?

**Comment by angelawong** [comment]
Daniel, thanks. I just realized that I did ask the same question a few months ago. I will try to upgrade the application to see whether the problem will be resolved. What I did not know is that when I click on the version of the application, it tells me that I have the latest version. The version I have is 5.03 but I realized that it is now up to 5.6. Why the discrepancy? The other thing I noticed this morning is that I could not sign in. All I see on the page are the words, "Please sign in" without any text boxes for me to actually put my username and password. Do you know what may be happening here?

**Comment by DanielnetoDotCom** [comment]
Hi

did you follow this to update? https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

actually, the version now is 6.6

also, check the log file and if you have some commercial plugins you may need to update them as well

**Comment by angelawong** [comment]
No, I did not follow the update because every time I go to see whether my application needed to be updated, it would tell me that I have the latest version. That is why I thought I was up to date. I had no idea it had already gone up to version 6.6. Perhaps for now the best thing to do for me is to do a new installation because I am so many version behind.

**Comment by DanielnetoDotCom** [comment]
you can not skip updates.

is possible to keep all your files and make updates, so a new installation is not mandatory.

what is your domain name?

if you still having errors check your log file

**Comment by angelawong** [comment]
I have decided to do a new install as it would be a lot quicker and more efficient for me since I don't have many videos online. The new version looks great and the count issue seemed to have resolved itself. I do have one more question though. Is there a way for me to remove the subscribe button? Thanks so much.

**Comment by DanielnetoDotCom** [comment]
sorry, we do not have this option yet
