### ISSUE TITLE
what is php file for landing page?

### ISSUE THREAD

**Issue by guldam1234** [DanielnetoDotCom/YouPHPTube#1501]
I would like to make, whenever the user leave the landing page, a snipet of javascript code is executed,

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>
window.onbeforeunload = function() {
################################something
}
</script>

However, I am struggling to find where to insert my code snipet.. can anybody help me to figure out?
thanks.

**Comment by DanielnetoDotCom** [comment]
try site configuration -> code -> head code

**Comment by guldam1234** [comment]
what/where is site configuration?

**Comment by DanielnetoDotCom** [comment]
it is on the left menu

![image](https://user-images.githubusercontent.com/18009293/53099260-2c3f5480-3504-11e9-8cab-1b6c29f14a2c.png)
