### ISSUE TITLE
Video upload menu  on main index page issue

### ISSUE THREAD

**Issue by datasurgeservers** [DanielnetoDotCom/YouPHPTube#1502]
Hi Daniel,

I am not sure if this is a global thing with everyone, but if I deselect options in the site configurations to stop people from importing/embedding, etc. it works fine on all pages except the main index page. Index page shows all options, where other pages show just the options I want it to show.

**Comment by DanielnetoDotCom** [comment]
maybe it is cached, check in another browser to see if it persist.

**Comment by datasurgeservers** [comment]
Tried 2 other browsers with the same result

**Comment by DanielnetoDotCom** [comment]
do you have cache plugin enabled?

can you reproduce it on demo site?

**Comment by datasurgeservers** [comment]
Cache plugin is and has been disabled.

**Comment by DanielnetoDotCom** [comment]
can you reproduce on demo site?
