### ISSUE TITLE
not permitted

### ISSUE THREAD

**Issue by moses268** [DanielnetoDotCom/YouPHPTube#1506]
how do i make the plugin dir writable before upload
the code        chown www-data:www-data /var/www/html/YouPHPTube/plugin && chmod 755 /var/www/html/YouPHPTube/plugin               is not working it keep saying operation not permitted

**Comment by DanielnetoDotCom** [comment]
even if it say it is not permitted, did you try to upload?

what about manually upload the plugin files, using FTP?

**Comment by moses268** [comment]
When I check the upload option that's the message that comes up

**Comment by DanielnetoDotCom** [comment]
what about upload using FTP?

**Comment by moses268** [comment]
Not sure how to do that. I will check Google to see. All the coding I know
was learnt during the setting up process of this website

**Comment by DanielnetoDotCom** [comment]
do you have FTP or SFTP access to your site?

check it with your server provider.

**Comment by moses268** [comment]
I am using aws. Will check

**Comment by DanielnetoDotCom** [comment]
you probably can use SFTP with the same SSH credentials

**Comment by moses268** [comment]
Ok noted. Will try it in a while
