### ISSUE TITLE
Live Streaming Page Won't Load

### ISSUE THREAD

**Issue by nightstryke** [DanielnetoDotCom/YouPHPTube#1508]
So I was running YouPHPTube 6.4,
I pulled the master from github updated to 6.5 and then to 6.6 but now when I click the red LIVE button it doesn't load the page I get a constant loading error that eventually ends up to an Error 503.

Help!

**Comment by DanielnetoDotCom** [comment]
is your live plugin updated? what version are you using?

![image](https://user-images.githubusercontent.com/18009293/53165723-2c962900-35b2-11e9-8c9c-73aacdd02deb.png)

**Comment by nightstryke** [comment]
It is turned on and it's the version  you have listed.
I have nginx and the live chat running so I have no idea why it's not working.

**Comment by nightstryke** [comment]
Alright weird, I updated overwrote existing files with ones from the lastest GitHub Master and it works now.

**Comment by oclwppri** [comment]
I have the same issue, when  click on live button on the top menu it looping my website and make it down.

**Comment by oclwppri** [comment]
Can you take a look on napgade.com ?

**Comment by DanielnetoDotCom** [comment]
@oclwppri  check your log file
