### ISSUE TITLE
Monetize Users

### ISSUE THREAD

**Issue by Andiweb87** [DanielnetoDotCom/YouPHPTube#1509]
Hi Daniel seems this plugin is not working or have na issue, because i open a video and nothing change in my wallet, same in demo site.

thank you

**Comment by DanielnetoDotCom** [comment]
maybe because you used the admin user

**Comment by Andiweb87** [comment]
i try also with simple user is same

**Comment by datasurgeservers** [comment]
I have a suggestion with this plugin. I found that users can just watch their own videos to gain currency in their wallets. Is it possible to create a option that disallows the increase in the user's wallet if the person watching the video is the author of said video?

**Comment by Andiweb87** [comment]
Is work in your site this plugin ? i mean is incrasing when you see a video ??

**Comment by datasurgeservers** [comment]
Andiweb87: Yes, mine is working just fine.

**Comment by Andiweb87** [comment]
can i see it ? if is not  a problem for you. thank you

**Comment by datasurgeservers** [comment]
![image](https://user-images.githubusercontent.com/47656663/53187997-5e1eec80-35d2-11e9-89e6-1d887fba8970.png)

**Comment by Andiweb87** [comment]
ok , i have created an account in your site and open some video , my wallet is 0.00 like the screenshot i made

https://snag.gy/8UR7y2.jpg

**Comment by datasurgeservers** [comment]
Right, because you do not own the video. The person who owns the video gets the increase in the wallet.

**Comment by datasurgeservers** [comment]
And I see the increase in my non-admin account which owns the videos you viewed.
