### ISSUE TITLE
The requested URL /YouPHPTube/user was not found on this server.

### ISSUE THREAD

**Issue by rimer10** [DanielnetoDotCom/YouPHPTube#1511]
i read this all 

#1125 
#763 
#872 
#979 same issue 
how to resolve my os ubuntu 18.10 and php 7.2 i can lod home page only 

and  Apache mode Rewrite is not enabled

**Comment by Ghost173** [comment]
i hope u try with localhost/youphptube

```
<VirtualHost *:80>
DocumentRoot /var/www/html/YouPHPTube-master
DirectoryIndex index.php
#ServerName bugs.insharptechnologies.com
ServerName www.mytube.com
<Directory "/var/www/html/YouPHPTube-master">
Options Indexes FollowSymLinks MultiViews
AllowOverride All
Order allow,deny
allow from all
Require all granted
</Directory>
</VirtualHost>
```

add this then edit your hosts then try with domain its work

**Comment by SubjectXXX** [comment]
Why is the apache mod rewrite not enabled?

Enable it..

**Comment by rimer10** [comment]
no its enable i follow @Ghost173  comment its work if i access with domain if i access with localhost/youphpube its not working 

you car reproduce 
1. download and unzip /var/www/html
2. in browser localhost/Youphptube
3. install it 
4. try to login

make sure apache2 mod rewrite not enable 

if apache2 mod rewrite not enable enable then also user.php gives 404

**Comment by SubjectXXX** [comment]
You cannot use @Ghost173 literal code, since his paths could be different than yours.
