### ISSUE TITLE
Fas fa-video

### ISSUE THREAD

**Issue by charliedaps1** [DanielnetoDotCom/YouPHPTube#1512]
Hello,

I would like, in addition to the login at the right of the navbar, that fa-video fa is enable even if the user is not log.

Is there an option for this?

Thank you

**Comment by DanielnetoDotCom** [comment]
Sorry, I do not understand what do you mean.

**Comment by charliedaps1** [comment]
Hello Daniel,

Thanks for your quickly anwser.

In the navbar, there is a button to upload the videos.

This button only appears when the user is login.

Is it possible to display this button even when the user is not logged in?

Thanks

**Comment by DanielnetoDotCom** [comment]
no, it is not possible, a user is required to upload videos, that is why it shows only when is logged in

**Comment by charliedaps1** [comment]
Seems normal.

Thanks

Have a good day
