### ISSUE TITLE
Preview gif too grainy - low quality

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1513]
I have found this line, that I guess creates gif with use of ffmpeg:

    eval('$ffmpeg ="ffmpeg -ss {$duration} -t {$howLong} -i {$pathFileName} -i {$pathFileName}palette.png -filter_complex \"fps=10,scale=(iw*sar)*min(320/(iw*sar)\,180/ih):ih*min(320/(iw*sar)\,180/ih):flags=lanczos[x];[x][1:v]paletteuse, pad=320:180:(320-iw*min(320/iw\,180/ih))/2:(180-ih*min(320/iw\,180/ih))/2\" {$destinationFile}";');

My gifs are too grainy and I cannot get my head around your magic that you did. Is there a way to make better quality gifs?

**Comment by DanielnetoDotCom** [comment]
what do you mean the magic I did?

**Comment by SubjectXXX** [comment]
This eval line that you wrote is like magic to me :) I dont understand it..

Is there, in this eval line that I pasted, parameter, that controls the quality of gif?

![_yptuniqid_5c6d05a0b4a5e7 31466336](https://user-images.githubusercontent.com/2082595/53168984-4d737400-35dc-11e9-82cf-751bfec4de3d.gif)

**Comment by DanielnetoDotCom** [comment]
I am not an expert on it, but the quality is based on the generated pallet

**Comment by SubjectXXX** [comment]
Ohh, ok, I'll have a look at this line then:

    eval('$ffmpeg ="ffmpeg -y -ss {$duration} -t {$howLong} -i {$pathFileName} -vf fps=10,scale=320:-1:flags=lanczos,palettegen {$pathFileName}palette.png";');

**Comment by DanielnetoDotCom** [comment]
Yes, I guess that is the key to improve quality

**Comment by DanielnetoDotCom** [comment]
If you get some progress, please let me know

**Comment by thaidh1907** [comment]
hi SubjectXXX,
do you have skype, whatapps ?
can we discuss something ?
