### ISSUE TITLE
no mp4 upload

### ISSUE THREAD

**Issue by thaidh1907** [DanielnetoDotCom/YouPHPTube#1514]
hi, 
my streamer don't have mp4 upload
how i can enable it ?
![nomp4upload](https://user-images.githubusercontent.com/3184283/53176968-bdf0b400-3621-11e9-9fcf-c7a8e478c4ba.png)

**Comment by DanielnetoDotCom** [comment]
try this 

![image](https://user-images.githubusercontent.com/18009293/53256651-20d85e80-36a7-11e9-9df7-1d9ae6e88842.png)
