### ISSUE TITLE
SMTP configuration is not working 

### ISSUE THREAD

**Issue by dom64** [DanielnetoDotCom/YouPHPTube#1517]
When trying to set up SMTP for YouPHPTube it gives the error "Message could not be sent SMTP connect() failed."

This is what i entered in
![image](https://user-images.githubusercontent.com/20028190/53294128-c3c7d000-37ae-11e9-8e23-30cedeeeee3e.png)
I also tried tls but it still gave the same error and I have less secure app access enabled on my email

**Comment by dom64** [comment]
Ok so I got Gmail to work and i wanted to use Yandex as my email as i have my domain linked to it but it just gives this error
![image](https://user-images.githubusercontent.com/20028190/53294366-6e41f200-37b3-11e9-93c6-8e7cdb282c28.png)
This is how i have it set up
![image](https://user-images.githubusercontent.com/20028190/53294384-aea17000-37b3-11e9-9836-ee037a549db6.png)

**Comment by SubjectXXX** [comment]
Well, the error is there already: your username does not correspond to entered email in your main config.

Check Site configurations -> Regular configuration -> Email: did you use the same domain?
