### ISSUE TITLE
No plugin for articles or blog to integrate youphptube

### ISSUE THREAD

**Issue by azunamc** [DanielnetoDotCom/YouPHPTube#1518]
reviewing the payment add-on, I was surprised that there is no add-on to add the functionality that users can add articles or blog, it would be interesting to add it, I really wanted to buy that add-on and use it with youphptube.
Since this functionality has several video script, hopefully the programmer of this script will be encouraged, I would have good sales, unfortunately I can not pay for an exclusive add-on.

**Comment by DanielnetoDotCom** [comment]
Thanks, it is a good idea that may be implemented in the future.
