### ISSUE TITLE
There is api for the mobile version

### ISSUE THREAD

**Issue by azunamc** [DanielnetoDotCom/YouPHPTube#1520]
I am sending to program, an Android application, and I request an API, to do it in a more stable way, and currently I do not find the api of youphptube, the mobile application that they sell here, it is very expensive and it is not very attractive to say it, speaking of functionality and design.

**Comment by SubjectXXX** [comment]
There is no API available as far as I've seen the code..

Also not sure which mobile app you are talking about...

**Comment by DanielnetoDotCom** [comment]
There is a API plugin that may help you
