### ISSUE TITLE
Sql  update 6.7 Error

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#1521]
SQL-Error
ALTER TABLE `subscribes` 
ADD COLUMN `subscriber_users_id` INT(11) NOT NULL AFTER `notify`,
ADD INDEX `fk_subscribes_users2_idx` (`subscriber_users_id` ASC)
MySQL meldet: Dokumentation

#1060- Doppelter Spaltenname(Double column name)( 'subscriber_users_id'

kann you help me?

**Comment by DanielnetoDotCom** [comment]
why do you already have a column `subscriber_users_id`?

try to remove the command add the column to see if it will work.

you can also try to run the update command manually

**Comment by SubjectXXX** [comment]
Upgrade works fine here, you had some other problems.
This ticket can be closed.
