### ISSUE TITLE
YPT Encoder -> videos folder remaining files

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1522]
I have noticed, that there are some leftovers from uploads in Encoder's video folder.

Files are named like original_Snemanje2K2C0249_YPTuniqid_5c6d062c2b0610.97911992.

Why werent they deleted?

**Comment by DanielnetoDotCom** [comment]
they suppose to be deleted after encode process.

if is not autodeleting I will need to take a look
