### ISSUE TITLE
stream does not play.

### ISSUE THREAD

**Issue by TTcam** [DanielnetoDotCom/YouPHPTube#1523]
When launching a stream from vMix or a mobile application, a problem occurs. 
The display is working, recording is normal, but the stream does not play. 
What could be the problem? and how to solve it? Rebooting the server did not help.

![01](https://user-images.githubusercontent.com/45658270/53336323-086a7d00-390f-11e9-8363-30fa61bce952.jpg)
![02](https://user-images.githubusercontent.com/45658270/53336329-0b656d80-390f-11e9-9326-3569a828dc06.jpg)
![03](https://user-images.githubusercontent.com/45658270/53336336-13bda880-390f-11e9-8a59-513a0e3f8e9b.jpg) ![04](https://user-images.githubusercontent.com/45658270/53336341-14eed580-390f-11e9-9e9a-76396eabb343.jpg)

**Comment by DanielnetoDotCom** [comment]
You have the useLowResolution checked on your Live plugin, I uncheck it for you and your live is fine now
