### ISSUE TITLE
Allow HTTP and HTTPS

### ISSUE THREAD

**Issue by alejo1521** [DanielnetoDotCom/YouPHPTube#1525]
Hi Daniel.

Is there a way to configure Http and Https on the global config. So we can access the server ether way.  Right now I have https and it work fine, but as you know Live stream does not work with https so I want to give access to my users to both. 

Right now went I click on Live it change it form https to http and all the layout change. Also how cna i change the Live URL: form https to http

thank you

**Comment by DanielnetoDotCom** [comment]
this should work if you replace your $global['webSiteRootURL'] variable on your configuration.php file

```
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('', ''), __FILE__);
$global['webSiteRootURL'] = "http" . (!empty($_SERVER['HTTPS']) ? "s" : "") . "://" . $_SERVER['SERVER_NAME'] . $subDir;
```

**Comment by alejo1521** [comment]
Hi Daniel,

I set your config you send me and it brake the site with https. I think is on the CCS configuration. 

I use this config and it allow me to do HTTPS and HTTP. The only problem is that the layout change a bit went using http.
Current Config: 
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
//$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
$global['webSiteRootURL'] = "https".(!empty($_SERVER['HTTP'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;

Is there a way I can only change the Live URL from show https://MYURL/vidport/plugin/Live/?c=USER+TV to http://MYURL/vidport/plugin/Live/?c=USER+TV

Thank you

**Comment by DanielnetoDotCom** [comment]
no, we do not have that

**Comment by thaidh1907** [comment]
alejo1521, do you have skype, can you help me some thing about ssl ?
my skype thaidh1907

**Comment by alejo1521** [comment]
Daniel, like always thank you for your support

**Comment by alejo1521** [comment]
Thaidh sure I will contact toy tomorrow
