### ISSUE TITLE
I uploaded a link from youtube and got this error

### ISSUE THREAD

**Issue by dgwnz** [DanielnetoDotCom/YouPHPTube#1529]
I uploaded an external link from youtube, in your demo it uploaded normally and it worked
<a href="http://pt-br.tinypic.com?ref=eaf43p" target="_blank"><img src="http://i65.tinypic.com/eaf43p.png" border="0" alt="Image and video hosting by TinyPic"></a>

When I uploaded the same link in my test the following error appeared
`Playback on other Websites has been disabled by the video owne`

<a href="http://pt-br.tinypic.com?ref=2j1u4qh" target="_blank"><img src="http://i67.tinypic.com/2j1u4qh.png" border="0" alt="Image and video hosting by TinyPic"></a>

Do you have a solution?

**Comment by Andiweb87** [comment]
seems like the user ho have uploaded in youtube activate an option to not play for a second time this video out from youtube , try to put another video link and see.  Its not an error from youphptube

**Comment by DanielnetoDotCom** [comment]
Do you have https access?

**Comment by Andiweb87** [comment]
it has also happened to me Daniel, there are some specific videos that can not be played for the second time out of youtube, maybe an option or copyright activated from the uploaded user in youtube, anyway @dgwnz if you can past here the link so we can try it also in my site.

**Comment by DanielnetoDotCom** [comment]
I see, thanks for your help @Andiweb87

**Comment by dgwnz** [comment]
> it has also happened to me Daniel, there are some specific videos that can not be played for the second time out of youtube, maybe an option or copyright activated from the uploaded user in youtube, anyway @dgwnz if you can past here the link so we can try it also in my site.

https://www.youtube.com/watch?v=4q9UafsiQ6k

**Comment by dgwnz** [comment]
> Do you have https setup on your website?

I'm testing on localhost, can that be the problem?

**Comment by Andiweb87** [comment]
try to embed another link and see if this issue persist
