### ISSUE TITLE
Encoder install issues on Godadday server

### ISSUE THREAD

**Issue by ThejeswarReddy** [DanielnetoDotCom/YouPHPTube#153]
I installed  the first part correctly and I have these issues,  anybody know how to set these  on godaddy server

![screenshot_2017-10-15-12-41-16](https://user-images.githubusercontent.com/29545146/31582626-836f515c-b1a6-11e7-9ff2-3dfbc5fb4e1c.jpg)

**Comment by ThejeswarReddy** [comment]
Okay I got solution for last four errors by going into cpanel > php version >  switch php options and input manual values. Now I need to know solution for first three errors ..

**Comment by mikweb2017** [comment]
for ubuntu machine
sudo apt-get update
sudo apt-get install ffmpeg git libimage-exiftool-perl

Mod rewite  
you can skip and sell with the install

and   read wiki
https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x---For-YouPHPTube-Encoder

**Comment by nightstryke** [comment]
Are you using a dedicated server or vps from godaddy, or godaddy shared hosting?

**Comment by ThejeswarReddy** [comment]
Thanks, I asked For Godaddy to look into this issue and they said, they
don't support these on shared hosting and asked to upgrade the plan, and
now i'm using the current plan to test different web scripts, if i think
seriously about this i  will go with Danielneto hosting service.

**Comment by nightstryke** [comment]
Yeah you need to at least be on one of their VPS services for this because share hosting or even reseller hosting does not give you the admin access you'd need like a VPS and Dedicated Server.

**Comment by DanielnetoDotCom** [comment]
You guys doing great, thanks

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
