### ISSUE TITLE
Unable to install the script 

### ISSUE THREAD

**Issue by chinli12** [DanielnetoDotCom/YouPHPTube#1531]
After configuring my server according to the wiki you pr
![screenshot_2019-02-25-23-56-16](https://user-images.githubusercontent.com/29612076/53402627-60a68b00-39b2-11e9-8bcc-0e8121b5e8d0.png)
ovided I have this error masage

**Comment by DanielnetoDotCom** [comment]
Hi

I found a typo on the script, I upload a fix.

please drop your database, update your files and try again

**Comment by chinli12** [comment]
Still not working I updated the files is still saying the same error

**Comment by DanielnetoDotCom** [comment]
I just sent a new update , now it should work.

Sorry if it does not work before.

Also please do not forget to drop the database first

**Comment by chinli12** [comment]
After successful installed their is another problem the code box shows blank
![screenshot_2019-02-26-17-03-13](https://user-images.githubusercontent.com/29612076/53427129-9f573800-39e8-11e9-9597-1ec81516f324.png)

**Comment by chinli12** [comment]
Sorry is working now

**Comment by chipowski** [comment]
Thanks that installs ok now (I had the same issue and was about to create a post).

Now there is an issue I'm having that I cannot login as admin, reset the password or create a new user.
Should I create a seperate post for this?

**Comment by DanielnetoDotCom** [comment]
@chipowski yes please
