### ISSUE TITLE
Monetize users - bug

### ISSUE THREAD

**Issue by datasurgeservers** [DanielnetoDotCom/YouPHPTube#1533]
Hi,
I've noticed that there is a potential issue with this plugin. People, including the user who posted the video, can click on their video and gain money in their wallet. I think this should not be the case as it would be a way to rip off site admins for money. Also, people can keep hitting refresh to have the money increase in the video owner's wallet.

**Comment by Andiweb87** [comment]
im continue to not understand how this plugin works, my wallet is not increase :(

**Comment by datasurgeservers** [comment]
Andiweb87, first, you need to set a beginning balance on your admin account. I set mine to 100,000 as a test. This is not real money, it's just something you can set.  Then, when someone watches a video you own on a non-admin account, the balance is deducted from the admin account and placed in your wallet.

**Comment by Andiweb87** [comment]
i have follow your instructions , same here still 0.00.
