### ISSUE TITLE
zlib library not found after downloading nginx-1.12.0

### ISSUE THREAD

**Issue by rtnorton57** [DanielnetoDotCom/YouPHPTube#1535]
While installing nginx code on Ubuntu 18.04 and YPT 6.7 the install seemed to be cut short after line:
"checking for zlib library   not found" after download nginx-1.12.0.tar.gz.
The error message was 
Next error during install:
./configure: error: the HTTP gzip module requires the zlib library.
You can either disable the module by using --without-http_gzip_module
option, or install the zlib library into the system, or build the zlib library
statically from the source with nginx by using --with-zlib=<path> option.

Not sure how to proceed. Please advise.

**Comment by patriclougheed** [comment]
Do you have zlib installed?

run: sudo apt show zlib1g

You should see something like:
Package: zlib1g
Version: 1:1.2.8.dfsg-2ubuntu4.1
Priority: required
Section: libs
Source: zlib
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Mark Brown <broonie@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 160 kB
Provides: libz1
Depends: libc6 (>= 2.14)
Conflicts: zlib1 (<= 1:1.0.4-7)
Breaks: libxml2 (<< 2.7.6.dfsg-2), texlive-binaries (<< 2009-12)
Homepage: http://zlib.net/
Task: minimal
Supported: 5y
Download-Size: 51.2 kB
APT-Manual-Installed: yes
APT-Sources: http://mirrors.digitalocean.com/ubuntu xenial-updates/main amd64 Packages
Description: compression library - runtime
 zlib is a library implementing the deflate compression method found
 in gzip and PKZIP.  This package includes the shared library.

If not then run: sudo apt-get install zlib1g

**Comment by DanielnetoDotCom** [comment]
I do this for myself

`sudo apt-get install --reinstall zlibc zlib1g zlib1g-dev`
