### ISSUE TITLE
How to activate this menu ??

### ISSUE THREAD

**Issue by Andiweb87** [DanielnetoDotCom/YouPHPTube#1536]
Hi , how can i activate this left menu for simple users , i see only in demo site ?

demo site -> https://snag.gy/GLonlU.jpg

my site - >  https://snag.gy/8PdQrk.jpg

some options are missing in my site in left menu.

**Comment by DanielnetoDotCom** [comment]
when you edit a user you can see the option to enable features.

![image](https://user-images.githubusercontent.com/18009293/53632916-dd28ac00-3bf4-11e9-8710-46f07ffe6266.png)

**Comment by Andiweb87** [comment]
thank you

**Comment by Andiweb87** [comment]
Sorry and for the comments in videos is any option to activate them ? for simple users i mean ?

https://snag.gy/WPcd2s.jpg

**Comment by DanielnetoDotCom** [comment]
activate what?

**Comment by Andiweb87** [comment]
the comment section i see only like admin and not from simple user, see the screenshot how is look for simple user , the comment section is missing

**Comment by DanielnetoDotCom** [comment]
Sorry, we do not have this option

**Comment by Andiweb87** [comment]
in demo site work the comments for simple users

**Comment by DanielnetoDotCom** [comment]
Sorry, I think I understand you now.

Try this

![image](https://user-images.githubusercontent.com/18009293/53956246-e06edc80-40b9-11e9-8bb7-8fe3eff1a1a4.png)

**Comment by Andiweb87** [comment]
works 

thank you
