### ISSUE TITLE
Noftification of live streams not updating

### ISSUE THREAD

**Issue by darthdaniel16** [DanielnetoDotCom/YouPHPTube#1537]
Hi,'

I have set up YouPHPTube and nginx and I can watch live streams using the  Live URL. My problem is that the notification that is supposed update when a live stream starts is not updating (the live stream counter on the menu bar is still on zero and on the home page the notification cannot be seen). I have confirmed the values of the parameters in the live plugin setting but I still cant figure out what i am doing wrong.

Thanks

**Comment by DanielnetoDotCom** [comment]
How is this on your site?

![image](https://user-images.githubusercontent.com/18009293/53644454-68b23500-3c15-11e9-8a64-16df936844a4.png)

**Comment by darthdaniel16** [comment]
Hi, listed transmissions is enabled but still there is no update

**Comment by DanielnetoDotCom** [comment]
check this https://github.com/DanielnetoDotCom/YouPHPTube/issues/1107

**Comment by darthdaniel16** [comment]
hi @DanielnetoDotCom could I send you server details and you have a look?

**Comment by darthdaniel16** [comment]
Hi @DanielnetoDotCom from the link referenced it seemed the issue is SSL. My first installation had been on a virtual server on my pc and I had used a self signed certificate for nginx and it worked fine. My current installation is on a public web server and I am still using a self signed certificate for nginx, could that be the problem?

**Comment by DanielnetoDotCom** [comment]
I just fix a very similar problem on a costumer.

the problem was because he added a redirect rule on .htaccess, so he redirects everything to his www URL.

After removing the redirect rule it starts to work perfectly

if you want us to fix it for you. Feel free to can hire us here https://www.youphptube.com/services
