### ISSUE TITLE
How to insert trailer in first page style netflix? how to change the size of the black degraded background to a white one and of a smaller size?

### ISSUE THREAD

**Issue by codelabinf** [DanielnetoDotCom/YouPHPTube#1538]
Hi, I can not upload and watch a video trailer in the bottom of the netflix homepage. The video is mine, it's not a movie or anything like that. It is a video of its own that does not appear in imbd or anywhere else. You only see a static image where the cursor is. I also want to change the graduated background in black to a smaller one, which occupies 25% of the screen instead of occupying almost 75%.

![cap8](https://user-images.githubusercontent.com/33943401/53652986-f6e3e680-3c28-11e9-8ab1-a39475e5690f.png)

Thank you so much!

**Comment by DanielnetoDotCom** [comment]
On videos manager 

![image](https://user-images.githubusercontent.com/18009293/53653622-7aea9e00-3c2a-11e9-9c79-2466d46a5b80.png)

**Comment by codelabinf** [comment]
I can not load it from a place other than YouTube?

**Comment by codelabinf** [comment]
how to change the size of the black degraded background to a white one and of a smaller size?

**Comment by DanielnetoDotCom** [comment]
the black bars are from the video source, the video player is 100% width. maybe with CSS you can make the changes you want.

**Comment by codelabinf** [comment]
Thank you so much!

**Comment by codelabinf** [comment]
Hello, when I play the video in vlc in full screen the bars do not appear, the video is in 16: 9 standard. But when I upload it to youphptube, the black bars appear on the sides. How could you solve it? From already thank you very much!

**Comment by codelabinf** [comment]
This is the video info
![videoinfo](https://user-images.githubusercontent.com/33943401/54227471-c03a8580-44de-11e9-87c1-a34af95144a3.png)

**Comment by DanielnetoDotCom** [comment]
it is because the trailer is not fullscreen, but you can try to make the video tag fill all space with css.

you will need to google for that
