### ISSUE TITLE
video tags plugin

### ISSUE THREAD

**Issue by nightstryke** [DanielnetoDotCom/YouPHPTube#1539]
I see there's  plugin called video tags, @DanielnetoDotCom is there a tutorial on the proper way of setting these video tags up?
How they're seen or used in YouPHPTube?
I would really like to know how to implement and use this plugin on my site.

**Comment by DanielnetoDotCom** [comment]
We do not have a tutorial for that. but the first step is to create tag types, then you will be able to add tags on your videos on videos manager.

![image](https://user-images.githubusercontent.com/18009293/53680530-c600c180-3cbb-11e9-940e-04c8d1c4cb81.png)


![image](https://user-images.githubusercontent.com/18009293/53680539-dc0e8200-3cbb-11e9-91b7-6461bf6aa2f9.png)


![image](https://user-images.githubusercontent.com/18009293/53680552-f0527f00-3cbb-11e9-90b5-f42a2eaeb2be.png)

**Comment by nightstryke** [comment]
So does the hashtag # need to be added or is it automatically added?

**Comment by Andiweb87** [comment]
no, just typ words in the lines withe circle red show by Daniel and press enter

**Comment by nightstryke** [comment]
Can the hashtag be added and used? A lot of my users are used to using YouTube and add the video tag in using hash tags so #this or #that can they still use the tags using that?

**Comment by DanielnetoDotCom** [comment]
I guess, if they use # it will be part of the tag name
