### ISSUE TITLE
Estão usando o tema para pornografia 

### ISSUE THREAD

**Issue by PlayxPE** [DanielnetoDotCom/YouPHPTube#154]
http://peppercool.com/

**Comment by DanielnetoDotCom** [comment]
Infelizmente, por enquanto nada posso fazer a não ser não prover suporte

**Comment by mikweb2017** [comment]
i write Email to abuse@godaddy.com

**Comment by DanielnetoDotCom** [comment]
Thanks @mikweb2017

**Comment by mikweb2017** [comment]
unfortunately the provider does not react to the reclamation

**Comment by mikweb2017** [comment]
![sperre](https://user-images.githubusercontent.com/30271757/31774470-2818a3c4-b4e6-11e7-84fb-809faa5b0b8b.PNG)

finally that the provider has reacted

**Comment by DanielnetoDotCom** [comment]
Nice , thanks for the help :)

What did you wrote on the email? 
Just saving for future needs actions?

**Comment by mikweb2017** [comment]
in this case for godaddy I filled out the complaint form 3 or 4 times(https://supportcenter.godaddy.com/AbuseReport?isc=gdbb3454&cvosrc=email.Transactional.3454&cvo_crid=55fVZeCBXs949Kl2OG2H6b) before I wrote to check the content of the site as it contains pornographic content. and always different for each provider with a complaint react slowly for this in these cases I write several times.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
