### ISSUE TITLE
Problem with getImageFromFilenameAsync__YPTuniqid_5c73e2bfb46171.33624372_embed

### ISSUE THREAD

**Issue by BMTTeam** [DanielnetoDotCom/YouPHPTube#1540]
Hello,
The installation went without any issues (following the instructions on the site).
The installation was done on Ubuntu 18.04
The problem is that if I embed a video link, the cache file contains wrong address (physical address). Here is the content of the file:
{"poster":"http:\/\/\/var\/www\/html\/YouPHPTube\/videos\/_YPTuniqid_5c73e2bfb46171.33624372.jpg","posterPortrait":false,"posterPortraitThumbs":false,"posterPortraitThumbsSmall":false,"thumbsGif":false,"gifPortrait":false,"thumbsJpg":"http:\/\/\/var\/www\/html\/YouPHPTube\/videos\/_YPTuniqid_5c73e2bfb46171.33624372_thumbsV2.jpg","thumbsJpgSmall":"http:\/\/\/var\/www\/html\/YouPHPTube\/videos\/_YPTuniqid_5c73e2bfb46171.33624372_thumbsSmallV2.jpg"}
And of course the the posters and thumbs are wrong.
If I clear the cache folder, for several minutes everything is OK. After that the .embed files are modified on a background with the wrong address.
Where could be the problem? Perhaps some config error or typo?

Cheers,
-Tiho

**Comment by DanielnetoDotCom** [comment]
how is your videos/configuration.php file?

**Comment by BMTTeam** [comment]
Here it is:
@roadrage:/var/www/html/YouPHPTube/videos# cat configuration.php 
<?php
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
$global['webSiteRootURL'] = 'https://roadrage.video/';
// get the subdirectory, if exists
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;

$global['systemRootPath'] = '/var/www/html/YouPHPTube/';
$global['salt'] = 'xxxxxxxxxxxxxxxxxxxxxxx';


$mysqlHost = 'localhost';
$mysqlPort = '3306';
$mysqlUser = 'dbuser';
$mysqlPass = 'dbpass';
$mysqlDatabase = 'youPHPTube';

/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';

**Comment by DanielnetoDotCom** [comment]
Try to make your configuration.php file looks like that way ...


```
<?php
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
$global['webSiteRootURL'] = 'https://roadrage.video/';
// get the subdirectory, if exists
//$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), FILE);
//$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;

$global['systemRootPath'] = '/var/www/html/YouPHPTube/';
$global['salt'] = 'xxxxxxxxxxxxxxxxxxxxxxx';

$mysqlHost = 'localhost';
$mysqlPort = '3306';
$mysqlUser = 'dbuser';
$mysqlPass = 'dbpass';
$mysqlDatabase = 'youPHPTube';

/**

Do NOT change from here
*/
require_once $global['systemRootPath'].'objects/include_config.php';
```

Comment the 2 lines below **$global['webSiteRootURL'] = 'https://roadrage.video/';**

**Comment by BMTTeam** [comment]
Hi Daniel,
After few hours, the modification of the config file is working perfectly.
I did the modification, cache folder cleaned and after several checks, the thumbs are still there.

Issue fixed and closed. Thanks.

Cheers,
-Tiho
