### ISSUE TITLE
GoDaddy Install+ Local Data Center Video Hosting

### ISSUE THREAD

**Issue by meetbushe** [DanielnetoDotCom/YouPHPTube#1541]
I want to install YouPHPTube web files and database on Godaddy. But to improve upload and download speed i want the videos to be uploaded saved to two separate data centers that are located in my country 1km away from here. Not on Godaddy. Is this possible, how do i do it?

**Comment by nightstryke** [comment]
@meetbushe You cannot use a Shared Web Host for YouPHPTube you need to use a VPS (Virtual Private Server), or a Dedicated Server to run YouPHPTube!

**Comment by tgd1973** [comment]
Hi! I can say for myself, if you do not want to have Live Streaming / Chat and without encoder ... The "YouTubePHP streamer" can be uploaded via FTP, in any Sharing Hosting preferably with an operating system, belonging to the Debian family. But the encoder must necessarily be installed in a VPS (at least).
If you also need Live Streaming it must necessarily have a VPS, or a dedicated server, if you have a lot of trafico ...
