### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by d0773d** [DanielnetoDotCom/YouPHPTube#1544]
Setup
Linode VPS
Virtualmin
latest release of video and encoder git cloned

I renamed classic.htaccess file to .htaccess

I didn't necessarily follow the install guide 100% because I already have my server configured using virtualmin.   I cloned the youphptube and the encoder into video and encoder directory on my server and pointed my browser to https://kannacloud.com/video and receive the following:  
**Forbidden
You don't have permission to access /video/index.php on this server.**

apache config directives:
```
<Directory /home/kannacloud/public_html>
Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch +ExecCGI
allow from all
AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
Require all granted
AddType application/x-httpd-php .php
AddHandler fcgid-script .php
AddHandler fcgid-script .php7.0
FCGIWrapper /home/kannacloud/fcgi-bin/php7.0.fcgi .php
FCGIWrapper /home/kannacloud/fcgi-bin/php7.0.fcgi .php7.0
</Directory>
<Directory /home/kannacloud/public_html/video>
          Options Indexes FollowSymLinks
          AllowOverride All
          Require all granted
</Directory>
```

**Comment by d0773d** [comment]
I fixed my issue by removing my video and encoder directory and git cloned again.  I then went into virtual min file browser and renamed the default YouPHPTube directory to video.  I am not able to view YouPHPTube :-)

**Comment by DanielnetoDotCom** [comment]
Hi

If is all fine now, please close the issue
