### ISSUE TITLE
No thumbnails on videos

### ISSUE THREAD

**Issue by chipowski** [DanielnetoDotCom/YouPHPTube#1546]
Hi.
I've installed YouPHPTube and it's working great. Thanks for putting this out there for everyone.
Loving the Netflix theme, it's exactly what I was looking for.

I've uploaded some videos by direct upload and got no thumbnails so read through the wiki so understand I need a plugin to get automatic thumbs from that method. 

So for now I tried the encoder method instead - using the public encoder - but still have no thumbnails. Is there a setting I need to change for the thumbnails to show? The videos are all showing a 404 thumbnail like the 20th century fox logo at the moment.

**Comment by thaidh1907** [comment]
check videos/youphptube.log

**Comment by chipowski** [comment]
Thanks.
There was nothing obvious in the log but I noticed the uploaded videos were truncated and then found that I had uploaded faulty video files.
I've uploaded a properly tested video file and have got a thumbnail for it so all good.
Thanks for getting back to me

**Comment by veljkostanar** [comment]
I'm having a similar issue the Encoder and Streamer are on the same server the video encodes ok and the animated gif works but all video's regardless of resolution quality or orgional file size do not show a thumbnale only a white background with a play button. 

I checked the log file and noticed this on every upload 

[11-Nov-2019 03:05:35 UTC] PHP Warning:  filectime(): stat failed for /var/www/html/nws/videos/_YPTuniqid_5dc8cfdf78d5b4.36003691_portrait_thumbsV2.jpg in /var/www/html/nws/objects/video.php on line 2255

**[11-Nov-2019 03:05:35 UTC] im_resize: Function does not exists: imagecreatefromjpeg**
