### ISSUE TITLE
Why is my site banned? Cannot log into my own site.

### ISSUE THREAD

**Issue by BigmIkeX** [DanielnetoDotCom/YouPHPTube#1556]
Why is my site banned? i boot users who upload 'bad content' so whats the deal!? this is on my own server, host by me... so why is it being controlled? 
![image](https://user-images.githubusercontent.com/32983492/53915912-7eb16280-4026-11e9-8c99-eb26acc34d8e.png)

**Comment by DanielnetoDotCom** [comment]
What is your site URL?

**Comment by BigmIkeX** [comment]
media.xphunk.com/tube
media.xphunk.com/encoder

**Comment by DanielnetoDotCom** [comment]
Probably because porn content

**Comment by BigmIkeX** [comment]
deleted the user and the content.
now what?

**Comment by DanielnetoDotCom** [comment]
I access your URL an I could not see any Youphptube installation

**Comment by BigmIkeX** [comment]
![image](https://user-images.githubusercontent.com/32983492/53916416-c8e71380-4027-11e9-80cd-3d225baf5e8e.png)

**Comment by BigmIkeX** [comment]
https://media.xphunk.com/encoder/

**Comment by BigmIkeX** [comment]
How do i get off the banned list?
![image](https://user-images.githubusercontent.com/32983492/53917470-3136f480-402a-11e9-8554-c8d163c4b9f4.png)

**Comment by DanielnetoDotCom** [comment]
I will remove, your site from banned, but please be careful with the content

**Comment by BigmIkeX** [comment]
Thank you and much appreciated.
I'm restricting site and reviewing the terms.
