### ISSUE TITLE
Cannot embed iFrames?

### ISSUE THREAD

**Issue by RapFan89** [DanielnetoDotCom/YouPHPTube#1558]
Hi,
Have the iFrame contents been disabled with recent updates?

I ask that because now i cannot insert videos in other platform using the share button.

Inside the code in can read the string iFrame are not supported.

Is that feature been removed from YouPHPTube?

**Comment by DanielnetoDotCom** [comment]
Hi

it was not disabled

**Comment by DanielnetoDotCom** [comment]
the only thing that may disable this is the SecureVideosDirectory plugin

![image](https://user-images.githubusercontent.com/18009293/53969992-947f6000-40d8-11e9-90c7-d13024ed51cd.png)

**Comment by RapFan89** [comment]
I do not have that plugin, it is a paid one?

This is the code that embed mode generates

<iframe width="640" height="360" style="max-width: 100%;max-height: 100%; border:none;" src="uURL" frameborder="0" allowfullscreen="allowfullscreen" allow="autoplay" scrolling="no">iFrame is not supported!</iframe>

**Comment by DanielnetoDotCom** [comment]
yes, it is paid.

it has no reason to happen, try it on demo site

**Comment by RapFan89** [comment]
i'm running 6.9 version.

It can reproduced in the demo site.
https://demo.youphptube.com/video/wolverine-vs-mulher-maravilha-

![image](https://user-images.githubusercontent.com/20926927/53970432-fea8fc80-40fa-11e9-93ef-eee39e4e7484.png)

**Comment by DanielnetoDotCom** [comment]
Are you saying the iframe is not working?
the embed video seems like it is working, maybe is your browser

https://demo.youphptube.com/videoEmbed/wolverine-vs-mulher-maravilha-

**Comment by RapFan89** [comment]
if i copy the code below Share Video: i cannot use it anymore. I've tried both with firefox and chrome. Also my colleague is reporting that issue.

**Comment by DanielnetoDotCom** [comment]
where are you sharing it? can you screen shot?

**Comment by RapFan89** [comment]
i'm sharing on a moodle platform, i'm waiting for the screenshot, but basically after inserting the code in the form, the video does not appear no more

**Comment by DanielnetoDotCom** [comment]
I guess it may be something else, maybe on moodle

**Comment by RapFan89** [comment]
I have created a simple html test page, here are the results
![immagine](https://user-images.githubusercontent.com/20926927/53973156-80e7ef80-4100-11e9-97d4-1310ad2d1c9f.png)



Tell me if it something wrong in that code:
`INSERT INTO videos_statistics (`when`,ip, users_id, videos_id, lastVideoTime, created, modified, session_id) values (now(),?,NULL,?,0,now(),now(),'416540c81b888397fc7204797be59644') Save Video Statistics Error : (1054) Unknown column 'session_id' in 'field list'`

**Comment by RapFan89** [comment]
<iframe width="640" height="360" style="max-width: 100%;max-height: 100%; border:none;" src="http://myservername/videoEmbed/myvideo" frameborder="0" allowfullscreen="allowfullscreen" allow="autoplay" scrolling="no">iFrame is not supported!</iframe>    

this is the iFrame generated by youPHPTube installation

**Comment by DanielnetoDotCom** [comment]
this is nothing to do with iframe or embed video, this youphptube installation is failing and need to be updated , looks like you skiped the version 6.7;

is it the demo site or your site?


try to run this mysql command on your database

```
ALTER TABLE `videos_statistics` 
ADD COLUMN `session_id` VARCHAR(45) NOT NULL AFTER `videos_id`,
ADD INDEX `session_id_statistics` (`session_id` ASC);
```

**Comment by RapFan89** [comment]
Great!
I tought that v.6.9 already had the previous version's changes inside. I was wrong, many thanks for help me to fix the issue. 


Now that i have discovered this, how can i check that my database has all the updates needed to work properly?

**Comment by DanielnetoDotCom** [comment]
I am not sure what update you skipped, you may need to check the updatedb files and your database, if you have all columns and fields

**Comment by danieljaber** [comment]
Hi Daniel. Please, I'm with some similar problem: i'm trying to embed an video of my chanel in my website and i receive a mensage that the conection with my server was refused. See:

![image](https://user-images.githubusercontent.com/73574002/97544219-0ee4ae00-19a8-11eb-8b57-8aa504cf9139.png)

This is my iframe code:
<div class="embed-responsive embed-responsive-16by9"><iframe width="640" height="360" style="max-width: 100%;max-height: 100%; border:none;" src="https://34xxxxx.77/AVideo/videoEmbed/1/teste?channelName=Admin_5f9a7533b3f3e" frameborder="0" allowfullscreen="allowfullscreen" allow="autoplay" scrolling="no">iFrame is not supported!</iframe></div>

**Comment by DanielnetoDotCom** [comment]
@danieljaber I guess this has nothing to do with AVideo, it is a network problem
