### ISSUE TITLE
First Page Mode: only Youtube and not gallery can be seen

### ISSUE THREAD

**Issue by aclaussen1** [DanielnetoDotCom/YouPHPTube#156]
I looked on the online video tutorials and there is supposed to be a second gallery option? How come I only see Youtube?

**Comment by ThejeswarReddy** [comment]
Go to plugins and activate the gallery plugin reload the page that's it...

**Comment by nightstryke** [comment]
I kinda wish the gallery didn't have the scrolling bar at the bottom of the page though.

**Comment by ThejeswarReddy** [comment]
Update to the latest one they fixed this issue..

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
