### ISSUE TITLE
Live Stream

### ISSUE THREAD

**Issue by bigdog175** [DanielnetoDotCom/YouPHPTube#1561]
I have youphptube installed and seems to running correctly I am able to upload videos and view them.  However when I try to go [LIVE] it does not work.  When I connect via mobile it seems to go live for a few seconds then disconnects but I never see the live feed in the browser. No errors in youphptube.log. This is the error that keeps popping in error.log: 
2019/03/10 21:22:27 [error] 14137#14137: *8 open() "/HLS/live/5c85xxx/index.m3u8" failed (2: No such file or directory), client: 1xx.xx.xx.xx, server: localhost, request: "GET /live/5c85xxx/index.m3u8 HTTP/1.1", host: "1xx.xx.xx.xx::8080", referrer: "http://1xx.xx.xx.xx/YouPHPTube/plugin/Live/"

Running UNBUNTU 18.04
PHP 7.2
nginx nginx/1.14.0 (unnbuntu)
Apache/2.4.29 (Ubuntu)

**Comment by DanielnetoDotCom** [comment]
this is an NGINX installation problem, check the permission for that dir /HLS/live/

if it persists try to find some help on the nginx RTMP project. 

https://github.com/arut/nginx-rtmp-module
