### ISSUE TITLE
How to show rondom  videos to homepage

### ISSUE THREAD

**Issue by chinli12** [DanielnetoDotCom/YouPHPTube#1564]
It will be good if the homepage shows random videos not the same video in date added,most watch and most popular it shows the same group of video

**Comment by DanielnetoDotCom** [comment]
What first-page mode are you using?

you can select preferred videos that will randomly appear

**Comment by chinli12** [comment]
I am using YouTube template how can I select random video to show

**Comment by chinli12** [comment]
It will also be nice to show categories videos in homepage

**Comment by DanielnetoDotCom** [comment]
I just sent an update for big videos be random

And I am almost sure I already sent an update to show the categories on the YouTube Page

![image](https://user-images.githubusercontent.com/18009293/54474229-3978f780-47c1-11e9-9f80-c5f1b0dad523.png)
