### ISSUE TITLE
How to disable Up Next panel?

### ISSUE THREAD

**Issue by RapFan89** [DanielnetoDotCom/YouPHPTube#1565]
Hi,
we are using playlists and we want to hide the upnext panel, is it possibile?

![immagine](https://user-images.githubusercontent.com/20926927/54220680-35fc1c80-44f2-11e9-9cf3-b9f221ec262e.png)

**Comment by DanielnetoDotCom** [comment]
we do not have this option yet. 

If you are willing to pay to add this feature, please contact us on developer@youphptube.com
