### ISSUE TITLE
How to generate Stream name/key

### ISSUE THREAD

**Issue by NightFlyerMD** [DanielnetoDotCom/YouPHPTube#1566]
At first: 
Thanks for this great piece of software.

Maybe you could help me out: I installed the live plugin and necessary stuff as described in the tutorials. Now, unfortunally, i dont get any Stream Key/name from the Site to connect to. How can i generate one?
![streamkey](https://user-images.githubusercontent.com/48571402/54395671-62f23000-46a8-11e9-9fbf-595dc1a124bc.jpg)

**Comment by DanielnetoDotCom** [comment]
did you install the live tables?


![image](https://user-images.githubusercontent.com/18009293/54474245-6fb67700-47c1-11e9-881d-d0138af7d2bd.png)

**Comment by NightFlyerMD** [comment]
Oh my god... I thought i did... But... You were right.. I did it "again" And it's working now.
Thanks a lot!

What is your experience with time delay in live streaming. I had my own NGINX/RTMP Proxy and do not bring it below 30s. And here it seems even longer...

**Comment by DanielnetoDotCom** [comment]
About stream delay, you may try to ask it on the NGINX/RTMP hub https://github.com/arut/nginx-rtmp-module

**Comment by raffeal** [comment]
install table not available

**Comment by raffeal** [comment]
install table not available

![54474245-6fb67700-47c1-11e9-881d-d0138af7d2bd](https://user-images.githubusercontent.com/47043451/54878376-77bf8800-4e4d-11e9-8b48-3ddad56113b6.png)

**Comment by DanielnetoDotCom** [comment]
Not sure why your server is not showing it. I can not reproduce this error.

you can try to manually install the tables on MySQL

**Comment by lunar54** [comment]
I also do not get Install tables under plugin section for live How to install tables manually ?
