### ISSUE TITLE
page navigation is missing when category is selected

### ISSUE THREAD

**Issue by abamilod** [DanielnetoDotCom/YouPHPTube#157]
Please add page navigation when category is selected. Page navigation is missing on mode youtube & gallery.  Thank you.

**Comment by DanielnetoDotCom** [comment]
what do you mean page navigation?

**Comment by abamilod** [comment]
When we have many videos under the same category (e.g default category), there is more than one page list. But we cannot see page 1,2 or more if we list video by category

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
