### ISSUE TITLE
How to Install Server Streamer On Ubuntu 18.04

### ISSUE THREAD

**Issue by lamadya** [DanielnetoDotCom/YouPHPTube#1570]
Hi 
i have a vps with ubuntu 18.04 I have successfully installed youphptube but when installed my server stream
get error :
checking for OS
 + Linux 4.15.0-46-generic x86_64
checking for C compiler ... not found

./configure: error: C compiler cc is not found

i dont understand why please help
thank you

**Comment by DanielnetoDotCom** [comment]
I am sure you are able to find this answer on google

https://stackoverflow.com/questions/12770501/c-compiler-gcc-not-found-while-installing-passenger-and-nginx
