### ISSUE TITLE
Shuffle playlists 

### ISSUE THREAD

**Issue by gregorymcewanmarriot** [DanielnetoDotCom/YouPHPTube#1573]
I want to shuffle a playlist by default when a user plays any playlist using the php shuffle command 

`shuffle($playlist);`

Currently users can sort by name/date ASC/DESC  where can i add the code to pass a randomise or shuffle command to the dropdown select - if this is too difficult in which php file can i just shuffle the array?

By default I am trying to add a button on top menu that allows users to click and get a random shuffled playlist of all videos and channels in the site so they can get an idea of what is available from across all channels or just one channel with one click

**Comment by DanielnetoDotCom** [comment]
Sorry, but it is not easy like you described
