### ISSUE TITLE
Watch all in category?

### ISSUE THREAD

**Issue by gregorymcewanmarriot** [DanielnetoDotCom/YouPHPTube#1574]
what link can i pass in menu item to allow user to watch all vids in a category with autoplay and autoplay next video in category?

**Comment by DanielnetoDotCom** [comment]
Sorry, we do not have this option to create a link for that

**Comment by gregorymcewanmarriot** [comment]
Hi Daniel - I have "sort of " got this working a tiny bit - but would appreciate some help on exactly how the playlist.php is called - does it call the json file which fetches the result.

I basically cloned your **getVideosFromPlaylist** function in object player.php and added a function see below which fetches the correct results from all videos in the category

`   static function getVideosFromCat($categories_id) {
        global $global;
        $sql = "SELECT *, categories.clean_name as playlists_id, videos.id as id, videos.created as cre, videos.externalOptions as externalOptions, categories.name as name FROM videos LEFT JOIN categories ON videos.categories_id = categories.id WHERE categories.id = ?";
        $sql .= self::getSqlFromPost();
        $res = sqlDAL::readSql($sql, "i", array($playlists_id));
        $fullData = sqlDAL::fetchAllAssoc($res);
        sqlDAL::close($res);
        $rows = array();
        if ($res != false) {
            foreach ($fullData as $row) {
                if (!empty($_GET['isChannel'])) {
                    $row['tags'] = Video::getTags($row['id']);
                    $row['pluginBtns'] = YouPHPTubePlugin::getPlayListButtons($categories_id);
                    $row['humancreate'] = humanTiming(strtotime($row['cre']));
                }
                $rows[] = $row;
            }
        } else {
            die($sql . '\nError : (' . $global['mysqli']->errno . ') ' . $global['mysqli']->error);
        }
        return $rows;
    }`

in mysql if you run the query  `SELECT *, categories.clean_name as playlists_id, videos.id as id, videos.created as cre, videos.externalOptions as externalOptions, categories.name as name FROM videos LEFT JOIN categories ON videos.categories_id = categories.id WHERE categories.id = 4
 you would see the results - i substituted `the category nicename to be the playlist so instead of say calling https://mydomain.com/playlist/64 i am calling https://mydomain.com/playlist/music

i have also in playlist.php cloned the getVideosIdFromPlaylist function as seen below

`    static function getVideosIdFromPlaylist($playlists_id) {
        $videosId = array();
        $rows = static::getVideosFromPlaylist($playlists_id);
        foreach ($rows as $value) {
            $videosId[] = $value['videos_id'];
        }
        return $videosId;
    }
	
    static function getVideosIdFromCat($categories_id) {
        $videosId = array();
        $rows = static::getVideosFromCat($playlists_id);
        foreach ($rows as $value) {
            $videosId[] = $value['videos_id'];
        }
        return $videosId;
    }`

I use the Netflix plugin so i added in the row and BigVideo.pho files the following to display the Buttons to link to play all Videos in Category as seen in image below 

`<a href="<?php echo $global['webSiteRootURL']; ?>playlist/<?php echo $value['clean_category']; ?>" class="btn btn-xs btn-default playAll hrefLink" ><span class="fa fa-play"></span> <?php echo __("Play All in " . $value['category']); ?></a><?php echo $playListButtons; ?>`

![image](https://user-images.githubusercontent.com/48602432/54618085-17a29d80-4a6b-11e9-8719-358b4b057913.png)

So theoretically instead of passing the playlist id to go get all rows from sql for videos in a playlist i am passing to sql the category clean-name id which i am trying to call my function **getVideosFromCat** pasted above in message... i know it returns what the playlist needs but just cannot figure out the last step to complete this

Would **really** appreciate a helping hand

**Comment by DanielnetoDotCom** [comment]
it is a good idea, but unfortunately, I can not go into it now and help you to make it work.

I really wish to have time to continue this.

about the URL
`https://mydomain.com/playlist/64 i am calling https://mydomain.com/playlist/music`
Did you change the .htaccess?

Also, I do not understand what is the last step you need to complete this
