### ISSUE TITLE
Youphptube cannot see php.ini.

### ISSUE THREAD

**Issue by inferno-prime** [DanielnetoDotCom/YouPHPTube#1576]
I am with dream host and there setup is rather different they refer to the php.ini as the phprc file so I am hoping your script can still see the file. Anyway I have to create one outside of my domain folder and input options there but youphptube does not see that it only sees the master file. 

Please tell me that this can be fixed because I cannot touch the master file I can only make a duplicate somewhere else with different options.

**Comment by DanielnetoDotCom** [comment]
I don't think the php.ini is regarding YouPHPTube script.

it is regarding your web server configuration.

you may contact dream host or try to google to fins a solution.
