### ISSUE TITLE
Please add a field for subtitle on each video

### ISSUE THREAD

**Issue by abamilod** [DanielnetoDotCom/YouPHPTube#158]
For build-in subtitle, I can add : ffmpeg -i {$pathFileName} -vf 'scale=-2:480,subtitles={$pathFileName}' -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -y {$destinationFile}

But for external subtitle such as .srt I need some help. Thank you

**Comment by DanielnetoDotCom** [comment]
YouPHPTube will always that code to encode your videos, we not support automatic subtitle now. but in the future we probably will let you upload a subtitle file with out need to encode the video with it.

**Comment by abamilod** [comment]
Thank you for taking this up for future updates
