### ISSUE TITLE
Rss Feed Download

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#1580]
Hi  Daniel,
have you change anything for Rss Feed?
check https://demo.youphptube.com/feed/

I can download them with Firefox 65.0.2 (64-Bit)

**Comment by DanielnetoDotCom** [comment]
I didn't change anything, and I guess that is the expected behavior

**Comment by mikweb2017** [comment]
but how strange before they were displayed as a normal Page

**Comment by DanielnetoDotCom** [comment]
don't you think that may be a browser update behavior?
I could not detect any difference on the code

**Comment by Andiweb87** [comment]
mikweb , all rss pages now can be downloaded not only the rss of youphptube, its a new change from the browsers.
