### ISSUE TITLE
Enabling sendfile breaks the images...

### ISSUE THREAD

**Issue by Criptos** [DanielnetoDotCom/YouPHPTube#1582]
![image](https://user-images.githubusercontent.com/4574233/54780330-0da1ab80-4bdf-11e9-9585-b6e6459667f3.png)

When used directly chorme trys to donwload the image. 

Enabling it allows me to download at the video manager interface, but breaks any other image at the site...

**Comment by Criptos** [comment]
I changed the .htaccess to this to fix the issue: 

From
       RewriteRule    ^videos/([A-Za-z0-9-_.]+)$ view/xsendfile.php?file=$1    [QSA]
To
       RewriteRule    ^videos/([A-Za-z0-9-_.]+mp4)$ view/xsendfile.php?file=$1    [QSA]

This limits xsendfile to mp4...only....

**Comment by Criptos** [comment]
No, actually when I enable sendfile as apache module, it completely breaks the site... 
Any advise?

**Comment by DanielnetoDotCom** [comment]
Did you add this code on apache.conf or on your virtual host file?

```
<Directory /var/www/YouPHPTube/>
    Options Indexes FollowSymLinks
    XSendFile on
    XSendFilePath /var/www/YouPHPTube/
    AllowOverride All
    Require all granted
    Order Allow,Deny
    Allow from All
</Directory>
```

**Comment by Criptos** [comment]
Now it works!!! 
Thanks...
