### ISSUE TITLE
Thank you again

### ISSUE THREAD

**Issue by inferno-prime** [DanielnetoDotCom/YouPHPTube#1583]
I just wanted to say thanks again. I see you added an option to allow Webm to be uploaded along with mp4. It's nice having another format to work with.

**Comment by DanielnetoDotCom** [comment]
thanks, what other formats?

**Comment by inferno-prime** [comment]
I meant that I can now direct upload webm along with mp4 that's all.

**Comment by DanielnetoDotCom** [comment]
thanks :)
