### ISSUE TITLE
Users 500

### ISSUE THREAD

**Issue by Allesanddro** [DanielnetoDotCom/YouPHPTube#1587]
HP Fatal error:  Uncaught Error: Call to undefined method YouPHPTubePlugin::getUsersManagerListButton() in /var/www/html/YouPHPTube/view/managerUsers_body.php:249
Stack trace:
#0 /var/www/html/YouPHPTube/view/managerUsers.php(24): include()
#1 {main}
  thrown in /var/www/html/YouPHPTube/view/managerUsers_body.php on line 249

when going on view/managerUsers.php im geting this

**Comment by ChrisSlS** [comment]
I was also able to identify this error, but no solution yet. I put away the old version. Look [68caeb9](https://github.com/DanielnetoDotCom/YouPHPTube/blob/68caeb912d11bd9428eea029f056b12edb723171/view/managerUsers_body.php) and replace with the current version if you ever want to access it during a fix

**Comment by DanielnetoDotCom** [comment]
Hi

I fixed it yesterday. sorry for this error;
