### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by honeyfairy** [DanielnetoDotCom/YouPHPTube#1593]
Hi there guys. Thank you for making this script, great stuff.
I have assumed that the search function is not usable from the previous issues: 
#https://github.com/DanielnetoDotCom/YouPHPTube/issues/287
#1432 

So, how could we integrate Google Custom search for now? Or any other workarounds?
Let me know because the search function is essential.

Regards

**Comment by DanielnetoDotCom** [comment]
@honeyfairy the issues are not clear for me.

I have never integrated Google Custom Search, maybe somebody else can help you with it.

**Comment by honeyfairy** [comment]
> @honeyfairy the issues are not clear for me.

Hi Daniel
The issue is that Search did not work.

But now I tested it and it seems to be working... Not sure what happened.

Is there an issue with the Search function on youphptube?

**Comment by DanielnetoDotCom** [comment]
I am not aware of any search issue
