### ISSUE TITLE
Some videos not playing

### ISSUE THREAD

**Issue by soapstreams** [DanielnetoDotCom/YouPHPTube#1596]
I have uploaded four episodes to my site, but 2 don't play.

I did direct upload to my encoder, but it won't play: http://soappirates.ch/video/sunset-beach-1-m010697

I imported another file to my encoder, but it won't play either: http://soappirates.ch/video/santa-barbara-ep-175-w040385

I embeded a youtube video link and it works great: http://soappirates.ch/video/santa-barbara-ep-173-m040185/page/1?

My encoder is at https://encoder.youphptube.com/?justLogin=1

Any ideas why those 2 aren't working?

Also, I paid for, installed and set up the BackBlaze plugin, but none of the videos I uploaded or linked to are getting stored in my Buckblaze bucket.

jdr

**Comment by DanielnetoDotCom** [comment]
I didnt check but sounds like the problem is your backblaze configuration

try to submit a video and check your log file.

I am pretty sure you will see an error.

**Comment by soapstreams** [comment]
What log file specifically? Thanks.

jdr

**Comment by DanielnetoDotCom** [comment]
The streamer log file, check here https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by soapstreams** [comment]
I had one error (a small typo in the name bucket), which I fixed. Now I get these errors and I have no idea how to fix this:

[28-Mar-2019 01:19:35 UTC] copy_to_B2 Start test.txt
[28-Mar-2019 01:19:36 UTC] BlackBlaze response ERROR: 400
[28-Mar-2019 01:19:36 UTC] BlackBlaze response ERROR Body: {
  "code": "bad_request",
  "message": "string does not start with quote",
  "status": 400
}

[28-Mar-2019 01:20:37 UTC] Array
(
    [headers] => Array
        (
            [Authorization] => 4_0021c3307a4038c0000000001_018b284f_b1a40a_acct_9Q_PlbckXOm8RQU5WWyfoSFxfzw=
        )

    [json] => Array
        (
            [accountId] => 
        )

)

[28-Mar-2019 01:20:37 UTC] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/plugin/Blackblaze_B2/vendor/gliterd/backblaze-b2/src/Client.php on line 127
[28-Mar-2019 01:20:38 UTC] BlackBlaze response ERROR: 400
[28-Mar-2019 01:20:38 UTC] BlackBlaze response ERROR Body: {
  "code": "bad_request",
  "message": "required field bucketId cannot be null",
  "status": 400
}

[28-Mar-2019 01:21:39 UTC] Array
(
    [headers] => Array
        (
            [Authorization] => 4_0021c3307a4038c0000000001_018b284f_b1a40a_acct_9Q_PlbckXOm8RQU5WWyfoSFxfzw=
        )

    [json] => Array
        (
            [bucketId] => 
        )

)

[28-Mar-2019 01:21:39 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#0 /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/Pr in /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186

**Comment by DanielnetoDotCom** [comment]
I think you still have misconfigurations

**Comment by soapstreams** [comment]
Are you serious? Obviously I "still have misconfigurations." That's what I get for my money, a dismissive reference to the obvious? I paid you to be a smarmy smart aleck? 

There are no instructions for the BackBlaze plugin that I have found. It didn't come with any and you haven't created a wiki entry for it. That's fine. But it's not all together obvious either and I don't think I am asking too much for a little clarification. Am I?

So I have a Backblaze account ID and I created a bucket. I then created a key and gave both read and write access. I used this application key (separate from the master application key) and the keyID that was generated from this process. 

On my site, I set the B2 Storage plugin preferences like this: 

1. The plugin is turned on; the bucket_name is the name of the bucket I created at my BackBlaze account; 
2. accountID is toggled off and I have no idea what that toggle does or doesn't do--can you please explain this setting;
3.  keyID is set the keyID provided when I created the key in my Backblaze account;
4. applicationKey is set to the application key generated when I created the key, NOT the master key that I can create in my account.
5. CDN_Link is toggled off and I have no idea what that toggle does or doesn't do--can you please explain this setting;
6. useDirectLink is also toggled off and I think I know what this is, but please explain this setting;
7. presignedRequestSecondsTimeout says 43200, but I don't know where that number comes from or what it means;
8. Lastly, usePublicBucket is also toggled off and I think I know what this is, but please explain this setting;

Can you please tell me in what ways  is my b2 storage plugin "misconfigured?" Thank you.

jdr

**Comment by DanielnetoDotCom** [comment]
What call my attention was this message:

`"message": "string does not start with quote",`

do you have a quote on some of your fields?


here is a sample of a site that has backblaze working

![image](https://user-images.githubusercontent.com/18009293/55176930-df811600-5160-11e9-97fe-97220407b6d9.png)

**Comment by soapstreams** [comment]
No, theres no quote at all. 

jdr

**Comment by DanielnetoDotCom** [comment]
email me your site admin and your Backblaze credentials and I will configure it for you.

developer@youphptube.com

**Comment by soapstreams** [comment]
Sent.

jdr

**Comment by DanielnetoDotCom** [comment]
I create new credentials on B2, also put the proper parameters and check to use a public bucket (because the bucket you created was public).

it is working now.

**Comment by soapstreams** [comment]
thx

**Comment by soapstreams** [comment]
Well, there's something else wrong. I just ran one of my youtube videos through the encoder, but it won't play on my site and it is not in my backblaze bucket. Any ideas?

[28-Mar-2019 18:29:05 UTC] youPHPTubeEncoder.json: start
[28-Mar-2019 18:29:05 UTC] youPHPTubeEncoder.json: Encoder receiving post
[28-Mar-2019 18:29:06 UTC] Do not need update duration: {}
[28-Mar-2019 18:29:06 UTC] youPHPTubeEncoder.json: Files Received for video 16: Santa Barbara, Ep# 191, R042585
[28-Mar-2019 18:30:02 UTC] ReceiveImage: Start receiving image
[28-Mar-2019 18:30:02 UTC] ReceiveImage: Encoder receiving post Array
(
    [image] => Array
        (
            [name] => thumbsmX5mvt.jpg
            [type] => application/octet-stream
            [tmp_name] => /tmp/phpcqJEZH
            [error] => 0
            [size] => 68676
        )

    [gifimage] => Array
        (
            [name] => 2756_tmpFile.mp4.gif
            [type] => application/octet-stream
            [tmp_name] => /tmp/php284FsI
            [error] => 0
            [size] => 643208
        )

)

[28-Mar-2019 18:30:02 UTC] ReceiveImage: Files Received for video 16: Santa Barbara, Ep# 191, R042585

**Comment by DanielnetoDotCom** [comment]
is that a newly uploaded file? (after the fix)

**Comment by DanielnetoDotCom** [comment]
BTW, today we released an update for the B2 plugin, it fixes some known bugs, that may help you.

**Comment by soapstreams** [comment]
Yes, I encoded/uploaded the video after the fix. I just downloaded B2 day before yesterday. Was it updated since then? Thanks.

jdr

**Comment by DanielnetoDotCom** [comment]
yes, was this morning, please download again and overwrite your plugin.

than try to submit a video again.

**Comment by soapstreams** [comment]
Excellent. Will do.

jdr

**Comment by soapstreams** [comment]
How do I update a plugin? Do I turn it off, delete the old and and reupload?

jdr

**Comment by DanielnetoDotCom** [comment]
just overwrite the files

**Comment by soapstreams** [comment]
I have no idea what has happened now. Why has the field you had my accountID turned into a toggle with no field to enter the accountID?

**Comment by DanielnetoDotCom** [comment]
Hi

I am not sure what you have done. but you can fix editing the JSON 

![image](https://user-images.githubusercontent.com/18009293/55231862-9a152500-5202-11e9-815c-b209e927ce3c.png)
