### ISSUE TITLE
Font-files needed on videos/configuration create event

### ISSUE THREAD

**Issue by avmesquita** [DanielnetoDotCom/YouPHPTube#1597]
Font-files needed on videos/configuration create event.

\videos\fonts\glyphicons*

[glyphicons.zip](https://github.com/DanielnetoDotCom/YouPHPTube/files/3015385/glyphicons.zip)

**Comment by DanielnetoDotCom** [comment]
Sorry, I dont understand this

**Comment by avmesquita** [comment]
When I installed into my server, install routine create video folder and include configuration.php and other files. But not font files and occours 404 error at console.

**Comment by DanielnetoDotCom** [comment]
the font files should not be on the videos directory, it should be on the view directory.

I guess you miss something on your configuration

**Comment by avmesquita** [comment]
Before installed fonts folder was not created.

![image](https://user-images.githubusercontent.com/646271/55201113-3eb24b00-51a0-11e9-81cb-150d84f5543c.png)

If, I change folder name like...

![image](https://user-images.githubusercontent.com/646271/55201178-8df87b80-51a0-11e9-9459-3012fd552304.png)

Console shows:
![image](https://user-images.githubusercontent.com/646271/55201190-a23c7880-51a0-11e9-968e-b4860cf7f789.png)

**Comment by avmesquita** [comment]
I changed this into my fork.
I need test before create a pull request.
Thanks.
