### ISSUE TITLE
Live Player Embed

### ISSUE THREAD

**Issue by nightstryke** [DanielnetoDotCom/YouPHPTube#160]
Is it possible to get the embed code for the live player like we can for normal videos? Like for example 

`<iframe width="560" height="315" style="max-width: 100%;max-height: 100%;" src="http://liveplayerurl" frameborder="0" allowfullscreen="allowfullscreen" class="YouPHPTubeIframe"></iframe>`

**Comment by mikweb2017** [comment]
![bildschirmfoto 2017-10-17 um 18 04 15](https://user-images.githubusercontent.com/30271757/31675755-dff9f3f8-b365-11e7-9be4-454490089994.png)

**Comment by nightstryke** [comment]
Thanks, apparently I wasn't paying attention. lol
