### ISSUE TITLE
Change image size

### ISSUE THREAD

**Issue by front-bittencourt** [DanielnetoDotCom/YouPHPTube#1600]
Hello, how could I make the image change from thumb to a different size. I changed the size in the div div css at first, but the image came in smaller size, getting distorted, how could it change?

**Comment by front-bittencourt** [comment]
?

**Comment by DanielnetoDotCom** [comment]
In the feature we have plans to make the image size customizable, but for now we do not have this option

**Comment by millzee01** [comment]
Did this get implemented? it would be handy to be able to change the size of the thumb
