### ISSUE TITLE
only 50 % cpu usage on mp4 encode

### ISSUE THREAD

**Issue by Allesanddro** [DanielnetoDotCom/YouPHPTube#1602]
https://i.imgur.com/Q0fWMZ7.png im only getting 50 % load so my question is can i optimize there something or increase the queue number?

**Comment by Allesanddro** [comment]
Server Specs
CPU Intel(R) Xeon(R) CPU D-1521 @ 2.40GHz 4c/8t
RAM 16gb ddr4 
space 14TB

**Comment by DanielnetoDotCom** [comment]
sorry, you can not increase the queue number

**Comment by Allesanddro** [comment]
but still why is it just using 50% of my cpu

**Comment by Allesanddro** [comment]
Well I also tried using the threads option didn't really helped iduno

YouPHPTube <notifications@github.com> schrieb am Mo., 1. Apr. 2019, 21:32:
