### ISSUE TITLE
Hello, the page has been playing buffer, OBS push is normal 

### ISSUE THREAD

**Issue by 1vivikun** [DanielnetoDotCom/YouPHPTube#1604]
Page play speed is not very fast, has been buffering state

The picture is not displayed, but the play is normal.

The interface is not displayed, but the playback is normal and has been buffered and loaded.

My server is very fast. There's nothing wrong with it.

**Comment by 1vivikun** [comment]
Page play speed is not very fast, has been buffering state

**Comment by 1vivikun** [comment]
How can I solve this problem?

**Comment by DanielnetoDotCom** [comment]
follow this here https://github.com/DanielnetoDotCom/YouPHPTube/issues/1599
