### ISSUE TITLE
Adding embed links

### ISSUE THREAD

**Issue by Andiweb87** [DanielnetoDotCom/YouPHPTube#1607]
Hi , if i embed add an link from another website videos in youphptube

https://goalgoal24.videostreamlet.net/embed/6KgO6JJfcd

is not generated thumbnail, and time of video.

**Comment by DanielnetoDotCom** [comment]
We do not support extract thumbs and other info from all sites.

can you specify that site are you grabbing?

**Comment by Andiweb87** [comment]
the main site is - > http://videostreamlet.net/ 

but have an option to create and using subdomains  for each account created  , mine is https://goalgoal24.videostreamlet.net

**Comment by DanielnetoDotCom** [comment]
we use youtube-dl app to extract image and info.

if you need to add it as a supported site, you may look for help with them

https://ytdl-org.github.io/youtube-dl/index.html
