### ISSUE TITLE
link "trending" results in 404

### ISSUE THREAD

**Issue by wn-siebert** [DanielnetoDotCom/YouPHPTube#1609]
hey,
i use .htaccess and nearly everythings works finde, just "trending" (linked to /trending) results in a 404-error.

is this a common error? has anyone the same problem?

chris

**Comment by DanielnetoDotCom** [comment]
Sorry, I can not reproduce this error

**Comment by wn-siebert** [comment]
okay, could you post me the coresponding line from .htaccess? i did a quick search in .htaccess and there is no entry for /trending.

**Comment by DanielnetoDotCom** [comment]
https://github.com/DanielnetoDotCom/YouPHPTube/blob/5bcfd61b277301385b3b7aae09b10851f45fb81f/.htaccess#L76

**Comment by wn-siebert** [comment]
okay, great, thx... for any reason, the "classic.htaccess" was my .htacces...

now it works! thx!
