### ISSUE TITLE
[rtmp @ 039bb640] Cannot open connection tcp:/

### ISSUE THREAD

**Issue by winklov** [DanielnetoDotCom/YouPHPTube#161]
FFMPEG.Exited
Streaming
[rtmp @ 039bb640] Cannot open connection tcp://noticiasgamesdahora.com:1935
rtmp://noticiasgamesdahora.com/live?p=1ac7fe883f0c3f4356f293f3a17967ad/59db2a37aded0: Unknown error

**Comment by winklov** [comment]
FFMPEG.Exited
Streaming
[rtmp @ 0098b4e0] Cannot open connection tcp://noticiasgamesdahora.com:1935
rtmp://noticiasgamesdahora.com/live?p=1ac7fe883f0c3f4356f293f3a17967ad/59db2a37aded0: Unknown error

Report written to "C:\ProgramData\vMix\streaming\streaming 20171018-124154.log"
ffmpeg version 2.8.git Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8.1 (rev2, Built by MinGW-W64 project)
  configuration: --enable-gpl --enable-version3 --enable-libx264 --enable-zlib --enable-libfaac --enable-nonfree --cpu=i686 --enable-nvenc
  libavutil      55.  2.100 / 55.  2.100
  libavcodec     57.  3.100 / 57.  3.100
  libavformat    57.  2.100 / 57.  2.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6.  9.100 /  6.  9.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.100 /  2.  0.100
  libpostproc    54.  0.100 / 54.  0.100
Guessed Channel Layout for  Input Stream #0.1 : stereo
Input #0, dshow, from 'video=vMix Video YV12:audio=vMix Audio':
  Duration: N/A, start: 19867.751000, bitrate: 1536 kb/s
    Stream #0:0: Video: rawvideo (YV12 / 0x32315659), yuv420p, 768x576, 29.97 tbr, 10000k tbn, 29.97 tbc
    Stream #0:1: Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s
[tcp @ 00987da0] TCP Buffer has been set to 6571008 bytes
[rtmp @ 0098b4e0] Cannot open connection tcp://noticiasgamesdahora.com:1935
rtmp://noticiasgamesdahora.com/live?p=1ac7fe883f0c3f4356f293f3a17967ad/59db2a37aded0: Unknown error

**Comment by DanielnetoDotCom** [comment]
Hi, I never did NGINX on windows, this is a NGINX issue, you may ask on its page for help https://github.com/nginx/nginx

**Comment by nightstryke** [comment]
If you're going to run nginx with rtmp on windows, I would suggest using an older pre-compiled variant than trying to compile it yourself it's a pain in the ass (forgive the language.)
[http://nginx-win.ecsds.eu/download/nginx%201.7.12.1%20Lizard.zip](http://nginx-win.ecsds.eu/download/nginx%201.7.12.1%20Lizard.zip)

**Comment by winklov** [comment]
thanx buys

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by Kingzhoudk** [comment]
I also have this problem with Linux
