### ISSUE TITLE
doNotIndentifyByEmail

### ISSUE THREAD

**Issue by weedogroup** [DanielnetoDotCom/YouPHPTube#1610]
Hiya, great script, I am blown away, I am a keen learner and having been playing and on using the switch for this element it is not removing emails from site.

I have Do not show user's email on the site highlighted.

**Comment by weedogroup** [comment]
my mistake, in profile it had no name to could not over ride, I take it. all sorted. my fault.

**Comment by DanielnetoDotCom** [comment]
Ok, thanks
