### ISSUE TITLE
AD_Server (AD_Server) Country not selecte

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#1611]
Hi Daniel,

I have problem add server if i select any Country after save is there showing all not selected Country
i checked also demo site same issue also is there.

**Comment by DanielnetoDotCom** [comment]
can you please screenshot the page where are you finding this error?

**Comment by gujarraju** [comment]
[Video3.zip](https://github.com/DanielnetoDotCom/YouPHPTube/files/3039703/Video3.zip)

please check attached file.

**Comment by DanielnetoDotCom** [comment]
you have to click on the green button "Add Location restriction"
