### ISSUE TITLE
Unable install Database

### ISSUE THREAD

**Issue by k7n2g** [DanielnetoDotCom/YouPHPTube#1612]
Unable to install database all pasword and user permissions okay, file permissions 777,  This is ERRORs:   There is no configuration.php file on server tried creating it not working  can someone  please tell me what to do  thank you.

[01-Apr-2019 15:14:40 UTC] PHP Warning:  require_once(videos/configuration.php): failed to open stream: No such file or directory in /var/www/html/YouPHPTube/index.php on line 126
[01-Apr-2019 15:14:40 UTC] PHP Fatal error:  require_once(): Failed opening required 'videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/html/YouPHPTube/index.php on line 126

**Comment by DanielnetoDotCom** [comment]
Make sure you run the installation script correctly and got no error during the installation.

**Comment by k7n2g** [comment]
https://www.screencast.com/t/P0cE5sLSY
No errors with install all fine just wont connect to mysql server  have tried now on three different VPS  installs  https://www.screencast.com/t/P0cE5sLSY
   Root password is correct tried another user,  Root can access Mysql with password no problem   IP: 45.77.226.99   PW: 3Z$z5#otds{LUJXX  database is root ABC123abacus1   

-----Original Message-----

**Comment by DanielnetoDotCom** [comment]
what OS are you using?

**Comment by k7n2g** [comment]
Hi Guys got ubuntu 16.04 got it connected now have reinstalled 3 times but now have main page  nothing else have set perrmisions to 777 and .htaccess to  600   tried 775 still nothing any ideas please.


-----Original Message-----

**Comment by DanielnetoDotCom** [comment]
Make sure you have installed the apache mod rewrite

**Comment by k7n2g** [comment]
Hi guys okay it turned out that server wasn't recognizing permissions have gone to reinstall os and everything all working okay thanks Dave


-----Original Message-----

**Comment by DanielnetoDotCom** [comment]
That is great
