### ISSUE TITLE
"media could not be loaded" / video 0 bytes

### ISSUE THREAD

**Issue by FastBlit** [DanielnetoDotCom/YouPHPTube#1613]
All video uploads show "media could not be loaded" error when played. When I click download video I receive a 0 byte file.

- Encoder works correctly and sends the right file to the streamer server, i can rsync the video file from the streamer server videos folder and it plays normally
- Databases installed correctly
- Compatibility check showing no errors
- Default theme / standard configuration
- No error in youphptube.log
- No error in apache error.log / access.log

I am wondering if there are any updated lines needed for a ssl apache vhost, besides that I cant come up with anything else.

```
<VirtualHost *:443>
ServerName sub.domain.com

DocumentRoot "/var/www/youphptube"
<Directory /var/www/youphptube>
  Options FollowSymlinks Indexes
  AllowOverride All
  Require all granted
</Directory>

Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /***
SSLCertificateKeyFile /***
</VirtualHost>
```

**Comment by DanielnetoDotCom** [comment]
can you make sure if the file was transferred?

check the file size.

also, make sure you are not using a CDN or apache mod security.

**Comment by FastBlit** [comment]
It is a command in the .htaccess file blocking access, replacing with a blank .htaccess gets the videos working. I will look through the .htaccess file later and find what is not working there for my config (ubuntu 18.04, apache2, hosted at a subdomain xxx.site.com).

**Comment by FastBlit** [comment]
Seems to be related to this where you mention adding some extra lines to the apache vhost for XSendFile and to comment out the xsendfile line in .htaccess file. If I try to use change to the apache vhost it breaks my video thumbnails so I will leave xsendfile off for now.

```
    XSendFile on
    XSendFilePath /var/www/YouPHPTube/
```

https://github.com/DanielnetoDotCom/YouPHPTube/issues/1582
https://github.com/DanielnetoDotCom/YouPHPTube/issues/1182

**Comment by DanielnetoDotCom** [comment]
I see if you do not have XSendFilePath proper configured it will fail for sure.

make sure you configure it https://github.com/DanielnetoDotCom/YouPHPTube/issues/1582#issuecomment-475604649

**Comment by FastBlit** [comment]
That's it I didn't fix the file path exactly, so XSendFile is working correctly and I turned it back on and have everything setup now. Thanks.
