### ISSUE TITLE
PPV Plugin Question

### ISSUE THREAD

**Issue by bobbyrabbit** [DanielnetoDotCom/YouPHPTube#1615]
Is it possible to add a user to a PPV video without them paying? The user will be paying for content on an external website, I would need to set the user up to view this video manually? I have the Subscription plugin, but am just trying to get my head around how the PPV plugin works.

**Comment by DanielnetoDotCom** [comment]
Yes, you can if you do it directly into the database

For now, I do not have this interface yet, but I will add this feature on the plugin in the future for sure.
