### ISSUE TITLE
../videos 403 Forbidden

### ISSUE THREAD

**Issue by soapstreams** [DanielnetoDotCom/YouPHPTube#1616]
Not sure what happened. I was looking at the logs, then went to refresh the page to see new entries and now I receive 403 Forbidden error. Everything seems to be working, including B2 plugin, but now I suddenly can't access https://soappirates.ch/videos. Any ideas? I chmod 755 and even tried 777, but still can't access that directory. Thanks.

jdr

**Comment by soapstreams** [comment]
Same problem with my encoder directory, https://soappirates.ch/encoder/videos

jdr

**Comment by DanielnetoDotCom** [comment]
This is not a problem, the videos directory must not be browsable.

**Comment by soapstreams** [comment]
It is a problem. I cant view the logs to find errors. Why is not browsable?

**Comment by DanielnetoDotCom** [comment]
for security reasons it is not browsable

to check error log see this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by soapstreams** [comment]
This hasn't happened before. Is there no way to make it browsable?

**Comment by DanielnetoDotCom** [comment]
if you want to make it readable (again, not recommended) those are rules on your .htaccess

For example, to deny access files and directory browse we use:

```
<Files routes.php>
Order Allow,Deny
Deny from all
</Files>
<Files PayPal.log>
Order Allow,Deny
Deny from all
</Files>
<Files youphptube.log>
Order Allow,Deny
Deny from all
</Files>
<Files youphptube.js.log>
Order Allow,Deny
Deny from all
</Files>
# Disable directory browsing
Options All -Indexes
```
