### ISSUE TITLE
Embed video with code

### ISSUE THREAD

**Issue by Andiweb87** [DanielnetoDotCom/YouPHPTube#1618]
any option to embed videos with code ? like the embed video with links.

thank you

**Comment by DanielnetoDotCom** [comment]
what kind of code? what kind of link?

**Comment by Andiweb87** [comment]
when embed videos with links https://snag.gy/08bXMu.jpg also have an option to copy paste a video code from another site and pas here like the embed link do.

**Comment by DanielnetoDotCom** [comment]
I need a sample of the code, so I can have an idea what are you talking about

**Comment by Andiweb87** [comment]
sorry , for ex this :

`<iframe class="contentVencher" width='100%' height='421px' frameborder='0' scrolling='no' allowfullscreen='true' webkitallowfullscreen='true' mozallowfullscreen='true' src='https://goalgoal24.veuclips.com/embed/FxrZeKv33w'></iframe>`

**Comment by DanielnetoDotCom** [comment]
it is an iframe embed code, if you want to embed it you should use the embed URL https://goalgoal24.veuclips.com/embed/FxrZeKv33w

**Comment by Andiweb87** [comment]
yes i know but if i embed this link show 00:00 time and is not generated the thumbnail

https://snag.gy/Zec7EB.jpg

**Comment by DanielnetoDotCom** [comment]
we use the youtube-dl app to extract thumbs and time from embed codes.

maybe this source is not supported. is impossible to support all internet sources.

**Comment by Andiweb87** [comment]
understand Daniel, ok is possible to add an option when embed this kind of videos from other sources to show or not the timer ?? will help to much.

https://snag.gy/1DLdQ0.jpg  , here under those 2 option , **show timer y/n**

thank you

**Comment by DanielnetoDotCom** [comment]
We are planning to release in future the option for you to edit the video length time.

we may include an option to hide it.

**Comment by Andiweb87** [comment]
Yes will be great if you add this option , for specific videos. Its what im trying to explain something to show or hide the timer when embed link video. Thanks
