### ISSUE TITLE
Encoder just Processing

### ISSUE THREAD

**Issue by k7n2g** [DanielnetoDotCom/YouPHPTube#1619]
Re-opened this as subject  installed Encoder tried Five times with different vps  no log file in videos/  all installed correctly  https://www.screencast.com/t/XqSGCL2x0xZb

Still processing install is on different Domain  This is error in log apache2  

81.139.231.148 - - [03/Apr/2019:09:13:04 +0000] "GET /YouPHPTube-Encoder/view/img/favicon.png HTTP/1.1" 200 19082 "http://encoder1.com/YouPHPTube-Encoder/install/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
81.139.231.148 - - [03/Apr/2019:09:13:36 +0000] "POST /YouPHPTube-Encoder/install/checkConfiguration.php HTTP/1.1" 200 298 "http://encoder1.com/YouPHPTube-Encoder/install/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
58.17.26.44 - - [03/Apr/2019:09:21:09 +0000] "GET / HTTP/1.1" 200 617 "-" "Mozilla/5.0 zgrab/0.x"

Can someone tell me please how to fix this and install

**Comment by DanielnetoDotCom** [comment]
What you post above looks like an access log NOT an error log.
try this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by k7n2g** [comment]
Sorry Daniel sorted this out but have one other problem cant access Encoder from streamer site it works occasionally this is log

[03-Apr-2019 20:48:41 UTC] YouPHPTube-Encoder sending confirmation to http://Cview.mobi/objects/youPHPTubeEncoderNotifyIsDone.json.php
[03-Apr-2019 20:48:41 UTC] YouPHPTube-Streamer confirmation answer {"error":false,"video_id":76}
[03-Apr-2019 20:48:41 UTC] {"error":false,"target":"http:\/\/Cview.mobi\/objects\/youPHPTubeEncoderNotifyIsDone.json.php","postFields":{"videos_id":76,"user":"admin","password":"824fdad815000b54ab0706d6ad83bea1","fail":0},"response_raw":"{\"error\":false,\"video_id\":76}","response":{"error":false,"video_id":76}}

can you tell me what i need to do to solve this please when you have time   Regards Dave

**Comment by DanielnetoDotCom** [comment]
I can not see any problem in the log above.

can you please delete the log. try to use the encoder again and provide us the complete log file?

**Comment by k7n2g** [comment]
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/3049570/youphptube.log)

This is whole Log my users cant access the encoder,  i can access it if i keep typing in site  username and PASSw  then eventually  Thanks Dave

**Comment by DanielnetoDotCom** [comment]
Hi

I can not see any login fail attempt on that log file.
that is why I asked you to delete the log file, try to log in and send me the log.

we will have fewer entries and will be easier to find it.

**Comment by k7n2g** [comment]
Hi Sorted now thanks Guys
