### ISSUE TITLE
Bug embed  video category

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#162]
![bug](https://user-images.githubusercontent.com/30271757/31675271-6bbfaed4-b364-11e7-9bb4-3c4528f83ed8.png)
![bildschirmfoto 2017-10-17 um 17 53 53](https://user-images.githubusercontent.com/30271757/31675219-43a83be6-b364-11e7-9699-0b9136146281.png)

bei embed video  i select   category test  but  Save  category  defaut

**Comment by DanielnetoDotCom** [comment]
OMG, thanks it is fixed now
