### ISSUE TITLE
Site is not working 

### ISSUE THREAD

**Issue by MayaV369** [DanielnetoDotCom/YouPHPTube#1620]
Hi,

Site is not working after the installation it show blank page 
url = http://*******/media/install/index.php

log message 

[Wed Apr 03 15:08:27 2019] [warn] [client *.*.*.*] mod_fcgid: stderr: PHP Notice:  Undefined variable: global in /home/*******/public_html/media/install/index.php on line 21, referer: http://www.*******.in/media/install/index.php

**Comment by DanielnetoDotCom** [comment]
if you complete the installation you should try to access it using http://*******/media/

**Comment by MayaV369** [comment]
No its not working, it show blank page 
HTTP ERROR 500

**Comment by DanielnetoDotCom** [comment]
what is in your log file?
check here https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by MayaV369** [comment]
[05-Apr-2019 14:10:31] PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the                  system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you us                 ed any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Moscow' for 'MSD/4.0/DST' instead' in /home/********/public_html/media/objects/include_config.php:8
Stack trace:
#0 /home/********/public_html/media/objects/include_config.php(8): DateTime->__construct()
#1 /home/********/public_html/media/videos/configuration.php(25): require_once('/home/********...')
#2 /home/********/public_html/media/install/index.php(24): require_once('/home/********...')
#3 {main}
  thrown in /home/********/public_html/media/objects/include_config.php on line 8

**Comment by MayaV369** [comment]
`[06-Apr-2019 11:51:51] PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Asia/Kolkata' for 'IST/5.0/no DST' instead' in /home/********/public_html/ypt/objects/include_config.php:8
Stack trace:
#0 /home/********/public_html/ypt/objects/include_config.php(8): DateTime->__construct()
#1 /home/********/public_html/ypt/videos/configuration.php(25): require_once('/home/********...')
#2 /home/********/public_html/ypt/view/index.php(12): require_once('/home/********...')
#3 {main}
  thrown in /home/********/public_html/ypt/objects/include_config.php on line 8
`

**Comment by DanielnetoDotCom** [comment]
Try google for that 

https://stackoverflow.com/questions/35455315/uncaught-exception-exception-with-message-datetime-construct

**Comment by MayaV369** [comment]
Thanks issue fixed
