### ISSUE TITLE
Change port

### ISSUE THREAD

**Issue by Tomasz31** [DanielnetoDotCom/YouPHPTube#1624]
Hi, 
I'm trying to change a port but it's not working properly for me.
I changed Apache2 port 
I changed /var/www/html/YouPHPTube/videos/configuration.php:
      AND   /var/www/html/YouPHPTube-Encodervideos/configuration.php:
      
`                 $global['webSiteRootURL'] = 'http://192.168.78.22:100/YouPHPTube/';`

I opend web page: http://192.168.78.22:100/YouPHPTube/
and the web is not working properly

"view-source" is:

`
        <link href="http://192.168.78.22/YouPHPTube/view/js/video.js/video-js.min.css" rel="stylesheet" type="text/css"/>
        <link href="http://192.168.78.22/YouPHPTube/view/css/player.css" rel="stylesheet" type="text/css"/>
        <link href="http://192.168.78.22/YouPHPTube/view/css/social.css" rel="stylesheet" type="text/css"/>
        <link href="http://192.168.78.22/YouPHPTube/view/js/jquery-ui/jquery-ui.min.css" rel="stylesheet" type="text/css"/>
`

`<source src="http://192.168.78.22/YouPHPTube/videos/_YPTuniqid_1_Low.webm" type="video/webm"><source src="http://192.168.78.22/YouPHPTube/videos/_YPTuniqid_1_Low.mp4" type="video/mp4"><source src="http://192.168.78.22/YouPHPTube/videos/_YPTuniqid_1_SD.webm" type="video/webm"><source src="http://192.168.78.22/YouPHPTube/videos/_YPTuniqid_1_SD.mp4" type="video/mp4"><source src="http://192.168.78.22/YouPHPTube/videos/_YPTuniqid_1_HD.webm" type="video/webm"><source src="http://192.168.78.22/YouPHPTube/videos/_YPTuniqid_1_HD.mp4" type="video/mp4"> `

It doesn't change addresses to add port 100

Tomasz

**Comment by Tomasz31** [comment]
IN:
/var/www/html/YouPHPTube/index.php  AND /var/www/html/YouPHPTube/route.php
IS:

`$basePath = parse_url ($global['webSiteRootURL'], PHP_URL_PATH);`

This line is removing the port number

**Comment by Tomasz31** [comment]
`//if(!empty($_SERVER['SERVER_NAME'])){
    // get the subdirectory, if exists
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
//    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
//}else{

    $global['webSiteRootURL'] = 'http://192.168.78.22:100/YouPHPTube/';

//}
`


Like that is working....

**Comment by DanielnetoDotCom** [comment]
@Tomasz31 

If you leave your config like the last message is it working fine?

**Comment by DanielnetoDotCom** [comment]
Great
