### ISSUE TITLE
About timer in embed videos.

### ISSUE THREAD

**Issue by Andiweb87** [DanielnetoDotCom/YouPHPTube#1625]
Daniel,  is possible to add an option when embed the videos from other sources, (not listed in youtube-dl app)  to show or not the timer ?? will help to much.

https://snag.gy/1DLdQ0.jpg , here under those 2 option , show timer y/n

thank you

**Comment by DanielnetoDotCom** [comment]
Answer here https://github.com/DanielnetoDotCom/YouPHPTube/issues/1618
