### ISSUE TITLE
Unable to secure directory -- w/ screenshots.

### ISSUE THREAD

**Issue by adamnoeve** [DanielnetoDotCom/YouPHPTube#1636]
I have followed the steps. See screenshots: 

![image](https://user-images.githubusercontent.com/4432175/55749287-8e014280-5a0e-11e9-9367-0662aaec37a5.png)

![image](https://user-images.githubusercontent.com/4432175/55749464-f94b1480-5a0e-11e9-9fc1-b40bbc49acfb.png)

![image](https://user-images.githubusercontent.com/4432175/55749563-3b745600-5a0f-11e9-88ac-658a644c604f.png)

**Comment by adamnoeve** [comment]
Jackpot777! is the password. By the way, my site still can't LiveStream. I
believe I've submitted a ticket for that. The SMTP also continues to fail
despite the suggestions.

Thanks in advance Daniel. I know you're working hard.

**Comment by DanielnetoDotCom** [comment]
I just test your Livestream and it is working fine.

https://tutorials.youphptube.com/video/youphptube-video-stream-with-obs-and-vmix

About your email configuration, I think you have something blocking your server to connect Google SMTP

**Comment by adamnoeve** [comment]
Okay I downloaded the OBS and got the streaming to work. So my site
visitors will need to download a separate program to Go Live?

**Comment by DanielnetoDotCom** [comment]
Yes, you need an RTMP publisher to do it
