### ISSUE TITLE
Install Issue: Access Denied Root @ Localhost

### ISSUE THREAD

**Issue by variable205** [DanielnetoDotCom/YouPHPTube#1639]
I've reviewed through the forums and unless there's a fix already, I apologize! I'm coming across an issue during the installation phase:

![image](https://user-images.githubusercontent.com/49423427/55770199-14d31100-5a49-11e9-98d6-9dc20933b21e.png)

I looked into the apache.log and found the following errors:

[Mon Apr 08 21:06:17.230461 2019] [php7:warn] [pid 2338] [client 127.0.0.1:49832] PHP Warning:  mkdir(): Permission denied in /var/www/html/YouPHPTube/objects/functions.php on line 158
[Mon Apr 08 21:09:41.057825 2019] [php7:notice] [pid 2817] [client 127.0.0.1:49884] PHP Notice:  Undefined variable: global in /var/www/html/YouPHPTube/install/index.php on line 21
[Mon Apr 08 21:10:36.848397 2019] [mpm_prefork:notice] [pid 2334] AH00169: caught SIGTERM, shutting down
[Mon Apr 08 21:10:37.018289 2019] [mpm_prefork:notice] [pid 2948] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Mon Apr 08 21:10:37.018492 2019] [core:notice] [pid 2948] AH00094: Command line: '/usr/sbin/apache2'
[Mon Apr 08 21:10:39.355114 2019] [php7:notice] [pid 2949] [client 127.0.0.1:49904] PHP Notice:  Undefined variable: global in /var/www/html/YouPHPTube/install/index.php on line 21

The first line showing "Permission Denied" may lead to something, but I've already provided write access to the YouPHPTube/videos folder

I apologize if I'm missing something obvious, and any help is appreciated!

**Comment by SubjectXXX** [comment]
To whom you gave write access on /videos?

Make owner of videos www-data and chmod it to 777 for testing and check if it works..

**Comment by SubjectXXX** [comment]
Could also be a problem with writing config file..

**Comment by variable205** [comment]
> Could also be a problem with writing config file..

Ya, agreed. I think I screwed something up in the installation. Thanks for getting back to me. I'll wipe and resow. Will tag back later

**Comment by variable205** [comment]
Just re-installed the pre-req's and still getting he same issue. I've also went ahead and made the owner of videos www-data and chmodd'd to 777

[Wed Apr 10 21:16:41.836530 2019] [php7:warn] [pid 17693] [client 127.0.0.1:55926] PHP Warning:  mkdir(): Permission denied in /var/www/html/YouPHPTube/objects/functions.php on line 158
[Wed Apr 10 21:18:48.047777 2019] [mpm_prefork:notice] [pid 17689] AH00169: caught SIGTERM, shutting down
[Wed Apr 10 21:18:48.193722 2019] [mpm_prefork:notice] [pid 18154] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Wed Apr 10 21:18:48.193843 2019] [core:notice] [pid 18154] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 10 21:18:55.671579 2019] [php7:notice] [pid 18155] [client 127.0.0.1:55964] PHP Notice:  Undefined variable: global in /var/www/html/YouPHPTube/install/index.php on line 21

I also found this in the mysql error log as well: 
2019-04-11T02:20:04.018781Z 4 [Note] Access denied for user 'root'@'localhost'
2019-04-11T02:23:29.032982Z 5 [Note] Access denied for user 'root'@'localhost'

Which is odd because I can log into the mySQL instance (with no special characters) for root, with no issues:

root@<server>:/var/log/mysql# mysql -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 6
Server version: 5.7.25-0ubuntu0.18.04.2 (Ubuntu)

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>


Would the system admin password WITH special characters screw up the script?

**Comment by SubjectXXX** [comment]
You have two problems:
1. script cannot create ypt_root_folder/videos/ folder. Why, I dont know, neither will Daniel know. Remove videos folder and try again, script should be able to create it and write to it. I have 755 on ypt folder in /var/www/html/ and root as owner and did have any problems with install..

2. using mysql with -u root -p command is the same as only using mysql, since root already has a auth pipeline into mysql, thus root doesnt need to auth to access to mysql. Google for more info.
Thus, always create a DB user that only has correct permissions on database that it needs.
 - go to mysql with root (usually executing mysql is enough)
 - create database named youPHPTube: CREATE DATABASE youPHPTube;
 - create user: GRANT ALL PRIVILEGES ON youPHPTube TO 'ypt_db'@'localhost' IDENTIFIED BY 'super_secret_password123';
 - enter this data on your install screen.

Should work.

**Comment by variable205** [comment]
Thanks for that! That did work! The only thing I had to modify with your command syntax was the following:

create user: GRANT ALL PRIVILEGES ON youPHPTube TO 'ypt_db'@'localhost' IDENTIFIED BY 'super_secret_password123';

create user: GRANT ALL PRIVILEGES ON *.* TO 'ypt_db'@'localhost' IDENTIFIED BY 'super_secret_password123';

otherwise mysql would complain about a database not selected or something silly. I know it was there, I had made it and it was confirmed:
mysql> CREATE DATABASE youPHPTube;
Query OK, 1 row affected (0.00 sec)

Regardless, I've been met with the congratulatory screen and seems to be working now. Thanks Subject!

**Comment by SubjectXXX** [comment]
Sounds like you have created a possible problem in the future.

Why not just select the correct database?

**Comment by variable205** [comment]
> Sounds like you have created a possible problem in the future.
> 
> Why not just select the correct database?

I tried to select it. When I did I would get an error stating that the "database was not selected". Which again, is strange because I made it with no problems. 

But yup, you definitely called it; because I now can't log into the youPHPtube admin console using that same user account or with root *sigh*.

And if I now attempt to select the correct database I'm met with a new error:
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ': GRANT ALL PRIVILEGES ON youPHPTube TO 'ypt_db'@'localhost' IDENTIFIED BY '<redacted>' at line 1

**Comment by variable205** [comment]
I may end up redoing it again and use the same guide like last time: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-YouPHPTube-version-4.x-or-newer

**Comment by variable205** [comment]
I had decided to go with the Ubuntu 16.X route and the installation went fine. The only problem I'm having now is signing into the admin console, using root and database password. I've also tried the usual root system password as well I get prompted with a base username and password:

![image](https://user-images.githubusercontent.com/49423427/56056633-6a960a80-5d22-11e9-94ae-dcdf2afcab64.png)

**Comment by SubjectXXX** [comment]
I'm running on Ubuntu 18.0.4 and it installs and works fine.

You defined admin password at the installation screen. If you missed that, mistyped or something, then either reinstall ypt (purge YPT Database and remove videos folder) or go play into user table in YPT database, its easy to hack password in there..

**Comment by variable205** [comment]
Just tested it, and mysql would deny access if I purposely put in the incorrect password. Once the correct password is placed, I get access.

The login to the admin console is directly correlated to the mysql root account and pass, correct? There's no special characters either

**Comment by SubjectXXX** [comment]
No, there is a separate password for admin, its not the same as for DB, at least it shouldn't be..

Like I said, either reinstall and be carefull which parameters you enter or go to mysql and overwrite admin password directly in database..

**Comment by variable205** [comment]
Forgive me for my confusion. But what's the user and pass that reflects the admin console? Like, which fields in the "pre-setup" is used?

**Comment by SubjectXXX** [comment]
Sorry, I dont have installation screen nearby..

**Comment by variable205** [comment]
Oh I'm a dummy. Okay, it's actually just "admin" as the username and whatever password you placed in at the end. This may push me to go back to 18.x and try that again, now that I know. 

I think I'm good now. Thanks subject, and for putting up with people like me :-)

**Comment by SubjectXXX** [comment]
No worries, here to help!

**Comment by catalin1986** [comment]
Sorry!
Connect Error (1698) Access denied for user 'root'@'localhost'
what to do?

**Comment by DanielnetoDotCom** [comment]
Probably wrong credentials

**Comment by catalin1986** [comment]
I follow step by step the guide,and 1234 is not a hard to remember pasa:) I
try again just how,maiby if do you want to help i give you the server ip
user and pass

mar., 28 ian. 2020, 12:57 Daniel Neto <notifications@github.com> a scris:

**Comment by DanielnetoDotCom** [comment]
If you want you can hire us to install it for you, check here https://www.youphptube.com/services

**Comment by catalin1986** [comment]
no thankx,becouse you make the installation like this to have a problem
only to make a salle,no thankx . i will google the trick you put in the
install . all setup are green only install get error Sorry!

Connect Error (1698) Access denied for user 'root'@'localhost' . i
setup the root pass 1234 , or are the pass or the Database Name

**Comment by catalin1986** [comment]
root have acces


+------------------+-----------+-----------------------+
| User             | Host      | plugin                |
+------------------+-----------+-----------------------+
| root             | localhost | auth_socket           |
| mysql.session    | localhost | mysql_native_password |
| mysql.sys        | localhost | mysql_native_password |
| debian-sys-maint | localhost | mysql_native_password |
+------------------+-----------+-----------------------+
4 rows in set (0.00 sec)

**Comment by catalin1986** [comment]
and "voila"  Your system is installed, remove the
/var/www/html/YouPHPTube/install directory to continue

**Comment by catalin1986** [comment]
i use :

Short steps are:

sudo mysql -u root
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'test';

Note: here test is a new password for the root user. Also, remember to run
the command sudo service mysql restart after altering the user.

---

*Option 1:*

$ sudo mysql -u root # I had to use "sudo" since is new installation

mysql> USE mysql;
mysql> UPDATE user SET plugin='mysql_native_password' WHERE User='root';
mysql> FLUSH PRIVILEGES;
mysql> exit;
$ service mysql restart

*Option 2:* (replace YOUR_SYSTEM_USER with the username you have)

$ sudo mysql -u root # I had to use "sudo" since is new installation

mysql> USE mysql;
mysql> CREATE USER 'YOUR_SYSTEM_USER'@'localhost' IDENTIFIED BY '';
mysql> GRANT ALL PRIVILEGES ON *.* TO 'YOUR_SYSTEM_USER'@'localhost';
mysql> UPDATE user SET plugin='auth_socket' WHERE User='YOUR_SYSTEM_USER';
mysql> FLUSH PRIVILEGES;
mysql> exit;
$ service mysql restart

**Comment by SubjectXXX** [comment]
Wau, you really are a douchebag.. Saying that Daniel hid something just to promote his service on an opensourced FREE product..

This software has at least thousand installations without a problem.. Surely is not Daniel's fault that you are doing a job that you are not qualified to do.

@DanielnetoDotCom : again, kudos to you for this software. Just ignore this kind of (ab)users..

**Comment by catalin1986** [comment]
Ok how you say,you.right me rong,is a bug with the root and ask money to
fix,what i say roung ? I give you  all the fix for that

mar., 28 ian. 2020, 13:57 Anze <notifications@github.com> a scris:

**Comment by SubjectXXX** [comment]
Its not bug, its your miss-configuration..

I didnt have this problem, doubt alot of people will have it..

**Comment by catalin1986** [comment]
You right,on windows test and ubuntu 16 all work fine in first antempt,on
ubuntu 18,my mistake was to ask for help here. Wana stop now?

mar., 28 ian. 2020, 14:09 Anze <notifications@github.com> a scris:

**Comment by SubjectXXX** [comment]
No, your mistake was to accuse Daniel that he is implementing bugs on purpose just to make money out of them.

Sure I can stop, but would expect at least an apology to @DanielnetoDotCom tho, if not even some small donation to his paypal account for false accusations..

**Comment by catalin1986** [comment]
No thankx,him ask money to give me one line of linux code :),i write and
ask to help other,but if i pay and the next one need to pay,not corect for
a free comunity

mar., 28 ian. 2020, 14:13 Anze <notifications@github.com> a scris:

**Comment by DanielnetoDotCom** [comment]
> Wau, you really are a douchebag.. Saying that Daniel hid something just to promote his service on an opensourced FREE product..
> 
> This software has at least thousand installations without a problem.. Surely is not Daniel's fault that you are doing a job that you are not qualified to do.
> 
> @DanielnetoDotCom : again, kudos to you for this software. Just ignore this kind of (ab)users..

I apprecciate your comment

**Comment by catalin1986** [comment]
Normal to apreciate the comment but you ask for money for a simple
question,i waste more time to replay here

mar., 28 ian. 2020, 14:19 Daniel Neto <notifications@github.com> a scris:

**Comment by DanielnetoDotCom** [comment]
I sent you to the services page because is clear for me you do not have the knowledge needed to make a correct installation.
The error you posted has nothing to do with AVideo, that was, a basic error, that you should search for help with the MySQL community or on Stackoverflow
I believe it would save you a lot of time to hire the services. but if you want to use the system to learn, you are welcome and feel free to do it. but one thing you should learn before try that, is learn how to ask for free help.

**Comment by catalin1986** [comment]
I use for test,i do not know linux,or other language,and you right maiby i
need to use google and not to ask 'real person' ,i search and i find what
dar roung,we chose this teader?

mar., 28 ian. 2020, 14:26 Daniel Neto <notifications@github.com> a scris:
