### ISSUE TITLE
Nao faz login

### ISSUE THREAD

**Issue by PlayxPE** [DanielnetoDotCom/YouPHPTube#164]
Nao quer fazer login não sei porque

**Comment by DanielnetoDotCom** [comment]
Tente isso https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
