### ISSUE TITLE
New feature bruteForeceBlock?!

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1644]
bruteForeceBlock: maxCon: 20 => secondTimeout: 5 | IP: 212.xxx.xxx.xxx | count:21

Is there a new feature added that controls how many connections from same IP is possible?

Where can I fine tune it? Since my browser triggers more than 20 requests for each gif on a front page.

**Comment by DanielnetoDotCom** [comment]
hi, for now it is hard coded here
https://github.com/DanielnetoDotCom/YouPHPTube/blob/72f647b7d1fa1faa5e309aa5dee36e7e036ebad2/objects/functions.php#L1586

soon I will release an update that you will be able to customize the parameters on the configuration.php file

**Comment by SubjectXXX** [comment]
Hmm, I checked your solution and I think that instead of die(), you could rather use sleep() for timeout, this way, DOS is still "prevented" and user doesnt get that ugly error on screen.

**Comment by SubjectXXX** [comment]
I have reorganised the code a bit, will create pull request..

**Comment by DanielnetoDotCom** [comment]
Thanks, I appreciate that
