### ISSUE TITLE
Site Blocked again...

### ISSUE THREAD

**Issue by BigmIkeX** [DanielnetoDotCom/YouPHPTube#1648]
I am trying to moderate users who violate the site terms.  but somehow YOUPHPTUBE keeps blocking my site? How is this possible? is there back door access to my setup? Is this even in the terms?
How do I unblock this?....

**Comment by DanielnetoDotCom** [comment]
what is your site URL?

**Comment by BigmIkeX** [comment]
https://media.xphunk.com/tube

**Comment by DanielnetoDotCom** [comment]
Probably porn content again

**Comment by BigmIkeX** [comment]
How does it block my site though?
I moderate best I can and delete whatever is there. How does blocking gain access to my site? And is this the only method to get ingredients unblocked?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DanielnetoDotCom** [comment]
We did not block you to access your site, it should be something else.

we block you to use the encoder.

**Comment by BigmIkeX** [comment]
/encoder is the site blocked

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BigmIkeX** [comment]
How is the site blocked from my local network?  Being is running on my local server?
How do I unblock it?

**Comment by DanielnetoDotCom** [comment]
Sorry, I can not unblock this site.

**Comment by BigmIkeX** [comment]
That doesn't answer all my questions?... How are you able to block my site? This seems pretty suspect. Like there is back-door access to my server using this app.
Nothing in the terms says you have the ability to do this.

**Comment by BigmIkeX** [comment]
Deleted and Uninstalled YouPHPTube. 
Just going to leave this right here.
http://youphptube.info/2018/09/10/so-today-daniel-santos-neto-of-youphptube-thought-it-was-a-good-idea-to-again-put-viruses-into-our-server-and/

**Comment by JeffersonSimonJS** [comment]
My encoder site has been blocked and it asking for site verification.
It’s actually an Intranet site an im following the term and condition of Youphptube ..still...i cant upload videos in my site ...
What’s the problem ?? Solution plz

**Comment by DanielnetoDotCom** [comment]
@JeffersonSimonJS what is your URL?

**Comment by JeffersonSimonJS** [comment]
Videos.karunya.edu    This is my url

**Comment by DanielnetoDotCom** [comment]
@JeffersonSimonJS this site is not banned or blocked should be something else

**Comment by JeffersonSimonJS** [comment]
I was not able to upload videos in encoder 
It is displaying as error line with the verification cmd

**Comment by DanielnetoDotCom** [comment]
you should be able to upload, even if the verification fail.

are you sure you have the latest version?
