### ISSUE TITLE
Hospedagem 

### ISSUE THREAD

**Issue by PlayxPE** [DanielnetoDotCom/YouPHPTube#165]
Onde posso hospedar gratuitamente?

**Comment by DanielnetoDotCom** [comment]
Hospedagens gratuitas, provavelmente so suportarão o player, mas não o encoder.
O Amazon até suporta o encoder, mas até um certo ponto depois começa a cobrar. mas esta cobrança para mim é uma caixa preta. vou colocar aqui alguns links: 
https://tutorials.youphptube.com/video/youphptube-on-000webhost
https://tutorials.youphptube.com/video/get-a-free-professional-hosting-for-youphptube-with-easytube-club
https://tutorials.youphptube.com/video/create-a-web-server-video-sharing-for-free-in-10-minutes

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
