### ISSUE TITLE
navbar search and language buttons

### ISSUE THREAD

**Issue by codelabinf** [DanielnetoDotCom/YouPHPTube#1653]
Hi, I need to remove the search engine (mysearch) and the language button from the navbar. Could you tell me how it is done? Please.
Thank you very much

**Comment by DanielnetoDotCom** [comment]
we do not have an option to remove it. you will need to manually remove it from the code

**Comment by SubjectXXX** [comment]
Its easy:

go to 

and enter

**Comment by DanielnetoDotCom** [comment]
@SubjectXXX solution is perfect, so you don't have to change the code and will still be able to follow the updates

**Comment by SubjectXXX** [comment]
He might need to include <style> tags around those suggested lines tho..

**Comment by codelabinf** [comment]
It works perfect! Thank you so much!
