### ISSUE TITLE
Category selection defaults to the first category

### ISSUE THREAD

**Issue by SilentMF** [DanielnetoDotCom/YouPHPTube#166]
When using the Embed a Video button and choosing the category it goes back to the first category upon saving it. For example if I choose category "Romantic" when I hit save it defaults back to the first category "Funny". However I can then hit the edit button and change the category back to "Romantic" and it will save the category correctly.

**Comment by mikweb2017** [comment]
https://github.com/DanielnetoDotCom/YouPHPTube/issues/162
please upgrade youPHPtube now git pull
it gefixt last evening

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
