### ISSUE TITLE
Obsolete code in functions.php

### ISSUE THREAD

**Issue by SubjectXXX** [DanielnetoDotCom/YouPHPTube#1661]
It could be a simple mistake or I'm not seeing something, thus I dont want to fix it on my own.

objects/functions.php@499:

you have
    
    else if (strpos($link, 'youtu.be') !== false) {

but then next else if has the same condition @508. This check is pointless, since in this case, condition is always gonna be handled by line 499. 
BUT, you do have different regex checkings there in these two conditions, so please check, which one is better one..

Same happens at line 587 and 595 with duplicate of

    else if (strpos($link, 'twitch.tv/videos') !== false) {

**Comment by DanielnetoDotCom** [comment]
The youtu.be you are right, I am sending a fix

the twitch the code is correct, are one for video and another one for channels

**Comment by SubjectXXX** [comment]
Nope, twitch is also wrong.

    else if (strpos($link, **'twitch.tv/videos'**) !== false) {
        //extract the ID
        preg_match(
                '/\/\/(www\.)?twitch.tv\/videos\/([a-zA-Z0-9_-]+)$/', $link, $matches
        );

        $id = $matches[2];
        return '//player.twitch.tv/?video=' . $id . '#';
    } else if (strpos($link, **'twitch.tv/videos'**) !== false) {
        //extract the ID
        preg_match(
                '/\/\/(www\.)?twitch.tv\/[a-zA-Z0-9_-]+\/v\/([a-zA-Z0-9_-]+)$/', $link, $matches
        );

        $id = $matches[2];
        return '//player.twitch.tv/?video=' . $id . '#';
    }

**Comment by DanielnetoDotCom** [comment]
Sorry, you are correct again
