### ISSUE TITLE
I do not know what to write the problem.

### ISSUE THREAD

**Issue by saloom21** [DanielnetoDotCom/YouPHPTube#168]
You can see the problem in this video. [https://youtu.be/qcLmJG-rYI0](url)

**Comment by mikweb2017** [comment]
please post your youphptube.log   paht to log  encodersite /videos/

**Comment by DanielnetoDotCom** [comment]
Yeah, the log file is needed here, check this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by saloom21** [comment]
this is my log. [https://drive.google.com/drive/folders/0B3Hr896UFsouelAyakJYOEZZTWM?usp=sharing](url)

my hope, can be found the solution. Thanks

**Comment by DanielnetoDotCom** [comment]
Hi
I found this on both log files:

```
[20-Oct-2017 05:27:10 Asia/Jakarta] PHP Notice:  Undefined variable: global in /var/www/html/video-Encoder/objects/Object.php on line 82
[20-Oct-2017 05:27:10 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to a member function real_escape_string() on null in /var/www/html/video-Encoder/objects/Object.php:82
Stack trace:
```

this error regarding this method
![image](https://user-images.githubusercontent.com/18009293/31800816-e4769da4-b519-11e7-816d-af84005bc0f3.png)


I still not sure what is going on.
can I see your configuration.php file? what PHP version are you using? what mysql version?

**Comment by saloom21** [comment]
here is the file. Config, Php version and mysql version.
[Configuration file.zip](https://github.com/DanielnetoDotCom/YouPHPTube/files/1400524/Configuration.file.zip)

**Comment by saloom21** [comment]
[File.zip](https://github.com/DanielnetoDotCom/YouPHPTube/files/1400623/File.zip)

**Comment by saloom21** [comment]
hai Mr. Daniel. How about this.

**Comment by DanielnetoDotCom** [comment]
can you show your phpinfo() output?

**Comment by saloom21** [comment]
[phpinfo.zip](https://github.com/DanielnetoDotCom/YouPHPTube/files/1429294/phpinfo.zip)

**Comment by DanielnetoDotCom** [comment]
Looks like your php/mysql installation are ok.
I have no glue what is wrong with your code.
did you change any file code?
try do make a fresh git clone and install again.

**Comment by saloom21** [comment]
I did not change anything. I just follow step by step like your video.
Thanks Mr. Daniel.

**Comment by DanielnetoDotCom** [comment]
Can you please try to make a fresh installation on it?

**Comment by saloom21** [comment]
as you suggest. I will make it from the beginning

**Comment by DanielnetoDotCom** [comment]
@saloom21 could you get it to work?

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
