### ISSUE TITLE
Features Request - Changes to Live Chat & Live Streaming

### ISSUE THREAD

**Issue by nightstryke** [DanielnetoDotCom/YouPHPTube#169]
Hey this is just a request thread of what I and maybe others might like to see as far as features for the Live Chat and Live Streaming aspect of YouPHPTube. Yes I know that requests are on the lowest priority with this project as you have many bugs to work out with the code including security, but I wanted to have a definitive list for reference.

**Wanted Features for Live Stream Chat:**
- Only allow registered users to send Chat Messages
- Ability to set Chat Moderators
- Ability to Ban Tolls/Abusive Users
- Ability to Delete Chat Messages/Comments left by Tolls/Abusive Users

**Wanted Features for Live Stream:**
- Ability to set Live Stream on for all users or until they reach a number of subscribers
- Ability to ban/block users who leave abusive/trolling comments from YouPHPTube Channel
- Ability to have the Share, Embedm Email Option on the Live Stream Page

@DanielnetoDotCom I know you're extremely busy working on YouPHPTube and I wish I knew PHP to help you even the smallest amount, but unfortunately my php knowledge is limited to using phpinfo and php includes.

**Comment by DanielnetoDotCom** [comment]
Hi @nightstryke 

Thanks for sharing your ideas

> Only allow registered users to send Chat Messages
> Ability to set Chat Moderators
> Ability to Ban Tolls/Abusive Users
> Ability to Delete Chat Messages/Comments left by Tolls/Abusive Users

YouPHPTube will have a new chat plugin. and those features will be on it.

> Ability to set Live Stream on for all users or until they reach a number of subscribers

This is hard to do, may be in the future

> Ability to ban/block users who leave abusive/trolling comments from YouPHPTube Channel

The comment system will be improved and maybe these functions are among these improvements

> Ability to have the Share, Embedm Email Option on the Live Stream Page

Can you give more details about it?

**Comment by nightstryke** [comment]
@DanielnetoDotCom I'm not very good at explaining, so I made a picture using screenshots from your demo site to help explain it better.

![untitled](https://user-images.githubusercontent.com/17477021/31779109-51b0fdb0-b4c0-11e7-909d-fe03c5187e5c.png)

**Comment by DanielnetoDotCom** [comment]
Understood.
I will probably do that too :)

**Comment by nightstryke** [comment]
@DanielnetoDotCom Awesome, sorry I'm not the best at explaining things.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
