### ISSUE TITLE
Multiple categories

### ISSUE THREAD

**Issue by Knah-Tsaeb** [DanielnetoDotCom/YouPHPTube#17]
I would like to add video in multiple categories.

**Comment by DanielnetoDotCom** [comment]
For now you cant
You have to duplicate the video if you need to

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by Krystian95** [comment]
This should be great!! 😃

**Comment by akhilleusuggo** [comment]
@Krystian95 yes , me too I wants this option . Some videos needs to be in multiple categories

**Comment by Krystian95** [comment]
@DanielnetoDotCom is there any update info (or roadmap) about this fantastic feature? 🙂

**Comment by DanielnetoDotCom** [comment]
I will probably add this in the future, but for now, it is not the priority
