### ISSUE TITLE
Video Statistic not showing correct data

### ISSUE THREAD

**Issue by stoneubi** [DanielnetoDotCom/YouPHPTube#170]
Hi there,

first I would thank you for this great project. YouPHPTube is amazing. 

I do have 3 different installations and two of them do not show correct data within the video statistic tab. The problem is, that on the left hand side at the "Color Legend" nothing is displayed. I do have one test video on the page and it is stored on the local machine. Everything works fine. Only the statistic do have problems. I already deleted everything from the video_statistic table but the result was the same. 

I'm on the latest version. 

Please see attached screenshot. 

How can I fix this?

Thanks and best regards,
Stone
![isse](https://user-images.githubusercontent.com/32926093/31762903-fcfe1f30-b4bc-11e7-91ca-d65cf1b979e4.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, how many videos do you have? do you have a link and user that I can check?

**Comment by stoneubi** [comment]
Dear Daniel,

thank you for your replay. 10 Videos listed. I sent you an email with the link and login. 

Many thanks
Stone

**Comment by DanielnetoDotCom** [comment]
@stoneubi I  have not receive your email? what is the sender email?

**Comment by stoneubi** [comment]
Dear Daniel,yesterday I used your contact form at https://youphptube.com/#contact to send the email. My sender email ist stoneubi@eclipso.atAnyhow here are the details:https://mitleichtigkeit.at/mtubeYour Username: danielYour Password: youphptube2017Many thanks for your support. Best regards,StoneubiIf this post is visible in github, please remove the details and email address. 
--- Ursprüngliche Nachricht ---Von: YouPHPTube <notifications@github.com>Datum: 20.10.2017 03:11:26An: DanielnetoDotCom/YouPHPTube <YouPHPTube@noreply.github.com>Betreff: Re: [DanielnetoDotCom/YouPHPTube] Video Statistic not showing correct data (#170)
@stoneubi I have not receive your email? what is the sender email?
—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

 

// <![CDATA[
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DanielnetoDotCom/YouPHPTube","title":"DanielnetoDotCom/YouPHPTube","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DanielnetoDotCom/YouPHPTube"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DanielnetoDotCom in #170: @stoneubi I  have not receive your email? what is the sender email?"}],"action":{"name":"View Issue","url":"https://github.com/DanielnetoDotCom/YouPHPTube/issues/170#issuecomment-338079065"}}}
// ]]>
----Ihre E-Mail-Postfächer zentral an einem Ort. Jetzt wechseln und alte E-Mail-Adresse mitnehmen! https://www.eclipso.at.

**Comment by DanielnetoDotCom** [comment]
Hi, the statistics shows you only the videos you manage, only admin can see all videos.
Do you think that is the issue?

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by republicus** [comment]
I am reviving this issue because my dashboard appears identical to the OP of this issue. My account has videos with views but several charts are missing data. Admin view appears the same.

![dashboard](https://user-images.githubusercontent.com/47370709/59212764-410e2980-8b81-11e9-84b7-fb79ef582638.PNG)

**Comment by DanielnetoDotCom** [comment]
@republicus , I am not sure what happening, please check your log file
