### ISSUE TITLE
Encoder is NOT working........

### ISSUE THREAD

**Issue by tdcpepsi** [DanielnetoDotCom/YouPHPTube#173]
When I try to upload a video using the encoder nothing happens after the upload.

**Comment by mikweb2017** [comment]
please  check your youphptube.log  unter  videos  for  more infomation

**Comment by tdcpepsi** [comment]
Why does it take so long to encode the videos??? I've been waiting for almost 2 days for the videos that I uploaded to show in my site???? They show under "my videos" as encoding but it's taking way too long.

**Comment by DanielnetoDotCom** [comment]
What encoder did you use?
if you use https://encoder.youphptube.com/ it may be deleted.
the public encoder is shared and slow, many people use it at the same time.
if you have many videos you should consider to install your private encoder.
will be much faster, and only you will be able to delete or send files.

**Comment by tdcpepsi** [comment]
An encoder is the same as a video converter....correct?

I know hardly anything about encoders and I want to make sure that I understand. Can you share some links and are they easy to install for the site??? I have a dedicated server, is there an encoder already on the server???

**Comment by mikweb2017** [comment]
https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x---For-YouPHPTube-Encoder

i have 2 site ono ist for videos and one  for encoder

**Comment by tdcpepsi** [comment]
Ok, also ...why does the gif's make the site load slow???

**Comment by DanielnetoDotCom** [comment]
@tdcpepsi gif, is an sequence of images in only one image, usually an animated gif is larger the jpegs images. We use gifs for all our mouse over video thumbs, maybe that is why you felling slow.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by chrissyshiru** [comment]
My video has been encoding for two days. status: encoding. how can i solve this?

**Comment by cgavaller2** [comment]
Yeah, same. I'm not sure what to do as there should be no hardware limitations (Two ten-core 20 thread Xeons)

**Comment by DanielnetoDotCom** [comment]
check your log file, you may find some clue there.

also make sure your FFMPEG is up to date

**Comment by d0773d** [comment]
This issue normally happens to me when I run out of storage space.
