### ISSUE TITLE
Embedded videos do NOT autoplay...

### ISSUE THREAD

**Issue by tdcpepsi** [DanielnetoDotCom/YouPHPTube#174]
When I embed a Youtube, Vimeo or Dailymotion video they don't autoplay and if you choose an embedded video as a video ad it don't work either.

**Comment by DanielnetoDotCom** [comment]
Yes, it is not made yet, I will take a look how to do it in the future

**Comment by tdcpepsi** [comment]
You can create a Javescript autoplay code for Youtube, Vimeo and Dailymotionvideos and it will autoplay all of the embedded videos. You can also do thisjust from using a cookie that open upon each page load.
You need to checkout "The Ultimate Video Player" and this is the video playerthat you should use within your script because it play mostly all video formats,Youtube, Vimeo and Dailymotion. It also play in-video banner ads and Pre Roll,Mid Roll and Post Roll Advertisments.

    On Saturday, October 21, 2017, 9:27:49 AM CDT, YouPHPTube <notifications@github.com> wrote:  
 
 
Yes, it is not made yet, I will take a look how to do it in the future

**Comment by DanielnetoDotCom** [comment]
Yes, thanks, I guess it is possible to do it, it will probably made some day, but we just can't do it now we are engaged in something else.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
