### ISSUE TITLE
Is there a way to use another video player that will play in-video banner ads???

### ISSUE THREAD

**Issue by tdcpepsi** [DanielnetoDotCom/YouPHPTube#175]
Is there a way to use another video player that will play in-video banner ads??? The site use the JSvideo player and it has the plugin for banner ads within the video player. Why is this NOT being used?

**Comment by DanielnetoDotCom** [comment]
I am planing to improve the ads system in the future , maybe with that plug in.
But now I need help for that

**Comment by tdcpepsi** [comment]
Ok, you're using the VideoJS video player and it has plugins for in-videobanner ads and it also have plugins for playing back Youtube, Vimeo and Dailymotionvideos, which mean that if you install all of the needed plugins for the VideoJS video player administrators would also be able to advertise pre roll ads from anyvideo, including embedded videos of all types.

    On Saturday, October 21, 2017, 9:27:08 AM CDT, YouPHPTube <notifications@github.com> wrote:  
 
 
I am planing to improve the ads system in the future , maybe with that plug in.
But now I need help for that

**Comment by tdcpepsi** [comment]
I've been trying to find people or a person that know how to install the VideoJS plugins but havn't had any luck and it's been over a year. I had a hard time with the Phpvibe script because it does not let you advertise pre roll ads unless you join JW Player or Flowplayer which their prices are too high. I've been studying the VideoJS player and the plugins for the player can be seen here: https://github.com/videojs/video.js/wiki/Plugins

The problem is....who can install the plugins and how do you add them to the player???

**Comment by DanielnetoDotCom** [comment]
You need clone this project and to modify the script, probably adding some libs on the file https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/view/include/head.php

and changing something here: https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/view/include/video.php

If you get this with success, please make a pull request

**Comment by tdcpepsi** [comment]
Ok, thanks for the much needed info.....

**Comment by tdcpepsi** [comment]
**I have the perfect idea for the post roll video ad....**

All you would have to do is "copy the pre roll code" within the script and
then change it to a post roll video ad, which you would have to add some code
that will detect that the previous video has ended.

Of course this sounds impossible to make happen but it's the easiet path!!!

After the pre roll code is copied all we would have to do next is "add the
settings" to the popup form or connect the popup form to the post roll settings
and this can be done using a drop down in the menu of the popup form, so that
when I choose a video to advertise in the site I'll have a choice to make it a
pre roll or a post roll ad.

1. Copy the pre roll script code
2. Change the settings of the copied pre roll code to a post roll ad
3. Connect the popup form to the post roll ad code by adding a dropdown menu
to the popup form. example: [Pre Roll Ad | Post Roll Ad]

**EXAMPLE:**
`<a href='https://postimages.org/' target='_blank'><img src='https://s20.postimg.org/g69ifhsct/Screen_Hunter_47_Oct._22_05.07.jpg' border='0' alt='Screen_Hunter_47_Oct._22_05.07'/></a>`

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
