### ISSUE TITLE
Can ONLY choose uploaded videos for pre roll advertising....

### ISSUE THREAD

**Issue by tdcpepsi** [DanielnetoDotCom/YouPHPTube#176]
It won't let me advertise Youtube, Dailymotion or Vimeo videos as a pre roll ad.

**Comment by DanielnetoDotCom** [comment]
Yes, at this moment we can not do this.
In the future we will figure out some way to do it

**Comment by tdcpepsi** [comment]
Use another video player that will play the Youtube videos...There are many video players that will play videos from Youtube, Dailymotion, Vimeoand more.

    On Saturday, October 21, 2017, 9:25:47 AM CDT, YouPHPTube <notifications@github.com> wrote:  
 
 
Yes, at this moment we can not do this.
In the future we will figure out some way to do it

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
