### ISSUE TITLE
Can I change the video player? Show me the steps...

### ISSUE THREAD

**Issue by tdcpepsi** [DanielnetoDotCom/YouPHPTube#177]
I want to change the video player in the site and use my video player which will autoplay Youtube, Vimeo and Dailymotion videos and it will play in-video banner ads, as well as pre roll, mid roll and post roll video advertisements.

Can I do this through "plugin" and what are the steps in changing the video player in the script???
If this can be done for me I can pay you for installing my video player. [The Ultimate Video Player]

**Comment by nightstryke** [comment]
It looks like a decent enough video player, but you'll have to figure out hot to set it up yourself or hire a coder to code it into a plugin for you. I think it might be out of the scope of services @DanielnetoDotCom offers.

**Comment by DanielnetoDotCom** [comment]
Hi, change player now is a bit harder, but video js can be enhanced .
Also is possible to create some plugin on youphptube to use differents players and pages, look Live plugin. it load a different page to play videos. also look Gallery and Facebook Plugin, all of them show you a different way to play videos.

If you want to develop it by your self try this https://github.com/DanielnetoDotCom/YouPHPTube/issues/175

If you want to hire the youphptube team to develop a new plugin, make some contact https://www.youphptube.com/#contact

**Comment by DanielnetoDotCom** [comment]
Good News, embed autoplay is working

**Comment by tdcpepsi** [comment]
Great, great, great...How do you make it work in my site???

**Comment by DanielnetoDotCom** [comment]
Just update your files with github files

**Comment by tdcpepsi** [comment]
How do I do that? When I go to the update page is show "Your system is up to date".

**Comment by DanielnetoDotCom** [comment]
You can make a git pull or download and overwrite your files

Em 23 de out de 2017 18:50, "tdcpepsi" <notifications@github.com> escreveu:

**Comment by tdcpepsi** [comment]
I'm very new to github....can this be done for me? Please.......

**Comment by DanielnetoDotCom** [comment]
Yes, I do not know how you installed it, if you made a git clone command, you can make a git pull command now.
Look here
https://tutorials.youphptube.com/video/how-to-update-your-youphptube-version

**Comment by tdcpepsi** [comment]
Still don't understand.... I installed it by watching the installation video but I know nothing at all about Ubunti, git clone or git pull command. I'm totally lost, sorry....

**Comment by DanielnetoDotCom** [comment]
then try to download and upload it to your site, overwrite your files

**Comment by tdcpepsi** [comment]
Ok, show me the link to the updated files and where the folder on the server is located.
You said overwrite the files, which are on the server [file manager] correct?

**Comment by tdcpepsi** [comment]
Ok, I'm now understanding github better and I see the new files. I just don't want to mess up anything and this is my worry. I want to learn the pull command that is in the instruction video. I went to virtualbox.org and downloaded it..."windows host 5.2.0"....

**Comment by tdcpepsi** [comment]
I fixed it....great job Mr. Daniel....I really like your video script, it is the best!!!!

**Comment by tdcpepsi** [comment]
It would be great if the embedded videos would "skip" to the next video. The video stop at the end and show Youtube related videos.

**Comment by DanielnetoDotCom** [comment]
Yes, I will look into that later

**Comment by tdcpepsi** [comment]
**I know that I'm on your nervers, sorry for this but I have idea's for the video script...**

**1.** This is how the profile pages should look: https://s20.postimg.org/51ybzfyrx/Screen_Hunter_51_Oct._23_19.36.jpg

**NOTICE:** the small description, the video likes and video views...
It's very simple but also very powerful. If you make the profiles look like the picture it will boost the profile activity between members and it will cause members to compete, which will keep them in the site.

**2.** The "post roll video ad" is important because it's a leverage additive that most video scripts do not have or offer. If this is added it will place your video script at the level of Youtube because they do not offer post roll video ads. Post Roll video ads will lift the script above all other video sites.

Placing the post roll into the site can be done easily: https://s20.postimg.org/btor1tih9/Screen_Hunter_47_Oct._22_05.07.jpg

**All you have to do is...** 
**1.** Copy the pre roll code and turn it into a post roll code.
**2.** Add a "drop down menu" to the submission form [Pre Roll or Post Roll].
**3.** Arrange the form to submission to post to the post roll when chosing to advertise a post roll.
Simple, clean and easy......

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by DanielnetoDotCom** [comment]
Not sure, but you may google for that, searching how to change it for videojs player.

**Comment by nightstryke** [comment]
> How to change the loading image in the center of the video player?
> 
> @DanielnetoDotCom

I don't know if this works anymore, but in the past if you want to change the loading animation. Look in **/view/img** folder and replace **loading-gif.png** (this is a still image) AND replace **loading.gif** (this is the animated image) Replacing the **loading.gif** with an animated image (another .gif file) of your choice should work provided that you delete the old **loading.gif** and rename the new one to the same file name.

**Comment by akhilleusuggo** [comment]
@nightstryke he's about the video.js not the gifs
