### ISSUE TITLE
Can a post roll video ad zone be added to the script???

### ISSUE THREAD

**Issue by tdcpepsi** [DanielnetoDotCom/YouPHPTube#179]
I need a post roll ad within the site. Can I pay you to add the post roll into the script???
You can copy the pre roll and then rearrange the settings to where it is a post roll. By this, we will have a pre roll ad and a post roll ad. Can this be done, we can pay you instantly!!!

**Comment by DanielnetoDotCom** [comment]
Better we discuss it here https://github.com/DanielnetoDotCom/YouPHPTube/issues/175

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
