### ISSUE TITLE
Select categorie when uploading a video

### ISSUE THREAD

**Issue by Knah-Tsaeb** [DanielnetoDotCom/YouPHPTube#18]
I think is better if we assign a categories and visibility when selecting a video before uploading than after a video is upload.

**Comment by DanielnetoDotCom** [comment]
This is a good idea, i will put this on the road

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
