### ISSUE TITLE
Is there a person who can install VideoJS plugins???

### ISSUE THREAD

**Issue by tdcpepsi** [DanielnetoDotCom/YouPHPTube#180]
I've located the needed plugins.....
The autoplay for embedded videos and the playback plugins for Youtube, Dailymotion, Soundcloud and Vimeo: https://github.com/videojs/video.js/wiki/Plugins

Is there a person who can install the plugins?

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
