### ISSUE TITLE
How do I delete the "Queue Log" without deleting the video???

### ISSUE THREAD

**Issue by tdcpepsi** [DanielnetoDotCom/YouPHPTube#181]
Is it possible to delete the queue log without deleting the video???

**Comment by DanielnetoDotCom** [comment]
On the encoder when you delete a queue log it also delete the original downloaded video (does not delete the encoded video on streamer site).
delete original video is needed to make some free space when is needed

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
