### ISSUE TITLE
Quem e o dono desse site ?

### ISSUE THREAD

**Issue by PlayxPE** [DanielnetoDotCom/YouPHPTube#182]
http://noticiasgamesdahora.com/

**Comment by DanielnetoDotCom** [comment]
Desconheço

**Comment by DanielnetoDotCom** [comment]
I found @winklov is the owner

**Comment by winklov** [comment]
@PlayxPE What is wrong

**Comment by PlayxPE** [comment]
Nada amigo , Gostaria de fazer um acordo com você

**Comment by winklov** [comment]
Que tipo de negócio você pode me enviar por e-mail no winklovsocial@gmail.com

**Comment by winklov** [comment]
im waiting on your email

**Comment by PlayxPE** [comment]
Ok
