### ISSUE TITLE
users groups and permmsions

### ISSUE THREAD

**Issue by soolhami** [DanielnetoDotCom/YouPHPTube#183]
Hey all

DDC really love what you got going here and have followed you since the beginning, have never had any issues with your scripts but have had the odd conflict with permissions and users, groups and so on starting with 4.0 and the streamer and encoder and so on and figured that out myself but with the live stream now Im having Issues with the /HLS/Live being located in root i know i could add it to nginx or apache directives or relocate it but im just not as smart as you... or to say the least as familiar with the code and its operation. Any chance you or anyone could help ?

**Comment by DanielnetoDotCom** [comment]
Hello

Yes it is possible that the /HLS folder stays elsewhere, just create it and change the parameter:          `hls_path /HLS/live;` in your nginx.conf file

If you need more help feel free to hire any of our services: https://www.youphptube.com/services

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
