### ISSUE TITLE
Important Information YouPHPTube Security Releases

### ISSUE THREAD

**Issue by DanielnetoDotCom** [DanielnetoDotCom/YouPHPTube#185]
As our software grows more and more evil people try to attack us.
So in the last days we have been attacked, however we have detect, have corrected the problem and also we have created a tutorial to teach you how to correct the problem.

Check this release and how to fix tutorial:
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/YouPHPTube-Security-Releases

Sorry for the inconvenience but we will always be alert for any kind of correction.

**Comment by winklov** [comment]
i did the security update but my encoder is encoding the videos but it does not send it to streaming site
what should i do now

**Comment by DanielnetoDotCom** [comment]
this issue is not related to this security release, please check your youphptube.log under videos for more information

**Comment by winklov** [comment]
![untitled](https://user-images.githubusercontent.com/18721141/32090224-ab430aa6-baee-11e7-8595-803d47b414da.png)

Please advice me what to do

**Comment by DanielnetoDotCom** [comment]
cd /var/www/html/YouPHPTube/videos/ && ls -lah *.php

Only configuration.php is allowed here, delete any other php file

**Comment by winklov** [comment]
thats the only file in the folder

**Comment by DanielnetoDotCom** [comment]
So you all set and clean

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
