### ISSUE TITLE
Pedido de promoção para plugin de qualidade 

### ISSUE THREAD

**Issue by PlayxPE** [DanielnetoDotCom/YouPHPTube#187]
Daniel , você poderia abaixar um pouco o preço do plugin em breve , sou adolescente e e Muito difícil de eu conseguir 29,6100358 reais caso não possa  eu entendo

**Comment by winklov** [comment]
Oi, você estava me procurando por qualquer coisa que eu possa ajudá-lo com

**Comment by DanielnetoDotCom** [comment]
@PlayxPE  de qual país vc é? Qual o seu email?

**Comment by winklov** [comment]
winklovsocial@gmail.com

**Comment by PlayxPE** [comment]
@DanielnetoDotCom 

ALEXS123655@gmail.com
Brasil
