### ISSUE TITLE
When taking embed code and placing it on another website | The video does not play!

### ISSUE THREAD

**Issue by tdcpepsi** [DanielnetoDotCom/YouPHPTube#189]
When taking embed code and placing it on another website | The video does not play!

**Comment by DanielnetoDotCom** [comment]
you mean auto play or does not play if you click on the play button?
do you have an site example?

**Comment by tdcpepsi** [comment]
See if the embedded code will play for you....
<iframe width="350" height="40" style="max-width: 100%;max-height: 100%;" src="http://www.vtubemobi.com/videoEmbeded/chris-brown-run-it-" frameborder="0" allowfullscreen="allowfullscreen" class="YouPHPTubeIframe"></iframe>

**Comment by DanielnetoDotCom** [comment]
Sorry @tdcpepsi  I don't understand what was the issue

**Comment by tdcpepsi** [comment]
The embeds don't play..........

**Comment by DanielnetoDotCom** [comment]
Sorry about that, I just send a fix for this on github

**Comment by tdcpepsi** [comment]
Can you give me the link to the files or fix...

**Comment by DanielnetoDotCom** [comment]
This will help you 
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

**Comment by tdcpepsi** [comment]
I'm totally lost...can I add the files instead of doing the whole update....where are the files?

**Comment by DanielnetoDotCom** [comment]
The best option is to do a whole update (You will not loose your videos and configurations)
Follow the link instructions, take a look on this video  https://tutorials.youphptube.com/video/force-git-to-overwrite-files

**Comment by tdcpepsi** [comment]
I don't know how to do the update that way....
Will this delete my ad zones in the site and ad blocks that I created in the script???

**Comment by DanielnetoDotCom** [comment]
no will not delete your ads.
but you can just overwrite the files on your server.
but I recommend you a git pull to keep you always up to date

**Comment by tdcpepsi** [comment]
Can you do the get pull for me???

**Comment by DanielnetoDotCom** [comment]
send me your an email with your server ssh credentials developer@youphptube.com

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
