### ISSUE TITLE
Encoder is NOT transferring the videos to the streaming site!!!

### ISSUE THREAD

**Issue by tdcpepsi** [DanielnetoDotCom/YouPHPTube#190]
**Been waiting for 2 days for the videos to transfer to the streaming site!!!**

Also, when I uploaded videos yesterday the videos were somehow switched during the transfer, as if someone is operating the encoding or able to hack and switch the videos during the transfer, which the problem could be due to hackers. The videos that I uploaded were not the same videos that were transfered to the streaming site. The videos were switched and some of the video pics were changed!!!

**Comment by DanielnetoDotCom** [comment]
Hi @tdcpepsi I have answered this question here: https://github.com/DanielnetoDotCom/YouPHPTube/issues/173 and here https://github.com/DanielnetoDotCom/YouPHPTube/issues/186

**Comment by winklov** [comment]
hi @DanielnetoDotCom the encoder was fix but when it transfer to the streaming site its not the same video

**Comment by DanielnetoDotCom** [comment]
Any news?

**Comment by winklov** [comment]
Hi @tdcpepsi and @DanielnetoDotCom go to the encoder folder in that folder look for the videos folder delete everything in that folder expect configuration.php and the youphpthe.log files DO NOT DELETE THOSE TWO FILES. THEN YOU WILL BE SORTED
