### ISSUE TITLE
EasyTube.Club

### ISSUE THREAD

**Issue by PlayxPE** [DanielnetoDotCom/YouPHPTube#191]
Daniel , voce poderia liberar o ftp no easytube , eu tenho a versão do site mais nova modificada para minha língua e com outras opeções , mais nao tem como adicionar lá

**Comment by DanielnetoDotCom** [comment]
@PlayxPE você tem duas opções, eu posso atualizar seu site pra vc ou voce pode tentar isto aqui. 
https://tutorials.youphptube.com/video/youphptube-on-000webhost

é quase a mesma coisa so que vc vai ter que instalar o site por você mesmo mas tambem vc vai ter o FTP

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
