### ISSUE TITLE
How do I get the API INFO for my website???

### ISSUE THREAD

**Issue by tdcpepsi** [DanielnetoDotCom/YouPHPTube#192]
**PLEASE HELP:** I have to make category slides for my site, so I have to have the API info for pulling the data into the slider. I need the correct API info for the sliders. Can you fill in the needed api info for my site within the code belw.

**I want to pull the video categories data into the Flickty slider...** 

**I need the correct API URL for the videos in my website...vtubemobi.com**
type: "GET",
            url: "http://api.vtubemobi.com/?type=all",
            dataType: "jsonp", 

Below is the Flickty slider code that I am using but the API to my sites video categories are needed.
**EXAMPLE CATEGORY:** "travel-and-event"....

<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Flickity - groupCells</title>
  <meta name="viewport" content="width=device-width">
  
  <link rel='stylesheet prefetch' href='https://npmcdn.com/flickity@2/dist/flickity.css'>

      <link rel="stylesheet" href="css/style.css">
 
</head>
<body>

<div class="carousel" data-flickity='{ "pageDots": false, "wrapAround": true, "groupCells": true }'>
<div class="section-header">
  Trending Now

<a href="http://www.vtubemobi.com/?type=all">browse all videos</a>

<script src='https://npmcdn.com/flickity@2/dist/flickity.pkgd.js'></script>

    <script  src="js/index.js"></script>

<style>
var $carousel = $('.carousel').flickity()
  .flickity('next')
  .flickity( 'select', 6 );
</style>
<style>
/* external css: flickity.css */

* { box-sizing: border-box; }

body { font-family: sans-serif; }

.carousel {
  background: #EEE;
}

.carousel-cell {
  width: 400;
  height: 161px;
  margin-right: 0px;
  background: #8C8;
  border-radius: 5px;
  counter-increment: carousel-cell;
  
}

/* cell number */
.carousel-cell:before {
  display: block;
  text-align: center;
  content: counter(carousel-cell);
  line-height: 0px;
  font-size: 0px;
  color: white;
}
</style>

<script>
$(document).ready(function() {
 
    vtubemobi();
 
    function vtubemobi () {
        $.ajax({
            type: "GET",
            url: "http://api.vtubemobi.com/?type=all",
            dataType: "jsonp",
            success: function(result){
                console.log(result.data);
                $.each(result.data, function (i) {
                    $('[data-vtubemobi="' + i + '"] .vtubemobi-thumb').attr('src', this.images.low_resolution.url);
                    $('[data-vtubemobi="' + i + '"] a').attr('href', this.link);
                    $('[data-vtubemobi="' + i + '"] .vtubemobi-views').text(this.views.count);
                    $('[data-vtubemobi="' + i + '"] .vtubemobi-likes').text(this.likes.count);
                });
            }
        });
    }   
});
</script>
 
 <center>
<table cellpadding="0" ccellspacing="0" border="0" width="1086" style="margin:15px 0px 0px 0px;">
<tr>
<td align="left" data-vtubemobi="0">
<a href="" target="_blank"><img src="" class="vtubemobi-thumb" width="204" height="204"></a>
<p>
<img src="/img/icon-views.png"><span class="vtubemobi-views"></span>
<img src="/img/icon-likes.png"><span class="vtubemobi-likes"></span>
</p>
</td>
<td align="left" data-vtubemobi="1">
<a href="" target="_blank"><img src="" class="vtubemobi-thumb" width="204" height="204"></a>
<p>
<img src="/img/icon-views.png"><span class="vtubemobi-views"></span>
<img src="/img/icon-likes.png"><span class="vtubemobi-likes"></span>
</p>
</td>
<td align="left" data-vtubemobi="2">
<a href="" target="_blank"><img src="" class="vtubemobi-thumb" width="204" height="204"></a>
<p>
<img src="/img/icon-views.png"><span class="vtubemobi-views"></span>
<img src="/img/icon-likes.png"><span class="vtubemobi-likes"></span>
</p>
</td>
<td align="left" data-vtubemobi="3">
<a href="" target="_blank"><img src="" class="vtubemobi-thumb" width="204" height="204"></a>
<p>
<img src="/img/icon-views.png"><span class="vtubemobi-views"></span>
<img src="/img/icon-likes.png"><span class="vtubemobi-likes"></span>
</p>
</td>
<td align="left" data-vtubemobi="4">
<a href="" target="_blank"><img src="" class="vtubemobi-thumb" width="204" height="204"></a>
<p>
<img src="/img/icon-views.png"><span class="vtubemobi-views"></span>
<img src="/img/icon-likes.png"><span class="vtubemobi-likes"></span>
</p>
</td>
<td align="left" data-vtubemobi="5">
<a href="" target="_blank"><img src="" class="vtubemobi-thumb" width="204" height="204"></a>
<p>
<img src="/img/icon-views.png"><span class="vtubemobi-views"></span>
<img src="/img/icon-likes.png"><span class="vtubemobi-likes"></span>
</p>
</td>
</tr>
</table>

</body>
</html>

**Comment by DanielnetoDotCom** [comment]
Are you looking for this (videosAndroid.json)?

https://demo.youphptube.com/videosAndroid.json

**Comment by tdcpepsi** [comment]
I don't understand....
I just need the API info for my site........

**Comment by DanielnetoDotCom** [comment]
on this link you have all information you need to build a carrossel image

**Comment by tdcpepsi** [comment]
Can you do this for me? I will pay you....
All I need is ONE slider set up [Flickity] under the category "travel-and-event" or create ONE slider for lastest videos in the site so that I can copy it....and create sliders for the categories that I want seen on the home page.

**Comment by DanielnetoDotCom** [comment]
send me an email and we will talk about id developer@youphptube.com

**Comment by tdcpepsi** [comment]
tdcpepsi@yahoo.com

**Comment by DanielnetoDotCom** [comment]
I sent you an email

**Comment by tdcpepsi** [comment]
Just messaged you back........

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
