### ISSUE TITLE
How to embed video like youtube in our project from this website.

### ISSUE THREAD

**Issue by rohitnehra** [DanielnetoDotCom/YouPHPTube#193]
https://instant.io/#ce421edde058ec77626a60d5cdfc1da18ed197ed

this uses torrent & show it to us.
This link is created by me. 
How to use it?

I tried blob url in simplest web also.

Please tell me the solution if possible.

**Comment by DanielnetoDotCom** [comment]
I dont understand your needs

**Comment by rohitnehra** [comment]
If we want to embed video from youtube we use
"https://www.youtube.com/watch?v=riZKD6ErJYs" this type of link

for dailymotion we use 
"http://www.dailymotion.com/video/x65r3i1"

but this is not working on that link I mentioned earlier

**Comment by DanielnetoDotCom** [comment]
Youtube should work.
But Dailymotion does not yet. I will send a fix for dailymotion soon

**Comment by rohitnehra** [comment]
Please do it for instant.io also. It will be very helpful for me.
Thanks & regards,
Rohit Nehra

**Comment by DanielnetoDotCom** [comment]
Done 
Update your code
https://demo.youphptube.com/video/making-ban-ja-rani-song-tumhari-sulu-guru-randhawa-vidya-balan

**Comment by rohitnehra** [comment]
which file I have to update?

**Comment by DanielnetoDotCom** [comment]
This
https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/objects/functions.php

**Comment by rohitnehra** [comment]
Please guide me to make same kind of function for https://instant.io/#ce421edde058ec77626a60d5cdfc1da18ed197ed  this video link.

**Comment by DanielnetoDotCom** [comment]
what?

**Comment by rohitnehra** [comment]
tell me when you are online.

This website fetches data from torrent. This torrent is only available to me.

**Comment by DanielnetoDotCom** [comment]
hi, I am not sure what you want do do, but try to hire 1 hour support we can try to figure out how to fix it

https://www.youphptube.com/services#service-prices

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by heme007** [comment]
Gostaria de reabrir esta dúvida de muitos. O que rohitnehra quis dizer, é que os videos, quando compartilhado no facebook, ou em qualquer stream, o video não se apresenta aberto, ele fica com o link pra clicar. E quando postamos videos do youtube ou vimeo ele se apresenta com o link aberto, a pessoa consegue assistir da minha página

**Comment by DanielnetoDotCom** [comment]
Isso e uma funcionalidade do facebook, não ha nada que possamos fazer.

**Comment by heme007** [comment]
eu criei uma página do script humhub, nao sei se conhece. Ele exige Ativar provedores OEmbed
e pede o seguinte: Use %url% como placeholder para URL. Formato precisa ser JSON. (por exemplo http://www.youtube.com/oembed?url=%url%&format=json)

eu consigo isso pelo meu streaming do youphptube?
