### ISSUE TITLE
Importa plugin Erro No results found!

### ISSUE THREAD

**Issue by PlayxPE** [DanielnetoDotCom/YouPHPTube#196]
Quando coloco o plugin na pasta manualmente e vou ver para ativar nehum plugin fica disponível

**Comment by DanielnetoDotCom** [comment]
Da uma olhada como vc copiou a pasta ela tem que ter um arquivo com o mesmo
nome da pasta logo quando vc entra.
Eu imagino que vc criou uma pasta a mais

Em 29 de out de 2017 16:10, "PLAYX" <notifications@github.com> escreveu:

**Comment by PlayxPE** [comment]
Acho que não entendi direito, e para mim verificar se o nome da pasta e o mesmo dos arquivos ?
So tirei a / dos arquivos por que não tava aceitando

**Comment by DanielnetoDotCom** [comment]
Seus arquivos tem que está parecido com a imagem,
Olhe se você não criou uma pasta a mais
![image](https://user-images.githubusercontent.com/18009293/32149159-26a44628-bcdf-11e7-98df-23f0b686402b.png)

**Comment by PlayxPE** [comment]
Sim

**Comment by PlayxPE** [comment]
Conseguir , obrigado pela ajuda

**Comment by PlayxPE** [comment]
Ops não aparece a opeção de qualidade no player

**Comment by DanielnetoDotCom** [comment]
@PlayxPE me desculpa, houve uma atualização no plugin.
Baixa ele lá de novo no easytube e depois faz o upload para seu site e limpa o cache do browser

**Comment by PlayxPE** [comment]
Ok

**Comment by DanielnetoDotCom** [comment]
Pronto coloquei o plugin agora, não sabia que você responderia tão rápido

**Comment by PlayxPE** [comment]
Ok

**Comment by PlayxPE** [comment]
Acredito que esse bug so esteja na 000webhost a uma semana atrás nao dava nem para fazer login caso continuar na nova hospedagem que vou pegar , reabrirei o tópico

**Comment by DanielnetoDotCom** [comment]
Manda para meu email os dados da sua conta que eu olho pra vc

Em 30 de out de 2017 18:51, "PLAYX" <notifications@github.com> escreveu:

Closed #196 <https://github.com/DanielnetoDotCom/YouPHPTube/issues/196>.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/DanielnetoDotCom/YouPHPTube/issues/196#event-1317659965>,
or mute the thread

**Comment by PlayxPE** [comment]
Qual seu email mesmo ?

**Comment by DanielnetoDotCom** [comment]
Você alterou o arquivo footer e removeu uma parte importante do código, eu vou coloca-lo novamente para você

**Comment by DanielnetoDotCom** [comment]
Agora está resolvido

**Comment by PlayxPE** [comment]
Obrigado , oque estava atrapalhando ?eu preciso fazer Blackup de algum
arquivo
Em 30 de out de 2017 9:33 PM, "YouPHPTube" <notifications@github.com>
escreveu:

**Comment by DanielnetoDotCom** [comment]
Você tinha alterado este arquivo e retirado parte importante do código https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/view/include/footer.php

**Comment by PlayxPE** [comment]
Obrigado por me ajudar e desculpe por tira um pouco do seu tempo
Em 30 de out de 2017 9:35 PM, "YouPHPTube" <notifications@github.com>
escreveu:

**Comment by DanielnetoDotCom** [comment]
Sem problemas, se divirta e que Deus lhe abençoe :)

**Comment by PlayxPE** [comment]
Amém , tenha uma boa noite
Em 30 de out de 2017 9:37 PM, "YouPHPTube" <notifications@github.com>
escreveu:
