### ISSUE TITLE
Erro na instalação 

### ISSUE THREAD

**Issue by PlayxPE** [DanielnetoDotCom/YouPHPTube#197]
Aparece esse erro quando tento instalar com wampserver no Windows 

Error deleting user: Cannot delete or update a parent row: a foreign key constraint fails (`newtix`.`configurations`, CONSTRAINT `fk_configurations_users1` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)

**Comment by PlayxPE** [comment]
![img-20171029-wa0013](https://user-images.githubusercontent.com/22136548/32176317-7ccebde6-bd6e-11e7-9713-1b58118fd622.jpg)

**Comment by DanielnetoDotCom** [comment]
Verifique se este banco de dados já não existe.
se existir apague

**Comment by PlayxPE** [comment]
Ok

**Comment by DanielnetoDotCom** [comment]
resolveu?

**Comment by PlayxPE** [comment]
Hoje a noite vou testar e te aviso :)

**Comment by PlayxPE** [comment]
Eu criei outra tabela e não resolveu

**Comment by PlayxPE** [comment]
*Database

**Comment by DanielnetoDotCom** [comment]
mas a tabela não é para você criar manualmente.
O script cria sozinho

**Comment by PlayxPE** [comment]
Sim , eu sei disso

**Comment by PlayxPE** [comment]
Eu estou utilizando wamp server

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
