### ISSUE TITLE
 Open OBS configuration -> Stream

### ISSUE THREAD

**Issue by k7n2g** [DanielnetoDotCom/YouPHPTube#199]
Hi guys never used this OBS  how do i open / where do i find the OBS configuration file in YouphpTube
looked every where for this it dosent make it clear on the video instruction  thanks

**Comment by DanielnetoDotCom** [comment]
You do not need to open OBS configuration file. just set the live stream parameters on the configuration
Did you see this tutorial? https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-stream-videos-to-YouPHPTube

**Comment by nightstryke** [comment]
@k7n2g You also might want to watch @DanielnetoDotCom's video on his tutorial site. https://tutorials.youphptube.com/video/youphptube-video-stream-with-obs-and-vmix

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
