### ISSUE TITLE
Bug Search

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#201]
looking for the most seen does not work can  you fix it

![bug2](https://user-images.githubusercontent.com/30271757/32321769-86630f96-bfc2-11e7-8779-d5ae49179287.PNG)

**Comment by mikweb2017** [comment]
sometimes it does not work

**Comment by DanielnetoDotCom** [comment]
When did you update your site?
I found some issues but they were fixed in about 6 hours ago.
can you reproduce this error on demo site?

**Comment by mikweb2017** [comment]
i did update now i do not spezz you sometimes i work fine sometimes i do not try to see if anything in the errorlogs of my server and the next time I make a video so you can see what i mean.

the demo page works fine

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
