### ISSUE TITLE
encoder enhancement in error control

### ISSUE THREAD

**Issue by laweschan** [DanielnetoDotCom/YouPHPTube#203]
Hi Daniel,

   for the video download link input, yup, I try to place an invalid link "https://www.google.com", nothing should convert as expect, however, the processing holding without disappear

   so how about if other video link input but encoder won't / unable to convert ? the processing screen just a confuse and give a signal that the system is running, but actually it should facing some error in background.

   for any process face in error it should go to detail error log, no matter in GUI / a text file, better than wait infinity processing, unless user to reload the page

![processing](https://user-images.githubusercontent.com/17445193/32360114-e2df5df8-c08d-11e7-8ee4-8717c74edbc2.png)

**Comment by DanielnetoDotCom** [comment]
Hi thanks for notice it.
It is regarding the encoder side right?
Let me know where exactly is it. I will fix this ASAP

**Comment by laweschan** [comment]
yup I guess this should be at encoder side, thanks

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
