### ISSUE TITLE
Offline Image and Installer Issue

### ISSUE THREAD

**Issue by DemonRem** [DanielnetoDotCom/YouPHPTube#205]
there is a message when I installing it in cpanel host say failed uknown error

and about streaming offline image it's can be good idea to do it or it's exist

**Comment by DanielnetoDotCom** [comment]
About the cpanel we need more info about it.
About the image, it will be done in the future

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
