### ISSUE TITLE
streamer is not allowed

### ISSUE THREAD

**Issue by cheesewizz** [DanielnetoDotCom/YouPHPTube#207]
Hi

Im so happy to used this opensource its really great to have it.

please im doing or testing the encoder i believed it was successfully installed but when i tried to access it
streamer is not allowed.

![streamerisnotallowed](https://user-images.githubusercontent.com/14123082/32636462-df3084fe-c5ef-11e7-9f25-bca6d07a7c8d.png)

can you guide me

thanks

**Comment by cheesewizz** [comment]
I tested it first using virtualbox under ubuntu linux system

**Comment by DanielnetoDotCom** [comment]
Hi, check your configuration table 

if this field is blank anyone can use, if not only this site can use

![image](https://user-images.githubusercontent.com/18009293/32636544-0fd8db76-c594-11e7-9957-cfc64c6cbeb0.png)

**Comment by cheesewizz** [comment]
Thanks for your reply

is that a database tables? where can i check the configuration table?

**Comment by DanielnetoDotCom** [comment]
it is your encoder tables, use mysql commands or any other tool you prefer

**Comment by cheesewizz** [comment]
![allowedstreamer](https://user-images.githubusercontent.com/14123082/32638460-4c0c119c-c5fa-11e7-82f4-b0c73cec0c51.png)

**Comment by DanielnetoDotCom** [comment]
I can see you are using workbench.
try to select row

![image](https://user-images.githubusercontent.com/18009293/32638570-b930006e-c59e-11e7-8cf3-25fb2cc01605.png)

**Comment by cheesewizz** [comment]
![streamer](https://user-images.githubusercontent.com/14123082/32638594-0522bbae-c5fb-11e7-9386-06545867d015.png)

**Comment by cheesewizz** [comment]
![limit](https://user-images.githubusercontent.com/14123082/32638619-1fefa974-c5fb-11e7-8f4f-bef12234fd91.png)

**Comment by cheesewizz** [comment]
![streamer2](https://user-images.githubusercontent.com/14123082/32638853-23a14ff4-c5fc-11e7-9233-03faf4930b1f.png)

**Comment by cheesewizz** [comment]
what do i update?

**Comment by DanielnetoDotCom** [comment]
I am not sure what is wrong, but do this, put a slash at the end of the allowedStreamersURL it will be http://192.168.50.219/YouPHPTube/

If it does not work, I have to take a deeper look on your installation.
But to make it work now, just remove the value from allowedStreamersURL  and it will work for sure, but be careful it will be public and anyone will be able to use your encoder

**Comment by DanielnetoDotCom** [comment]
I just realized, you install a encoder, but are you sure you are using your encoder and not the public one?
you can not use the public encoder with a local IP address.

Make sure your streamer site is point to your encoder

![image](https://user-images.githubusercontent.com/18009293/32639167-4b247534-c5a1-11e7-856f-b58689c2717c.png)

**Comment by cheesewizz** [comment]
it works just putting / slash at the end of the path

![slash](https://user-images.githubusercontent.com/14123082/32640034-9ad92510-c601-11e7-8526-412af82ac9e7.png)

**Comment by cheesewizz** [comment]
thank you very very much :)

**Comment by DanielnetoDotCom** [comment]
you welcome.
But I can see you are not admin, change your isAdmin column to 1 on your streamers table

**Comment by cheesewizz** [comment]
![isadmin](https://user-images.githubusercontent.com/14123082/32640327-21806992-c603-11e7-8c52-016d090312ed.png)

**Comment by DanielnetoDotCom** [comment]
change isAdmin to 1

**Comment by cheesewizz** [comment]
![adminisadmin](https://user-images.githubusercontent.com/14123082/32641494-3652ebb4-c609-11e7-9ef3-dac0e336172c.png)

**Comment by fst24sx** [comment]
I do not have any tools. what would be the mysql commands used to change the streamer url?

**Comment by DanielnetoDotCom** [comment]
this can be done on command line, phpmyadmin or mysql workbench

**Comment by fst24sx** [comment]
> this can be done on command line, phpmyadmin or mysql workbench

i understand this. But do not know which commands I need. I dont use any SQL tools

command line only
