### ISSUE TITLE
Failed to conenct Live Streaming

### ISSUE THREAD

**Issue by cheesewizz** [DanielnetoDotCom/YouPHPTube#208]
I just followed the tutorials using OBS
but no lucks for me because failed to connect

![pluginsenabled](https://user-images.githubusercontent.com/14123082/32641797-df185652-c60a-11e7-8deb-3ea9ce25c1a9.png)

![obs settings streamer1](https://user-images.githubusercontent.com/14123082/32641766-bb368aa6-c60a-11e7-91c1-4456ec1e9bdb.png)

![obs failed to connect](https://user-images.githubusercontent.com/14123082/32641769-bfb3154a-c60a-11e7-9980-c6e463161e17.png)

**Comment by DanielnetoDotCom** [comment]
Can you post your nginx.conf file here?

**Comment by DanielnetoDotCom** [comment]
check on your nginx.conf this parameter

 on_publish http://**[YouPHPTube-Path]**/plugin/Live/on_publish.php;

**Comment by cheesewizz** [comment]
Thank you and good morning

sorry but cant find nginx.conf in my ubuntu if the default location is /etc/nginx/nginx.conf no such file or directory

**Comment by cheesewizz** [comment]
i tried this command to find nginx.conf

youphptube@youphptube-VirtualBox:~$ whereis nginx.conf
nginx: /usr/local/nginx
youphptube@youphptube-VirtualBox:~$ 

youphptube@youphptube-VirtualBox:~$ ls /usr/local/nginx/nginx.conf
ls: cannot access '/usr/local/nginx/nginx.conf': No such file or directory
youphptube@youphptube-VirtualBox:~$ 

youphptube@youphptube-VirtualBox:~$ whereis nginx.conf
nginx: /usr/local/nginx

**Comment by cheesewizz** [comment]
chat and live pages is visible
![adminpagechat](https://user-images.githubusercontent.com/14123082/32684047-f68293e2-c6ba-11e7-9b35-75686ef10b38.png)

plugins enabled
![plugins enabled](https://user-images.githubusercontent.com/14123082/32684063-10e565de-c6bb-11e7-8bad-548d371030a3.png)

**Comment by DanielnetoDotCom** [comment]
try this ...
```
sudo updatedb
sudo locate nginx.conf
```

**Comment by cheesewizz** [comment]
youphptube@youphptube-VirtualBox:~$ sudo updatedb
youphptube@youphptube-VirtualBox:~$ sudo locate nginx.conf
/home/youphptube/build/nginx-1.12.0/conf/nginx.conf
/home/youphptube/build/nginx-rtmp-module/test/nginx.conf
/usr/local/nginx/conf/nginx.conf
/usr/local/nginx/conf/nginx.conf.default
/usr/local/nginx/conf/nginx.conf.old
/var/www/html/YouPHPTube/plugin/Live/install/nginx.conf
youphptube@youphptube-VirtualBox:~

**Comment by DanielnetoDotCom** [comment]
try this one 
`/usr/local/nginx/conf/nginx.conf`

**Comment by cheesewizz** [comment]
Good Morning

Thanks for your reply, I cant access anymore i dont know what happened so i decided to reinstall, Ill update you .

thanks

**Comment by cheesewizz** [comment]
Hello 
Im Back, I Already reinstall new UBUNTU and YouPHPTube and Encoder
here is now the path of nginx.conf

youphptube@youphptube-VirtualBox:/var/www/html/YouPHPTube-Encoder$ sudo locate nginx.conf
youphptube@youphptube-VirtualBox:/var/www/html/YouPHPTube-Encoder$ sudo updatedb 
youphptube@youphptube-VirtualBox:/var/www/html/YouPHPTube-Encoder$ 
youphptube@youphptube-VirtualBox:/var/www/html/YouPHPTube-Encoder$ sudo locate nginx.conf
/var/www/html/YouPHPTube/plugin/Live/install/nginx.conf
youphptube@youphptube-VirtualBox:/var/www/html/YouPHPTube-Encoder$

**Comment by cheesewizz** [comment]
is that the correct path?

**Comment by cheesewizz** [comment]
I have 4.3 version but the tutorial is 4.1 Do I need to follow this instruction 
https://tutorials.youphptube.com/video/10-min-youphptube-stream-server-installation1?

**Comment by cheesewizz** [comment]
ok I followed this and its working but i still another problem, the OBS is starting Streaming and Recording 
but no notification display on youphptube 
![no notification2](https://user-images.githubusercontent.com/14123082/32711702-45bffcf8-c87b-11e7-8b4b-b86318a4e46a.png)

**Comment by cheesewizz** [comment]
I noticed it appears OFFLINE when i paly the live streaming 
![offline](https://user-images.githubusercontent.com/14123082/32711818-e8e4f12c-c87b-11e7-850d-7fbdd60520fc.png)

**Comment by DanielnetoDotCom** [comment]
Check this https://github.com/DanielnetoDotCom/YouPHPTube/issues/210

**Comment by cheesewizz** [comment]
Hello DDC

![streamingitworks](https://user-images.githubusercontent.com/14123082/32756601-e94c110a-c915-11e7-898f-6c7fd49b19cc.png)

Finally its working now 

what i did is to followed the guide you commented #210 and edit the parameters of LIVE under plugins
i removed the existing code then i replaced this 
{"button_title":"LIVE","server":"rtmp://192.168.50.219/live","playerServer":"http://192.168.50.219:8080/live","stats":"http://192.168.50.219:8080/stats"} then save and click start streaming from OBS then few second i see it 1 notification appeared. Hoorayyyy

**Comment by cheesewizz** [comment]
how do i start boot the nginx when ubuntu reboot?
after i reboot nginx not working, so i run this code to make nginx work again sudo /usr/local/nginx/sbin/nginx

**Comment by DanielnetoDotCom** [comment]
Try to edit this file

`sudo nano /etc/rc.local `

and add this line before the exit command

`/usr/local/nginx/sbin/nginx && nohup php /var/www/html/YouPHPTube/plugin/LiveChat/chat-server.php &`

**Comment by cheesewizz** [comment]
Thank you very much DDC.
