### ISSUE TITLE
Language Flag Selection

### ISSUE THREAD

**Issue by stefannagies** [DanielnetoDotCom/YouPHPTube#209]
Hello,
i am trying to add korean language and there are no flags to select from available. 
can you please give me a suggestion as to why and how to fix this.

![language flag](https://user-images.githubusercontent.com/11727598/32655620-f0f25d7e-c640-11e7-8e41-94da7e877f2d.png)

**Comment by DanielnetoDotCom** [comment]
Sorry, I will try to fix it

**Comment by stefannagies** [comment]
Thank you ...

**Comment by DanielnetoDotCom** [comment]
Please update your files and try again

**Comment by stefannagies** [comment]
Hello,
worked perfect! :)

Thank you very much... great job..

**Comment by DanielnetoDotCom** [comment]
you welcome
