### ISSUE TITLE
Autoplay video's configurable

### ISSUE THREAD

**Issue by glumpje** [DanielnetoDotCom/YouPHPTube#21]
Noticed that it can be a bit annoying when clicking around that the video restarts or starts playing again. Of course whenever you click on a video it should play automatic.

**Comment by DanielnetoDotCom** [comment]
Ok, I will put this on TODO List, thank you

**Comment by DanielnetoDotCom** [comment]
Hi, now we have 2 autoplay options

This is the default option
![image](https://cloud.githubusercontent.com/assets/18009293/26697689/4d9b9d42-46e9-11e7-974b-2fbcf85aeeb2.png)

This is the client option to play next video

![image](https://cloud.githubusercontent.com/assets/18009293/26697745/82c4f3ec-46e9-11e7-8d31-f76e83334466.png)

**Comment by glumpje** [comment]
Fantastic thanks!

**Comment by alimusa80** [comment]
is there away to work around and put ads bellow the client option i figure it out header without using you auto ads on script, i know you have build system that let put ads both header and client option at the same time but i want to have different ads  header and the client option that  is why i am looking way to bypass
