### ISSUE TITLE
Offline/Online Status and Counter Live Stream

### ISSUE THREAD

**Issue by stefannagies** [DanielnetoDotCom/YouPHPTube#210]
Hello,
i setup rtmp server and youphptube on two different vps. all is working great, streaming via OBS, but the player site is still showing me offline and the counter shows 0. stats page and everything is working as expected. Can you point me in the right direction as to why the counter and status message don't switch to Online and show correct live stream count

kind regards

Stefan

![livestream](https://user-images.githubusercontent.com/11727598/32696651-54a45500-c7b0-11e7-8d21-964599b792b9.png)

**Comment by DanielnetoDotCom** [comment]
How is your stats? it is on the plugin configuration tab
`{"button_title":"LIVE","server":"rtmp://[nigix-server]/live","playerServer":"http://[nigix-server]:8080/live","stats":"http://[nigix-server]:8080/stats"}`

Also check if you have to marked listed transmition to make it appear
![image](https://user-images.githubusercontent.com/18009293/32698524-147aff80-c786-11e7-90f3-e89cf3c107b3.png)

**Comment by stefannagies** [comment]
Hello,
thank you for your reply..
since i am using a dedicated vps for the rtmp and nginx i use standard ports. I also use a private network backend connection in the datacenter, so my rtmp server has 192.168.xx address and is reachable from the phpyoutube server. i will reconfigure it and go through the public frontend and update...

kind regards

Stefan

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by p-Clerick** [comment]
Hi.
I have a similar problem with TS.
When my site use HTTP, counter of LIVE translations works correctly.
But after transit to HTTPS LIVE counter shows "0" almost all times? when I streaming.
stats.json.php returned something like there during working streaming:
{"error":true,"msg":"OFFLINE","nclients":0,"name":"undefined","applications":[],"disableGif":false,"countLiveStream":1}

Can somebody tell me, where I most seek the problem?

**Comment by DanielnetoDotCom** [comment]
@p-Clerick you have to make sure your NGINX is https as well

**Comment by DanielnetoDotCom** [comment]
"when 2 different translations from different computers take place"

What translations?

**Comment by p-Clerick** [comment]
Sorry, I want to say "2 different live streams"
