### ISSUE TITLE
YouPHPTube_Encoder Database - Processing

### ISSUE THREAD

**Issue by cheesewizz** [DanielnetoDotCom/YouPHPTube#211]
I tried to configure YouPHPTube-Encoder Processing of Database is Keeps Processing nothing happened

![youtubestreamer hang on processing](https://user-images.githubusercontent.com/14123082/32709396-16b180d6-c86b-11e7-8708-a6bb7de8901a.png)

**Comment by cheesewizz** [comment]
ok its working now i just replace the streamer site uRL http://192.168.50.209/YouPHPTube/

**Comment by DanielnetoDotCom** [comment]
Nice :)
