### ISSUE TITLE
bulk video removal

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [DanielnetoDotCom/YouPHPTube#212]
1) How to disable annoying video delete confirmation
2) How to delete 100 videos at once.
3) How to disable annoying success message after video deletion. It is logical if i deleted video and not see it at list anymore then it deleted. Why need to press OK button every time. It is stupid operation which just eating time.

**Comment by DanielnetoDotCom** [comment]
The bulk delete will be implemented in the future.
And please be polite next time.
