### ISSUE TITLE
Youphptube show that i host video even if it is completely empty

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [DanielnetoDotCom/YouPHPTube#213]
![2017-11-14_110926](https://user-images.githubusercontent.com/22169129/32774468-a863c86a-c92c-11e7-80ec-c5fd1501614e.png)

**Comment by DanielnetoDotCom** [comment]
Maybe the video is in another user account,

**Comment by jpVm5jYYRE1VIKL** [comment]
It is only one account in system .

**Comment by DanielnetoDotCom** [comment]
You right then this is wrong. does it happened on demo site?
What is your site. can I check it?

**Comment by jpVm5jYYRE1VIKL** [comment]
Not sure that you can look . Because from one side it was created internally and from another side i already reinstalled it.  If this issue appear again i ll report new ticket.
But i have a feeling that hosting counter increase even if during video import was error.

**Comment by DanielnetoDotCom** [comment]
I see. 
But the time counter comes from database. those videos must be on database.
did you add those videos as an ad?
Ads does not appear on the regular way. but it counts as a video time.

**Comment by jpVm5jYYRE1VIKL** [comment]
nope . I installed your application not for money and advertisements. I not use them . It is for my child. Because youtube not do normal video censorship. and show to my 2 year child  videos like https://www.youtube.com/watch?v=uXjJdv5fj5k . So i decided to create for him personal youtube. And your product was most good for such purpose.  

PS: Before i did reinstall i looked in DB little bit and seen in table videos . Records which was not showed in Gui. I think i found how it happened . In happens in case of Embed video from yourtube.

**Comment by DanielnetoDotCom** [comment]
It is a good idea
Is your new installation ok?

**Comment by jpVm5jYYRE1VIKL** [comment]
This is example of record which not shows anywhere in gui but exist in table. 

"35","12     -","12-",,"1","a","2017-11-14 14:04:57","2017-11-14 15:02:50","1","2","_YPTuniqid_5a0aeb092079d6.00278053","01:01:23","embed",,"1","0","1",NULL,"https://www.youtube.com/watch?v=FywilkySqDU"

**Comment by DanielnetoDotCom** [comment]
you have to check if this video is on video_ads table

**Comment by jpVm5jYYRE1VIKL** [comment]
MariaDB [web_tube]> select * from video_ads;
Empty set (0.00 sec)

MariaDB [web_tube]> 

MariaDB [web_tube]> select * from videos where id = 35;
+----+----------+-------------+-------------+-------------+--------+---------------------+---------------------+----------+---------------+------------------------------------+----------+-------+---------------------+-------+----------+------+-----------+---------------------------------------------+
| id | title    | clean_title | description | views_count | status | created             | modified            | users_id | categories_id | filename                           | duration | type  | videoDownloadedLink | order | rotation | zoom | youtubeId | videoLink                                   |
+----+----------+-------------+-------------+-------------+--------+---------------------+---------------------+----------+---------------+------------------------------------+----------+-------+---------------------+-------+----------+------+-----------+---------------------------------------------+
| 35 | 12     - | 12-         |             |           1 | a      | 2017-11-14 14:04:57 | 2017-11-14 15:02:50 |        1 |             2 | _YPTuniqid_5a0aeb092079d6.00278053 | 01:01:23 | embed |                     |     1 |        0 |    1 | NULL      | https://www.youtube.com/watch?v=FywilkySqDU |
+----+----------+-------------+-------------+-------------+--------+---------------------+---------------------+----------+---------------+------------------------------------+----------+-------+---------------------+-------+----------+------+-----------+---------------------------------------------+
1 row in set (0.00 sec)
