### ISSUE TITLE
Unable to sort video in categories

### ISSUE THREAD

**Issue by Gwenguillaume** [DanielnetoDotCom/YouPHPTube#214]
Hi,
First , sorry for my English , I'm french.
I have a problem with my YouPhpTube server. I can not sort video in a categorie. (View capture)
the cursor turns. The problem is same in the demo site: https://demo.youphptube.com 

![capture](https://user-images.githubusercontent.com/33656927/32777677-6a7a0842-c937-11e7-8cdb-26bef74b9fb1.JPG)

Thanks

**Comment by DanielnetoDotCom** [comment]
I will take a look on that

**Comment by Gwenguillaume** [comment]
Thanks it's OK !

**Comment by DanielnetoDotCom** [comment]
Can you update your files, I just release a fix
