### ISSUE TITLE
Almost not possible to work with big video collection.

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [DanielnetoDotCom/YouPHPTube#215]
Not possible to do assignment  multiply videos to one category. 
Not possible to assign one video to multiply categories. 
Not possible to filter video by category or group.
Not possible to deactivate multiply videos. Not possible to deactivate by category, 
Not possible to create multiply channels.

If you change category somewhere in the middle of video list. Page refresh completely and you forced to search again video you just modified. 

Constant nag modals with "Your video has been saved" and requirement to press button. If somebody have same issue you can use Escape button on keyboard it can make your life little bit better.

**Comment by DanielnetoDotCom** [comment]
Thanks for notice that, we will try to improve this in future versions

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by jpVm5jYYRE1VIKL** [comment]
Strange style to close issue even if it not solved.

**Comment by DanielnetoDotCom** [comment]
Sorry you right it was closed by mistake

**Comment by DanielnetoDotCom** [comment]
> Not possible to do assignment multiply videos to one category.
You can do that now

> Not possible to assign one video to multiply categories.
Not yet

> Not possible to filter video by category or group.
On the search option now filter by category too

> Not possible to deactivate multiply videos. 
You can do that now

> Not possible to deactivate by category,
No, it is not

> Not possible to create multiply channels.
Not yet

> If you change category somewhere in the middle of video list. Page refresh completely and you forced to search again video you just modified.
This is a issue from bootgrid, I could not figure out hot to fix this

> Constant nag modals with "Your video has been saved" and requirement to press button. If somebody have  same issue you can use Escape button on keyboard it can make your life little bit better.
I have removed some

I guess now is ready to close :)
