### ISSUE TITLE
Wrong category during video import.

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [DanielnetoDotCom/YouPHPTube#216]
Encode video and audio option always place video to Default category even if you start it in another category page, 
For example you have category Default and list1.
Category "list1" now empty and if you enter to to it you will see 
"Warning! We have not found any videos or audios to show. "
Ok not problem. Press on top encode video and audio. And after import  video appears in "Default" category instead of "list1"

**Comment by DanielnetoDotCom** [comment]
Thnaks again, It is in our plans to let you decide what categories will be the video after upload it

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
