### ISSUE TITLE
.htaccess endline style

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [DanielnetoDotCom/YouPHPTube#217]
.htaccess have windows endline style (CRLF) all another files have UNIX style (LF). 

UPDATE: It is not only .htaccess . Part of files have CRLF part of files (LF)

**Comment by DanielnetoDotCom** [comment]
Thanks for notice it.
Does it makes come up any error?

**Comment by jpVm5jYYRE1VIKL** [comment]
Nope. But it create "^M" in linux console editor. Just cosmetic issue.

**Comment by DanielnetoDotCom** [comment]
ok, thanks
