### ISSUE TITLE
Changer Order Ctaegories

### ISSUE THREAD

**Issue by Gwenguillaume** [DanielnetoDotCom/YouPHPTube#218]
Hi,

Is it possible to change the order of categories by alphabetical order ?

![capture](https://user-images.githubusercontent.com/33656927/32784683-c7170e98-c94f-11e7-9592-cd0481cc9323.JPG)

Thanks !

**Comment by DanielnetoDotCom** [comment]
Hi, I just release a fix it is by alphabetical order now

**Comment by Gwenguillaume** [comment]
Thanks you !!
