### ISSUE TITLE
Subcategorys and /cat/-overview

### ISSUE THREAD

**Issue by hersche** [DanielnetoDotCom/YouPHPTube#219]
Hey there,

i think, subcategorys can make much sense to bring a better overview of projects.

i would do it myself and tried a bit, but i didn't know the bootstrap-stuff and always when i click on a parent-category, menu disappears after a click (what didn't matter, when the click loads a new site - what all of current menu-points do).

in the db, the whole thing can be very simple - a additional column with a int that is -1 by default and parent, or the id of a parent-category.

in the ui for set it, a WHERE categoryid != current-id should be enough, so it has all other cat's than itself..

i can add my try's, but i assume you could do it faster and cleaner (since it's your project).

also, when i access youphptube-url/cat/, there's a 404 - wouldn't it make sense to create a overview there?
also preview-pic's (and gif's? they're pretty cool on videos :) ) for cat's could be nice for such a site..

let me know what you think about this.

best regards

vinz

edit: didn't see #45 , sorry. anyway, would be interessting in case it's needed, i would help to realize.

**Comment by DanielnetoDotCom** [comment]
You right, it may be fixed and implemented in the future :) thanks again for your ideas

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by mj1985** [comment]
Subcategories would be awesome, the only feature I've been missing, while switching from clipbucket

**Comment by DanielnetoDotCom** [comment]
@mj1985 Yeah, that is something will be implemented in the future

**Comment by hersche** [comment]
i'm working on it, basicly it does what it should, some beauty-stuff have to be done:
https://github.com/hersche/YouPHPTube/commit/521b78e4776a54128f42c6d955c12607ad4ed94f

**Comment by mj1985** [comment]
@hersche do you need help witht the beauty stuff?

**Comment by hersche** [comment]
yeah, wouldn't be bad.. if you could recommend a good beautifier for php, you can tell me.. i begin to do this manual since it's getting worse with those i've tried.

**Comment by mj1985** [comment]
I'll get your version later today and will test it :)

**Comment by hersche** [comment]
btw, if you read still here, there was some progress again, mainly in gallery-mode..

**Comment by hersche** [comment]
for the moment, main-branch is changed to master..
the reason is here: #563
