### ISSUE TITLE
(help) do not know what to do next.

### ISSUE THREAD

**Issue by okazgumi** [DanielnetoDotCom/YouPHPTube#22]
![3](https://cloud.githubusercontent.com/assets/29045007/26555372/aa5eacfc-44cf-11e7-8ce8-3e21135ddad5.png)
sorry I can not using to english well.

**Comment by DanielnetoDotCom** [comment]
Hi, try to look on apache log.
On ubunto you can type 
`tail /var/log/apache2/error.log`
It may give you some glue

BTW what is your main language?

**Comment by okazgumi** [comment]
I usually using Japanese.

**Comment by okazgumi** [comment]
I opened "error.log".
PHP Warning:  require_once(../videos/configuration.php): failed to open stream: No such file or directory in /home/hogehoge/public_html/view/index.php on line 8
PHP Fatal error:  require_once(): Failed opening required '../videos/configuration.php' (include_path='.:/usr/share/mphp54/pear:/usr/share/php') in /home/hogehoge/public_html/view/index.php on line 8

**Comment by okazgumi** [comment]
Is it bad to use a rental server?

**Comment by okazgumi** [comment]
If these issues resolve, I would like to help localizing into Japanese

**Comment by DanielnetoDotCom** [comment]
if you want send me your server credentials (IP/URL, user and password), I will help you to configure it.
send it to developer@youphptube.com

**Comment by okazgumi** [comment]
I can never thank you enough.

**Comment by DanielnetoDotCom** [comment]
Ok, I am waiting for your email

**Comment by okazgumi** [comment]
I sent a mail.
I am worried whether I am in a spam account

**Comment by DanielnetoDotCom** [comment]
Got it
