### ISSUE TITLE
Next video set-able

### ISSUE THREAD

**Issue by hersche** [DanielnetoDotCom/YouPHPTube#220]
Hello,

i think, it would be a usefull idea to let uploaders set the next video - if not set, the current used chooser could be the fallback.

this could be usefull in various situations like series or when your hoster only allows a limited uploadsize and you've to split your videos out of this.

also like i described in #219 i would add a single column to the videos-table called nextVideo or so, containing -1 or videoId of next-video.

also here i would like to do, but maybe you're much faster and it would be relative easy for you by knowing your project better.

best regards

vinz

best regards

**Comment by DanielnetoDotCom** [comment]
Really great idea, it may be implemented in next verions

**Comment by DanielnetoDotCom** [comment]
Good news, you idea was implemented :)
