### ISSUE TITLE
Increase count view video

### ISSUE THREAD

**Issue by Gwenguillaume** [DanielnetoDotCom/YouPHPTube#221]
hi,

is it possible to increment the view counter only when play button is push ?
Currently the counter is incremented when we refresh the page

Thanks

**Comment by DanielnetoDotCom** [comment]
You right, the problem to increment on that way is the embed videos. we have no control on click on play button

**Comment by Gwenguillaume** [comment]
ok, thanks

**Comment by ehk20** [comment]
Our site is entirely based on embedded videos so this is a bit of an issue for us too and I was therefore wondering if the views counter should simply not be shown for embedded videos?
