### ISSUE TITLE
Change a permalink like Youtube?

### ISSUE THREAD

**Issue by fuckalone** [DanielnetoDotCom/YouPHPTube#223]
Hi Danielneto. I see this project is awesome. But in video permalink, can you have a option to change permalink like Youtube (youtube.com/watch?v=9@danielyouphp)?. Because this good for multi file with same name and if user change video name, permalink will permanent and helpful for SEO. What do you think about this?

**Comment by DanielnetoDotCom** [comment]
Great, I will probably do that soon thanks for the idea

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
