### ISSUE TITLE
how to change path of VIDEOS Uploaded

### ISSUE THREAD

**Issue by cheesewizz** [DanielnetoDotCom/YouPHPTube#224]
Good morning

Is it possible to separate the path of videos folder uploaded to be redirect to another storage device.
just incase the system failed and more capacity.

Thanks

**Comment by DanielnetoDotCom** [comment]
you will need to move the whole youphptube site.
videos are always stored on videos directory

**Comment by brando-online** [comment]
I have this setup with a network share from a Windows PC. I'm running the streamer/encoder from a VM, but didn't want all the video files to grow the virtual disk to the point that it could cause a performance issue.

Things you need to accomplish this:

* An SMB or similar network share with proper permissions for a new video storage. I'm using a Windows 10 PC with the built in file-sharing to serve up the new video network share \\192.168.0.10\YouPHPTube-Vids\
* Copy (at minimum) configuration.php and youphptube.log files to new network share  ***IMPORTANT, if you miss this step you break your install of streamer/encoder***. If you navigate to your network share, you should be able to see both of these files. If you have pre-existing video files that you've already encoded or added to your YouPHPTube site, copy these over to the new video network share as well.
* Update /etc/fstab to permanently mount your new video network share on your YouPHPTube server
-- I used this walkthru to mount password protected Windows Network Share: https://wiki.ubuntu.com/MountWindowsSharesPermanently
-- You will need to add the 'special permissions' uid=www-data like it show on above walk through. I read the first part, got it mounted, seemingly it worked, until it came time to saving the file through the encoder website, it failed everytime. This caused me the most time trying to diagnose, shouldve just kept reading. Learn from my mistakes lol
* Then reboot your YouPHPTube and Encoder servers - for good measure. I went through so many steps trying to diagnose issues that I'm not entirely sure it's necessary, but it never hurts to ensure everything starts up nicely on initial boot.

I also tried moving the Encoder videos directory (temp files) to a network share as well but the performance hit wasn't worth it. I'll leave it on my VM and just clean up the left over files with a automated script or something, but this IS possible :)

IMPORTANT FYI: While this seems doable, I'm not sure if it's causing issues on new uploads. It appears newly uploaded videos are glitchy/pixely when played back. However everything saves in it's proper place, generates thumbnail, etc.

**Comment by DanielnetoDotCom** [comment]
I have find way to fix it:
take a look on that. https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Moving-videos-directory-and-securing-files-from-direct-access-to-the-video-source-file

I could with success move the videos dir.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
