### ISSUE TITLE
Warning! We have not found any videos or audios to show

### ISSUE THREAD

**Issue by jimmyk1** [DanielnetoDotCom/YouPHPTube#225]
Hey guys. How does the audio only page work...I keep getting this error and would like to upload some audio but I do not see any examples of what it should look like or how to configure.

Thanks

**Comment by DanielnetoDotCom** [comment]
Hi, looks like audio files stops to work (we were to much focused on videos).
We will put it back this week.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
