### ISSUE TITLE
Encoder not working

### ISSUE THREAD

**Issue by Sugiramireille** [DanielnetoDotCom/YouPHPTube#226]
Hi Daniel, Hope you are doing good. I am facing an issue with the encoder installed on my server. I tried to upload a video of 900MB but it failed, I tried another of 500 MB still in the queue for two days now. My server is a VM, with 2TB of diskspace and 16GB of RAM. The encoder Max File Size is: 1.50GB The Streamer Max File Size is: 1.50GB The Streamer Max Video Storage Limit is: Unlimited And all resources seem ok and more than enough. ANy idea?

**Comment by DanielnetoDotCom** [comment]
please take a look on your log file.
It should be in videos/youphptube.log

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
