### ISSUE TITLE
Disable function SHARE

### ISSUE THREAD

**Issue by Gwenguillaume** [DanielnetoDotCom/YouPHPTube#227]
Hi,

It's possible to disable share function in videos ?
Thanks

**Comment by DanielnetoDotCom** [comment]
What share, the embed share or the share on the main page?

The share on the main page you can not disable now.
But the one on the embed page it is a plugin. just disable the plugin and it will dissapear

**Comment by Gwenguillaume** [comment]
yes, it's the share below video:
![capture](https://user-images.githubusercontent.com/33656927/33026465-c35562d0-ce10-11e7-9e31-4662c88edaed.JPG)

i don't find the plugin:

![capture1](https://user-images.githubusercontent.com/33656927/33026516-e13f1480-ce10-11e7-94d5-aeda596d3b44.JPG)

Thanks !

**Comment by DanielnetoDotCom** [comment]
The shared below video is not possible to disable.
The share plugin for embed videos is a paid plugin 
![image](https://user-images.githubusercontent.com/18009293/33028207-0bd00b90-cdf4-11e7-9c85-3f633e4a3e29.png)

**Comment by Gwenguillaume** [comment]
Ok Thanks
