### ISSUE TITLE
problem with some videos

### ISSUE THREAD

**Issue by Gwenguillaume** [DanielnetoDotCom/YouPHPTube#228]
Hi, I have launch git pull 2 hours ago and since then I can not read some videos anymore. The image remains frozen and the sound continues.
Thanks

**Comment by DanielnetoDotCom** [comment]
What is your URL?
Try to restart the browser. I cant see anything causing it.

**Comment by Gwenguillaume** [comment]
Is it possible that it comes because of the modification of the url. I modified the access url in the configuration.php file
some videos work others not.
Thanks

**Comment by DanielnetoDotCom** [comment]
if you change the URL you have to change the configuration.php file.
Are you sure you also move all videos?
If you are missing a video file it will not work

**Comment by Gwenguillaume** [comment]
I followed this tutorial: https://tutorials.youphptube.com/video/fix-youphptube-url-after-move-server-location-and-ip

**Comment by DanielnetoDotCom** [comment]
I think the tutoria does not show how to move videos, but I mean did you move the entire videos directory?

**Comment by Gwenguillaume** [comment]
Sorry, I found the source of the problem. In fact this comes from some videos with the mp4 codec. The sound is good but the video remains frozen.I re-coded in h264 and the video is passed.
Thanks

**Comment by DanielnetoDotCom** [comment]
nice :)
