### ISSUE TITLE
How to embed video like youtube in our project from this metacafe & vid.me

### ISSUE THREAD

**Issue by rohitnehra** [DanielnetoDotCom/YouPHPTube#229]
Hey Daniel
I tried it on my project as well as on youphptube demo website also.
The video get fetched but we are unable to play that video.

Recently you solved dailymotion problem. 
This is same kind of problem.

Please tell me about how to hire one hour support & premium services also.
I will definitely want your services as soon as I launched the website.

Thanks & Regards
Rohit Nehra

You are doing a great work. I will support you as much as possible & asap.

**Comment by DanielnetoDotCom** [comment]
hi, use this link to get 1 hour support: https://www.youphptube.com/services#service-prices

I guess 1 hour is enough to make metacafe and vid.me embed support

Thanks

**Comment by rohitnehra** [comment]
currently I don't have any funds.

When I launch the website I promise I will purchase your premium services.

Thanks & Regards
Rohit Nehra

**Comment by DanielnetoDotCom** [comment]
Hey, good news for you
YouPHPTube now support metacafe & vid.me
Just update your files

**Comment by rohitnehra** [comment]
Thanks a lot Daniel
