### ISSUE TITLE
Users Videos management

### ISSUE THREAD

**Issue by Sugiramireille** [DanielnetoDotCom/YouPHPTube#230]
Is there an option for the admin to manage uploaded videos by users? To moderate, to approve or delete videos uploaded by users?

**Comment by DanielnetoDotCom** [comment]
Not, yet. maybe in future versions

**Comment by datosior** [comment]
Is there possible to upload videos to the separate category folders, because it is difficult to find loaded videos on local machine?

**Comment by DanielnetoDotCom** [comment]
All videos sits on videos directory. you cant separate them

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
