### ISSUE TITLE
New Language file

### ISSUE THREAD

**Issue by Sugiramireille** [DanielnetoDotCom/YouPHPTube#231]
I have translated YouPHPTube into my language Kinyarwanda (From Rwanda - East Africa), how do I share it with community?

**Comment by DanielnetoDotCom** [comment]
This is great.

Please make a pull request https://help.github.com/articles/creating-a-pull-request/
this way your name will appear as a contributor

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
