### ISSUE TITLE
Bulk encode cant get to work

### ISSUE THREAD

**Issue by k7n2g** [DanielnetoDotCom/YouPHPTube#235]
Hi Daniel hope you are well   have issue with Bulk encode     installed encoder on new separate server  
added playlist to youtube   downloaded playlist from YouTube okay no problem - have tried all local  paths like /playlist   /YouPHPTube/playlist    tried with  url complete path  videos are in playlist but cant  access in Bulk encode  to see files   anyone have a solution please

**Comment by DanielnetoDotCom** [comment]
how did you download the play list?
Did you try that way? https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Import-a-Full-playlist-from-Youtube

**Comment by k7n2g** [comment]
Hi Daniel followed the instructions playlist down loads with youtube-dl -f best -citw -v "https://www.youtube.com/watch?v=My-PlayList"  into YouphpTube  playlist /directory/ okay    will contact you later to sort for me please Dave

**Comment by DanielnetoDotCom** [comment]
Ok, nice :)

**Comment by VJPranay** [comment]
@k7n2g I have faced same , but it worked for me after I install  php7.0-xml , please try 

`sudo apt-get install php7.0-xml`

 Duplicate #https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/issues/20

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
