### ISSUE TITLE
Mobile Live Stream

### ISSUE THREAD

**Issue by winklov** [DanielnetoDotCom/YouPHPTube#236]
Hi

When will we be able to stream live from mobile devices almost like facebook live or twitch mobile live

Can it be integrated into the mobile and the android app

**Comment by DanielnetoDotCom** [comment]
Hi, Stream from mobile requires an RTMP app. is not possible do it from browsers.
There are several RTMP apps out there. I have used Larix Broadcaster with success on my Android mobile.
https://play.google.com/store/apps/details?id=com.wmspanel.larix_broadcaster&hl=en

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by polfejs** [comment]
I have installed Larix Broadcaster. Added rtmp and key but live not working. Tested on Pc from OBS and it works

**Comment by DanielnetoDotCom** [comment]
if work on OBS and does not with Larix, or it is a Larix problem or you miss to add some information.
