### ISSUE TITLE
I can upload and encode video, but not show up in streamer

### ISSUE THREAD

**Issue by alexevermeulen** [DanielnetoDotCom/YouPHPTube#237]
Hi Daniel !

its a super application !! i will use it in our TV station in the Childrenhospital in Amsterdam as their VOD platform !

but... i am able to encode and upload the videos, but they are not showing in the streamer site...

perhaps I'm doing something wrong.

Are you able to steer me in the right direction ?

greetz, Alex Vermeulen

**Comment by DanielnetoDotCom** [comment]
Hi

when they start to encode usually they create as empty video on the streamer site.
I am not sure what is wrong, may be some missconfiguration on encoder site.

is possible to access your TV station from here? then I can take a closer look what is going on?

**Comment by alexevermeulen** [comment]
off course... i can send you the teamviewer acces... preferable via direct message :)

**Comment by DanielnetoDotCom** [comment]
send to developer@youphptube.com

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
