### ISSUE TITLE
How can one limit the common users from creating video qualities

### ISSUE THREAD

**Issue by danionescu2007** [DanielnetoDotCom/YouPHPTube#239]
Well the question is in the title. I am reffering to these: 
<img width="183" alt="screen shot 2017-11-26 at 03 01 55" src="https://user-images.githubusercontent.com/4688610/33236257-ad5d5a60-d256-11e7-99fa-5aff03c434d0.png"> in the encoder.
For example I want to limit the posibility to create only SD and HD versions, but to enforce it on the user interface.

**Comment by DanielnetoDotCom** [comment]
unfortunately there is no such option yet

**Comment by danionescu2007** [comment]
Any thoughts on implementing something like this?

**Comment by DanielnetoDotCom** [comment]
Hello
For now we have no plans to implement this functionality, which does not mean that it can not be implemented in the future.
But if you need it right away, please contact us at developer@youphptube.com that you can negotiate to buy hours of support and development services. https://www.youphptube.com/services
