### ISSUE TITLE
I could not proseed this page...

### ISSUE THREAD

**Issue by okazgumi** [DanielnetoDotCom/YouPHPTube#24]
http://61.195.96.19
I changed the override and restarted apache...
What do I do the next ?

**Comment by DanielnetoDotCom** [comment]
I need more details about it

**Comment by okazgumi** [comment]
would I sent server information to your email ?

**Comment by okazgumi** [comment]
would I sent server information to your email ?

**Comment by okazgumi** [comment]
sorry. I disordered about serverdown...

**Comment by DanielnetoDotCom** [comment]
Sure, i will try to help you today. as soon as I get home

**Comment by DanielnetoDotCom** [comment]
Yout YouPHPTube is installed http://61.195.96.19.
I have sent you an email with instructions

**Comment by okazgumi** [comment]
thanks!!!!!!!!!!I try my best to your project !01.06.2017, 04:12, "YouPHPTube" <notifications@github.com>:Yout YouPHPTube is installed http://61.195.96.19.
I have sent you an email with instructions
