### ISSUE TITLE
file uploads successfully and see videos in video folder but doesn't list on the streamer

### ISSUE THREAD

**Issue by d0773d** [DanielnetoDotCom/YouPHPTube#240]
I believe my videos have been uploaded successfully.  I also see the videos that I uploaded in the videos directory; however, I do not see any of the videos listed on my youphptube streamer.  I also used the youphptube encoder installed on my server to upload videos, I see they have been a success via the Queue Log, but still, I do not see any of the videos listed on the streamer. 

I'm not sure why or how to fix this issue.

**Comment by DanielnetoDotCom** [comment]
Hi

Sorry about that but I guess I know what happened.

On version 4.4 we add a column on video table `next_videos_id` it suppose to allow null values, but by mistake it was released with not null.

It is fixed now you need to update your files and after that you have 2 options:

1. You need to drop the database and reinstall your YouPHPTube
2. Or you can update your files and run this command on your mysql client.
 `ALTER TABLE `videos` CHANGE COLUMN `next_videos_id` `next_videos_id` INT(11) NULL DEFAULT NULL;`

If it does not fix the problem show us your log file 
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by d0773d** [comment]
Hi again.  I dropped my database and reinstalled youphptube successfully.  Everything seems to be functioning properly. Thanks!

**Comment by DanielnetoDotCom** [comment]
I am glad

**Comment by mikweb2017** [comment]
Thanks
