### ISSUE TITLE
linux Installion

### ISSUE THREAD

**Issue by DemonRem** [DanielnetoDotCom/YouPHPTube#241]
when try to install it on Linux Centos 
I got those following errors

Your Server , You Must Install Apache
Your PHP Version is , we recommend install PHP 5.6.x or greater
Mod Rewrite is not enable
Your Video Directory Must Be Writable
Your Post_Max_siz is , it must be at least 100M
Your Upload Max_filesize is , it must be at least 100M

now I installed the webserver "httpd"

but seems like something get wrong

**Comment by DanielnetoDotCom** [comment]
try to fix at least  ` Your Video Directory Must Be Writable `
and ignore the error and continue
YouPHPTube is designed for ubuntu, but with the exception of live stream all features should work without problems

**Comment by DemonRem** [comment]
still the same even with Ubuntu 

Daniel can you make interaction in the readme file?

**Comment by DanielnetoDotCom** [comment]
Hi, please put you log file here to help us to find the problem

what is " interaction in the readme file"?

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by subhamraj** [comment]
Hey daniel i need the same help?

**Comment by subhamraj** [comment]
Mod_rewrite is not enabled in my CentOs dedicated server!! Please help me out on this

**Comment by subhamraj** [comment]
http://68.65.120.35/install/index.php

**Comment by subhamraj** [comment]
This is my hosting link

**Comment by DanielnetoDotCom** [comment]
I went to the link and it is installed now correct?

**Comment by patricknasci** [comment]
I'm having problem with my installation ... please help
I already installed it but now it's on this page it's all configured
https://videos.cenathostbr.com/

**Comment by DanielnetoDotCom** [comment]
what OS are you using?
are you sure you have enabled mod rewrite?
did you restart apache?

**Comment by patricknasci** [comment]
CentOS

**Comment by patricknasci** [comment]
MOD RWRITE ENABLED

**Comment by patricknasci** [comment]
When I put the .htaccess error 500
