### ISSUE TITLE
Linux Local Network Streaming

### ISSUE THREAD

**Issue by DemonRem** [DanielnetoDotCom/YouPHPTube#242]
my obs say can't connect to server when I try to stream

**Comment by DanielnetoDotCom** [comment]
you may have a misconfiguration on NGINX, paste your nginx.conf file here

**Comment by DemonRem** [comment]
ok few thing to say before 

I have installed nginx + rtmp module on port 8080 there is the encoder while apache server is running on port 80 with YouPHPTube site

the nginx.cfg is

`worker_processes  1;

    error_log  logs/error.log debug;

    events {

            worker_connections  1024;

    }

    rtmp {

            server {

                    listen 1935;

                    allow play all;

                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments

                    application live {

                            allow play all;

                            live on;

                            #record all;

                            #record_path /video_recordings;

                            #record_unique on;

                            hls on;

                            hls_nested on;

                            var/www/html/hls_path /HLS/live;

                            #hls_playlist_length 4s;

                            #hls_fragment 1s;

                            hls_fragment 10s;

                            on_publish http://10.0.0.8/plugin/Live/on_publish.php;

                            on_play http://10.0.0.8/plugin/Live/on_play.php;

                            on_record_done http://10.0.0.8/plugin/Live/on_record_done.php;

                    }

            }

    }

    http {

            include       mime.types;

            default_type  application/octet-stream;

            server {

                    listen 8080;

                    server_name localhost;

                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://10.0.0.8/live/my-stream-key/index.m3u8"      

                    location /live {

                            # Disable cache

                            add_header 'Cache-Control' 'no-cache';



                            # CORS setup

                            add_header 'Access-Control-Allow-Origin' '*' always;

                            add_header 'Access-Control-Expose-Headers' 'Content-Length';



                            # allow CORS preflight requests

                            if ($request_method = 'OPTIONS') {

                                    add_header 'Access-Control-Allow-Origin' '*';

                                    add_header 'Access-Control-Max-Age' 1728000;

                                    add_header 'Content-Type' 'text/plain charset=UTF-8';

                                    add_header 'Content-Length' 0;

                                    return 204;

                            }

                            types {

                                    application/vnd.apple.mpegurl m3u8;

                            }

                            alias /HLS/live;

                    }

                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     

                    #location /stats {

                    #        stub_status;

                    #}

                    location /stat {

                            rtmp_stat all;

                            rtmp_stat_stylesheet stat.xsl;

                    }

                    location /stat.xsl {

                            root html;

                    }

                    location /control {

                            rtmp_control all;

                    }

                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     

                    location / {

                            root   html;

                            index  index.html index.htm;

                    }   

            }

    }`

**Comment by DanielnetoDotCom** [comment]
Looks like correct, are you sure port 1935 is not blocked?

**Comment by DemonRem** [comment]
yes i sure

**Comment by DanielnetoDotCom** [comment]
I am not sure what is going on, if you can[ hire me for 1 hour](https://www.youphptube.com/services) I can take a look on your server

**Comment by DemonRem** [comment]
it's a vm server opened with virtualbox Ubuntu on my local pc

**Comment by DanielnetoDotCom** [comment]
Hi, run in on a VM should be no problem. just make sure your VM is using a bridge network interface and have a local ip address from your local network

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
