### ISSUE TITLE
Not Possible for Reverse Proxy working

### ISSUE THREAD

**Issue by laweschan** [DanielnetoDotCom/YouPHPTube#243]
Hi Daniel,

   currently the source code refer to href link is an absolute path rather than relative path, I know both has pros and cons but if working behind a reverse proxy, absolute path will resolve to a blackhole or an unresolve linking.

   is that possible to implement a better way so reverse proxy can co-work with youphptube ?

    thanks

Regards,
Lawes

**Comment by DanielnetoDotCom** [comment]
Do you mean a relative path would solve this issue?
Now all youphptube is based on absolute paths. I do not think I can change it now.

**Comment by laweschan** [comment]
yup change in relative path should solve it.
I aware this should require a revamp of coding, I hope it can be in your
roadmap and consider together with video path store request

cheers,
Lawes

**Comment by DanielnetoDotCom** [comment]
Yeah, I am thinking to move video storage place. making it more flexible and secure

**Comment by alexevermeulen** [comment]
moving the video storage would be cool !!

**Comment by DanielnetoDotCom** [comment]
@alexevermeulen  and @laweschan take a look on that. https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Moving-videos-directory-and-securing-files-from-direct-access-to-the-video-source-file

I could with success move the videos dir.

**Comment by laweschan** [comment]
Hi Daniel,

    thanks for info, but it should not the "wish" what we need.
  
  a bit over in here but it would better as we could share the user expects, or it would better have a place to discuss the roadmap or design in future

   the link shows that a way to hidden the video using xsendfile module, however, it seems if, without login, the video has no way to access currently. if video download is prohibit, then the solution should also help to cover the public access without "access link" to download.

   for video folder change, as previous article, we can use tricky way like symbolic link to redirect to different SAN LUN. however, for a future change, I think it would better for a folder structure like:

    - /videos
       --/$Categories1
                               ---/$subCategories1
                                                              ---/$upload_videos1 
                                                                                              ---$files{LD/SD/HD/img/gif}
       --/$Categories2
                               ---/$subCategories2
                                                              ---/$upload_videos2 
                                                                                              ---$files{LD/SD/HD/img/gif}
----------------------------------------------------------------------------------------------

   the benefit of that structure: 
     - we can separate the disk for different categories , even quota module for user not implement yet
     - a better organize of video resources,
           since, currently, all materials stored under videos/ folder, it is very hard for finding/grouping and lead to migration of resource very difficulty.

Regards,
Lawes

**Comment by DanielnetoDotCom** [comment]
@laweschan Thaks, I really like that idea, I will think about it

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
