### ISSUE TITLE
Automated video ingest ?

### ISSUE THREAD

**Issue by alexevermeulen** [DanielnetoDotCom/YouPHPTube#244]
Would it be possible to create a watch folder ? so you can automate the upload of videos ?

there is an other open source project (ffastrans) is capable to move files around..

with this also comes the question to have a possibility to add meta data in a separate file (same filename as video file) ?

Grtz Alex Vermeulen

**Comment by DanielnetoDotCom** [comment]
It may be possible, but is not made yet.

**Comment by jeroen1956** [comment]
I might not understand it... but:
1. The videos directory of the application is write protected, as I understand it
2. Create a symbolic link from there to a writeable directory
3. Use Samba server and let FFAStrans forward the videos there

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
