### ISSUE TITLE
error while uploading large ( > 2,4Gb ) video file

### ISSUE THREAD

**Issue by alexevermeulen** [DanielnetoDotCom/YouPHPTube#245]
Sorry!
Array ( [upl] => Array ( [name] => ETV35Xa.mp4 [type] => [tmp_name] => [error] => 7 [size] => 0 ) )

**Comment by DanielnetoDotCom** [comment]
I do not know what happened, but we can see the upload was not complete.

**Comment by nightstryke** [comment]
Apache has a 2gb upload max, make sure your php upload max file size and post max size are at most 2gb.

@DanielnetoDotCom may be in the future we could use straight nginx for the http/https/rtmp all in one.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
