### ISSUE TITLE
Como faço para corrigir esse erro?

### ISSUE THREAD

**Issue by CarolineAzeredo** [DanielnetoDotCom/YouPHPTube#247]
Erro de conexão (1045) ProxySQL: Acesso negado para o usuário 'id3745060_univversonovelas' @ '2a02: 4780: ruim: f00d :: 14' (usando senha: SIM)

**Comment by DanielnetoDotCom** [comment]
Tenta rodar o [script](https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/install/database.sql) manualmente e depois configurar o youphptube sem criar as tabelas

**Comment by CarolineAzeredo** [comment]
Continua aparecendo o mesmo erro....

**Comment by DanielnetoDotCom** [comment]
vc conseguiu rodar o script de criação do banco?

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
