### ISSUE TITLE
criei meu site, mas como faço para fazer upload dos videos?

### ISSUE THREAD

**Issue by CarolineAzeredo** [DanielnetoDotCom/YouPHPTube#248]
![image](https://user-images.githubusercontent.com/33944094/33405330-f90ed56a-d54e-11e7-959e-8af068427d29.png)

**Comment by DanielnetoDotCom** [comment]
Aparentemente, você não está logada

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
