### ISSUE TITLE
LiveTV Section Plugin

### ISSUE THREAD

**Issue by rollykaunang** [DanielnetoDotCom/YouPHPTube#249]
@DanielnetoDotCom 
I understand this software has live streaming section, but I would recommend to make a livetv section and this must apart from video section, and enough to put http://example.com/live/example.m3u8  which is from external streaming server like wowza, xtreamcodes or flussonic etc.. and make it as a plugin so who is interesting he or she could buy it. Please Hopely You will consider it.. Thank You So Much!

**Comment by DanielnetoDotCom** [comment]
This is a great idea, it will be in our roadmap for sure.

**Comment by rollykaunang** [comment]
@DanielnetoDotCom
Thank You Daniel.. I'll be the first to buy it..

**Comment by DanielnetoDotCom** [comment]
I am engaged in something else now, once I have some free time I will do it for sure.

**Comment by rollykaunang** [comment]
Thanks Daniel.

**Comment by danionescu2007** [comment]
+1  on this

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
