### ISSUE TITLE
Streaming Error with vMix

### ISSUE THREAD

**Issue by deatoninc** [DanielnetoDotCom/YouPHPTube#250]
Installed YouPHPTube on Google Cloud Compute Engine last night and everything worked great accept for streaming. When I try to stream from vMix I get the following error:

FFMPEG.Exited
Streaming
[rtmp @ 058c8aa0] Cannot open connection tcp://35.185.123.228:1935
rtmp://35.185.123.228/live?p=22b949e14675dfb7b9f35540b4fa90f8/5a209014480fb: Unknown error

Report written to "C:\ProgramData\vMix\streaming\streaming 20171130-172928.log"
ffmpeg version 2.8.git Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8.1 (rev2, Built by MinGW-W64 project)
  configuration: --enable-gpl --enable-version3 --enable-libx264 --enable-zlib --enable-libfaac --enable-nonfree --cpu=i686 --enable-nvenc
  libavutil      55.  2.100 / 55.  2.100
  libavcodec     57.  3.100 / 57.  3.100
  libavformat    57.  2.100 / 57.  2.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6.  9.100 /  6.  9.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.100 /  2.  0.100
  libpostproc    54.  0.100 / 54.  0.100
Guessed Channel Layout for  Input Stream #0.1 : stereo
Input #0, dshow, from 'video=vMix Video:audio=vMix Audio':
  Duration: N/A, start: 461657.264000, bitrate: 1536 kb/s
    Stream #0:0: Video: rawvideo (UYVY / 0x59565955), uyvy422, 640x360, 29.97 tbr, 10000k tbn, 29.97 tbc
    Stream #0:1: Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s
[tcp @ 058c8f60] TCP Buffer has been set to 3990528 bytes
[rtmp @ 058c8aa0] Cannot open connection tcp://35.185.123.228:1935
rtmp://35.185.123.228/live?p=22b949e14675dfb7b9f35540b4fa90f8/5a209014480fb: Unknown error

**Comment by deatoninc** [comment]
Also I have tried the same stream on the demo site and it works fine

**Comment by DanielnetoDotCom** [comment]
Looks like you have installed it on windows.
How is your nginx.conf file?

**Comment by deatoninc** [comment]
It is on Ubuntu 16.04

**Comment by DanielnetoDotCom** [comment]
Why do you have this in your log file:?
`Report written to "C:\ProgramData\vMix\streaming\streaming 20171130-172928.log"`

**Comment by deatoninc** [comment]
It is the vmix error log

**Comment by deatoninc** [comment]
Sorry that was just the error from vmix popup. Her is the contents of the vMix log file:

ffmpeg started on 2017-11-30 at 17:29:28
Report written to "C:\ProgramData\vMix\streaming\streaming 20171130-172928.log"
Command line:
"C:\\Program Files (x86)\\vMix\\streaming\\ffmpeg.exe" -report -rtbufsize 256M -f dshow -i "video=vMix Video:audio=vMix Audio" -codec:v libx264 -s:v 640x360 -pix_fmt:v yuv420p -threads 4 -bufsize:v 1500k -g:v 60 -preset:v veryfast -profile:v baseline -level:v 3.1 -b:v 1500k -maxrate:v 1650k -codec:a libfaac -b:a 96k -strict -2 -rtmp_flashver "FMLE/3.0 (compatible; vMix/19.0.0.54)" -f flv "rtmp://35.185.123.228/live?p=22b949e14675dfb7b9f35540b4fa90f8/5a209014480fb"
ffmpeg version 2.8.git Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8.1 (rev2, Built by MinGW-W64 project)
  configuration: --enable-gpl --enable-version3 --enable-libx264 --enable-zlib --enable-libfaac --enable-nonfree --cpu=i686 --enable-nvenc
  libavutil      55.  2.100 / 55.  2.100
  libavcodec     57.  3.100 / 57.  3.100
  libavformat    57.  2.100 / 57.  2.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6.  9.100 /  6.  9.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.100 /  2.  0.100
  libpostproc    54.  0.100 / 54.  0.100
Guessed Channel Layout for  Input Stream #0.1 : stereo
Input #0, dshow, from 'video=vMix Video:audio=vMix Audio':
  Duration: N/A, start: 461657.264000, bitrate: 1536 kb/s
    Stream #0:0: Video: rawvideo (UYVY / 0x59565955), uyvy422, 640x360, 29.97 tbr, 10000k tbn, 29.97 tbc
    Stream #0:1: Audio: pcm_s16le, 48000 Hz, 2 channels, s16, 1536 kb/s
[tcp @ 058c8f60] TCP Buffer has been set to 3990528 bytes
[rtmp @ 058c8aa0] Cannot open connection tcp://35.185.123.228:1935
rtmp://35.185.123.228/live?p=22b949e14675dfb7b9f35540b4fa90f8/5a209014480fb: Unknown error

**Comment by DanielnetoDotCom** [comment]
Sorry man, I do not know what is wrong with that.
If you server is in a public IP you can hire me for 1 hour to take a deep look on it https://www.youphptube.com/services

**Comment by VJPranay** [comment]
I have faced same issue , but it worked for me when I start nginx .  try this command once 

> sudo /usr/local/nginx/sbin/nginx

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by deatoninc** [comment]
I know this just closed, but recently I hired Daniel to install YouPHPTube on the same type of server I used before to see if he could get it going and to possibly see what went wrong when I did it. I believe the issue was just in opening some ports in the firewall. Opened all the necessary ports and all was good.
