### ISSUE TITLE
White screen after succesfull install

### ISSUE THREAD

**Issue by agabird** [DanielnetoDotCom/YouPHPTube#251]
Hello and thanks in advance for your reply...

My issue:
Installation goes ok, finally the screen prompts to delete the installation folder and to press te green button to continue.
After this, nothing happens, just a white screen.

Hereby my youphptube.log:

[01-Dec-2017 14:28:21 America/Chicago] PHP Fatal error: Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/ehealth1/public_html/objects/plugin.php:190
Stack trace:
#0 /home/ehealth1/public_html/plugin/YouPHPTubePlugin.php(116): Plugin::getEnabled('c4fe1b83-8f5a-4...')
#1 /home/ehealth1/public_html/view/include/head.php(5): YouPHPTubePlugin::isEnabled('c4fe1b83-8f5a-4...')
#2 /home/ehealth1/public_html/view/modeYoutube.php(104): include('/home/ehealth1/...')
#3 /home/ehealth1/public_html/view/index.php(22): require('/home/ehealth1/...')
#4 {main}
thrown in /home/ehealth1/public_html/objects/plugin.php on line 190
[01-Dec-2017 14:28:46 America/Chicago] PHP Fatal error: Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/ehealth1/public_html/objects/plugin.php:190
Stack trace:
#0 /home/ehealth1/public_html/plugin/YouPHPTubePlugin.php(116): Plugin::getEnabled('c4fe1b83-8f5a-4...')
#1 /home/ehealth1/public_html/view/include/head.php(5): YouPHPTubePlugin::isEnabled('c4fe1b83-8f5a-4...')
#2 /home/ehealth1/public_html/view/modeYoutube.php(104): include('/home/ehealth1/...')
#3 /home/ehealth1/public_html/view/index.php(22): require('/home/ehealth1/...')
#4 {main}
thrown in /home/ehealth1/public_html/objects/plugin.php on line 190
[01-Dec-2017 14:28:51 America/Chicago] PHP Fatal error: Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/ehealth1/public_html/objects/plugin.php:190
Stack trace:
#0 /home/ehealth1/public_html/plugin/YouPHPTubePlugin.php(116): Plugin::getEnabled('c4fe1b83-8f5a-4...')
#1 /home/ehealth1/public_html/view/include/head.php(5): YouPHPTubePlugin::isEnabled('c4fe1b83-8f5a-4...')
#2 /home/ehealth1/public_html/view/modeYoutube.php(104): include('/home/ehealth1/...')
#3 /home/ehealth1/public_html/view/index.php(22): require('/home/ehealth1/...')
#4 {main}

etc.

**Comment by DanielnetoDotCom** [comment]
It was answered https://github.com/DanielnetoDotCom/YouPHPTube/issues/234#issuecomment-348634996
