### ISSUE TITLE
setup nginx ssl on a different port?

### ISSUE THREAD

**Issue by d0773d** [DanielnetoDotCom/YouPHPTube#252]
youphptube and the encoder are running on Apache2 which is configured for SSL on 443.  I'm attempting to setup the live plugin.  NGINX is setup, but isn't setup for SSL support.  In the Chrome console i receive: "mixed Content: The page at 'https://www.****.tv/plugin/Live/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.****.tv:8080/live/5a2266d60057b/index.m3u8'. This request has been blocked; the content must be served over HTTPS.." Therefor live streaming isn't working at the moment.

I'm assuming NGINX needs to support HTTPS for my current setup to live stream over HTTPS?  Does anyone have an example of how to setup the nginx .conf file to support SSL on a different port other than 443?

**Comment by d0773d** [comment]
I think i may have spoke too soon.  I believe i fixed my ssl issue. My conf file:
`    worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://www.epicgrowers.tv/plugin/Live/on_publish.php;
                            on_play http://www.epicgrowers.tv/plugin/Live/on_play.php;
                            on_record_done http://www.epicgrowers.tv/plugin/Live/on_record_done.php;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name *****.tv;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }   
            }
            server {
            	listen 9443 ssl;
    			listen [::]:9443 ssl;
                server_name ****.tv;
    			include /usr/local/nginx/snippets/self-signed.conf;
                
                #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    } 
                
            }
    }
`

However, live streaming is now sorta working.  The live stream page constantly says offline even though the video can play when the play button is pressed.

**Comment by DanielnetoDotCom** [comment]
Take a look on this and see if it is what are you looking for https://github.com/DanielnetoDotCom/YouPHPTube/issues/210

**Comment by d0773d** [comment]
HI DDC.  I'm using a public ip/domain and server is not private.  I've changed the live plugin to use my ip instead of domain, but I'm still having the same issue. I'm at a loss as to why offline is showing even when I can watch the live stream.

**Comment by DanielnetoDotCom** [comment]
You need to check 2 things...
check if you have to marked listed transmition on livestream panel
check your plugin configuration if you put a port on stats

{"button_title":"LIVE","server":"rtmp://[nigix-server]/live","playerServer":"http://[nigix-server]:8080/live","stats":"http://[nigix-server]:**8080**/stats"}

**Comment by d0773d** [comment]
i have listed transmition as marked and saved the stream so it will stay persistent. and triple checked the live plugin configuration for the correct syntax.  Everything seems to be configured properly, but I am still having the same issue.

**Comment by DanielnetoDotCom** [comment]
what about your stats URL is it working if you paste on the browser? http://[nigix-server]:8080/stats

**Comment by d0773d** [comment]
Hi DDC. I checked if stats is working and yes, it is working both for domain and ip.

**Comment by DanielnetoDotCom** [comment]
Sorry man, I anything wrong with your installation.
If you want you can hire me for 1 hour to take a deep look on it https://www.youphptube.com/services

**Comment by d0773d** [comment]
Hi again.  Well, good news.  I was able to fix this issue by changing the plugin stats url.  I had a eureka moment after reading issue #138 

You'll notice In the Old plugin config I was using https in the stats url and I replaced it with http and port 8080.  Both https and http for the stats page do load in the browse. Maybe, loading the stats as https doesn't work at the moment? Or maybe, my nginx ssl isn't configured correctly? Possible bug?  Either way, it's just stats and I don't think there will be any security issues if I don't use SSL. However, I am a bit OCD when it comes to using SSL, I would prefer to use it whenever possible.  Do you have any input on why SSL doesn't work for the stats page for triggering "Offline/Online"?

Live Plugin perimeters:

Old:
{"button_title":"LIVE","server":"rtmp://www.***.tv/live","playerServer":"https://www.***.tv:9443/live","stats":"https://www.***.tv:9443/stats","disableGifThumbs":false}

New:
{"button_title":"LIVE","server":"rtmp://www.***.tv/live","playerServer":"https://www.***.tv:9443/live","stats":"http://www.***.tv:8080/stats","disableGifThumbs":false}

**Comment by DanielnetoDotCom** [comment]
This is great. I am glad it works!
