### ISSUE TITLE
after reboot SQL error...

### ISSUE THREAD

**Issue by alexevermeulen** [DanielnetoDotCom/YouPHPTube#253]
SELECT * FROM categories WHERE 1=1 ORDER BY name ASC \nError : ()

did i break it ?

**Comment by DanielnetoDotCom** [comment]
no, it is not broken

**Comment by alexevermeulen** [comment]
this is what the opening page shows... can i restore it my self ?

**Comment by DanielnetoDotCom** [comment]
Hi, sorry, but we need more information to try diagnostic the problem.
Drop database and try to reinstall is one thing you can do.
Also try to find errors https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by alexevermeulen** [comment]
solved.. reinstalled.. everything works !

**Comment by DanielnetoDotCom** [comment]
Great !
