### ISSUE TITLE
Gallery not available?

### ISSUE THREAD

**Issue by agabird** [DanielnetoDotCom/YouPHPTube#254]
Hello ,

i noticed the following:

--> First page mode --> No Gallery option available (only Youtube).
Gallery plugin is switched on and page is refreshed.

Any sollution ?

thanks in advance,

**Comment by DanielnetoDotCom** [comment]
Suppose to be available. what is your URL?

**Comment by agabird** [comment]
Hello Daniel ,

It is https://www.ehealthloket.nl

I use the latest version of YouPHPTube.

Thanks.

**Comment by DanielnetoDotCom** [comment]
I can see your gallery working

**Comment by agabird** [comment]
figured it out.

thanks for your reply.

Grt. Aga
