### ISSUE TITLE
possible to speed up encoding by using already encoded files

### ISSUE THREAD

**Issue by alexevermeulen** [DanielnetoDotCom/YouPHPTube#255]
would it be possible to speed up the encoding by using already encoded files ( from a external transcoder like carboncoder or Ffastrans ) and let the YouPHPTube-Encoder just pass and copy the files ?

**Comment by DanielnetoDotCom** [comment]
You can upload the encoded files directly.
To extract the Image and animated gif you will need a plugin.

![image](https://user-images.githubusercontent.com/18009293/33526039-09eaebae-d819-11e7-8554-9466e46f7278.png)

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
