### ISSUE TITLE
Autoplay not working in Safari on MacOSX

### ISSUE THREAD

**Issue by danionescu2007** [DanielnetoDotCom/YouPHPTube#258]
Autoplay not working in Safari on MacOSX. This could be considered a bug, I suppose.

**Comment by DanielnetoDotCom** [comment]
Thanks for your feed back.
I have now way to test it :( if you have any idea how to fix let me know.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
