### ISSUE TITLE
Google Analytics header in source code pings pageviews to author's GA-account

### ISSUE THREAD

**Issue by Yetangitu** [DanielnetoDotCom/YouPHPTube#26]
FYI,

There's a Google Analytics section in the source (in `view/include/head.php`) which points at your own GA account. Others might be less than thrilled to know that what they consider to be 'their own server' sends pageview pings to someone else's GA-account. I'd suggest removing your personal GA-account from the source.

**Comment by DanielnetoDotCom** [comment]
Hi, thanks to use YouPHPTube
Please update your files, there is this new version there is an option to disable it.
Site configuration -> Advanced Configuration -> Disable YouPHPTube Google Analytics
![image](https://cloud.githubusercontent.com/assets/18009293/26697385/27ce614a-46e8-11e7-9c83-0bcd2939bf60.png)

**Comment by Yetangitu** [comment]
OK, thanks
