### ISSUE TITLE
Playlist support?

### ISSUE THREAD

**Issue by d0773d** [DanielnetoDotCom/YouPHPTube#264]
I see playlist code in the code base, but I don't see playlist functionality in the script UI. Did I overlook the playlist functionality or is this feature going to be added in the future release of youphptube?

**Comment by DanielnetoDotCom** [comment]
Now we use this to import a plylist https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Import-a-Full-playlist-from-Youtube

**Comment by d0773d** [comment]
Ah ok. Thanks for the input.
