### ISSUE TITLE
Recommended videos

### ISSUE THREAD

**Issue by FixTechToday** [DanielnetoDotCom/YouPHPTube#265]
How to enable recommended videos, just like the demo?

**Comment by DanielnetoDotCom** [comment]
Hi, what recommended videos?

**Comment by FixTechToday** [comment]
The videos that are showing up in the sidebar. It only works if a user isn't logged in.

**Comment by DanielnetoDotCom** [comment]
It not suppose to. can you reproduce it on demo site?

**Comment by FixTechToday** [comment]
It works fine on the demo site
