### ISSUE TITLE
Hello, i can't see uploaded movies image404.php

### ISSUE THREAD

**Issue by shortymc** [DanielnetoDotCom/YouPHPTube#269]
Hello,
 and thanks for your great work !

The player is loading without result
i see only a image 404.php but the system catch the lenght of the videos.
bug report :  Before install i replace    
 ENGINE=innodb;
by
    ENGINE=innodb ROW_FORMAT=DYNAMIC;;
in videos table
and restart mysql server like this 
service mysql restart --innodb-adaptive-hash-index=ON
before install in a clean database and it works

i can't see the page below for configure ffpeg path etc..
![Uploading d0adfc6a-2dcc-11e7-9f65-94e3461237a8.png…]()
Is it a php file for configure ?

php 5.6
mysql 5.6

Can you help me please ?

best regards shorty

**Comment by DanielnetoDotCom** [comment]
Hi, to have access on all configurations, check your streamer table on encoder database, check if your user is admin, the column isAdmin = 1

about the image404.php to automatic extract an jpg and gif of uploaded files you need a plugin.
but if you use the encoder you will have it automatic

**Comment by shortymc** [comment]
I install the encoder with succes inside a /encoder subfolder. i modify the databse to isadmin=1 inside my database, one of the both was on 0 after i put the rigth url in siteConfigurations but when i update the configuration. So the encoding looks like started with a green bar and and red bar flashing attack below. But the progress bar stay fixed close to the start. ffmpeg mencoder imagick etc.. are installed on this machine.  so i don't know acces to configuaration files. I've installed separtely the encoder master on github. 
Best regards shorty

**Comment by DanielnetoDotCom** [comment]
Hi
Is it not working?
Can you check the encoder log file?

**Comment by shortymc** [comment]
log 
http://www.tradezone.fr/modules/Streaming/encoder/videos/youphptube.log

streamer site
http://www.tradezone.fr/modules/Streaming/

encoder site 
http://www.tradezone.fr/modules/Streaming/encoder/

tell me if you need an ftp/admin or bdd access

**Comment by shortymc** [comment]
For the error
PHP Warning:  mysqli::mysqli(): Headers and client library minor version mismatch.
I've just replaced php5-mysql by php5-mysqlnd and i've got the same result

**Comment by DanielnetoDotCom** [comment]
hi, your problem is: PHP Fatal error:  Call to undefined method mysqli_stmt::get_result() 

try 

`sudo apt-get install php5-mysqlnd`

and then restart your web server:

`sudo /etc/init.d/apache2 restart`

**Comment by shortymc** [comment]
thanks for your help and fast response.
tanks you, i've forgot restart.
the video playing works fine with mp4. But i can't encode. I can acess one time to the full configuration in the encoder but i don't know see it another time the settings.
http://www.tradezone.fr/modules/Streaming/ the movie works fine
but i can't see thumbnail. You tell me something about a plugin, i try to activate all the plugin in config but after it's not work so i disable all, maybe you tell about a specific plugin must be download on you website ? or a server plugin, imagick is actually installed on the machine. 
The encoder at http://www.tradezone.fr/modules/Streaming/ still not work i don't know why, can you help me ?

The only files the server can run is mp4 si hope it will possible to use it with more kind of files
It's exist a way users files are directly encoded if it's not mp4 or a way to redirect users to encoder site ?
is possible to accept movies without admin checking ?
also, i want to bridge users database with another php script for users, how is it's possible ?

Thanks you for your geat support
 Best regards

**Comment by DanielnetoDotCom** [comment]
Hi, I just wrote this, I hope can help you

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Automatic-Thumbs-(JPG-GIF)-on-direct-uploaded-MP4-videos

**Comment by shortymc** [comment]
Hello,
ok i'm very surprised,
is a way to got it free ?
The encoder at http://www.tradezone.fr/modules/Streaming/encoder still not work i don't know why, can you help me ?
 I can acess one time to the full configuration in the encoder but i don't know how see it another time the settings.
 Best regards
shorty

**Comment by DanielnetoDotCom** [comment]
Hi, you miss this PHP Fatal error:  Uncaught Error: Class 'CURLFile'

The class CURLFile is only available in PHP 5 >= 5.5.0

`sudo apt-get install php5-curl`

After that, restart the Apache server:

`sudo /etc/init.d/apache2 restart`

**Comment by shortymc** [comment]
thanks for your help
Yes my php config is ok
i when try to install it, server return.
php5-curl is already installed at the requested version (5.6.30+dfsg-0+deb8u1)
so i don't know what i need to do if it's already installed.
and if the picture thumbnails works with the encoder, it would be perfect.

**Comment by DanielnetoDotCom** [comment]
Some times you have more then 1 php version installed on your server, try to check witch one is apache using.
try to check your phpinfo()

To create a phpinfo file, open a plain text file, add the following lines, and save:
Filename: phpinfo.php

```
<?php

// Show all information, defaults to INFO_ALL
phpinfo();

?>
```

https://mediatemple.net/community/products/dv/204643880/how-can-i-create-a-phpinfo.php-page

**Comment by shortymc** [comment]
If thinks it's the right one.
You can look it there
http://tradezone.fr/modules/Streaming/phpinfo.php

**Comment by DanielnetoDotCom** [comment]
yeah, looks like your CURL is working fine, and it still not encoding?

did you try it again? in your log file shows the last time you tried to encode was on 14-Dec-2017

**Comment by shortymc** [comment]
i've just tried to upload a file.
the green boar going 3 or 4 times to 100% and fter continue to flashing grenn fastly like before. something looks like blocked

**Comment by DanielnetoDotCom** [comment]
flashing the green bar is ok, sometimes is encoding another format, some times is waiting to transfer.
But I can see again the error `PHP Fatal error:  Uncaught Error: Class 'CURLFile' not found`

you need to fix this before proceed

**Comment by shortymc** [comment]
Thanks for helping me :)

i've updated the server and something changed
a green bar stay at 99 percent for some files but the result is the same
some files appears like encoding in a grenn button  in stream site
so, in my php.ini in found about curl  
[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
;curl.cainfo =

maybe it's should be something looks like in this link
https://recalll.co/app/?q=%27Fatal%20error%3A%20Class%20%27CURLFile%27%20not%20found%27%20error%20in%20Facebook%20PHP%20Application%20for%20%27upload%20photo%20to%20user%27s%20timeline%27%20-%20Stack%20Overflow 

normally, what is written in php.ini for youphptube works ?

Best regards
![youphptube](https://user-images.githubusercontent.com/10462908/34075165-a62013e6-e2be-11e7-889d-fcd14409313b.png)

**Comment by DanielnetoDotCom** [comment]
you need php 5.6+ actually php 7 is recommended

but I just check your log and still the same fatal error regarding curl

**Comment by shortymc** [comment]
but the php version is good
PHP Version 5.6.30-0+deb8u1 
linux said : 

in php.ini
[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
;curl.cainfo =

and 
php5-curl is already installed at the requested version (5.6.30+dfsg-0+deb8u1)
-----------------------------------------
there is something to modify in php.ini for it works with youphptube ?

php7 is also installed on the machine but youphptube looks like prefer 5.6

![curl](https://user-images.githubusercontent.com/10462908/34081182-eb9735ae-e349-11e7-8e47-b3fe97d3b4af.png)

**Comment by shortymc** [comment]
ok, it's works for an avi file after doing : 
aptitude install php-curl
service apache2 restart

File converted successfully an diseapear from queue after succes encode
and the thumbnail is appear 👍 

But for an mp4 simple upload, image is not showing but it's running on the same machine.
Simple m4 upload can work with local encoder ? it was the case in version 4.1 ?

 Actually the biggest is 2 permissions problem. 
1 - Users can't upload files. I don't know how/Where set permissions for users can upload movies and they don't see upload buttons and my videos menu 

2- Not able to access encoder settings

- also the page display is very slow.

Thanks you for  your support
 Best regards

**Comment by DanielnetoDotCom** [comment]
Hi

I fit works with an AVI, it should work with other extensions as well, try to check your log file

1- check your users manager, you will find an option to allow users to upload videos

2- As I answer before on this thread

> to have access on all configurations, check your streamer table on encoder database, check if your user is admin, the column isAdmin = 1

Or try this https://github.com/DanielnetoDotCom/YouPHPTube/issues/238

**Comment by shortymc** [comment]
Thanks for your response

1 - it's ok i found the option is working fine
2 - ok, i modify the column in database and it's works. It' was a forgotten slash in first configuration.

- The movies don't play continue loop loading :
http://www.tradezone.fr/modules/Streaming/video/toy-plane-liftoff
http://www.tradezone.fr/modules/Streaming/video/mars-20030905
http://www.tradezone.fr/modules/Streaming/video/bird123
http://www.tradezone.fr/modules/Streaming/video/rassegna212
http://www.tradezone.fr/modules/Streaming/video/mvi-3572

and it's written "the media could not be loaded because the server or network failed"
on some movies when adblock is activated.

 I got a dsl connection and the server is in a datacenter, so i don't understand why it's so slow.
Movies can't start and continue loading
 Best regards

**Comment by DanielnetoDotCom** [comment]
your videos works fine from here

**Comment by shortymc** [comment]
Thanks for your great support 👍 

What i see at home :
some movies looks heavy and need to be paused de work correcty.
http://www.tradezone.fr/modules/Streaming/video/fete-musique-shana-final1
for convert this video i choose only low quality settings for convert
this an high compressed movie source is 16 mo only for 2 minutes
is it a way for compress stronger or streaming faster ?
.mod .mpg and .3gp files can work ?
i cant see this movie, can you see it ?
http://www.tradezone.fr/modules/Streaming/video/toy-plane-liftoff
source media info:
Format                      : AVI
Format/Info                 : Audio Video Interleave
Format settings             : rec
File size                   : 2.26 MiB
Duration                    : 4 s 0 ms
Overall bit rate            : 4 746 kb/s

Video
ID                          : 0
Format                      : JPEG
Codec ID                    : MJPG
Duration                    : 4 s 0 ms
Bit rate                    : 4 732 kb/s
Width                       : 640 pixels
Height                      : 480 pixels
Display aspect ratio        : 4:3
Frame rate                  : 25.000 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:2
Bit depth                   : 8 bits
Scan type                   : Progressive
Compression mode            : Lossy
Bits/(Pixel*Frame)          : 0.616
Stream size                 : 2.26 MiB (100%)

**Comment by DanielnetoDotCom** [comment]
Hi

This video:
http://www.tradezone.fr/modules/Streaming/video/fete-musique-shana-final1

works fine for me, if it is not loading proper for you, please check your Internet connection

About this: http://www.tradezone.fr/modules/Streaming/video/toy-plane-liftoff

it is not working for me also

**Comment by shortymc** [comment]
Hi :)

 Okay, i made more test and it's working fine on local computer based on linux os (debian stretch).

- why not on Windows xp ? one some computers movies don't start and continue loading.
 When i try to start demo page on demo.youphptube.com i got the message : "no compatible source was found for this media" on windows. The  test from yesterday was on windows 10 machine and it was very slow. I'm installing a new windows 7 system for make more test.
 
- Also logo picture is cutted in http://www.tradezone.fr/modules/Streaming/ , i try different width en height but same results, i need to made an image with a bigger bordure for put inside or it's exist a way to make it enter ? i try everything to adjust with admin button but it's always cutted. I try to replace the file with ftp but permission denied. I don't know how i can do...

 Best regards

**Comment by DanielnetoDotCom** [comment]
> why not on Windows xp

try to encode on webm format, I guess it is because the old browsers

> Also logo picture

About file permitions you can fix this with your root user

**Comment by shortymc** [comment]
I more test with an higer connection and os and it's work better
for windows xp ok i will try to encode webm with the option for chrome browser (i thinks its what you wanna say) or here is priority numbers, is it for select a encoding type or for the ressource consume of the server. Also in settings don't know where add new extension types. I don't find it in encoder settings page
 for : About file permitions you can fix this with your root user
The user i use got all ftp permissions on this folder !
i will try to put it in root ssh. but i think your script will replace it

**Comment by DanielnetoDotCom** [comment]
What file extension do you need for encoder?

**Comment by shortymc** [comment]
Hi
 I need .3gp .mpg .mod file extensions
for import from phones and cameras
best regards

**Comment by DanielnetoDotCom** [comment]
in your encoder/videos/configuration.php file, you will find this:

$global['allowed'] = array('mp4', 'avi', 'mov', 'mkv', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv');

Add the extensions you need to be allowed and you should be all set 

should be like this:

$global['allowed'] = array('mp4', 'avi', 'mov', 'mkv', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv', '.3gp',  '.mpg', '.mod');

**Comment by shortymc** [comment]
i tried to modify the file but it's not working, 
but files extensions appears well after the phrase below,
so the settings are understood in the file
File extension error (sample.mpg), we allow only...
$global['allowed'] = array('mp4', 'avi', 'mov', 'mkv', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv', '.3gp', '.mpg', '.mod', '.MOD');
/**
 * Do NOT change from here
 */
...

**Comment by DanielnetoDotCom** [comment]
remove the . (dot)

make like this `$global['allowed'] = array('mp4', 'avi', 'mov', 'mkv', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv', '3gp', 'mpg', 'mod');`

**Comment by shortymc** [comment]
yes it's works 🥇 
so i just need to find a solution for the logo.
i think made another with a big border

**Comment by DanielnetoDotCom** [comment]
Great

**Comment by shortymc** [comment]
Also i see captcha code in users.php file.
 How activate it for prevents bot ?
and also i got problems for install apt-get install python-pip
all attempt go to a broken tree 
it's on other way for install youtube-dl because this package looks like outdated
 For the fullscreen on mobile phone i don't know, and for the logo i actually made a brand new one hope it will be good

**Comment by DanielnetoDotCom** [comment]
I will try to make a confirmation email for new users to prevent bots, the captcha may be included too 

youtube-de is very active, try to post your difficulties regarding youtube-dl here https://github.com/rg3/youtube-dl

**Comment by shortymc** [comment]
:) yes it will be great for bots !
okay i will try to install it without pip
best regards

**Comment by shortymc** [comment]
YouTube DL was updated and works fine now. :)
But after a server reboot videos don't wan't to play.
i really don't know why.
i see nothing anormal in logfiles
Can you help me ?
http://tradezone.fr/modules/Streaming/
Best regards

**Comment by DanielnetoDotCom** [comment]
Hi

here is working fine

**Comment by shortymc** [comment]
Hi :)
 Yes you are right. 👍 
i already made this mistake : I was trying with the wrong computer and finally it's working in webm format. finally i made another clean install and it's working good also.
 bugs encouter : 
i can't put fullscreen on w10 / but full screen works fine with windows xp computers.

i try to bridge database users with my cms.
 i'm looking for the way to create php session for users be connected on both scripts.
users are imported from another database and the login is working
 how i can made a new users session ?
what code i need to insert in the other website for users be connected on both site without re-enter a password. I can made full french translate of youphptube if you are interested.

Also 🥇  you win this another medal for the working social connect login.

 Thanks for your help and for all you already do for internet.
Best regards

**Comment by shortymc** [comment]
okay the fullscreen mode is working now, after reboot 👍 
i don't know why its wasn't working yesterday
can u help me for script something like :`<?php  if { $user is registered on sometables
 create new youphptube user session for $user }
if { $phptube user session active 
create new user session on $mycms 
php ?>`

 Thanks for your supports
Best regards

**Comment by DanielnetoDotCom** [comment]
@shortymc I don t understand your script

**Comment by shortymc** [comment]
want users from another cms stay connected when they go to youphptube portal
i don't what code it's need for declare php tube user is connected and create a session from another cms. like hybrid-auth do, but without reconnect because both cms are on the same server.

 this code was made by family is out to date, i modify it for made an exemple, maybe its explain better what i want to do.
`<?php
$page = htmlspecialchars($_GET['page']);

setcookie('yphptConnect', false, time() - 3600);
unset($_COOKIE['yphptConnect']);

require_once('youphptubeauthfiles.php');

$yphptConnect = sql_query("SELECT * FROM ${user_prefix}_users WHERE user_lastmod!='logout' AND user_lastip='".$_SERVER["REMOTE_ADDR"]."'");
$userConnected = sql_num_rows($yphptConnect);

if ($userConnected == 1) {
	while ($datayphptConnect = sql_fetch_array($yphptConnect)) {
		mxSetUserSession($datayphptConnect['uid'], $datayphptConnect['uname'], $datayphptConnect['pass'], $datayphptConnect['storynum'], $datayphptConnect['umode'], $datayphptConnect['uorder'], $datayphptConnect['thold'], $datayphptConnect['noscore'], $datayphptConnect['ublockon'], $datayphptConnect['theme'], $datayphptConnect['commentmax']);
		mxSessionDelVar("formvalues");
		mxSessionDelVar("ucountbadlogin");
		mxSessionDelVar("newusercheck");
	}
}
else {
	setcookie('yphptConnect', '0', (time() + 30));
}

header("Location: ".$page."");`


 Thanks for you help :)
best regards

**Comment by DanielnetoDotCom** [comment]
Take a look on this file https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/objects/login.json.php#L102, 
you can post user and pass variable (Line 102)

it is the URL http://yourYPTsite.com/login

**Comment by shortymc** [comment]
Hello, thanks for your great work, i will pay all your new version and features in few times.
I'm continuing for beta test youphptube working well but after mysql attack-update-reboot system can't connect database.
What file configure it ? 
install/checkConfiguration.php says :  

error | "Connect Error (1045) Access denied for user ''@'localhost' (using password: NO)"

Please help me !
Thanks you for your great project !

**Comment by DanielnetoDotCom** [comment]
So it may be a mysql server issue

Try to connect manually in your MySQL , when you are sure your MySQL is working you can try AVideo

**Comment by shortymc** [comment]
yes but what file i need to modify ?

**Comment by DanielnetoDotCom** [comment]
The database credentials are in the videos/configuration.php file
