### ISSUE TITLE
Video encoding seems to have stopped working.

### ISSUE THREAD

**Issue by glumpje** [DanielnetoDotCom/YouPHPTube#27]
Tried to add some new video's, they apear in the video manager but do not get encoded anymore. Also no text files are being created for those video's in the videos directory.

**Comment by DanielnetoDotCom** [comment]
What is the link of your web site.
Please check videos/youphptube.log file and apache2/error.log file

**Comment by glumpje** [comment]
I run the site local on my laptop so http://localhost/YouPHPTube/mvideos

Apache2 error log does not contain any entries

Only 1 line per failed video in the youphptube.log:
[03-Jun-2017 15:16:44 Europe/Berlin] Duration founded: 0:01:30

**Comment by glumpje** [comment]
After a fresh git pull in another directory it's working again.. wondering what went wrong.

**Comment by DanielnetoDotCom** [comment]
Nice it is working now
