### ISSUE TITLE
Categories and Status does not works

### ISSUE THREAD

**Issue by flochman** [DanielnetoDotCom/YouPHPTube#272]
Hi,

it seems that in Video manager when I choose categories or status: active/inactive menu, allways is displayed window "Sorry!".

I have installed predefinedcategories plugin.

What is this?

Thanks.

**Comment by DanielnetoDotCom** [comment]
check error log please

**Comment by flochman** [comment]
There is no error regarding this. 

Only new error is this, but it seems it is not regard this behavior:

[13-Dec-2017 19:08:35 Europe/Berlin] Files Received for video 13: Céline Dion - You And I
[13-Dec-2017 20:09:44 Europe/Berlin] PHP Notice:  Undefined index: id in /var/www/html/ph/objects/youtubeUpload.json.php on line 39
[13-Dec-2017 20:09:44 Europe/Berlin] PHP Notice:  Undefined index: id in /var/www/html/ph/objects/youtubeUpload.json.php on line 40

**Comment by DanielnetoDotCom** [comment]
Are you sure you are checking the checkbox of a video before click on the status button?

**Comment by flochman** [comment]
Ok. Now I udersand how status works. It is OK now.

But what categories?

I have a lot of videos in default category but when click on that category "Sorry!" is displayed. Also with others categories. I am logged as admin.

**Comment by DanielnetoDotCom** [comment]
you also need to check the videos before click

**Comment by flochman** [comment]
Ach now I uderstand. This manager is for changing the parameters. I though that when I select category it will show and filter videos only in this cathegory.

OK. now it is clear.

Oh. It is not too intiutive this layout. User expect something diffrent.

But. Ok. Now uderstand.

Thanks.

**Comment by DanielnetoDotCom** [comment]
you welcome
