### ISSUE TITLE
Video Manager layout and design

### ISSUE THREAD

**Issue by flochman** [DanielnetoDotCom/YouPHPTube#273]
Hi again,

I would like only suggest that video manager layout and design is very confusing with change categories and status in menu for listed videos.

I would like recomend the design like phpmyadmin where should be such actions for change categories and status  for listed videos are in botton or top of the list of the videos and use dropdown menu there like is in phpmyadmin when workong with tables. This way is standard user interface and no confusing.

Thanks.

**Comment by DanielnetoDotCom** [comment]
Thanks for your suggestion, we will analyze and evaluate the feasibility of this implementation
