### ISSUE TITLE
virus {HEX}php.shell.black-id.616.UNOFFICIAL FOUND

### ISSUE THREAD

**Issue by abamilod** [DanielnetoDotCom/YouPHPTube#274]
Hello all, 
I cannot get the plugins stay at my host server due to virus removal. Maybe this is caused by the php encryption or something. Anyone else got this problem and how to solve this?

**Comment by abamilod** [comment]
It seems that encryption in plugin file was identified as virus by antivirus. I hv tried to ask the web hosting admin but no answer. Php dev wants to secure the sourcecode and web admin wants to secure file hosted. Maybe I need to ask the antivirus dev to redefine virus signature?

**Comment by abamilod** [comment]
the antivirus that scan php file encrypted as a virus is called Linux Malware Detect (maldet). I will try to request them to re-consider this issue.

**Comment by DanielnetoDotCom** [comment]
Thanks, I guess this antivirus will accuse any php encrypted code as a virus.
do you have any idea how to be able to encrypt and it is not regonized as a virus?

**Comment by DanielnetoDotCom** [comment]
I have open an isssue there https://github.com/rfxn/linux-malware-detect/issues/263
if you guys can help us to encourages them to solve this

**Comment by abamilod** [comment]
I guess this in my own problem with my hosting server.
