### ISSUE TITLE
Video Cover Image Not Showing Up in Facebook

### ISSUE THREAD

**Issue by angelawong** [DanielnetoDotCom/YouPHPTube#277]
When I try to embed my YouPHPTube video in Facebook, an oversized image of my YouPhpTube logo shows up instead of the video cover image. Please advise. Thank you.

**Comment by DanielnetoDotCom** [comment]
Hi, what link specific did you try to share?

are u using some first page plugin such as YouPHPFlix or Gallery?

we use the official facebook debugger to test the links and with the demo site is all working fine

https://developers.facebook.com/tools/debug/sharing/

**Comment by angelawong** [comment]
Thanks so much Daniel. I went to the debug link you gave me and the error indicated that there was something wrong with the image URL. There were some weird numbers that were tagged on to the jpeg image. Don't know how it got there but after scraping the link a few times, it magically worked. Thanks so much!!!

**Comment by DanielnetoDotCom** [comment]
Great
