### ISSUE TITLE
I was setting again the first. but I couldnot completion...

### ISSUE THREAD

**Issue by okazgumi** [DanielnetoDotCom/YouPHPTube#28]
![sorry](https://cloud.githubusercontent.com/assets/29045007/26757438/1d5840b8-48f6-11e7-86d2-a691e7f65b65.png)
http://www.grassland.space/install/index.php

**Comment by okazgumi** [comment]
when I check error_log, the errorrog tells me php-error.

**Comment by DanielnetoDotCom** [comment]
check **/var/logs/apache2/error.log** and **/var/www/YouPHPTube/videos/youphptube.log**
Paste here the results
`tail /var/logs/apache2/error.log`

`tail /var/www/YouPHPTube/videos/youphptube.log`

**Comment by okazgumi** [comment]
This server doesn't have "logs" directory...

**Comment by okazgumi** [comment]
[04-Jun-2017 12:40:18 Asia/Tokyo] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/install/checkConfiguration.php:16
Stack trace:
#0 {main}
  thrown in /var/www/html/install/checkConfiguration.php on line 16

**Comment by DanielnetoDotCom** [comment]
Did you follow this tutorial?
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x
you probably need to install php-mysql

**Comment by okazgumi** [comment]
Thanks!
Why does the user jump to the user page when the user clicks the upload or import link?

**Comment by DanielnetoDotCom** [comment]
Bucause you need to be logged as admin to upload, or give permition to regular users to upload too
