### ISSUE TITLE
Help page request

### ISSUE THREAD

**Issue by flochman** [DanielnetoDotCom/YouPHPTube#281]
Hi,

I would like to request the help page implementation like you already have the About page. Only duplicate code is needed to have help page for explaining help how to use YouPHPTube for the users.

Thanks.

**Comment by DanielnetoDotCom** [comment]
Hi, is under development an Menu plugin, it will support create new pages

**Comment by flochman** [comment]
Thanks. I will wait to that and hope it will be soon.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
