### ISSUE TITLE
Remove MP4 Upload button

### ISSUE THREAD

**Issue by Sugiramireille** [DanielnetoDotCom/YouPHPTube#282]
Hello,

How can I remove MP4 upload button? I strictly need to use the encoder.
Thanks,

**Comment by DanielnetoDotCom** [comment]
In the future I will add this option somewhere on the app

**Comment by DanielnetoDotCom** [comment]
Hi I just create a plugin that can handle some advanced configurations, like remove MP4 Upload button

Just update your files and take a look on this
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Advanced-Customization-Plugin
