### ISSUE TITLE
How to enable Mod_rewrite in my centOs dedicated server

### ISSUE THREAD

**Issue by subhamraj** [DanielnetoDotCom/YouPHPTube#283]
http://68.65.120.35/install/index.php

This is my website issue, I can't enable mod_rewrite in my centOs dedicated server, Please help me out, The customer support says that mod_rewrite is already enabled in their server, But this framework is not detecting them, Any kind of support would be really helpful,
Please help me out , My Email ID is iec2015076@iiita.ac.in

**Comment by DanielnetoDotCom** [comment]
Looks like you could install it correct?

**Comment by subhamraj** [comment]
Yes. Daniel I have removed the mod_rewrite check function in the install/index.php page and then it worked. I think you should recheck the Mod_rewrite check function for different browsers

**Comment by DanielnetoDotCom** [comment]
ok, thanks
