### ISSUE TITLE
SQL install error

### ISSUE THREAD

**Issue by elitemerctech** [DanielnetoDotCom/YouPHPTube#284]
I tried installing with the normal install method but when I loaded the page on a different pc the site came up basically blank with no images so I tried installing the hard way now when I try to install the database in MariaDB-10.1 & phpmyadmin it gives me this error. 
CREATE TABLE IF NOT EXISTS `videos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `clean_title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `views_count` INT NOT NULL DEFAULT 0,
  `status` ENUM('a', 'i', 'e', 'x', 'd', 'xmp4', 'xwebm', 'xmp3', 'xogg', 'ximg') NOT NULL DEFAULT 'e' COMMENT 'a = active\ni = inactive\ne = encoding\nx = encoding error\nd = downloading\nxmp4 = encoding mp4 error \nxwebm = encoding webm error \nxmp3 = encoding mp3 error \nxogg = encoding ogg error \nximg = get image error',
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  `users_id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  `filename` VARCHAR(255) NOT NULL,
  `duration` VARCHAR(15) NOT NULL,
  `type` ENUM('audio', 'video', 'embed') NOT NULL DEFAULT 'video',
  `videoDownloadedLink` VARCHAR(255) NULL,
  `order` INT UNSIGNED NOT NULL DEFAULT 1,
  `rotation` SMALLINT NULL DEFAULT 0,
  `zoom` FLOAT NULL DEFAULT 1,
  `youtubeId` VARCHAR(45) [...]

MySQL said: Documentation
#1071 - Specified key was too long; max key length is 767 bytes

There are no errors in the apache2 logs that I can see..

**Comment by DanielnetoDotCom** [comment]
try to update your mysql version 

767 bytes is the stated prefix limitation for InnoDB tables in MySQL version 5.6 (and prior versions). It's 1,000 bytes long for MyISAM tables. In MySQL version 5.7 and upwards this limit has been increased to 3072 bytes.

**Comment by elitemerctech** [comment]
I tried updating MariaDB but I have the latest version. Any suggestions?

**Comment by DanielnetoDotCom** [comment]
Try google 

> Specified key was too long; max key length is 767 bytes

http://bfy.tw/FjG8

**Comment by DanielnetoDotCom** [comment]
Check this:
https://github.com/DanielnetoDotCom/YouPHPTube/issues/171
https://github.com/DanielnetoDotCom/YouPHPTube/issues/85

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
