### ISSUE TITLE
YouPHPTube => IIS 10 & MS SQL SERVER 2017

### ISSUE THREAD

**Issue by kostia7alania** [DanielnetoDotCom/YouPHPTube#285]
is it real?
I have frontend side on IIS + ms sql . How can i migrate from apache and mysql?

**Comment by DanielnetoDotCom** [comment]
I dont know this, we do not support windows

**Comment by gamersalpha** [comment]
using windows seriously ...

**Comment by kostia7alania** [comment]
can i put encoder in linux virtual machine, but in frontend use MS SQL AND ISS? Is it difficult to remake this mysql queries to mssql? and instead apache->mod_rewrite module use iis->mod_rewrite ?

**Comment by DanielnetoDotCom** [comment]
@kostia7alania 
I am not sure how hard is to change requirements, but will be easier if you use your virtual machine to host the streamer and the encoder

**Comment by kostia7alania** [comment]
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Upload Video</title>
        <link href="css/bootstrap.css" rel="stylesheet" type="text/css" media="screen">
		<?php require ('dbconn.php');?>
	</head>
		<script src="js/jquery.js" type="text/javascript"></script>
		<script src="js/bootstrap.js" type="text/javascript"></script>

<body>

    <div class="row-fluid">
        <div class="span12">
            <div class="container">
		<br>
		<br>
				<form method="post" enctype="multipart/form-data" >
					<?php
						if(isset($_FILES['file'])){
								$name = $_FILES['file']['name'];
								$extension = explode('.', $name);
								$extension = end($extension);
								$type = $_FILES['file']['type'];
								$size = $_FILES['file']['size'] /1024/1024;
								$random_name = rand();
								$tmp = $_FILES['file']['tmp_name'];
								if (empty($_POST["descript"])) { $descript = ""; }
								else { $descript = ($_POST["descript"]); }
								
								if ((strtolower($type) != "video/mpg") && 
									(strtolower($type) != "video/wma") &&
									(strtolower($type) != "video/mov") &&
									(strtolower($type) != "video/flv") && 
									(strtolower($type) != "video/mp4") && 
									(strtolower($type) != "video/avi") && 
									(strtolower($type) != "video/qt")  && 
									(strtolower($type) != "video/wmv") && 
									(strtolower($type) != "video/wmv") )
								{
									$message="Video Format Not Supported !";
								} else {
									$message="Video uploaded successively !";
									move_uploaded_file($tmp, './upload/'.$random_name.'.'.$extension);	
									//$conn->query("INSERT INTO [dbo].[videos] VALUES('$name','$random_name.$extension','descript!')");
								
								$SQL2 = "INSERT INTO [dbo].[videos] VALUES('$name','$random_name.$extension','$descript')";
								$RES2 = @odbc_exec( $DB, $SQL2 ); 
								
								?>
								<?php
								echo "<script type='text/javascript'>alert('$descript\\n\\n$message\\n\\nUpload: $name\\nSize: $size\\nType: $type\\nStored in: uploads/$name');</script>";
								?>
								
								<?php
							}
						}
					
					?>
	
					<h4> Select a Video : </h4>
					<input name="UPLOAD_MAX_FILESIZE" value="104857600"  type="hidden"/>
					<input type="file" name="file" 	  id="file" />
					<span>&nbsp;&nbsp;&nbsp;&nbsp;</span>
					<input placeholder="Type your description" type="text" name='descript' id='descript' />
					<button  type="submit"  class="btn">button_SEND</button>
					<input type="submit" value="input_send" />
					
				</form>
			
			<hr>
			
	       
				<h4>List of Videos:</h4>
		  
					<ul>
							<?php
								//$query = $conn->query("SELECT * FROM videos");
								$SQL = "SELECT * FROM [dbo].[videos]";
								$RES = @odbc_exec( $DB, $SQL );
								//while($row = $RES->fetch()){
								while($row = odbc_fetch_array($RES)){
								$video_id = $row['video_id'];
							?>
							
								Click to Watch ---> 
									<a style="color:orange" href="#Video_Modal<?php echo $video_id; ?>" data-toggle="modal">
										<?php
											echo $row['title'];
										?>
									</a> 
								<br />
								
							<?php include ('video_modal.php'); ?>
							<?php
							} 
							?>
					</ul>
          
        </div>
        </div>
        </div>  
		
</body>
</html>

**Comment by nightstryke** [comment]
Your problem is you're trying to use IIS and MS SQL in Windows to acheive something YouPHPTube is not designed to do which is "Run on Windows."

At the moment YouPHPTube is designed to run on Linux "Using Apache and MySQL."

Now if you could get MAMP or WAMP installed on Windows and somehow get FFMPEG to work with a MAMP or WAMP installation of YouPHPTube then it would run/function on Windows. But it won't right out of the box if you're trying to use IIS and MS SQL.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by veljkostanar** [comment]
I know this thread is old but I have a slightly different scenario would youphptube work on a ubuntu server running Microsoft Server 2017?

**Comment by nightstryke** [comment]
> I know this thread is old but I have a slightly different scenario would youphptube work on a ubuntu server running Microsoft Server 2017?

You could possibly run Ubuntu 16.04 or 18.04 in VirtualBox, but you would have to have a very high spec server to get it to work. You would also need the VM to be accessible to the Internet otherwise there'd be no point.

**Comment by veljkostanar** [comment]
would a Vbox be needed? MS server 2017 is compatible with ubuntu, I'm questioning more if youphp is compatible with MS server 2017

**Comment by nightstryke** [comment]
> ooops my bad what i ment to say was will youphptube work with "MS SQL Server 2017" and ubuntu together

You have to run Ubuntu in a Virtual Machine if you want to run YouPHPTube in windows, MYSQL is a requirement. MS SQL is not compatible.
