### ISSUE TITLE
 I'm on this problem, I need help.

### ISSUE THREAD

**Issue by LucasCM45** [DanielnetoDotCom/YouPHPTube#286]
Error deleting user: Cannot delete or update a parent row: a foreign key constraint fails (youPHPTube.configurations, CONSTRAINT fk_configurations_users1 FOREIGN KEY (users_id) REFERENCES users (id) ON DELETE NO ACTION ON UPDATE NO ACTION)"

![27969047-0ae8bc7a-6352-11e7-9351-6ff66cc47327](https://user-images.githubusercontent.com/34850035/34347006-01bf2444-e9e5-11e7-9e37-3bdab6d738d3.png)

**Comment by DanielnetoDotCom** [comment]
I am not sure how this happened.

Try to drop the database and try again

**Comment by mikweb2017** [comment]
your DB user  dont have permission

**Comment by LucasCM45** [comment]
I REFARE ANOTHER DATABASE AND NOW THIS ERROR HAS APPEARED!
MYSQL IS IN VERSION 5.7

Sorry!
Error performing query '<strong> 

CREATE TABLE IF NOT EXISTS `videos` ( 
`id` INT NOT NULL AUTO_INCREMENT, 
`title` VARCHAR(255) NOT NULL, 
`clean_title` VARCHAR(255) NOT NULL, 
`description` TEXT NULL, 
`views_count` INT NOT NULL DEFAULT 0, 
`status` ENUM('a', 'i', 'e', 'x', 'd', 'xmp4', 'xwebm', 'xmp3', 'xogg', 'ximg') NOT NULL DEFAULT 'e' COMMENT 'a = active\ni = inactive\ne = encoding\nx = encoding error\nd = downloading\nxmp4 = encoding mp4 error \nxwebm = encoding webm error \nxmp3 = encoding mp3 error \nxogg = encoding ogg error \nximg = get image error', 
`created` DATETIME NOT NULL, 
`modified` DATETIME NOT NULL, 
`users_id` INT NOT NULL, 
`categories_id` INT NOT NULL, 
`filename` VARCHAR(255) NOT NULL, 
`duration` VARCHAR(15) NOT NULL, 
`type` ENUM('audio', 'video', 'embed') NOT NULL DEFAULT 'video', 
`videoDownloadedLink` VARCHAR(255) NULL,
`order` INT UNSIGNED NOT NULL DEFAULT 1, 
`rotation` SMALLINT NULL DEFAULT 0, 
`zoom` FLOAT NULL DEFAULT 1, 
`youtubeId` VARCHAR(45) NULL, 
`videoLink` VARCHAR(255) NULL, 
`next_videos_id` INT NULL, 
PRIMARY KEY (`id`), 
INDEX `fk_videos_users_idx` (`users_id` ASC),
INDEX `fk_videos_categories1_idx` (`categories_id` ASC), 
UNIQUE INDEX `clean_title_UNIQUE` (`clean_title` ASC), 
INDEX `index5` (`order` ASC), 
INDEX `fk_videos_videos1_idx` (`next_videos_id` ASC), 
CONSTRAINT `fk_videos_users` 
FOREIGN KEY (`users_id`) 
REFERENCES `users` (`id`) 
ON DELETE NO ACTION 
ON UPDATE NO ACTION, 
CONSTRAINT `fk_videos_categories1` 
FOREIGN KEY (`categories_id`) 
REFERENCES `categories` (`id`) 
ON DELETE NO ACTION 
ON UPDATE NO ACTION, 
CONSTRAINT `fk_videos_videos1` 
FOREIGN KEY (`next_videos_id`) 
REFERENCES `videos` (`id`) 
ON DELETE NO ACTION 
ON UPDATE NO ACTION) 
ENGINE = InnoDB; 
': Specified key was too long; max key length is 767 bytes<br /><br />

**Comment by DanielnetoDotCom** [comment]
Check this:
https://github.com/DanielnetoDotCom/YouPHPTube/issues/171
https://github.com/DanielnetoDotCom/YouPHPTube/issues/85
https://github.com/DanielnetoDotCom/YouPHPTube/issues/284

**Comment by LucasCM45** [comment]
thank you! I got it resolved

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
