### ISSUE TITLE
Search Function Not Working

### ISSUE THREAD

**Issue by vjaytv** [DanielnetoDotCom/YouPHPTube#287]
heh Daniel
you had suggested to enter what I was searching for and then hit Enter
this just refreshes the site and reloads the first video

http://vjaytv.easytube.club/

**Comment by Matthuffy** [comment]
does this on the demo site too.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by Matthuffy** [comment]
Inactivity on your part hahaha, just close things that you do not want to address :) great customer support. Think will simply make my own as then will be bug free... (yes I can easily)
