### ISSUE TITLE
Streaming Error

### ISSUE THREAD

**Issue by DemonRem** [DanielnetoDotCom/YouPHPTube#288]
I managed to start the streaming but there is an error on the player

The media could not be loaded, either because the server or network failed or because the format is not supported.

**Comment by mikweb2017** [comment]
check
https://github.com/DanielnetoDotCom/YouPHPTube/issues/138

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
