### ISSUE TITLE
No preview when upluoad video ?

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/YouPHPTube#289]
hello, 
i m on afrech install, but no preview when i upluad a video : 

![image](https://user-images.githubusercontent.com/32466950/34421481-d0c7d304-ec0f-11e7-8cd6-35df84a7dc3c.png)
what do u think please ?

i  m using the last realesed

**Comment by DanielnetoDotCom** [comment]
to automatic extract an jpg and gif of uploaded files you need a plugin.
but if you use the encoder you will have it automatic

check this: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Automatic-Thumbs-(JPG-GIF)-on-direct-uploaded-MP4-videos

**Comment by gamersalpha** [comment]
is a paid plugin

**Comment by DanielnetoDotCom** [comment]
The encoder extract is free to upload MP4 you need to pay

**Comment by gamersalpha** [comment]
on this page is all things i need 

https://easytube.club/#plugins

but not free ...

**Comment by DanielnetoDotCom** [comment]
there are some free plugins, but the one you are looking for is MP4ThumbsAndGif

**Comment by gamersalpha** [comment]
need all of this : 

YouPHPTube Plugin: VideoThumbnails 
YouPHPTube Plugin: FloatVideo 
YouPHPTube Plugin: LiveUsers 
YouPHPTube Plugin: PredefinedCategory 
and this one : YouPHPTube Plugin: SecureVideosDirectory

**Comment by DanielnetoDotCom** [comment]
check this to learn how to install https://tutorials.youphptube.com/video/donwloading-and-installing-a-plugin

**Comment by loso20p** [comment]
my MP4ThumbsAndGif doesnt grab any images it says 0kb when i check

**Comment by DanielnetoDotCom** [comment]
please check the encoder and streamer error log

**Comment by loso20p** [comment]
ok i did i foun this in the streamer log ): failed to open stream: HTTP request failed!  in /home/xxxxxx/public_html/plugin/MP4ThumbsAndGif/MP4ThumbsAndGif.php(14) : eval()'d code(1) : eval()'d code on line 33

**Comment by DanielnetoDotCom** [comment]
I need more details

**Comment by loso20p** [comment]
24-Feb-2018 00:01:56 UTC] Create Gif Pallet: ffmpeg -y  -ss 00:54:51 -t 3 -i http://xxxxxx.com/videos/AnnabelleCreation20171080pBluRayx264YTSAG_5a908831220908.87834584.mp4 -vf fps=10,scale=320:-1:flags=lanczos,palettegen /tmp/c2c7a9ee05546c627a426d7c25d95b2apalette.png
[24-Feb-2018 00:01:56 UTC] Create Gif with Pallet: ffmpeg -y  -ss 00:54:51 -t 3 -i http://xxxxx.com/videos/AnnabelleCreation20171080pBluRayx264YTSAG_5a908831220908.87834584.mp4 -vf fps=10,scale=320:-1:flags=lanczos,palettegen /tmp/c2c7a9ee05546c627a426d7c25d95b2apalette.png
[24-Feb-2018 00:01:56 UTC] /home/xxxxx/public_html/rtsencode/objects/getImageMP4.php 68Execution time : 1.9330139160156 seconds

**Comment by DanielnetoDotCom** [comment]
how is your encoder, is it working?

I also can see an extra slash on its URL http:///rtsencode/

check your YPT configuration menu

**Comment by loso20p** [comment]
its working good

**Comment by DanielnetoDotCom** [comment]
with 3 slashes? http://**/**rtsencode/

**Comment by loso20p** [comment]
its one slash http://realtalksociety.com/rtsencode

**Comment by DanielnetoDotCom** [comment]
Ok, the command should be file_get_contents(http://realtalksociety.com/rtsencode/getImageMP4/aHR0cDovL3JlYWx0YWxrc29jaWV0eS5jb20vdmlkZW9zL0FubmFiZWxsZUNyZWF0aW9uMjAxNzEwODBwQmx1UmF5eDI2NFlUU0FHXzVhOTA4ODMxMjIwOTA4Ljg3ODM0NTg0Lm1wNA==/jpg/3291.5):

Does this URL works? 

http://realtalksociety.com/rtsencode/getImageMP4/aHR0cDovL3JlYWx0YWxrc29jaWV0eS5jb20vdmlkZW9zL0FubmFiZWxsZUNyZWF0aW9uMjAxNzEwODBwQmx1UmF5eDI2NFlUU0FHXzVhOTA4ODMxMjIwOTA4Ljg3ODM0NTg0Lm1wNA==/jpg/3291.5

What is your encoder log?

Also make sure you have encoder and streamer updated

**Comment by loso20p** [comment]
did u update it recently?

**Comment by DanielnetoDotCom** [comment]
no, but just make sure

**Comment by loso20p** [comment]
everything is updated also i notice when i upload an mp4 under 100mb it grabs the images ut anything over 100mb it doesnt grab the image

**Comment by DanielnetoDotCom** [comment]
check your max upload file size (php.ini).

And also check the final file size (after encoder)

Check this, our limit is 500 mb, but HD video was over it, it was not complete, that is why this video does not receive image

![image](https://user-images.githubusercontent.com/18009293/36643392-521f61dc-1a29-11e8-8b9d-798e449c04e4.png)

**Comment by loso20p** [comment]
this is in my phph.ini
display_errors = Off
max_execution_time = 7200
max_input_time = -1
max_input_vars = 1000
memory_limit = 712M
post_max_size = 5000M
session.gc_maxlifetime = 1440
session.save_path = "/var/cpanel/php/sessions/ea-php70"
upload_max_filesize = 5000M
zlib.output_compression = Off

**Comment by DanielnetoDotCom** [comment]
Are you using the encoder right?

**Comment by loso20p** [comment]
yes

**Comment by DanielnetoDotCom** [comment]
Sorry for delay, still the problem with the image ?

**Comment by loso20p** [comment]
yes still a problem with it not grabbing the main image but ill just use the encoder way for now since that works.

**Comment by DanielnetoDotCom** [comment]
And the plugins still not working even after update encoder?
did you update the streamer also?

**Comment by DanielnetoDotCom** [comment]
No, you need to overwrite the files . the configuration does not detect updates yet

make sure you have latest encoder and streamer

**Comment by DanielnetoDotCom** [comment]
> and do i have to run the update in the encoder?

Depends what version you are

> and do i have to overwrite every file except videos?

Yes
