### ISSUE TITLE
Bug dashbord link

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#290]
![bildschirmfoto 2017-12-29 um 09 54 46](https://user-images.githubusercontent.com/30271757/34433414-6f0688ac-ec7f-11e7-9fad-2a2e53f56f76.png)
if I click on comments I'm redirected to this page  https://youtube.mikweb.eu/videos/ -->error 403
 instead I click on another button I'm reinitized on the video page  https://youtube.mikweb.eu/mvideos
 the link is wrong?

**Comment by DanielnetoDotCom** [comment]
Hi @mikweb2017  thanks for your help.
The Dashboards links still need to be improved.
I will release some better control, with moderation for comments. and there is where the link should go

**Comment by mikweb2017** [comment]
thanks
