### ISSUE TITLE
Plugins!!

### ISSUE THREAD

**Issue by LucasCM45** [DanielnetoDotCom/YouPHPTube#291]
I can create my own plugin or this is not allowed!

**Comment by DanielnetoDotCom** [comment]
Sure you can :) the problem is that still does not have documentation for that. 
but if you can learn it from the free plugins this will be great :)

**Comment by LucasCM45** [comment]
always when I upload some plugin always of this message No results found! and the folder name is the same as php :(

**Comment by DanielnetoDotCom** [comment]
Hi

Did you follow this: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-To-Install-a-new-Plugin

Can we see your youphptube.log file?

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
