### ISSUE TITLE
new features

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#293]
could you please tell us about the roadmap which new features we can expect in the future

**Comment by DanielnetoDotCom** [comment]
Sure: 

This is not the order that will be made, but it is what I am interested to do

## Plugins

1. Plugin Menu you can put an external or internal Link and create new dynamic pages
2. Plugin PayPal Paid to automatic enter in a group
3. Plugin Subtitle
4. Plugin Facebook comments
5. Plugin Amazon S3 support.

## Upgrades

1. Improve comments, let admin/video owners moderate and edit comments
2. Verify users email, send email to verify, and put a badge on the verified users name
3. Use a permalink like Youtube, videos will have the SEO link (current) but also will have a permanent link that will never change
4. save live streams and automatic send it to encoder
5. Watch later system.
6. like / dislikes on comments
7. reply to comment system.
8. Tags for videos to help SEO
9. Admin can moderate/approve users videos

## Encoder

1. Encoder choose audio track from video

**Comment by DanielnetoDotCom** [comment]
Any new Ideas will be graceful

**Comment by gamersalpha** [comment]
- do u have same plugin template ? to let comunity make pluigin ?
- really need let user make some live streaming not only amdin
- Add a way to edit video (like google) diretly on the editing

many things, i will make a big list :)

i really like u apps :)

**Comment by linusanderas** [comment]
Im interested in using youPHPTube for a service to let Swedish churches stream their services but we would need the feature to save the livestream. 
Is it any way that I can help to get that feature into place?

**Comment by abamilod** [comment]
I vote subtitle plugin priority 1st pls.

**Comment by DanielnetoDotCom** [comment]
Hi @linusanderas @abamilod  @gamersalpha  @mikweb2017 

We release an way to priorize the features development, an [Crowdfunding System](https://easytube.club/#funding)

There you can incentivize us for more Features
Pledge $10 USD or more and when the plugin or feature is ready the value offered will be deducted from the final cost of the update if it is to be paid. None of the improvements offered here are defined as whether it will be free or paid, but you get paid anyway, if it is paid you will have the discount over the amount offered, if it is free you will be helping the community and others.
Fell Free to add more Features Requests Here

**Comment by abamilod** [comment]
@DanielnetoDotCom 
usually crowdfunding such as (kickstarter/indiegogo) concept is about early backer gets cheaper price. but anyway good idea tho.

**Comment by DanielnetoDotCom** [comment]
@abamilod you right, I will think correct and make a discount for the backer

**Comment by DanielnetoDotCom** [comment]
**More New desired features**

Add broadcast on facebook and youtube., create an option to play the streamed video on the site and broadcast to facebook and youtube account

Use external HLS / RTMP sources, like wowza and others

Make the app use external filesystem, like remote ones
Make tests with https://flysystem.thephpleague.com if it is good...

**Comment by gamersalpha** [comment]
Hello, 
just an other idea, to have compatibilité with many database, maybe can use doctrine ?

http://www.doctrine-project.org/

> The Doctrine Project is the home to several PHP libraries primarily focused on database storage and object mapping. The core projects are a Object Relational Mapper (ORM) and the Database Abstraction Layer (DBAL) it is built upon. Doctrine has greatly benefited from concepts of the Hibernate ORM and has adapted them to fit the PHP language.


i think is a good project

**Comment by mikweb2017** [comment]
new features  Photo gallery  with Star ratink  like instgram or flicker

**Comment by DanielnetoDotCom** [comment]
First version of Android App https://play.google.com/store/apps/details?id=mobile.youphptube.com

**Comment by mikweb2017** [comment]
> 
First version of Android App https://play.google.com/store/apps/details?id=mobile.youphptube.com
> 
great work congratulations
but there is no possibility to save access data even better than autologin with faceboock and google

**Comment by DanielnetoDotCom** [comment]
It already save access
But I am trying to work with social medias login. It is not done yet

Em 9 de jan de 2018 02:15, "mikweb2017" <notifications@github.com> escreveu:

**Comment by mikweb2017** [comment]
![whatsapp image 2018-01-09 at 18 00 27](https://user-images.githubusercontent.com/30271757/34732984-2d23c9ea-f567-11e7-99cd-868508603efd.jpeg)


when I close the app and then reopen again I have to log in again I do not find it very convenient

  ulpoad video not working right?

**Comment by DanielnetoDotCom** [comment]
You not suppose to login again.
It should be automatic

Did you update your streamer and encoder ?
You will need all up to date

Em 9 de jan de 2018 14:07, "mikweb2017" <notifications@github.com> escreveu:

[image: whatsapp image 2018-01-09 at 18 00 27]
<https://user-images.githubusercontent.com/30271757/34732984-2d23c9ea-f567-11e7-99cd-868508603efd.jpeg>

when I close the app and then reopen again I have to log in again I do not
find it very convenient

ulpoad video not working right?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/DanielnetoDotCom/YouPHPTube/issues/293#issuecomment-356349218>,
or mute the thread

**Comment by mikweb2017** [comment]
i take a screen-video

**Comment by mikweb2017** [comment]
https://demo.youphptube.com/video/androip-app
 
screen-video

**Comment by DanielnetoDotCom** [comment]
@mikweb2017 thanks for testing.
I can see you are using an android emulator, can you please share it's configurations?
I also use an emulator of nexus 5. and works fine.
Also on real mobile device Moto X, LG K10 and an Zenfone 3, all works fine

that is my emulator configuration: 
![image](https://user-images.githubusercontent.com/18009293/34740866-9b47ab6a-f55f-11e7-965e-0f03fec3a78e.png)

I also made a video
https://demo.youphptube.com/video/youphptube-android-application

**Comment by mikweb2017** [comment]
I'm using a real phone with Android 7.0

http://consumer.huawei.com/en/phones/nova/

video upload dont work i have streamer and encoder  already up to date

I love your job and test willingly

**Comment by DanielnetoDotCom** [comment]
Did you enable your Plugin mobile manager? 
![image](https://user-images.githubusercontent.com/18009293/34742168-0a8ef7fe-f564-11e7-8270-269ed16b9dec.png)

Can you check the log files?

**Comment by mikweb2017** [comment]
yes i have enable  
which log files  streamer  or enconder or mobile phone?

**Comment by DanielnetoDotCom** [comment]
Streamer

**Comment by mikweb2017** [comment]
[08-Jan-2018 18:14:56 UTC] Files Received for video 171: Video by michelindaniele
[09-Jan-2018 03:44:34 UTC] PHP Warning:  require_once(/var/www/vhosts/you-tube.eu/httpdocs/plugin/LoginLDAP/LoginLDAP.php): failed to open stream: No such file or directory in /var/www/vhosts/you-tube.eu/httpdocs/plugin/MobileManager/upload.php on line 8
[09-Jan-2018 03:44:34 UTC] PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/you-tube.eu/httpdocs/plugin/LoginLDAP/LoginLDAP.php' (include_path='.:/opt/plesk/php/7.1/share/pear') in /var/www/vhosts/you-tube.eu/httpdocs/plugin/MobileManager/upload.php on line 8
[09-Jan-2018 03:44:46 UTC] PHP Warning:  require_once(/var/www/vhosts/you-tube.eu/httpdocs/plugin/LoginLDAP/LoginLDAP.php): failed to open stream: No such file or directory in /var/www/vhosts/you-tube.eu/httpdocs/plugin/MobileManager/upload.php on line 8
[09-Jan-2018 03:44:46 UTC] PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/you-tube.eu/httpdocs/plugin/LoginLDAP/LoginLDAP.php' (include_path='.:/opt/plesk/php/7.1/share/pear') in /var/www/vhosts/you-tube.eu/httpdocs/plugin/MobileManager/upload.php on line 8
[09-Jan-2018 03:48:30 UTC] PHP Warning:  require_once(/var/www/vhosts/you-tube.eu/httpdocs/plugin/LoginLDAP/LoginLDAP.php): failed to open stream: No such file or directory in /var/www/vhosts/you-tube.eu/httpdocs/plugin/MobileManager/upload.php on line 8
[09-Jan-2018 03:48:30 UTC] PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/you-tube.eu/httpdocs/plugin/LoginLDAP/LoginLDAP.php' (include_path='.:/opt/plesk/php/7.1/share/pear') in /var/www/vhosts/you-tube.eu/httpdocs/plugin/MobileManager/upload.php on line 8
[09-Jan-2018 03:48:43 UTC] PHP Warning:  require_once(/var/www/vhosts/you-tube.eu/httpdocs/plugin/LoginLDAP/LoginLDAP.php): failed to open stream: No such file or directory in /var/www/vhosts/you-tube.eu/httpdocs/plugin/MobileManager/upload.php on line 8
[09-Jan-2018 03:48:43 UTC] PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/you-tube.eu/httpdocs/plugin/LoginLDAP/LoginLDAP.php' (include_path='.:/opt/plesk/php/7.1/share/pear') in /var/www/vhosts/you-tube.eu/httpdocs/plugin/MobileManager/upload.php on line 8
[09-Jan-2018 03:48:54 UTC] PHP Warning:  require_once(/var/www/vhosts/you-tube.eu/httpdocs/plugin/LoginLDAP/LoginLDAP.php): failed to open stream: No such file or directory in /var/www/vhosts/you-tube.eu/httpdocs/plugin/MobileManager/upload.php on line 8
[09-Jan-2018 03:48:54 UTC] PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/you-tube.eu/httpdocs/plugin/LoginLDAP/LoginLDAP.php' (include_path='.:/opt/plesk/php/7.1/share/pear') in /var/www/vhosts/you-tube.eu/httpdocs/plugin/MobileManager/upload.php on line 8
[09-Jan-2018 03:50:52 UTC] PHP Warning:  require_once(/var/www/vhosts/you-tube.eu/httpdocs/plugin/LoginLDAP/LoginLDAP.php): failed to open stream: No such file or directory in /var/www/vhosts/you-tube.eu/httpdocs/plugin/MobileManager/upload.php on line 8
[09-Jan-2018 03:50:52 UTC] PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/you-tube.eu/httpdocs/plugin/LoginLDAP/LoginLDAP.php' (include_path='.:/opt/plesk/php/7.1/share/pear') in /var/www/vhosts/you-tube.eu/httpdocs/plugin/MobileManager/upload.php on line 8
[09-Jan-2018 03:51:26 UTC] PHP Warning:  require_once(/var/www/vhosts/you-tube.eu/httpdocs/plugin/LoginLDAP/LoginLDAP.php): failed to open stream: No such file or directory in /var/www/vhosts/you-tube.eu/httpdocs/plugin/MobileManager/upload.php on line 8
[09-Jan-2018 03:51:26 UTC] PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/you-tube.eu/httpdocs/plugin/LoginLDAP/LoginLDAP.php' (include_path='.:/opt/plesk/php/7.1/share/pear') in /var/www/vhosts/you-tube.eu/httpdocs/plugin/MobileManager/upload.php on line 8
[09-Jan-2018 05:25:52 UTC] MOBILE UPLOAD: Starts
[09-Jan-2018 05:25:52 UTC] SEND To QUEUE: Array
(
    [user] => admin
    [pass] => df3148490984cc5c47d5812ddf81c16c
    [fileURI] => https://you-tube.eu/videos/original_video3A97875mp4_YPTuniqid_5a545260daf4f5.26378073
    [filename] => video3A97875mp4_YPTuniqid_5a545260daf4f5.26378073
    [videos_id] => 
    [notifyURL] => https://you-tube.eu/
)

[09-Jan-2018 05:25:53 UTC] QUEUE CURL: stdClass Object
(
    [error] => 
    [response] => This user can not upload files
)

[09-Jan-2018 05:25:53 UTC] MOBILE SUCCESS UPLOAD: We sent your video to the encoder
[09-Jan-2018 16:56:52 UTC] MOBILE UPLOAD: Starts
[09-Jan-2018 16:56:52 UTC] SEND To QUEUE: Array
(
    [user] => admin
    [pass] => df3148490984cc5c47d5812ddf81c16c
    [fileURI] => https://you-tube.eu/videos/original_video3A97875mp4_YPTuniqid_5a54f454c98876.10152368
    [filename] => video3A97875mp4_YPTuniqid_5a54f454c98876.10152368
    [videos_id] => 
    [notifyURL] => https://you-tube.eu/
)

[09-Jan-2018 16:56:52 UTC] QUEUE CURL: stdClass Object
(
    [error] => 
    [response] => This user can not upload files
)

[09-Jan-2018 16:56:52 UTC] MOBILE SUCCESS UPLOAD: We sent your video to the encoder
[09-Jan-2018 19:12:02 UTC] MOBILE UPLOAD: Starts
[09-Jan-2018 19:12:02 UTC] SEND To QUEUE: Array
(
    [user] => admin
    [pass] => df3148490984cc5c47d5812ddf81c16c
    [fileURI] => https://you-tube.eu/videos/original_video3A97875mp4_YPTuniqid_5a551402228a26.64686300
    [filename] => video3A97875mp4_YPTuniqid_5a551402228a26.64686300
    [videos_id] => 
    [notifyURL] => https://you-tube.eu/
)

[09-Jan-2018 19:12:02 UTC] QUEUE CURL: stdClass Object
(
    [error] => 
    [response] => This user can not upload files
)

[09-Jan-2018 19:12:02 UTC] MOBILE SUCCESS UPLOAD: We sent your video to the encoder
[09-Jan-2018 19:59:04 UTC] MOBILE UPLOAD: Starts
[09-Jan-2018 19:59:04 UTC] SEND To QUEUE: Array
(
    [user] => admin
    [pass] => df3148490984cc5c47d5812ddf81c16c
    [fileURI] => https://you-tube.eu/videos/original_video3A97882mp4_YPTuniqid_5a551f086394b9.91156045
    [filename] => video3A97882mp4_YPTuniqid_5a551f086394b9.91156045
    [videos_id] => 
    [notifyURL] => https://you-tube.eu/
)

[09-Jan-2018 19:59:04 UTC] QUEUE CURL: stdClass Object
(
    [error] => 
    [response] => This user can not upload files
)

[09-Jan-2018 19:59:04 UTC] MOBILE SUCCESS UPLOAD: We sent your video to the encoder

**Comment by DanielnetoDotCom** [comment]
your encoder answer this "This user can not upload files"
any glue?
can yo double check if you update your encoder?

**Comment by mikweb2017** [comment]
sorry  
you're right!!
I have more encoders in the same domain...
Video upload  workfine   but autologin  for me  dont  work

**Comment by DanielnetoDotCom** [comment]
About the auto login it is working fine in all androids I have, I am not sure how to proceed to fix this.

**Comment by abamilod** [comment]
@DanielnetoDotCom after testing youphptube mobile : i managed to upload file and see encoder message while file being encoded. This app good and stabil. I only wish if the app can remember last url streamer so I dont hv to keyin again.
 Thank you for this great apk.

**Comment by DanielnetoDotCom** [comment]
Hi @abamilod 

It suppose to remmember.
what is your device model? I will make some research to see what happened.
also I sent an update today, may be available in couple hours. please test if the "not saving URL" persist
@mikweb2017 please test it too

**Comment by mikweb2017** [comment]
now nothing is happening anymore

![whatsapp image 2018-01-10 at 13 46 19](https://user-images.githubusercontent.com/30271757/34773720-03e3aff4-f60d-11e7-90ac-4abd5926d0be.jpeg)

**Comment by DanielnetoDotCom** [comment]
@mikweb2017 can you please give details about your mobile module, I will make a deep research here

**Comment by DanielnetoDotCom** [comment]
@abamilod can you also give me your hardware details too?

**Comment by mikweb2017** [comment]
what do you mean? whit  "mobile module"

**Comment by DanielnetoDotCom** [comment]
I meant "mobile model" it was a mistype.
I mean RAM processor Android version brand :)

**Comment by mikweb2017** [comment]
http://consumer.huawei.com/en/phones/nova/

Snapdragon625 (4 x A53@2.0 GHz + 4 x A53@2.0 GHz)
RAM: 3 GB LPDDR3*

ROM: 32 GB; User Available: about 22 GB*

MicroSD: supports cards up to 128 GB

Android 7.0  with Emotion UI 5.0.1

**Comment by abamilod** [comment]
I am using mi5s plus cpu 235ghz ram 6gb on androud 7. In mobile app thr is memory tmp and persist memory and also sql db. When i close without clear memory its remember the url but after clear memory, it use default demo url back.

**Comment by DanielnetoDotCom** [comment]
@mikweb2017 and @abamilod I could not reproduce it with Android ver 7, but I got a similar error regarding the persistence in Android ver 6.
I made some changes and I guess it will working now, I am sending an update to playstore, and in couple hours you may have it.

Thanks for helping testing once more

**Comment by mikweb2017** [comment]
Sorry... but dont work for me

**Comment by mikweb2017** [comment]
https://demo.youphptube.com/video/svid-20180110-195749
video for my  mobile telephon

**Comment by DanielnetoDotCom** [comment]
@mikweb2017  You already update for the last version? 1.3?

**Comment by mikweb2017** [comment]
yes i have  remove  and  reinstall  now  1.3.0  and reboot  my phone  but don't work for me

**Comment by DanielnetoDotCom** [comment]
OMG, I will keeping trying to find an emulator that reproduce the same error.

**Comment by mikweb2017** [comment]
https://appetize.io

100 minutes for  free  online  emulator

**Comment by DanielnetoDotCom** [comment]
but can you find an emulator with the same problemas you?
I have many emulators here, but the app works on emulators, also on the mobiles I have

**Comment by mikweb2017** [comment]
sorry i don't know

**Comment by mikweb2017** [comment]
can you share  your .APK  app  i try  same emulator

**Comment by DanielnetoDotCom** [comment]
that is the link for the newest APK https://www.dropbox.com/s/jevj34u4lvovput/YouPHPTube.apk?dl=0

**Comment by mikweb2017** [comment]
New info app work in my phone only if login in demo.youphptube.com.  steamer site... if try my streamer site don' t work

**Comment by DanielnetoDotCom** [comment]
@mikweb2017  I am glad about it. You need to update the streamer and the encoder

**Comment by mikweb2017** [comment]
Streamer is up-to-date  enconder i check Tomorrow  pc Sleep  Germany is 22:00 pm

**Comment by abamilod** [comment]
@DanielnetoDotCom fyi login name Do persist as i keyin before. What you did in login name should be done on url too.

**Comment by abamilod** [comment]
@DanielnetoDotCom after install new apk : app ask streamer url and forward to next interface. After successfully login i press back to close app. Without clear memory and with clear memory the app shows white backgroung with colour dots but going nowhere. It stucks.

**Comment by DanielnetoDotCom** [comment]
@abamilod @mikweb2017  I just send one version, with some other fixes regarding persistence, also I included social network login (facebook, google, etc)

But is very important update your streamer and encoder, usually updates for the mobiles comes with streamer updates too

**Comment by abamilod** [comment]
My streamer and encoder uptodate as we speak. I hv no problem login to url streamer with android apk. But now it stucks still show colour dots.

**Comment by DanielnetoDotCom** [comment]
Please wait google put the new APK on the play store or download it from here https://www.dropbox.com/s/4evn20kkr0oalje/YouPHPTube.apk?dl=0

**Comment by abamilod** [comment]
After install latest apk and update streamer : i can login to streamer like before with no problem. But after close the app with and without clear memory i got popup msg login and password does not match and colour dots and stucks also. I want to try social login next.

**Comment by DanielnetoDotCom** [comment]
@abamilod  can you contact me on developer@youphptube.com then we can test it together?

**Comment by mikweb2017** [comment]
good mornig   work fine for me !

**Comment by abamilod** [comment]
yes to those who want to download the stable version of youphptube android apk, you can get it on google play

**Comment by abamilod** [comment]
google social network login is been disable tho. but facebook and others should be ok

**Comment by novalava** [comment]
Hi,

I know most of uploading sites have Report feature.  
It's much better to have Report feature to prevent abuse.

Thanks,

Rob

**Comment by DanielnetoDotCom** [comment]
@novalava Yeah, you right Report Abuse will be added in the future

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
