### ISSUE TITLE
Live Streaming Group

### ISSUE THREAD

**Issue by DemonRem** [DanielnetoDotCom/YouPHPTube#294]
why only admin can do stream every new user need permission to apply their account to stream and I can do that only with the MySQL why is that if I want to let all registered users to stream what can i do

**Comment by DanielnetoDotCom** [comment]
Let users automatic able to stream is an upgrade that will come soon

**Comment by nightstryke** [comment]
@DanielnetoDotCom Do you mean it might be a future plugin?

**Comment by DanielnetoDotCom** [comment]
@nightstryke I do not know yet if it will be a plugin or will be built in

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
