### ISSUE TITLE
Change the videos directory

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/YouPHPTube#295]
Hello, 

on my configuration the video directory is : '/var/www/html/YouPHPTube/videos

so i need to change this video directory with somethings like this : 

/media/nas01/YouPHPTube/Videos

so on my serveur o share a directory for the video because my server don't have space disk

so how change the directory 
thanks

**Comment by DanielnetoDotCom** [comment]
Hi

There is a Plugin **SecureVideosDirectory** that allow you to change the video directory and Deny direct access to the video source file

![image](https://user-images.githubusercontent.com/18009293/34461089-ab032cc0-ee00-11e7-896e-99bba171b6c0.png)

**Comment by gamersalpha** [comment]
the plugin cost : USD $29.99

it's for a home using, i m not a professional :'(

**Comment by DanielnetoDotCom** [comment]
The plugin is for secure files.

But the tutorial shows you how to create symbolic links and change the
videos dir location

Em 1 de jan de 2018 7:00 AM, "Issa" <notifications@github.com> escreveu:

**Comment by abamilod** [comment]
Symbolic link folder wthin the same sever is stable but link with webdav/mount another remote server is not good especially within apache web folder.

**Comment by DanielnetoDotCom** [comment]
@abamilod Thanks for the tip, do you have any idea how to use a network storage?

**Comment by abamilod** [comment]
Network storage will be force not to sleep idle as it is coonected to apache webserver and thats not good too

**Comment by DanielnetoDotCom** [comment]
I have tried to use AWS S3 to store videos, and I think it war happening there.
I wish find a way to use it stably

**Comment by abamilod** [comment]
I also doing this test so far no good result yet

**Comment by DanielnetoDotCom** [comment]
@abamilod  thanks for your help, I am open if some one find a solution for network storage

**Comment by abamilod** [comment]
Thats why i was trying embeded video is storage server to main domain web

**Comment by abamilod** [comment]
No problem we all want the same thing i guess

**Comment by gamersalpha** [comment]
Hello, 
why not using a framwork ?

like this :

**Comment by gamersalpha** [comment]
Hello, 
why not using a framwork like this : 

https://flysystem.thephpleague.com/

with this framwork u can create class to optimise the files ressource ?

**Comment by DanielnetoDotCom** [comment]
@gamersalpha this is great, I will take a look on this. at least to host videos

**Comment by dragonfly4** [comment]
@DanielnetoDotCom The demo video on your info page is broken. I don't mind paying $30 for the SecureVideosDirectory plug-in but I want to be sure it does what I need and that is prevent direct download of the .mp4 file. Can you please update the page with a working demo?

Follow this instructions: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Moving-videos-directory-and-securing-files-from-direct-access-to-the-video-source-file

> There is a Video, it is not public. The video source file is https://demo.youphptube.com/videos/_YPTuniqid_599cee25994a94.99095552.mp4, you will only be able to see the source file if you are logged in on demo site.

https://demo.youphptube.com/video/michael-w-smith-agnus-dei

**Comment by DanielnetoDotCom** [comment]
Hi, @dragonfly4 

I just tested and it is working fine, to make it clear this is the direct access to the video file: https://demo.youphptube.com/videos/_YPTuniqid_599cee25994a94.99095552.mp4

but you will be able to see it only if you login on the demo site.

use those credentials: 
user: admin
Pass: 123

**Comment by dragonfly4** [comment]
Hi @DanielnetoDotCom 

Thanks for clarifying this. 

So this "SecureVideosDirectory" plug-in cannot do the following access control?

> Allow video playback with embed code on a website and disable direct download access to the .mp4 file.

**Comment by DanielnetoDotCom** [comment]
I am not sure if I understand what do you mean.

The thing is. if the user have access to the site, and he is allow to vie the video he will be able to see, even embed videos.
But if he tried to share your video in somewhere else. people will need to go to your site to register to be able to see the video.

**Comment by dragonfly4** [comment]
I'm talking about anonymous access.

Example is Kaltura, they have access control settings so that the source/referrer can be checked when you embed a video on your corporate site.
https://knowledge.kaltura.com/kaltura-media-access-control-model

With youphptube the visitor just needs to view the source or open Chrome developer tools and he has the direct download link to the video.

`<source src="https://video.mydomain.com/youphptube/videos/_YPTuniqid_5a4e36925eb4e79.46428908_HD.mp4" type="video/mp4">`

I know you cannot avoid ripping but this way it's very easy to download the full video.

**Comment by DanielnetoDotCom** [comment]
If the user is logged in we can not avoid him to download the video.
About the domain , it is a good idea, may be implemented in the future

**Comment by dragonfly4** [comment]
It's a pity that plug-ins don't have documentation pages but just want to be sure as your first sentence confuses me. Logged in users can download the video, it are the anonymous users that interest me.

With the "SecureVideosDirectory" plug-in you can only protect video files if the user is forced to log-in to play the video?

**Comment by abamilod** [comment]
someone told me if u can watch/stream the video meaning that you can download it somehow.

**Comment by abamilod** [comment]
it just better make it more harder for newbies

**Comment by DanielnetoDotCom** [comment]
@dragonfly4  that is right, we will force users to login (and have the right privileges) to see the video.

@abamilod that is right too, with screen recorder is impossible to protect the videos.
Not even Netflix can protect them

**Comment by abamilod** [comment]
@DanielnetoDotCom  maybe your plugin could hv 3 days trial like that for testing purpose

**Comment by DanielnetoDotCom** [comment]
Hi, I do not have this option for trial, but you guys can use the demo site to test it

**Comment by abamilod** [comment]
@dragonfly4 you right At https://demo.youphptube.com/videos/ I can see files *.txt, *.jpg but no *.mp4 but even as anoymous visitor i can watch and view source page and get the mp4 address directly for downloading

**Comment by abamilod** [comment]
@DanielnetoDotCom Ok I agreed

**Comment by abamilod** [comment]
@dragonfly4 I think you can see the video mp4 because the plugin in demo site is still at /var/www/YouPHPTube/videos NOT in different folder storage.

**Comment by dragonfly4** [comment]
@abamilod The plug-in cannot do what I'm looking for which is OK. The purpose of Daniel his work is a self hosted YouTube clone.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by hohok17** [comment]
Hai Dan,
Can I change URL mydomain/YouPHPTTube to be ex : mydomain/videos
please help
Thanks

**Comment by DanielnetoDotCom** [comment]
I think what you need is use apache virtual hosts . Try Google that .

Or maybe just rename the directory

**Comment by hohok17** [comment]
After I rename directory YouPHPTube to be nutube
when I try mydomain/nutube nothing appeared in browser

**Comment by DanielnetoDotCom** [comment]
you also need to change the path on the videos/configuration.php file

**Comment by hohok17** [comment]
done
thanks much
