### ISSUE TITLE
raspberry install : #1071 - La clé est trop longue. Longueur maximale: 767

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/YouPHPTube#296]
Hello, 

so i m trying to install youPHPtube on my raspberry dedicated serveur
i really want have it on my home 
but i have an issu with mysql table : 

i have this errro : 

> CREATE TABLE IF NOT EXISTS `videos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `clean_title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `views_count` INT NOT NULL DEFAULT 0,
  `status` ENUM('a', 'i', 'e', 'x', 'd', 'xmp4', 'xwebm', 'xmp3', 'xogg', 'ximg') NOT NULL DEFAULT 'e' COMMENT 'a = active\ni = inactive\ne = encoding\nx = encoding error\nd = downloading\nxmp4 = encoding mp4 error \nxwebm = encoding webm error \nxmp3 = encoding mp3 error \nxogg = encoding ogg error \nximg = get image error',
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  `users_id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  `filename` VARCHAR(255) NOT NULL,
  `duration` VARCHAR(15) NOT NULL,
  `type` ENUM('audio', 'video', 'embed') NOT NULL DEFAULT 'video',
  `videoDownloadedLink` VARCHAR(255) NULL,
  `order` INT UNSIGNED NOT NULL DEFAULT 1,
  `rotation` SMALLINT NULL DEFAULT 0,
  `zoom` FLOAT NULL DEFAULT 1,
  `youtubeId` VARCHAR(45) NULL,
  `videoLink[...]

with error : 

#1071 - La clé est trop longue. Longueur maximale: 767

how to fix please

**Comment by DanielnetoDotCom** [comment]
Check this:
https://github.com/DanielnetoDotCom/YouPHPTube/issues/171
https://github.com/DanielnetoDotCom/YouPHPTube/issues/85
https://github.com/DanielnetoDotCom/YouPHPTube/issues/284

**Comment by gamersalpha** [comment]
ok thanks

> 4 > modifiy the source code because of old Mysql version the databases will not created if u not modify files likes this : 
> 
> `sudo nano/var/www/html/YouPHPTube/install/database.sql`
> 
> replace this line 52 : 
> `clean_title VARCHAR(255) NOT NULL,`
> by 
> `clean_title VARCHAR(191) NOT NULL,`
>

**Comment by gamersalpha** [comment]
ok so to install on raspbery, u have to do this  : 

1> Install a clean sd card with the latest Build of debian found here --> http://www.planete-domotique.com/blog/2016/05/26/creer-carte-systeme-raspberry-pi-version-12-3/
2> Make some optimisation of u os on raspberry here --> https://raspbian-france.fr/installer-raspbian-premier-demarrage-configuration/
3> Adding a network sharing for datas videos of youPhpTube --> http://frechdesign.blogspot.fr/2012/12/raspberry-xbmc-raspbmc-ajouter-un.html

so now install youPHPTube and youPHPTube-encoder : source : https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x-For-YouPHPTube-version-4.x-or-newer

first install all necessary : 

`sudo apt-get install apache2 php7.0 libapache2-mod-php7.0 php7.0-mysql php7.0-curl php7.0-gd php7.0-intl mysql-server mysql-client ffmpeg git libimage-exiftool-perl && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube.git && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube-Encoder.git && sudo apt-get install python && sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && sudo chmod a+rx /usr/local/bin/youtube-dl && sudo a2enmod rewrite`

4 > modifiy the source code because of old Mysql version the databases will not created if u not modify files likes this : 

`sudo nano/var/www/html/YouPHPTube/install/database.sql`

replace this line 52 : 
`clean_title VARCHAR(255) NOT NULL,`
by 
`clean_title VARCHAR(191) NOT NULL,`

5> Change the video directory with u sharing network : 

so my videos datas is in sharing directory : /media/FlexGoHome/YouPHPTube/videos

and second i create a ln -s :

    sudo ln -s /media/FlexGoHome/YouPHPTube/videos/ /var/www/html/YouPHPTube/videos

do the same for encoder :

sudo ln -s /media/FlexGoHome/YouPHPTube/videos-encoder/videos/ /var/www/html/YouPHPTube-Encoder/

6> modifie apache to have a redirection with domain name : 




7> Now u can go to : 

http://youtube-encoder.namel.fr/install/index.php
http://youtube.namel.fr/install/index.php

**Comment by DanielnetoDotCom** [comment]
thanks for your help

**Comment by gamersalpha** [comment]
Hello @DanielnetoDotCom can u please create a raspbery page for this ?

i try to install evry time on raspberry, i ahve to look on issu, i think u can add this tuto on the wiki

thanks

**Comment by DanielnetoDotCom** [comment]
Sorry, I don't have raspberry and I have never deal with that
