### ISSUE TITLE
Hotkeys-Issues solved

### ISSUE THREAD

**Issue by hersche** [DanielnetoDotCom/YouPHPTube#297]
Hello, 

don't know how i should handle, i could make a pull-request but don't know how to do this for a single commit. Feel free to handle it as you like.

My commit https://github.com/hersche/YouPHPTube/commit/29e823f5c8d408cb5c86fsdf8f45306a4bb9cb1eb47 solves the point of space for pause/resume, f for fullscreen, etc. May need finetuning!

That should solve #59 and may others?

Have fun and best regards. Also many thx for the person wrote the youphpflix-plugin, it's genoius!

**Comment by DanielnetoDotCom** [comment]
Hi @hersche 

When I click on your link I got this...

![image](https://user-images.githubusercontent.com/18009293/34472713-a4ce0798-ef46-11e7-9da4-bde05b7a6455.png)

But any way, can you please make a pull request? will be great having you as a contributor :)

**Comment by hersche** [comment]
don't know whats wrong, typo or so, i'm sorry. here's the link again, i've tested it in the preview..

https://github.com/hersche/YouPHPTube/commit/29e823f5c8d408cb5c86f8f45306a4bb9cb1eb47

**Comment by DanielnetoDotCom** [comment]
Great, you use the video.js plugin. that is nice. The only thing I would make different I would make it as an youphptube plugin. some times people dont want it. 
If you want to try, let me know, I may help you with this new plugin :)
but any way, this was great thanks for your help :)

**Comment by hersche** [comment]
mh, don't see through your plugin-structure yet and i think it's may better useable with settings?
anyway, would be interessting to do plugins, but not today.. when you are faster in implement it in a nice way, feel free.. :)

**Comment by gamersalpha** [comment]
Hello cool !

> Have fun and best regards. Also many thx for the person wrote the youphpflix-plugin, it's genoius!

Where get this plugins please ?

**Comment by hersche** [comment]
it's not a plugin, it's hardcoded right now.

apply these changes on your youphptube-code and there you go: https://github.com/hersche/YouPHPTube/commit/29e823f5c8d408cb5c86f8f45306a4bb9cb1eb47

or you mean this? https://github.com/DanielnetoDotCom/YouPHPTube/tree/master/plugin/YouPHPFlix
i just said thx for this cause it makes a great overview of categorys and videos.

**Comment by abamilod** [comment]
Please make this as a plugin visible coded so i can learn it too

**Comment by DanielnetoDotCom** [comment]
@gamersalpha  go yo your plugin page , if your YouPHOTube is up dated you should have a plugin called YouPHPFlix

@abamilod if @hersche  can not build it as a plugin as soon as I get some free time I will build it and release it free and open :)

**Comment by abamilod** [comment]
@DanielnetoDotCom you are the best man!

**Comment by hersche** [comment]
@DanielnetoDotCom i think i get/understand the main-plugin-structure, like getName, getHeaderCode etc..

what i don't get: the youphpflix-plugin use the "getFirstPage()"-method - this seems to place the plugin into the startpage, /cat/-site, etc, but not on the page where the video itself plays. that's well for this plugin(s).

in my case, i need the opposite, my plugin should only be active, when the user is on a concrete video, so there where the movie plays, what's for shure not the "firstPage".

i found no method like "getVideoPage()" where i could return my scriptcontent. maybe this would also work with the getHeaderCode-method, but this would be unproper, because of the first page - also, i'm not shure if it's not included too early then.

so what's the right method for this case?

my reference for plugin-structure was https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/plugin/Plugin.abstract.php

plugin/YouPHPTube.php is a bit too complex to understand for me atm, but shure there would be a solution-szenario..

**Comment by hersche** [comment]
well, i got it.

https://github.com/hersche/YouPHPTube/commit/92ca10f9228fa3bd6e76cec50735b3a666b6671e

the if-condition is may not very great, but it works. also, i don't know how to set und use options/parameters, personaly i would like to disable up and down for volume and use it default.

to set such stuff would be the best. close, if you want, extend how you like..

best regards and have fun

**Comment by DanielnetoDotCom** [comment]
@hersche 
Looks like you did it right.
can you please make a pull request?

**Comment by abamilod** [comment]
@hersche
Did you create the plugin youphptube? Good job.

**Comment by abamilod** [comment]
@hersche Actually you can use tab key to navigate to player control (tab 3x) until it reaches volume bar and use arrow key for volume but using + and - would be better tho.

**Comment by hersche** [comment]
you should be able to change volume with up/down-arrows only (no tab/control-showup needed). 

but + - would be also nice - up/down is just default and i have to look for the right key-codes and similiar stuff..

**Comment by abamilod** [comment]
This is nice. I think using arrow up/down for volume better than -/+. thumbs up

**Comment by hersche** [comment]
i don't think so. when i personaly press up/down-arrows, i except, the website will sharing. instead i mute the movie.

youtube, which we "want to clone", also don't handle it this way. if you really like it the way it is, i could make it reverseable via plugin-options - but i have to do it at all first ;)

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by hersche** [comment]
oh, it's basicly implemented, merged and working, so it's absolutly closeable.. 
i (or faster people than me) will bring updates via pull-requests, not issues, so no reason in my eyes for reopen :)
