### ISSUE TITLE
Erreur connexion serveur for live stream with OBS

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/YouPHPTube#299]
Hello, 
now i finish my install of my encoder and my principal youPHPTUBE, 

now i really want to make a streaming, so i m using OBS : 

on my youPhpTUBE i have this information : 

![image](https://user-images.githubusercontent.com/32466950/34483805-1ee1e9b2-efc1-11e7-8325-04ab81d224b6.png)

so i put this info on my OBS :
![image](https://user-images.githubusercontent.com/32466950/34483870-74516f26-efc1-11e7-9256-ff75420d67ef.png)

but when i start to stream  i have an error message : 

![image](https://user-images.githubusercontent.com/32466950/34483885-86271200-efc1-11e7-9f99-2fcb010b9c44.png)

what do u think please ?

**Comment by mikweb2017** [comment]
try  nginx to start  sudo /usr/local/nginx/sbin/nginx

**Comment by gamersalpha** [comment]
i have this : 

`sudo: /usr/local/nginx/sbin/nginx: command not found`

i don't remember nginx on the install procedure ?

**Comment by gamersalpha** [comment]
ok u have this how to to make stream : 

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Set-up-my-own-Stream-Server


can we used apache and nginx on the same server ?

**Comment by gamersalpha** [comment]
i have a news error : 

![image](https://user-images.githubusercontent.com/32466950/34487788-27a430e0-efd6-11e7-8a77-f1d2480afdf9.png)

**Comment by DanielnetoDotCom** [comment]
check your nginx.conf file

check your on_publish directive
it must be pointing to your Live plugin

`on_publish http://[Your.YouPHPTube.url]/plugin/Live/on_publish.php;`

**Comment by gamersalpha** [comment]
i have this on acces.log of nginx : 


`192.168.50.21 - - [02/Jan/2018:16:57:18 +0100] "\x03\x01\x02\x90\xBA\x00\x00\x00\x00)#\xBE\x84\xE1l\xD6\xAER\x90I\xF1\xF1\xBB\xE9\xEB\xB3\xA6\xDB<\x87\x0C>\x99$^" 400 173 "-" "-"
`


nothing on error.log


and the nginx.conf looks good for the config : 

`
    worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells w$
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://youtube.domaine.fr/plugin/Live/on_publish.php;
                            on_play http://youtube.domaine.fr/plugin/Live/on_play.php;
                            on_record_done http://youtube.domaine.fr/plugin/Live/on_record_done.php;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
...
`

**Comment by DanielnetoDotCom** [comment]
youtube.domaine.fr does not exists here

change it 
`http://youtube.domaine.fr/plugin/Live/on_publish.php;`

to your youphptube URL  location

**Comment by gamersalpha** [comment]
sorry but how restart nginx, we don't have service with the guide installation ?

**Comment by DanielnetoDotCom** [comment]
sudo /usr/local/nginx/sbin/nginx -s stop
    sudo /usr/local/nginx/sbin/nginx

**Comment by gamersalpha** [comment]
not working same things :/

**Comment by mikweb2017** [comment]
what have you in live plugin settinngs?

**Comment by gamersalpha** [comment]
i have my domain : 

![image](https://user-images.githubusercontent.com/32466950/34492345-6aab21f8-efe7-11e7-9408-fd2d6ecbf4ae.png)

**Comment by mikweb2017** [comment]
![bildschirmfoto 2018-01-02 um 18 05 51](https://user-images.githubusercontent.com/30271757/34492432-d8b462b8-efe7-11e7-848d-aca8c739d134.png)

**Comment by mikweb2017** [comment]
you mix http und https  
set you playerr http

{"button_title":"LIVE","server":"rtmp://youdoamin/live","playerServer":"**http:**//lyoudomain:80/live","stats":"http://youdomain:81/stats","disableGifThumbs":false}

**Comment by gamersalpha** [comment]
i found log in OBS : 

```

18:09:23.180: [rtmp stream: 'simple_stream'] Connecting to RTMP URL rtmp://youtube.domaine.fr:8080/live?p=561f66a38324d844e76860f7853ce6d5...
18:09:23.180: [rtmp stream: 'simple_stream'] Interface: Realtek PCIe GBE Family Controller (ethernet, 1000 mbps)
18:09:23.182: HandShake: Type mismatch: client sent 3, server answered 72
18:09:23.183: RTMPSockBuf_Fill, remote host closed connection
18:09:23.183: RTMP_Connect1, handshake failed.
18:09:23.183: [rtmp stream: 'simple_stream'] Connection to rtmp://youtube.domaine.fr:8080/live?p=561f66a38324d844e76860f7853ce6d5 failed: -2
18:09:23.189: ==== Streaming Stop ================================================
```

**Comment by mikweb2017** [comment]
check
https://github.com/DanielnetoDotCom/YouPHPTube/issues/115
https://github.com/DanielnetoDotCom/YouPHPTube/issues/138

**Comment by gamersalpha** [comment]
i have no success :/

**Comment by mikweb2017** [comment]
check pleas your settings  in  plugin  manager

![bildschirmfoto 2018-01-02 um 18 05 51](https://user-images.githubusercontent.com/30271757/34493815-dbc950de-efed-11e7-87df-cd8a36472013.png)

**Comment by gamersalpha** [comment]
i have this : 

![image](https://user-images.githubusercontent.com/32466950/34493844-028462b8-efee-11e7-9059-14f5da3af8a1.png)


i can't see what is wrong i remove the https

**Comment by mikweb2017** [comment]
change  port  for  player

**Comment by gamersalpha** [comment]
still this error : 

18:57:21.939: ------------------------------------------------
18:57:26.937: [rtmp stream: 'simple_stream'] Connecting to RTMP URL rtmp://youtube.domaine.fr:8080/live?p=561f66a38324d844e76860f7853ce6d5...
18:57:26.938: [rtmp stream: 'simple_stream'] Interface: Realtek PCIe GBE Family Controller (ethernet, 1000 mbps)
18:57:26.939: HandShake: Type mismatch: client sent 3, server answered 72
18:57:26.940: RTMPSockBuf_Fill, remote host closed connection
18:57:26.940: RTMP_Connect1, handshake failed.
18:57:26.940: [rtmp stream: 'simple_stream'] Connection to rtmp://youtube.domaine.fr:8080/live?p=561f66a38324d844e76860f7853ce6d5 failed: -2
18:57:26.945: ==== Streaming Stop ================================================

**Comment by DanielnetoDotCom** [comment]
player:444 it suppose to be https, try to use player:8080
and remove the 8080 port from server

**Comment by DanielnetoDotCom** [comment]
Server: rtmp://youtube.domaine.fr/live
PlayerServer: http://youtube.domaine.fr:8080/live
Stats: http://youtube.domaine.fr:8080/stats

**Comment by gamersalpha** [comment]
i remove 8080 from OBS : 

![image](https://user-images.githubusercontent.com/32466950/34494210-a66fd726-efef-11e7-80a1-256b883fe64c.png)

and looks working on obs :  (something is sending)

![image](https://user-images.githubusercontent.com/32466950/34494199-93db2570-efef-11e7-905b-d225b2d7ece8.png)

but on youphptube nothing comes : 

![image](https://user-images.githubusercontent.com/32466950/34494228-bf11c172-efef-11e7-82cd-87645a60b811.png)

**Comment by DanielnetoDotCom** [comment]
Definitely is sending.
Now you have to check your PlayerServer
Are u using https? or just http?

**Comment by gamersalpha** [comment]
only http for now

**Comment by DanielnetoDotCom** [comment]
FYI, HLS there is some latency, you may need to wait a minute to be able to see something
just wait a minute  of stream and refresh the page

**Comment by gamersalpha** [comment]
u right he is look like 1 min of delay (why so long i m on the same network ? )

other things, my video is on the screen, but youphptube, say's i m not online ?


![image](https://user-images.githubusercontent.com/32466950/34494466-f10e35ec-eff0-11e7-9da6-229f7de17b53.png)

**Comment by gamersalpha** [comment]
ok now working, we have to wait befre the stream start : 

![image](https://user-images.githubusercontent.com/32466950/34495995-ecd806e0-eff7-11e7-889c-8a0bd433fd62.png)


ok now two other problem : 


first : why the stream is not recorded by default :'( 
i see we need a plugin : SendRecordedToEncoder
but i can't found it : https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Record-Live-Stream

and the chat is not working to i have an error : 

`Trying to establish a chat server connection `


Well, i m so happy to see this apps

thanks

**Comment by mikweb2017** [comment]
Open an terminal from your webserver and type this command:

nohup php /[path-to-YouPHPTube]/plugin/LiveChat/chat-server.php &

and press Ctrl+C

**Comment by mikweb2017** [comment]
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Set-up-my-own-Stream-Server

**Comment by DanielnetoDotCom** [comment]
@gamersalpha 

the plugin SendRecordedToEncoder is almost out of the oven.
It is not on the market yet, but maybe will be release by tomorrow and will be a paid plugin.

Take a look on the plugins and features that we have in mind https://easytube.club/#funding 

Think about to make a bid on our funding system and you can have this plugin with a discount

**Comment by DanielnetoDotCom** [comment]
about your offline status check it this URL is working  http://youtube.domaine.fr:8080/stats

**Comment by gamersalpha** [comment]
Hello there, 

so i make a reinstall compete, without HTTPS (beaucause to many error) .

so now my youphptube.domaine.fr is full in HTTP and only on my home network.

so in live page : 

![image](https://user-images.githubusercontent.com/32466950/34571925-3a05ef9e-f170-11e7-9d7d-3009c014dd2d.png)

i have the live started but the website continu tu say's i m offline ?

and when i m going to  : 

![image](https://user-images.githubusercontent.com/32466950/34571988-6546adb0-f170-11e7-8127-d87c2d267e0d.png)

i m offline, 

this my config plugin : 

![image](https://user-images.githubusercontent.com/32466950/34572042-935e7192-f170-11e7-99e7-ce5059b7e107.png)

i can access to : http://youtube.domaine.fr:8080/stats

![image](https://user-images.githubusercontent.com/32466950/34572068-a783d6a8-f170-11e7-8af0-55af7da3c878.png)


just about the CHAT popup, i can send message but if i refrech the page, evrymessage is deleted ?

so i still have a problem for streaming

on youphptube log i have this : 

```
[04-Jan-2018 15:39:16 UTC] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
[04-Jan-2018 15:39:16 UTC] YouPHPTube-Encoder sending file to http://youtube.namel.fr/youPHPTubeEncoder.json
[04-Jan-2018 15:39:16 UTC] YouPHPTube-Encoder reading file from 
[04-Jan-2018 15:39:16 UTC] YouPHPTube-Streamer answer 
```

so i don"t know what is wrong, i follow the guide

**Comment by gamersalpha** [comment]
let's continue, 

so now i can have the word online, to have this we have the streamer need to activate the difusion to other people with this checkBox ; 

![image](https://user-images.githubusercontent.com/32466950/34575956-af454c1c-f17c-11e7-9a72-c5d2eea037ce.png)

don't forget to click the save stream box : 

![image](https://user-images.githubusercontent.com/32466950/34575975-bb45039a-f17c-11e7-9a5f-25ac25a8b48b.png)

ok so now i m here : 
people can see i  monline but i have the message : 

No compatible source was found for this media.

![image](https://user-images.githubusercontent.com/32466950/34576034-f360eab4-f17c-11e7-839c-ccf7bebd45b9.png)

i m close to make it works

**Comment by DanielnetoDotCom** [comment]
Hi, 

try to wait a minute before try to see your stream.
Also do you have a proxy?
for example in some companies the block this kind of stream

**Comment by gamersalpha** [comment]
Hello still stuck with this streaming things, i m interesting, with stream and record
and it's not easy to make it work

Streaming with OBS works : 



can u please make a better place for this features, for me  he is the best think on youPHPtube 

the way to stream and backup directly with youPHPEncoder
so please

**Comment by mikweb2017** [comment]
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Record-Live-Stream

and pay plugin
![bildschirmfoto 2018-01-13 um 18 56 59](https://user-images.githubusercontent.com/30271757/34908674-a5750e0c-f893-11e7-94d8-2513d9fd2314.png)

**Comment by gamersalpha** [comment]
ok works now the problem is on of my firefox plugins who refused to execute the video.

when i restart firefox with no plugin

streams works 


![image](https://user-images.githubusercontent.com/32466950/35233805-71f35d32-ff9f-11e7-80f9-70edc56137aa.png)

**Comment by gamersalpha** [comment]
Hello there, 
so now i m using a reverse proxy to have the https acess.

so in my config nginx files i change the http://youtube.domaine.fr by https://youtube.domaine.fr

and when i try to restart nginx i have this error 

can help please : 


```
pi@raspberrypi:~ $ sudo /usr/local/nginx/sbin/nginx -s stop
nginx: [emerg] invalid port in url "https://youtube.domaine.fr/plugin/Live/on_publish.php" in /usr/local/nginx/conf/nginx.conf:23
```

**Comment by DanielnetoDotCom** [comment]
you can not use https for on_publish parameter, must be http

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
