### ISSUE TITLE
Support for LDAP

### ISSUE THREAD

**Issue by Megatronic79** [DanielnetoDotCom/YouPHPTube#3]
Hey,

Great product! - just wondering if adding authentication via LDAP was on the road map at some stage?

Cheers

Stephen

**Comment by DanielnetoDotCom** [comment]
Thanks for using it.

LDAP Authentication is an interesting function. we may impplement it.
I can not guarantee when we will do it.
but it is on the road

best regards.

**Comment by Megatronic79** [comment]
Great :)
