### ISSUE TITLE
adding global configurition in site configuration

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/YouPHPTube#300]
Hello, 
i change my website http to https, and i have to found in : 

`/var/www/html/YouPHPTube/videos/configuration.php`

the  line : 

`$global['webSiteRootURL'] = 'https://youtube.domaine.fr/';`

because all page stille have http, can u please add this config directly in administrateur page on the site

thanks :)

**Comment by DanielnetoDotCom** [comment]
that is the correct place to change URL
did you change on config file and still not working?

**Comment by gamersalpha** [comment]
Hello, 
yes i found it in this php files, and now working, evry element of my page is in https.
but i have to go in command line and edit the php files

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
