### ISSUE TITLE
TvHeadend Connector - Show live TV on youPHPTube :)

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/YouPHPTube#301]
Hello, 
it will be very interresting to have a connector to  : https://tvheadend.org/

can we imagine, evry  think u can make with that :)

so exelent !!!

**Comment by DanielnetoDotCom** [comment]
I do not understand what we can do with that

**Comment by gamersalpha** [comment]
Hello 

tvheadend is a server with television flux,

so we can imagine some steaming with TV.

like the live channel BBC, or CBC or i don't know

u see ?
:)

if not i m sorry

**Comment by gamersalpha** [comment]
Hello
i have a real exemple 

so i have a server (raspberry :) ) who have a TNT key's connected with serveur TvHedend 

so now i can look TV via this files : 

```
#EXTM3U
#EXTINF:-1,TF1
http://192.168.50.50:9981/stream/channelid/170578283?ticket=61548A1A493A079395C121FBAE9EB5C9F99397C8&profile=pass
#EXTINF:-1,France 2
http://192.168.50.50:9981/stream/channelid/2027332605?ticket=B82FFC60B48B6770F9035D2F053795B852D4C1D1&profile=pass
#EXTINF:-1,F3 Aquitaine
http://192.168.50.50:9981/stream/channelid/1720143351?ticket=E3D2D809BABB869FFB6DD08E519F8529A3F8A04A&profile=pass
#EXTINF:-1,CANAL+
http://192.168.50.50:9981/stream/channelid/72323235?ticket=4574EE21A951744F7A1BEF6B16F0AFF69683B6F0&profile=pass
#EXTINF:-1,France 5
http://192.168.50.50:9981/stream/channelid/817842855?ticket=CF00B162784B5FAA57422A561EE6B2DB4FC949CB&profile=pass
```

so now my question is how send this link in streaming direct on YouPHPTUBE : 
if i put this in VLC i can see the live streaming channel :
`
http://192.168.50.50:9981/stream/channelid/72323235?ticket=4574EE21A951744F7A1BEF6B16F0AFF69683B6F0&profile=pass`

what do u think please ?

**Comment by gamersalpha** [comment]
so i try this : 

`ffmpeg -i http://192.168.50.50:9981/stream/channelid/170578283?ticket=61548A1A493A079395C121FBAE9EB5C9F99397C8&profile=pass   -c:v libx264 -c:a libmp3lame -ar 44100 -ac 1 -f flv rtmp://youtube.domaine.fr/live?p=XXXXXXXXXXXXXXXXXXXXXXXXXXXX
`
of course not working

i try with files ! 

> ffmpeg -re -i _YPTuniqid_5a4e6dd7920e50.61924115_SD.mp4 -c:v libx264 -c:a libmp3lame   -ar 44100 -ac 1 -f flv  rtmp://youtube.domaine.fr/live?p=561f66a38324d844e76860f7853ce6d5

with this error : 

```
ffmpeg version 3.2.9-1~deb9u1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1) 20170516
  configuration: --prefix=/usr --extra-version='1~deb9u1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '_YPTuniqid_5a4e6dd7920e50.61924115_SD.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.56.101
  Duration: 00:05:03.46, start: 0.000000, bitrate: 1529 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 720x540 [SAR 60:41 DAR 80:41], 1395 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 129 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
rtmp://youtube.domaine.fr/live?p=561f66a38324d844e76860f7853ce6d5: Input/output error
```

well i think it will not be so easy, maybe need create a files to send it ...

**Comment by rollykaunang** [comment]
@gamersalpha whih one you like?
https://manadosiar.com:444/video/annihilation-2018-official-trailer-paramount-pictures
or
https://manadosiar.com:444/video/embed

**Comment by gamersalpha** [comment]
hello

this is it !

this is exatly what i want !!

please can u explain how do that 

realy thanks

**Comment by DanielnetoDotCom** [comment]
@rollykaunang this is great, is this just embed links or you did something else?

**Comment by rollykaunang** [comment]
@gamersalpha Yes it is embed link, It is very secure it could only embed to specific domain depend on which domain you allow. You could try by view source page and find the live stream source then embed to your site.

**Comment by gamersalpha** [comment]
@rollykaunang Hello

u have removed u site ?

when i m going on it i have a redirect to youphptube.com ?

**Comment by gamersalpha** [comment]
for me not working : 

this my html page : 

```
<head>
  <link href="http://vjs.zencdn.net/6.6.0/video-js.css" rel="stylesheet">

  <!-- If you'd like to support IE8 -->
  <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
</head>

<body>
  <video id="my-video" class="video-js" controls preload="auto" width="640" height="264"
  poster="_YPTuniqid_5a4e6b51cc78c4.71777935.jpg" data-setup="{}">
    <source src="_YPTuniqid_5a4e6b51cc78c4.71777935_HD.mp4" type='video/mp4'>

    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>
  
  
  <video id="my-video" class="video-js" controls preload="auto" width="640" height="264"
  poster="5.jpg" data-setup="{}">
    <source src="http://192.168.50.50:9981/stream/channelid/170578283?ticket=61548A1A493A079395C121FBAE9EB5C9F99397C8?fake=/play.mp4" type='video/mp4'>

    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>

  
  

  <script src="http://vjs.zencdn.net/6.6.0/video.js"></script>
</body>
```

the result : 

![image](https://user-images.githubusercontent.com/32466950/34638891-8bbce89a-f2d5-11e7-80d3-d5a3aba2dace.png)

```

Media resource http://192.168.50.50:9981/stream/channelid/170578283?ticket=61548A1A493A079395C121FBAE9EB5C9F99397C8?fake=/play.mp4 could not be decoded.
index.html
All candidate resources failed to load. Media load paused.
index.html
Media resource http://192.168.50.50:9981/stream/channelid/170578283?ticket=61548A1A493A079395C121FBAE9EB5C9F99397C8?fake=/play.mp4 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_METADATA_ERR (0x806e0006)
```


still looking how

**Comment by rollykaunang** [comment]
@gamersalpha Sorry if you can't visit my site no more! If you don't mind please provide your working computer ip addres send to danowudu@gmail.com and I will allow your ip addres into .htaccess so you will have access to it. Anyway i copy your html script and changing the video and live streaming source url, all went fine.  You could check https://manadosiar.com:444/videos/emb.html off course after i allowed you to visit my site.. So please email your ip address to my email address if you don't mind.

**Comment by gamersalpha** [comment]
can u copy past u cade please ?

**Comment by gamersalpha** [comment]
ok so i found somthing who working in InternetExplorrer and not in Firefox 👍 
with this code : 

`<head>
  <link href="http://vjs.zencdn.net/6.6.0/video-js.css" rel="stylesheet">

  
  <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
</head>

<body>
  <video id="my-video" class="video-js" controls preload="auto" width="640" height="264"
  poster="_YPTuniqid_5a4e6b51cc78c4.71777935.jpg" data-setup="{}">
    <source src="_YPTuniqid_5a4e6b51cc78c4.71777935_HD.mp4" type='video/mp4'>

    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>
  
  <br><br>
  
  <video id="my-video" class="video-js" controls preload="auto" width="640" height="264"
  poster="_YPTuniqid_5a4e6b51cc78c4.71777935.jpg" data-setup="{}">
    <source src="http://192.168.50.50:9981/stream/channelid/544973810?ticket=3F310E60A2A0D80507AC9641FB865D37C6B44206&profile=pass" type='video/mp4'>

    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>

  <script src="http://vjs.zencdn.net/6.6.0/video.js"></script>
</body>`

![image](https://user-images.githubusercontent.com/32466950/34686742-d1253d50-f4ac-11e7-9bd3-b89641fe3e4d.png)

so now how i create a streming playlist on youphptube please ?

**Comment by gamersalpha** [comment]
so i create a requete like this : 


`INSERT INTO `videos` (`id`, `title`, `clean_title`, `description`, `views_count`, `status`, `created`, `modified`, `users_id`, `categories_id`, `filename`, `duration`, `type`, `videoDownloadedLink`, `order`, `rotation`, `zoom`, `youtubeId`, `videoLink`, `next_videos_id`) VALUES (NULL, 'BFM TV', 'French information TV', 'French information TV', '0', 'a', '2018-01-08 00:00:00', '2018-01-08 00:00:00', '2', '1', 'http://192.168.50.50:9981/stream/channelid/1731118543?ticket=7BE6AC3AD8F9740D60A9AF2D83E693A406825CA9&profile=pass', '', 'video', NULL, '1', '0', '1', NULL, NULL, NULL);`


of course not working missing somthing, maybe need to add a TYPE live but is a enum i can add it on the database ?

and with this type can change the type a videojs balise in the code

what do u think please ?

**Comment by gamersalpha** [comment]
why using enum : 

![image](https://user-images.githubusercontent.com/32466950/34689459-e423dcb4-f4b5-11e7-9190-1a67f57e4d31.png)


no mto add a new type we have to modifie all structr database :/

**Comment by gamersalpha** [comment]
Hello, 

please do u have an idea how add some live tv support link in please of a video in local drive ?

**Comment by tgd1973** [comment]
Have you managed to embed live streaming of other sites? Inter also to me ...

**Comment by gamersalpha** [comment]
ok i want work again on tihs

just need an idea please to how to implement this in youPHPTUBE @DanielnetoDotCom

**Comment by gamersalpha** [comment]
ok so i try with embeded link direct on youphptub : 

First : 

![image](https://user-images.githubusercontent.com/32466950/35193055-ccf9bd00-fe9d-11e7-9d95-293c7cd7d338.png)

Second adding my embeded link : 
![image](https://user-images.githubusercontent.com/32466950/35193089-14b55e88-fe9e-11e7-9fc6-a36976d7347b.png)

and i m stuck like this for hour (and all my website is stuck (i can show other video )): 

![image](https://user-images.githubusercontent.com/32466950/35193110-632d11a0-fe9e-11e7-846c-5c893bced953.png)

so i crash this page and i have this on my video interface :

**Comment by DanielnetoDotCom** [comment]
Look the streamer log file to see what happened

**Comment by gamersalpha** [comment]
ok so i have this on my interface : 

![image](https://user-images.githubusercontent.com/32466950/35193564-c2052d9c-fea4-11e7-905f-68d16965684b.png)

but when i clike on it i have this message : 

![image](https://user-images.githubusercontent.com/32466950/35193571-da9de718-fea4-11e7-9eae-be7d722f94ca.png)

where is embede log please : 

i know this log :
 tail -f /media/FlexGoHome/YouPHPTube/videos/youphptube.log
and this : tail -f /media/FlexGoHome/YouPHPTube/videos-encoder/videos/youphptube.log

and not found information about this streaming ?


in database : 

```
`-- phpMyAdmin SQL Dump
-- version 4.6.6deb4
-- https://www.phpmyadmin.net/
--
-- Client :  localhost:3306
-- Généré le :  Dim 21 Janvier 2018 à 11:17
-- Version du serveur :  10.1.23-MariaDB-9+deb9u1
-- Version de PHP :  7.0.19-1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `youPHPTube`
--

-- --------------------------------------------------------

--
-- Structure de la table `videos`
--

CREATE TABLE `videos` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `clean_title` varchar(191) NOT NULL,
  `description` text,
  `views_count` int(11) NOT NULL DEFAULT '0',
  `status` enum('a','i','e','x','d','xmp4','xwebm','xmp3','xogg','ximg') NOT NULL DEFAULT 'e' COMMENT 'a = active\ni = inactive\ne = encoding\nx = encoding error\nd = downloading\nxmp4 = encoding mp4 error \nxwebm = encoding webm error \nxmp3 = encoding mp3 error \nxogg = encoding ogg error \nximg = get image error',
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  `users_id` int(11) NOT NULL,
  `categories_id` int(11) NOT NULL,
  `filename` varchar(255) NOT NULL,
  `duration` varchar(15) NOT NULL,
  `type` enum('audio','video','embed') NOT NULL DEFAULT 'video',
  `videoDownloadedLink` varchar(255) DEFAULT NULL,
  `order` int(10) UNSIGNED NOT NULL DEFAULT '1',
  `rotation` smallint(6) DEFAULT '0',
  `zoom` float DEFAULT '1',
  `youtubeId` varchar(45) DEFAULT NULL,
  `videoLink` varchar(255) DEFAULT NULL,
  `next_videos_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Contenu de la table `videos`
--

INSERT INTO `videos` (`id`, `title`, `clean_title`, `description`, `views_count`, `status`, `created`, `modified`, `users_id`, `categories_id`, `filename`, `duration`, `type`, `videoDownloadedLink`, `order`, `rotation`, `zoom`, `youtubeId`, `videoLink`, `next_videos_id`) VALUES
(63, '', '', 'French TV : TF1', 0, 'a', '2018-01-21 11:10:25', '2018-01-21 11:10:25', 2, 1, '_YPTuniqid_5a647521d0d153.78609694', '', 'embed', '', 1, 0, 1, NULL, 'http://192.168.50.50:9981/stream/channelid/170578283?ticket=61548A1A493A079395C121FBAE9EB5C9F99397C8&profile=pass', NULL);

--
-- Index pour les tables exportées
--

--
-- Index pour la table `videos`
--
ALTER TABLE `videos`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `clean_title_UNIQUE` (`clean_title`),
  ADD KEY `fk_videos_users_idx` (`users_id`),
  ADD KEY `fk_videos_categories1_idx` (`categories_id`),
  ADD KEY `index5` (`order`),
  ADD KEY `fk_videos_videos1_idx` (`next_videos_id`);

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `videos`
--
ALTER TABLE `videos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=64;
--
-- Contraintes pour les tables exportées
--

--
-- Contraintes pour la table `videos`
--
ALTER TABLE `videos`
  ADD CONSTRAINT `fk_videos_categories1` FOREIGN KEY (`categories_id`) REFERENCES `categories` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_videos_users` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_videos_videos1` FOREIGN KEY (`next_videos_id`) REFERENCES `videos` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
```

**Comment by newtecnerd13** [comment]
In your interface in the "status" tray it's acting "as if" as if what,  streaming live or?

Sent from Yahoo Mail on Android 
 
  On Sun, Jan 21, 2018 at 5:23 AM, Issa<notifications@github.com> wrote:   
ok so i have this on my interface :



but when i clike on it i have this message :



where is embede log please :

i know this log :
tail -f /media/FlexGoHome/YouPHPTube/videos/youphptube.log
and this : tail -f /media/FlexGoHome/YouPHPTube/videos-encoder/videos/youphptube.log

and not found information about this streaming ?

in database :
`-- phpMyAdmin SQL Dump
-- version 4.6.6deb4
-- https://www.phpmyadmin.net/
--
-- Client :  localhost:3306
-- Généré le :  Dim 21 Janvier 2018 à 11:17
-- Version du serveur :  10.1.23-MariaDB-9+deb9u1
-- Version de PHP :  7.0.19-1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `youPHPTube`
--

-- --------------------------------------------------------

--
-- Structure de la table `videos`
--

CREATE TABLE `videos` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `clean_title` varchar(191) NOT NULL,
  `description` text,
  `views_count` int(11) NOT NULL DEFAULT '0',
  `status` enum('a','i','e','x','d','xmp4','xwebm','xmp3','xogg','ximg') NOT NULL DEFAULT 'e' COMMENT 'a = active\ni = inactive\ne = encoding\nx = encoding error\nd = downloading\nxmp4 = encoding mp4 error \nxwebm = encoding webm error \nxmp3 = encoding mp3 error \nxogg = encoding ogg error \nximg = get image error',
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  `users_id` int(11) NOT NULL,
  `categories_id` int(11) NOT NULL,
  `filename` varchar(255) NOT NULL,
  `duration` varchar(15) NOT NULL,
  `type` enum('audio','video','embed') NOT NULL DEFAULT 'video',
  `videoDownloadedLink` varchar(255) DEFAULT NULL,
  `order` int(10) UNSIGNED NOT NULL DEFAULT '1',
  `rotation` smallint(6) DEFAULT '0',
  `zoom` float DEFAULT '1',
  `youtubeId` varchar(45) DEFAULT NULL,
  `videoLink` varchar(255) DEFAULT NULL,
  `next_videos_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Contenu de la table `videos`
--

INSERT INTO `videos` (`id`, `title`, `clean_title`, `description`, `views_count`, `status`, `created`, `modified`, `users_id`, `categories_id`, `filename`, `duration`, `type`, `videoDownloadedLink`, `order`, `rotation`, `zoom`, `youtubeId`, `videoLink`, `next_videos_id`) VALUES
(63, '', '', 'French TV : TF1', 0, 'a', '2018-01-21 11:10:25', '2018-01-21 11:10:25', 2, 1, '_YPTuniqid_5a647521d0d153.78609694', '', 'embed', '', 1, 0, 1, NULL, 'http://192.168.50.50:9981/stream/channelid/170578283?ticket=61548A1A493A079395C121FBAE9EB5C9F99397C8&profile=pass', NULL);

--
-- Index pour les tables exportées
--

--
-- Index pour la table `videos`
--
ALTER TABLE `videos`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `clean_title_UNIQUE` (`clean_title`),
  ADD KEY `fk_videos_users_idx` (`users_id`),
  ADD KEY `fk_videos_categories1_idx` (`categories_id`),
  ADD KEY `index5` (`order`),
  ADD KEY `fk_videos_videos1_idx` (`next_videos_id`);

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `videos`
--
ALTER TABLE `videos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=64;
--
-- Contraintes pour les tables exportées
--

--
-- Contraintes pour la table `videos`
--
ALTER TABLE `videos`
  ADD CONSTRAINT `fk_videos_categories1` FOREIGN KEY (`categories_id`) REFERENCES `categories` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_videos_users` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `fk_videos_videos1` FOREIGN KEY (`next_videos_id`) REFERENCES `videos` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

**Comment by tgd1973** [comment]
Maybe for embedded it was better to use as usual, the codes that use them all <iframe>  rather than using the APIs. 
I refer here to those who designed the current interface of youPHPTube with the video embedding section.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by gamersalpha** [comment]
still not working i hope u will make what @tgd1973 says in the code

because now u have only three type of audio - video - embede

maybe can create a new type livetv

who create a new php code with this : 

`<iframe style="width:640px; height:480px;" allowfullscreen src="http://x.x.x.x:8080/live2/embed.html"></iframe>`

**Comment by gamersalpha** [comment]
anyone is intersting by this ?

**Comment by Spartacus2018** [comment]
Hello there, 

can up this topic !!!
thanks

**Comment by DanielnetoDotCom** [comment]
@Spartacus2018 and @gamersalpha  can you put a sample link here?
