### ISSUE TITLE
Let's talk YouPHPTube in DISCORD

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/YouPHPTube#303]
Hello, 

i now this is not an issue, but i open a channel to talk about YouPHPtube in discord, to (i hope) create a community around this exelent tools !!

https://discord.gg/mKxeaPJ

thanks

**Comment by gamersalpha** [comment]
Hello, 

can u OK to add WebHook on the repo for Discord, ?

with WebHook, we can have all news direct on the discord ?

**Comment by gamersalpha** [comment]
@DanielnetoDotCom can u please contact me to add webhook of this project on discord ?

thanks to u

**Comment by DanielnetoDotCom** [comment]
@gamersalpha I do not use Discord

**Comment by gamersalpha** [comment]
maybe it's time, it's a realy cool tools to comunic with poeple
https://discordapp.com/

**Comment by gamersalpha** [comment]
@DanielnetoDotCom Hello, can i contact u in MP please ?

**Comment by DanielnetoDotCom** [comment]
What is MP?
anyway my email is: developer@youphptube.com

**Comment by gamersalpha** [comment]
hello

I'm afraid there are problems after.
should I make a backup of the database + file after I put in joru and if no problem I stay like that

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
