### ISSUE TITLE
index page is error page

### ISSUE THREAD

**Issue by GodSpeed2323** [DanielnetoDotCom/YouPHPTube#305]
I would like to know why the index page is legit an error page
I did what it said it I figured ok fixed but when I looked in the code
its an actual index page of an error page, any reason for this?? and how
do I fix? for /user works fine and so does admin panel

**Comment by DanielnetoDotCom** [comment]
Can you give us more details please?

**Comment by GodSpeed2323** [comment]
So I fresh installed the script right? no problems, yet the main index page is an error page saying I need to go into www/var/etc. and do something right? so I did that and yet nothing worked so I checked the index page to see if any includes where missing or maybe incorrect and I see that the actual index page is the damn error page, why is that? site is here :http://socialsans.online/ 
but https://www.socialsans.online/user works fine and admin panel work fine, did you mistake replace the index page? for on my other vps this never happened

**Comment by DanielnetoDotCom** [comment]
looks like the mode rewrite is not working properly
On the firsts line or .htaccess there are 3 lines


   ```
 #main Files
    RewriteRule    ^index.php$ view/index.php    [NC,L]
    #RewriteRule    ^index.php$ /view/index.php    [NC,L]
    #RewriteRule    ^$ view/    [NC,L]
```

try each per time for example comment the first line and uncomment the second, and see what happen


```
    #main Files
    #RewriteRule    ^index.php$ view/index.php    [NC,L]
    RewriteRule    ^index.php$ /view/index.php    [NC,L]
    #RewriteRule    ^$ view/    [NC,L]
```

And then the third line


```
    #main Files
    #RewriteRule    ^index.php$ view/index.php    [NC,L]
    #RewriteRule    ^index.php$ /view/index.php    [NC,L]
    RewriteRule    ^$ view/    [NC,L]
```

**Comment by GodSpeed2323** [comment]
ok thanks

**Comment by GodSpeed2323** [comment]
#main Files
    #RewriteRule    ^index.php$ view/index.php    [NC,L]
    #RewriteRule    ^index.php$ /view/index.php    [NC,L]
    RewriteRule    ^$ view/    [NC,L]

fixed it thanks!
