### ISSUE TITLE
Error when viewing "channels" as public  

### ISSUE THREAD

**Issue by SparcImagination** [DanielnetoDotCom/YouPHPTube#306]
Please check this whenever you choose to view a channel not logged on or as a public 

example: your-ip-address.com/video/channel/5/

you get this error (which was not present in previous -master build)

SELECT u.*, pl.* FROM playlists pl LEFT JOIN users u ON u.id = users_id WHERE 1=1 AND status = 'public' AND users_id = 5 LIMIT 12 \nError : (1052) Column 'status' in where clause is ambiguous

**Comment by DanielnetoDotCom** [comment]
Sorry you right, thanks for notify. I just sent a fix for this
