### ISSUE TITLE
user Image size

### ISSUE THREAD

**Issue by DemonRem** [DanielnetoDotCom/YouPHPTube#307]
i try to add a profile image as orginal size without corp but it's can't handle i guess it's possible to add full picture with orginal size or it's must to be corp :(

**Comment by DanielnetoDotCom** [comment]
The crop option is to guarantee the layout does not break and save some bandwidth .
For now there is only the crop option

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
