### ISSUE TITLE
nginx on  mac os X

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#308]
https://gist.github.com/netpoetica/5879685

would you like to try to run the streaming server on my mac according to you would work?

**Comment by DanielnetoDotCom** [comment]
I have never tested :(
To be honest I only tested it on ubuntu, but I see some users put it running on centos

**Comment by mikweb2017** [comment]
I'll try the week end I'll let you know

**Comment by mikweb2017** [comment]
dont work to youPHPTube
