### ISSUE TITLE
Specify resolutions in lines only (-2:480, -2:720,  etc) to keep source aspect ratio

### ISSUE THREAD

**Issue by Yetangitu** [DanielnetoDotCom/YouPHPTube#31]
FYI,

Specifying a full (x:y) resolution to `ffmpeg` when resampling a video it will result in distorted results for source material with different aspect ratios (eg. 4:3 will be 'squashed', etc).

To avoid this, make sure to specify only one part of the resolution and set the other to '-2'. Given that resolutions are often defined in lines the 'recommended resolutions' list would look like this:

```
-2:240 (240p)(SD)
-2:360 (360p)
-2:480 (480p)
-2:720 (720p)(Half HD)
-2:1080 (1080p)(Full HD)
-2:2160 (2160p)(Ultra-HD)(4K)
```

It might look a bit odd but it leads to better results.

**Comment by DanielnetoDotCom** [comment]
Very Thanks man.
I saw you pull requests, tomorrow I will take a look and accept them

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
