### ISSUE TITLE
live  chat Https

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#310]
help me please  chat dont work unter https

![bildschirmfoto 2018-01-13 um 18 37 10](https://user-images.githubusercontent.com/30271757/34908821-83d3f03a-f896-11e7-91a4-e9037a79f0df.png)
![bildschirmfoto 2018-01-13 um 19 06 45](https://user-images.githubusercontent.com/30271757/34908823-8672c302-f896-11e7-9764-482c42a4e425.png)

**Comment by DanielnetoDotCom** [comment]
did you make this ...


```
<IfModule mod_proxy.c>
        ProxyPass /wss/ ws://127.0.0.1:8888/
</IfModule>

sudo a2enmod proxy_wstunnel && sudo /etc/init.d/apache2 restart
```

**Comment by mikweb2017** [comment]
work fine  and my test stremear work fine HTTPS

**Comment by mikweb2017** [comment]
I had 2 nginx and one interfered with apache proxy
