### ISSUE TITLE
could not found your streamer site

### ISSUE THREAD

**Issue by cdseoo** [DanielnetoDotCom/YouPHPTube#311]
Hi 

Im so happy to used this opensource its really great to have it.

please im doing the encoder i believed it was successfully installed but when i tried to access it
could not found your streamer site!.
<img width="844" alt="123" src="https://user-images.githubusercontent.com/6162118/34919210-763f6e68-f99a-11e7-908d-d6a9a5c62258.PNG">

**Comment by DanielnetoDotCom** [comment]
you will need to give more details about log file and database tables and content

**Comment by cdseoo** [comment]
Thank you for your reply, hoping to continue to guide me.

<img width="848" alt="1234" src="https://user-images.githubusercontent.com/6162118/34925253-2b86a9f6-f9e3-11e7-961d-d7fd7cbc1a3e.PNG">
<img width="503" alt="12345" src="https://user-images.githubusercontent.com/6162118/34925254-2bc9c358-f9e3-11e7-88a9-0c7f1e18ee29.PNG">

erros log - streamer site:
[14-Jan-2018 21:53:28 America/New_York] PHP Notice:  Undefined variable: img in /var/www/html/YouPHPTube/view/modeYoutube.php on line 106
[14-Jan-2018 21:53:28 America/New_York] PHP Notice:  Undefined variable: img in /var/www/html/YouPHPTube/view/modeYoutube.php on line 118
[14-Jan-2018 21:53:28 America/New_York] PHP Notice:  Undefined variable: imgw in /var/www/html/YouPHPTube/view/modeYoutube.php on line 119
[14-Jan-2018 21:53:28 America/New_York] PHP Notice:  Undefined variable: imgh in /var/www/html/YouPHPTube/view/modeYoutube.php on line 120
[14-Jan-2018 21:53:28 America/New_York] PHP Warning:  file_get_contents(https://video./youwoai./com/plugin/CustomizeAdvanced/advancedCustom.json.php): failed to open stream: Connection refused in /var/www/html/YouPHPTube/view/include/navbar.php on line 11

erros log - encoder site:
[14-Jan-2018 21:53:55 America/New_York] https://video./youwoai./com/ == https://video./youwoai./com/
[14-Jan-2018 21:55:56 America/New_York] https://video./youwoai./com/ == https://video./youwoai./com/
[14-Jan-2018 21:55:59 America/New_York] https://video./youwoai./com/ == https://video./youwoai./com/

/ in urls for no <a>

Still >Sorry! We could not found your streamer site! <

**Comment by cdseoo** [comment]
I created Encoder on another vps, which works fine for my streamer site https/://video./youwoai./com/

Really strange~~~

<img width="307" alt="12" src="https://user-images.githubusercontent.com/6162118/34928499-f06b2160-f9f8-11e7-81d8-95ac65ee1093.PNG">

**Comment by gamersalpha** [comment]
U certificat ssl is valid ?

Because for mz when i used SSL certificat not valide youphptub not working

**Comment by DanielnetoDotCom** [comment]
I can see from the image the streamer on 77.55.209... is not on a https site

I  always like to keep all https or all http

**Comment by cdseoo** [comment]
Thank you for helping me~

My youphptube and encoder sites are all worded fine on https with one (*.youwoai.com) AlphaSSL Wildcard Certificate.

Do these two sites can not use a same SSL Wildcard domain name certificate?

<img width="634" alt="21" src="https://user-images.githubusercontent.com/6162118/34948786-1a6fb606-fa49-11e7-87b1-6052c41a6edb.PNG">
<img width="771" alt="22" src="https://user-images.githubusercontent.com/6162118/34948788-1aa67808-fa49-11e7-8265-fcfc6da0c283.PNG">

**Comment by DanielnetoDotCom** [comment]
@cdseoo look your streamer configuration menu and check your encoder server

![image](https://user-images.githubusercontent.com/18009293/34957754-9ffa09c0-fa0d-11e7-84ea-93dae3ff35d3.png)

**Comment by cdseoo** [comment]
@DanielnetoDotCom 

Sure, I had enter Encoder-url: https://video-/encoder/.youwoai./com/ 

I always saw:
Sorry!
We could not found your streamer site!

<img width="616" alt="31" src="https://user-images.githubusercontent.com/6162118/34974485-46b75294-fac8-11e7-8f78-1ed38da8c51a.PNG">

I almost collapsed~~

@DanielnetoDotCom if possible, please help me check the settings, thank you a lot.

**Comment by DanielnetoDotCom** [comment]
@cdseoo  send it to developer@youphptube.com

**Comment by DanielnetoDotCom** [comment]
I received your email, but looks like it is all fine

try to debug this line https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/blob/b2e831aca771dc913ba5dda1e3f220514dbc9487/objects/Login.php#L36
and see why the file_get_contents function is not working for you.

1 - remove the @ from the begin of the function and try again, it should display an error to you. 
2 - check the encoder error log

**Comment by DanielnetoDotCom** [comment]
I just learn this

Some times your PHP is configured that you can't include a PHP script that is on an external website/server into your local script

On your php.ini add this:

```
allow_url_fopen = On

allow_url_include = On

```
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Encoder-Error-We-could-not-found-your-streamer-site!

**Comment by cdseoo** [comment]
`; Fopen wrappers ;
;;;;;;;;;;;;;;;;;;

; Whether to allow the treatment of URLs (like http:// or ftp://) as files.
; http://php.net/allow-url-fopen
allow_url_fopen = On

; Whether to allow include/require to open URLs (like http:// or ftp://) as files.
; http://php.net/allow-url-include
allow_url_include = On`

The # problem always exists~~~

**Comment by DanielnetoDotCom** [comment]
@cdseoo you just did this?
did you restart apache after change?
does the problem persist?

**Comment by cdseoo** [comment]
@DanielnetoDotCom 
yes, I had resart apache after did those code, even restart all the proxmox5 server.
the problem still stubbornly~~~

**Comment by cdseoo** [comment]
I'd reinstall all the server.
The problem has been solved, please just close this matter.
