### ISSUE TITLE
Miscalculation of Time

### ISSUE THREAD

**Issue by angelawong** [DanielnetoDotCom/YouPHPTube#312]
I recently uploaded a video on January 2, 2018. Today is January 14, 2018. On the web page, it indicates that the video is only 1 week old. Is this a caching issue? If so, how can I fix it? If not, is there a miscalculation of time in the application? Please advise. Thank you.

**Comment by DanielnetoDotCom** [comment]
Hi @angelawong 

Should not have a miss calculation, your video is a 12 days old, probably will it go to 2 weeks after 14 days old

**Comment by angelawong** [comment]
Thank you @DanielnetoDotCom. You are right. The time just changed today (January 16, 2018) to indicate 2 weeks. Cheers.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
