### ISSUE TITLE
Problem with autoplay ... and categories ...

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#313]
I report a problem in the streamer autoplay ... If one chooses movies from a category, why does the autoplay take videos to other categories as well? For example if in a category, I have music and in another sermons ... and I would like to listen with autoplay only the music, how do I do it?

Then, to not open another ticket ...
How do I view the categories translated into multiple languages, according to the language you choose?

and yet another question ... how do you reduce languages in the menu on the right? type 2 - 3 - 4 languages only?

**Comment by tgd1973** [comment]
Hello again! 
How can I get the autoplay in order to binds  only the category already in play?

**Comment by DanielnetoDotCom** [comment]
This will need some development on it.
I am not sure how to do yet

**Comment by tgd1973** [comment]
I also wanted to notice a problem with the drop-down menu that is no longer accessible ...    not even in Choreme, even in Firefox 
![menu](https://user-images.githubusercontent.com/15127860/34949359-295a1014-fa10-11e7-8c9d-19be1524ec72.png)

**Comment by DanielnetoDotCom** [comment]
Thanks for notice it, I sent a fix

**Comment by tgd1973** [comment]
I would like to reopen this request for the AUTOPLAY ...
For me it's quite important because when  have a lot of material ... and not just music ... it becomes annoying ...
On the points:
1. to modify the autoplay criteria based on the category of where the video file is being played.
2. to insert in database a new entry type US, ES, IT ... that concerns the language of the video ... and use this tag for autoplay, in connection with the language chosen from the top menu, so that a user if choose the US language ... the autoplay, to not proposing music or sermons in other languages ... (this is to avoid for example if i have a sermon in a language, that the autoplay proposes another sermon in a language that not known).

For now, I thank the author of this important video portal ... who has written to bring praise to the Lord.

**Comment by DanielnetoDotCom** [comment]
@tgd1973 
Hi, those ideas are great, and you are right, the tags system are required for this app, and may be implemented in the future.
I agree with you it is important to be made
