### ISSUE TITLE
push notification for  livestream

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#314]
I would like to create notifications on facebook as soon as I start a live stream
and this file LiveTransmition.php seems to me the right one to make changes or I'm wrong?

**Comment by DanielnetoDotCom** [comment]
I think you could create it here https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/plugin/Live/on_publish.php
this is always called before a plublish

**Comment by mikweb2017** [comment]
ok thanks
