### ISSUE TITLE
Storing files in /tmp folder

### ISSUE THREAD

**Issue by set80** [DanielnetoDotCom/YouPHPTube#315]
It seems like Encoder is storing already encoded clips in /var/www/html/YouPHPTube-Encoder/videos/ and also in /tmp folder. Why is that? That makes my partitions full after a short time. Why isn't it removing it's files from both folders after encoding?

**Comment by DanielnetoDotCom** [comment]
PHP, Upload to the tmp dir, then the encoder copy it.
After the encode is done you can delete the queue log, it will also free some space

**Comment by gamersalpha** [comment]
hello, 

i m using raspberry with sdcard, so we really don't need create tmp files in the sdcard.


can u please explain me how works it ?
to change the tmp files with the same directory of the video ?

**Comment by hersche** [comment]
i think this has to be done in php.ini, means, in your system's configuration..

**Comment by hersche** [comment]
> Check upload_tmp_dir in php.ini. This is directory where PHP stores temporary files while uploading.

https://stackoverflow.com/questions/12531408/setting-php-tmp-dir-php-upload-not-working?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
