### ISSUE TITLE
Adsense Script Code box disappeared

### ISSUE THREAD

**Issue by k7n2g** [DanielnetoDotCom/YouPHPTube#316]
Hi  all,  my Script Code box for Adsense has disappeared this morning, have done a git pull its not appeared  can you tell me how to correct this please
https://www.screencast.com/t/Bdzs6TlTsdj

**Comment by DanielnetoDotCom** [comment]
Can you be more specific what Scrip Code Box for Adsense?
Where did you insert it.
or are you talking about a plugin?

**Comment by k7n2g** [comment]
Script Box in site configurations--  my Adsense code  was in Adsense for google box  the box has disappeared
See this in the screen cast  at  https://www.screencast.com/t/Bdzs6TlTsdj

For Google Analytics code: https://analytics.google.com
Leave blank for native code
Google Ad SenseFor Google AdSense code: https://www.google.com/adsense
Leave blank for native code

**Comment by DanielnetoDotCom** [comment]
I see

It is saved on database, it not suppose to desapear

**Comment by k7n2g** [comment]
Hi Daniel  how do i get it back please

**Comment by k7n2g** [comment]
Daniel have you changed the site to an adsense  plugin so this script code box no longer works



-----Original Message-----

**Comment by DanielnetoDotCom** [comment]
No I didn't change
The code should work, also I am using code on demo site

Em 16 de jan de 2018 17:59, "k7n2g" <notifications@github.com> escreveu:

**Comment by k7n2g** [comment]
okay Daniel sorted didn't realize the plugin was available missed your email among the 8000 plus on my return thanks Dave



-----Original Message-----

**Comment by gujarraju** [comment]
Hi Daniel,
Please fix my problem google ad sense in Firefox not showing and also google chrome  blank showing 
only my PC chrome showing but i check my friends systems not showing only blank showing please check attached file mypc and friend 
![my pc](https://user-images.githubusercontent.com/35865505/35470904-17ca3afe-036b-11e8-980d-3d36769ef160.jpg)
![friend](https://user-images.githubusercontent.com/35865505/35470906-21248d70-036b-11e8-86c5-7dc79a80cb40.jpg)

**Comment by DanielnetoDotCom** [comment]
How is the demo site on those computers?
they have any king ad block?

**Comment by gujarraju** [comment]
thanks working fine
there ad blocker know OK

but why not showing next button in player

**Comment by DanielnetoDotCom** [comment]
What next button?

Em 27 de jan de 2018 08:31, "gujarraju" <notifications@github.com> escreveu:

**Comment by hersche** [comment]
it looks like this is fixed as well..

i think, next button means the plugin.

because this is done: close. reopen if im wrong.
