### ISSUE TITLE
Provide LDAP login support

### ISSUE THREAD

**Issue by ilosamart** [DanielnetoDotCom/YouPHPTube#319]
It would be nice to have Active Directory (or LDAP) as a login mechanism.

I've made a little hack (that needs php-ldap module) to address the issue in file https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/objects/user.php#L312 as follows:

```php
    private function find($user, $pass, $mustBeactive = false, $encodedPass=false) {
        $foundUser = $this->mysqlFind($user, $pass, $mustBeactive, $encodedPass);
        if (!$foundUser) {
            $foundUser = $this->ldapFind($user, $pass);
        }
        return $foundUser;
    }

    private function ldapFind($user, $pass) {
        global $global;
        $info["count"] = 0;
        $user = $global['mysqli']->real_escape_string($user);
        $ds=ldap_connect("ldap://ldap.my.local");
        if ($ds) {
            $r=ldap_bind($ds, "$user@my.local", $pass);
            $sr=ldap_search($ds, "ou=my_ou,dc=my,dc=local", "samaccountname=$user");
            $info = ldap_get_entries($ds, $sr);
            ldap_close($ds);
        }
        if ($info["count"] > 0) {
            $userInfo = $info[0];
            // mb_convert_encoding é necessário, pois o Windows trabalha com outro encoding e o 
            // retorno do LDAP não é convertido corretamente
            $this->createUserIfNotExists($user, ''
                                        ,mb_convert_encoding($userInfo['displayname'][0], "UTF-8", "ISO-8859-1")
                                        , $userInfo['mail'][0]
                                        , ''
                                        , true);
            $user = $this->mysqlFind($user, false, true);
        } else {
            $user = false;
        }
        return $user;
    }

    private function mysqlFind($user, $pass, $mustBeactive = false, $encodedPass=false) {
        global $global;

        $user = $global['mysqli']->real_escape_string($user);
        $sql = "SELECT * FROM users WHERE user = '$user' ";

        if ($mustBeactive) {
            $sql .= " AND status = 'a' ";
        }

        if ($pass !== false) {
            if (!$encodedPass || $encodedPass === 'false') {
                $pass = md5($pass);
            }
            $sql .= " AND password = '$pass' ";
        }
        $sql .= " LIMIT 1";
        $res = $global['mysqli']->query($sql);

        if ($res) {
            $user = $res->fetch_assoc();
        } else {
            $user = false;
        }
        return $user;
    }

```

I could submit a PR if the solution aplies to your standard, obviously with some changes to accept server and root DN as parameters :smiley:

**Comment by DanielnetoDotCom** [comment]
This will be great :)

**Comment by tramasoli** [comment]
Ok then, I'll do the refactoring and send as PR. One thing, for this to work, I don't store the user password, I create a random one instead so the YouPHPTube-Encoder is affected by this change. In my case - as I'm only testing for now - I've changed the code that receives files from the encoder to accept data without a password.

Obviously this is suboptimal and unsuited to a production scenario, so if you care to discuss the possible 
solutions I would most appreciate.

I thought some kind of authentication between apps (not users) could be done so the encoder app itself could send data on behalf of the users. In that case the encoder would have no need to store users passwords.

I think the password need to exists only in the main app, as for LDAP/AD the passwords should never be saved anywhere.

What do you think?

Regards

**Comment by DanielnetoDotCom** [comment]
save a random password is a great Idea.
I have a ldap/AD plugin, and works that way, to save a random pass in case of login success. it is needed for encoder.

Just one question.
How the LDAP login is enabled or disabled in your YPT?
the plugin I have creates another form if you enable the plugin.

**Comment by tramasoli** [comment]
In my case, as I'm only testing the tool, I use the same form for ldap or MySQL login and the plug-in is always on. First I try ldap, if it is not successful, then I try the MySQL.

I thought that this is best as most end-users won't care if they're at ldap or local database. They don't need to know this. So what I suggest is a simple "on off" switch at settings page that enables or disabled the ldap integration.


As for the random password, this causes a problem for the encoder.
You see, after you login to the encoder with your password as 'senha', the YPT will successfully create a session. You'll then encoder your video et. al. So when the encoder sends the video it sends the username and the hashed original password to YPT.
So YPT tries to login on ldap with the hashed, which fails; then it tries to login in MySQL with that same hash but it differs from what is stored at the database because I storing a random string hash.
That's the current status.

**Comment by tramasoli** [comment]
Some spelling errors but I think you've got the idea.

Currently in my setup I've disabled the password check for videos coming from the encoder. That does the trick but is extremely insecure.

That's why my suggestion would be a pre-shared key between YPT and the encoder to do app auth and enable the encoder to send videos on behalf of the user, never storing the user's password on the encoder as is done now.

**Comment by patriclougheed** [comment]
@DanielnetoDotCom Does your plugin support OpenLDAP? I cannot afford to buy a plugin that only supports AD.

Great work on this software by the way! I have tested many video front-ends and this one is one of the best.

**Comment by DanielnetoDotCom** [comment]
It is made using ldap functions, so it is not exclusive for AD

**Comment by SubjectXXX** [comment]
So, this functionality was moved to the (payable) plugin as a whole?

**Comment by DanielnetoDotCom** [comment]
Hi, LDAP was always a paid plugin

**Comment by SubjectXXX** [comment]
I did buy your plugin but it doesnt work.

I have tried all different combinations of rdn to no avail..

Sad face..

**Comment by DanielnetoDotCom** [comment]
I see, the biggest problem is to find the correct RDN.

can you also please check your log file?

**Comment by SubjectXXX** [comment]
[17-Jan-2019 12:39:12 UTC] LDAP BIND fail: -1: Can't contact LDAP server

I'm using string ldap://dcv1ul.xxxx.si:3268

Connection works to Ad server works for sure, since I'm using some other software with same parameters. Also tried ldapsearch command with appropriate parameters, and it works.

**Comment by DanielnetoDotCom** [comment]
how is your LDAP parameters configuration?

**Comment by DanielnetoDotCom** [comment]
Looks like the problem is not your RDN, it is your connection with the server

**Comment by SubjectXXX** [comment]
Yes, I'm debugging that now, adding some more error messages to your code. Will let you know.

**Comment by DanielnetoDotCom** [comment]
if you can please screenshot your plugin parameters

**Comment by SubjectXXX** [comment]
![ldap yt](https://user-images.githubusercontent.com/2082595/51320509-611d3f00-1a60-11e9-8da9-8776b66f82a1.png)

**Comment by SubjectXXX** [comment]
Posted a bit more info then should, but ok..

**Comment by DanielnetoDotCom** [comment]
I guess on the server field you do not need the ldap:// and the port

**Comment by SubjectXXX** [comment]
http://php.net/manual/en/function.ldap-connect.php

Also, 3268 port is not default one I think, thus it should be set..

**Comment by SubjectXXX** [comment]
[17-Jan-2019 13:07:19 UTC] PHP Warning:  ldap_connect(): Could not create session handle: Bad parameter to an ldap routine in /var/www/html/YouPHPTube/plugin/LoginLDAP/LoginLDAP.php on line 53
[17-Jan-2019 13:07:19 UTC] PHP Warning:  ldap_errno() expects parameter 1 to be resource, boolean given in /var/www/html/YouPHPTube/plugin/LoginLDAP/LoginLDAP.php on line 65
[17-Jan-2019 13:07:19 UTC] PHP Warning:  ldap_error() expects parameter 1 to be resource, boolean given in /var/www/html/YouPHPTube/plugin/LoginLDAP/LoginLDAP.php on line 65
[17-Jan-2019 13:07:19 UTC] LDAP Connection fail: :  on: xxx.xxx.si:3268

ldap:// is needed.

Searching forward..

**Comment by DanielnetoDotCom** [comment]
I see, didn't put the port option, I am releasing a new version of this plugin with the port option

**Comment by SubjectXXX** [comment]
OK, found culprit.

ldap_connect can accept both versions, ldap_connect(ldap://hostname:port) or ldap_connect(hostname, port), so really no need for this fix :)

Culprit was, that I somehow managed to block my IP on AD controller. Sorry for wasting your time.

**Comment by SubjectXXX** [comment]
If you ever come around this plugin tho, a little optimization would be, that you connect to server, bind with service account (elevated account on AD) and then search ldap for correct user.

Some ADs have listings disabled for domain users without permissions.

**Comment by DanielnetoDotCom** [comment]
I see, anyway, I am releasing the version with the port option.

thanks for the feed back

**Comment by SubjectXXX** [comment]
Did you forget to update plugin's settings so we can add custom port?

It doesnt show for me..

![plugin](https://user-images.githubusercontent.com/2082595/51682401-a0f79f80-1fe7-11e9-9528-0a9b2da66524.png)

**Comment by SubjectXXX** [comment]
I had to disable the plugin, manually delete all the plugin's files and reupload the plugin to get it showing port textbox.

**Comment by DanielnetoDotCom** [comment]
thanks

**Comment by SaliC-re** [comment]
Hey,
is it possible to configure LDAPS (secure) with port 636?
If yes - how do we do that? I think it works with a keystore and certificate and so on

**Comment by DanielnetoDotCom** [comment]
Hi

I have never did for my self but I had costumers thas successfully did it.

that is what they wrote:

> For reference in case anyone else asks you, the certificate for the LDAP target server has to be placed somewhere on the server, and /etc/ldap/ldap.conf has to be configured to use it. I didn’t need to change your code at all.
> I used OpenSSL to connect to the server providing LDAPS and extract the certificate. You could also just log into the server itself and pull the cert that way. Here’s the script, replace “buls-ad01.barrette.wan” with the LDAPS server name:

`echo -n | openssl s_client -connect buls-ad01.barrette.wan:636 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ~/buls-ad01.barrette.wan.cer`

> Settings for the plugin:

![image](https://user-images.githubusercontent.com/18009293/80364078-a7fd0580-885b-11ea-9bbe-80598d242668.png)

> Ldap.conf (I added the last two lines):

![image](https://user-images.githubusercontent.com/18009293/80364115-b77c4e80-885b-11ea-8f31-e44714a756de.png)

> Documentation is in the comments of this article: https://www.php.net/manual/en/function.ldap-start-tls.php

**Comment by SaliC-re** [comment]
> Hi
> 
> I have never did for my self but I had costumers thas successfully did it.
> 
> that is what they wrote:
> 
> > For reference in case anyone else asks you, the certificate for the LDAP target server has to be placed somewhere on the server, and /etc/ldap/ldap.conf has to be configured to use it. I didn’t need to change your code at all.
> > I used OpenSSL to connect to the server providing LDAPS and extract the certificate. You could also just log into the server itself and pull the cert that way. Here’s the script, replace “buls-ad01.barrette.wan” with the LDAPS server name:
> 
> `echo -n | openssl s_client -connect buls-ad01.barrette.wan:636 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ~/buls-ad01.barrette.wan.cer`
> 
> > Settings for the plugin:
> 
> ![image](https://user-images.githubusercontent.com/18009293/80364078-a7fd0580-885b-11ea-9bbe-80598d242668.png)
> 
> > Ldap.conf (I added the last two lines):
> 
> ![image](https://user-images.githubusercontent.com/18009293/80364115-b77c4e80-885b-11ea-8f31-e44714a756de.png)
> 
> > Documentation is in the comments of this article: https://www.php.net/manual/en/function.ldap-start-tls.php

thanks for your fast answer - i'll try it :)
