### ISSUE TITLE
Thumbnails are not displayed.

### ISSUE THREAD

**Issue by okazgumi** [DanielnetoDotCom/YouPHPTube#32]
http://www.grassland.space/

**Comment by okazgumi** [comment]
when i wait anytime,displayed thumbnails.

**Comment by DanielnetoDotCom** [comment]
It is Ok from here
![image](https://cloud.githubusercontent.com/assets/18009293/26766812/dfe6b470-496e-11e7-8dc0-71b82b0e6264.png)

**Comment by okazgumi** [comment]
thanks.
