### ISSUE TITLE
Embend video link 

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#320]
I do not know what's different but on my instance of youphptube the Embend video link does not work anymoreand my problem on demo.youphptube.com works and on the top 2 instances even some ideas.
in log ist nothing.
![bildschirmfoto 2018-01-16 um 21 39 24](https://user-images.githubusercontent.com/30271757/35011402-3aec04bc-fb06-11e7-9d4e-b9d44d9af626.png)

**Comment by DanielnetoDotCom** [comment]
try to update your youtube-dl

**Comment by mikweb2017** [comment]
after update it does not work either
maybe a tables on the DB?
or permission problems?
![bildschirmfoto 2018-01-16 um 21 49 04](https://user-images.githubusercontent.com/30271757/35011770-a1c01d58-fb07-11e7-9cfa-df2391e25bbd.png)

**Comment by DanielnetoDotCom** [comment]
There is something on log file?
did you install youtube-dl on that way? https://github.com/DanielnetoDotCom/YouPHPTube/wiki/youdtube-dl-failed-to-extract-signature

this to use pip to install

**Comment by mikweb2017** [comment]
no in the logs I can not find anything I installed youtube-dl as per your tutorial. I do not understand the streams always on the same server

**Comment by mikweb2017** [comment]
![bildschirmfoto 2018-01-16 um 22 01 33](https://user-images.githubusercontent.com/30271757/35012116-da823b52-fb08-11e7-8f42-79a0183003e8.png)
and in my DB in the database are all but I do not sell anyone on the streamer ???

**Comment by DanielnetoDotCom** [comment]
for your youtube-dl did you use apt-get or pip?

**Comment by mikweb2017** [comment]
i use pip

**Comment by mikweb2017** [comment]
I do not know what happened now all the videos suddenly appeared
really crazy

**Comment by mikweb2017** [comment]
I do not know what happened now all the videos suddenly appeared really crazy
