### ISSUE TITLE
how to change the http video port to another

### ISSUE THREAD

**Issue by markusgraj** [DanielnetoDotCom/YouPHPTube#321]
hello, I have a question about how to change the http video port to another, 80 I have busy.
installed on Ubuntu 16.I would like to share for my family and I do not know which port to redirect on my router
Thank you Marek

**Comment by DanielnetoDotCom** [comment]
You will need to change apache Port.
Try Google for that

Em 17 de jan de 2018 00:09, "markusgraj" <notifications@github.com>
escreveu:

**Comment by hersche** [comment]
i think this can be seen as done, also withouth feedback and it's a point of apache itself. i close it out of that.
