### ISSUE TITLE
Problem with Encoder after SSL install - Streamer site not allowed

### ISSUE THREAD

**Issue by set80** [DanielnetoDotCom/YouPHPTube#322]
Hi. I've changed http to https  in /var/www/html/YouPHPTube/videos//configuration.php and /var/www/html/YouPHPTube-Encoder/videos//configuration.php  the same thing in Advanced configuration menu / Encoder URL. But while trying to log in to Encoder i get this error: This streamer site is not allowed. Everything was fine before SSL. What else should i modify?
![streamersite](https://user-images.githubusercontent.com/35449991/35045904-a71a4060-fb95-11e7-911e-e09e3921bcb2.jpg)
 
![streamersite1](https://user-images.githubusercontent.com/35449991/35046027-1279800a-fb96-11e7-88f4-0c9739acca83.jpg)

**Comment by DanielnetoDotCom** [comment]
You will need to check the streamer table and config table on encoder database

**Comment by set80** [comment]
Just like You said.... adding a little "s" helped a lot! ;)

![mysql](https://user-images.githubusercontent.com/35449991/35065638-13a09be8-fbce-11e7-9836-e5fde090d4e9.jpg)

**Comment by DanielnetoDotCom** [comment]
Great :)
