### ISSUE TITLE
new idea - Get Twitch user streaming direct on youPHPTUBE

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/YouPHPTube#323]
Hello, 
i m looking for a way to add twitch streamer directly in my youPHPTUBE !!!

i want create a user virtual who is a twith stream and when streaming start i want notification on my youPHPTUbe and want to show it on my youPHPTUB ?

what do u think

**Comment by DanielnetoDotCom** [comment]
I just add a support to twitch but youtube-dl could not capture the poster and time (maybe because it is live).
but you can add it manually

**Comment by gamersalpha** [comment]
Hello cool, 
how update ?

How add it manually ?


really thanks

**Comment by DanielnetoDotCom** [comment]
You will need to update your files

**Comment by gamersalpha** [comment]
I'm afraid there are problems after.
should I make a backup of the database + file after I put in joru and if no problem I stay like that

**Comment by gamersalpha** [comment]
ok so now i backup my files and database 

so i try to update youphptube and youphptube-encoder : 


but with github statu says to me no update ??



```
root@raspberrypi:/var/www/html/YouPHPTube# git status
Sur la branche master
Votre branche est à jour avec 'origin/master'.
Modifications qui ne seront pas validées :
  (utilisez "git add/rm <fichier>..." pour mettre à jour ce qui sera validé)
  (utilisez "git checkout -- <fichier>..." pour annuler les modifications dans la copie de travail)

        supprimé :        install/checkConfiguration.php
        supprimé :        install/database.sql
        supprimé :        install/index.php

Fichiers non suivis:
  (utilisez "git add <fichier>..." pour inclure dans ce qui sera validé)

        videos

aucune modification n'a été ajoutée à la validation (utilisez "git add" ou "git commit -a")
root@raspberrypi:/var/www/html/YouPHPTube# cd ..
root@raspberrypi:/var/www/html# cd YouPHPTube-Encoder/
root@raspberrypi:/var/www/html/YouPHPTube-Encoder# git status
Sur la branche master
Votre branche est à jour avec 'origin/master'.
Modifications qui ne seront pas validées :
  (utilisez "git add/rm <fichier>..." pour mettre à jour ce qui sera validé)
  (utilisez "git checkout -- <fichier>..." pour annuler les modifications dans la copie de travail)

        supprimé :        install/checkConfiguration.php
        supprimé :        install/database.sql
        supprimé :        install/index.php

Fichiers non suivis:
  (utilisez "git add <fichier>..." pour inclure dans ce qui sera validé)

        videos
aucune modification n'a été ajoutée à la validation (utilisez "git add" ou "git commit -a")
```

what do u think please ?

**Comment by DanielnetoDotCom** [comment]
a twitch link you will embed it not encode

**Comment by gamersalpha** [comment]
ok so now 
i added twitch channel with emded link, but i have black screen : 


![image](https://user-images.githubusercontent.com/32466950/35194810-c90196f2-feb9-11e7-9ccd-7a791ff983b5.png)

**Comment by DanielnetoDotCom** [comment]
can you please share the channel link here?
if you add the same channel on demo site does it work?

**Comment by gamersalpha** [comment]
ok i try to the demo site : 

the twitch stream : https://www.twitch.tv/killeuzz

Works with youphptube demo site : 

https://demo.youphptube.com/video/killeuzz-2018-01-22-11-51

https://demo.youphptube.com/video/5a6616e5863fe

so i have a problem with my conf

**Comment by gamersalpha** [comment]
ok i try to the demo site : 

the twitch stream : https://www.twitch.tv/killeuzz

Works with youphptube demo site : 

https://demo.youphptube.com/video/killeuzz-2018-01-22-11-51

https://demo.youphptube.com/video/5a6616e5863fe

so i have a problem with my conf

![image](https://user-images.githubusercontent.com/32466950/35233239-cda14970-ff9d-11e7-994b-4aa1f8e7b40e.png)

**Comment by gamersalpha** [comment]
ok i try to the demo site : 

the twitch stream : https://www.twitch.tv/killeuzz

Works with youphptube demo site : 

https://demo.youphptube.com/video/killeuzz-2018-01-22-11-51

https://demo.youphptube.com/video/5a6616e5863fe

so i have a problem with my conf
