### ISSUE TITLE
app Andrid problem

### ISSUE THREAD

**Issue by markusgraj** [DanielnetoDotCom/YouPHPTube#324]
hello, I have a problem with the app on android, I'm logic but there are no videos,
please help Marek

**Comment by DanielnetoDotCom** [comment]
Hi, First thing, make sure you update your Streamer and encoder site

**Comment by markusgraj** [comment]
I installed everything yesterday, I hope everything is new

**Comment by DanielnetoDotCom** [comment]
But if you use the demo site on your device is it working?

**Comment by markusgraj** [comment]
Wait, I'll check

**Comment by markusgraj** [comment]
yes everything is ok

**Comment by DanielnetoDotCom** [comment]
ok, make sure you have all new files on git master branch

**Comment by markusgraj** [comment]
I think something is wrong with Encoder, but I do not know how to do it

**Comment by DanielnetoDotCom** [comment]
try to remove and reinstall it

**Comment by markusgraj** [comment]
ok

**Comment by markusgraj** [comment]
thank you today, I will install everything again

**Comment by DanielnetoDotCom** [comment]
Sorry is it working now?

**Comment by markusgraj** [comment]
no, tomorrow will write what and how

**Comment by DanielnetoDotCom** [comment]
ok

**Comment by markusgraj** [comment]
Hi, I installed everything, and the local network is ok, outside there is nothing, the server I inserted in the DMZ router

**Comment by markusgraj** [comment]
ok closed subject everything is working thank you for help
