### ISSUE TITLE
New idea -  User Live

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/YouPHPTube#325]
Hello, 
what do u think about a user (created by defaut,) who get all link live who can add it  : 

like this a channel  live :
https://www.youtube.com/channel/UC4R8DWoMoI7CAwX8_LjQHig

what do u think ?

**Comment by DanielnetoDotCom** [comment]
I am not sure what you mean, but you can embed live links

**Comment by newtecnerd13** [comment]
What exactly is your objective,  I think if you put the blinders on,  tunnel vision...  You'll not get jumbled with other fundamentals that are causing confusion

**Comment by gamersalpha** [comment]
yes u right i m sorry
