### ISSUE TITLE
Android App 3 questions

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#326]
![whatsapp image 2018-01-21 at 15 35 27](https://user-images.githubusercontent.com/30271757/35195276-617b165e-fec1-11e7-82e2-f649aa2075cf.jpeg)
![whatsapp image 2018-01-21 at 15 35 39](https://user-images.githubusercontent.com/30271757/35195277-6192ded8-fec1-11e7-8d46-628c2110469c.jpeg)
![whatsapp image 2018-01-21 at 15 36 03](https://user-images.githubusercontent.com/30271757/35195278-61a8e8f4-fec1-11e7-9829-bd0c6331a47e.jpeg)

in this case admin and suscribed more times?

it seems that a photo backgraud is missing

if I could take the time in minutes instead of seconds

**Comment by newtecnerd13** [comment]
What is the time format,  possibly JPEG?

Sent from Yahoo Mail on Android 
 
  On Sun, Jan 21, 2018 at 8:43 AM, mikweb2017<notifications@github.com> wrote:   




in this case admin and suscribed more times?

it seems that a photo backgraud is missing

if I could take the time in minutes instead of seconds

**Comment by mikweb2017** [comment]
sorry I did not understand what you mean

**Comment by DanielnetoDotCom** [comment]
Hi mike, about the photo backgrund, was released yesterday an update for the app and for the streamer

**Comment by mikweb2017** [comment]
thanks, I saw now. strange but I had already updated app but I had to deinstall and install again

**Comment by mikweb2017** [comment]
now also the streming from the mobilephone     work great work!!!!!!!!!

**Comment by DanielnetoDotCom** [comment]
@mikweb2017 yes :)

**Comment by mikweb2017** [comment]
streaming and still beta phase if I turn the screen the streming stops and the flasch does not work, however, excellent work
