### ISSUE TITLE
interface improvement: comment system should not be displayed when disabled

### ISSUE THREAD

**Issue by ehk20** [DanielnetoDotCom/YouPHPTube#327]
This should be be relatively trivial and will make the end user interface tidier:

When "Authenticated users can comment videos" is set to "No" the comment system doesn't need to be displayed at all and should be hidden rather than displayed with various messages like 'disabled' and 'you can't comment on videos' (why display something the user won't be able to use!)

**Comment by DanielnetoDotCom** [comment]
@ehk20 Great and I agree, it will be fixed soon

**Comment by ehk20** [comment]
Wow, that was prompt follow-up. I've just pulled it and have the following follow-up: 
The comment section itself can probably also be hidden if there are no comments. ie. when the condition is  "No results found!" coupled with "comments not allowed" there is probably no reason to display the comments table either?

**Comment by DanielnetoDotCom** [comment]
Yes you right again
