### ISSUE TITLE
Problem with autostart of  player with plug: VideoResolutionSwitcher on

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#328]
I noticed that the play of any file does not start automatically if the VideoResolutionSwitcher plug is activated even if i choose in the Config Site "Autoplay Video on Load Page" ...
In this way it becomes very inconvenient to use this plug.
Please find a solution, otherwise, it is useless to make money in this plugs ...

**Comment by DanielnetoDotCom** [comment]
Hi @tgd1973 

On demo site we have the VideoResolutionSwitcher plugin and auto start active, and it is working fine.
can you share here your site URL?

**Comment by tgd1973** [comment]
I have already made a request in your chat https://easytube.club/  ... with my site ... but since you do not answer I have also written here ...

**Comment by tgd1973** [comment]
Do you refer to the language flags?  if you want to open the chat we save these words here ...

**Comment by DanielnetoDotCom** [comment]
Yes the  language flags
The chat may be with problems, I have answer you there since the begin

try to download fresh files and overwrite yours.
do not worry you wont loose videos and configurations

**Comment by tgd1973** [comment]
Anyway ... I used Beyond Compare to see all the new files you modified ...
and yes, I deleted the files from the locale folder  with the languages that do not interest me ... because I'm in Europe and I do not want to make a universal service ....

**Comment by DanielnetoDotCom** [comment]
you can delete the locale files you do not want, but you will need to keep one at least

**Comment by tgd1973** [comment]
I have 4 languages ... among which the English ... that I think is of reference and I'm doing it again, uploading the files downloaded tonight, from github ...

**Comment by DanielnetoDotCom** [comment]
@tgd1973 I may have found something, I will take a look;

**Comment by tgd1973** [comment]
if you register on my site I give you access as admin ...

**Comment by DanielnetoDotCom** [comment]
Hey, I sent a fix, please update and let me know

**Comment by tgd1973** [comment]
but which file is to be downloaded?

**Comment by DanielnetoDotCom** [comment]
view/include/video.php

**Comment by tgd1973** [comment]
OK. Thanks!
Now it works. 
The question can be considered resolved.
Thanks so much.

**Comment by DanielnetoDotCom** [comment]
Great

**Comment by tgd1973** [comment]
Another problem that I noticed at the plug is that at every video, the plug starts with the low resolution. On the one hand it's good because it saves the band but in theory it has to meorizing the selected position ... or maybe making some band measurements to choose the most suitable value. Can you do something?

**Comment by DanielnetoDotCom** [comment]
Yes, you right , this is something we notice, and will be improved in future versions

**Comment by tgd1973** [comment]
When will it be an update  ... I can  download the plugin again?

**Comment by DanielnetoDotCom** [comment]
sure will
