### ISSUE TITLE
how to delete comments

### ISSUE THREAD

**Issue by okazgumi** [DanielnetoDotCom/YouPHPTube#33]
I commented to video.
I had wanted to delete it.
what do I do?

**Comment by DanielnetoDotCom** [comment]
You cant, but we will add this function in next releases

**Comment by okazgumi** [comment]
thanks

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
