### ISSUE TITLE
Adding SSL

### ISSUE THREAD

**Issue by shadowlerawr** [DanielnetoDotCom/YouPHPTube#330]
How would i go about adding SSL?

**Comment by DanielnetoDotCom** [comment]
Usually I use lets encrypt https://letsencrypt.org/

**Comment by shadowlerawr** [comment]
That is what we plan on using is Lets Encrypt 

but is there anything i need to change in the config of YouPHPTube file or will it automatically port to it.

**Comment by DanielnetoDotCom** [comment]
you will need to change config file for streamer and encoder. and encoder streamer and configuration tables

**Comment by DanielnetoDotCom** [comment]
check this https://tutorials.youphptube.com/video/fix-youphptube-url-after-move-server-location-and-ip

**Comment by shadowlerawr** [comment]
it would be easier to have a Plugin to make things simple 

Also i did not understand that video tutorial to move to SSL

**Comment by DanielnetoDotCom** [comment]
SSL is the same as move the URL , you will need to edit some files

**Comment by shadowlerawr** [comment]
alright so we are using Lets Encrypt 
where do we point the webroot?
Nginx or Apache?

**Comment by DanielnetoDotCom** [comment]
depends what you want to use ssl, you will probably need to do on both

**Comment by shadowlerawr** [comment]
we got apache2 ssl to work it redirects to https://furrybroadcasting.stream 
now we are trying to configure the Encoder and it is not working

**Comment by SparksSkywere** [comment]
What files are all configured to HTTP? I have done the Main site and did some others, but which php files control the encoder site? 

@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
@shadowlerawr we need more details about the error

@SparksSkywere what do you mean files "control the encoder"?

**Comment by shadowlerawr** [comment]
@DanielnetoDotCom 

@SparksSkywere is my developer 

We have in stalled lets encrypt 
it now redirects to HTTPS now with Apache

But when we try to login to the encoder we get this error

![screenshot 196](https://user-images.githubusercontent.com/35711451/35301054-8c4d08f4-0058-11e8-9974-ac57b395d5d8.png)

**Comment by DanielnetoDotCom** [comment]
ok, check your encoder database 

![image](https://user-images.githubusercontent.com/18009293/35301226-bc3e07d2-0069-11e8-81d3-17009c1ed750.png)

**Comment by SparksSkywere** [comment]
@DanielnetoDotCom 

What i mean is what configuration file runs the URL of the encoder login page, so i can change the URL over to the new one "https://furrybroadcasting.stream/encoder"

**Comment by DanielnetoDotCom** [comment]
encoder/videos/configuration.php

**Comment by shadowlerawr** [comment]
<?php
$global['webSiteRootURL'] = 'https://furrybroadcasting.stream/encoder/';
$global['systemRootPath'] = '/var/www/html/encoder/';

$global['disableConfigurations'] = false;
$global['disableBulkEncode'] = false;

$mysqlHost = 'localhost';
$mysqlUser = '(redacted)';
$mysqlPass = '(redacted)';
$mysqlDatabase = 'stream_encode';

$global['allowed'] = array('mp4', 'avi', 'mov', 'mkv', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv');
/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';

**Comment by DanielnetoDotCom** [comment]
It seems correct but I just check your site and it is pointing to https://localhost.streamview/

**Comment by SparksSkywere** [comment]
@DanielnetoDotCom 

So today i checked out the encoders code (Post above) and if i changed any of the host names or user/password names it wouldn't load the website at all.

Which other files should i look at?

**Comment by shadowlerawr** [comment]
We have also found this error too when we try to restart Nginx 

![photo_2018-01-24_16-34-10](https://user-images.githubusercontent.com/35711451/35358397-886dd69c-0124-11e8-9128-24452ea76f4f.jpg)

**Comment by shadowlerawr** [comment]
this is also the error produced when trying to log into the encoder 

[24-Jan-2018 19:21:44 America/New_York] https://furrybroadcasting.stream/ == http://furrybroadcasting.stream/

**Comment by DanielnetoDotCom** [comment]
yes, nginx can not be on ssl. 
@shadowlerawr 
try to provide a http address for the on_publish, play and record.
I guess you can just remove the "s"

**Comment by shadowlerawr** [comment]
I  can restart Nginx now as well as Apache

Error: 

[24-Jan-2018 21:17:14 America/New_York] http://furrybroadcasting.stream/ == http://furrybroadcasting.stream/

![image](https://user-images.githubusercontent.com/35711451/35367400-257a64ba-014c-11e8-8617-97126e294cac.png)


This Image i still cannnot log into the encoder

**Comment by DanielnetoDotCom** [comment]
really strange, this error is new for me.
I can see your form. now to figure out this you will need to debug the code

**Comment by shadowlerawr** [comment]
how would i go about debugging the code?

**Comment by DanielnetoDotCom** [comment]
First try to inspect your browser.

![image](https://user-images.githubusercontent.com/18009293/35370135-beab212e-016a-11e8-89de-bb8c0964dd2a.png)

try to find any javascript error

then

try to use a var_dump($_POST); 

before this line https://github.com/DanielnetoDotCom/YouPHPTube/blob/8a5f7769c0dcdc8d122789021dcdbc147303461a/objects/login.json.php#L98

to see if your user was submited.
I have never seen this error before, I am not sure what it may be.

**Comment by shadowlerawr** [comment]
Threw the var_dump in the file and got this 

[25-Jan-2018 11:48:14 America/New_York] http://furrybroadcasting.stream/ == http://furrybroadcasting.stream/
[25-Jan-2018 11:48:15 America/New_York] PHP Warning:  Creating default object from empty value in /var/www/html/encoder/objects/Login.php on line 47
[25-Jan-2018 11:48:15 America/New_York] PHP Stack trace:
[25-Jan-2018 11:48:15 America/New_York] PHP   1. {main}() /var/www/html/encoder/objects/login.json.php:0
[25-Jan-2018 11:48:15 America/New_York] PHP   2. Login::run() /var/www/html/encoder/objects/login.json.php:15

**Comment by DanielnetoDotCom** [comment]
Looks like your error is on the encoder site now.

check [this ](https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Encoder-Error-We-could-not-found-your-streamer-site!)

**Comment by SparksSkywere** [comment]
@DanielnetoDotCom  I've been altering the code to the site and the main things ive done is changed over database codes from default to the stream sites code, example below.

![image](https://user-images.githubusercontent.com/34066194/35443811-43a21768-02a4-11e8-88d1-d6aaa521d7ac.png)

**Comment by DanielnetoDotCom** [comment]
@SparksSkywere and is it working?

**Comment by SparksSkywere** [comment]
I went searching for the php.ini but didnt find it, is it supposed to be in the "encoder.php" or something else? file wise

**Comment by SparksSkywere** [comment]
Aha found it, thanks, i will add it now

**Comment by SparksSkywere** [comment]
Alright, one was already on and i just put the other one on but now its stuck in processing.

**Comment by SparksSkywere** [comment]
@DanielnetoDotCom 

In the Index.php do i change all the HTTPS URL's over to the websites root URL? i started to edit it and wandering if it changes anything, below is what i see.

![image](https://user-images.githubusercontent.com/34066194/35473076-64289ce0-0372-11e8-9973-c0ce00c2e15e.png)

**Comment by DanielnetoDotCom** [comment]
I think you should make a clean installation, you not suppose tho change those files

**Comment by SparksSkywere** [comment]
Really? well ive reset them to default, changed to HTTPS and still nope

**Comment by shadowlerawr** [comment]
It seems that as we cannot get this to work 
we have reverted back to a snapshot before SSL 

and everything works 

it seems that everything is not supported via SSL 
as par video showing how to move ips

**Comment by DanielnetoDotCom** [comment]
the demo site uses ssl

**Comment by shadowlerawr** [comment]
What we are trying to do is make the streamer and encoder to stream over SSL 
like Discord 

because that is what you are spouse to do and it is the smart thing to do. 

so you can add SSL to the site witch when you connect to the browser that gives you a secure to the browser 

so how can we get the streamer and encoder to go over SSL

**Comment by DanielnetoDotCom** [comment]
@shadowlerawr sorry but I dont know what is missing in your installation. But is possible to install streamer and encoder on SSL. (check https://demo.youphptube.com/ and https://encoder.youphptube.com/)

**Comment by SparksSkywere** [comment]
Hello @DanielnetoDotCom sorry to bother you again, but ive redone a lot of the work and now majority is working, however an error which is being a real pain is "mysqli" screenshots below are from both logs of the main site and the encoder

![mainsite](https://user-images.githubusercontent.com/34066194/36617981-512cdf14-18e1-11e8-8c4c-54b3e929fa7b.JPG)
^Main site

![encodersite](https://user-images.githubusercontent.com/34066194/36617995-58a4289c-18e1-11e8-806a-b6bf70ec2baa.JPG)
^encoder

I have done Nginx, Apache2 and Mysql client are all on SSL and HTTPS is there but this error is causing the whole stream to still be in the same error 

![streamlogin](https://user-images.githubusercontent.com/34066194/36618069-a309296e-18e1-11e8-872d-508c8a4494b6.JPG)

**Comment by SparksSkywere** [comment]
Side Note, i also did the SQL Files too

![image](https://user-images.githubusercontent.com/34066194/36618111-ca12ed42-18e1-11e8-8713-668e2681ddbd.png)

**Comment by DanielnetoDotCom** [comment]
I dont know how you did this, but configuration table should be only 1 row.
Only the first row will be valid

**Comment by DanielnetoDotCom** [comment]
Also you can check your include_config.php file was not found, check what happened

**Comment by SparksSkywere** [comment]
So i changed the SQL file over to "https://furrybroadcasting.stream/" while i checked for the error, the following image is the line, this was not tampered with. What do you say?

![errorline](https://user-images.githubusercontent.com/34066194/36631364-764c7c36-196e-11e8-9ae6-82a3529ef6fd.PNG)

**Comment by DanielnetoDotCom** [comment]
What I mean about the 1 row configuration is because you have 2 rows on the table. you should have only one.

But the most important thing to check is why you got this error 
![image](https://user-images.githubusercontent.com/18009293/36631421-36345668-1956-11e8-88c0-1ca902bde064.png)

**Comment by SparksSkywere** [comment]
Well heres the SQL File now, if this is ok?

![image](https://user-images.githubusercontent.com/34066194/36631463-075a8a46-1970-11e8-977c-00c85bd99b96.png)

ps i have 2 computers, the windows 7 is the main and the windows 10 is a laptop i carry around with the same software as my rig.

**Comment by DanielnetoDotCom** [comment]
May be that is why.

We do not support Windows, we support linux only

**Comment by SparksSkywere** [comment]
Oh the servers on linux (ubuntu 16.04LTS), not windows, sorry if i confused you.

Well the SQL issue is baffling, but i will see what i can do

**Comment by SparksSkywere** [comment]
So i did many edits to main "localhost" to see what was being an issue, but no luck, however checking the error log after a quick flush and here is something new:

![image](https://user-images.githubusercontent.com/34066194/36632079-941042f6-1979-11e8-861a-ff788623d391.png)

**Comment by SparksSkywere** [comment]
Ok.. @DanielnetoDotCom this is getting more and more 

![image](https://user-images.githubusercontent.com/34066194/36632241-0be63c20-197c-11e8-8c6a-12917f23f201.png)

**Comment by SparksSkywere** [comment]
So i followed it to here but what do i need to type in?

![image](https://user-images.githubusercontent.com/34066194/36632275-9b85f8ac-197c-11e8-838b-2467d766dbb0.png)

**Comment by SparksSkywere** [comment]
@DanielnetoDotCom Fixed SQL but still this is the only error coming back on the encoder

![image](https://user-images.githubusercontent.com/34066194/36632672-0651decc-1981-11e8-9933-d53877b117f9.png)

**Comment by DanielnetoDotCom** [comment]
This is not an error, it is just a log

**Comment by SparksSkywere** [comment]
Its the issue. i have cleared all the other issues and problems but it is only something that is causing the login page to be denying. I cant determine where it is coming from, ive done the dump that was suggested higher up this post but still cant find where it is coming from, im checking down NGINX to see if it is coming internally. If you come up with anything @DanielnetoDotCom let me know :3

**Comment by DanielnetoDotCom** [comment]
I know what
you have mix the http and https what are you really using? update your encoder configuration database with the correct protocol 

![image](https://user-images.githubusercontent.com/18009293/36635317-5dc56fc4-1991-11e8-953d-0469d2c457af.png)

**Comment by SparksSkywere** [comment]
Im doing a reinstall of the encoder entirely, seeing if that works

**Comment by SparksSkywere** [comment]
Done and it was a SQL error all along

![image](https://user-images.githubusercontent.com/34066194/36635582-b542cce2-19af-11e8-86fb-12fcc714bd1f.png)

**Comment by DanielnetoDotCom** [comment]
is it working now?
looks like is working for me

**Comment by SparksSkywere** [comment]
Yep it is working now

**Comment by DanielnetoDotCom** [comment]
Great :)

**Comment by karvox** [comment]
Hi,

I follow all documentation on https://github.com/DanielnetoDotCom/YouPHPTube to configure, including SSL settings, but after I change all to SSL live stream not works. My browser show this error: 

Live Streaming really works over SSL?

![untitled](https://user-images.githubusercontent.com/7475131/38382678-f741b996-38e0-11e8-97de-2c5f66c9d3df.png)

**Comment by karvox** [comment]
My plugin configuration

![untitled](https://user-images.githubusercontent.com/7475131/38435896-8037ee0a-39a9-11e8-91f8-81e41cde91bc.png)

**Comment by karvox** [comment]
I change playerServer port to 444 and now works, what is wrong?

![untitled](https://user-images.githubusercontent.com/7475131/38444251-f8e04472-39c4-11e8-931a-feb2db0bdb3b.png)

**Comment by karvox** [comment]
Yes, its works! but the live not appears on streamer site still.

![untitled](https://user-images.githubusercontent.com/7475131/38503741-350b9af2-3be9-11e8-845f-989711bbf095.png)

**Comment by DanielnetoDotCom** [comment]
I saw this problem before

you probably has a misconfiguration on your stats/nginx.conf

look the demo page https://youphptube.com:444/stat

you suppose to have the key name instead the URL on the 

![image](https://user-images.githubusercontent.com/18009293/38504323-c4ae8330-3bea-11e8-81a7-3382c0c7bf72.png)

**Comment by karvox** [comment]
Hi Daniel, my URL and key are correctly, how the key appear on "live streams" field of image above?


![untitled](https://user-images.githubusercontent.com/7475131/38511909-10d75920-3c00-11e8-996f-6ccc9669f687.png)
![untitled1](https://user-images.githubusercontent.com/7475131/38511920-14c7c2e0-3c00-11e8-8a7d-c289eb9bdcd6.png)

**Comment by DanielnetoDotCom** [comment]
it is correct, 

but you should not have your URL here, it should be your key. that is how the script indentify the live stream
![image](https://user-images.githubusercontent.com/18009293/38512040-6e813230-3c00-11e8-84ec-f40b3250c361.png)


I think it is due your nginx.conf file

**Comment by karvox** [comment]
But where is the conf in nginx.conf file?

**Comment by karvox** [comment]
So, I want to know where to find this configuration (stats) inside nginx.conf. I compiled my nginx and the configuration file is in:

root@ubuntu:/usr/local/nginx/conf# ls
fastcgi.conf                     koi-utf                       nginx.conf               scgi_params.default
fastcgi.conf.default         koi-win                      nginx.conf.default   uwsgi_params
fastcgi_params               mime.types              nginx.conf.old         uwsgi_params.default
fastcgi_params.default   mime.types.default   scgi_params           win-utf

**Comment by DanielnetoDotCom** [comment]
my nginx file is on /usr/local/nginx/conf/nginx.conf

**Comment by ldgv** [comment]
Hi guys+
How I must to configure my nginx.conf for enable SSL?

Stream is working fine in http but I could enable SSL, when I enabled it stream no work.


This is my Nginx conf

    worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }

rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and$
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://xxxxxxxxx/plugin/Live/on_publish.php;
                            on_play http://xxxxxxxxx/plugin/Live/on_play.php;
                            on_record_done http://xxxxxxxxxx/plugin/Live/on_record_done.php;
                    }
            }
    }

    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
		    listen 9090;
		    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }   
            }

    }

Thanks

**Comment by karvox** [comment]
@ldgv here is my nginx conf file

worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            hls_fragment 10s;
                            on_publish http://evideo.ect.ufrn.br/plugin/Live/on_publish.php;
                            on_play http://evideo.ect.ufrn.br/plugin/Live/on_play.php;
                            on_record_done http://evideo.ect.ufrn.br/plugin/Live/on_record_done.php;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name evideo.ect.ufrn.br encoder-evideo.ect.ufrn.br;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"
                    location /stats {
                            stub_status;
                    }
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }

        	    listen 444 ssl; 
                    #server_name evideo.ect.ufrn.br;
                    ssl_certificate /etc/apache2/ssl/xxxxxxxxx.chain.crt;
                    ssl_certificate_key /etc/apache2/ssl/xxxxxxxx.key;


        }
    }

**Comment by DanielnetoDotCom** [comment]
Try to find help here https://github.com/arut/nginx-rtmp-module

And make sure why your live stream name is your URL, NOT the stream key

**Comment by ldgv** [comment]
No guys... Ive tried different thing... but always when I enabled ssl... My stream key is my plugin url.
Aswell I try to use the nginx conf of karvox but neither work with ssl...

My stream work but my stream counter is 0...

I tried change my nginx version and to 1.13.8 but neither work...

Anyway, thank you for your time...

**Comment by ldgv** [comment]
Guys... I problem is with apache server and the virtual hots

When I force ssl in my virtual hots my live streams show the error (show URL and no name of key)

Now Ive enabled my SSL but without force SSL.... Site is in https with no forced... Now my 444/stat show my key and my site couter show my stream... But no Ive another problem... hehe...

The stream no is workin in my site...


This is my apache conf for my virtual host for my youphptube site


Http


<VirtualHost *:80>
	
	ServerName xxxxxx.com
    ServerAlias www.xxxxxx.com
	
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/mysite
	
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
	
	
RewriteEngine on
RewriteCond %{SERVER_NAME} =xxxxxxxxxx.com [OR]
RewriteCond %{SERVER_NAME} =www.xxxxxx.com
**#RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]** 
THIS IS THE FORCE TO SSL


<Directory /var/www/mysite>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
</Directory>

</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet


And for my SSL .conf is


<IfModule mod_ssl.c>
<VirtualHost *:443>
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/mysite
<Directory /var/www/mysite>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
</Directory>
	
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

ServerName lookymore.gq
Include /etc/letsencrypt/options-ssl-apache.conf
ServerAlias www.xxxxxxxxxxxxxxx.com
SSLCertificateFile /etc/letsencrypt/live/xxxxxxxxxxx.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/xxxxxxxxxxx.com/privkey.pem

</VirtualHost>
</IfModule>

**Comment by DanielnetoDotCom** [comment]
I dont understand well what you wrote.

but your NGINX https is not working here https://www.lookymore.gq:444/

**Comment by ldgv** [comment]
> I dont understand well what you wrote.
> 
> but your NGINX https is not working here https://www.lookymore.gq:444/

Is working in https://lookymore.gq:444/stat

But Ive not enblaed my redirection to internet

Try again please

**Comment by DanielnetoDotCom** [comment]
it is working, your code should be working as well.

If you want, screenshot your live plugin parameters and your live screen

**Comment by ldgv** [comment]
> it is working, your code should be working as well.
> 
> If you want, screenshot your live plugin parameters and your live screen

Ok
My plugin conf
https://footo.gq/image/ieir

Problem. i think is when SSL is forced for rewrite....

So, how to enable SSL? So that the site always working on SSL

**Comment by DanielnetoDotCom** [comment]
Looks like all fine for me, but this question is not regarding youphptube.

try to google to figure it out

**Comment by ldgv** [comment]
Ok, you for your time.

**Comment by hosnyegy** [comment]
my dear Daniel 
I have a problem after installing the security certificate https://koora4k.com:8443/stat it does not work

**Comment by DanielnetoDotCom** [comment]
> my dear Daniel
> I have a problem after installing the security certificate https://koora4k.com:8443/stat it does not work

Your nginx seems to not  be installed or running

**Comment by hosnyegy** [comment]
I installed it with the same steps https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server and it worked for me, but when I deactivated the security certificate, it stopped working

**Comment by DanielnetoDotCom** [comment]
What do you mean "deactivated the security certificate"?

the SSL is strongly recommended to be installed

for my self I use letsencrypt

**Comment by hosnyegy** [comment]
I mean, after installing ssl, the problem occurred

**Comment by hosnyegy** [comment]
These are the errors 
[2022-01-10 19:26:27] Time Elapsed: 0.00002 seconds - Starting try to get URL https://koora4k.com:8443/stat
[2022-01-10 19:26:27] Time Elapsed: 0.00013 seconds - url_get_contents start timeout=2

Warning: file_get_contents(https://koora4k.com:8443/stat): failed to open stream: Connection refused in /var/www/html/AVideo/plugin/Live/test.php on line 54
[2022-01-10 19:26:27] Time Elapsed: 0.00083 seconds - file_get_contents::
[2022-01-10 19:26:27] Time Elapsed: 0.00084 seconds - file_get_contents fail return an empty content
[2022-01-10 19:26:27] Time Elapsed: 0.00085 seconds - FAIL
[2022-01-10 19:26:27] Time Elapsed: 0.00085 seconds - Finish try to get URL

**Comment by hosnyegy** [comment]
Sorry dear if I bothered you

**Comment by DanielnetoDotCom** [comment]
your Nginx seems to not even be running

try to stop and start it

`sudo /usr/local/nginx/sbin/nginx -s stop `

than

`sudo /usr/local/nginx/sbin/nginx`

**Comment by hosnyegy** [comment]
same problem not working

**Comment by hosnyegy** [comment]
Can my friend send you the server data to help me?

**Comment by DanielnetoDotCom** [comment]
share the output when you start nginx.

**Comment by hosnyegy** [comment]
Sorry my friend, I didn't understand and excuse me because I am weak in English

**Comment by hosnyegy** [comment]
Can I send you the login information for the server? for help me

**Comment by DanielnetoDotCom** [comment]
Hi, you can hire me for support so I can try to find the issue (not guaranteed)

We do not offer partial installations because it is a lot easier to make a clean install than find bugs on preinstalled systems.
If you really want a partial installation we need to charge per hour (50 USD/hour) and there is no guarantee it will work.
Basic installation costs 70 USD, but we require a clean server for that.  To make a clean installation we require the following:
The operational system you will need to provide a clean Ubuntu 20.04 (VPS or dedicated) shared servers do not work.
Please make sure you do NOT install any kind of control panel (No Plesk, cPanel, etc)

about the server requirements please check this https://github.com/WWBN/AVideo/wiki/AVideo-Platform-Hardware-Requirements  

For direct support (email or zoom meeting with a screen share) you can hire me per hour 50 USD /hour. we just schedule a time and I will be with you online.

**Comment by hosnyegy** [comment]
thanks sir
