### ISSUE TITLE
Update and got a Blank Screen

### ISSUE THREAD

**Issue by DanielnetoDotCom** [DanielnetoDotCom/YouPHPTube#332]
If you Update and got a Blank Screen or something like you could not found class Object

It happened because we had to change the Object Class to make it compatible with PHP 7.2

to make your system go back to work now, uncoment this line: 

`abstract class Object extends ObjectYPT{};`

https://github.com/DanielnetoDotCom/YouPHPTube/blob/8a5f7769c0dcdc8d122789021dcdbc147303461a/objects/Object.php#L206

 fix this error you will  need to download all plugins you have again, just replace the files on your server for the ones you just got.

then you are ready to PHP 7.2

**Comment by abamilod** [comment]
Do we need to replace the free plugin also?

**Comment by DanielnetoDotCom** [comment]
Yes you will need to replace all paid plugins

Em 26 de jan de 2018 00:58, "Ayub Job" <notifications@github.com> escreveu:

Do we need to replace the free plugin also?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DanielnetoDotCom/YouPHPTube/issues/332#issuecomment-360678100>,
or mute the thread

**Comment by hersche** [comment]
can we automate this by checking the php-version?

**Comment by DanielnetoDotCom** [comment]
I think this is fixed already, all new installations have the right files and plugins.
it can be closed :)
