### ISSUE TITLE
Support Environment Variables

### ISSUE THREAD

**Issue by sorvis** [DanielnetoDotCom/YouPHPTube#334]
What are the supported environment variables? Is there a wiki page for this or can we start one? If we want to start a wiki page I would be glad to document the variables I know about.

Thank you

**Comment by DanielnetoDotCom** [comment]
@sorvis I can start a wiki, But I think you will not be able to edit. we can do that. I will start the variables I can remember here and you can complete or suggest something here. once we have enough information I will transfer for a wiki

## On videos/configuration.php file
$global['webSiteRootURL'] = The Installation site URL
$global['systemRootPath'] = The Path for the root


## on objects/include_configuration.php file
$global['mysqli'] mysql connection variable

**Comment by sorvis** [comment]
@DanielnetoDotCom 

Here are some I had from a docker-compose file I'm trying to create:

DB_HOST=mysql     <--verified seem to work
DB_PORT=3306     <--verified seem to work
DB_USER=root     <--verified seem to work
DB_PASSWORD=your_db_passwd      <--verified seem to work
DOMAIN=localhost
ADMIN_EMAIL=some_email
ADMIN_PASSWORD=test123
LANG=en

I'm a bit dubious about the ADMIN fields because they didn't seem to work. I found them inside of [this docker file](https://github.com/leejoneshane/docker-youphptube/blob/master/Dockerfile).

**Comment by DanielnetoDotCom** [comment]
@sorvis 
I do not know much about docker (but I like the idea).
Also I do not know where those variables came from :(

**Comment by sorvis** [comment]
@DanielnetoDotCom I figured out where those variables came from. They are from @leejoneshane repository. Tonight I forked your repository and I'm going to work on putting in leejoneshane's files then I can write a docker-compose file for them and we can do a pull request then if you wish.

**Comment by DanielnetoDotCom** [comment]
@sorvis I will love to do it :)
