### ISSUE TITLE
Android Upload  error

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#336]
![whatsapp image 2018-01-28 at 13 19 58](https://user-images.githubusercontent.com/30271757/35486536-7ae12404-046f-11e8-86e1-ecbbfb110476.jpeg)

 i try upload  550 MB   video  but  after  30%   i have a Error.

logs  is nothing

**Comment by DanielnetoDotCom** [comment]
@mikweb2017 
Please make sure you have all files up to date, and also check the log files on the site

**Comment by mikweb2017** [comment]
@DanielnetoDotCom 

i have  already  update  but  not  work for me big video  and  logs  is nothing

**Comment by DanielnetoDotCom** [comment]
@mikweb2017 
if you try with another (small) file, does it work? 
can you email me the credentials and the site you are using to upload this video?
I will try to see what happened

**Comment by mikweb2017** [comment]
in Server error Log 

[Mon Jan 29 01:38:03.157869 2018] [fcgid:warn] [pid 2881:tid 140665967056640] [client 81.169.216.90:44856] mod_fcgid: HTTP request length 134218822 (so far) exceeds MaxRequestLen (134217728)

**Comment by mikweb2017** [comment]
i have fixed and jet work fine

**Comment by DanielnetoDotCom** [comment]
Great :)
