### ISSUE TITLE
[Feature Request] Password protected streams

### ISSUE THREAD

**Issue by JonnyTech** [DanielnetoDotCom/YouPHPTube#339]
I cannot find a way to host password protected (live) streams - is this on the roadmap?

**Comment by DanielnetoDotCom** [comment]
You do not need this, the rtmp URL have a "p=protectionKey"

![image](https://user-images.githubusercontent.com/18009293/35507430-805e26d2-04cb-11e8-9a6e-5f469cb4446e.png)

**Comment by JonnyTech** [comment]
Ah, thank you, I shall try that.
