### ISSUE TITLE
SSLcommunication　settings

### ISSUE THREAD

**Issue by okazgumi** [DanielnetoDotCom/YouPHPTube#34]
I want to set SSL.
what do I do?

**Comment by DanielnetoDotCom** [comment]
For YouPHPTube site we use https://certbot.eff.org/
Very easy to install.
After that you will need to change videos/configuration.php line:
`$global['webSiteRootURL'] = '**http**://www.yourSite.com/';`
To
`$global['webSiteRootURL'] = '**https**://www.yourSite.com/';`

**Comment by okazgumi** [comment]
websiterootURL isnot in configuration.php...

**Comment by DanielnetoDotCom** [comment]
Must be

**Comment by okazgumi** [comment]
![configno](https://cloud.githubusercontent.com/assets/29045007/26788531/70ba4d84-4a48-11e7-8512-1429232312f7.png)

**Comment by okazgumi** [comment]
sorry. I found...
