### ISSUE TITLE
Streaming Offline Photo

### ISSUE THREAD

**Issue by DemonRem** [DanielnetoDotCom/YouPHPTube#340]
when will be streaming offline photo function?

can you tell ETA?

**Comment by DanielnetoDotCom** [comment]
I no sure yet.
I am developing something else now.

**Comment by hersche** [comment]
what does "streaming offline photo" means exactly?

youphptube is a website, so you generally have to be online.

streaming a photo is usual loading a picture one time... 

can you explain the idea a bit more?

**Comment by DemonRem** [comment]
Look
![default](https://user-images.githubusercontent.com/29927382/40904234-b6805f58-67e2-11e8-8fc6-3b19a8f7fd6b.png)

THE PC Is On Hebrew so i translate the buttons and the screen for you to see the idea

**Comment by DemonRem** [comment]
Yes but for stream not video
