### ISSUE TITLE
why i can' upload folder with format .mkv

### ISSUE THREAD

**Issue by ardidwisaputra** [DanielnetoDotCom/YouPHPTube#341]
why i can' upload folder with format .mkv

**Comment by DanielnetoDotCom** [comment]
Actually you can!
What was the problem?

Em 31 de jan de 2018 05:08, "ardidwisaputra" <notifications@github.com>
escreveu:

**Comment by ardidwisaputra** [comment]
i cant share .mkv file with Encoder

**Comment by ardidwisaputra** [comment]
the file does not wont appear on streaming site 

but file with format mp4 can show on streaming site

**Comment by DanielnetoDotCom** [comment]
to direct upload you can only send MP4.
mkv you only can send to encoder

**Comment by ardidwisaputra** [comment]
how to set encoder to share mkv file

**Comment by DanielnetoDotCom** [comment]
Hi

What do you mean share mkv?

**Comment by ardidwisaputra** [comment]
Thanks for you help

Pada tanggal Rab, 31 Jan 2018 16.00 YouPHPTube <notifications@github.com
menulis:
