### ISSUE TITLE
Enconder install it never ends

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#342]
![encoder](https://user-images.githubusercontent.com/30271757/35672466-f9c9356e-073e-11e8-8b90-d3c47896e878.PNG)

I had to resistallre my server but I can not install encoder there are no errors on the server any idea

**Comment by mikweb2017** [comment]
i have  install but
wiht PHP 7.2.1  dont work for me 
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /var/www/vhosts/beta.mikweb.eu/httpdocs/YouPHPTube-Encoder/objects/Object.php on line 8

work fine  wiht PHP 7.1.13

**Comment by DanielnetoDotCom** [comment]
@mikweb2017 try this https://github.com/DanielnetoDotCom/YouPHPTube/issues/332

**Comment by mikweb2017** [comment]
thanks
