### ISSUE TITLE
Support for tags and subcategories

### ISSUE THREAD

**Issue by fwn0** [DanielnetoDotCom/YouPHPTube#343]
I would like a bit sort videos after tags, for example metal, ambient, post-rock.
Is it possible to create a new subcategory some like for examle: Music/MusicVideos/Genre/Industrial or another example: Music/Audio/Artist ?

**Comment by DanielnetoDotCom** [comment]
Yes those are things we agree it needs and may be included in the future

**Comment by hersche** [comment]
subcategories are possible since a moment :)
