### ISSUE TITLE
New feature. Resolution switcher plugin default quality configuration

### ISSUE THREAD

**Issue by tvmanus** [DanielnetoDotCom/YouPHPTube#344]
I got the resolution switcher plugin from the store and found that it defaults to low option. Would it be possible to introduce a config parameter on the "Plugins" page which would allow to set default option to something else. 
Or at least recommend a supported way to make this change manually, I'd like to set the default option to HD and let users to opt for lower quality if the experience difficulties with streaming in HD

**Comment by DanielnetoDotCom** [comment]
This improve will come soon, and if it is on the plugin you will get a free update

**Comment by cbuchmannNM** [comment]
Hello,
is there any update regarding this feature?
Also I would be interested, if the quality could be automatically determined by the bandwith of the user.

**Comment by DanielnetoDotCom** [comment]
Not, yet sorry

**Comment by cbuchmannNM** [comment]
I've used the "Head Code" in the Script Code from the Site Configuration to change the default quality to every video.
`<script>
    window.onload = function () {
        videojs('mainVideo').currentResolution('HD');
    }
</script>`

Maybe it will help someone.

**Comment by DanielnetoDotCom** [comment]
thanks

**Comment by cbuchmannNM** [comment]
As it turns out it works only on some videos.
When called manually `videojs('mainVideo').currentResolution('HD');` the videos are in HD Quality again.

On the videos which are not working, I get the following error:

> videojs(...).currentResolution is not a function [...] at window.onload

Which indicates that the function is not loaded yet. Even though I can call it in the head section on other videos flawlessly.

**Comment by cbuchmannNM** [comment]
I've tested more with the custom header.
Just half of the videos get played in hd quality with the change.
If I open a video site with the "open in a new tab" it always works and will be changed default to HD Quality.
Not an Issue, just observations.

**Comment by cbuchmannNM** [comment]
Since update 2c10e90 the Javascript is loading on every single site.
I just have to wait a second to load the whole site. After pressing the "Big Play Button" the video loads directly in the choosen Quality.

**Comment by DanielnetoDotCom** [comment]
@cbuchmannNM are you saying now the script is memorizing the last used resolution?
I am not aware of it.

**Comment by cbuchmannNM** [comment]
No, it is unfortunately not.
The earlier mention script in the header section is working now properly on every video.
It is loading for all users a default resolution, before playing the video.
I'm writing mainly for documentation and for others.

**Comment by nospi** [comment]
Much appreciated @cbuchmannNM! Been looking for a solution on this myself. If I come across anything interesting I'll add it here.

**Comment by SaliC-re** [comment]
> Much appreciated @cbuchmannNM! Been looking for a solution on this myself. If I come across anything interesting I'll add it here.

you got something?
