### ISSUE TITLE
cache plugin

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#345]
can you explain to me how to function the cache plugin if the active I have a strange phenomenon with login logout if I click on the homepage then I have to Login again?

**Comment by DanielnetoDotCom** [comment]
Hi @mikweb2017 

It not suppose to happened, I want to investigate it.

I put on wiki some information:

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Cache-Plugin

also please confirm if this parameter is unchecked: enableCacheForLoggedUsers

![image](https://user-images.githubusercontent.com/18009293/35727655-99c7c4f6-07e7-11e8-8cba-da8abc637a64.png)

**Comment by mikweb2017** [comment]
ok  i have  this  unchecked and work fine
