### ISSUE TITLE
suggestion: page dwell for view counter

### ISSUE THREAD

**Issue by ehk20** [DanielnetoDotCom/YouPHPTube#346]
Not sure if this is the exact terminology for it, but for embedded videos would it be possible to have (possibly user configurable) dwell timer to improve the view counter since we can't pick up the play action on these videos? ie. page view only 'counts' after the page has been loaded for a certain amount of time. While not precise this would be better than counting every page load, as it is more probable that user dwelling on the page is viewing the video than someone simply loading it. 

Note: The configurability is more a 'how long does a video have to play before it counts as viewed' idea. Ours are an hour long in general, so I may want quite a long wait.

**Comment by DanielnetoDotCom** [comment]
@ehk20 .
I dont know what version you are running. recently we release a version where the video counts only when it is played.

Except the embed videos, what counts when the page loads

**Comment by ehk20** [comment]
We’re on the latest version and perhaps I should have made this clearer: this suggestion was specifically to do with embedded video counts since the page count is so inaccurate. 

Espen

**Comment by DanielnetoDotCom** [comment]
Understood, I will count on this idea for a finally solution.

Thanks any way :)
