### ISSUE TITLE
Some questions/suggestions

### ISSUE THREAD

**Issue by niedon** [DanielnetoDotCom/YouPHPTube#347]
Hi, I have been testing your work and it's awesome, congratulations. I have some things to ask:

Would it be useful to upload videos with specific metadata, so that metadata "autofills" the fields of Description, Category, etc?

I think that tag function would be so useful, not only for SEO but for the search inside the web too.

Is there any way to set a link to a random video, or that will be a future upgrade?

Thanks!

**Comment by DanielnetoDotCom** [comment]
@niedon 

> Would it be useful to upload videos with specific metadata, so that metadata "autofills" the fields of Description, Category, etc?

You mean put this on encoder?
 
> I think that tag function would be so useful, not only for SEO but for the search inside the web too.

Yeah, we are planning to include this feature on videos

> Is there any way to set a link to a random video, or that will be a future upgrade?

The next version 4.8, probably, we will have an option to set up an option to mark a video as a "suggested", the suggested videos will randomly appear on the main page

**Comment by niedon** [comment]
About metadata: I dont know, maybe in the encoder or in myphptube itself, it's just an idea in case you think it's useful somehow.

About the other 2 questions: Okay, thank you!

**Comment by diroots** [comment]
do you know by when the tags feature will be available? in the next release? in far future releases? not before 6 month?

**Comment by diroots** [comment]
and will it be available in the core youphptube, as a free included plugin or as a paid plugin?

**Comment by DanielnetoDotCom** [comment]
@diroots I am not sure yet. But all new features follows the funding project https://easytube.club/#funding

Also we just include the Tags feature there

**Comment by niedon** [comment]
Hello again, how can I update YouPHPTube on Windows? And will I lose the user/comment/likes data? Thanks!

**Comment by DanielnetoDotCom** [comment]
Hi, not suppose to loose anything. jut overwrite the files and run the update

**Comment by manish-ip** [comment]
Hello
I have some custom requirement and want to implement all those things. Just I want to know is there any way to listen to the event, for example, like, subscribe, comment, upload etc. so that I can add some additional functionality to capturing the above event/hook. Is there such event available  ??

Thanks!

**Comment by DanielnetoDotCom** [comment]
Hi

If you figure out how to create a plugin you may use some methods.

```
afterNewVideo($videos_id)
    
afterNewComment($comments_id)
    
afterNewResponse($comments_id)
```

https://github.com/DanielnetoDotCom/YouPHPTube/blob/c1dd04dff8875e7343ce98489b10862ef5b9248e/plugin/Plugin.abstract.php#L78
