### ISSUE TITLE
Change owner / user of videos

### ISSUE THREAD

**Issue by diroots** [DanielnetoDotCom/YouPHPTube#350]
Hi. 
Actually, changing owner of a video is not possible through the interface. 
Is it safe to change the user of a video directly in the database? 
I've seen a users_id column in the 'videos' table. changing user'id here is ok? 
I tried to change the value for a video, but when doing this, the video, wich was ok ith the old user (video info, video lenght, thumbnails,...) is ko in the new user's video list. 

Is it needed to change the user's information anywhere else for it to work ? if yes, can you tell us where? 

Many thanks in advance for this confirmation

**Comment by DanielnetoDotCom** [comment]
I think you can change users_id with no problem on the database

**Comment by diroots** [comment]
hi, thanks for this prompt answer, indeed, only by changing this value it's ok! i just tried on a corrupted video.
