### ISSUE TITLE
Request new option: "Embedded Channel" ...

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#351]
Thanks again to the author of this platform that becomes more and more useful to everyone. 
My suggestion: Since you have created a separate menu with the channels:
if you can complete this menu with an emmbed code for each separate channel, so that a church can  have only their channel with their videos in an iframe, so in this way can show them their archive in a simpler way ... to understand what I want, you can see an example of my "friend" who has already done the work on another private platform that unfortunately is not available to the public ...
http://archives.bisericilive.com/gallery?cid=bisericamanasturro
It would be also  useful to be able to choose the sequence of videos from the newest to the oldest or on the contrary ...

**Comment by DanielnetoDotCom** [comment]
Understood I will think about it
