### ISSUE TITLE
new Funkion  like youtube Community (yotube channels)

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#352]
it would be instigable to create a database with all the active streamer in order to create a commnuy like youtube.

in the sense that for each new installation it is that you request freely if you want to join the community (Dabase with all the Streamers)

in order to have the possibility to see other channels and to give the possibility to make known the contents quickly.

I do not know if I explained myself well

**Comment by DanielnetoDotCom** [comment]
Sooo great Idea.

Like a site center, to distribute content.

**Comment by hersche** [comment]
i am not shure if i get it right, but meanwhile we have channels and a overview - is this done already or is this about a extended feature?

**Comment by hersche** [comment]
i close it out of inactivity and because i think it's done.. reopen when i am wrong.
