### ISSUE TITLE
S3 Integration

### ISSUE THREAD

**Issue by alonbl92456** [DanielnetoDotCom/YouPHPTube#353]
Hey, 
really cool project!!!
is there any way to use amazon s3 as a storage backend for all of the videos ?

**Comment by DanielnetoDotCom** [comment]
I really want to do that, I have tried but I fell like s3 had a slow response

**Comment by domainoverflow** [comment]
Hi @DanielnetoDotCom , great project, congrats ! muito legal mesmo.
I was wondering ( like @alonbl92456 ) what would it take for a S3 integration ? 
Maybe I can help with the S3 slowness just so you assess the possibility ?
regardless of S3, thanks for making YPT !
best,
s

**Comment by DanielnetoDotCom** [comment]
@domainoverflow Sorry for late answer, how can you help with S3 slowness?

**Comment by domainoverflow** [comment]
no worries. I work in a heavily used cdn/s3 context and have optmized S3 
in many different ways -Perhaps if you describe details of your slowness 
experience... I might be able to assist. Feel free to reply here or 
directly ( Eu falo Português :-) ... thanks for making youTubePHP, it's 
really neat.
Sergio

**Comment by DanielnetoDotCom** [comment]
Hi @domainoverflow 
Do you use s3fs? 
Is your server dedicated or a VM?
Do you know if we can use s3fs on OpenVZ VM?

**Comment by domainoverflow** [comment]
Hi @DanielNetoDotCom,

multiple dedicated + DNS load balanced CDNs by regions.  We have used 
S3FS and it can be very efficient with -small- files but any sort of 
attribute change or file change --will-- cause the file to be reuploaded 
( S3FS it is -not- a true file system ), although it supports partial 
download in distinct blocks, in our experience it is great for small 
files but not efficient for larger files on a stream context ( or 
encoding ). Why not an EBS mounted with a matching AWS region, -with- a 
load balanced CDN ?? Keep in mind it's been a while so you might want to 
double check with AWS, maybe they have improved it by now... txs,s

**Comment by DanielnetoDotCom** [comment]
I decide to use the S2 SDK instead S3FS. After implement is easier to configure

**Comment by waqasbelushi** [comment]
Hi DanielnetoDotCom thanks For making this script to open source
my English is not good but i want to say same thing about this topic 
I'm try this aws-sdk, s3fs, goofys, fuse, 
s3fs do the job but very slow
goofys a high-performance, POSIX-ish Amazon S3 file system written in Go 
in my opinion goofys is best fast read and write but i'm facing 1 problem with goofys 
if i upload video without ffmeg video upload successfully 
if i use ffmeg gating [mp4 @ 0x5583d4e896c0] Starting second pass: moving the moov atom to the beginning of the file
Error writing trailer of /s3/test/ko12.mp4: Operation not supported
frame= 758 fps=0.0 q=-1.0 Lsize= 3194kB time=00:00:30.27 bitrate= 864.2kbits/s speed= 672x
video:2719kB audio:475kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.001468%

**Comment by DanielnetoDotCom** [comment]
Hi, I have a S3 plugin for YPT already, it will be on the market soon (50 USD)

I use SDK and it works great!

here how to use it

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Use-AWS-S3-on-YouPHPTube

If some one wants this plugin now, make a direct contact with me developer@youphptube.com

**Comment by domainoverflow** [comment]
Would you be able to share details ?

**Comment by DanielnetoDotCom** [comment]
There are details above, if you want to get the plugin I can direct sell for you, or you can wait .

On the next day's I will be releasing it on the plugins market

**Comment by waqasbelushi** [comment]
@DanielnetoDotCom i Already use s3 in your script but different way i use goofys for upload video only for stream i use aws-sdk-php now i'm trying to change video file extra content in directory videos because im getting very slow experience can you help me  to change videos extra content like cache dire configuration.php userPhoto i only want to store video data thanks for you response.

**Comment by DanielnetoDotCom** [comment]
I store only video data on S3

and I choose to use aws-sdk-php because all S3 file systems are slow

**Comment by waqasbelushi** [comment]
Now A Day Im Working With aws-sdk-php Just Wait If I do My Job Than I Share With You.

**Comment by waqasbelushi** [comment]
One more thing your script not supported long duration videos.

**Comment by DanielnetoDotCom** [comment]
It does support

**Comment by waqasbelushi** [comment]
in this time im only focus s3 after i checked again thanks and By t.c

**Comment by hersche** [comment]
because there is a plugin now, i close it.
