### ISSUE TITLE
Page loading very slowly..

### ISSUE THREAD

**Issue by Bhargavvidem** [DanielnetoDotCom/YouPHPTube#354]
I tried on installing the YouPHPTube, worked fine for the first time. I launched these in an AWS instance.
Later I stopped the server for an hour, and after the page is not even loading. It taking too much time and loads some part. Even the configuration of the server is high.
Is that an issue with apache or what, can anyone please help me out.

**Comment by DanielnetoDotCom** [comment]
@Bhargavvidem Sorry to hear it, I have never seen any error like that.
I can not tell you what may be causing this, but I guess may be the connection.
Try to use your 4G connection on your cellphone, to be able to discard this hypothesis about your local network

**Comment by hersche** [comment]
@Bhargavvidem is this issue still exist for you?

**Comment by hersche** [comment]
reopen if this still exists, we have done some things which should improve performance, but we would need feedback.
