### ISSUE TITLE
Embed video link stopped working

### ISSUE THREAD

**Issue by NineSeven8** [DanielnetoDotCom/YouPHPTube#355]
Hi, 

I just recently installed YouPHPTube, on the initial tests, before installing the encoder, I was able to embed a youtube video, after the encoder installation I try to embed a video uploaded by me on youtube, with embed permissions and the video never shows up on my videos.

Am I missing something, is that normal ?

**Comment by DanielnetoDotCom** [comment]
I dont know what happend.

Try to check the log file for encoder and streamer.

**Comment by NineSeven8** [comment]
Hi,

I found the issue, I'm sorry for wasting time. It ended up being our Proxy blocking, disabled it and it worked straight away.

Cheers for the prompt reply tho.
