### ISSUE TITLE
mycloudstreaming.com takeover?

### ISSUE THREAD

**Issue by abamilod** [DanielnetoDotCom/YouPHPTube#356]
What will happen to our beloved youphptube? I guess no more updates after this. Please tell me I am wrong.

I am crying inside...

**Comment by JonnyTech** [comment]
Is this true? Now a commercial product? Can anyone state a FOSS alternative? I was about to try this as a personal project but will not if it becomes restricted or closed.

**Comment by DanielnetoDotCom** [comment]
Hi

They are representing YPT on Asia, but the community edition still on GitHub and it will still receiving updates

**Comment by DanielnetoDotCom** [comment]
Also it still opensource
