### ISSUE TITLE
SMTP-not working 

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#357]
Your message could not be sent!
Message could not be sent SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/

**Comment by gujarraju** [comment]
hi Daniel please fix my issue...

**Comment by gujarraju** [comment]
Your message could not be sent!
Message could not be sent SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/

**Comment by DanielnetoDotCom** [comment]
It is because you do not have an stmp on your server and you did not configure an external stmp on YPT configuration

**Comment by gujarraju** [comment]
then how to configure smtp in my own server

**Comment by DanielnetoDotCom** [comment]
Try Google for that , I know u can use postfix

**Comment by gujarraju** [comment]
ok

**Comment by hersche** [comment]
this looks solved, reopen if this is not the case.
