### ISSUE TITLE
Share Button

### ISSUE THREAD

**Issue by NineSeven8** [DanielnetoDotCom/YouPHPTube#358]
Hi guys,

Did anyone find a way to remove the SHARE button from the page ? Although the server has no public exposure I don't want users to try to share anything on social media.

Help would be appreciated.

Thanks

**Comment by DanielnetoDotCom** [comment]
Try to add on configuration - head code a css file

**Comment by NineSeven8** [comment]
Unfortunately I have no knowledge about CSS or PHP or I might have misunderstood what you said.

If someone can help with this would be great. Other than that, great piece of software.

**Comment by DanielnetoDotCom** [comment]
try this:

```
<style>
#shareBtn{
display:none;
}
</style>
```

![image](https://user-images.githubusercontent.com/18009293/36114939-3d754cec-1010-11e8-8cdc-7f158a8576ab.png)

**Comment by NineSeven8** [comment]
You're a genius ! 

Thank you very much Mate ! 👍 🥇
