### ISSUE TITLE
[Security] Use appropriate, secure hashing algorithm

### ISSUE THREAD

**Issue by TheAssassin** [DanielnetoDotCom/YouPHPTube#360]
*Sorry for posting this without content at first.*

This application is using a very insecure password hashing method. It uses the MD5 algorithm without any salting or other security measures.

Now, there's several issues with this hashing method. First of all MD5 is a very weak hashing algorithm. There's several known attacks on it, and it should not be used any more for any cryptographic work.

The next issue is there is no salting applied, hence equal passwords will yield the same results in the database. Now, looking at a database, you could easily check who else's using your password, etc., and an attacker could make those checks as well, if they had access to the database. MD5 being a really old and well known hashing algorithm, there's also a lot of so-called rainbow tables which you can feed with a given hash value to get the original text.

So, don't use MD5 for security stuff. Ever.

To mitigate some of those issues, so-called "salting" has been invented. Using salting prevents two equal passwords to result in the same hash value. It works like this: you add a column to the database, and fill it with random strings (you need a proper PRNG to get some appropriate entropy there, but as long as you're using a crypto library, this is the least issue to worry about). When hashing a password, you just combine that password and the salt, and feed that into your hashing algorithm. Now, if you have the same password twice, the probability that both salts differ is very high, so the results won't be the same either.

You should check out the OWASP (Open Web Application Security Project) Top 10 project. It's a list of the 10 most common security issues in web applications. See https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project#OWASP_Top_10_for_2013. The current version (2017) hasn't been released yet, as it's still being translated into several languages.

For this specific security issue, the points A6 ("Sensitive Data Exposure") and A9 ("Using Known Vulnerable Components") apply here.

Of course, using a salt doesn't mean MD5 is safe to use again. You will have to replace that hashing algorithm as well.

You don't have to reinvent the wheel here in order to fix this security bug. There's a couple of really secure hashing issues, and the best part is, PHP supports them out of the box (in recent version, that is).

### TL;DR

PHP5.5+ provides a password hashing function called `password_hash` (to verify, use `password_verify`). See http://php.net/manual/function.password-hash.php for details. If you're unexperienced in security questions (and, no offense, I think you are), just use the default algorithm `PASSWORD_DEFAULT`. You should not provide a custom `salt` or `cost` either. Just use the default values, they're sane choices, and will be updated in the future. Also, as the page says, the password column should support a lot of characters (the page recommends `VARCHAR(255)` at the moment) to be ready for future changes in the algorithms. The returned string is in a standard, interoperable format, which is understood by other software as well. Don't modify that string, just put it in the database, and you're good to go.

### General notes

Make sure to check out [OWASP Password Storage Cheat Sheet](https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet) if you build web applications. It provides detailed explanations and up to date recommendations.

My personal recommendation is to use either PBKDF2 or bcrypt with a salt (applies to 2018 -- might change in the future) Usually, there's libraries available with a standard interoperable format which developers should use. For Python, e.g., use https://passlib.readthedocs.io/en/stable/.

**Comment by DanielnetoDotCom** [comment]
Thanks for notice it.

We know the risks about MD5 hash. and also we have plans to improve it, password_hash is one good option for that

Thanks one more time

**Comment by TheAssassin** [comment]
Why close it then? I'd keep it open until the issue is resolved.

**Comment by TheAssassin** [comment]
P.S.: Being such a critical issue (I mean, let me keep searching, issues like #361 allow actual access to those hash values), I'd appreciate if you could work on this with priority. The fix doesn't seem to be too much work, given that PHP5.5+ support `password_hash`. The only real problem is that you'll have to raise the lower compatibility limit (current: PHP 5.3).

**Comment by TheAssassin** [comment]
P.P.S.: This software seems to be the most feature-complete video hosting software available which is free software. But any kind of security issue prevents me (and others) from using it. If you need help, let me know, I'll try to contribute some lines then.

**Comment by DanielnetoDotCom** [comment]
@TheAssassin OK, I will start to work on this next week, it is not hard to change, but we need to make it compatible with old versions

**Comment by TheAssassin** [comment]
The easiest way to do so is to update this value on the first login if an MD5 hash is used. But I'd rather have the update SQL script "reset" or "invalidate" all the passwords, that's more secure.

**Comment by DanielnetoDotCom** [comment]
I am thinking to make a script that will try to login using password_hash first , if success, that is fine.
If not will try MD5 , if success update the pass to password_hash.

This function will be removed in the future, will only be for transition.

**Comment by DanielnetoDotCom** [comment]
What salt function do you think is best, I am thinking to use a hash with salt

**Comment by TheAssassin** [comment]
Well, you should leave that in place forever then, it won't hurt, but allow upgrades from old versions. 
Otherwise, if you remove it, you'll really have to implement a function invalidating all the old passwords. 

Thinking about it, that's probably better, allowing a graceful migration of the passwords for a while, then switching to the more "brutal" version at some point.

**Comment by TheAssassin** [comment]
As I wrote in the original post, `password_hash` is adding a random salt automatically already. You don't have to do anything there. Please read that page entirely, it contains all the details.

(In general, generating a random string (with all alphanumeric characters in both cases (making a total of 62 characters) should suffice if the string is long enough, many systems use 8-16 characters.)

**Comment by DanielnetoDotCom** [comment]
I see, great, i didnt know about the random salt

**Comment by TheAssassin** [comment]
As mentioned before, the only side effect is that your lower compatibility limit will have to be raised to 5.5+. But, let's be realistic, 5.3 is ancient, and to really deploy this software, you need your own server anyway rather than using some shared hosting service (which, unfortunately, sometimes ship such outdated PHP versions...), so I wouldn't care too much about it.

**Comment by DanielnetoDotCom** [comment]
You right

**Comment by TheAssassin** [comment]
@DanielnetoDotCom this issue is still closed, but I think it needs to be reopened, otherwise it will most likely be forgotten over time.

**Comment by DanielnetoDotCom** [comment]
@TheAssassin thanks, I will not forget it. I just cant change it now. I still not find a solution to communicate encoder and mobile and streamer. but I am still looking for that;

the problem is...

you may send something to the encoder, and it goes to a queue and finish to encoder 24 hours later. encoder needs to be able to open an session on the server. I use the same user password hash for it, the salted hashes are different.

**Comment by DanielnetoDotCom** [comment]
That is a good idea to implement, I will probably do on that way, thanks

**Comment by TheAssassin** [comment]
Oh, I almost forgot, here's the workflow I promised:

![workflow](https://user-images.githubusercontent.com/4503202/38841554-3d852778-41e5-11e8-8b2c-6951be049016.png)

Not my best ever work, but I think it depicts the idea sufficiently.

**Comment by DanielnetoDotCom** [comment]
Wow, thanks that is great

but, on encoder there is an option to resend (or maybe reencode) the video if something goes wrong.
any idea how to handle this?

**Comment by TheAssassin** [comment]
> on encoder there is an option to resend (or maybe reencode) the video if something goes wrong

Could you elaborate on that, please? In what case would the video have to be re-sent?

**Comment by DanielnetoDotCom** [comment]
For example, if for some reason the streamer site gets offline, or a network fail (some times encoder and streamer are in different networks).
you can just resend the encoded files.

**Comment by TheAssassin** [comment]
Therefore, the generated secret is revoked by the encoder _only_ after verifying that all files have been transmitted.

Now, it could happen that due to some issues, the 2 day timeout is hit and the ticket becomes invalid, but I guess in this case it's fine to require a user to create a new encoding request.
You could also implement some kind of video caching mechanism, for example hash the original video, check in your database whether it's been encoded previously and still is available on the encoder, and use that. When an encoding request is recreated, the cached file can be used.
However, I can see some security issues with this approach. If a hash collision occurs (or an attacker provokes one), the attacker might be able to get the encoder to return a (potentially confidential) video. But that's only an issue with public encoder instances. Though, it might lead to legal issues.

I would just force users to re-upload videos if there's a network failure and the token has expired. At most, two days of videos have to be re-encoded. That's an acceptable trade-off.
