### ISSUE TITLE
[Security] Password hash is sent as query parameter to encoder

### ISSUE THREAD

**Issue by TheAssassin** [DanielnetoDotCom/YouPHPTube#361]
While trying out YouPHPTube, I noticed another security issue. The authentication information exchange between the encoder and the main page is vulnerable.

When switching to the encoder page from the main page, the main page issues a redirect to a URL like `https://encoder.mystuff.com/?webSiteRootURL=https%3A%2F%mystuff.com%2F&user=test&pass=XXXXXXXX`, where `XXXXXXXX` is the password hash stored in the database. This hash is currently a plain, unsalted MD5 hash, and is insecure, see my other issue #360 for details.

So, first of all, this system is sharing *sensitive data* with the other page, namely the password. This is an OWASP Top 10 point A6 "Sensitive Data Exposure". You shouldn't ever share that kind of information with anyone else, not even if the system is hosted by the same person, but especially not when using a public system like the main encoder page. And you should not put it in the query arguments.

I understand that the problem you tried to solve is that the encoder page needs to authenticate to the stream page and vice versa. However, such an insecure system does allow a variety of attacks. I don't want to go into detail too much. (*The easiest attack would probably be a `Referer:` header based one, tricking the user to connect to an external site, causing the browser to send the entire URL to a third party page. Having access to the user name, the target page, and the hash, this could serve as a starting point for attacks. Considering that the current hashing algorithm is easy to break (e.g., using a rainbow table), you could have access to the user's account within minutes.*)

Instead of your homebrew system, you should consider using OAuth(2) to allow the encoder to authenticate the user on the encoder page, and also to allow API access to send back the encoded videos. That's how modern pages solve this problem, there's a lot of frameworks and good resources on the Internet explaining OAuth2 and how it's implemented.

**Comment by DanielnetoDotCom** [comment]
Agree with you, but that is what is preventing me to make the password_hash change right now.
if I do this on the streamer the encoder and mobile will stop to work.

OAuth2 is an good option, but it will take some time to implement.

**Comment by hersche** [comment]
> if I do this on the streamer the encoder and mobile will stop to work.

just as a idea: i think in .htpasswd's is the hash-syntax like

{md5}xxxxxxx

when you implement it like this is possible too in the encoder and mobile app for a while,
via update-script you alter the values (just add {md5} to begin) in the streamer-database, also code for handle this and the future algo.

and finaly you can decide to force users to update that {md5} with a new {sha512}-password (but of course after they logged in via the right md5-pw a last time) - there would be also a good place for inform about they should update the encoder and mobile app..

like this, there's no loss of data, no need for asking user-passwords and when sha-512 becomes weak, you can repeat the whole thing with the better algo..
