### ISSUE TITLE
Live broadcast stopped by plugin

### ISSUE THREAD

**Issue by jhon181** [DanielnetoDotCom/YouPHPTube#365]
Hi, I need help, buy the liveusers plugin and when I enable it, the live streaming stops working, what can I do?
![image](https://user-images.githubusercontent.com/7749806/36067066-cf192008-0e83-11e8-99ea-53dc442787eb.png)

**Comment by DanielnetoDotCom** [comment]
Hi

Did u click in install tables buttons?

What is your streamer log file ?
