### ISSUE TITLE
The right sidebar Css needs modification 

### ISSUE THREAD

**Issue by TomOndiba** [DanielnetoDotCom/YouPHPTube#366]
place the following css in https://demo.youphptube.com/css/custom/default.css to fix it

`.compress {
top: 1px !important;
}`

**Comment by DanielnetoDotCom** [comment]
Great, please send a pull request, your name will be as a YouPHPTube contributor

**Comment by TomOndiba** [comment]
DanielnetoDotCom, I created a pull Request on  https://github.com/TomOndiba/YouPHPTube/pull/1

This is the file that I modified; YouPHPTube/view/css/custom/default.css

**Comment by DanielnetoDotCom** [comment]
Great, Accepted
