### ISSUE TITLE
VideoResolutionSwitcher plug  .... and the choice of quality in Live streaming.

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#367]
Hello.   Please consider the possibility of choosing the quality in the plug made for the video, even for the live streaming so that the user can choose the quality by himself ... especially if one looks at the mobile phone ... and can choose the most low if it has not so much band available.
Do not forget also the possibility to memorize for this plug the choice made, so that it is maintained also to the other videos ... maybe using a specia of cookies.

**Comment by TomOndiba** [comment]
The quality can be achieved by storing the original video then converting it into different resolutions just like Youtube does. I wrote a php code based on Elgg social network to use YouPHPTube script. You can check it live on action here http://myadventhome.org/video/view/692/view-from-a-blue-moon-4k

**Comment by tgd1973** [comment]
That's not what I meant  but ...
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Configure-NGINX-Stream-Resolutions

If you look at the new code, see that from the primary stream with the transcoding ... you get the second stream from the Live which is the Low ... all two that you can download switching between the two different indexes that are obtained from the Nginx-rtmp HLS ...
What DanielNetoDotCom did is also to pin another small code in the admin interface of the Live plugin ... with which decides as admin to provide the Live / index.m3u8 or Low / index.m3u8 I would have preferred to leave the choice to the user final instead of the admin ...

**Comment by DanielnetoDotCom** [comment]
@TomOndiba Great, how did you do that?

@tgd1973 this wiki still incomplete, but I will update it later.

This wiki was made because I have some YouPHPTube installations with huge traffic (about 1000 at the same time), that is why I made the cache plugin, to help the server to support it.

Another problem was because the sites with huge traffic, they are streaming in 1080p.

The way it was the live was also in 1080p. consuming a lot of bandwidth. the solution was to reduce the resolution to make possible more simultaneous connections at the same time.

I am also looking for a way to improve the resolution switch with memorize resolution. and automatic resolution due the internet speed. also resolution switch for HLS live, with the same features as it is for VOD.

**Comment by tgd1973** [comment]
Thanks in advance.

**Comment by tgd1973** [comment]
To not open another report, I write here ...
I see that if the apache server or other web server, if it does not have a directive not to open subdirectory, inserting in the browser addresses of all subdirectory you see clearly 
https://demo.youphptube.com/plugin/   ....
... what is hosted inside ...
To avoid this you have to insert an index.html file with the code inside:
`<HTML><HEAD><META HTTP-EQUIV="REFRESH" CONTENT="0; URL=/../"></HEAD></BODY></HTML>` 
within each subdirectory that makes a redirect to the homepage ...

It is not normal for one to see in this way all that is inside.
Please also correct also the git source.

https://demo.youphptube.com/plugin/

**Comment by SaliC-re** [comment]
> **To not open another report, I write here ...**
> I see that if the apache server or other web server, if it does not have a directive to not open subdirectory, inserting in the browser addresses of all subdirectory you see clearly
> https://demo.youphptube.com/videos/ ....
> ... what is hosted inside ...
> To avoid this you have to insert an index.html file with the code inside:
> `<HTML><HEAD><META HTTP-EQUIV="REFRESH" CONTENT="0; URL=/../"></HEAD></BODY></HTML>`
> within each subdirectory that makes a redirect to the homepage ...
> 
> It is not normal for one to see in this way all that is inside.
> Please also correct in the git source.

@DanielnetoDotCom is this going to be corrected in the next updates? we can still see the clear path to the video

**Comment by DanielnetoDotCom** [comment]
I disagree with it.

the videos directory browsing is already disabled and has a forbidden entry in the .htaccess.

https://github.com/WWBN/AVideo/blob/8f5e4b3a25d75faffcdd34296d9c78497ef26162/.htaccess#L30

if you can not add this directive on the host, many other things will also fail in your site.
