### ISSUE TITLE
LiveChat Plugin

### ISSUE THREAD

**Issue by Puyodead1** [DanielnetoDotCom/YouPHPTube#369]
When i click the Live button it says "Trying to establish a chat server connection
" then "Chat connection fail" i have apache2 and nginx running as i followed in the wiki page to setup server, plz help

**Comment by DanielnetoDotCom** [comment]
Is your streamer https or http?

Did you run `nohup php /var/www/html/YouPHPTube/plugin/LiveChat/chat-server.php &` ?

can you make sure you can connect on port 8888

**Comment by Puyodead1** [comment]
Got it working, the ports had to be changed from the guide, also its saying stream offline  buts its streaming

**Comment by DanielnetoDotCom** [comment]
About offline check this:

https://github.com/DanielnetoDotCom/YouPHPTube/issues/299
https://github.com/DanielnetoDotCom/YouPHPTube/issues/210

**Comment by hersche** [comment]
issue seems to be solved, reopen when im wrong

**Comment by tgibson1** [comment]
I have the same issue with https? I was working with http, is there something that needs to change for https?
