### ISSUE TITLE
Change the order of videos

### ISSUE THREAD

**Issue by angelawong** [DanielnetoDotCom/YouPHPTube#371]
Under the YouTube display mode, Is there a way to re-arrange my videos or highlight the one I want? At the moment, they are arranged by the published date. Please advise. Thank you.

**Comment by mikweb2017** [comment]
Version 4.8
![ytp](https://user-images.githubusercontent.com/30271757/36255440-56d4127c-124f-11e8-85a0-d66f727e3b28.PNG)
Add preferred videos that will randomly appear on first page

**Comment by DanielnetoDotCom** [comment]
@mikweb2017 Perfect answer

**Comment by angelawong** [comment]
Thanks so much for the answer. I am on version 4.1 and my system is telling me that my system is up to date. I did not know that there was an upgrade. Does this feature only appear in 4.8?

**Comment by DanielnetoDotCom** [comment]
Yes you need latest version 

Check those links

https://tutorials.youphptube.com/video/how-to-update-your-youphptube-version

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

**Comment by angelawong** [comment]
Thanks Daniel. I am getting a white screen though. Does the latest update work with PHP 5 or must I be on PHP7 for it to work?

**Comment by DanielnetoDotCom** [comment]
@angelawong check this https://github.com/DanielnetoDotCom/YouPHPTube/issues/332

**Comment by angelawong** [comment]
Thanks Daniel. I saw that posting and tried what was at #332 which is why I wonder whether it applies to PHP7 and not PHP5. I have PHP5 at the moment. Does version 4.8 only works with PHP7?

**Comment by DanielnetoDotCom** [comment]
No, it works with PHP 5 also
