### ISSUE TITLE
MP4ThumbsAndGif  plug problem ...

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#374]
The plugin MP4ThumbsAndGif   gives me error and no longer generates the Thumbs ... for the mp4 file uploaded to direct mp4 menu. Since the plug is totally encrypted, I ask for help to dev.
This is the error from youphptube.log
```
[15-Feb-2018` 21:57:07 Europe/Berlin] PHP Warning:  file_get_contents(https://www.abcd.eu/encoder/getImageMP4/aHR0cHM6Ly93d3cudHViZXNreS5ldS92aWRlb3MvQ2F0YWxpbklvbml0YV81YTg1ZjQyMzQ0MWNjMS4wMDIwNTcwOC5tcDQ=/jpg/1169): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /var/www/clients/client1/web6/web/plugin/MP4ThumbsAndGif/MP4ThumbsAndGif.php(14) : eval()'d code(1) : eval()'d code on line 33
[15-Feb-2018 21:57:07 Europe/Berlin] PHP Warning: file_get_contents(https://www.abcd.eu/encoder/getImageMP4/aHR0cHM6Ly93d3cudHViZXNreS5ldS92aWRlb3MvQ2F0YWxpbklvbml0YV81YTg1ZjQyMzQ0MWNjMS4wMDIwNTcwOC5tcDQ=/gif/1169): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
in /var/www/clients/client1/web6/web/plugin/MP4ThumbsAndGif/MP4ThumbsAndGif.php(14) : eval()'d code(1) : eval()'d code on line 33
```
The gif and jpg files that it generates are 0Kb and I can not even upload from the "edit" menu of video management (it loads jpg from the manual menu, them but then when it is saved it is not memorized).
I still have on the php v7.0 server I can not change from one day to another, since it is shared (Ubunti-ISPConfig)

**Comment by tgd1973** [comment]
In the encoder I have no error (I think it's normal since this plug has to generate the Thumb itself)
the gif or jpg file having 0Kb can not be viewed / loaded from the browser ... it gives me a blank page ...

**Comment by DanielnetoDotCom** [comment]
If it is blank should have an error on your encoder page

**Comment by tgd1973** [comment]
I have the encoder / downloader from Youtube & other put on the server in a subdomain with the name https://abcd.eu/encoder/ ... I do not know if in the latest version you have touched some script regarding this plug ...

**Comment by DanielnetoDotCom** [comment]
The plugin needs the encoder to extract the images .
The demo site have the latest version of the codes ,can you reproduce this error there?

But again please check your encoder log file since you are having a blank page

**Comment by tgd1973** [comment]
In your site it works quite ... but I do not know what's holding back ... this plug from me ... until a while ago it worked ... can you tell me what is the file from the streamer side that manages, the video in the admin part?

**Comment by DanielnetoDotCom** [comment]
I don't understand your question 

Try to update your streamer, encoder and the plugin file (download again)

**Comment by tgd1973** [comment]
Hi! I found the problem ... to my encoder not being updated to the latest version from your site, in the folder .htaccess lacked this rule: 
`` [RewriteRule    ^getImageMP4/([A-Za-z0-9=/]+)/([A-Za-z0-9]{3})/([0-9.]+)$ objects/getImageMP4.php?base64Url=$1&format=$2&time=$3    [NC,L]]``
 apart from the other changes ... for now it was sufficient to reload only .htaccess ... and has started to work again ...
For now, a big thanks.

**Comment by DanielnetoDotCom** [comment]
Nice I am glad it is working
