### ISSUE TITLE
Plugin MP4ThumbsandGifs do not generating Images and gifs

### ISSUE THREAD

**Issue by mfaheemkhan6** [DanielnetoDotCom/YouPHPTube#376]
Hello. I had bought MP4ThumbsandGif and upload MP4 videos. I did not get any image. In youphptube.log following error appear.
`[17-Feb-2018 04:53:50 Asia/Karachi] PHP Warning:  file_get_contents(http://md.expertpk.com/encodergetImageMP4/aHR0cDovL21kLmV4cGVydHBrLmNvbS92aWRlb3MvRWxhYW4yMjAxNk5hZ2FyanVuYVNocml5YVNhcmFuTXVrZXNoUmlzaGlGdWxsSERNb3ZpZVlvdVR1YmVfNWE4NzY2MzI1YzA4ZTIuNzczNTU5MTUubXA0/jpg/3599.5): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /home/expertpk/public_html/plugin/MP4ThumbsAndGif/MP4ThumbsAndGif.php(14) : eval()'d code(1) : eval()'d code on line 33
[17-Feb-2018 04:53:54 Asia/Karachi] PHP Warning:  file_get_contents(http://md.expertpk.com/encodergetImageMP4/aHR0cDovL21kLmV4cGVydHBrLmNvbS92aWRlb3MvRWxhYW4yMjAxNk5hZ2FyanVuYVNocml5YVNhcmFuTXVrZXNoUmlzaGlGdWxsSERNb3ZpZVlvdVR1YmVfNWE4NzY2MzI1YzA4ZTIuNzczNTU5MTUubXA0/gif/3599.5): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in /home/expertpk/public_html/plugin/MP4ThumbsAndGif/MP4ThumbsAndGif.php(14) : eval()'d code(1) : eval()'d code on line 33
`
I had tried this solution. [https://github.com/DanielnetoDotCom/YouPHPTube/issues/374](url)
I had added .htaccess rule mentioned in this comment in my htaccess file and restart my apache2 but still same error and no gif or image.
Another error in youphptube.log is 
`Class Plugin Not found: /pluginsAvailable.json`

**Comment by DanielnetoDotCom** [comment]
Strange, can you please make sure you have all files up to date

**Comment by mfaheemkhan6** [comment]
Yes. Fresh install.

**Comment by DanielnetoDotCom** [comment]
does that domain works? http://md.expertpk.com
the encoder need to be available dor the streamer

**Comment by mfaheemkhan6** [comment]
this domain absolutely work. http://md.expertpk.com for streamer and http://md.expertpk.com/encoder for encoder.

**Comment by mfaheemkhan6** [comment]
from encoder uploading video works great. But if I upload MP4 from streamer it did not get image and gif.

**Comment by DanielnetoDotCom** [comment]
Ok, I see why
On your streamer put a slash at the end of your encoder address 
you should change  http://md.expertpk.com/encoder to   http://md.expertpk.com/encoder/

**Comment by mfaheemkhan6** [comment]
another log entry in streamer log
`PHP Notice:  Undefined variable: img_portrait in /home/expertpk/public_html/plugin/Gallery/view/modeGallery.php on line 90`

**Comment by DanielnetoDotCom** [comment]
Does it work?
About the notice, you can ignore it;

**Comment by mfaheemkhan6** [comment]
Yes. Thanks a lot. It is working now. Great help. Only '/' take my hours. It should be documented in the plugin folder. Rewrite Rule and this fu***ng slash. Anyways, thanks for the quick help.

**Comment by DanielnetoDotCom** [comment]
I will try to automatic fix it in a future version :)
