### ISSUE TITLE
Some words not translated to Chinese

### ISSUE THREAD

**Issue by baalchina** [DanielnetoDotCom/YouPHPTube#377]
Hi, I found some words in Chinese UI still English, here are they, if the translation file can generate, I can help to translate to Chinese. Thanks.

1.Toolbar
![image](https://user-images.githubusercontent.com/3983019/36338595-85efb750-13ee-11e8-9d1b-1425152e9c7a.png)
May be `User Groups`, `Video Advertising`, `Categories` can be translated.

2.Site config-Themes
` Do not forget to save after choose your theme`

3.Site config--Regular Configuration
`Your Logo`, `Your Small Logo`, `First Page Mode`,`Authenticated users can upload videos`,`Authenticated users can comment videos`,`Autoplay Video on Load Page`

4.Site config--Advanced Configuration, All the options.

5.Upload Button
![snipaste_20180217_143424](https://user-images.githubusercontent.com/3983019/36338629-9ea0bdac-13ef-11e8-9fa1-bade892117eb.png)

Pls let me know how can I help to the translate job, YouPHPTube is so great, glad to help.

**Comment by hersche** [comment]
hey, you can add them to this file:

https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/locale/cn.php

basicly, you can edit there and make a pull request then. Or, you can send me a list with the translations to vinzenz.hersche@gmail.com and i can implement it.. thanks for the offer! :)
