### ISSUE TITLE
Live User Counter plugin 

### ISSUE THREAD

**Issue by 786739** [DanielnetoDotCom/YouPHPTube#378]
Hello

I have purchase Live user counter and install but after installing the plugin my live streaming show offline but when i click play button its working but show offline and i cannot see live user counter 

please advise

**Comment by DanielnetoDotCom** [comment]
Hi can you please take a screenshot of your live configuration?

Also the plugin configuration

**Comment by 786739** [comment]
Thanks for your reply 


![live](https://user-images.githubusercontent.com/36560821/36340655-459a3f5e-13f3-11e8-950d-d47d80721d83.png)
![screen shot 2018-02-17 at 2 56 49 pm](https://user-images.githubusercontent.com/36560821/36340657-577bdb4c-13f3-11e8-8090-9fb16aeb1c56.png)

**Comment by 786739** [comment]
![screen shot 2018-02-17 at 5 38 04 pm](https://user-images.githubusercontent.com/36560821/36343147-92320722-1419-11e8-9b4e-7c6d2ab0cd1a.png)

**Comment by DanielnetoDotCom** [comment]
Did you check the list stream option on the stream screen?

**Comment by 786739** [comment]
Yes I tried

**Comment by 786739** [comment]
When i turn on live user counter then stream show offline.
I’m using YouPHPTube v4.8

**Comment by DanielnetoDotCom** [comment]
can you please check your streamer log file

**Comment by DanielnetoDotCom** [comment]
One more question, did you update all yours files to latest?

**Comment by 786739** [comment]
yes it latest version and where can I get log file

**Comment by DanielnetoDotCom** [comment]
here: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by 786739** [comment]
please check  the below error 

[17-Feb-2018 23:50:58 UTC] PHP Fatal error:  Class 'Object' not found in /var/www/html/YouPHPTube/plugin/LiveUsers/Objects/LiveOnlineUsers.php(14) : eval()'d code(1) : eval()'d code on line 6
[17-Feb-2018 23:50:58 UTC] PHP Fatal error:  Class 'Object' not found in /var/www/html/YouPHPTube/plugin/LiveUsers/Objects/LiveOnlineUsers.php(14) : eval()'d code(1) : eval()'d code on line 6

**Comment by DanielnetoDotCom** [comment]
Ok, I know what is it ...

You have 2 options ...
Download the plugin file again (I just send a new file)

or do this
https://github.com/DanielnetoDotCom/YouPHPTube/issues/332

Sorry About that I have update the file, this error will not happened anymore.
This was an out dated file, but it is OK now

**Comment by 786739** [comment]
Thanks you for support its working
now I have also downloaded VideoResolutionSwitcher but it is also not showing in my live stream

**Comment by DanielnetoDotCom** [comment]
Hi,

VideoResolutionSwitcher  supports onlu VOD videos, is not available to Live Stream yet

**Comment by 786739** [comment]
Hi, 
my streaming was working fine till now , but now my streaming is working it says offline when I see the log I find this 

[18-Feb-2018 17:24:27 UTC] Could not resolve host: http
[18-Feb-2018 17:24:28 UTC] Could not resolve host: http
[18-Feb-2018 17:24:31 UTC] Could not resolve host: http
[18-Feb-2018 17:24:32 UTC] Could not resolve host: http
[18-Feb-2018 17:24:35 UTC] Could not resolve host: http
[18-Feb-2018 17:24:35 UTC] Could not resolve host: http
[18-Feb-2018 17:24:38 UTC] Could not resolve host: http
[18-Feb-2018 17:24:40 UTC] Could not resolve host: http
[18-Feb-2018 17:24:42 UTC] Could not resolve host: http

**Comment by DanielnetoDotCom** [comment]
I am not sure what happened can you give more log details?

**Comment by 786739** [comment]
[18-Feb-2018 17:09:27 UTC] Array
(
    [app] => live
    [flashver] => FMLE/3.0
    [swfurl] =>
    [tcurl] => rtmp://000.00.00.00:0/live?p=85d2663db4d986a99d603eecddfc5ab8
    [pageurl] =>
    [addr] => 41.222.93.2
    [clientid] => 45
    [call] => publish
    [name] => 5a87190fae5e1
    [type] => live
)

[18-Feb-2018 17:09:27 UTC] stdClass Object
(
    [error] => 1
)

[18-Feb-2018 17:09:28 UTC] Could not resolve host: http
[18-Feb-2018 17:09:35 UTC] Could not resolve host: http
[18-Feb-2018 17:09:35 UTC] Could not resolve host: http

**Comment by DanielnetoDotCom** [comment]
Because or this rtmp://000.00.00.00:0

I guess is something wrong with your Live Installation/Configuration

**Comment by 786739** [comment]
ok can please give the link to reinstall  because there is so many instruction im confuse

**Comment by DanielnetoDotCom** [comment]
You download the software here on GitHub

Check this https://tutorials.youphptube.com/video/streamer-and-encoder
