### ISSUE TITLE
YouTube-DL stuck saying "Downloading"

### ISSUE THREAD

**Issue by matthall1998** [DanielnetoDotCom/YouPHPTube#38]
Video downloads completely when I check the files, but in the web interface, it's stuck saying downloading.

**Comment by DanielnetoDotCom** [comment]
can you check **path/to/YouPHPTube/videos/youphptube.log**?

**Comment by DanielnetoDotCom** [comment]
Very sorry for that, i dettect an erron in the code.
can u please update your code with this git version

**Comment by matthall1998** [comment]
Awesome, uploaded the new youtubeDL.php in objects folder, works great now! Love the script! I was searching for hours for a free tube script, you need to advertise this more, because this one is amazing! GREAT JOB! WORKS GREAT!!!!!

**Comment by DanielnetoDotCom** [comment]
I am very happy you like it.
I want to do that, but I have no idea how to advertise. I am accepting ideas and help :)
