### ISSUE TITLE
How to point to my local disk for videos

### ISSUE THREAD

**Issue by jeehay** [DanielnetoDotCom/YouPHPTube#380]
Hi,

I have install the YouPhPTube on my localhost and I like to you it for my home video. How can i point it to my  local video lib without uploading the videos. I dont want to upload or encode the video as it will only be used in my local network.

**Comment by jeehay** [comment]
Only support linux

**Comment by DanielnetoDotCom** [comment]
To be able to use videos on browsers you need the correct format. that is why you need to encode.

Try to use bulk encode on local dir
