### ISSUE TITLE
Clean title in Chinese UI can be improved?

### ISSUE THREAD

**Issue by baalchina** [DanielnetoDotCom/YouPHPTube#382]
Hi, 
The clean title function in Chinese works not so fine. For example, I add a videos such as '视频'(means video), the clean title seems not recoginze Chinese character, and only give a '-'. And then I add video named '电影'(means movie), the clean title give still a '-', after save changes, the clean title became '-1', auto add a word 1 to differ from last title.

Maybe this function can be improved, such as using https://github.com/overtrue/pinyin module?

Thanks, just a suggsetion. :)

**Comment by DanielnetoDotCom** [comment]
Great, I have notice that.

I have some questions ... Chinese chars works on URL?
What is the regular expression to detect chinese chars?

I will take a look on pinyin later
