### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by EatBananas** [DanielnetoDotCom/YouPHPTube#383]
I see there is an LDAP-Plugin you can buy in the Plugin-Store.

If I log in to my YouPHPTube with an LDAP-User, will there be a YouPHPTube user created wich I can add to specific user groups or is there no possibility to add a LDAP-Authenticated user to a group?

**Comment by DanielnetoDotCom** [comment]
Yes, 

The plug-in only authenticate with LDAP, then create a user on YouPHPTube, then will have the same functions as regular users

**Comment by EatBananas** [comment]
Thanks you for your quick response :).
