### ISSUE TITLE
After Live Stream Plugin installation - not login possible

### ISSUE THREAD

**Issue by stoneubi** [DanielnetoDotCom/YouPHPTube#384]
Hi there, 

I hope you can help me. I use youphptube 4.3 and the gallery plugin was the only plugin selected. 

Today I switched on the two plugins live stream and live chat and now the youphp-site is not working any more. 

The only thing I see is this. I can press the button, but no reaction. If I open a direct link for a video, the video is playing but I cannot login any more and cannot manage any plugins. 
![live](https://user-images.githubusercontent.com/32926093/36395201-412021ac-15b8-11e8-85a2-f9af1e6be6f1.jpg)

I also checked the youphplog but there is no entry. 

Please could you let me know how to switch of plugins via file order. I have a hosted/shared server with ftp login. I don't have any cmd or command possibilities. 

Many thanks
Stone

**Comment by DanielnetoDotCom** [comment]
Update your files to youphptube 4.8 
Get them on GitHub

**Comment by stoneubi** [comment]
For all users having the same issue as I, the problem could be solved by disabling the two plugins in the mysql database in table plugin. Simply choose inactive. 

And yes, I already tried to upgrade to version 4.8 by uploading all files via ftp filezilla client. I overwrote each file one by one and the result was a white blank screen. 

Anyhow, I do have an active youphptube installation and therefore I cannot play around too much. Actually, for me it is important to have a running version. 

I don’t how if there are any other users having youphptube installed on a shared / hosted server with no linux command access, but for me it would be great to have web installer and a web updater to install and to update to the latest version. This would be a milestone for users like me. 

This thread can be closed. 

Many thanks
Stone

**Comment by DanielnetoDotCom** [comment]
Hi

About your blank screen check this https://github.com/DanielnetoDotCom/YouPHPTube/issues/332
