### ISSUE TITLE
VR360 Plugin not working

### ISSUE THREAD

**Issue by brajeshrgupta** [DanielnetoDotCom/YouPHPTube#385]
Hi

I have installed VR360 plugin but it is not working. Ever my stemer site is not working after enable plugin. 

Error log says - 
[20-Feb-2018 06:53:31 UTC] PHP Fatal error:  Class 'Object' not found in /home/video1newstrackl/public_html/plugin/VR360/Objects/VideosVR360.php(14) : eval()'d code(1) : eval()'d code on line 8

[20-Feb-2018 06:55:47 UTC] PHP Fatal error:  Call to a member function getStart() on boolean in /home/video1newstrackl/public_html/plugin/YouPHPTubePlugin.php on line 185

**Comment by DanielnetoDotCom** [comment]
yes bad,
I just update the plugin, can you please download it again

Atenciosamente

Daniel Neto

Master in Systems and Computing (2009)
Specialist in WEB Systems and Applications (2005)
http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K4252385T9

PHP ZEND 4/5 Certified Engineer
PHP Zend Certification - Authentication
http://zend.com/zce.php?c=ZEND001318&r=209210010

Programming in HTML5 with JavaScript and CSS3 Specialist (MCP 70-480)
https://mcp.microsoft.com/authenticate/ValidateMCP.aspx
Transcript ID (1040640) and the Access Code (danielNeto)

**Comment by brajeshrgupta** [comment]
Hi

Still same error


[20-Feb-2018 13:28:24 UTC] PHP Fatal error:  Class 'Object' not found in /home/video1newstrackl/public_html/plugin/VR360/Objects/VideosVR360.php(14) : eval()'d code(1) : eval()'d code on line 8

**Comment by DanielnetoDotCom** [comment]
hi, are you sure you download from the easytube the VR plugin again?

**Comment by brajeshrgupta** [comment]
Yes

On 20-Feb-2018 7:33 PM, "YouPHPTube" <notifications@github.com> wrote:

hi, are you sure you download from the easytube the VR plugin again?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DanielnetoDotCom/YouPHPTube/issues/385#issuecomment-366986604>,
or mute the thread

**Comment by DanielnetoDotCom** [comment]
Can you please delete the files on the server and upload again, to make sure they are overwrite

**Comment by brajeshrgupta** [comment]
Hi

working now.

Please help how embed videos will auto play


Thanks

**Comment by DanielnetoDotCom** [comment]
The auto play function on embed videos is not guaranteed .
only some providers support this feature

**Comment by hersche** [comment]
the plugin is working now, and the question is answered. so i close that issue.
