### ISSUE TITLE
View counter is not working

### ISSUE THREAD

**Issue by rohitnehra** [DanielnetoDotCom/YouPHPTube#386]

**Comment by DanielnetoDotCom** [comment]
Check this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-Video-Count-Works

**Comment by rohitnehra** [comment]
still not working. It remains 0 for all videos

**Comment by DanielnetoDotCom** [comment]
Did you enable cache?
if yes, that is why

**Comment by rohitnehra** [comment]
cache is disabled.

**Comment by rohitnehra** [comment]
I disabled the cache . If there is any file I need to change kindly tell me

**Comment by DanielnetoDotCom** [comment]
Check your youphptube log file and see if there is any issue.
did you update your files?
what version are you running?

**Comment by rohitnehra** [comment]
4.7
not updated
two log files are there.

**Comment by DanielnetoDotCom** [comment]
Please update to 4.8

**Comment by rohitnehra** [comment]
how to update to new version . It said it already updated

**Comment by DanielnetoDotCom** [comment]
check here https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

**Comment by rohitnehra** [comment]
Thanks working perfectly
