### ISSUE TITLE
How to change description 

### ISSUE THREAD

**Issue by rohitnehra** [DanielnetoDotCom/YouPHPTube#387]
It says the best youtube clone ..

I want to change it.

I want to ask for your permissions.

Is it right that it will not harm your sentiments.

I don't want to change footer.

tell me the finest way to edit

**Comment by DanielnetoDotCom** [comment]
Hi, the code is yours you can change it hard coded (not recommended because you may have problems on future updates ) or you can get the customize plugin (4,99). I allow you to change About, footer and description.

**Comment by rohitnehra** [comment]
Thanks & god bless you :)

**Comment by DanielnetoDotCom** [comment]
you welcome :)

**Comment by amishultimatehacker** [comment]
from where can i download that plugin

**Comment by amishultimatehacker** [comment]
But from where do I access those setting after I have Installed CustomizeAdvanced plugin

**Comment by amishultimatehacker** [comment]
But from where do I access the setting of "CustomizeAdvanced" Plugin and moreover the website is always displaying a dash (-) before site title.

**Comment by DanielnetoDotCom** [comment]
@amishultimatehacker 
Site title you can go on configuration menu.
to change the description is not on CustomizeAdvanced, it is in a paid plugin called Customize

**Comment by amishultimatehacker** [comment]
ok
