### ISSUE TITLE
openload not downloading

### ISSUE THREAD

**Issue by loso20p** [DanielnetoDotCom/YouPHPTube#388]
hey i was wondering if the download video works with openload because i tried on ur demo site and i got this  
We could not get the title of your video () go to https://github.com/DanielnetoDotCom/YouPHPTube/wiki/youdtube-dl-failed-to-extract-signature to fix it.
so is openload not working for it?
is there a fix?

**Comment by DanielnetoDotCom** [comment]
Hi

You may be tried to use youtube-dl on openload video.
I guess is not possible here is a list of supported sites: https://rg3.github.io/youtube-dl/supportedsites.html

**Comment by loso20p** [comment]
o ok hopefully one day u can make it work
