### ISSUE TITLE
YouPHPTube Streaming in Facebook Style Block

### ISSUE THREAD

**Issue by DemonRem** [DanielnetoDotCom/YouPHPTube#389]
will be cute to have this block of live in the facebook style like this
![idea](https://user-images.githubusercontent.com/29927382/36604230-d22efabe-18c5-11e8-9d70-9b0b9a92e7a7.png)

sorry my pc is on Hebrew but the idea is that there will be a read animated say live on the top of the post
and cool box like in the photo that allow you post any text

**Comment by DanielnetoDotCom** [comment]
Yeah we may implement live support on Facebook style in the future

Em 23 de fev de 2018 13:20, "DemonRem" <notifications@github.com> escreveu:
