### ISSUE TITLE
Multiple Issues / Enhancements

### ISSUE THREAD

**Issue by Digitalcdj** [DanielnetoDotCom/YouPHPTube#39]
1. Custom css on admin dashboard

2. YouPHPtube taking 100% CPU server power when uploading video files

3. Ability to remove default categories e.g Audio, Video and Audio, Audio only

4. Be able to hide Share button on Video's

5. Be able to add a custom button below video's (embed url link to button)

6.  Be able to change/modify social buttons in footer to our own (leaving powered by still there), only changing Facebook and Google+, also adding more options than just 2 social button types.

**Comment by DanielnetoDotCom** [comment]
> YouPHPtube taking 100% CPU server power when uploading video files
This behavior is expected because at the moment the video is encoded (only once, right after upload) it will use 100% of the CPU. But to watch the video the use of the CPU is very little

I would like to thank you for the enhancements ideas, they may be on next release if we get some help :)
Thanks one more time

**Comment by Digitalcdj** [comment]
Also I tried to update translations to add a GB (United Kingdom flag) basically its the same as USA, I gave permissions to rewrite to the file through putty but it still doesn't allow me to add the translation, can you add a GB (United Kingdom option) thanks and also the ability to make it site wide default (to any language).

**Comment by francisdeneto** [comment]
Are you logged as admin on your YouPHPTube?
Can you try to do the same on demo site?
I have tried to create spanish with argentina flag, and it works well
