### ISSUE TITLE
No compatible source was found for this media

### ISSUE THREAD

**Issue by PSanf2** [DanielnetoDotCom/YouPHPTube#390]
Hello!
I'm trying to get YouPHPTube installed on my private virtualization server, and keep getting an error when trying to watch a video I downloaded from YouTube. I see a screenshot of the image, and an error saying "No compatible source was found for this media."

I'm running a fresh install of Ubuntu 16, and installed curl before following the directions on the wiki. I roughly followed along with the video tutorial in order to finish setting things up on my local YouPHPTube website.

The browser's not blocking anything, and doesn't have any plugins installed.

I'm including links to the wiki and tutorial resources I've referenced, a screenshot of the error, and the video I downloaded.

Did I miss a step in the installation?
Thanks and Lord Bless!

I ran sudo apt-get update followed by sudo apt-get install curl. After that I ran the large block of commands from the first article linked below.

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x-For-YouPHPTube-version-4.x-or-newer

https://tutorials.youphptube.com/video/streamer-and-encoder

https://tutorials.youphptube.com/cat/default/video/how-to-download-videos-from-youtube

https://www.youtube.com/watch?v=QjprMs_qT4A

https://i.imgur.com/tb5CdB4.png

**Comment by PSanf2** [comment]
Lord be praised, it looks like a reboot fixed it. Bless him and his workings.

**Comment by willpower68** [comment]
My youtube embed videos will not play.  I get this error
"No compatible source was found for this media."
All videos are under 30 minutes.  They were playing and I tried on different browsers and refreshed.  I still get error.

Can anyone offer some advice on how to fix it?

**Comment by DanielnetoDotCom** [comment]
maybe you got a problem on the file transfer between encoder and streamer.

check the log file and make sure the source file exists
