### ISSUE TITLE
video advertising error

### ISSUE THREAD

**Issue by gvasquezj** [DanielnetoDotCom/YouPHPTube#391]
First of all, I want to thank you and congratulate you for this great work. I occupy this type of platforms in an educational institution, where students and teachers upload educational content and can view them on the local network from their cell phones. And I must say that your system is very complete and your tutorials are very well explained and easy to understand.

Now I have a problem with Ads uploaded locally. throws the following error when I press skip ad (Not compatible source was found for this media.) and can not play the selected video. What could be the problem?

Saludos desde Chile :)

Gabriel Vasquez
![ads_error](https://user-images.githubusercontent.com/31965681/36638222-a3271cde-19cd-11e8-8a11-984aff506330.png)

**Comment by DanielnetoDotCom** [comment]
Can you please check the log file?
Are you using encoder , embed or direct upload?

**Comment by gvasquezj** [comment]
[25-Feb-2018 11:31:39 America/Santiago] PHP Notice:  Undefined index: host in /var/www/html/edufrog/view/include/video.php on line 79
[25-Feb-2018 11:31:39 America/Santiago] PHP Notice:  Array to string conversion in /var/www/html/edufrog/objects/functions.php on line 577

The videos were uploaded directly to mp4

**Comment by DanielnetoDotCom** [comment]
What URL did you put there?

![image](https://user-images.githubusercontent.com/18009293/36643445-20879526-1a2a-11e8-8715-7495318d0de9.png)


Can I see your ad form screen?

**Comment by gvasquezj** [comment]
the truth is that I did not know what to put in URL, so leave blank 

![form_ads](https://user-images.githubusercontent.com/31965681/36647549-0e81772a-1a66-11e8-9eaa-6d7023be45d6.jpg)

**Comment by DanielnetoDotCom** [comment]
can you please put an URL there?
It should have a URL to redirect

**Comment by gvasquezj** [comment]
add a url and the error persists
attached video error, maybe I'm doing something wrong

https://demo.youphptube.com/video/error-ads

**Comment by DanielnetoDotCom** [comment]
Sorry, the video was removed, the server reset 4 times a day

**Comment by gvasquezj** [comment]
upload youtube!!

saludos y muchas gracias por la ayuda! :)

**Comment by DanielnetoDotCom** [comment]
On the URL use http://www.edufrog.cl

**Comment by gvasquezj** [comment]
adding http://www.edufrog.cl and the problem persists.
send browser console information. Can it be something related to the latest versions of ff and chrome?

zoomrotate: Start
videojs.zoomrotate.js:5 zoomrotate: Init defaults
video.js:489 VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead
logByType @ video.js:489
log.warn @ video.js:621
videojs.plugin @ video.js:24504
(anonymous) @ videojs.zoomrotate.js:33
(anonymous) @ videojs.zoomrotate.js:71
videojs.zoomrotate.js:73 zoomrotate: End
video.js:489 VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead
logByType @ video.js:489
log.warn @ video.js:621
videojs.plugin @ video.js:24504
(anonymous) @ videojs.persistvolume.js:121
(anonymous) @ videojs.persistvolume.js:16
(anonymous) @ videojs.persistvolume.js:19
(index):521 compress
videojs.zoomrotate.js:34 zoomrotate: Register init
videojs.zoomrotate.js:44 zoomrotate: [object CSSStyleDeclaration]
videojs.zoomrotate.js:45 zoomrotate: [object CSSStyleDeclaration]
videojs.zoomrotate.js:46 zoomrotate: 0
videojs.zoomrotate.js:47 zoomrotate: 1
videojs.zoomrotate.js:69 zoomrotate: Register end
(index):638 Change Video
video.js:489 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. MediaError {code: 4, message: "No compatible source was found for this media."}
logByType @ video.js:489
log.error @ video.js:607
error @ video.js:22727
(anonymous) @ video.js:22278
bound @ video.js:2232
setTimeout (async)
setTimeout @ video.js:4362
(anonymous) @ video.js:22277
setSourceHelper @ video.js:11223
setSourceHelper @ video.js:11225
(anonymous) @ video.js:11145
bound @ video.js:2232
setTimeout (async)
setTimeout @ video.js:4362
setSource @ video.js:11144
src @ video.js:22266
changeVideoSrc @ script.js:119
(anonymous) @ (index):640
dispatch @ jquery-3.2.0.min.js:3
q.handle @ jquery-3.2.0.min.js:3
script.js:256 {status: "", count: "0"}

**Comment by DanielnetoDotCom** [comment]
What about the error you posted before:

```
[25-Feb-2018 11:31:39 America/Santiago] PHP Notice: Undefined index: host in /var/www/html/edufrog/view/include/video.php on line 79
[25-Feb-2018 11:31:39 America/Santiago] PHP Notice: Array to string conversion in /var/www/html/edufrog/objects/functions.php on line 577
```
Still there?

**Comment by gvasquezj** [comment]
**this information is from the youphptube.log file:**

[28-Feb-2018 12:45:15 America/Santiago] PHP Notice:  Array to string conversion in /var/www/html/edufrog/objects/functions.php on line 577
[28-Feb-2018 12:45:16 America/Santiago] PHP Notice:  Array to string conversion in /var/www/html/edufrog/objects/functions.php on line 577
[28-Feb-2018 12:45:26 America/Santiago] PHP Notice:  Array to string conversion in /var/www/html/edufrog/objects/functions.php on line 577


**this information is the browser console(chrome):**

zoomrotate: Start
videojs.zoomrotate.js:5 zoomrotate: Init defaults
video.js:489 VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead
logByType @ video.js:489
log.warn @ video.js:621
videojs.plugin @ video.js:24504
(anonymous) @ videojs.zoomrotate.js:33
(anonymous) @ videojs.zoomrotate.js:71
videojs.zoomrotate.js:73 zoomrotate: End
video.js:489 VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead
logByType @ video.js:489
log.warn @ video.js:621
videojs.plugin @ video.js:24504
(anonymous) @ videojs.persistvolume.js:121
(anonymous) @ videojs.persistvolume.js:16
(anonymous) @ videojs.persistvolume.js:19
(index):521 compress
videojs.zoomrotate.js:34 zoomrotate: Register init
videojs.zoomrotate.js:44 zoomrotate: [object CSSStyleDeclaration]
videojs.zoomrotate.js:45 zoomrotate: [object CSSStyleDeclaration]
videojs.zoomrotate.js:46 zoomrotate: 0
videojs.zoomrotate.js:47 zoomrotate: 1
videojs.zoomrotate.js:69 zoomrotate: Register end
(index):638 Change Video
video.js:489 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. MediaError {code: 4, message: "No compatible source was found for this media."}
logByType @ video.js:489
log.error @ video.js:607
error @ video.js:22727
(anonymous) @ video.js:22278
bound @ video.js:2232
setTimeout (async)
setTimeout @ video.js:4362
(anonymous) @ video.js:22277
setSourceHelper @ video.js:11223
setSourceHelper @ video.js:11225
(anonymous) @ video.js:11145
bound @ video.js:2232
setTimeout (async)
setTimeout @ video.js:4362
setSource @ video.js:11144
src @ video.js:22266
changeVideoSrc @ script.js:119
(anonymous) @ (index):640
dispatch @ jquery-3.2.0.min.js:3
q.handle @ jquery-3.2.0.min.js:3
script.js:256 {status: "", count: "0"}

and the error is about the advertisers, as seen in the attached video (updated)
https://www.youtube.com/watch?v=PhfwXvOAhac

regards

Gabriel V.

**Comment by gvasquezj** [comment]
modify the file /var/www/html/edufrog/objects/functions.php on line 577

Original = return $videoSources. $AudioTracks. $SubtitleTracks;
modification = return $videoSources;

And now it works! :), but what error can generate this modification in the future?

Saludos

Gabriel

**Comment by DanielnetoDotCom** [comment]
You Right

I was just looking into it, I have no idea why this code is there.
I am sending a fix for this.

Thanks for your help

**Comment by DanielnetoDotCom** [comment]
Ok, Now I know why, it is because the subtitle support, I will need more fixes on that. I am working on it now.

**Comment by DanielnetoDotCom** [comment]
@gvasquezj , I recommend you to update your files with github version.
The problem with ads is fixed. and now support multi resolution and subtitle with no problem

**Comment by gvasquezj** [comment]
Great! then I give my problem for solved. I reiterate the congratulations for this great project. Your work is excellent, it shows that there is a heart in this!

regards

Gabriel Vasquez
Since the end of the world
