### ISSUE TITLE
Permalink of video URL.

### ISSUE THREAD

**Issue by lazygirls** [DanielnetoDotCom/YouPHPTube#392]
I see that Script is best for Youtube Clone. Everything is good only permalink not good.
You should use Permalink like Youtube.  Like: youtube.com/watch?v=Cz8u1Su2L1k

Thank you!

**Comment by DanielnetoDotCom** [comment]
It will be implemented soon :)

**Comment by DanielnetoDotCom** [comment]
By Default you have now a PermaLink on share option

![image](https://user-images.githubusercontent.com/18009293/36733556-bdf01258-1baf-11e8-8923-e62c53358870.png)

Also you can choose to use PermaLink in other links (Not all of them to keep SEO improvement)

![image](https://user-images.githubusercontent.com/18009293/36733597-d7f0e286-1baf-11e8-9132-b283c837be35.png)
