### ISSUE TITLE
LDAP PW change

### ISSUE THREAD

**Issue by EatBananas** [DanielnetoDotCom/YouPHPTube#393]
Heyy,
Another Question to the LDAP-Authentication Plug-In. If the password of a user is being changed in the Active Directory, will the user be able to log-in with his new password in YouPHPTube or is there any change needed?

**Comment by DanielnetoDotCom** [comment]
Yes, the AD manage user and pass, YPT always authenticate on the AD, is success, YPT creates a local user.

**Comment by EduardoOsquel** [comment]
I need to know if its possible to find a free version for the LDAP-Authentication Plug-In, i need it and unfortunately i cant afford to pay it because i am in Cuba...

**Comment by DanielnetoDotCom** [comment]
@EduardoOsquel

Create an account on GitHub and send an email to developer@youphptube.com

**Comment by EduardoOsquel** [comment]
Good morning, created account, sent mail, Regards EduardoOsquel

**Comment by DanielnetoDotCom** [comment]
Hi, I did not receive the email, could you please double check?
