### ISSUE TITLE
FFMPEG Libraries

### ISSUE THREAD

**Issue by brajeshrgupta** [DanielnetoDotCom/YouPHPTube#394]
Hi

Please provide ffmpeg libraries which are required for video streaming and encoding

**Comment by DanielnetoDotCom** [comment]
Hi, on the installation I install only the default ffmpeg with it's default libs

**Comment by deaf-tv** [comment]
CentOS 7 and CWP

CWP FFMPEG Install Auto
FFMPEG Default

CWP with YouPHPTube work good

**Comment by deaf-tv** [comment]
http://centos-webpanel.com/

![cwp ffmpeg](https://user-images.githubusercontent.com/17132516/37397685-80bcaac6-277c-11e8-896e-bada49363efd.jpg)

**Comment by DanielnetoDotCom** [comment]
Good to know it works

**Comment by hersche** [comment]
so that's solved.. take the system's default binarys make absolute sense - imagine a raspberry (arm) and usual server (amd64) - would not work on one of both systems.

so, i close this as well..
