### ISSUE TITLE
Installation hangs when port number is specified

### ISSUE THREAD

**Issue by kcsrnd** [DanielnetoDotCom/YouPHPTube#397]
My streamer site is listening on http://127.0.0.1:5001

When I try to specify that while installing, it hangs at "Processing".

Is there anything I can do to fix this?  Thanks.

**Comment by DanielnetoDotCom** [comment]
it is not suppose to happened, check the apache log

**Comment by hersche** [comment]
still a problem, @kcsrnd ?
