### ISSUE TITLE
LDAP Group Synchronization

### ISSUE THREAD

**Issue by EatBananas** [DanielnetoDotCom/YouPHPTube#398]
Is there away to synchronize groups between Active Directory and YPT, so that a user being assigned to a group in Active Directory will automatically be assigned the group in YPT? Or is it planned to implement this function in the future?

**Comment by DanielnetoDotCom** [comment]
It is not done. and we are not planning to do it yet

**Comment by SubjectXXX** [comment]
@EatBananas Which AD parameter are you using for defining user's group?

**Comment by EatBananas** [comment]
The "member of" parameter
