### ISSUE TITLE
Multiple cores for FFMpeg

### ISSUE THREAD

**Issue by Megatronic79** [DanielnetoDotCom/YouPHPTube#4]
Hey Daniel,

To speed up the conversion process do we just need to edit the advanced section and add **-thread X** where x is the number of cores?

Would this be something worth adding as an input option on the UI that automatically includes it in the different conversion commands?

Cheers

Stephen

**Comment by DanielnetoDotCom** [comment]
Hi 

All ffmpeg configurations you can do by editing the ffmpeg command on site configuration-> advanced

![image](https://cloud.githubusercontent.com/assets/18009293/25567834/d0adfc6a-2dcc-11e7-9f65-94e3461237a8.png)

**Comment by DanielnetoDotCom** [comment]
BTW what is the URL of your video sharing?

**Comment by Megatronic79** [comment]
Thanks for the pointer will play with the commands to speedup the conversions.

URL is not published at the moment, just put this online in a dev environment to test it out, was seeing if we can use it to host our presentations, training guides etc.. so far very impressed with it.

**Comment by DanielnetoDotCom** [comment]
Thanks for the comments, if you can share your speed up optimizations we will apprecciate that.
If you need any other help fell free to ask.
