### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by fablin** [DanielnetoDotCom/YouPHPTube#40]
Hi,
on the sign in window, I click on Forgot Password without filling the user input 
on the next window with captcha, I click an the send button and nothing happens.
Just processing bar and nothing else

<img width="636" alt="capture d ecran 2017-06-17 a 11 27 39" src="https://user-images.githubusercontent.com/29496388/27249794-09e6fd44-5350-11e7-82d8-985b0edd33a8.png">

**Comment by DanielnetoDotCom** [comment]
Thanks for this, I just upload a new file to fix this issue

**Comment by fablin** [comment]
Thanks !
