### ISSUE TITLE
 full screen permanently

### ISSUE THREAD

**Issue by sergioloyola** [DanielnetoDotCom/YouPHPTube#401]
When I have auto play, there is a way to keep the full screen for all the videos

**Comment by DanielnetoDotCom** [comment]
That is a good idea I will research how to do it

**Comment by hersche** [comment]
i also thinked about this and became feedback from useres there...

i assume (!) that it leaves the fullscreen when the new page loads (not when the video ended) and that this feature would need to load the new video via ajax (so replacing videolink in mainVideo only), to not leave fullscreen..

when it is like this, it would need some work.. i'm very interessted in how the solution will be! :)

**Comment by DanielnetoDotCom** [comment]
This function may help this 

https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/view/js/script.js#L126

**Comment by sergioloyola** [comment]
I check it with the script that you told me but it does not work

2018-03-05 11:09 GMT-03:00 YouPHPTube <notifications@github.com>:

**Comment by hersche** [comment]
@sergioloyola i think Daniel just wanted to say that this would be a ajax-method, that can be used for load the next video.. but when it's not used in youphptube, it doesn't help - we have to build this into the next-video-function correctly, and when we do this, the website won't reload and the video (maybe) stays in fullscreen then.

**Comment by sergioloyola** [comment]
OK thank you very much. I thought that not that scrip to which
reference could solve the problem.



2018-03-05 14:09 GMT-03:00 Vinzenz Hersche <notifications@github.com>:

**Comment by hersche** [comment]
@DanielnetoDotCom currently, i try to solve this issue with your method in this two places: [L122](https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/view/include/video.php#L122) and [Line 149 of view/include/video.php](https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/view/include/video.php#L149) , my code looks like

`` $sources = getSources($autoPlayVideo['filename'], true); ``
        ``?>``
                 ``       else if (Cookies.get('autoplay') && Cookies.get('autoplay') !== 'false') {``
``                                changeVideoSrc(player, <?php echo json_encode($sources); ?>);``
``                                //document.location = '<?php echo $autoPlayVideo['url']; ?>';``
                        ``} ``

like what i find [here](https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/view/include/video.php#L173)

you do use this method with the usual player-variable, as it looks, but in my case i have this exception:
TypeError: player.updateSrc is not a function

so i am not shure, why this object should have the method downer, but not where i am using them.

maybe you have any hints there?

**Comment by sergioloyola** [comment]
Try to make the changes you indicated but I can not keep the full screen



2018-03-05 15:41 GMT-03:00 Vinzenz Hersche <notifications@github.com>:

**Comment by hersche** [comment]
@sergioloyola no, it is still NOT working, i need to have more information about the whole thing.
but i think, when we load videojs-resolution-switcher, it could PARTIALLY work (i think, not all infos on the website will be updated with this function).

when i solve it, i will send the link of my commit :)

btw, i've tried it also with loading the js-file before and add this to the videojs-constructor, still NO success:

`		plugins: {
			videoJsResolutionSwitcher: {
				default: 'low',
				dynamicLabel: true
			}`

**Comment by hersche** [comment]
horray, i've got the begin :D 

my code basicly works, solution is basicly simple: https://github.com/hersche/YouPHPTube/commit/6d4d29392a18f5273e6bd2f6ade5a04f96a75359

the .src-method do the same and works withouth any plugin!

also, it definently stays in fullscreen between changes.

now, there has other stuff to be done as well, for example:

- after the first "autoplayed" video, the video repeats, because this is set via php only - update via js would be needed.
- update all the other content on the site
- change the address as well (withouth reloading)

- and when we do a such big structure change, it may would be cool to have this as default for changing videos at all (performance)

**Comment by sergioloyola** [comment]
sorry, but I do not understand much programming, make the modification that
you recommend, but I still can not keep the full screen. what am I missing

2018-03-05 18:17 GMT-03:00 Vinzenz Hersche <notifications@github.com>:

**Comment by hersche** [comment]
when you want to try it, download this version:
https://github.com/hersche/YouPHPTube/tree/stay-in-fullscreen
but several things has to be done, before it will work completly. at the moment, it only autoplay one video correctly, after you have to reload the page, select "next" video manualy, etc etc etc.

ONLY the technical aspect that it loads one video correctly and stays in fullscreen for this SINGLE change of the video means that it's on the right way. To make this working as you want it, it will use a lot of changes.

i do absolutly NOT recommend to use this on a productive server!

**Comment by hersche** [comment]
i close this because we have #760 which is more "clean" and a link to this issue. it needs to be done, but not to be duplicated.

**Comment by finesofttest** [comment]
When I have auto play, there is a way to keep the full screen for all the videos
Plz provide the solution of above #401

**Comment by DanielnetoDotCom** [comment]
Try this 

![image](https://user-images.githubusercontent.com/18009293/45597026-329d3380-b99c-11e8-806e-4d5004f92635.png)
