### ISSUE TITLE
[Idea]YouPHPTube Facebook Function

### ISSUE THREAD

**Issue by DemonRem** [DanielnetoDotCom/YouPHPTube#403]
Daniel i wonder if you can add useful function from facebook at last in my opinion

usually when streaming done by the software you can't continue at the same streaming video 
but facebook add function that even if the streaming stop and when you click streaming again it's resume the streaming you stop they add it as checkbox that they users can choose if doing or uncheck it to prevent the resume and create new stream , this can be amazing idea for YouPHPTube.

let me know you going doing in some point ;)

**Comment by DanielnetoDotCom** [comment]
humm, that is a great idea for sure. I will think about it.
