### ISSUE TITLE
question about the 120mins allowed video limit

### ISSUE THREAD

**Issue by joey2354** [DanielnetoDotCom/YouPHPTube#404]
My site is http://probeatz.easytube.club i'v upgraded to 120mins, so i'm just wondering how this works or if i have a bug.

So in videos panel i see this  "" You are hosting 184 minutes and 39 seconds of video and you have 120 minutes of storage""
it has gone over but i can still upload videos like i'v got unlimited, also when i log in as a test member i have, he also has the same "" you are hosting 184mins etc etc 
and he can also still upload over the limit. 

is this a bug ? 

thank you.

**Comment by DanielnetoDotCom** [comment]
Hi @joey2354 

Yea, it looks like a bug. for now it is working, but you may loose some content in the future.
I also sent you couple emails some days ago, asking you if you dont want to have a VPS, instead use easytube. a VPS is a way more powerful and Professional then easytube.

If you want to try a VPS let me know

**Comment by joey2354** [comment]
sorry i can't seem to find the emails you sent, so the vps ? i can try that
if it's better thank you.


what is it please ?  i'm no coder so excuse my dumbness at times :)

**Comment by DanielnetoDotCom** [comment]
I will send you an email to joeycool**@gmail.com agai ok?
(I guess is this one, I hide the last 2 chars)
