### ISSUE TITLE
Thumbnail Generation Issues

### ISSUE THREAD

**Issue by guru69** [DanielnetoDotCom/YouPHPTube#405]
When a video is uploaded from android created in portrait mode, the thumbnails are still created for landscape mode, leaving them all stretched. I think Exiftool can detect "Rotation" (0,90,180,270) and it appears to be detecting it right in the edit box (shows cutout for portrait thumb with landscape draping over it). Any easy fix or workaround for this?

Another issue is when large videos are uploaded that no thumbnail is created (get static noise pic)

![screenshot](https://user-images.githubusercontent.com/17300382/36937589-af40de72-1ee3-11e8-9272-b8781d45bfe1.png)

**Comment by DanielnetoDotCom** [comment]
Thanks I will remake the android app soon, and I will check this details
