### ISSUE TITLE
[Feature Request] Default Group for all Uploads

### ISSUE THREAD

**Issue by guru69** [DanielnetoDotCom/YouPHPTube#406]
I would love to see a Per User/Group option in User Account settings and Group Settings:
"All Uploads default to Group: ___"

This will prevent private videos or adult Youtubes from automatically appearing until shared with respective groups. 

Another option might be to add dropdown on the Upload section for Group. This would making organizing them much easier while uploading, instead of having to go to each one and set the group manually.

**Comment by DanielnetoDotCom** [comment]
Hi @guru69 

You can set up Default categories for each user

![image](https://user-images.githubusercontent.com/18009293/36978940-b1d6d79a-2064-11e8-9e61-17353cd4c44c.png)


Check the predefined category on demo site

**Comment by nospi** [comment]
Hi @DanielnetoDotCom, I'm not sure if @guru69 is asking for automatic video categories, but rather automatic user groups.

Categories (as far as I'm aware) don't necessarily alter access to files, simply organisation.

I'm looking for a similar feature - I'd like all uploaded videos to be put in to the "Authorized" user group (with an id of 1). I'd like to disable public videos and require a login to see these. All users are by default in the Authorized group.

I've tried to force this in object/videoAddNew.json.php on line 48 - by replacing `$_POST['videoGroups']` with: `array(1)`. It isn't having any effect at the moment, though from what I can find throughout the restr of the code the function will be expecting an array of integers representing group id's.

Is there any reason why this method should not be working?

**Comment by DanielnetoDotCom** [comment]
Hi

I just update the PredefinedCategory plugin to let you choose a default userGroup as well

![image](https://user-images.githubusercontent.com/18009293/42764341-c571374c-88eb-11e8-8d95-0bb662e2126f.png)

**Comment by nospi** [comment]
Cheers Daniel. 

I've just bought the plugin and undone any changes I'd made but I'm not getting any results.

I'm seeing the following in the streamer logs:

`[isSuggested:Video:private] => 0 `
`[videoGroups:Video:private] =>    `
`[videoAdsCount:Video:private] => 0 `

As far as I can tell my manual fix should have had an effect, but I'm not seeing any errors in the logs, other than an empty value for videoGroups.

**Comment by DanielnetoDotCom** [comment]
Hi,

You also will need to update your streamer
there are changes on streamer files as well.
