### ISSUE TITLE
Idea: Merge gif & jpg-upload

### ISSUE THREAD

**Issue by hersche** [DanielnetoDotCom/YouPHPTube#407]
Hello,

i always create my own preview-pictures and thinked about this: 

In /mvideos, under editing, there are 2 tabs, one for jpg, one for gif. This looks quite good, but it need some clicks.

Wouldn't make it sense to have there one upload-file only (accepting both formats) and show the pictures/progress on the right site of the upload-field?

this way, people would be able to upload both files at once, so it saves me work.

i would like to try this my own too, but i'm not shure when. Also i'm interessted about feedback, if there are contras or so..

best regards

vinz

**Comment by DanielnetoDotCom** [comment]
Hi @hersche I just don't understand how to upload both files at once?

**Comment by hersche** [comment]
mh, to compare: in the direct mp4-upload-site (in the streamer), i can put 1-n videos at once on that drag-and-drop-upload-field.

same should be possible for mvideos->edit->upload-fields.. just use one upload-field and clarfify in javascript or php which is gif, which jpg (and if it's none of both, it's still invalid of course).

**Comment by hersche** [comment]
according to https://stackoverflow.com/questions/181214/file-input-accept-attribute-is-it-useful

the input-field could look like this: `<input` type="file" `accept="image/*,video/*">`

so also

`<input` type="file" `accept="image/jpg,image/gif">`

for using the same field.

i just didn't found the whole way of uploading/generating the upload-button (after drop a picture/gif) etc..
