### ISSUE TITLE
Issue: video's with ad don't play

### ISSUE THREAD

**Issue by gkooistra** [DanielnetoDotCom/YouPHPTube#408]
When a Ad is finished playing, the video self will not played. 
Videos withoud ad's will play just fine.

In the consolelog of the browser:

```
VIDEOJS: ERROR: 
TypeError: player.updateSrc is not a function
Stack trace:
changeVideoSrc@https://videos.incotech.online/js/script.js:137:5
@https://videos.incotech.online/video/waar-staat-https-voor#:294:17
dispatch@https://videos.incotech.online/js/jquery-3.2.0.min.js:3:10264
add/q.handle@https://videos.incotech.online/js/jquery-3.2.0.min.js:3:8326
trigger@https://videos.incotech.online/js/jquery-3.2.0.min.js:4:5608
trigger/<@https://videos.incotech.online/js/jquery-3.2.0.min.js:4:6112
each@https://videos.incotech.online/js/jquery-3.2.0.min.js:2:2713
each@https://videos.incotech.online/js/jquery-3.2.0.min.js:2:1001
trigger@https://videos.incotech.online/js/jquery-3.2.0.min.js:4:6091
@https://videos.incotech.online/video/waar-staat-https-voor#:275:25
bound@https://videos.incotech.online/js/video.js/video.js:2232:12
on/data.dispatcher@https://videos.incotech.online/js/video.js/video.js:1867:15
trigger@https://videos.incotech.online/js/video.js/video.js:1994:5
trigger$$1@https://videos.incotech.online/js/video.js/video.js:2795:12
handleTechEnded_@https://videos.incotech.online/js/video.js/video.js:21245:5
bound@https://videos.incotech.online/js/video.js/video.js:2232:12
bound@https://videos.incotech.online/js/video.js/video.js:2232:12
on/data.dispatcher@https://videos.incotech.online/js/video.js/video.js:1867:15
video.js:489:5
```

Test server is running on Ubuntu 16.04 with php7 (mod-php) and got the latest version from GIT.
Tested it on FireFox and Chrome

**Comment by gvasquezj** [comment]
Maybe this information will help you

https://github.com/DanielnetoDotCom/YouPHPTube/issues/391

**Comment by gkooistra** [comment]
Found the problem.

File: view/js/script.js - Row 149
Replaced: "player.updateSrc(srcs);"
To: "player.src(srcs);"

Now it's working.

**Comment by DanielnetoDotCom** [comment]
Hi I saw your pull request thanks.

Can you reproduce this error on Demo site?

I need to check this before change the player.updateSrc(srcs); To: player.src(srcs);

**Comment by gkooistra** [comment]
Hello,

I've reproduced it and record it: [](https://videos.incotech.online/video/show-fix-for-ads-in-youphptube-code-change)

**Comment by DanielnetoDotCom** [comment]
I can see your error, but on demo site the same happened?
Maybe, I could not reproduce it. maybe you have a different videojs version.

**Comment by gkooistra** [comment]
I've reproduced it on the demo site. First disabled plugins I have not enabled and got the same issue.
After enabling the plugins one of the time, the problem disappeared by enabling the plugin "VideoResolutionSwitcher" and tested it multiple times.

So you could reproduce it by turning off the resulition Switch plugin.

**Comment by DanielnetoDotCom** [comment]
Thanks you absolutely right
This merge helps a lot
