### ISSUE TITLE
idea: make an advertisement available for all categories

### ISSUE THREAD

**Issue by gkooistra** [DanielnetoDotCom/YouPHPTube#409]
If you now want to place an advertisement under all categories, you have to create it for all categories one at a time.

I have a number of ads that apply to all categories (visit our website, support us via patreon, .....).

**Comment by nospi** [comment]
I came to the same conclusion, and had an idea though I haven't tested it yet.

Is it possible to create one root category, and nest all others under that? That will allow site-wide advertisements if I understand correctly.

**Comment by DanielnetoDotCom** [comment]
for now, the ads is managed on the Ads_server plugin, and all ads there are site wide 

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Ad-Server-Plugin
