### ISSUE TITLE
unique email for sign in

### ISSUE THREAD

**Issue by fablin** [DanielnetoDotCom/YouPHPTube#41]
Hi
I can create many accounts with the same email.
Is it possible to have an unique email for sign in ?
1 account = 1 email

Thanks
Fabrice

**Comment by DanielnetoDotCom** [comment]
The only check is a unique user name, email restrictions may be in futures releases.
Thanks for your consideration

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
