### ISSUE TITLE
unable to authenticate with google

### ISSUE THREAD

**Issue by danikuci1** [DanielnetoDotCom/YouPHPTube#410]
I recently discovered this project and am installing it. I'm pretty excited but am having some trouble with the google oauth plugin. If you could, please assist.

I went to `https://console.developers.google.com/apis` and got a, oauth 2.0 client ID credentials and verified my domain via TXT record. I added `objects/login.json.php?type=Google` and `plugin/MobileManager/oauth2.php?type=Google` to my authorized redirect URI list. I've waited a couple of hours, but the plugin still does not work.

Whenever I try to log in, the login fails and the address bar has the following error message in it, although youphotube displays no error itself:

```
https://mywebsite.com/user?error=Signed+API+request+has+returned+an+error.+HTTP+error+403.+Raw+Provider+API+response%3A+%7B%0A+%22error%22%3A+%7B%0A++%22errors%22%3A+%5B%0A+++%7B%0A++++%22domain%22%3A+%22usageLimits%22%2C%0A++++%22reason%22%3A+%22accessNotConfigured%22%2C%0A++++%22message%22%3A+%22Access+Not+Configured.+Google%2B+API+has+not+been+used+in+project+GOOGLENUM+before+or+it+is+disabled.+Enable+it+by+visiting+https%3A%2F%2Fconsole.developers.google.com%2Fapis%2Fapi%2Fplus.googleapis.com%2Foverview%3Fproject%3DGOOGLENUM+then+retry.+If+you+enabled+this+API+recently%2C+wait+a+few+minutes+for+the+action+to+propagate+to+our+systems+and+retry.%22%2C%0A++++%22extendedHelp%22%3A+%22https%3A%2F%2Fconsole.developers.google.com%2Fapis%2Fapi%2Fplus.googleapis.com%2Foverview%3Fproject%3DGOOGLENUM%22%0A+++%7D%0A++%5D%2C%0A++%22code%22%3A+403%2C%0A++%22message%22%3A+%22Access+Not+Configured.+Google%2B+API+has+not+been+used+in+project+GOOGLENUM+before+or+it+is+disabled.+Enable+it+by+visiting+https%3A%2F%2Fconsole.developers.google.com%2Fapis%2Fapi%2Fplus.googleapis.com%2Foverview%3Fproject%3DGOOGLENUM+then+retry.+If+you+enabled+this+API+recently%2C+wait+a+few+minutes+for+the+action+to+propagate+to+our+systems+and+retry.%22%0A+%7D%0A%7D%0A.

```

Is it possible to capture the JSON payload that youphptube send to google? Or do you have some suggestion for what I could try?

thanks for your help.

**Comment by DanielnetoDotCom** [comment]
Hi

You must enable a couple API's for things to work as expected.

First go to https://console.developers.google.com and make sure under "APIs" that you have the  "Google+ API" enabled. Once that is done you should no longer see that error message.

Also make sure you put the Valid OAuth redirect URIs on google API?
![image](https://user-images.githubusercontent.com/18009293/37050927-ed76f9ca-2153-11e8-9d39-94430a3525ef.png)

**Comment by danikuci1** [comment]
Eureka! I did not have the google+ api active, I only created an oauth credential. Once I enabled google+, it started working ok.
