### ISSUE TITLE
thumbnails

### ISSUE THREAD

**Issue by wilsondanquah** [DanielnetoDotCom/YouPHPTube#414]
I have tried youPHPTube on localhost and all uploaded videos look same. They take up the look of the first uploaded video even though they are different. is there a way to upload thumbnails or a way to make all the videos look different.

**Comment by DanielnetoDotCom** [comment]
You can upload a thumbs on videos manager page, 

![image](https://user-images.githubusercontent.com/18009293/37098431-9c2a4a46-21fc-11e8-97ef-cee8a4ee2da3.png)


or you can get the plug-in to automatic extract the thumbs and gif from the video.
Check this
https://github.com/DanielnetoDotCom/YouPHPTube/issues/246
