### ISSUE TITLE
Embed - Extra white image

### ISSUE THREAD

**Issue by Dorthra** [DanielnetoDotCom/YouPHPTube#415]
First of all, I would like to thank you for the script :).

when we insert the video as embed, an extra white image appears.
example picture: https://i.hizliresim.com/Md8mra.png

there is an excess under the video. demo website and everywhere the same.

and finally, we bought a video resolution switcher. how can we change the HD SD low names here?

@DanielnetoDotCom 
@TomOndiba

**Comment by DanielnetoDotCom** [comment]
About the extra white space you can change the iframe size.

about the SD and HD uppercase you cant change it

**Comment by Dorthra** [comment]
No relevance to iframe size. the extra whiteness at the bottom always comes out.

@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
you have to decrease the height only, until it fits on the video

**Comment by Dorthra** [comment]
this is due to: https://i.hizliresim.com/p6kvVo.png
there is a cursor that goes down in the embed image.

must be:https://i.hizliresim.com/y0129n.png

phptube:https://demo.youphptube.com/videoEmbed/deus-nao-existe-ele-e
youtube:https://www.youtube.com/embed/Qs_YkcqVU6c

what file should I edit to fix this?. I do not want to drop the height

**Comment by Dorthra** [comment]
@DanielnetoDotCom thanks for the quick answers. I look forward to your reply

**Comment by Dorthra** [comment]
@DanielnetoDotCom 
I need your help please :)

**Comment by DanielnetoDotCom** [comment]
Try to add scrolling="no" attribute to the iframe

**Comment by Dorthra** [comment]
@DanielnetoDotCom 
it is useless.
are not you the script coder?
there must be a solution ? it's a very simple thing
which file should I edit ?

thanks.

**Comment by DanielnetoDotCom** [comment]
If you want to try to edit the file, try to edit this one: https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/view/videoEmbeded.php

**Comment by Dorthra** [comment]
@DanielnetoDotCom  Thanks
what should I change here?

**Comment by DanielnetoDotCom** [comment]
You may change some CSS or HTML, I am not sure.

But one thing, if you make the embed background the same as your site, maybe have a nicer looking.

BTW, this problem may be fixed in the future

**Comment by Dorthra** [comment]
thank you very much @DanielnetoDotCom 

please teach me how to do :)

**Comment by heymam2bab** [comment]
@DanielnetoDotCom we bought the plugin from you
 
plugin name : VideoResolutionSwitcher (VideoResolutionSwitcher)

but the plugin says "hd" "sd" "low"
how can we change this plug-in to "1080" p "720" "480p"?

**Comment by DanielnetoDotCom** [comment]
@heymam2bab  Sorry I do not understand what you want

**Comment by DanielnetoDotCom** [comment]
@Dorthra You need to have some CSS/HTML/PHP background to do it.
