### ISSUE TITLE
Mod Rewrite is not enabled

### ISSUE THREAD

**Issue by muazzamazaz** [DanielnetoDotCom/YouPHPTube#417]
I am getting the following error when try to install it at centoes server where mod_rewrite apache module already activated

> In order to use mod_rewrite you can type the following command in the terminal:
> a2enmod rewrite
> 
> Restart apache2 after
> /etc/init.d/apache2 restart

**Comment by Dorthra** [comment]
already enabled. ignore and continue

**Comment by muazzamazaz** [comment]
it gives message

> Unknown Error

 when I try to continue

**Comment by muazzamazaz** [comment]
http://cypherkiller.com/YouPHPTube/install/index.php

**Comment by Dorthra** [comment]
Are you sure you entered your database information correctly?

**Comment by DanielnetoDotCom** [comment]
Check your apache log file

**Comment by muazzamazaz** [comment]
There is nothing in apache log file for this issue
