### ISSUE TITLE
Cannot change first page style

### ISSUE THREAD

**Issue by danikuci1** [DanielnetoDotCom/YouPHPTube#418]
I am unable to change the first page style after loading plugins for other styles. It seems that the only selectable option under configuration is "YouTube".

Do I need to do something besides load the plugin I'd like to use? I've tried rebooting the server but it does not help. Please advise.

![image](https://user-images.githubusercontent.com/5247319/37166610-5ad75152-22b4-11e8-97fb-d868a78efc38.png)

![image](https://user-images.githubusercontent.com/5247319/37166654-75e22f1c-22b4-11e8-900b-f6618368b9f1.png)

**Comment by DanielnetoDotCom** [comment]
First page mode now, there is only youtube.

To change it you need to enable plugins.

**Comment by danikuci1** [comment]
is that not what I have done? see screenshot

**Comment by DanielnetoDotCom** [comment]
Facebook Style is not working?
Do you have cache plugin enabled?

**Comment by danikuci1** [comment]
facebook style is not working. neither is netflix.

cache plugin is not enabled.

**Comment by DanielnetoDotCom** [comment]
Stranger, can you try it from another browser

**Comment by danikuci1** [comment]
originally working with chrome. just tried in edge and IE.

under configurations -> first page mode only "Youtube" is available as an option.

under plugins I have the following first page plugins enabled: Facebook Tube (FBTube) and YouPHPFlixHybrid (YouPHPFlixHybrid)

**Comment by DanielnetoDotCom** [comment]
Disable one of them Facebook Tube or YouPHPFlixHybrid

**Comment by danikuci1** [comment]
well this is weird. i disabled fbtube, so only YouPHPFlixHybrid is active. The only option under site configurations is still youtube, however, the theme has changed to YouPHPFlixHybrid!  

it doesn't make sense to me.

![image](https://user-images.githubusercontent.com/5247319/37168008-5d673fdc-22b8-11e8-8c32-08da0d8a6307.png)

**Comment by DanielnetoDotCom** [comment]
That is what I mean on the first answer 

> First page mode now, there is **only** youtube. 
> To change it you need to enable plugins.

**Comment by danikuci1** [comment]
just logged out, cleared cookies etc, and restarted apache. same results.

**Comment by danikuci1** [comment]
oh, so you're saying that drop down menu is deprecated?

**Comment by DanielnetoDotCom** [comment]
First page mode  is an old option it will be disabled soon

**Comment by DanielnetoDotCom** [comment]
Yes deprecated

**Comment by danikuci1** [comment]
ok, that mode did confuse me. might want to add clear instructions to only enable one firstpage plugin at a time when you make the update to remove the drop down menu for first page mode.

i've tested them all and it is working as expected. closing issue.
