### ISSUE TITLE
Turn off Share button / feature by user and/or group

### ISSUE THREAD

**Issue by dschoonm** [DanielnetoDotCom/YouPHPTube#419]
This is going to be very handy for storing and sharing videos but I do not want users to have the option to share through facebook / twitter / G+  but email a link would be ok.  I want them to always have to sign in to view - no uploads to Facebook etc. via the Share button which do not require authentication to view.  Email link should throw an auth dialog so email is ok to share.

Blessings!

**Comment by DanielnetoDotCom** [comment]
Hi, Thanks for the Idea, it may be implemented in the future
