### ISSUE TITLE
Live Plug-in Parameters URLs Case Sensitive

### ISSUE THREAD

**Issue by dschoonm** [DanielnetoDotCom/YouPHPTube#421]
After installing YouPHPTube and configuring nginx for OBS streaming, all was well except that the player links were broken in the Live plug-in parameters page.  I believe the install had inserted Live in the URLs with a capital "L".   After trouble-shooting everything else, with no success, changed "L" in Live to lower case in the Player URL's and suddenly all worked as designed.

Amazing software.  Many thanks.

**Comment by DanielnetoDotCom** [comment]
I'm glad you like it :) thanks for sharing your experience
