### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method mysqli_stmt::get_result

### ISSUE THREAD

**Issue by Chipdjf** [DanielnetoDotCom/YouPHPTube#422]
I had mod_rewrite is not enabled.  checked the server mod_rewrite is enabled. so i installed and this is what I get.
after install I get this Error
`Fatal error: Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home/chipdjf/public_html/derolds.com/video/objects/plugin.php:194 Stack trace: #0 /home/chipdjf/public_html/derolds.com/video/plugin/YouPHPTubePlugin.php(162): Plugin::getEnabled('c4fe1b83-8f5a-4...') #1 /home/chipdjf/public_html/derolds.com/video/view/include/head.php(5): YouPHPTubePlugin::isEnabled('c4fe1b83-8f5a-4...') #2 /home/chipdjf/public_html/derolds.com/video/view/modeYoutube.php(111): include('/home/chipdjf/p...') #3 /home/chipdjf/public_html/derolds.com/video/view/index.php(21): require('/home/chipdjf/p...') #4 {main} thrown in /home/chipdjf/public_html/derolds.com/video/objects/plugin.php on line 194`

**Comment by karen20ced4** [comment]
Your system is missing the mysqlnd driver!

If you are able to install new packages on your (Debian/Ubuntu-based) server, install the driver:

sudo apt-get install php5-mysqlnd

and then restart your web server:

sudo /etc/init.d/apache2 restart

**Comment by Chipdjf** [comment]
I am on godaddy server

**Comment by DanielnetoDotCom** [comment]
make sure you have mysqlnd lib on it

**Comment by Chipdjf** [comment]
OK I will check thanks

**Comment by Chipdjf** [comment]
Yes its on it

**Comment by DanielnetoDotCom** [comment]
then you should not have this: `Uncaught Error: Call to undefined method mysqli_stmt::get_result()`

**Comment by Chipdjf** [comment]
I installed it in a sub directory. I will reinstall and see what happens.

**Comment by hersche** [comment]
godady does not support mysqlnd on webspace, only on a vps. i had this with a customer and now, there's a solution which works also withouth mysqlnd. so a update should be enough and we can close this?

**Comment by hersche** [comment]
no feedback, so i close it.
