### ISSUE TITLE
pagination problem

### ISSUE THREAD

**Issue by fablin** [DanielnetoDotCom/YouPHPTube#43]
Hi
I have a problem with pagination on the YouTube mode  page in the column Up Next.
Example from your online demo: 
https://demo.youphptube.com/video/roma11
If I click on Page 3, I get a page without videos and message:
Warning! We have not found any videos or audios to show.

If I click on Page 2, there is a redirection to Gallery mode  page. 
Could it be possible to stay on the same page mode YouTube page and just update the Up Next column ?

Thanks
Fabrice

**Comment by DanielnetoDotCom** [comment]
Thanks I will try to fix this or get some help to do

**Comment by DanielnetoDotCom** [comment]
Hi, thanks for your help, I think this issue is fixed, please update your files.
Remember to update youphptube on configuratio menu
