### ISSUE TITLE
Youtube Upload

### ISSUE THREAD

**Issue by deaf-tv** [DanielnetoDotCom/YouPHPTube#430]
400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, http://deaf-tv.eu/YouPHPTube/objects/youtubeUpload.json.php, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/926584776662-bp24cthdu9ef2lu0bstskqgrgr47tvph.apps.googleusercontent.com?project=926584776662

Learn more

Request Details
That’s all we know.

**Comment by DanielnetoDotCom** [comment]
Yes, you need to add the correct URI

![image](https://user-images.githubusercontent.com/18009293/37400772-b3d740c8-2764-11e8-8e4c-bb780160646a.png)

**Comment by hersche** [comment]
@deaf-tv the 404 come from a wrong link.. http://deaf-tv.eu/objects/youtubeUpload.json.php here it's working / giving another answer.

also daniel seem to answered the question about url's needed on google's side..

> Learn more

;)
