### ISSUE TITLE
Footer Menu

### ISSUE THREAD

**Issue by deaf-tv** [DanielnetoDotCom/YouPHPTube#431]
Footer Menu add build

![footer-menu](https://user-images.githubusercontent.com/17132516/37375503-2bbcba40-2720-11e8-949d-86ebbfc53bb5.png)

**Comment by DanielnetoDotCom** [comment]
On the Customize plugin you can add a custom html code on the footer

**Comment by hersche** [comment]
seems to be done, since there is a plugin for it? reopen when i'm wrong
