### ISSUE TITLE
LIve Streaming  not working

### ISSUE THREAD

**Issue by brajeshrgupta** [DanielnetoDotCom/YouPHPTube#432]
Hi

I have completed setup of encoder and Streamer site and all is working fine.
But live streaming and live chat is not working. We are able to connect to server via OBS but stream is showing offline. 

Please share what details yo required to check and resolve.
Please help how we can resolve this.

**Comment by DanielnetoDotCom** [comment]
check this:

https://github.com/DanielnetoDotCom/YouPHPTube/issues/138
https://github.com/DanielnetoDotCom/YouPHPTube/issues/299
https://github.com/DanielnetoDotCom/YouPHPTube/issues/378

**Comment by oclwppri** [comment]
I have the same issue
