### ISSUE TITLE
Nothing happens when trying to encode video

### ISSUE THREAD

**Issue by nbenm** [DanielnetoDotCom/YouPHPTube#434]
Hi,

When I try to encode video, nothing happens.
Here's what is displayed on the screen (see attached picture)
Any idea about what's happening.

Thanks

<img width="414" alt="screen" src="https://user-images.githubusercontent.com/4224717/37403651-d57a619e-278f-11e8-82be-c62ee39358cc.png">

**Comment by DanielnetoDotCom** [comment]
check log file https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube
