### ISSUE TITLE
[Bug] exception when change category in /mvideos

### ISSUE THREAD

**Issue by hersche** [DanielnetoDotCom/YouPHPTube#437]
when i want to sort under /mvideos by category, a error-field appears, saying "Sorry!"
In JS-Console i get a bit more:
Object { error: "Permission denied" }
mvideos:661:49
Object { error: "Permission denied" }

of course i'm logged in and it's the same after a refresh (still loged in)

maybe a very small thing for you?

**Comment by DanielnetoDotCom** [comment]
I think you misunderstood, the button is not a sort. it is to change the selected videos to the choosen category

**Comment by hersche** [comment]
ooooh, ok, very nice, this will save me a lot of time, thank you!

**Comment by DanielnetoDotCom** [comment]
you right!

**Comment by DunklerPhoenix** [comment]
Heho. Sorry for opening this old thing up, but it's still saying "Sorry" :D

**Comment by DanielnetoDotCom** [comment]
Check your log file

**Comment by DunklerPhoenix** [comment]
I know why this Message comes, but i think the Messages should be more informative
