### ISSUE TITLE
Plugin Add 

### ISSUE THREAD

**Issue by deaf-tv** [DanielnetoDotCom/YouPHPTube#439]
Shoutbox build ?

**Comment by DanielnetoDotCom** [comment]
what?

**Comment by deaf-tv** [comment]
![shoutboxwidget](https://user-images.githubusercontent.com/17132516/37487238-38ac26ec-2891-11e8-8076-2ad0aab2024c.png)

**Comment by hersche** [comment]
not very explained and inactive.. i close it.
