### ISSUE TITLE
These features would be nice to implement

### ISSUE THREAD

**Issue by ThejeswarReddy** [DanielnetoDotCom/YouPHPTube#44]
1. Design and layout customizable for admin like color and font style and size(the present font size is bit small). with responsive layout and some other minor changes.
2. Mouse :hover show menu and :not(:hover) hide menu. 
3. How about .GIF's rather than boring .JPG thumbnails so that user can see video glimps at once.
4. Sub menu under the logo be auto centerd as new categories added(for now it's completely to the left)
5. Video sorting by LIKES and COMMENTS or may be our own system because i just read that youtube view counts can be hacked.
6. Multisize player screen (the present default one is Theatre mode) and yeah subtitles(may be for later)
7.  Replay button and in player Thumbnails after watching the video
8. Profile Timeline as facebook has, to see what user did on the tube which must be similar to youtube history but should be like facebook timeline option.

These are some idea's i got for now if i get more ideas as i surf i'll try to say so that our tube be the best.

**Comment by DanielnetoDotCom** [comment]
II really really enjoyed all of your suggestions, I'll put everything on the road.
I have hope that I will find help to implement them as soon as possible.

**Comment by DanielnetoDotCom** [comment]
I think I could implement your first feature
https://tutorials.youphptube.com/video/how-to-change-the-theme-of-youphptube-ver-3-1

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
