### ISSUE TITLE
Forum Code 

### ISSUE THREAD

**Issue by deaf-tv** [DanielnetoDotCom/YouPHPTube#440]
WoltLab Suite™ 3.0.13

Youtube yes
Clipbucket yes
YouPHPTube no

BB Code and Embed Object
no iframe

YouPHPTube add Embed Object, BBCode

-------------------------------------------------------------

iframe:  Blog and Homepage
BBCode:   Forum
Embed Object:  Forum, Homepage, Blog

![code](https://user-images.githubusercontent.com/17132516/37490626-6c88dfe6-289b-11e8-8c43-1917bc294b4c.png)

**Comment by DanielnetoDotCom** [comment]
Great, I will take a look on that

**Comment by deaf-tv** [comment]
https://www.woltlab.com
