### ISSUE TITLE
save stream nothing happen

### ISSUE THREAD

**Issue by khalil1123** [DanielnetoDotCom/YouPHPTube#442]
hi 
when i push button save stream nothing happen just  show " pressing" and  nothing change stay in the same page not go to live page as public and i dont have notification like video i watch to you  
what must do ? 
thanks

**Comment by DanielnetoDotCom** [comment]
Hi

Check your log file
Also make sure you install the tables of this plugin

If you are not sure how to transmit check this https://tutorials.youphptube.com/video/youphptube-video-stream-with-obs-and-vmix

**Comment by DanielnetoDotCom** [comment]
If you not sure how to find the log file, check here https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How to find errors on YouPHPTube

**Comment by khalil1123** [comment]
[17-Mar-2018 22:50:10 Europe/Helsinki] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/html/YouPHPTube/plugin/Live/Live.php:86
Stack trace:
#0 /var/www/html/YouPHPTube/plugin/Live/stats.json.php(22): Live->getStatsObject()
#1 {main}
  thrown in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 86
[17-Mar-2018 22:50:10 Europe/Helsinki] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/html/YouPHPTube/plugin/Live/Live.php:86
Stack trace:
#0 /var/www/html/YouPHPTube/plugin/Live/stats.json.php(22): Live->getStatsObject()
#1 {main}
  thrown in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 86
[17-Mar-2018 22:53:10 Europe/Helsinki] Array
(
    [scheme] => rtmp
    [host] => 10.20.30.221
    [path] => /live
    [query] => p=202cb962ac59075b964b07152d234b70
)

[17-Mar-2018 22:53:10 Europe/Helsinki] Array
(
    [p] => 202cb962ac59075b964b07152d234b70
)

**Comment by khalil1123** [comment]
![screenshot from 2018-03-17 22-55-07](https://user-images.githubusercontent.com/18646882/37559885-7a7d92d0-2a36-11e8-9889-ada59abc8a63.png)

**Comment by DanielnetoDotCom** [comment]
Your problem is this ...

PHP Fatal error: Uncaught Error: Call to undefined function simplexml_load_string() 

It is not hard to fix try Google for that

**Comment by khalil1123** [comment]
hi 
i try alot  by google and more solution 
but nothing :: hint : i have 4 version fot php in my server  5.6 ,  7.0 , 7.1 , 7.2 
the same error : 
#1 {main}
  thrown in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 86
[18-Mar-2018 20:22:49 Europe/Helsinki] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/html/YouPHPTube/plugin/Live/Live.php:86
Stack trace:
#0 /var/www/html/YouPHPTube/plugin/Live/stats.json.php(22): Live->getStatsObject()
#1 {main}
  thrown in /var/www/html/YouPHPTube/plugin/Live/Live.php on line 86

i need some hints from you and i will make it 
many thanks

**Comment by khalil1123** [comment]
this my function in live php
    function getStatsObject() {
        ini_set('allow_url_fopen ', 'ON');
        $xml = simplexml_load_string($this->get_data($this->getStatsURL()));
        return $xml;

**Comment by nightstryke** [comment]
Your PHP version and installation needs one of these plugins installed to work.
`php-xml or php-simplexml`

**Comment by DanielnetoDotCom** [comment]
@khalil1123 you have to figure out how to make simplexml_load_string function work

**Comment by khalil1123** [comment]
thnaks alot for support i will tell you what i do : 
first i install php-xml and  php simplexml 
then i caught this error   
 PHP Fatal error:  Uncaught Error: Call to undefined function curl_init()
i solved it by install  php-curl 
and  all things good 
but i open from windows like chrome  and Firefox give me that : 
The media could not be loaded, either because the server or network failed or because the format is not supported.
what i do ?

**Comment by DanielnetoDotCom** [comment]
now check the Streamer log file.

**Comment by khalil1123** [comment]
Undefined index: filename in /var/www/html/YouPHPTube/plugin/Live/view/modeYoutubeLive.php on line 17

**Comment by DanielnetoDotCom** [comment]
It is a notice, You can try to not display errors notice (usually it is the default)

The `PHP Notice: Undefined index: filename in /var/www/html/YouPHPTube/plugin/Live/view/modeYoutubeLive.php on line 17` is not a problem

Also I am sending a fix for it anyway

**Comment by khalil1123** [comment]
hi 
the last problem solved now that:
im_resize: Function does not exists: imagecreatefromjpeg

**Comment by DanielnetoDotCom** [comment]
You need to install GD Library, please google for that.

**Comment by nightstryke** [comment]
@khalil1123 Install GD Library, install these dependencies `php-gd`
please check which version of php you are using because sometimes you have to have the version number before the gd like this `php7.0-gd`

**Comment by hersche** [comment]
those libs are now also in the wiki, so it should be more clear now and the problem seems solved. i close it out of this.
