### ISSUE TITLE
YouPHPTube Log Error

### ISSUE THREAD

**Issue by nightstryke** [DanielnetoDotCom/YouPHPTube#444]
@DanielnetoDotCom can you explain this error for me that I have in `youphptube.log`?

`[18-Mar-2018 22:17:09 US/Eastern] PHP Notice:  Undefined index: filename in /path/to/youphptube/domain.org/public_html/plugin/Live/view/modeYoutubeLive.php on line 17`

**Comment by DanielnetoDotCom** [comment]
This is just a notice, no worries. but I will fix it later

**Comment by khalil1123** [comment]
wait you @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Just fixed, please update your files

**Comment by hersche** [comment]
fixed, so i close it.
