### ISSUE TITLE
Unable to install on QNAP TS853A with 4.3.4 Software

### ISSUE THREAD

**Issue by apc005** [DanielnetoDotCom/YouPHPTube#446]
Hi
I'm trying to install youphptube on QNAP TS853A with 4.3.4 Software. I installed Qapache, youphptube, changed the php.ini and restarted all. When I save all the parameters I'm redirected to http://myqnap:48171/install/index.php which is blank. The database is cretaed (checked with phpmyadmin) but when I fo to http://myqnap:48171 all I get is a 500 error...

Any hint ?

Thx

**Comment by DanielnetoDotCom** [comment]
check the apache error log.

**Comment by apc005** [comment]
Hi
In /opt/Qapache/var/logs/error_log I found a lot of "[example_hooks:notice] [pid 32217:tid 140202872031104] x_monitor()" and these errors :

PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
PHP Warning:  PHP Startup: xattr: Unable to initialize module\nModule compiled with module API=20160303\nPHP    compiled with module API=20170718\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: solr: Unable to initialize module\nModule compiled with module API=20160303\nPHP    compiled with module API=20170718\nThese options need to match\n in Unknown on line 0
PHP Warning:  Xdebug MUST be loaded as a Zend extension in Unknown on line 0
[Mon Mar 19 15:44:47.420499 2018] [mpm_event:notice] [pid 12128:tid 139766058092416] AH00489: Apache/2.4.29 (Unix) OpenSSL/1.0.2n PHP/7.2.3 SVN/1.9.7 configured -- resuming normal operations
[Mon Mar 19 15:44:47.420587 2018] [core:notice] [pid 12128:tid 139766058092416] AH00094: Command line: '/share/CACHEDEV1_DATA/.qpkg/Qapache/bin/httpd -f /share/CACHEDEV1_DATA/.qpkg/Qapache/etc/httpd.conf'
[Mon Mar 19 15:45:10.809693 2018] [mpm_event:notice] [pid 12128:tid 139766058092416] AH00491: caught SIGTERM, shutting down
[Mon Mar 19 15:45:21.791691 2018] [ssl:warn] [pid 32217:tid 140202872031104] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Mon Mar 19 15:45:21.792083 2018] [lbmethod_heartbeat:notice] [pid 32217:tid 140202872031104] AH02282: No slotmem from mod_heartmonitor


Not sure it helps :-(

**Comment by apc005** [comment]
Just re-tried an install. Nothing in error_lo. In access_log only : 

172.31.241.100 - - [19/Mar/2018:19:52:31 +0100] "GET / HTTP/1.1" 302 -
172.31.241.100 - - [19/Mar/2018:19:52:32 +0100] "GET /install/index.php HTTP/1.1" 200 12500
172.31.241.100 - - [19/Mar/2018:19:54:16 +0100] "POST /install/checkConfiguration.php HTTP/1.1" 200 418
172.31.241.100 - - [19/Mar/2018:19:54:18 +0100] "GET /install/index.php HTTP/1.1" 500 698

**Comment by apc005** [comment]
I enabled error reporting in php.ini and got : 

<br />
<font size='1'><table class='xdebug-error xe-fatal-error' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Cannot use 'Object' as class name as it is reserved in /share/CACHEDEV1_DATA/.qpkg/YouPHPTube/www/objects/Object.php on line <i>2</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>403504</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/share/CACHEDEV1_DATA/.qpkg/YouPHPTube/www/install/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0008</td><td bgcolor='#eeeeec' align='right'>407232</td><td bgcolor='#eeeeec'>require_once( <font color='#00bb00'>'/share/CACHEDEV1_DATA/.qpkg/YouPHPTube/www/videos/configuration.php'</font> )</td><td title='/share/CACHEDEV1_DATA/.qpkg/YouPHPTube/www/install/index.php' bgcolor='#eeeeec'>.../index.php<b>:</b>23</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0245</td><td bgcolor='#eeeeec' align='right'>408120</td><td bgcolor='#eeeeec'>require_once( <font color='#00bb00'>'/share/CACHEDEV1_DATA/.qpkg/YouPHPTube/www/objects/include_config.php'</font> )</td><td title='/share/CACHEDEV1_DATA/.qpkg/YouPHPTube/www/videos/configuration.php' bgcolor='#eeeeec'>.../configuration.php<b>:</b>18</td></tr>
</table></font>

**Comment by DanielnetoDotCom** [comment]
Please Update your YPT version with the master branch version on github

**Comment by apc005** [comment]
Not so easy. I rely on the Qnap Club packaged version.... Do you know who is in charge of this package ? Thx

**Comment by DanielnetoDotCom** [comment]
Hi

what is **Qnap Club packaged version**??

This problem is fixed on the newest version

**Comment by apc005** [comment]
Hi
YouPhpTube version (on Qnap Club AppStore) is 4.0.2
I installed the latest revision from githup and it woks perfectly. The only bug I found is that the encoder sets the duration to EE:EE:EE instead of the real video length but it's not very important.
Thx

**Comment by DanielnetoDotCom** [comment]
Great

About encoder check the error log of the encoder

**Comment by hersche** [comment]
this is about a old solution, seems to be solved and version 5.4 is very diffrent meanwhile. i close it.
