### ISSUE TITLE
torrent request?

### ISSUE THREAD

**Issue by loso20p** [DanielnetoDotCom/YouPHPTube#447]
can you add a torrent downloading plugin for this script? or not possible?

**Comment by DanielnetoDotCom** [comment]
I am not sure how to do it.

Also I don't know if it is priority for the market, we have so many features on the road right now.

**Comment by loso20p** [comment]
o ok are u added new plugins in the store

**Comment by DanielnetoDotCom** [comment]
Yes I did, I am always trying to make new features

**Comment by DanielnetoDotCom** [comment]
Import from youtube and other videos sites, you can use the encoder. this option is there by default.

**Comment by hersche** [comment]
wouldn't torrents need a tracker?
i just did a quick-search but i've only found node-js-implementations (as i searched for php).

**Comment by loso20p** [comment]
@DanielnetoDotCom i know  that but i mean like we an importer where u search for the video via keyword or channel and select or the videos u want n import them directly without encoding them using a youtube api.

**Comment by loso20p** [comment]
@hersche i was thinking more like we can use the torrent or magnet file  and just download the torrent to our server like we already do when we use a an external link and then jus encode the file

**Comment by abamilod** [comment]
Or maybe download file from RSS Feed, you can update the feeds after you finished download it using torrent or magnet file with other app.
