### ISSUE TITLE
Sub categories

### ISSUE THREAD

**Issue by hughmclain** [DanielnetoDotCom/YouPHPTube#45]
Hi Daniel, love the project. 

Is there a way to add sub categories for videos? I have several categories that I would like to sub divide different videos into. e.e. Cat1, Cat2, Cat3 with sub categories 1.1, 1.2, 2.1, 2.2 etc..

**Comment by ThejeswarReddy** [comment]
yes login as username:- admin  password :- 123 . left next to the LOGO you'll see the menu button , click on it and choose categories . There you can add delete modify your sub-categories and graphicons. is this what you were asking OR Sub-categories under each sub-category.?

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
