### ISSUE TITLE
Fatal error: Can't use function return value in write context in C:\wamp\www\fans\objects\user.php on line 140

### ISSUE THREAD

**Issue by onyedika135** [DanielnetoDotCom/YouPHPTube#452]
Please can any one help me with this error. I have little knowledge on php codes. This error appeared after submitting my installation form. All database queries went correctly. 
"Fatal error: Can't use function return value in write context in C:\wamp\www\fans\objects\user.php on line 140".
Here is the code line #140 " static function getNameIdentification(){
        $advancedCustom = YouPHPTubePlugin::getObjectDataIfEnabled("CustomizeAdvanced");
        if(self::isLogged()){
            if(!empty(self::getName()) && empty($advancedCustom->doNotIndentifyByName)){
                return self::getName();
            }
            if(!empty(self::getMail()) && empty($advancedCustom->doNotIndentifyByEmail)){
                return self::getMail();
            }
            if(!empty(self::getUserName()) && empty($advancedCustom->doNotIndentifyByUserName)){
                return self::getUserName();
            }
        }
        return __("Unknown User");
    }
    
    /**
     * return an name to identify the user from database
     * @return String
     */"
This is line 137- 156.  line 140 is " if(!empty(self::getName()) && empty($advancedCustom->doNotIndentifyByName)){
                return self::getName();"

**Comment by DanielnetoDotCom** [comment]
What PHP Version are you using?
I cant reproduce this error here.

**Comment by hersche** [comment]
no feedback since a long time. please reopen it if the problem still exists.
