### ISSUE TITLE
partner program 

### ISSUE THREAD

**Issue by chinli12** [DanielnetoDotCom/YouPHPTube#46]
I think it will sell more if you add partner program like YouTube, which allowed user to earn money through Ad that runs on their videos

**Comment by DanielnetoDotCom** [comment]
Hi
How is this partner program?
In youphptube you already can earn money through google ads and independent video ads as well.
What is your idea?

**Comment by chinli12** [comment]
My idea is revenue shearing, when user sign up, he create a chanel and partner with adsens,like YouTube he will have his dashboard to view his earnings and analysis

**Comment by DanielnetoDotCom** [comment]
I see, chanels and a better profile (Like Facebook) are on the road. it is a big change on YouPHPTube but i am thinking and want to do. it will take some time to release, but it will.

**Comment by DanielnetoDotCom** [comment]
Thanks for your ideas

**Comment by chinli12** [comment]
Can you add it

**Comment by DanielnetoDotCom** [comment]
As i mention before it is a big change on YouPHPTube, it will take some time to be done, But I will add it for sure

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
