### ISSUE TITLE
Speed up encoding

### ISSUE THREAD

**Issue by webbaldo** [DanielnetoDotCom/YouPHPTube#48]
Hi there love the project!

Is there anyway to speed up the encoding? I have a server with high resources but even small videos are taking a while to encode.

Can I speed up ffmpeg encoding somehow? Had a look through the configuration php but cant find any options?

M.Webb

**Comment by DanielnetoDotCom** [comment]
Hi, you will need to change the ffmpeg script in the advanced configurations.
Search on google how to use multiple CPU cores/threads on ffmpeg

**Comment by DanielnetoDotCom** [comment]
If you get success, please share your results here.

**Comment by webbaldo** [comment]
Hi , sorted it by just adding the -ultrafast profile switch to the ffmpeg options in advanced options.

Filesize doesn't seem to have increased much.

I've also turned off webm as we don't need it for our internal server.
