### ISSUE TITLE
Not deleting from videos folder & profile picture

### ISSUE THREAD

**Issue by codec212** [DanielnetoDotCom/YouPHPTube#5]
I followed all steps in tutorial video and from https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x but found some of things below not working.

1. Whenever I deleted video from MyVideos it actually delete from the list but not deleting from videos folder (/var/www/html/YouPHPTube/videos). The original file and image still there.
2. There's no option to change profile picture.

Do I miss some configuration?

**Comment by DanielnetoDotCom** [comment]
Hi, I'm glad you found these problems. Sorry for the delay in responding, but we were correcting the issues before we answered.
To update these problems, simply update the files with the files in github.

Whenever you delete a video the files in the folder (/var/www/html/YouPHPTube/videos) will be also deleted now.
To deal with orphaned files (which have not been deleted previously) you can use a tool that we just did.
Go to "My Videos", you will see the "Orphan Files"

![image](https://cloud.githubusercontent.com/assets/18009293/25673117/b3b188f6-300c-11e7-8db1-59eb7e83838b.png)

On the orphans page you will find a list of all orphans files, just click on the red button to delete them all

![image](https://cloud.githubusercontent.com/assets/18009293/25673210/f080cb5c-300c-11e7-9f19-a94a8688d0b7.png)

About the profile picture, we just add this function, just go to "My Account"

![image](https://cloud.githubusercontent.com/assets/18009293/25673311/3f74324e-300d-11e7-8a09-b437e128354e.png)

Thanks I hope you enjoy

**Comment by codec212** [comment]
I've click update and do it says my system is up to date. (see image). When I clone from github it has another problem won't saving (processing bar stucked forever and never save).
![php20](https://cloud.githubusercontent.com/assets/28330621/25697095/d8c06ea0-30e3-11e7-915a-8add77d8f66f.JPG)

**Comment by DanielnetoDotCom** [comment]
Hi

As I can see your system is running 2.0 version and using 2.2 files.
Please double check the update folder, see it there is a file called updateDb.v2.2.sql
If not download and update the system again.

![image](https://cloud.githubusercontent.com/assets/18009293/25700257/41c295aa-309d-11e7-8b50-4d1c180f285e.png)

you suppose to have updateDb.v2.1.sql and updateDb.v2.2.sql files and update one at time.
**Do not skip updates** first 2.1 then 2.2

After this if the problem still, could you giveme your YouPHPTube URL, an user and password?
I can ckeck what is going on for you. 

Best Regards

**Comment by codec212** [comment]
yay it's fixed with latest version 2.4. Thanks and regards.
