### ISSUE TITLE
Change the board shows me error when upar videos

### ISSUE THREAD

**Issue by diegonsf** [DanielnetoDotCom/YouPHPTube#50]
I'm having the following problem, I'm installing the script to do some testing here at home, when I execute the cd / var / www / html && sudo git clone command https://github.com/DanielnetoDotCom/YouPHPTube.git, it creates a Folder, more when I want to enter the localhost I have to put YouPHPTube, I can upar the normal files, more when I change the files to stay in localhost, I normal access more when I try to access the link of videos upar me presents an error, "Not Found The requested URL was not found on this server.
Apache / 2.4.18 (Ubuntu) Server at 192.168.25.5 Port 80 "I do not know what to do to fix this, would anyone have an idea how to fix?

**Comment by DanielnetoDotCom** [comment]
Make sure to move the .htaccess file, it is a hidden file that must also be moved to the folder.
Your command should look something like this:
`mv -R /var/www/YouPHPTube/. /var/www/`

Another thing, why do not you exchange your apache root folder or why do not you create a virtual host?
If you make one of these options, you do not need to move your files

**Comment by diegonsf** [comment]
Thank you solved my problem, now you can tell me how I can select the video configuration I want to watch? Type puts in 320p, 480p, 720p and 1080p and 4k the same video? Same as youtube have? To select the type of resolution?

**Comment by DanielnetoDotCom** [comment]
For now YouPHPTube do not support different resolutions
