### ISSUE TITLE
Twitch issue

### ISSUE THREAD

**Issue by rohitnehra** [DanielnetoDotCom/YouPHPTube#505]
Embedded videos from Twitch are not working (playing)

**Comment by DanielnetoDotCom** [comment]
can you please provide the link you are trying to embed?

**Comment by rohitnehra** [comment]
http://www.twitch.tv/rohitnehra/v/240948198

**Comment by DanielnetoDotCom** [comment]
Update your files it is fixed now :)

**Comment by rohitnehra** [comment]
After updating the file.
My already uploaded videos are not showing in my videos.

Whenever I upload new video I get this error

Fatal error: Call to undefined method Object YPT::getCache() in /objects/functions.php on line 543

**Comment by DanielnetoDotCom** [comment]
hi

are you sure you have all your files up to date?

**Comment by rohitnehra** [comment]
I only updated functions.php file

Which files I need to update kindly tell me

**Comment by DanielnetoDotCom** [comment]
you have to keep all your files up to date, I cant tell you what files are you missing

**Comment by rohitnehra** [comment]
OK
