### ISSUE TITLE
Bulk upload / link

### ISSUE THREAD

**Issue by birdie60** [DanielnetoDotCom/YouPHPTube#509]
Hello Daniel,
I'm wondering if there is a script or API for bulk uploading or bulk linking?
My situation is this: I have uploaded by FTP many .mp4 files into a directory on the same server where YouPHPTube is installed. Now, I'd like to tell YouPHPTube to scan this directory and add all the movies to my channel.
Is there a way to do upload or link many files in a batch? I do not want to re-upload many Gigabytes of movie files again.

**Comment by DanielnetoDotCom** [comment]
Yes there is

check this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Import-a-Full-playlist-from-Youtube

You can skip the part to download youtube playlist

**Comment by mikweb2017** [comment]
is there a command to add a cron job so that you can check automatically if there are new videos?

**Comment by DanielnetoDotCom** [comment]
@mikweb2017 sorry, there is no such feature now :(

**Comment by loso20p** [comment]
is there a way to add bulk url links?

**Comment by DanielnetoDotCom** [comment]
hi, what you mean URL links?

BTW, if you can download to the server any video, you can use Bulk Encode option

**Comment by loso20p** [comment]
i mean add multiple url links at once to the encode queue that needs to be downloaded

**Comment by DanielnetoDotCom** [comment]
Understood, Sorry we do not have this option yet
