### ISSUE TITLE
Player configuration and ads manager missing?

### ISSUE THREAD

**Issue by inebunit** [DanielnetoDotCom/YouPHPTube#51]
Hi, in the version i downloaded, 3.2, i can't find the ads manager (ad or remove ads, etc) neither player configuration.
Is this just a trial version?

**Comment by inebunit** [comment]
i found out about the ads configuration. but i think you should introduce an annotation over the advertising video so if they click to pause it, it goes to the website. It's very rare that people will click on the link :)

**Comment by inebunit** [comment]
ps, can't it display random ads from same category? i see it only displays the first created.

**Comment by DanielnetoDotCom** [comment]
I will write down your observations, and probably fix it
Thanks
