### ISSUE TITLE
[Question] Create an Theme

### ISSUE THREAD

**Issue by mj1985** [DanielnetoDotCom/YouPHPTube#510]
I really like you script :) and I already checked github, the wiki and avaliable plugins, but I still don't have an idea on how to create my own theme (adjusting colors, padding , margins etc).
Is it possible?

**Comment by DanielnetoDotCom** [comment]
Yes it is, you can create your theme as a plugin (like gallery plugin) or you can use a custom css.

Put your custom css on **configuration->script code->head** section:
![image](https://user-images.githubusercontent.com/18009293/37863279-9255b99c-2f3a-11e8-8cd2-7f1dab0dc317.png)

**Comment by mj1985** [comment]
Thanks, I copied the gallery plugin, changed the paths, name and last but not least this line 

`class Gallery extends PluginAbstract`

and got it working now 👍
