### ISSUE TITLE
Even with correct code, YouPHPTube can't show adverts from Revive Adserver instead of google adsense.

### ISSUE THREAD

**Issue by Tomoli75** [DanielnetoDotCom/YouPHPTube#513]
I've been denied google adsense, so have put in my own adserver. This is the header code:
`<script type='text/javascript' src='https://ads.spoosaroo.ml/www/delivery/spcjs.php?id=1&amp;target=_top'></script>`
and this is the actual "adsense code"
`<script type='text/javascript'></script>`
Any help possible?

**Comment by Tomoli75** [comment]
Also you can view the actual advert at [Hyperlink, please click](http://ads.spoosaroo.ml/www/admin/banner-htmlpreview.php?bannerid=1)

**Comment by Tomoli75** [comment]
I've found a workaround, though now the adverts show at the top of the page, not by the side of the video, like it showed in the tutorial vid?

**Comment by DanielnetoDotCom** [comment]
Sorry, where are you placing the javascript code?

are you placing on` configuration->script code-> Google Ad Sense` ?

**Comment by Tomoli75** [comment]
Yes.

**Comment by DanielnetoDotCom** [comment]
can you do the same on demo site, to see if it works?

**Comment by hersche** [comment]
@Tomoli75 still unresolved?

**Comment by The-Do-It-Yourself-World** [comment]
I have the exact same problem. Google banned me so I have been trying ads from various other sites. To date not one ad has worked for me outside of the original google ads.

I put it into config - script code - google adsense and it does not show up. Been trying to work for a year now with one company and we cant get their ads to work.

**Comment by Tomoli75** [comment]
Unresolved

**Comment by DanielnetoDotCom** [comment]
@Tomoli75 you need google approval before display ads.

I can not control Google rules, but I know if Google detects copycats he will not display ads.

check we can display ads on demo site, so for sure you can display on your site as well if google approve you

**Comment by Tomoli75** [comment]
I can close this myself, stale bot.
