### ISSUE TITLE
youtube Notification

### ISSUE THREAD

**Issue by harismaqsood** [DanielnetoDotCom/YouPHPTube#515]
There is no any notification option. like youtube and facebook. for replying notification. comment, subscribe, etc

**Comment by DanielnetoDotCom** [comment]
Not yet, but it may be implemented in the future

**Comment by mikweb2017** [comment]
now it is possible with the help of rss feed and IFTTT to post automatically on faceboock and twitter every time there is a new video

**Comment by hersche** [comment]
thats done then, if a criteria is not done or so, feel free to reopen. thanks @mikweb2017 !

**Comment by DanielnetoDotCom** [comment]
Hi @mikweb2017 can you please give us more details how you did it?

**Comment by hersche** [comment]
@DanielnetoDotCom https://demo.youphptube.com/feed/ :)

**Comment by DanielnetoDotCom** [comment]
I mean use " IFTTT to post automatically on faceboock and twitter "
I create an account on https://ifttt.com (I think is there) and I am kind lost

**Comment by mikweb2017** [comment]
I just came back from the holidays.
I see that you've solved

**Comment by mikweb2017** [comment]
![bildschirmfoto 2018-06-16 um 09 32 33](https://user-images.githubusercontent.com/30271757/41496779-3bb66d7a-7148-11e8-8a70-01f88551012e.png)

**Comment by mikweb2017** [comment]
![bildschirmfoto 2018-06-16 um 09 34 44](https://user-images.githubusercontent.com/30271757/41496794-8894c3da-7148-11e8-8c23-28bee441c2a8.png)
