### ISSUE TITLE
my gif is not displaying on viewing page

### ISSUE THREAD

**Issue by loso20p** [DanielnetoDotCom/YouPHPTube#517]
my gif is not displaying on the viewing page after i updated to the latest updates u had but on the home page its there

![bourto111](https://user-images.githubusercontent.com/29187523/37907589-932b950e-30d3-11e8-99a2-6b068ff54bc7.png)

**Comment by DanielnetoDotCom** [comment]
Please clear your browser cache, also delete the cache dir inside your videos dir. `videos/cache`

**Comment by loso20p** [comment]
thx looks like it worked
