### ISSUE TITLE
Mysql Request

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#518]
with which variable function it obtains the data on and on saved on configuration.php to effect a request to the mysql server.

**Comment by DanielnetoDotCom** [comment]
Sorry I dont understand wht you need

**Comment by DanielnetoDotCom** [comment]
@mikweb2017 really sorry, but what you mean with call up data?

**Comment by mikweb2017** [comment]
<?php
$db = mysqli_connect("localhost", "username", "Passwort", "Dbname");
?>

**Comment by mikweb2017** [comment]
$db = mysqli_connect("localhost", "Benutzername", "Passwort", "Datenbankname");

**Comment by DanielnetoDotCom** [comment]
usually we put that code on a file that we include in every php file that needs mysql connection

**Comment by hersche** [comment]
unshure, which file i've included for my personal, additional script, but you may search this?

$global['mysqli']

this would be for code of course.

$mysqlHost = 'localhost';
$mysqlPort = '3306';
$mysqlUser = 'root';
$mysqlPass = '';
$mysqlDatabase = 'youtube';

is my (test-enviroment)-configuration.php (only sql-part).

hope, one of both helps you.

**Comment by mikweb2017** [comment]
thanks my my mistake.. syntax error
