### ISSUE TITLE
plugins not uploading 

### ISSUE THREAD

**Issue by joey2354** [DanielnetoDotCom/YouPHPTube#519]
hi there

Plugins zip files are not uploading to the admin panel, they do upload but don't show in the plugin list.

I'v tried drag n drop, and normal browse files way, and i'v cleared my cache but still not there.

thank you. 

edit: was the liveuser and footer mod plugins if this helps.

**Comment by DanielnetoDotCom** [comment]
Hi, 

There is a bug on the upload form (we are working to fix it).

For now what you can do is unpack the zip file and upload it to the plugins directory

Sorry about it

**Comment by joey2354** [comment]
ok thats cool, i'll give that a go.


thank  you.
