### ISSUE TITLE
Install finalization differs from video tutorial

### ISSUE THREAD

**Issue by keith20mm** [DanielnetoDotCom/YouPHPTube#520]
In the tutorial video: https://tutorials.youphptube.com/video/how-to-install-youphptube-in-a-fresh-ubuntu-server

once the php parameters have been set, and the database initialized, video shows "Congratulations" message and instructs to remove the install directory, and return to the main directory.

I do all that, but the index.php in the main directory is still the error index.php instructing to correct the apache directory entry to allow htaccess.

Main directory index.php shows:

**Error. Oops you've encountered an error

It appears that either something went wrong or the mod rewrite configration is not correct.

We need to allow Apache to read .htaccess files located under the /usr/www/users/subguns/V directory. You can do this by editing the Apache configuration file:

Find the section <directory /var/www/html> and change AllowOverride None to AllowOverride All

sudo nano /etc/apache2/apache2.conf

After editing the above file your code should be like this:

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>

In order to use mod_rewrite you can type the following command in the terminal:**

The video shows a different screen upon return to the main directory.  It shows the YouPHPTube main screen.

Why does my install still show the error screen (again, it's index.php), telling to fix the apache directory to allow?  Everything apparently has successfully been set (and tested by the install)...

What is supposed to be in the final index.php in the main directory?

**Comment by DanielnetoDotCom** [comment]
Looks like your mod rewrite is not enabled

**Comment by keith20mm** [comment]
I see the html was hacked by the git save script.. see the SO entry for complete listing, if needed.

**Comment by keith20mm** [comment]
Oh, I see that your install provides .htaccess in the home directory.   My php variable sets for 
php_value upload_max_filesize 100M
php_value post_max_size 100M

over-wrote the entire pre-existing htaccess file, which I did not know was present.

Fixed now.  Thanks.
