### ISSUE TITLE
would like the header script open please

### ISSUE THREAD

**Issue by joey2354** [DanielnetoDotCom/YouPHPTube#523]
hi there.

I need the header script area open so i can get google to verify my site so i can set up google login and the youtube auto-uploader.

is this possible please ? or is there an other way i can do it ?

edit: also the google login doesn't seem to work properly, i'v added the secret key correctly but it just won't produce a new profile on my youphptube site ...so the log in works, but it doesn't if this makes sense

thank you.

**Comment by DanielnetoDotCom** [comment]
Try on head code

![image](https://user-images.githubusercontent.com/18009293/37980321-37fd64a2-31c1-11e8-8852-3a7fad959089.png)

**Comment by joey2354** [comment]
it's not there buddy, the header codes not there. 


![nssn](https://user-images.githubusercontent.com/25159595/37980501-3010e5c6-31e3-11e8-8816-ed769348db4c.png)

**Comment by DanielnetoDotCom** [comment]
what version are you using?
where are you hosting it?

**Comment by joey2354** [comment]
you set it up yesterday for me .. so i don't know sorry.

**Comment by DanielnetoDotCom** [comment]
Please remember me your URL

**Comment by joey2354** [comment]
https://potads-vids.ml/

**Comment by DanielnetoDotCom** [comment]
it suppose to be there,
You have 2 options...
1- you can upload files to your server using filezila sftp with your ssh credentials.
2- please email me your site admin credentials I will check what is going on with this field. it suppose to be there

**Comment by joey2354** [comment]
can i have your email address please

**Comment by DanielnetoDotCom** [comment]
developer@youphptube.com

**Comment by joey2354** [comment]
your email didn;t work buddy .. i sent to your other one.

**Comment by DanielnetoDotCom** [comment]
The field is there you just cant see because the theme you choose

![image](https://user-images.githubusercontent.com/18009293/37981669-ad39085e-31c4-11e8-8c30-59c7874b2256.png)

**Comment by joey2354** [comment]
yes thank you !!  fixed :)


have a nice day !

**Comment by DanielnetoDotCom** [comment]
Great

**Comment by joey2354** [comment]
http://probeatz.easytube.club/

hi there ... not good bizness my friend

i won't be getting this now ... i was going to aswel .. the £340

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by DanielnetoDotCom** [comment]
Hi @joey2354 what is the problem?
