### ISSUE TITLE
LI Dots on pages?

### ISSUE THREAD

**Issue by keith20mm** [DanielnetoDotCom/YouPHPTube#525]
What is the purpose of these html LI dots?

Image is: http://subguns.com/SP/YouPHPTubeDots.jpg

**Comment by DanielnetoDotCom** [comment]
It not suppose to be there 
All your css files are loaded?

**Comment by keith20mm** [comment]
I wouldn't have a clue.  I just installed the provided distro.

How or where would I look to see if css is all loaded?

**Comment by DanielnetoDotCom** [comment]
What is your site URL?

**Comment by keith20mm** [comment]
Better yet, check your email from website.

**Comment by keith20mm** [comment]
subguns.com/V
or
subguns.com/YouPHPTube

**Comment by keith20mm** [comment]
You can right click - view source to see the .css calls.  I would guess 
they did get loaded.
