### ISSUE TITLE
li dots on screen after installation

### ISSUE THREAD

**Issue by waste-d** [DanielnetoDotCom/YouPHPTube#530]
oii,

the layout is not working on a fresh install.
i tried 3 different servers and all have same issue.
they show li dots and the login button is not working.

php -v output: PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )
mysql -V output: Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper

![youphptube_error](https://user-images.githubusercontent.com/35196740/38050351-f38c1286-32ca-11e8-9f87-9400aa457026.jpg)

**Comment by keith20mm** [comment]
Exactly my result.  Don't know why.

**Comment by waste-d** [comment]
i was able to fix it.
at least the layout is correct now and the sign in button is working

here's what i did
> 
/etc/php/7.0/apache2/php.ini => allow_url_fopen = On
remove the files into [youphptube]/videos/cache
reload or restart apache2 service
( clear browser cache and/or ) reload page with control + F5

**Comment by keith20mm** [comment]
In my setting, I use .htaccess in the YouPHPTube directory:

php_flag allow_url_fopen on
:
:
This did not correct the problem.

**Comment by DanielnetoDotCom** [comment]
For me looks like the bootstrap css is not there or it is corrupted

**Comment by hersche** [comment]
that should be working since a while. if it still not do, please reopen it.
