### ISSUE TITLE
This is not an issue but a question

### ISSUE THREAD

**Issue by FathiBenNasr** [DanielnetoDotCom/YouPHPTube#533]
Hello, I want to setup YouPHPTube in a closed lan with no access to internet. What would be the recommended hardware for the encoder ?
TIA

**Comment by DanielnetoDotCom** [comment]
Hi, 

At least 2 GB ram and 2 CPU cores.
also is recommended you configure it in a internet connection then move it to your lan, because you will need to use some apt-get commands
