### ISSUE TITLE
Request option in Live menu ...

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#534]
Hi! Can I edit and change for each user separately ... only as admin, the encircled menu that provides .m3u8 files?
I explain ... if maybe possible to edit as admin, for each user, this line ... I have for example a live server much more powerful than the Nginx-rtmp ... which is called Flussonic. If maybe I can put my .m3u8 file of flussonic server, instead of the local Live one ... I could also be able to install multiple live streaming servers to even balance the transmissions ...
How can you edit this line apart from the Live plugin menu that changes them to all users ... do not leave-me the possibility to customize for each user separately?

![info for edit](https://user-images.githubusercontent.com/15127860/38100014-62a38b84-337c-11e8-8514-f7fc504ffd46.jpg)

PS: If I think about it a bit, I think the solution is this ...
 I think that just insert another cell in the database that contains the default data inserted in Live Plugin for each user  ... then with a special menu that appears only to the admin ... can edit this line and in this way customize it for each user that live streaming...

To avoid creating two separate questions ... how do auto play in an embed?

`<iframe width="640" height="360" style="max-width: 100%;max-height: 100%;" `
`src="https://www.abc.eu/vEmbed/316`**?autoplay=1**`" frameborder="0"` 
`allowfullscreen="allowfullscreen" class="YouPHPTubeIframe"></iframe>` 

doing it in this way does not work ...

**Comment by tgd1973** [comment]
After such a long time I was waiting for an answer ... but nothing ...
______________________________________

Now another question about embed:
When the option "unlisted" will be available ... and I'll explain: a video that does not appear in any list, apart from the video management of the author but at the same time if one has the permalink or the address. .. or wants to add an embed in one of his blog ... that can do it.
Now this option is not possible because if you create a private group and the video goes in that group ... if you are not logged on the site, you can not see the video ... even the embed ...

**Comment by DanielnetoDotCom** [comment]
Hi

To be unlisted unselect the option "Listed Transmition "

And also uncheck all groups , the who ever has the link will be able to see the transmition

![image](https://user-images.githubusercontent.com/18009293/38203322-43b2c2b6-3675-11e8-8f6e-907448d5c0d6.png)

**Comment by tgd1973** [comment]
I was referring to a video results from the conversion / recording from a Live ... that must remain stored on the server but that should not be seen in the public list ... but at the same time if I want ... I have to be able to do embed of this video (on the blog of the church) ... 
Now if I create a group that I call "unlisted", and if asign this video to the group ... anyone who wants to see this vodeo, it must belong to the group and be logged ... but if I want to do an embed with this video I can not proceed ... because it gives me videos not found ... 
How can I do?

**Comment by DanielnetoDotCom** [comment]
Check this

![image](https://user-images.githubusercontent.com/18009293/38262500-bcee9154-3743-11e8-83d0-3b03ed82deec.png)

after encode your video will be inactive, and then you can decide what to do before activate it

**Comment by tgd1973** [comment]
I was referring to the fact that it must be active in order to be able to do embed but at the same time it should not be seen in the list ...

![elenco](https://user-images.githubusercontent.com/15127860/38274634-a22fc990-378f-11e8-8973-4a99703d484e.png)

**Comment by DanielnetoDotCom** [comment]
Understood, an active video but unlisted.
For now we dont have that option

**Comment by tgd1973** [comment]
Thanks for the reply ...
The simplest modification you can make is to create an option in the groups that are created to be able to also do public embed with the group that keeps the videos unlisted ....
