### ISSUE TITLE
Encode disallows .MPG file?

### ISSUE THREAD

**Issue by keith20mm** [DanielnetoDotCom/YouPHPTube#536]
Many cameras save video as .mpg files.

Why are these mpeg files disallowed by encoder, since they are common?

I had to use VLC to convert.

**Comment by DanielnetoDotCom** [comment]
Hey, 

Sorry for that, to make encoder accept mpg directly you can add mpg extension on your encoder config

change this line

`$global['allowed'] = array('mp4', 'avi', 'mov', 'mkv', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv');`

to this

`$global['allowed'] = array('mp4', 'avi', 'mov', 'mkv', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv', 'mpg', 'mpeg');`
