### ISSUE TITLE
Add contribution guidelines.

### ISSUE THREAD

**Issue by Maikuolan** [DanielnetoDotCom/YouPHPTube#54]
*See: https://github.com/blog/1184-contributing-guidelines*

I would recommend adding some contribution guidelines to the project. This could make it easier for outsiders and potential new contributors to know what is and isn't an acceptable contribution, how to contribute to the project, etc.

**Comment by DanielnetoDotCom** [comment]
Yeah, you right, I am king a noob on that, but this will be great, If you can help me start this I will apprecciate

**Comment by Maikuolan** [comment]
Sure thing. :-)

I'll make a start on this some time today or tomorrow, when I've got a moment.

**Comment by DanielnetoDotCom** [comment]
Very thanks

**Comment by Cosmopal** [comment]
Hey, 

Is this project still open for contribution? Most of the issues seem to be Usage questions so it's difficult to find something to work on :sweat_smile:. The above merge of the PR doesn't seem to have added the Contribution guide, and your README also doesn't seem to have a contribution guide. This seems like a cool project and I'd love to contribute to it. :smiley:

@Maikuolan did you end up making the contribution guide after all?

**Comment by Maikuolan** [comment]
> @Maikuolan did you end up making the contribution guide after all?

@Cosmopal I honestly don't even remember. I can't see any evidence of it in any old pull requests or in any of my offline repositories/forks though, so.. unless I'm just not seeing it, I'm assuming that I must've forgotten to work on this, and then consequently forgotten about the project entirely. September 2017.. Had been working security/night shift for most of the working week for quite a while around that time, so forgetting about things wasn't too usual, unfortunately (one of the consequences of most of us still needing to earn money somehow while not being paid for any volunteer, open-source work that we do, I guess; I promise that I'm friendly and that I don't bite when people remind me about things though 😬).

I could still do this, or.. if you wanted to do it instead, I'd be totally okay with that. But, in regards to..

> Is this project still open for contribution?

..probably best to wait for @DanielnetoDotCom to respond, before either of us try to work any further on this (no point sending PRs to unmaintained projects, after all).

**Comment by Maikuolan** [comment]
If we wanted any specific examples to work with here, here are some of the contribution guidelines that I wrote for some of my own projects:

- https://github.com/CIDRAM/CIDRAM/blob/v2/CONTRIBUTING.md
- https://github.com/Maikuolan/Common/blob/v2/CONTRIBUTING.md

There are many different, unique ways to approach contribution guidelines, and different package maintainers often have many very different, varying opinions about the matter. I'm not that there exists any "standards", or accepted "industry practice" regarding contribution guidelines either (at least, I haven't found any anywhere before), so, which is the right/wrong way to do it, the best/worst way to do it, etc could be readily debated/argued. Ultimately comes down to what the maintainers for any particular project think about it, I think.

If we're not sure about how we want it to look here, maybe we could look at the contribution guidelines that I wrote for my other projects, and using those as a starting point, pretend/imagine that they were already written for this project, and then discuss what would need changing, in order to make them better suit this particular project here? (Basically, using them as a shell/framework for writing something here, which might be a little easier/simpler than writing from scratch).

**Comment by DanielnetoDotCom** [comment]
Hey guys, I really appreciate all help/contributions.

all your help will be very welcome

@Maikuolan do you mind if I copy one of yours CONTRIBUTING.md?

**Comment by Maikuolan** [comment]
> @Maikuolan do you mind if I copy one of yours CONTRIBUTING.md?

You can do that; that's fine. :-)

Just make sure you read through it all first, before copying it, because some things in it might be irrelevant for YouPHPTube, or might need to be slightly modified in order to suit YouPHPTube better (e.g., any specific points I've mentioned there about code style, PSRs, where some of links point to, etc).

**Comment by Cosmopal** [comment]
@DanielnetoDotCom since most of the issues are actually questions about the app, it might help to try and maintain a list of open issues in the app in the contributing.md ? Might be a good place to start for beginners?

**Comment by Maikuolan** [comment]
> since most of the issues are actually questions about the app, it might help to try and maintain a list of open issues in the app in the contributing.md ?

Maybe creating an FAQ, as a generalised way to address some of the more frequently asked questions, would be better? The amount of questions asked at the issues page is getting quite large, and that's something we definitely need to do something about, I think. Also, I've also always been a fan of keeping lists to help keep things more organised. But, I'm thinking that keeping a list of open issues in an actual file inside the repository could eventually start making the commit history look really messy (i.e., needing to update that file whenever an issue is opened/closed means another commit added whenever an issue is opened/closed; numbers could eventually start adding up down the track, making it a little more difficult to isolate specific commits in the event that we need to do so in response to fixing future bugs and such).

**Comment by Cosmopal** [comment]
Hmm agreed @Maikuolan . The FAQ idea seems the right way to go. Also I just realised that instead of a file of open issues, we can tag the github issues into actual bugs/issues or questions

**Comment by DanielnetoDotCom** [comment]
I agree with all you guys, but right now it is too much for me, also english is not my first language:( 

I appreciate any help.

**Comment by Cosmopal** [comment]
@DanielnetoDotCom , 
For now we can just start by making or adding appropriate labels for issues. It's really quick and simple actually. Currently you already have the labels like "Bug", "Enhancement" etc. These are for issues which are related to code changes or changes in the repo. For example, this issue would be labelled "Enhancement". And some other issue, which reports a bug in your app, will be marked "Bug". Similarly, issues which are only questions about how to use your app and your services can be marked "Questions". 

It is really simple actually, you seem to be pretty active in responding to issues (That is awesome by the way :+1:  :smile:  ). So next time you respond to an issue, just give it a good label as well. Only you can do that I think.
