### ISSUE TITLE
Plugin didn't create folder

### ISSUE THREAD

**Issue by keith20mm** [DanielnetoDotCom/YouPHPTube#540]
I uploaded the "Customize" plugin.  Instead of it making a Customize folder, each filename is shown in the YouPHPTube/Plugin directory

http://23.88.234.139/PS/CustomizeNotx.jpg

**Comment by hersche** [comment]
i have the same names (as wrote in e-mail)

**Comment by DanielnetoDotCom** [comment]
Sorry I am aware about it I will fix it soon , but for now you can extract the file locally and then upload the file using ftp or SFTP (ssh credentials) to the plugins directory

Sorry again for this trouble

**Comment by hersche** [comment]
rename of the files helped me - remove the "folderpart" in the filename and put it in a folder named the removed name..

or:

Customize\Customize.php

to a folder named Customize, file Customize.php

then it will work (in my plugins). forgot to write it before, sorry.

**Comment by keith20mm** [comment]
Simple enough.

Thanks, Guys!
