### ISSUE TITLE
The Captcha not working under nginx proxy

### ISSUE THREAD

**Issue by foxinstone** [DanielnetoDotCom/YouPHPTube#541]
Hi
I have successfully installed YouPHPTube onubuntu16.04 by nginx proxy. It looks very well run!
But on the 'contact' page, The Captcha not working.
Why? How to fix it?

![image](https://user-images.githubusercontent.com/35874666/38147899-d1761b8e-3486-11e8-8a05-2009694f1bae.png)

**Comment by DanielnetoDotCom** [comment]
I am not sure, but maybe you miss the GD or imagemagick php libs.

check your log file
