### ISSUE TITLE
Error while sending QUERY packet cpanel

### ISSUE THREAD

**Issue by DanielnetoDotCom** [DanielnetoDotCom/YouPHPTube#543]
I saw some users with this error before, I could fix it in a CPanel with this...

Turn off the cpanel control

![image](https://user-images.githubusercontent.com/18009293/38157648-3fa3cf70-345f-11e8-9961-b7671119f6d5.png)

**Comment by hersche** [comment]
i moved this here, it's linked in the admin-manual (troubleshooting)

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Error-while-sending-QUERY-packet-cpanel

hope thats fine like this.
