### ISSUE TITLE
hi there everyone

### ISSUE THREAD

**Issue by joey2354** [DanielnetoDotCom/YouPHPTube#545]
would like to test the Subdomain a bit more with members etc ... but it's not there now.

so how can i test this for at least 6 months before i upgrade to the £340 vps .. it's a new bizness that earns no money just yet so upgrading before 6 months is out of the questions sorry to say because i'm sick and have no money. 

thanks.

**Comment by DanielnetoDotCom** [comment]
Let me know if there is something I can do to help you run your video business

**Comment by joey2354** [comment]
maybe thanks

**Comment by hersche** [comment]
seems this ticket is not needed anymore, reopen when i am wrong.
