### ISSUE TITLE
can't seem to upload a plugin

### ISSUE THREAD

**Issue by joey2354** [DanielnetoDotCom/YouPHPTube#548]
hi there ... i can't seem to upload plugins, i'm trying the custom footer plugin but it doesn't seem to show up after it's uploaded.

i'v tried different themes but it's stiil the same.

https://i.imgur.com/4hf4wEY.png cant find the add image button sorry, it's the drag n drop file box showing the plugins 'done' but it doesn't show after in the list.

thank you.

**Comment by DanielnetoDotCom** [comment]
Sorry about that that is a know issue , please unzip the plugin locally on your computer and upload the directory to your plugins directory on your streamer site

**Comment by joey2354** [comment]
i tried that buddy, it didn't work sorry.

**Comment by hersche** [comment]
if the files are named after PluginName\fileName.php rename it to fileName.php and move it to a folder with the plugin-name. this worked for me.

**Comment by joey2354** [comment]
are u talking about adding through my ftp ?

**Comment by DanielnetoDotCom** [comment]
Yes FTP works :)

**Comment by joey2354** [comment]
where is my ftp please ?

**Comment by DanielnetoDotCom** [comment]
try SFTP with filezilla (https://filezilla-project.org/) or winscp (https://winscp.net/eng/download.php) with the same ssh credentials

**Comment by joey2354** [comment]
ok i use filezilla

what is the port number please ?

**Comment by DanielnetoDotCom** [comment]
Should be 22 but leave it blank then will use the default port.

Remember it is not FTP is SFTP

**Comment by joey2354** [comment]
thank you i'm in now.

which folder do i put the plugin in please ?

**Comment by hersche** [comment]
plugin .

the path should look like plugin/CustomizeAdvanced/CustomizeAdvanced.php , for example.

**Comment by joey2354** [comment]
i can't seem to find the plugin folder

**Comment by DanielnetoDotCom** [comment]
should be /var/www/html/YouPHPTube/plugin

**Comment by joey2354** [comment]
it says it doesn't exsit them files.

Directory /root/ /var/www/html/YouPHPTube/plugin: no such file or directory
Error: Failed to retrieve directory listing

**Comment by DanielnetoDotCom** [comment]
@joey2354 what command did you make?
what is your URL?

**Comment by joey2354** [comment]
i don't know what command means sorry.


i searched   /var/www/html/YouPHPTube/plugin  and it said it doesn't exist.


https://potads-vids.ml/



i'm not a coder sorry, i just worked a few stuff out being poorly at home
not able to work, so i try understand and learn as much as i can.




thank you.

**Comment by DanielnetoDotCom** [comment]
What is the plugin you want to upload?
I think I can put there for you

**Comment by joey2354** [comment]
'customise' ​ and  'LiveUses'

the only 2 i payed for atm.


thank you :)

**Comment by DanielnetoDotCom** [comment]
Check your plugins now :)

**Comment by joey2354** [comment]
thank you buddy !

**Comment by DanielnetoDotCom** [comment]
:)
