### ISSUE TITLE
Sorry! Unknown error when clicking Submit button on install/index.php

### ISSUE THREAD

**Issue by FathiBenNasr** [DanielnetoDotCom/YouPHPTube#549]
Hello,

Trying to install YouPHPTube but I am staling at the first screen. All requirements are on green but when hitting the submit button, i get "Sorry! Unknown error". Checked that sql user can connect remotely. I am CentOS centric and have little experience with ubuntu. Could someone helpme to debug/solve my problem please ?

TIA

**Comment by DanielnetoDotCom** [comment]
What the apache log says?

**Comment by FathiBenNasr** [comment]
Nothing other than the usual messages here after:
error.log
[Mon Apr 02 16:22:16.355971 2018] [mpm_prefork:notice] [pid 283] AH00169: caught SIGTERM, shutting down
[Mon Apr 02 16:22:17.204865 2018] [mpm_prefork:notice] [pid 547] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Mon Apr 02 16:22:17.204942 2018] [core:notice] [pid 547] AH00094: Command line: '/usr/sbin/apache2'

access.log
x.x.x.x - - [02/Apr/2018:13:48:30 +0000] "GET /YouPHPTube/install/index.php HTTP/1.1" 200 2269 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"
x.x.x.x - - [02/Apr/2018:13:48:31 +0000] "GET /YouPHPTube/view/bootstrap/css/bootstrap.min.css HTTP/1.1" 200 20089 "http://10.x.xy.xyz/YouPHPTube/install/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"
x.x.x.x - - [02/Apr/2018:13:48:31 +0000] "GET /YouPHPTube/view/js/jquery-3.3.1.min.js HTTP/1.1" 200 30660 "http://10.x.xy.xyz/YouPHPTube/install/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"
x.x.x.x - - [02/Apr/2018:13:48:31 +0000] "GET /YouPHPTube/view/bootstrap/bootstrapSelectPicker/css/bootstrap-select.min.css HTTP/1.1" 200 1924 "http://10.x.xy.xyz/YouPHPTube/install/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"
x.x.x.x - - [02/Apr/2018:13:48:31 +0000] "GET /YouPHPTube/view/js/seetalert/sweetalert.css HTTP/1.1" 200 2749 "http://10.x.xy.xyz/YouPHPTube/install/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"
x.x.x.x - - [02/Apr/2018:13:48:31 +0000] "GET /YouPHPTube/view/js/script.js HTTP/1.1" 200 4544 "http://10.x.xy.xyz/YouPHPTube/install/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"
x.x.x.x - - [02/Apr/2018:13:48:31 +0000] "GET /YouPHPTube/view/js/seetalert/sweetalert.min.js HTTP/1.1" 200 5532 "http://10.x.xy.xyz/YouPHPTube/install/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"
x.x.x.x - - [02/Apr/2018:13:48:31 +0000] "GET /YouPHPTube/view/bootstrap/js/bootstrap.min.js HTTP/1.1" 200 10189 "http://10.x.xy.xyz/YouPHPTube/install/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"
x.x.x.x - - [02/Apr/2018:13:48:31 +0000] "GET /YouPHPTube/view/bootstrap/bootstrapSelectPicker/js/bootstrap-select.min.js HTTP/1.1" 200 10088 "http://10.x.xy.xyz/YouPHPTube/install/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"
x.x.x.x - - [02/Apr/2018:13:48:31 +0000] "GET /YouPHPTube/view/img/logo.png HTTP/1.1" 304 180 "http://10.x.xy.xyz/YouPHPTube/install/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"
::1 - - [02/Apr/2018:13:48:37 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) (internal dummy connection)"
::1 - - [02/Apr/2018:13:48:38 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) (internal dummy connection)"
x.x.x.x - - [02/Apr/2018:13:56:04 +0000] "GET / HTTP/1.1" 200 3525 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"
x.x.x.x - - [02/Apr/2018:13:56:04 +0000] "GET /icons/ubuntu-logo.png HTTP/1.1" 200 3623 "http://10.x.xy.xyz/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0"

**Comment by DanielnetoDotCom** [comment]
there are only 3 lines in your error log?
can you try to install and get the error log

**Comment by FathiBenNasr** [comment]
That's the problem, I have no errors in my logs. How can I go in debug mode ?

**Comment by DanielnetoDotCom** [comment]
try this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Check-Ajax-answer

**Comment by FathiBenNasr** [comment]
Thank you, this helped me diagnose a dns proipagation problem. Now, that is solved, i can see some logs but nothing in the error log and still get the same "Sorry! Unknown error" from both firefox and chrome.
I also forgot to mention that I have created manually the databases and chosen "Create only tables (cdo not create database)".

**Comment by FathiBenNasr** [comment]
Still not getting any error and suspecting some dns problem, i changed my first page config to use ip instaead of fqdn and now I have the following error:
Error deleting user: Cannot delete or update a parent row: a foreign key constraint fails (`youphptubestreamer_db`.`configurations`, CONSTRAINT `fk_configurations_users1` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
So I removed the 18 existing tables, restarted install and now I have a congratulations message.
Still can't understand what led to the first error message as my /etc/hosts on the streamer vm contained all the necessary information.
Thank You Daniel.

**Comment by DanielnetoDotCom** [comment]
Great, I am glad it is working

**Comment by ElusiveMind** [comment]
At the risk of re-opening an old issue. I had this problem when I converted my site to SSL using Let's Encrypt. The URL on the install page did not have https:// but http:// so it was causing mix-content errors and not completing. I am putting this here in the event it helps someone else.

**Comment by DanielnetoDotCom** [comment]
sure, check your Encoder configuration.php file and verify if the http:// is updated to the https://

if still a problem, check the log file

**Comment by ElusiveMind** [comment]
It’s an issue with the logic looking for HTTPS in environment variable. It won’t be set if not on port 80.

We need an option that overrides it.

I also am finding a new bug with a recent update to ffmpeg.  I’ll detail that in a separate email

<?php
$global['force_https'] = TRUE;
$global['configurationVersion'] = 2;
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) { 
    // get the subdirectory, if exists
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS']) || !empty($global['force_https'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'https://tube.xxx.com/';
}
$global['systemRootPath'] = '/var/www/html/streamer/';
$global['salt'] = '5d207cb3a29e0';
$global['enableDDOSprotection'] = 1;
$global['ddosMaxConnections'] = 40;
$global['ddosSecondTimeout'] = 5;
$global['strictDDOSprotection'] = 0;

$mysqlHost = 'db';
$mysqlPort = '3306';
$mysqlUser = 'root';
$mysqlPass = 'SailAway77';
$mysqlDatabase = 'fliptube';

/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';




—
Good Talk,
Michael R. Bagnall
mrbagnall@icloud.com - (615) 476-3269

**Comment by DanielnetoDotCom** [comment]
FYI, your MySQL pass is compromised now, I edit it for you

try to replace this

```
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) {
    // get the subdirectory, if exists
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS']) || !empty($global['force_https'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'https://tube.xxx.com/';
}
```

for this 

`$global['webSiteRootURL'] = 'https://tube.xxx.com/';`

yes, only one line, it will force you to use only one address
