### ISSUE TITLE
Pre Purchase question

### ISSUE THREAD

**Issue by Accordingtojoe** [DanielnetoDotCom/YouPHPTube#550]
I have installed and have been running your system, but unfortunately continue to run into issues. I am now planning on purchasing your  Full Pack. 

One of the issues that I am running into, is importing files over 3BG, It seems not to take it. Will this be the problem with you Full Pack?

The storage disc space fills up very fast with all three video qualities. Do you offer the ability to scale? 
Also the buffering is slow sometimes. Does your system have a fast buffering and this be scaled up if needed? 

How long will it take you to get it up and running?

Can you please let me know of any limitations I am not asking.
Thank you.

**Comment by DanielnetoDotCom** [comment]
Hi I have answer you by email, let me know if you received
