### ISSUE TITLE
Embedding videos from YouPHPTube into Drupal

### ISSUE THREAD

**Issue by FathiBenNasr** [DanielnetoDotCom/YouPHPTube#552]
Hi,
I finnaly got YouPHPTube streamer and encoder installed and working toghether (encoder sends encoded videos to streamer upon completion and video appears on streamer :-)
Now, I would like to embed videos in a drupal site and thats the targeted use of YouPHPTube in my case as local users don't have, due to internal policy, access to youtube so I needed a local youtube in the LAN.
Is there a way to embed videos from YouPHPTube as oEmbed media or should I use a YouPHPTube url as if it was a youtube url ?
TIA.

**Comment by DanielnetoDotCom** [comment]
Try the embed code, that uses iframe

![image](https://user-images.githubusercontent.com/18009293/38262797-ad2acafc-3744-11e8-8a04-5d51200588e2.png)

**Comment by heme007** [comment]
Hello, I have the same problem. I can't share my videos, even with the oembed code that uses the iframe
