### ISSUE TITLE
Error Page installing it online

### ISSUE THREAD

**Issue by hypedboss** [DanielnetoDotCom/YouPHPTube#554]
Here is the message i got after uploading and extracting the YouPHPTube-Streamer file to my server.

# **`Error. Oops you've encountered an error`**

**It appears that either something went wrong or the mod rewrite configration is not correct.

We need to allow Apache to read .htaccess files located under the /home/webbiwoo/public_html directory. You can do this by editing the Apache configuration file:

Find the section <directory /var/www/html> and change AllowOverride None to AllowOverride All

sudo nano /etc/apache2/apache2.conf

After editing the above file your code should be like this:

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>

In order to use mod_rewrite you can type the following command in the terminal:

sudo a2enmod rewrite

Restart apache2 after

sudo /etc/init.d/apache2 restart

or

sudo service apache2 restart**

_Though am using litespeed server not apache cos of it speed

Please any solution to that?_

**Comment by DanielnetoDotCom** [comment]
you need to enable mod_rewrite on that server, please google for that
