### ISSUE TITLE
right menu button on mobile needs a simple fix

### ISSUE THREAD

**Issue by joey2354** [DanielnetoDotCom/YouPHPTube#555]
The right menu button in mobile view https://potads-vids.ml/ isn't long enough when open, or doesn't scroll to the bottom to show the menu options. 

the 'style & themes' menu is affected the most.

thank you.

**Comment by DanielnetoDotCom** [comment]
Thanks for notice, we are working to fix this

**Comment by DanielnetoDotCom** [comment]
Hey, the search bar had an issue on small device (it is fixed now)
I could not find anything regarding 'style & themes'  can you screenshot an example for me?
