### ISSUE TITLE
RTMP Live streaing and Live Chat is not working on SSL/HTTPS

### ISSUE THREAD

**Issue by brajeshrgupta** [DanielnetoDotCom/YouPHPTube#557]
Hi

RTMP Livew streaming and Live chat features are not woriking on SSL/HTTPS.

We have configured Linux on port 8443 and stat link for RTMP is working and showing stats.

But when we start streaming from OBS then connection to server is failed. ( Please check below screen shot,
![obs](https://user-images.githubusercontent.com/36666047/38295615-30895522-380c-11e8-857f-9722bba9eee5.JPG)

Also chat is showing connection failed.
![chat](https://user-images.githubusercontent.com/36666047/38295646-454c631e-380c-11e8-9af3-363facbe5328.JPG)

Both are working fine in NON SSL mode.
NGINX is wrking on Port 8443 and Apache on port 443.

Please help to resolve this issue.

**Comment by brajeshrgupta** [comment]
Below is the plugin config for Live Streaming

![live](https://user-images.githubusercontent.com/36666047/38349194-82d6d6d0-38c3-11e8-891c-6380e89deb4b.JPG)


And for Live Chat

![chat live](https://user-images.githubusercontent.com/36666047/38349208-8c9ad658-38c3-11e8-9651-8f5a29130bb1.JPG)

**Comment by DanielnetoDotCom** [comment]
for the Live Chat you will need to configure the apache proxy to ws://tv.newstracklive.com:8888, try google for that.

About the connection, it is related to your NGINX installation/configuration, what I can tell you is to make sure your on_publish parameter on your nginx.conf is acessibble

**Comment by datasurgeservers** [comment]
I am also having this issue. Using the ProxyPass statement for httpd.conf is not working. I set teh url to wss://my-host:8888  and it gives a timeout for handshaking

**Comment by datasurgeservers** [comment]
Any chance you can help with the above Daniel? If you need more info, I would be happy to provide.

**Comment by DanielnetoDotCom** [comment]
Hi, this is quite different then what I do

For niginx I install the SSL certificate on port 444, so that way will be no conflict on Apache SSL on port 443

For the chat you need to ...

Edit the proxy.conf file

`sudo nano /etc/apache2/mods-available/proxy.conf`

Add this on the file ...

```
<IfModule mod_proxy.c>
        ProxyPass /wss/ ws://127.0.0.1:8888/
</IfModule>
```

Enable the module and restart apache

`sudo a2enmod proxy_wstunnel && sudo /etc/init.d/apache2 restart`



So your web socket will be something like this

`wss://tv.newstracklive.com/wss/`
