### ISSUE TITLE
Recording Live Stream

### ISSUE THREAD

**Issue by gseiki** [DanielnetoDotCom/YouPHPTube#558]
I've followed these instructions to install a plugin and record a live stream.  

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-To-Install-a-new-Plugin
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Record-Live-Stream

What exactly is suppose to happen after I enable the SendRecordedToEncoder plugin?  It doesn't look like anything is happening and nothing new appears on my YouPHPTube page or my encoder page.  I have streamer and nginx on my local server.  Any advice or help would be appreciated.

**Comment by DanielnetoDotCom** [comment]
it suppose to send your recorded stream to the encoder

If you can , after transmit check if the streamer was recorded on your /tmp directory

**Comment by gseiki** [comment]
Thanks for the quick response.  I have the following file, streamKey-04-Apr-18-12:33:40.flv, in /tmp so it looks like it recorded.  But, I don't see it on my encoder page.

**Comment by DanielnetoDotCom** [comment]
yes, looks like is recording, can you please check your streamer log file and encoder log file?
also make sure the plugin is enabled

**Comment by gseiki** [comment]
Plugin is enabled.  What exactly am I looking for in the log files that would let me know that everything is working.

**Comment by DanielnetoDotCom** [comment]
try to live stream then (10 seconds is fine) when you finish check your log

**Comment by DanielnetoDotCom** [comment]
sorry, what do you mean status is encoding?
can you please screen shot?
also please check your log.
your live stream will go to the encoder only when you finish it.

**Comment by gseiki** [comment]
![screen shot 2018-04-04 at 2 32 21 pm](https://user-images.githubusercontent.com/37559861/38341607-2279876e-3815-11e8-953c-9ec131ae3935.png)

**Comment by gseiki** [comment]
I streamed for 10 seconds and stopped.  New file was created in /tmp.  File size is only 3.4MB.  On my videos page of my my YouPHPTube site, I see this.  Status is encoding, and has been that way for 20 minutes now.

**Comment by gseiki** [comment]
![screen shot 2018-04-04 at 2 32 46 pm](https://user-images.githubusercontent.com/37559861/38341672-77fe9fe4-3815-11e8-8746-b5af670a4a02.png)

**Comment by gseiki** [comment]
On my encoder page, Encoding Queue and Queue Log are empty.  This is where I was expecting my stream to be sent.

**Comment by DanielnetoDotCom** [comment]
ok, and your log files, what they say?
Please check https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by gseiki** [comment]
[04-Apr-2018 14:46:19 Pacific/Honolulu] PHP Warning:  rename(/tmp/5ab407eb8a7ad-04-Apr-18-14:43:55.flv,/var/www/html/YouPHPTube/videos/original_PNELiveBroadcaston04Apr18144355_YPTuniqid_5ac571dbd63335.29969119): Operation not permitted in /var/www/html/YouPHPTube/plugin/SendRecordedToEncoder/SendRecordedToEncoder.php(14) : eval()'d code(1) : eval()'d code on line 45
[04-Apr-2018 14:46:19 Pacific/Honolulu] SEND To QUEUE: Array
(
    [user] => admin
    [pass] => 899bb440adbce77be5340ffb4c83d5ab
    [fileURI] => http://10.177.200.96/YouPHPTube/videos/original_PNELiveBroadcaston04Apr18144355_YPTuniqid_5ac571dbd63335.29969119
    [filename] => PNELiveBroadcaston04Apr18144355_YPTuniqid_5ac571dbd63335.29969119
    [videos_id] => 29
    [notifyURL] => http://10.177.201.97/YouPHPTube/
)

[04-Apr-2018 14:47:20 Pacific/Honolulu] QUEUE CURL: stdClass Object
(
    [error] => 
    [response] => 
)

**Comment by DanielnetoDotCom** [comment]
Here we go, `Operation not permitted` 

Try to give permition to the /tmp directory

**Comment by gseiki** [comment]
How?

**Comment by DanielnetoDotCom** [comment]
try this command `sudo chmod 777 /tmp`

**Comment by DanielnetoDotCom** [comment]
Let me know if it works

**Comment by gseiki** [comment]
No, same result.  I did another 10 second stream.  Here is the output.

[04-Apr-2018 15:05:58 Pacific/Honolulu] Class Plugin Not found: /YouPHPTube/pluginsAvailable.json
[04-Apr-2018 15:07:28 Pacific/Honolulu] Array
(
    [scheme] => rtmp
    [host] => 10.177.201.97
    [path] => /live
    [query] => p=899bb440adbce77be4230ffb4c74d4ab
)

[04-Apr-2018 15:07:28 Pacific/Honolulu] Array
(
    [p] => 899bb440adbce77be4230ffb4c74d4ab
)

[04-Apr-2018 15:07:39 Pacific/Honolulu] Record Finish
[04-Apr-2018 15:07:39 Pacific/Honolulu] POST: Array
(
    [app] => live
    [flashver] => FMLE/3.0 (compatible; FMSc/1.0)
    [swfurl] => rtmp://10.177.201.97/live?p=899bb440adbce77be4230ffb4c74d4ab
    [tcurl] => rtmp://10.177.201.97/live?p=899bb440adbce77be4230ffb4c74d4ab
    [pageurl] => 
    [addr] => 10.177.201.115
    [clientid] => 4378
    [call] => record_done
    [recorder] => video
    [name] => 5ab407eb8a7ad
    [path] => /tmp/5ab407eb8a7ad-04-Apr-18-15:07:28.flv
    [videoKeyframeFrequency] => 2
    [totalDatarate] => 2048
)

[04-Apr-2018 15:07:39 Pacific/Honolulu] SEND To QUEUE: Array
(
    [user] => admin
    [pass] => 899bb440adbce77be5340ffb4c85d4ab
    [fileURI] => http://10.177.201.97/YouPHPTube/videos/original_PNELiveBroadcaston04Apr18150728_YPTuniqid_5ac576dbabdc55.34377519
    [filename] => PNELiveBroadcaston04Apr18150728_YPTuniqid_5ac576dbabdc55.34377519
    [videos_id] => 30
    [notifyURL] => http://10.177.201.97/YouPHPTube/
)

[04-Apr-2018 15:08:40 Pacific/Honolulu] QUEUE CURL: stdClass Object
(
    [error] => 
    [response] => 
)

**Comment by DanielnetoDotCom** [comment]
Hi, I am about to go to sleep, but I will keeping helping you tomorrow if the error persist.

I cant see any error on that log. for me looks like it is working.

the only reason I can see now is if you have a wrong **stream name/key**, in your case you are using 5ab407eb8a7ad

check your **stream name/key** here to make sure it is correct
![image](https://user-images.githubusercontent.com/18009293/38342869-3768206c-3857-11e8-9799-8e7a2a26c53d.png)


also can you please check the encoder log?

and post here your nginx.conf

**Comment by DanielnetoDotCom** [comment]
Hi does it work?

**Comment by DanielnetoDotCom** [comment]
What about the encoder log file?

**Comment by gseiki** [comment]
04-Apr-2018 13:37:04 Pacific/Honolulu] runMultiResolution
[04-Apr-2018 13:37:04 Pacific/Honolulu] YouPHPTube-Encoder Start Encoder [ffmpeg -i /var/www/html/YouPHPTube-Encoder/videos/27_tmpFile.mp4 -vf scale=-2:360 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -y /var/www/html/YouPHPTube-Encoder/videos/27_tmpFile_converted_Low.mp4] 
[04-Apr-2018 13:40:18 Pacific/Honolulu] Duration founded: 0:08:02
[04-Apr-2018 13:40:18 Pacific/Honolulu] YouPHPTube-Encoder sending file to http://10.177.201.97/YouPHPTube/youPHPTubeEncoder.json
[04-Apr-2018 13:40:18 Pacific/Honolulu] YouPHPTube-Encoder reading file from /var/www/html/YouPHPTube-Encoder/videos/27_tmpFile_converted_Low.mp4
[04-Apr-2018 13:40:27 Pacific/Honolulu] YouPHPTube-Streamer answer {"error":false,"video_id":"26"}
[04-Apr-2018 13:40:27 Pacific/Honolulu] {"error":false,"format":"mp4","file":"\/var\/www\/html\/YouPHPTube-Encoder\/videos\/27_tmpFile_converted_Low.mp4","resolution":"Low","target":"http:\/\/10.177.201.97\/YouPHPTube\/youPHPTubeEncoder.json","postFields":12,"videoFileSize":"52.08MB","response_raw":"{\"error\":false,\"video_id\":\"26\"}","response":{"error":false,"video_id":"26"}}
[04-Apr-2018 14:10:46 Pacific/Honolulu] http://10.177.201.97/YouPHPTube/ == http://10.177.201.97/YouPHPTube/
[05-Apr-2018 07:51:54 Pacific/Honolulu] http://10.177.201.97/YouPHPTube/ == http://10.177.201.97/YouPHPTube/

**Comment by gseiki** [comment]
rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://10.177.201.97/YouPHPTube/plugin/Live/on_publish.php;
                            on_play http://10.177.201.97/YouPHPTube/plugin/Live/on_play.php;
                            on_record_done http://10.177.201.97/YouPHPTube/plugin/Live/on_record_done.php;
                        recorder video{
                               record all;
                               record_path /tmp;
                               record_notify on;
                               record_suffix -%d-%b-%y-%T.flv;
                            }
                    }
            }
    }

**Comment by DanielnetoDotCom** [comment]
I can't see anything wrong .

I will make some changes on the plugin to give us a better debug idea.

I will start now and will let you know when it is done and you, please, will download the plugin again, and try tonregord again and we will see the results .

I will let you know when it is done

**Comment by gseiki** [comment]
thanks

**Comment by DanielnetoDotCom** [comment]
@gseiki I upload a new plugin version, can you please download again, overwrite the old plugin, make a live stream and show me the log file?

**Comment by gseiki** [comment]
Something seems different about this plugin.  The unzip file is SendRecordedToEncoder\SendRecordedToEncoder.php and unix commands don't work on file.  Suggestions?

**Comment by DanielnetoDotCom** [comment]
I just put another file there, should be fixed now

**Comment by gseiki** [comment]
[05-Apr-2018 11:35:58 Pacific/Honolulu] Array
(
    [scheme] => rtmp
    [host] => 10.177.201.97
    [path] => /live
    [query] => p=899bb440adbce77be5330ffb4c74d3ab
)

[05-Apr-2018 11:35:58 Pacific/Honolulu] Array
(
    [p] => 899bb440adbce77be5330ffb4c74d3ab
)

[05-Apr-2018 11:36:09 Pacific/Honolulu] Record Finish
[05-Apr-2018 11:36:09 Pacific/Honolulu] on_record_done POST: Array
(
    [app] => live
    [flashver] => FMLE/3.0 (compatible; FMSc/1.0)
    [swfurl] => rtmp://10.177.201.97/live?p=899bb440adbce77be5330ffb4c74d3ab
    [tcurl] => rtmp://10.177.201.97/live?p=899bb440adbce77be5330ffb4c74d3ab
    [pageurl] => 
    [addr] => 10.177.201.115
    [clientid] => 4
    [call] => record_done
    [recorder] => video
    [name] => 5ab406eb4a3ad
    [path] => /tmp/5ab406eb4a3ad-05-Apr-18-11:35:58.flv
    [videoKeyframeFrequency] => 2
    [totalDatarate] => 2048
)

[05-Apr-2018 11:36:09 Pacific/Honolulu] SEND To QUEUE: Array
(
    [user] => admin
    [pass] => 899bb440adbce77be5330ffb4c74d3ab
    [fileURI] => http://10.177.201.97/YouPHPTube/videos/original_PNELiveBroadcaston05Apr18113558_YPTuniqid_5ac696c9555978.06240999
    [filename] => PNELiveBroadcaston05Apr18113558_YPTuniqid_5ac696c9555978.06240999
    [videos_id] => 31
    [notifyURL] => http://10.177.201.97/YouPHPTube/
)

[05-Apr-2018 11:37:10 Pacific/Honolulu] QUEUE CURL: stdClass Object
(
    [error] => 
    [response] => 
)

[05-Apr-2018 11:37:10 Pacific/Honolulu] on_record_done END

**Comment by gseiki** [comment]
The log above is from YouPHPTube/videos/youphptube.log.  The log below if from YouPHPTube-Encoder/videos/youphptube.log

[05-Apr-2018 11:36:49 Pacific/Honolulu] http://10.177.201.97/YouPHPTube/ == http://10.177.201.97/YouPHPTube/

**Comment by gseiki** [comment]
these are the only new entries since I did my 10 second test stream this morning.

**Comment by DanielnetoDotCom** [comment]
one question, do you have your encoder and streamer up to date?

streamer version 5.0 and encoder version 2.3?

**Comment by gseiki** [comment]
encoder and streamer update pages says its up to date but it's not.  Encoder is 2.2 and Streamer is 4.8.  I will work on updating now.

**Comment by DanielnetoDotCom** [comment]
great, let me know when you finish

**Comment by gseiki** [comment]
Streamer and Encoder are now up to date.  Result the same.

**Comment by gseiki** [comment]
Do I have to restart any services after update?

**Comment by DanielnetoDotCom** [comment]
no, just make sure you run the update script on the streamer and encoder

**Comment by gseiki** [comment]
I ran cd /var/www/html/YouPHPTube/ && sudo git pull and cd /var/www/html/YouPHPTube-Encoder/ && sudo git pull.  I also had to update via gui on streamer and Encoder.  I'm wondering why stream always shows up on streamer video page with status "encoding" and never finishes?  Shouldn't it go to YouPHPTube-Encoder?

**Comment by DanielnetoDotCom** [comment]
you can remove the video that say "encoding", don't forget to go to the update menu

![image](https://user-images.githubusercontent.com/18009293/38394474-0bde0534-3905-11e8-8b51-e3fb515be656.png)

**Comment by gseiki** [comment]
![screen shot 2018-04-05 at 12 12 28 pm](https://user-images.githubusercontent.com/37559861/38394549-a7f99428-38ca-11e8-8d74-f8b612fd4c53.png)

**Comment by gseiki** [comment]
![screen shot 2018-04-05 at 12 12 16 pm](https://user-images.githubusercontent.com/37559861/38394557-b15bfd6c-38ca-11e8-8530-51ff80d5572d.png)

**Comment by DanielnetoDotCom** [comment]
Great, try the record, plugin now.
I will need to step out but I will keep following you closely;

**Comment by gseiki** [comment]
Nothing happens anymore.  Streams are not being recorded and stored in /tmp anymore.

**Comment by gseiki** [comment]
disregard my last comment.  I restarted my streamer and needed to restart nginx

**Comment by DanielnetoDotCom** [comment]
to record and store on /tmp it does not depends on YouPHPTube, its is only nginx configuration.

When NIGNX finishs the transmition it notfy YPT on  `on_record_done`

YPT move the /tmp file to the encoder and run the encode script

so if it is not saving on /tmp it may be regarding to nginx configuration

**Comment by gseiki** [comment]
Sorry, it is saving in tmp folder again.  I had restarted Streamer and forgot to restart nginx.  Steamer working again, same problem and symptoms as before. Updating streamer and encoder hasn't fixed the problem.

**Comment by DanielnetoDotCom** [comment]
can you do this, please, delete the log files, stream a 10 seconds, dont do anything else and send the full log file, please

**Comment by gseiki** [comment]
Encoder log was not created

**Comment by gseiki** [comment]
I need to change permissions of /tmp folder again since i restarted server.  I think that's the reason for "operation not permitted when trying to rename .flv file.  I will change permissions on tmp folder, delete the log and resend you output.

**Comment by gseiki** [comment]
[05-Apr-2018 13:37:17 Pacific/Honolulu] Array
(
    [scheme] => rtmp
    [host] => 10.177.201.97
    [path] => /live
    [query] => p=899bb440adbce77be5330ffb4c74d3ab
)

[05-Apr-2018 13:37:17 Pacific/Honolulu] Array
(
    [p] => 899bb440adbce77be5330ffb4c74d3ab
)

[05-Apr-2018 13:37:28 Pacific/Honolulu] https://encoder.youphptube.com/getImage/aHR0cDovLzEwLjE3Ny4yMDAuOTY6ODA4MC9saXZlLzVhYjQwN2ViNWE0YWQvaW5kZXgubTN1OA==/jpg Image Expired 0
[05-Apr-2018 13:37:35 Pacific/Honolulu] https://encoder.youphptube.com/getImage/aHR0cDovLzEwLjE3Ny4yMDAuOTY6ODA4MC9saXZlLzVhYjQwN2ViNWE0YWQvaW5kZXgubTN1OA==/gif Image Expired 0

**Comment by gseiki** [comment]
I deleted the old log file, changed permissions on /tmp, and did another 10 second stream.  Here is the log output.  Encoder doesn't have a log file.

**Comment by gseiki** [comment]
Sorry, I had problem with stream.  The log files above not correct.  I resolved stream issue.  Here is the new log file.  Still not recording. 


[05-Apr-2018 13:52:18 Pacific/Honolulu] Array
(
    [scheme] => rtmp
    [host] => 10.177.201.97
    [path] => /live
    [query] => p=899bb440adbce77be5330ffb4c74d3ab
)

[05-Apr-2018 13:52:18 Pacific/Honolulu] Array
(
    [p] => 899bb440adbce77be5330ffb4c74d3ab
)

[05-Apr-2018 13:52:31 Pacific/Honolulu] Record Finish
[05-Apr-2018 13:52:31 Pacific/Honolulu] on_record_done POST: Array
(
    [app] => live
    [flashver] => FMLE/3.0 (compatible; FMSc/1.0)
    [swfurl] => rtmp://10.177.201.97/live?p=899bb440adbce77be5330ffb4c74d3ab
    [tcurl] => rtmp://10.177.201.97/live?p=899bb440adbce77be5330ffb4c74d3ab
    [pageurl] => 
    [addr] => 10.177.201.115
    [clientid] => 64
    [call] => record_done
    [recorder] => video
    [name] => 5ab406eb4a3ad
    [path] => /tmp/5ab406eb4a3ad-05-Apr-18-13:52:18.flv
    [videoKeyframeFrequency] => 2
    [totalDatarate] => 2048
)

[05-Apr-2018 13:52:31 Pacific/Honolulu] SEND To QUEUE: Array
(
    [user] => admin
    [pass] => 899bb440adbce77be5330ffb4c74d3ab
    [fileURI] => http://10.177.201.97/YouPHPTube/videos/original_PNELiveBroadcaston05Apr18135218_YPTuniqid_5ac6b6bf0b7dc3.35173551
    [filename] => PNELiveBroadcaston05Apr18135218_YPTuniqid_5ac6b6bf0b7dc3.35173551
    [videos_id] => 35
    [notifyURL] => http://10.177.201.97/YouPHPTube/
)

[05-Apr-2018 13:53:31 Pacific/Honolulu] QUEUE CURL: stdClass Object
(
    [error] => 
    [response] => 
)

[05-Apr-2018 13:53:31 Pacific/Honolulu] on_record_done END

**Comment by DanielnetoDotCom** [comment]
I really cant see why

this is where it should be to your encoder `QUEUE CURL`

can you please make sure where your **site configuration -> advanced configuration ->Encoder URL** is pointing?
can you please screen shot this screen

![image](https://user-images.githubusercontent.com/18009293/38398459-28c0730c-391a-11e8-95c4-3e362b8ac298.png)

**Comment by gseiki** [comment]
Thanks! In the GUI I had encoder pointing to your online encoder.   Changed address to my local encoder and works now.  Thank you and sorry for the trouble.  I have one last question though.  If you want me to create a new ticket, I can.  But how to encode recorded stream in low quality only.  Right now streams are encoded in low, SD, and HD.

**Comment by gseiki** [comment]
Stream is recording perfectly now.   Thanks for all of your work on this project and your help troubleshooting my setup.

**Comment by DanielnetoDotCom** [comment]
@gseiki Great, I am glad you did it
