### ISSUE TITLE
Tutorial for Distributed / Separated Services

### ISSUE THREAD

**Issue by LHammonds** [DanielnetoDotCom/YouPHPTube#560]
Thanks for creating and sharing YouPHPTube with the world.  I found this service yesterday evening when looking for an alternative to YouTube.  I have MediaGoblin but it is a complicated beast to setup, use and maintain.  Like many other tutorials out there for web apps, the ones I found for YouPHPTube were mainly "get everything on one box" scenarios.

In an environment where you have over 100 virtual servers, admins tend to prefer separating out functionality and sharing resources to keep overhead low...such as not having a dozen separate database servers (silos).  I wanted to set this up with a separate dedicated servers and document how I did this on my forum.  If my company decides to use this instead of MediaGoblin, I'll setup production servers and refine these tutorials but until then, I thought I'd share how I would set these up in a production environment with the rest of the community.

[How to Install and Configure an Ubuntu Server 16.04 LTS](http://hammondslegacy.com/forum/viewtopic.php?f=40&t=220)
[How to Install MariaDB on Ubuntu Server 16.04 LTS](http://hammondslegacy.com/forum/viewtopic.php?f=40&t=225)
[How to install YouPHPTube on Ubuntu Server 16.04 LTS](http://hammondslegacy.com/forum/viewtopic.php?f=40&t=242)
[How to install YouPHPTube Encoder on Ubuntu Server 16.04 LTS](http://hammondslegacy.com/forum/viewtopic.php?f=40&t=243)

Thanks,
LHammonds

**Comment by DanielnetoDotCom** [comment]
@LHammonds very thanks for that

I cant wait to read them all, but the links are not opening

**Comment by LHammonds** [comment]
That's odd.  They work for me.  Here they are in the same order:

http://hammondslegacy.com/forum/viewtopic.php?f=40&t=220 - Ubuntu Server
http://hammondslegacy.com/forum/viewtopic.php?f=40&t=225 - MariaDB
http://hammondslegacy.com/forum/viewtopic.php?f=40&t=242 - YouPHPTube
http://hammondslegacy.com/forum/viewtopic.php?f=40&t=243 - YouPHPTube Encoder

**Comment by DanielnetoDotCom** [comment]
that is sad, for some reason I cant open it from here 

![image](https://user-images.githubusercontent.com/18009293/38495025-78a3cf2a-3bce-11e8-96a1-a8a696615086.png)

**Comment by DanielnetoDotCom** [comment]
Maybe you are blocking Brazil
I have tried form home and from my office

**Comment by LHammonds** [comment]
Well, I did find out that our network guy is blocking all of Brazil due to multiple malware attacks.  You'll have to use one of a dozen methods for bypassing such blocks via proxy to get around it.  Or let me know your IP block and he can add it as an exception.

I do have the Ubuntu and MariaDB tutorials also posted on Ubuntu Forums but the YouPHPTube tutorials are not yet ready for release.

Ubuntu Server - https://ubuntuforums.org/showthread.php?t=2373161
Maria DB - https://ubuntuforums.org/showthread.php?t=2373219

You can probably see my website pages using Google Translate - http://itools.com/tool/google-translate-web-page-translator

Sorry for the inconvenience,
LHammonds
