### ISSUE TITLE
can we not get the andriod aplication source code with all feutures 

### ISSUE THREAD

**Issue by adeseg** [DanielnetoDotCom/YouPHPTube#562]
hi i try out the android source code it is noting to the main app and always giving me couldn't get json from server

**Comment by DanielnetoDotCom** [comment]
I think the Android application you are looking for is a third party app.

The official app is not opensource

**Comment by adeseg** [comment]
cant i get the official app or cant u try and make it open source it will be nice

**Comment by DanielnetoDotCom** [comment]
The official app is here https://www.youphptube.com/mobile/

**Comment by adeseg** [comment]
ok thanks but try as much as possible to make it opensource

**Comment by adeseg** [comment]
just the android version... will be looking forward till when u make it open source thanks

**Comment by DanielnetoDotCom** [comment]
:)

**Comment by hersche** [comment]
i think for the moment it will stay closed source, maybe daniel will change this one day, until then i close the issue..
