### ISSUE TITLE
failed to open stream: No such file or directory in view/modeYoutube.php on line 81

### ISSUE THREAD

**Issue by GaneshKandu** [DanielnetoDotCom/YouPHPTube#564]
Hi,

I am Getting Warning on every page 
Warning: getimagesize({PATH}/youphptube/videos/{my_video}.jpg): failed to open stream: No such file or directory in {PATH}/youphptube/view/modeYoutube.php on line 81
on
http://domain.com/video/{my_video}-mp4 no Thumb image of video getting this
![image404 php](https://user-images.githubusercontent.com/12833130/38420087-3215a54e-3992-11e8-9651-d5af70af9264.gif)

![screenshot-webuzo web-2018-04-06-17-33-07](https://user-images.githubusercontent.com/12833130/38420262-aeaef2a4-3992-11e8-8b81-af14f22ce705.png)

[youphptube.log.txt](https://github.com/DanielnetoDotCom/YouPHPTube/files/1883832/youphptube.log.txt)

**System Details**

server | version
--- | ---
PHP | 7.0.12
Server | Apache/2.2.31 (Unix) 
OS | CentOS 6
Mysql | 5.5.53

**Comment by DanielnetoDotCom** [comment]
Hi, looks like you are using an old version.

we are now on version 5 you are on version 4.1

on the recently version 5.01 we are working to put the audio support back.

about the static image, if you are directing upload a MP4 file you will need the MP4ThumbsAndGif plugin

**Comment by GaneshKandu** [comment]
Hi,
@DanielnetoDotCom  i have updated my YouPHPTube to latest 5.0 version
still facing issue after successful installation on login page

Fatal error: Call to undefined method mysqli_stmt::get_result() in bjects/plugin.php on line 194

seems it requires ```mysqlnd``` in latest version of YouPHPTube 
[http://php.net/manual/en/mysqli-stmt.get-result.php](http://php.net/manual/en/mysqli-stmt.get-result.php)
[http://php.net/manual/en/mysqli-stmt.get-result.php#refsect1-mysqli-stmt.get-result-mysqlnd](http://php.net/manual/en/mysqli-stmt.get-result.php#refsect1-mysqli-stmt.get-result-mysqlnd)

latest YouPHPTube  doesn't fully support ```mysqli```

**Comment by DanielnetoDotCom** [comment]
It requires PHP 5.6+ (or greater) and the mysqlnd driver.

Please try to google to find out how to install it on your server

**Comment by GaneshKandu** [comment]
get_result method is used only at plugin.php on line 194

**Comment by DanielnetoDotCom** [comment]
not, it is used all over the code, the plugin was the first error

**Comment by GaneshKandu** [comment]
Hi,
i moved to other server which is mysqlnd installed but getting same error
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/1898668/youphptube.log)

**Comment by hersche** [comment]
this should be solved by the mysqlnd-fallback.

@GaneshKandu can you retry and confirm this meanwhile? updated version is needed.

**Comment by GaneshKandu** [comment]
@hersche  Thanks Working
Waiting for next Release with this fix

**Comment by hersche** [comment]
@GaneshKandu i would recommend to download a direct zip. the releases are a bit old.
try this: https://github.com/DanielnetoDotCom/YouPHPTube/archive/master.zip

**Comment by GaneshKandu** [comment]
i have installed current master zip and its Working fine

**Comment by hersche** [comment]
perfect! :+1: :)
