### ISSUE TITLE
Table already exists 

### ISSUE THREAD

**Issue by winnipeg21** [DanielnetoDotCom/YouPHPTube#566]
When i set everything up and click install it says 

Sorry!
Error deleting user: Table 'epiz_21827313_New.users' doesn't exist

**Comment by DanielnetoDotCom** [comment]
Please drop the database and try to install again

**Comment by hersche** [comment]
@winnipeg21 is this solved for you?

**Comment by winnipeg21** [comment]
Uninstalled this software for another, much more stable one. As for the issue, it was not fixed.

**Comment by hersche** [comment]
so you don't retest it?

did you do any check after install the "much more stable one"?

**Comment by hersche** [comment]
close it due to inactivity and sw-change
