### ISSUE TITLE
In V5.0, jQuery Error.

### ISSUE THREAD

**Issue by foxinstone** [DanielnetoDotCom/YouPHPTube#568]
Hi,
Take a look at the screenshots:

![image](https://user-images.githubusercontent.com/35874666/38462263-aa5f6140-3b16-11e8-871c-e8062baf40a6.png)
![image](https://user-images.githubusercontent.com/35874666/38462266-b945719a-3b16-11e8-86df-8e9dad0ede67.png)

By the way, The capcha is OK now, maybe it's because I use second - level domain name, or  as a result of your work ... any way , i've closed the issue. thanks!

**Comment by hersche** [comment]
it seems, css/flagstrap/js/jquery.flagstrap.min.js is nowhere loaded on your site. this should be in footer.php

**Comment by foxinstone** [comment]
Hi,
Yes, it's ok now after i clear the cache.
Maybe you should clear the project file , you know ,i was a fresh installation.
thanks.

**Comment by hersche** [comment]
weird, because the cache-folder did not exist in the beginning. i'm still relative new in the project and never had a look into the cache, but maybe it's a good info for @DanielnetoDotCom
