### ISSUE TITLE
Mod_rewrite dont work on Plesk 17 

### ISSUE THREAD

**Issue by Europekicker** [DanielnetoDotCom/YouPHPTube#57]
Hi i try to install on Plesk 17 ubuntu 14, and mod_rewrite dont work, mod_rewrite its allready on.

> sudo a2enmod rewrite
Module rewrite already enabled

The place of config files for domain in Plesk 17 its diferent to standart apache config.

Vhost have own config file and AllowOverride All its set.

<Directory /var/www/vhosts/domain.de>
		AllowOverride AuthConfig FileInfo Indexes Limit Options=Indexes,SymLinksIfOwnerMatch,MultiViews,FollowSymLinks,ExecCGI,Includes,IncludesNOEXEC
	</Directory>

where is the problem?

**Comment by DanielnetoDotCom** [comment]
is .htaccess file there?
Did you copy it

**Comment by Europekicker** [comment]
yes

here the beginn of 

<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin: *
</IfModule>
<IfModule mod_rewrite.c>
    RewriteEngine on

    #main Files
    RewriteRule    ^$ view/    [NC,L]
    RewriteRule    ^bootstrap/(.+)$ view/bootstrap/$1 [NC,L]
    RewriteRule    ^js/(.+)$ view/js/$1 [NC,L]
    RewriteRule    ^css/(.+)$ view/css/$1 [NC,L]
    RewriteRule    ^img/(.+)$ view/img/$1 [NC,L]
    RewriteRule    ^page/([0-9]+)/?$ view/?page=$1    [NC,L]
    RewriteRule    ^videoOnly/?$ view/?type=video    [NC,L]
    RewriteRule    ^audioOnly/?$ view/?type=audio    [NC,L]
    RewriteRule    ^download$ view/downloadExternalVideo.php    [NC,L]
    RewriteRule    ^downloadNow$ objects/downloadVideo.php    [NC,L]
    RewriteRule    ^getDownloadProgress$ objects/downloadVideoProgress.php    [NC,L]

    RewriteRule    ^about$ view/about.php    [NC,L]
    RewriteRule    ^contact$ view/contact.php    [NC,L]
    RewriteRule    ^sendEmail$ objects/sendEmail.json.php    [NC,L]
    RewriteRule    ^captcha$ objects/getCaptcha.php    [NC,L]
    RewriteRule    ^monitor/(.+)$ objects/ServerMonitor/$1    [NC,L]

    #for the category name

........

**Comment by DanielnetoDotCom** [comment]
I really have not sure. I have no Plex to test it. See if you can google something about it.
If you find please share with me :)

**Comment by Europekicker** [comment]
ok sure thx

**Comment by Europekicker** [comment]
it works just i delete the index.php in the root and use the domain.com/install to install
just ignore the red error of mod_rewrite 
now it works fine

**Comment by DanielnetoDotCom** [comment]
That is great !
