### ISSUE TITLE
Site Not Loading Completely

### ISSUE THREAD

**Issue by hypedboss** [DanielnetoDotCom/YouPHPTube#570]
Hello, On my VPS, after installing the YouPHPTube, site is not loading well link [](https://webbiwood.com) https://webbiwood.com

**Comment by hersche** [comment]
did you clear videos/cache/ ?

there's a flagstrap-exception, yesterday the issue was solved this way in another issue..

**Comment by hypedboss** [comment]
No. And what should i do?

**Comment by hersche** [comment]
delete the files in 

**videos/cache/**

in your youphptube-root-folder

**Comment by hypedboss** [comment]
Thanks

**Comment by hypedboss** [comment]
I will try that and give you feedback

**Comment by RisKatOr** [comment]
Hi, i have same problem www.ahiska.tv , and nginx & rtmp module not vork (after start nginx i have this error (1935 already in use)

**Comment by hersche** [comment]
and do you tried deleting all the files in videos/cache/ already?

**Comment by RisKatOr** [comment]
Yes, but nothing is changing

**Comment by hersche** [comment]
ok, thanks for your try.

this file looks weird and not same like in my installation.. so i still think it's in that context, but i can be wrong..
http://www.ahiska.tv/videos/cache/3eda368acc6cf5188bdf61aa6ee131d3.js

another idea, can or have you already tried to disable the cache-plugin?

**Comment by RisKatOr** [comment]
cache-plugin Disabled because its fresh install

**Comment by hersche** [comment]
tried to reproduce it, was not possible to me.. but i'm using apache, maybe there's the reason.. 

@hypedboss do you use nginx too?

**Comment by RisKatOr** [comment]
I reistall but the result did not change, www.ahiska.tv . I think that this is due to the server settings (Ubuntu 16.04 , Apache2), since on my other site it works www.ahiska.net/tv (Debian 9 , Apache2)

**Comment by hersche** [comment]
yeah, looks a bit like this when it does it's job there..

can this help? https://github.com/DanielnetoDotCom/YouPHPTube/issues/530 there they solved a similiar problem by 

/etc/php/7.0/apache2/php.ini => allow_url_fopen = On
remove the files into [youphptube]/videos/cache
reload or restart apache2 service

didn't had that in mind, sorry..

**Comment by RisKatOr** [comment]
allow_url_fopen already On
cache removed and apache restarted but same problem.

**Comment by hersche** [comment]
ok, i'm running out of ideas.. maybe a comparsion between debian 9 and ubuntu 16.04's config-files can help?

**Comment by RisKatOr** [comment]
I reinstall Ubuntu server, problem same, maybe problem in script (YouPHPTube) ?

**Comment by hersche** [comment]
reinstall with debian 9 or simply ubuntu again? maybe the defaults of ubuntu are not right..
but as i said, i don't really have other ideas..

**Comment by RisKatOr** [comment]
Reinstall Ubuntu 16.06 ... i try install Debian 9

**Comment by hersche** [comment]
ok, when you set it up the same way, that should work. 

the output of

videos/youphptube.log 

can maybe also help to see whats going on - when for example php-dependencies are not installed or it's something from the script itself, it may shown there.. (also a bit late, sry again)

**Comment by RisKatOr** [comment]
I install Debian Stretch and same problem :(

**Comment by RisKatOr** [comment]
I'm tired, I remove the server.

**Comment by hersche** [comment]
mh, when there's not even a log-entry and you set everything up the same way, i don't know what to do further..

**Comment by RisKatOr** [comment]
After fresh install (without Webmin/Virtualmin) its work. But not comfortable without hosting control panel

**Comment by hersche** [comment]
mh, ok, but that's a good point..
this can change settings too.. i try to install webmin to reproduce it..

**Comment by hersche** [comment]
yeah, can confirm, webmin works fine.. i never used virtualmin, i wanted to try it quick, but it's not fine with ubuntu 17.10..

i can imagine that they restrict 

allow_url_fopen already On

because it's known that it can be insecure, when wrong used in code.. maybe you have to allow a security-option about php anywhere?

**Comment by hypedboss** [comment]
Mine is still having problem
webbiwood.com

**Comment by hypedboss** [comment]
I have tried the above solutions cos am not having Webmin/Virtualmin

**Comment by hypedboss** [comment]
Am seeing this error 
**# Fatal error: Uncaught Error: Class 'mysqli' not found in /home/webbiwoo/public_html/objects/include_config.php:6 Stack trace: #0 /home/webbiwoo/public_html/videos/configuration.php(18): require_once() #1 /home/webbiwoo/public_html/view/index.php(10): require_once('/home/webbiwoo/...') #2 {main} thrown in /home/webbiwoo/public_html/objects/include_config.php on line 6**

**Comment by hypedboss** [comment]
i have sorted it out, it's working fine now. Thanks a lot...
