### ISSUE TITLE
help out with the andriod app so i can play my website video

### ISSUE THREAD

**Issue by adeseg** [DanielnetoDotCom/YouPHPTube#572]
always telling me couldn't get json from server help with it pls

**Comment by DanielnetoDotCom** [comment]
Sorry, can you give me more details? I don't understand

**Comment by adeseg** [comment]
i downloaded the android app source code and i made the app it work but it is unable to get my videos also cant play any video wen i click the video to play i get this error message couldn't get json from server

**Comment by adeseg** [comment]
do u get it now pls

**Comment by DanielnetoDotCom** [comment]
Hi, the only mobile app we support is that one https://www.youphptube.com/mobile/ (NOT open source)

there are other mobile app, that somebody else develop it.

**Comment by adeseg** [comment]
and it is

**Comment by adeseg** [comment]
all plugin are enable

**Comment by DanielnetoDotCom** [comment]
if you connect on demo site, how is it working?

**Comment by BigmIkeX** [comment]
same problem

**Comment by BigmIkeX** [comment]
I installed the app and it won't let me login over https 
http works, but my site is configured for https

**Comment by DanielnetoDotCom** [comment]
I just tested it on demo site and it works fine:
![image](https://user-images.githubusercontent.com/18009293/40491295-0acb759a-5f44-11e8-949d-597f2ef86ebd.png)

**Comment by DanielnetoDotCom** [comment]
please make sure you have the latest files on your site. and your site is updated.

**Comment by BigmIkeX** [comment]
Already tried the new bits from Git and Website
![image](https://user-images.githubusercontent.com/32983492/40545843-ed395d8a-5ff2-11e8-88a3-e242315d126c.png)

**Comment by BigmIkeX** [comment]
Not sure the logic here but I disconnected from my Wi-Fi network and connected to it. Reconnected to my Wi-Fi and a continued working.

**Comment by DanielnetoDotCom** [comment]
So it is working now?

**Comment by BigmIkeX** [comment]
Yeah, weirdest thing must be something on my home network.

**Comment by DanielnetoDotCom** [comment]
I am glad it is working

**Comment by andreicaba** [comment]
Hello,

  For some reason, for us doesn't work. We enabled the mobile management plugin, but... - still, it doesn't work. Your demo.youphptube.com site works in the mobile app, but ours doesn't. It simply doesn't do anything!... It doesn't show any error, anything!... It simply doesn't work. Our site is https://brtl.raultrezirii.ro - and we simply have no idea why it doesn't work... Do you have any?... :)
  Thanks in advance for your quick and amiable reply!

best regards,
Eng. Andrei Caba

**Comment by DanielnetoDotCom** [comment]
Your SSL is not good

![image](https://user-images.githubusercontent.com/18009293/57173193-49e14200-6e02-11e9-8a98-13f6792834c1.png)

**Comment by adeseg** [comment]
I can get you a good ssl for your site hit me up on WhatsApp +2348116308124 or email  adeseg99@gmail.com let me help you get it resolved

**Comment by andreicaba** [comment]
And that is why?... OK, thanks :)
Let's Encrypt is accepted?...

**Comment by andreicaba** [comment]
I only see colored dots dancing instead of each audio's thumbnail/text... how so?... And how could that be solved?... It is veey hard for the user to choose a sermon if he can not see any details about the item right in the list, you know.... :) I also did find some kind of a workaround, but... it's not that intuitive :) If the user searches for a space in the search option - the results will have text associated and the image associated too... :)
Any hints about this, Daniel?... :)

**Comment by DanielnetoDotCom** [comment]
About the mobile app, make sure you update your streamer , we made a lot of changes on the mobile and streamer this weekend 

If the problem persist , can you please screenshot the problem are you having ?

**Comment by andreicaba** [comment]
I installed it via Turnkey's solution for Xen virtual machine. For some reason, it doesn't find any update higher than 6.2. I can see in the git hub that the current version is 7.1. I have some little customization (especially on the front page, but not only...) (added some links to download some stuff, etc...). How would you recommend me to do the update?... Git clone?... overwrite the update file and then run it?... What would you recommend?...
Also... - here is the behavior
![directly-doesnt_display-items-properly](https://user-images.githubusercontent.com/45318272/57240195-8d23f680-7036-11e9-9d22-e096332e9f1d.jpg)
 I told you about:
  - immediately after I click "Check site" (and then clicking on the user "Anonymous", for the free and easiest access) - some colored dots (blue, red, yellow, green) keep dancing. I've attached how it looks like. However, if I click on the "search" button, and I search for a blank space, for example, I can see all the audios & videos (mostly they are audios), with their right thumbnail (the image that I've chosen) and with the associated text shown...
![with-search_works](https://user-images.githubusercontent.com/45318272/57240233-9f059980-7036-11e9-92c7-4e5c305a34a4.jpg)

**Comment by DanielnetoDotCom** [comment]
I don't know what did you customize, so I recommend you update all files.

for my self, I use git clone and then git pull to get updates

**Comment by andreicaba** [comment]
I just tried... it did a mess... now I can't even login from the website - but the login works from the mobile app. What should/could I do?!...

**Comment by DanielnetoDotCom** [comment]
Looks like you miss a / on your videos/configuration.php file

change this: `$global['webSiteRootURL'] = 'https://brtl.raultrezirii.ro';`

for this: `$global['webSiteRootURL'] = 'https://brtl.raultrezirii.ro/';`

**Comment by andreicaba** [comment]
I just checked - it's like this already
$global['webSiteRootURL'] = 'https://brtl.raultrezirii.ro/';
So... it must be anther issue?... Btw, update 6.8 or 6.9 had some errors... (the sql script...)

**Comment by DanielnetoDotCom** [comment]
It may be the cache directory, try to delete the videos/cache directory

**Comment by andreicaba** [comment]
nope, I just did. It just gets re-created with all the wrong URLs again...

**Comment by DanielnetoDotCom** [comment]
I really can not see another reason if the configuration is with $global['webSiteRootURL'] = 'https://brtl.raultrezirii.ro/';

**Comment by andreicaba** [comment]
also, the 7.0 update is the one failing.
here is the error:
root@brtl .../youphptube/updatedb# mysql -u tubeuser -p yphptube < updateDb.v7.0                                   .sql
Enter password:
ERROR 1071 (42000) at line 6: Specified key was too long; max key length is 767                                    bytes
root@brtl .../youphptube/updatedb#

**Comment by andreicaba** [comment]
also, here are the first 15 lines of the configuration.php:

root@brtl .../youphptube/videos# head -n15 configuration.php
<?php
$global['configurationVersion'] = 2;
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) {
    // get the subdirectory, if exists
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'https://brtl.raultrezirii.ro/';
}
$global['systemRootPath'] = '/var/www/youphptube/';
$global['salt'] = 'fgq2rd43mujuz';
$global['enableDDOSprotection'] = 1;
$global['ddosMaxConnections'] = 40;
root@brtl .../youphptube/videos# pwd
/var/www/youphptube/videos
root@brtl .../youphptube/videos#

**Comment by andreicaba** [comment]
could it be some .htaccess rewrite?!... or?... Also... why is the 7.0 failing?!....

**Comment by andreicaba** [comment]
I changed the charset of my database and 7.0 is not failing any more... But the site is still like that... What could/should I do?!...

**Comment by DanielnetoDotCom** [comment]
Hi 2 things, 

1. Specified key was too long; max key length is 767 bytes
I saw this happen before because MySQL was an old version, so you need to update it.
also check this: https://github.com/YouPHPTube/YouPHPTube/issues/649
https://github.com/YouPHPTube/YouPHPTube/issues/284
https://github.com/YouPHPTube/YouPHPTube/issues/85
https://github.com/YouPHPTube/YouPHPTube/issues/171

2. remove the dynamic URL from your configuration.php

```
<?php

$global['configurationVersion'] = 2;
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
$global['webSiteRootURL'] = 'https://brtl.raultrezirii.ro/';
$global['systemRootPath'] = '/var/www/youphptube/';

...
```

**Comment by andreicaba** [comment]
The mysql was already at the last version, but, still, until I changed the charset to the infamous "utf8" from "utf8mb4" (only the yphptube).
removing the dynamic URL worked :) ... Today, when I woke up, exactly something like that was in my mind - to do to the site, fixing exactly just that :)
Although... for some reason now... - the videos are simply not loading... the files are still there, it seems... but the videos are shown the correct names, categories & thumbnail, but... when clicked on them... - they are not loading... what could cause it?... how to debug that?...

**Comment by andreicaba** [comment]
Actually... they are working from the admin interface, there it works. Only when I am entering simply "brtl.raultrezirii.ro" - then the "Play" button... - only then nothing happens... What could cause that?...

**Comment by andreicaba** [comment]
OK... I did
root@brtl .../www/youphptube# cd updatedb/
root@brtl .../youphptube/updatedb# grep -r "lastVideoTime" .
./updateDb.v6.3.sql:ADD COLUMN `lastVideoTime` INT(11) NULL DEFAULT NULL AFTER `                                                                                                             modified`;
and I've seen that in the 6.3 update that it adds "lastVideoTime" - and then I've rerun the sql update
now, when I manually click on the embeded video link: it worked...
Only from home it doesn't work...

**Comment by andreicaba** [comment]
I've changed the theme into youtube theme and now I kinda "skipped" the problem: the link is directly where it should... :) Although... the netflix theme still doesn't work, as I said before...
