### ISSUE TITLE
Audio  Error Js script

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#573]
if  play  audio  MP3  
Error 

![bildschirmfoto 2018-04-09 um 16 34 24](https://user-images.githubusercontent.com/30271757/38504098-1f843754-3c14-11e8-8649-dece9cfc1329.png)
and  this with Firefox 

![bildschirmfoto 2018-04-09 um 16 38 46](https://user-images.githubusercontent.com/30271757/38504282-915844d8-3c14-11e8-99a3-7e3ce9c81859.png)

**Comment by hersche** [comment]
i tried to reproduce this by update to the last commit, but for me it still works (quick-tested in firefox and chromium).

what plugins do you have activated?

**Comment by mikweb2017** [comment]
![bildschirmfoto 2018-04-09 um 17 03 32](https://user-images.githubusercontent.com/30271757/38505657-008872a8-3c18-11e8-9d14-0a4edd8f4188.png)
![bildschirmfoto 2018-04-09 um 17 03 17](https://user-images.githubusercontent.com/30271757/38505659-027b5364-3c18-11e8-8623-3b992dd6393b.png)
![bildschirmfoto 2018-04-09 um 17 03 07](https://user-images.githubusercontent.com/30271757/38505661-04e793e2-3c18-11e8-9e8d-33407342c003.png)

**Comment by hersche** [comment]
i still cannot reproduce it, but i think i found it in your installation..

it's in theater-button-plugin, which is a bit stupid for audio, but i should be able to solve it quick, only a sec

**Comment by hersche** [comment]
can you try these changes?
if you need more info, just tell me.. :)
https://github.com/hersche/YouPHPTube/commit/156321812b5a4ce9b7525c2066993f7f876a93a6

**Comment by mikweb2017** [comment]
yes  it's theater-button-plugin .

disable thant  und works fine

**Comment by hersche** [comment]
ok.. when you can try the commit, you can even let plugin activated.. 
ps: nice music :)

**Comment by hersche** [comment]
thanks!

https://github.com/hersche/YouPHPTube/commit/bfba4bbe7744fc2384c826ce3705ff8e4085c1ce

i think this should solve it. is this way ok for "pre-apply" the changes?

**Comment by mikweb2017** [comment]
i try later  your change

**Comment by hersche** [comment]
got id (i think).
the usual installation has the Id "mainVideo" in the <video>-tag.

https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/view/include/video.php#L34

yours look like this..

`<video style="width: 870px; height: 489px; left: 0px; top: 0px;" tabindex="-1" class="video-stream html5-main-video" controlslist="nodownload" src="blob:https://www.youtube.com/2ce090b4-0d82-4320-9aa7-0eb7a34f0511"></video>`

but you also stream videos directly from youtube.com, as it looks? is this a plugin?

and what's ytp-videowall, also a plugin? (for the videos when it ended, as it looks). not seen or used this yet..

or do you put somehow embeded youtube-videos in there? if so, i would correct the emeded code like

`<video style="width: 870px; height: 489px; left: 0px; top: 0px;" tabindex="-1" class="video-stream html5-main-video" id="mainVideo" controlslist="nodownload" src="blob:https://www.youtube.com/2ce090b4-0d82-4320-9aa7-0eb7a34f0511"></video>`

this is important for the plugins. Important, for audio it is  id="mainAudio"

**Comment by mikweb2017** [comment]
sorry now I'm a bit confused

**Comment by hersche** [comment]
ok, sorry, i was a bit much in "developing-language"..

how do you upload your videos?

do you link them somehow with youtube?

this confuses me a bit.. when i can reproduce to get this kind of video, i should be able to fix..

**Comment by DanielnetoDotCom** [comment]
@hersche what you mean special kind of videos?

**Comment by hersche** [comment]
the video-tag is like

`<video style="width: 870px; height: 489px; left: 0px; top: 0px;" tabindex="-1" class="video-stream html5-main-video" controlslist="nodownload" src="blob:https://www.youtube.com/2ce090b4-0d82-4320-9aa7-0eb7a34f0511"></video>`

so

1. https://www.youtube.com/2ce090b4-0d82-4320-9aa7-0eb7a34f0511 - from youtube directly?
2. where is the id="mainVideo" ? is that the tag from view/include/video.php? not that i know - confusing..
3. on the end of the video, i become suggestions from youtube (i know it because it's personal stuff)

could that mean it's just a embedded youtube-video? is there a way to do so and i just not see it?

my test-link: https://you-tube.eu/cat/default/video/applescript-tutorial-2

**Comment by DanielnetoDotCom** [comment]
To be honest, I dont know there this video tag come from
