### ISSUE TITLE
Full screen for embeded video links

### ISSUE THREAD

**Issue by rohitnehra** [DanielnetoDotCom/YouPHPTube#577]
Unable to switch to full screen on embedded video links.

**Comment by DanielnetoDotCom** [comment]
what embed code are you using

**Comment by ChrisSlS** [comment]
Identical problem on my side.

![embed-link](https://user-images.githubusercontent.com/37787071/38591604-cc103bf2-3d37-11e8-81d1-d88c2a5a1223.png)

@DanielnetoDotCom rohitnehra is talking about that too, I think.

**Comment by rohitnehra** [comment]
http://srsanime.com/video/attack-on-titan-s01e07-a-small-blade

check this link

**Comment by DanielnetoDotCom** [comment]
Thanks

I confirm this issue, and I am sending a fix, please update your files and let me know

**Comment by ChrisSlS** [comment]
It works ! Thanks.

**Comment by rohitnehra** [comment]
:)
