### ISSUE TITLE
facebook login

### ISSUE THREAD

**Issue by abamilod** [DanielnetoDotCom/YouPHPTube#579]
After April 4, FB login doesn’t work in ypt. How to solve this?

**Comment by mikweb2017** [comment]
![bildschirmfoto 2018-04-12 um 06 46 25](https://user-images.githubusercontent.com/30271757/38656835-4be106be-3e1d-11e8-8acf-c692d318e344.png)

**Comment by abamilod** [comment]
Is it inside the php request code or we can do solution in fb settings?

**Comment by mikweb2017** [comment]
i no I know we wait for daniel on site demo works weight is something in Faceboock

**Comment by DanielnetoDotCom** [comment]
I didn't know that. I will check

**Comment by DanielnetoDotCom** [comment]
I am sending a fix, please update your files and try again

**Comment by abamilod** [comment]
nicely done. Thank you again.
