### ISSUE TITLE
List of supported file types for upload

### ISSUE THREAD

**Issue by Gregger83** [DanielnetoDotCom/YouPHPTube#58]
Actually the upload form allows the following file types to be uploaded.

`$allowed = array('mp4', 'avi', 'mov', 'mkv', 'flv', 'mp3', 'wav', 'm4v', 'webm');`

I added 'wmv' locally and everything worked fine, too.

Why not adding everything ffmpeg / avconvert supports itself?

**Comment by DanielnetoDotCom** [comment]
Yes, those are the file types I have remmember when I wrote :) 
But it may support more file types :)
Would you like to send-me your fork?? 
os should I add it manualy too, thanks for that

**Comment by Gregger83** [comment]
My "fork" is:

`$allowed = array('mp4', 'avi', 'mov', 'mkv', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv');`

**Comment by tgd1973** [comment]
By uploading mp3 you can play in player as it would be extracted, audio from a video file?
I tried to upload only the mp3 but does not let me do anything. After uploading the file name turns red and does not continue on ...

**Comment by DanielnetoDotCom** [comment]
I think Audio support need some fixes

**Comment by tgd1973** [comment]
And when will it be ready? I have audio sermons to put online.
I've also tried on the Demo server and it does not work the same ...

**Comment by DanielnetoDotCom** [comment]
As soon as I have some time I will check this audio support

**Comment by hltibbs** [comment]
It's not allowing me to upload MOV files. Where do I make this edit?
