### ISSUE TITLE
Plugin request

### ISSUE THREAD

**Issue by d0773d** [DanielnetoDotCom/YouPHPTube#581]
Any works in the future to stream line the upload to the encoder server when the uploaded video doesn't meet the supported video format? 

Creating a plugin to do this from within the youphptube to check the format of the video script could be beneficial to members who aren't experienced enough and help stream line the uploading process to automatically send the video to the encoder server from within youphptube instead of logging into the the encoder server to upload the unsupported video.

**Comment by DanielnetoDotCom** [comment]
Hi

Do you mean upload the video to youphptube than if the format is not supported send it to encoder?

**Comment by hypedboss** [comment]
Please, Can you create a 
#1 Messaging plugin
Description: I mean users can message each other if they are subscribed

**Comment by d0773d** [comment]
Hi Daniel. Yes, that is what I mean.

**Comment by DanielnetoDotCom** [comment]
@hypedboss understood, we may develop this on the future

@d0773d I think the best option is disable direct upload MP4 file. leave encoder only. encoder support may formats and extract image and gif

**Comment by d0773d** [comment]
@DanielnetoDotCom I disabled the authenticated users can upload videos.  Now the normal camera icon at the top right corner disappeared. It now appears that 'normal users' can not upload videos via streamer and encoder. Only admin can upload.

How do I correctly 'disable direct upload'? Will I be required to dig into the source code to remove "Direct Upload" from the dropdown menu?

**Comment by RisKatOr** [comment]
Plugins -> CustomizeAdvanced -> doNotShowUploadMP4Button

**Comment by d0773d** [comment]
@RisKatOr got it! Thanks
