### ISSUE TITLE
Feature request: Pause / unpause video with the spacebar.

### ISSUE THREAD

**Issue by glumpje** [DanielnetoDotCom/YouPHPTube#59]
One of the hotkeys that youtube has is the spacebar to pause / unpause video. Some of my colleagues asked for this feature.

Thanks,
Chris

**Comment by DanielnetoDotCom** [comment]
Great, I like this feature, I will take a look

**Comment by DanielnetoDotCom** [comment]
Hi, I was looking if the focus is on the player spacebar to pause / unpause already works.
I have tested it on chrome, what browser did you tested?

**Comment by glumpje** [comment]
I tested on chromium on Ubuntu and a browser on Windows, i think it was
Firefox. Did IT allready work for you on Chrome?

Op 8 jul. 2017 2:54 a.m. schreef "YouPHPTube" <notifications@github.com>:

**Comment by glumpje** [comment]
I tried on different browsers, and the problem seems to be focus, if there is no focus on the video the spacebar will be used to scroll down. If you start the video clicking in the middle of the video you dont seem to get focus, if you use the play button on the lower left corner you do get focus.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
