### ISSUE TITLE
Issue with php.ini max file size setting

### ISSUE THREAD

**Issue by d0773d** [DanielnetoDotCom/YouPHPTube#591]
I increased my max file upload size in my php ini file to 1000MB, but youphptube will only allow 100.00MB. The same goes for the encoder.

I attached 3 images to give more detail.

![01 - streamer __ configuration](https://user-images.githubusercontent.com/1925962/38754824-2991e38e-3f18-11e8-8af3-624c976a2b2a.png)

![02 - streamer_upload](https://user-images.githubusercontent.com/1925962/38754829-2cc4fa8c-3f18-11e8-8b68-052908354c18.png)

![03 - encoder_upload](https://user-images.githubusercontent.com/1925962/38754831-2e771c5c-3f18-11e8-9ae8-a02ed5f96afe.png)

**Comment by DanielnetoDotCom** [comment]
You need to increase post_max_size

![image](https://user-images.githubusercontent.com/18009293/38755288-93628bb0-3f3b-11e8-8c52-ddc28ec9bedb.png)

**Comment by d0773d** [comment]
HI Daniel.  Thanks for the reply.  Increasing post_max_size did the trick.  I completely forgot about the correct php.ini file settings from when I successfully installed/setup youphptube a few months ago.

**Comment by DanielnetoDotCom** [comment]
I am glad you fixed

**Comment by willpower68** [comment]
I'm have an issue with encoded video.  It's about 3 minutes long but get the EE:EE:EE for time and of course it does not play.  The file is about 422.2 MB.  I'm assuming there is an issue with file size limit or post mx size.  However, I don't know how to increase file size requirement to determine if that is the problem.  Any direction you can give me would be helpful.

**Comment by DanielnetoDotCom** [comment]
you can change the file size in your php.ini, you can google for that.

make sure you are aware of the CDN problem 

https://github.com/YouPHPTube/YouPHPTube/wiki/About-Video-Upload#cloudflare
