### ISSUE TITLE
conect user and encoder same time

### ISSUE THREAD

**Issue by halhnini** [DanielnetoDotCom/YouPHPTube#592]
Hi,
thank you for your appreciate efforts, i have a question is what if i want to connect user and encoder same time meanning if the user is connected he can use encoder also without login twice.

**Comment by ChrisSlS** [comment]
It's already the case. The user connected to the site is automatically connected in the encoder, besides looking at the url, you will see that it is the case.

![canal](https://user-images.githubusercontent.com/37787071/38775786-fc0d730a-408a-11e8-8e3d-c725c77c5f9b.png)

**Comment by DanielnetoDotCom** [comment]
@ChrisSlS is correct, if you click on the menu on the top right you will be directed to the encoder and will be automatic logged in

![image](https://user-images.githubusercontent.com/18009293/38805230-7ebe32ce-414b-11e8-8ece-b0a2c89f9185.png)
