### ISSUE TITLE
Direct upload missing

### ISSUE THREAD

**Issue by dfreddie** [DanielnetoDotCom/YouPHPTube#593]
Youphptube ver. 5.0.1 no more direct upload button. Tryed with 2 users with right permissions.

**Comment by gamersalpha** [comment]
hello :  

![image](https://user-images.githubusercontent.com/32466950/38780193-21803aa8-40d3-11e8-9f4f-32c9ca1b5013.png)

i have it

withthe last version : 

![image](https://user-images.githubusercontent.com/32466950/38780196-2c98a024-40d3-11e8-8fd2-66f14ae52739.png)

**Comment by RisKatOr** [comment]
Plugins -> CustomizeAdvanced -> doNotShowUploadMP4Button (uncheck)

![mp4](https://user-images.githubusercontent.com/4102352/38782959-52cff3c4-4104-11e8-8296-0f75a4cd1a34.jpg)

**Comment by dfreddie** [comment]
@RisKatOr thank you!!!

**Comment by harsh85** [comment]
thank you, sir,
https://tyrosx.com
