### ISSUE TITLE
Saving shanges issue

### ISSUE THREAD

**Issue by NunoSAlmeida** [DanielnetoDotCom/YouPHPTube#6]
I'm having problems saving the configuration, the initial config went fine but updates when we save, the saving popup apears and stays on screen forever.

I check the code and realize its related with this 2 lines in /objects/configuration.php
. "ffmpegMp4Portrait = '{$global['mysqli']->real_escape_string($this->getFfmpegMp4Portrait())}',"
. "ffmpegWebmPortrait = '{$global['mysqli']->real_escape_string($this->getFfmpegWebmPortrait())}',"

I did not change the values in the config page so i'm testing with the default ones.

Also, one sugestion about upload files, when a file is uploaded the system starts encoding immediately, that is fine when we upload only one file, I have uploaded 5 files at the same time and the server went 100% CPU because its was encoding all files at the same time. It would be nice if the encoding was be made by upload order one at a time, or an option in the configuration to select the number of encondings we want at same time.

Regards

**Comment by DanielnetoDotCom** [comment]
Hi, thanks about your coment.

About the encode line, it is something I want to do. encode just one at the time. but for right now once the upload is complete it starts to encode.

About the saving configuration, you maybe have an undone upgrade to do, go to the "update version" menu:
![image](https://cloud.githubusercontent.com/assets/18009293/25685517/711e5334-303e-11e7-94f0-235dc59be538.png)

if your system is up to date you should see a screen like the image below

![image](https://cloud.githubusercontent.com/assets/18009293/25685541/a261be9a-303e-11e7-8ea8-ffd8203ad73b.png)

if is not up to date, you should see a update button

![image](https://cloud.githubusercontent.com/assets/18009293/25686032/b0da73d8-3041-11e7-901b-79e77de12eb2.png)

**Comment by codec212** [comment]
I have same problem with processing bar stucked forever when saving settings in admin page (advance regular configuration). But this happen when update to latest version (2.2) and not in version 2.0.

**Comment by DanielnetoDotCom** [comment]
I have answered in the other issue, i think you wrote in wrong place.

As I can see your system is running 2.0 version and using 2.2 files.
Please double check the update folder, see it there is a file called updateDb.v2.2.sql
If not download and update the system again.

![image](https://cloud.githubusercontent.com/assets/18009293/25700257/41c295aa-309d-11e7-8b50-4d1c180f285e.png)

you suppose to have updateDb.v2.1.sql and updateDb.v2.2.sql files and update one at time.
**Do not skip updates** first 2.1 then 2.2

After this if the problem still, could you giveme your YouPHPTube URL, an user and password?
I can ckeck what is going on for you. 

Best Regards

**Comment by NunoSAlmeida** [comment]
Hi Daniel, 

No, i'm in 2.2, when I first install the software it was already in that version.
I have never update a version, but I have git pull to update your changes.

But was this a known issue? Perhaps its all OK with the code but the value in does fields are causing the issue perhaps!

**Comment by NunoSAlmeida** [comment]
Ok I found the problem, please correct the initial /instal/database.sql, you are creating the 2 fields that I refer before with 255 insted of 400.

`ffmpegMp4Portrait` VARCHAR(255) NULL,
`ffmpegWebmPortrait` VARCHAR(255) NULL,

In your 2.2 update you create the fields with 400 but in new instalations the script was creating with 255.

Its a simple fix :)

**Comment by DanielnetoDotCom** [comment]
Ok, thanks
You right, I just fix the script. new installations had those problems.
