### ISSUE TITLE
How to Edit views 

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#605]
Hi Daniel I want edit views how to do please teach me.

**Comment by DanielnetoDotCom** [comment]
Hi, what do you mean?
If you want to change the first page modes, try to do it as a plugin. see the plugins sample

**Comment by gujarraju** [comment]
i want change views 
![views](https://user-images.githubusercontent.com/35865505/38932710-1241fad4-4328-11e8-8e21-3b90ae19c07f.jpg)

**Comment by gujarraju** [comment]
how to increase views of any videos.

**Comment by DanielnetoDotCom** [comment]
to edit this you have to do it direct into the videos table on the database

**Comment by DanielnetoDotCom** [comment]
There is no path, you need to know how to edit mysql rows

**Comment by ChrisSlS** [comment]
Look here : 

![capture d ecran_2018-04-23_19-42-00](https://user-images.githubusercontent.com/37787071/39143871-652fe32c-472f-11e8-8827-6a2dc9f01936.png)

**Comment by hersche** [comment]
i think that's answered good enough, so i close it.
