### ISSUE TITLE
request

### ISSUE THREAD

**Issue by osiann** [DanielnetoDotCom/YouPHPTube#61]
its a excelent work

i need watermark image in videos its posible to help ?

**Comment by DanielnetoDotCom** [comment]
Hi

You will need to change the ffmpeg encode code.
Go to the configurations->advanced tab
![image](https://user-images.githubusercontent.com/18009293/27995208-b6c260ce-64a0-11e7-9e5a-495346cfcd79.png)

try too google for the best fit code.
I found this one 
https://stackoverflow.com/questions/10918907/how-to-add-transparent-watermark-in-center-of-a-video-with-ffmpeg

**Comment by RockHardJim** [comment]
Hi awesome script you made how abou multi server capability wih conversion server, streaming and storage server?

**Comment by DanielnetoDotCom** [comment]
Next release will support a conversion dedicated server.
Streaming will be the YouPHPTUbe as you know today and storage could be a mounted server

**Comment by RockHardJim** [comment]
awesome stuff man, can you do custom paid job for me?

**Comment by DanielnetoDotCom** [comment]
Sure, email me developer@Youphptube.com

Em 11 de jul de 2017 7:45 AM, "Tumelo Baloyi" <notifications@github.com>
escreveu:

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
