### ISSUE TITLE
Upload file from 3rd party app

### ISSUE THREAD

**Issue by abamilod** [DanielnetoDotCom/YouPHPTube#611]
Hello,
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Upload-videos-from-third-party-applications

Before I tried to do bash script, I create a simple html to upload file to youphptube. 

![upload](https://user-images.githubusercontent.com/25945730/38925154-5a9fc532-4331-11e8-8801-71cf0ace4cc6.png)
 
It seems it rejected the upload. Is it the sample html is not working or plugin listener.

**Comment by DanielnetoDotCom** [comment]
the password must be an MD5 hash 
try this .. http://www.miraclesalad.com/webtools/md5.php
`
upload.php?user=admin&pass=202cb962ac59075b964b07152d234b70`

**Comment by abamilod** [comment]
I see. Forgot about that security was added. Thank you Daniel.
