### ISSUE TITLE
feed issue

### ISSUE THREAD

**Issue by Andiweb87** [DanielnetoDotCom/YouPHPTube#616]
I have a problem about feed section, i have check in Feed Validator and show this issue

This feed does not validate.

    line 64, column 24: XML parsing error: <unknown>:64:24: not well-formed (invalid token) [help]

               <title>Brighton & Hove Albion 1-1 Tottenham Hotspur</title>
                                ^

In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendations.

    Your feed appears to be encoded as "UTF-8", but your server is reporting "UTF8" [help]

    line 17, column 17: Image title doesn't match channel title [help]

        		<title>RSS Feed</title>
                         ^

    line 32, column 7: item should contain a guid element (4 occurrences) [help]

               </item>

**Comment by Andiweb87** [comment]
when i use the url feed to free feed gadgets is show url: "https://www.domain.com/feed/" - is not a valid feed

**Comment by DanielnetoDotCom** [comment]
Please make sure you have the correct version and files, it is working on demo site: https://demo.youphptube.com/feed/

**Comment by hersche** [comment]
shouldn't chars like & being escaped? like for html, so &amp;

looks so.. https://stackoverflow.com/questions/7381974/which-characters-need-to-be-escaped-on-html?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
