### ISSUE TITLE
Request "unlisted" video option ...

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#619]
Hello and thank you for all this effort to bring this video platform closer to perfection.
Seeing all these changes, please consider also this little option to add for videos ... "not in list" of videos not viewable on the site but at the same time can make embed visionable to all and permalink ...

![unlisted](https://user-images.githubusercontent.com/15127860/39002505-fef3cea4-43f8-11e8-8b69-19b92547c68d.png)

So in this way I can buy the registration module  and then use it in the church ... quietly ...

**Comment by davidjmaxey** [comment]
I would love to see this idea implemented as well. Really love the software so great work!

**Comment by restriato** [comment]
How wonderful! To update a platform that is already in the air is just modify the files?

**Comment by DanielnetoDotCom** [comment]
Hi, I am glad you like it.

update your files and check your update menu

![image](https://user-images.githubusercontent.com/18009293/40748824-12cdc7ea-6438-11e8-9952-0ec44d7ea409.png)

**Comment by restriato** [comment]
![screenshot_26](https://user-images.githubusercontent.com/34867124/40749694-39798232-643b-11e8-9891-a477cc54db07.png)
My system appears to be up to date, but the unlisted. Version 5.4

**Comment by DanielnetoDotCom** [comment]
try here 
![image](https://user-images.githubusercontent.com/18009293/40749925-0728c684-643c-11e8-97e5-d466a35079da.png)

**Comment by restriato** [comment]
When I update the video.php file appears the error 500

**Comment by DanielnetoDotCom** [comment]
check your error log file. also please make sure you didnt skip any update

if you do , check your configuration table on your database, edit the version column and update again

**Comment by restriato** [comment]
Does it have to stay that way?

![screenshot_27](https://user-images.githubusercontent.com/34867124/40750133-a1b92c2a-643c-11e8-81c7-6c2821dab5d5.png)

**Comment by restriato** [comment]
It has to turn gray

![screenshot_28](https://user-images.githubusercontent.com/34867124/40750252-1066ce3e-643d-11e8-8f53-9fdc29605686.png)

**Comment by DanielnetoDotCom** [comment]
first click disable, another click make it unlisted, another click enable again.
Also I found a bug and it is fixed

**Comment by restriato** [comment]
thanks!

**Comment by hersche** [comment]
this one looks done, so i close it.
