### ISSUE TITLE
Option for bulk load without uploading

### ISSUE THREAD

**Issue by hriskov** [DanielnetoDotCom/YouPHPTube#62]
Hi, this platform is magnificent.
I have a hard disk with lots of videos, which I want to add without uploading them, just i want to attach that disk and use it only for the platform. Is that is possible. I'm still trying to understand if that is possible. 
Can you show me where i can find the answer of that question.

Thanks in advance!

**Comment by DanielnetoDotCom** [comment]
I am working in a version with a separated encoder, that will support it

**Comment by DanielnetoDotCom** [comment]
BTW, the book encode is on the new encoder project https://github.com/DanielnetoDotCom/YouPHPTube-Encoder
