### ISSUE TITLE
Problem changing username with connected account through Oauth (Twitter, Facebook, Google, etc.)

### ISSUE THREAD

**Issue by ChrisSlS** [DanielnetoDotCom/YouPHPTube#622]
Hello,

The problem is rather simple to understand: The user connects through Oauth, everything works perfectly.
At a certain point, the user wants to change his username and goes to the parameters of his account :100: 

![name](https://user-images.githubusercontent.com/37787071/39026790-28467a08-444f-11e8-9fa8-c3f11e096b5c.png)
(you will notice that the username is the email)

So, when the user replaces the username (e-mail) with something else, it creates a new user !

![83](https://user-images.githubusercontent.com/37787071/39026921-d4e8feb6-444f-11e8-9fe1-7ca0a8a6a9e1.png)

![84](https://user-images.githubusercontent.com/37787071/39026922-d6944626-444f-11e8-9f84-f6f5adeae6f3.png)

The worst thing about this bug is that the user will not be able to go back to his old channel, it will automatically connect him to the second account created when changing the username on the first channel.

**Comment by ChrisSlS** [comment]
At the same time, the problem of writing the e-mail in the box "username" causes a problem of confidentiality during a live broadcast :

![live](https://user-images.githubusercontent.com/37787071/39027329-b76a615c-4451-11e8-898a-f3ed03273cbb.png)

The url displays the email.

So, I tried to modify this file by replacing "getUserName" by "getName" but it does not work, the functional url is the one containing the e-mail.

![index](https://user-images.githubusercontent.com/37787071/39027456-42f0068c-4452-11e8-84f9-0ad6bdde6ee9.png)

Have I forgotten something?

**Comment by DanielnetoDotCom** [comment]
I understand, thanks.

I probably will need to change something on the oauth authentication, maybe consider the email field instead the username. and Just create a temporary random username. so if a user change his user name the oauth will still work.

I will try to fix this soon.

**Comment by ChrisSlS** [comment]
@DanielnetoDotCom Hey, The problem is different now, here is the error returned if a user uses Oauth and changes his username, then disconnects and reconnects :

![syntaxerror](https://user-images.githubusercontent.com/37787071/39553369-a87bac98-4e6d-11e8-936d-f62f3d4117e7.png)

`INSERT INTO users (user, password, email, name, isAdmin, canStream, canUpload, status,photoURL,recoverPass, created, modified) VALUES ('mail@mail.com','PASSWORD','mail@mail.com','NAME',false, false, false, 'a', 'https://lh4.googleusercontent.com/-XXXXX/XXXXXXXX/XXXXXX/XXXXX/photo.jpg?sz=150', '', now(), now()) Error : (1364) Field 'channelName' doesn't have a default value`

**Comment by DanielnetoDotCom** [comment]
hey, looks like you update your files and didnt update your app 

![image](https://user-images.githubusercontent.com/18009293/39580200-f85847c0-4ebe-11e8-831a-77199b353707.png)

**Comment by ChrisSlS** [comment]
Everything has been updated from my side yet. I notice the problem is also present on the demo site but more serious than in my case because there, impossible to use Oauth :

![demo](https://user-images.githubusercontent.com/37787071/39591907-80665e04-4f05-11e8-9cf4-983b35b31e8d.png)
