### ISSUE TITLE
Site Broken at first place

### ISSUE THREAD

**Issue by amishultimatehacker** [DanielnetoDotCom/YouPHPTube#623]
When earlier I installed youphptube on my localhost it was working fine everytime. But when I installed it on my VPS Server it seems broken Everytime.

The Home page seems not to load correctly and even the website design structure is malformed.

Have a look on how it looks At http://blivu.com

Here's the Screenshot

![1](https://user-images.githubusercontent.com/20637510/39080028-1292efa2-4544-11e8-945d-b7663dd8264d.jpg)

and the Menu area looks like

![2](https://user-images.githubusercontent.com/20637510/39080043-73cbd824-4544-11e8-8582-da066f22a1c6.jpg)

![3](https://user-images.githubusercontent.com/20637510/39080049-90353cf8-4544-11e8-8ed9-2127db0bc58a.jpg)

While all the frontend code matches correctly with the Original code even then its not opening correctly.
I tried all my browsers like IE, Mozilla,Chrome, but the problem persists.

Here is just the difference between CSS Consoles of both the localhost and the webhost.

Website on Localhost :
![localhost](https://user-images.githubusercontent.com/20637510/39081413-82c1a4d4-455e-11e8-86cb-d18b745f28fa.jpg)

Website on VPS Hosting :

![server](https://user-images.githubusercontent.com/20637510/39081420-a02b3d6e-455e-11e8-81e1-7b27dbc5b75b.jpg)

**Comment by RisKatOr** [comment]
Try fresh installing Ubuntu 16.04 (without any hosting control panel) and use the [instructions](https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x-For-YouPHPTube-version-4.x-or-newer) step by step.

**Comment by amishultimatehacker** [comment]
That would do nothing to this issue as atleast the html and css based front page should open without conflicts as they are opening on my localhost. Could you suggest what issue would be stopping website to not to load properly into my browser.

**Comment by RisKatOr** [comment]
the problem may be due to the php and its modules. So be sure that you use mod_php 7.0 and needed modules.

**Comment by amishultimatehacker** [comment]
I already have php 7.0 enabled for the domain.
Can you tel  me which php modules are required in youphptube

**Comment by hersche** [comment]
is the php-option

allow-url-fopen

activated / on / 1?

**Comment by RisKatOr** [comment]
Yes, must be ON

**Comment by amishultimatehacker** [comment]
I just noticed it in the error logs
[21-Apr-2018 13:08:44 UTC] PHP Warning:  file_get_contents(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0 

allow-url-fopen is OFF
Can you tell me how to turn back it on
I have no option to turn it on even not in any of my WHM or cpanel

**Comment by amishultimatehacker** [comment]
file_get_contents(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0
file_get_contents(http://blivu.com/plugin/CustomizeAdvanced/advancedCustom.json.php): failed to open stream: no suitable wrapper could be found

this is the Error log

I Enabled the allow-url-fopen now but still its not working

**Comment by RisKatOr** [comment]
https://github.com/DanielnetoDotCom/YouPHPTube/issues/530

**Comment by amishultimatehacker** [comment]
Yeah ! It definately was issue #530.
I repaired it.
Site not working fine

**Comment by RisKatOr** [comment]
You're welcome.

How you solved the problem, write here step by step, this will help others who will have such problems.

Then you can "Close issue"

**Comment by amishultimatehacker** [comment]
Here is how I finally solved out this problem

1. In WHM, php.ini change allow_url_fopen setting to on or 1
2. Restarted Server
3. Deleted files in /video/cache
4. Reloaded the page without cache i.e. Ctrl+ F5

And the Website worked fine

**Comment by amishultimatehacker** [comment]
Fixes #623

**Comment by RisKatOr** [comment]
What about php modules ? you install mod_php (libapache2-mod-php7.0) and modules (php7.0-mysql php7.0-curl php7.0-gd php7.0-intl) or have they already been?

**Comment by amishultimatehacker** [comment]
Currently Website is working basically only not any extra functionality is added by me, but until I neither installed any of above modules.
