### ISSUE TITLE
Page Title Concern

### ISSUE THREAD

**Issue by amishultimatehacker** [DanielnetoDotCom/YouPHPTube#626]
The site title should be its original name until one of any video is played. Also think from the point of view of SEO

**Comment by DanielnetoDotCom** [comment]
Is not showing the site title?
Is it showing what?

**Comment by amishultimatehacker** [comment]
Issue 1 . 
The Problem is that when I am entering my website http://blivu.com , it is showing the last video on the forefront and the title of that video always remains struct to main site title, until I play the next video.

It should be like that as on your's website. When we open https://demo.youphptube.com then it comes with its default title "Live Stream Site and VR 360º" and as soon as we click on any video then title changes to (lets say. xyzxyzxyz - Live Stream Site and VR 360º)

but I am unable to get my solo website title on front page "blivu".

Issue 2.
Also your website displays all of your videos in a clear manner and lists them all over the screen, whereas my site shows them in a right-side-list view. Any Help !

**Comment by DanielnetoDotCom** [comment]
try to enable gallery plugin and see how it works

**Comment by amishultimatehacker** [comment]
Yeah it worked well now, a very thank to you Daniel
