### ISSUE TITLE
Install failed: unknow error

### ISSUE THREAD

**Issue by benIT** [DanielnetoDotCom/YouPHPTube#63]
Hi, 
I am encountering error during webinstall!
All prerequisites are checked ([see install screenshot](http://hpics.li/c526342)) but when I submit the install form I get 'sorry unknow error'.

Technical stack:
-  Apache/2.4.10
- PHP 5.6.30-0+deb8u1
- mysql  Ver 14.14 Distrib 5.5.55, for debian-linux-gnu (x86_64) using readline 6.3

Maybe this came from the response of ajax call of `checkConfiguration.php` that is empty?

**Comment by DanielnetoDotCom** [comment]
If the script create already a database try to manual delete it and try
install again

Em 11 de jul de 2017 09:22, "Benoît" <notifications@github.com> escreveu:

**Comment by DanielnetoDotCom** [comment]
is it fixed?

**Comment by benIT** [comment]
nope,
I dropped DB and run install again : still the same issue.
I provision another VM with ubuntu/PHP 7.0 this is running fine whereas the issue is still here on the debian VM with PHP 5.6.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
