### ISSUE TITLE
 currently serious issue i have

### ISSUE THREAD

**Issue by harismaqsood** [DanielnetoDotCom/YouPHPTube#630]
my youphpTube site is not showing live on server, i have been not fix this issue, like directory and configuration can any tell me how can i fixed it, 
[https://www.tube80.com](url)

**Comment by DanielnetoDotCom** [comment]
Hi, I dont know what is your issue, can you please explain it better?

**Comment by harismaqsood** [comment]
but Sir this site is accurate run on localhost.  
I check all lines in config-file. but its still showing this error. 
Warning: require_once(1objects/include_config.php): failed to open stream: No such file or directory in /home3/asimmukhtar/public_html/videos/configuration.php on line 18

Fatal error: require_once(): Failed opening required '1objects/include_config.php' (include_path='.:/opt/php54/lib/php') in /home3/asimmukhtar/public_html/videos/configuration.php on line 18

**Comment by hersche** [comment]
i don't know how you handle your this, but in require_once(1objects/include_config.php): the "1" is too much. it's only 
require_once("objects/include_config.php"); - like.

and also, when i go to your site, there's no more error, but a inform that you should enable modrewrite for your apache

**Comment by harismaqsood** [comment]
but still shwoing error -_-​. on https://www.tube80.com/

**Comment by harismaqsood** [comment]
i sent you my configuration coding

**Comment by hersche** [comment]
where do you send it?

pastebin or similiar would be fine..

**Comment by harismaqsood** [comment]
i send you sscreen shots​

**Comment by harismaqsood** [comment]
​

**Comment by harismaqsood** [comment]
​website still showing same errors​

**Comment by hersche** [comment]
can you paste it here?
https://pastebin.com/

i don't see any screenshots, but for corrections, text is anyway better..

**Comment by harismaqsood** [comment]
yes sure sir

**Comment by harismaqsood** [comment]
pasted..!

**Comment by harismaqsood** [comment]
https://pastebin.com/vYW5aR0a

**Comment by hersche** [comment]
can you try this?

http://piratepad.net/tube80-conf

**Comment by harismaqsood** [comment]
"First Of all I am very thankfull to you for kindly services, help and
response"
yes i already try this but now showing this error on tube80.com

*Warning*: mysqli::mysqli(): (42000/1044): Access denied for user
'asimmukh_asim'@'localhost' to database 'asimumkh_tubeplus' in
*/home3/asimmukhtar/public_html/objects/include_config.php* on line *6*

*Warning*: mysqli::query(): Couldn't fetch mysqli in
*/home3/asimmukhtar/public_html/objects/include_config.php* on line *15*

*Fatal error*: Can't use function return value in write context in
*/home3/asimmukhtar/public_html/objects/user.php* on line *140*

**Comment by hersche** [comment]
this is the next problem. the login for the database is not alright.

this can be a general mysql-"problem" i think, because you have special characters like ^ in the password.

because this pastes are public, i would maybe change the password anyway, and also to something withouth ^ or _ .

you can also e-mail me, if you like more direct support: vinzenz.hersche@gmail.com

**Comment by hersche** [comment]
this is fixed latest with #667 (private tested)
