### ISSUE TITLE
Not displaying "live" issue fixed

### ISSUE THREAD

**Issue by davidjmaxey** [DanielnetoDotCom/YouPHPTube#632]
Not sure if this is the best place to mention this but I had issues again with the live stream randomly not showing it was live. I discover the issue to be in my /usr/local/nginx/conf/nginx.conf file.

If my "worker_processes  1;" showed anything other than the default 1, the issue would happen. Attempting to fine tune nginx, I put this setting to auto and everytime I do I get the intermittent no live showing issue..

**Comment by DanielnetoDotCom** [comment]
Nice, what was exactly your issue?

and what value did you put on  "worker_processes"

**Comment by davidjmaxey** [comment]
So the issue was the live button would random show offline even when the feed was live. Using a worker_pressess of 1 works fine but auto or anything else did not. Often with nginx I set this value to my cpu core count but this does not work well in that case which seems fine for this purpose.

**Comment by DanielnetoDotCom** [comment]
Great, I learn something on that and I guess it will help others.

Thanks @davidjmaxey
