### ISSUE TITLE
Deleting YouPHPTube-Encoder tmpFile_converted_SD.mp4

### ISSUE THREAD

**Issue by gseiki** [DanielnetoDotCom/YouPHPTube#633]
Is it safe to delete the *_tmpFile_converted_SD.mp4 files found in /var/www/html/YouPHPTube-Encoder/videos? Or, are they needed?

**Comment by DanielnetoDotCom** [comment]
after encode is finished you can delete with no problem

**Comment by gseiki** [comment]
Thanks! Deleting those temp files cleared up 30GBs of space on my server.

**Comment by DanielnetoDotCom** [comment]
:)
