### ISSUE TITLE
Can't get Captcha loaded

### ISSUE THREAD

**Issue by martinustrinc** [DanielnetoDotCom/YouPHPTube#635]
Hello,
I have a problem with this log..
Anyone can help me?
[26-Apr-2018 16:44:24] PHP Fatal error: Uncaught Error: Call to undefined function imagecreate() in /var/www/html/YouPHPTube/objects/captcha.php:23
Stack trace:
#0 /var/www/html/YouPHPTube/objects/getCaptcha.php(10): Captcha->getCaptchaImage()
#1 {main}
thrown in /var/www/html/YouPHPTube/objects/captcha.php on line 23

**Comment by DanielnetoDotCom** [comment]
This means your installation of php doesn't have the gd library installed/enabled. 

`sudo apt-get install php7.0-gd`

to install the php_gd2.dll extension. It will then work after an Apache restart.

**Comment by martinustrinc** [comment]
thank's it works

**Comment by DanielnetoDotCom** [comment]
Great :)

**Comment by directorsty** [comment]
have the same issue even after installing "php-gd" captcha fails to load
kindly assist
