### ISSUE TITLE
Title video name in youphptube from 3rd party app

### ISSUE THREAD

**Issue by abamilod** [DanielnetoDotCom/YouPHPTube#636]
Hello again,
Please make the video title name as the file name when uploading from 3rd party app (just like upload file from encoder title name). Usually it starts with original_username_***.
For example file name : Custom WIFI Landing Page.mp4 
![sample](https://user-images.githubusercontent.com/25945730/39348778-12ddb28a-4a2b-11e8-983b-402799f6c3b0.png)

The video title is too long and not human readable name. Thank you.

**Comment by abamilod** [comment]
We can edit upload.php file in plugin MobileManager to change video title name.
    //$filename = uniqid($mainName . "_YPTuniqid_", true);

But the filename will always have a prefix name : original_[filename]. I dont know why. If anyone knows how to remove this prefix please share. Thank you.

**Comment by hersche** [comment]
can't you just change the title of the videos?

respective, we should make the title clean, not the filename.. i am not shure about this, but i think it has it's sense in the filenames (one part is a hash-sum, that definently make sense)

**Comment by hersche** [comment]
and, when it's about downloading, try the download-option in the settings - it is using the title as download-name.

**Comment by abamilod** [comment]
1. yes we can change the title of each videos manually but I am trying to setup an auto system sending out video by schedule without human/user intervene.
2. at upload setting we can set video title and description before upload it. But can we do it by API? so far I can see parameter for API : username, hashcode password, file video only.
