### ISSUE TITLE
on mobile + Add to menu is hidden

### ISSUE THREAD

**Issue by davidjmaxey** [DanielnetoDotCom/YouPHPTube#639]
When I load any video on a mobile phone (using iphone x) the +Add to Menu is half hidden as shown in the screen shot. Is there css I can tweak to fix this?

![menucovered](https://user-images.githubusercontent.com/13489763/39382280-f8cc277a-4a32-11e8-906d-054c295e6712.jpeg)

**Comment by DanielnetoDotCom** [comment]
The add to button is really a problem I will be fix in the future.

but the video for some reason, I could not reproduce it
