### ISSUE TITLE
Does not work on web: Error 500

### ISSUE THREAD

**Issue by germapace** [DanielnetoDotCom/YouPHPTube#646]
In local work but I wanted to place it in
http://www.cirugiadetobilloypie.video/
housed in godaddy and it does not work
![not_work](https://user-images.githubusercontent.com/17485096/39497308-1195b75a-4d79-11e8-9eee-e8f3e62f9d8e.jpg)

**Comment by germapace** [comment]
I was looking at the error_log file and it shows

[02-May-2018 01:19:21 UTC] PHP Warning:  require_once(public_html/cirugiadetobilloypie.video/objects/include_config.php): failed to open stream: No such file or directory in /home/germanpace/public_html/cirugiadetobilloypie.video/videos/configuration.php on line 35
[02-May-2018 01:19:21 UTC] PHP Fatal error:  require_once(): Failed opening required 'public_html/cirugiadetobilloypie.video/objects/include_config.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/germanpace/public_html/cirugiadetobilloypie.video/videos/configuration.php on line 35
[02-May-2018 01:19:24 UTC] PHP Warning:  require_once(public_html/cirugiadetobilloypie.video/objects/include_config.php): failed to open stream: No such file or directory in /home/germanpace/public_html/cirugiadetobilloypie.video/videos/configuration.php on line 35
[02-May-2018 01:19:24 UTC] PHP Fatal error:  require_once(): Failed opening required 'public_html/cirugiadetobilloypie.video/objects/include_config.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/germanpace/public_html/cirugiadetobilloypie.video/videos/configuration.php on line 35

**Comment by germapace** [comment]
35 require_once $global['systemRootPath'].'objects/include_config.php';

**Comment by DanielnetoDotCom** [comment]
Yes, can you please check if this file exists?

`public_html/cirugiadetobilloypie.video/objects/include_config.php`

**Comment by germapace** [comment]
Yes, there is that file really
![archivo](https://user-images.githubusercontent.com/17485096/39531935-ad4cf666-4e02-11e8-832a-0643cf3ab139.jpg)

**Comment by DanielnetoDotCom** [comment]
You are on windows, we support only linux

![image](https://user-images.githubusercontent.com/18009293/39534139-4630fab8-4e07-11e8-8935-ac36e3f4de8b.png)

**Comment by germapace** [comment]
yes but the godaddy platform where the domain is hosted is in linux

**Comment by germapace** [comment]
![archivo2](https://user-images.githubusercontent.com/17485096/39534732-a8580622-4e08-11e8-8ae8-952526ae109c.jpg)

**Comment by DanielnetoDotCom** [comment]
Ok, you have to make sure that file exists on godady NOT locally

**Comment by germapace** [comment]
yes, for now I install the basic package without encode

**Comment by germapace** [comment]
Eu acho que deveria ser um tópico de rotas

**Comment by DanielnetoDotCom** [comment]
and this file `public_html/cirugiadetobilloypie.video/objects/include_config.php` exists on godaddy?

**Comment by germapace** [comment]
yes , 
![image](https://user-images.githubusercontent.com/17485096/39591105-1bad6164-4ed9-11e8-9085-9956d183bbc7.png)

**Comment by germapace** [comment]
![image](https://user-images.githubusercontent.com/17485096/39591136-2fa849fe-4ed9-11e8-83cc-a8feaf23e30e.png)

**Comment by germapace** [comment]
yes, it exists, what you see is communicated directly by ftp with godaddy

**Comment by DanielnetoDotCom** [comment]
how is your configuration file, I guess you have an error on your **systemRootPath**

**Comment by germapace** [comment]
with a friend developer we found the error
![image](https://user-images.githubusercontent.com/17485096/39643321-c86e07ec-4faa-11e8-8f95-980111d90409.png)

**Comment by germapace** [comment]
before it was
![image](https://user-images.githubusercontent.com/17485096/39643383-f4964f82-4faa-11e8-97b1-597e886cc74e.png)

**Comment by DanielnetoDotCom** [comment]
Sorry, what was the error?

**Comment by germapace** [comment]
Bem, muito obrigado, vou tentar um pouco mais para instalar o seu script, e se eu não procurar por um menos elaborado
Saudações

**Comment by germapace** [comment]
![image](https://user-images.githubusercontent.com/17485096/39664269-1834c80e-5057-11e8-85da-0bbca045830d.png)

**Comment by germapace** [comment]
the last mistake goes on
05-May-2018 14:13:33 UTC] PHP Fatal error:  Call to undefined method mysqli_stmt::get_result() in /home/germanpace/public_html/cirugiadetobilloypie.video/objects/user.php on line 490

**Comment by germapace** [comment]
I put in a .txt file all the errors
[error.txt](https://github.com/DanielnetoDotCom/YouPHPTube/files/1976761/error.txt)

**Comment by germapace** [comment]
Do you want the username ftp password and ftp address to pass, so can you see the error ?

**Comment by DanielnetoDotCom** [comment]
@germapace if the error now is the `Fatal error: Call to undefined method mysqli_stmt::get_result()`it is something regarding your mysql driver.

try to google for that, I am sure you will find many problems like yours

**Comment by germapace** [comment]
Muchas gracias ahi encontre el problema el método mysqli_stmt::get_result solo esta disponible con el controlador nativo de MySQL mysqlnd . Disculpa que te responda en mi idioma nativo
https://www.phpcentral.com/pregunta/674/fatal-error-call-to-undefined-method-mysqli-stmtget-result

**Comment by DanielnetoDotCom** [comment]
Great I am glad you found a solution.
let us know if is all working fine now.

**Comment by hersche** [comment]
@germapace i worked on a solution withouth stmt::get_result / mysqlnd.
when you still can not continue or have your old host (withouth mysqlnd), i would please you to test this version: https://github.com/hersche/YouPHPTube/tree/unstable

**Comment by germapace** [comment]
![image](https://user-images.githubusercontent.com/17485096/39885971-747d7a3c-5464-11e8-894c-a5ed9541afe8.png)

**Comment by germapace** [comment]
http://cirugiadetobilloypie.video/

**Comment by hersche** [comment]
ok. that looks nice! :+1: 

is this on a host withouth mysqlnd now? so does it work?

**Comment by germapace** [comment]
that is a basic html clone that adds the foreach to a basic html clone, because yours did not work and in the video tab it shows with that foreach all my youtube videos
http://cirugiadetobilloypie.video/

**Comment by hersche** [comment]
yeah, ok, i thinked, it has maybe something to do with the issue, because you are talking about.

i hope, the new code is fixing it.

on another host with another user, it was a success, so i think it will work.

**Comment by germapace** [comment]
I'm going to try it, and I'll pass the link, I'm starting with programming, after 20 years as a traumatologist, now it's my hobby and I love php

**Comment by hersche** [comment]
do you tried it? does it work with a update?

**Comment by hersche** [comment]
one successfull install from my side, no response here, so i close it.
