### ISSUE TITLE
Error creating admin user: Field 'channelName' doesn't have a default value

### ISSUE THREAD

**Issue by dimitar83** [DanielnetoDotCom/YouPHPTube#647]
Hi,

I get this error with a new installation on new Ubuntu 16.x:
Error creating admin user: Field 'channelName' doesn't have a default value

Can you please please?

I use the manual from here:
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x-For-YouPHPTube-version-4.x-or-newer
![clipboard02](https://user-images.githubusercontent.com/38901442/39505485-46bc5850-4ddb-11e8-8f38-bda487ead630.jpg)

**Comment by DanielnetoDotCom** [comment]
sorry, let me see, I will try now

**Comment by DanielnetoDotCom** [comment]
My Bad, please try again now

**Comment by dimitar83** [comment]
Now works, thank you very much!

**Comment by DanielnetoDotCom** [comment]
Great :)
