### ISSUE TITLE
[5.3] [phone device] Not-clickable element on the home page

### ISSUE THREAD

**Issue by ChrisSlS** [DanielnetoDotCom/YouPHPTube#648]
Hello,

First of all, thanks for the latest update, the changes are appreciable, I really liked the option "channel name" :)

So, here is the current problem, impossible to click on the videos framed in red :

![no-click](https://user-images.githubusercontent.com/37787071/39552960-cdb42c62-4e6b-11e8-92e7-d20e95f15d79.png)

This bug is apparent on every part, namely "Date added", "Most watched", "Most popular".

Then there is also another problem, always being on the homepage. There are empty spaces, because some characters like the string name are too long.

![blankspace](https://user-images.githubusercontent.com/37787071/39553234-e2b98188-4e6c-11e8-9dee-21db568ef063.png)

I tried various ways, like removing the tags but the problem is the same.

**Comment by DanielnetoDotCom** [comment]
Hi thanks for notice it, we will find a way to fix it
