### ISSUE TITLE
several tables not getting created

### ISSUE THREAD

**Issue by magicmissile72** [DanielnetoDotCom/YouPHPTube#649]
Fresh build on Debian 9.3
Followed directions and install went well. The only deviation I made from the install was i created a user account and database for both streamer and encoder rather than use the root. 

<snip>
CREATE DATABASE youPHPTube;
CREATE USER 'youphptube'@'localhost' IDENTIFIED BY 'sanitized';
GRANT ALL PRIVILEGES ON youPHPTube.* TO youphptube@localhost;
FLUSH PRIVILEGES;

CREATE DATABASE youPHPTubeEncoder;
CREATE USER 'youphptubecoder'@'localhost' IDENTIFIED BY 'sanitized';
GRANT ALL PRIVILEGES ON youPHPTubeEncoder.* TO youphptubecoder@localhost;
FLUSH PRIVILEGES;
</snip>

I added both accounts on the install page and it 'appears' to have installed correctly, however several options in the streamer admin portal generate db errors. Example:
Login as admin
click "My Video's"
click "Video Chart"
generates this error:
<snip>
SELECT u.*, v.*, c.iconClass, c.name as category, c.clean_name as clean_category,c.description as category_description, v.created as videoCreation, v.modified as videoModified, (SELECT count(id) FROM video_ads as va where va.videos_id = v.id) as videoAdsCount, (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = 1 ) as likes, (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = -1 ) as dislikes FROM videos as v LEFT JOIN categories c ON categories_id = c.id LEFT JOIN users u ON v.users_id = u.id WHERE 1=1 AND v.status IN ('a','xmp4','xwebm','xmp3','xogg') having videoAdsCount = 0 AND v.users_id = '1'\nError : (1146) Table 'youPHPTube.videos' doesn't exist
</snip>

Similarly, clicking "Dashboard" generates this:
<snip>
SELECT u.*, v.*, c.iconClass, c.name as category, c.clean_name as clean_category,c.description as category_description, v.created as videoCreation, v.modified as videoModified, (SELECT count(id) FROM video_ads as va where va.videos_id = v.id) as videoAdsCount, (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = 1 ) as likes, (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = -1 ) as dislikes FROM videos as v LEFT JOIN categories c ON categories_id = c.id LEFT JOIN users u ON v.users_id = u.id WHERE 1=1 AND v.status IN ('a','xmp4','xwebm','xmp3','xogg') having videoAdsCount = 0 AND v.users_id = '1'\nError : (1146) Table 'youPHPTube.videos' doesn't exist
</snip>

Looks to be the same...

**Comment by DanielnetoDotCom** [comment]
Hi, why didnt you let the script creates your database?

**Comment by magicmissile72** [comment]
I did that the first time, and same effect.
Build attempt 1
a. Changed user from root to my created user for the database
b. built DB in Maria and added user (see above commands)
c. selected the 'create database and tables' options

This did not work and I get the missing tables.

So I rebuilt it with the same process, but selected 'create only the tables' option.

Are you suggesting I should be giving the script 'root' to create and use the database?

**Comment by DanielnetoDotCom** [comment]
@magicmissile72 I dont know what is happening.

Usually is very simple, you just let the script creates the database.

and that is the way I usually do.

**Comment by magicmissile72** [comment]
Thank you Daniel, I did some research and found that this is in fact a problem with MariaDB 10.1...the best fix for Debian 9 users which installs version 10.1 is to manually install 10.2. I did that on a fresh install of Debian 9.3, added the Maria DB repository, installed, the continued on with your original config minus the 'mysql-server' and 'mysql-client' files. Also I did not install as 'root', but created the DB manually.

It works like a CHAMP!!!! Wow!!!

I am super impressed with what you have done and you should be quite proud of your accomplishment.

Next step is to separate the encoder and DB and build as a multi-tier application.

For anyone wanting to follow, the Debian 9.3 build is...
-----------------------------------------------------------
1. Install Debian 9.3 from net-install cd or dvd1

2. Select only 'ssh server' and 'common tools'

3. Finish install and secure/customize with any addiitonl apps you need (like htop, vmware-tools, etc)

4. ssh in and configure IP and DNS

5. Install MariaDB 10.2 from the repository

apt-get install software-properties-common dirmngr
# (wait for install to complete...)

apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xF1656F24C74CD1D8
# (wait for install to complete...)

add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://ftp.osuosl.org/pub/mariadb/repo/10.2/debian stretch main'

apt-get update

apt-get install mariadb-server

6. MariaDB will ask for a password during install...so enter one

7. Run the 'secure install' for MySQL/MariaDB

mysql_secure_installation

8. Login to MariaDB

mysql -u root -p

9. Create the Main Database (youPHPTube)

CREATE DATABASE youPHPTube;
CREATE USER 'youphptube'@'localhost' IDENTIFIED BY '---------------';
GRANT ALL PRIVILEGES ON youPHPTube.* TO youphptube@localhost;
FLUSH PRIVILEGES;

10. Create the Encoder Database (youPHPTube-Encoder)
note: no hyphen, Maria with barf on that...

CREATE DATABASE youPHPTubeEncoder;
CREATE USER 'youphptubecoder'@'localhost' IDENTIFIED BY '---------------';
GRANT ALL PRIVILEGES ON youPHPTubeEncoder.* TO youphptubecoder@localhost;
FLUSH PRIVILEGES;

quit;

11. Continue with main install script sans mysql (we installed that above)
# removed 'mysql-server mysql-client' from snippet
# use this instead...

apt-get install curl apache2 php7.0 libapache2-mod-php7.0 php7.0-mysql \
	php7.0-curl php7.0-gd php7.0-intl ffmpeg git libimage-exiftool-perl \
	&& cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube.git \
	&& cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube-Encoder.git \
	&& sudo apt-get install python \
	&& sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl \
	&& sudo chmod a+rx /usr/local/bin/youtube-dl && sudo a2enmod rewrite


12. restart Apache
systemctl restart apache2

13. Pre-configre YouPHPTube...past the following in the CLI and wait...
# The 'cat' show a before an after as a sort of error checking...
# I need to make this into a shell script...

# start
mkdir /var/www/html/YouPHPTube/videos

mkdir /var/www/html/YouPHPTube-Encoder/videos

chown -R www-data:www-data /var/www/html/YouPHPTube/

chmod 755 /var/www/html/YouPHPTube/videos 

chown -R www-data:www-data /var/www/html/YouPHPTube-Encoder/

chmod 755 /var/www/html/YouPHPTube-Encoder/videos 

cat /etc/php/7.0/apache2/php.ini | grep post_max_size

sed -i -e 's/post_max_size = 8M/post_max_size = 1000M/g' /etc/php/7.0/apache2/php.ini

cat /etc/php/7.0/apache2/php.ini | grep post_max_size

cat /etc/php/7.0/apache2/php.ini | grep upload_max_filesize

sed -i -e 's/upload_max_filesize = 2M/upload_max_filesize = 1000M/g' /etc/php/7.0/apache2/php.ini

cat /etc/php/7.0/apache2/php.ini | grep upload_max_filesize

cat /etc/php/7.0/apache2/php.ini | grep max_execution_time

sed -i -e 's/max_execution_time = 30/max_execution_time = 7200/g' /etc/php/7.0/apache2/php.ini

cat /etc/php/7.0/apache2/php.ini | grep max_execution_time

cat /etc/php/7.0/apache2/php.ini | grep memory_limit

sed -i -e 's/memory_limit = 128M/memory_limit = 512M/g' /etc/php/7.0/apache2/php.ini

cat /etc/php/7.0/apache2/php.ini | grep memory_limit

systemctl restart apache2

# End

14. Edit Apache...
hint: edit line 172, change None to all

vi /etc/apache2/apache2.conf

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>

15.  Restart Aapche...

systemctl restart apache2

16. Go to your main site URL: <your domain>/YouPHPTube/install

17. Go to your encoder site URL: <your domain>/YouPHPTube-Encoder/install

18. Enjoy!
-----------------------------------------------------------

Thanks again!

**Comment by DanielnetoDotCom** [comment]
@magicmissile72 I really apprecciate your tutorial, I am positive it will help others

**Comment by hersche** [comment]
@DanielnetoDotCom can you paste it in the wiki beside the ubunut 16.04-article? i think that would be the best place for the tutorial :)

**Comment by hersche** [comment]
i made this wiki-entry for it

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Install-YouPHPTube-in-Debian-9.3

so i think this can be closed. thank you for this, @magicmissile72 !
