### ISSUE TITLE
error by istallation

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#65]
You can help me after installing this error
SELECT * FROM categories WHERE 1=1 \nError : (1146) Table 'youtube.categories' doesn't exist
https://youtub.mikweb.eu/user?error=You%20need%20to%20%3Ca%20href=%27https://youtub.mikweb.eu/update%27%3Eupdate%20your%20system%20to%20ver%202.0%3C/a%3E

ubuntu 16.04 
plesk onix
php 7.1

**Comment by DanielnetoDotCom** [comment]
Please drop your youphptube database and try again

Atenciosamente

Daniel Neto

PHP ZEND 4/5 Certified Engineer
PHP Zend Certification - Authentication
http://zend.com/zce.php?c=ZEND001318&r=209210010

Programming in HTML5 with JavaScript and CSS3 Specialist (MCP 70-480)
https://mcp.microsoft.com/authenticate/ValidateMCP.aspx
Transcript ID (1040640) and the Access Code (danielNeto)

**Comment by mikweb2017** [comment]
I deleted the database and tried again 5 but I have the same error

I deleted the database and the error remained the same despite the database being empty
Is it about modrewrite?
I have plesk and setup is always red if I run the command schell Module rewrite already enabled

some idea?

**Comment by mikweb2017** [comment]
Fine work done works
