### ISSUE TITLE
Error creating admin user: Field 'channelName' doesn't have a default value

### ISSUE THREAD

**Issue by jollero** [DanielnetoDotCom/YouPHPTube#650]
I am getting this error on the installation page. Everything seems to be checked out but I don't know why Im getting this.

Any ideas on what to check is appreciated. 

Thanks!

**Comment by DanielnetoDotCom** [comment]
did you update your version?

![image](https://user-images.githubusercontent.com/18009293/39580289-32ecc1e0-4ebf-11e8-8b57-83037618ecdc.png)

**Comment by hersche** [comment]
looks like this is working and therefore done. reopen, when i am wrong, please.
