### ISSUE TITLE
 I can not embed videos in wordpress

### ISSUE THREAD

**Issue by restriato** [DanielnetoDotCom/YouPHPTube#651]
I can not embed videos in wordpress, I select the video, I click embed, I copy the code, I paste it on the page that I want it to appear, but the video does not appear. I tried several wordpress installations, on different servers (thinking that maybe a firewall had blocked) but to no avail. I tried to use only the link permanete and insert in a player also did not work. I cleaned the entire server and I installed the script from scratch and it also did not work, can you help me to verify what it could be?

**Comment by DanielnetoDotCom** [comment]
is your youphptube http or https?

and your word press site http or https?

**Comment by restriato** [comment]
My Youphptube is with http
My wordpress with https

**Comment by restriato** [comment]
do you have any tutorial to use https on youphptube? I already installed the encrypted lets on the server

**Comment by hersche** [comment]
you can edit

videos/configuration.php (in your youphptube-folder)

and change the http:// to https://

(maybe you have to do more on your server, but this is needed for youphptube itself)

i also tried it quickly and it works, but on my site, both is https://.

another, small but important thing: from visual and text in wordpress-editor (2 buttons, right upper corner), you have choose text, i think? if not, do. but the ssl-problem seems more realistic..

**Comment by restriato** [comment]
That's right @ I got it, thank you!

**Comment by hersche** [comment]
nice :+1: 
was it https:// or visual/text?
and, when it works, can you close the issue?

**Comment by restriato** [comment]
works with https!

**Comment by guymass** [comment]
I have the same problem, I cannot embed videos on my wordpress site. They are both running https and I keep getting error of not being able to embed my videos. I thought to use the share button but there is none. What can I do?

**Comment by DanielnetoDotCom** [comment]
How are you embeding the videos?

Make sure you are using an iframe

**Comment by guymass** [comment]
I figured it out, sorry for late replay. I have to make to videos shareable to be able to copy to embed link.
