### ISSUE TITLE
Bouton send mail to test smtp configuration

### ISSUE THREAD

**Issue by gamersalpha** [DanielnetoDotCom/YouPHPTube#652]
Hello there, i think it will be good to have a bouton test send when we configure the smtp : 
![image](https://user-images.githubusercontent.com/32466950/39592593-80c23010-4f07-11e8-8253-0c412850a11a.png)

**Comment by ChrisSlS** [comment]
Oh, good idea. I will try to make it but I promise nothing.

**Comment by DanielnetoDotCom** [comment]
I also like the idea

**Comment by DanielnetoDotCom** [comment]
I will send an update soon
