### ISSUE TITLE
Embeed Video

### ISSUE THREAD

**Issue by brajeshrgupta** [DanielnetoDotCom/YouPHPTube#653]
Hi

I have some quires for Embed Videos

1. Can we show ads on embedded video ( Pre roll and overlay)

2. Can we set auto play on 

3. Can  next video will be played as in main video page

4. Can we suggest another video to user (on main video also)

Regards

Brajesh

**Comment by DanielnetoDotCom** [comment]
>     Can we show ads on embedded video ( Pre roll and overlay)
Yes with google IMA plugin
>     Can we set auto play on
Yes
>     Can next video will be played as in main video page
Not now, but yes on the future
>     Can we suggest another video to user (on main video also)
What do you mean?

**Comment by brajeshrgupta** [comment]
Can we suggest another video to user (on main video also)


LIke You tube end screen - some other videos are shown to user and on selection that vide0 is played

**Comment by brajeshrgupta** [comment]
How to set auto play on

**Comment by brajeshrgupta** [comment]
IF I enable Google IMA plugin then ads are displayed automatically or any changes to be done to show ads on Embedded videos

**Comment by DanielnetoDotCom** [comment]
It is automatic, check the demo link https://demo.youphptube.com/videoEmbed/o-melhor-lugar-do-mundo-eli-soares
