### ISSUE TITLE
first page layout

### ISSUE THREAD

**Issue by Nisarg22** [DanielnetoDotCom/YouPHPTube#654]
If
![screenshot_20180505-175356](https://user-images.githubusercontent.com/39002772/39663252-8d1f9f50-508d-11e8-8a52-2d3c273c65ee.jpg)
![screenshot_20180505-175419](https://user-images.githubusercontent.com/39002772/39663253-8d6b8cbc-508d-11e8-956f-f98eed7d04b2.jpg)

 we set our first page layout to gallery or netflix look and after if we close it our first page directly show first video instead of showing videos list
First image is of gallery plugin on
And second is after gallery plugin of
Both at first page

**Comment by DanielnetoDotCom** [comment]
Sorry, I don't understand what do you mean.

Can you please put some screenshots?
