### ISSUE TITLE
fix  please  live  settings in progress

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#655]
i do not know what happened after i update in the live section i have this
processing never end.
![bildschirmfoto 2018-05-06 um 09 45 47](https://user-images.githubusercontent.com/30271757/39671113-5dcaa7ec-5112-11e8-992e-73fd19d11917.png)

![bildschirmfoto 2018-05-06 um 09 49 28](https://user-images.githubusercontent.com/30271757/39671135-cf5c437a-5112-11e8-8ff7-f9646106c8ff.png)

**Comment by DanielnetoDotCom** [comment]
Your LiveChat now, persist data.

Go to the plugins and isntall livechat tables
![image](https://user-images.githubusercontent.com/18009293/39673430-76fac3c8-5112-11e8-82cd-1c13f560adb8.png)

**Comment by mikweb2017** [comment]
ok thanks
