### ISSUE TITLE
Navbar issues

### ISSUE THREAD

**Issue by RisKatOr** [DanielnetoDotCom/YouPHPTube#663]
Hi,

There is no streaming but LIVE NOW flashing also no video-camera icon.

![ekran goruntusu_2018-05-08_12-45-17](https://user-images.githubusercontent.com/4102352/39751685-93df4ce2-52c1-11e8-8055-c7976b445882.png)

**Comment by DanielnetoDotCom** [comment]
I will fix it today , sorry

**Comment by RisKatOr** [comment]
Thank you,

What about fa-video icon ?

![39751685-93df4ce2-52c1-11e8-8055-c7976b445882](https://user-images.githubusercontent.com/4102352/39767926-8c255300-52f0-11e8-8fdc-20d1fad3156c.png)

**Comment by RisKatOr** [comment]
![adsiz](https://user-images.githubusercontent.com/4102352/39768543-476da652-52f2-11e8-847c-b53a7708f994.jpg)


I changed to "fas fa-video" and all right.

Thank you,
