### ISSUE TITLE
No SD/HD change option

### ISSUE THREAD

**Issue by amishultimatehacker** [DanielnetoDotCom/YouPHPTube#664]
Hey Daniel, The Videos being played aren't showing SD/HD changing option

**Comment by hersche** [comment]
hey amish,

this is a commercial plugin, name: VideoResolutionSwitcher, link: https://easytube.club/

**Comment by amishultimatehacker** [comment]
So does those videos autoswitch qualities in basic version

**Comment by DanielnetoDotCom** [comment]
@amishultimatehacker id does not, it will use the first video found. in case you make all 3 resolutions, it will be low.

**Comment by amishultimatehacker** [comment]
Ok I will Buy the Premium Plugin very Soon
