### ISSUE TITLE
Error when Attempting to install PHP using Wiki Script Ubuntu 18.04

### ISSUE THREAD

**Issue by PFH1987** [DanielnetoDotCom/YouPHPTube#668]
OS: Ubuntu 18.04 Desktop

When attempting to run the code shown below copied from the wiki I get the following error.
*************:~$ sudo apt-get install apache2 php7.0 libapache2-mod-php7.0 php7.0-mysql php7.0-curl php7.0-gd php7.0-intl mysql-server mysql-client ffmpeg git libimage-exiftool-perl && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube.git && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube-Encoder.git && sudo apt-get install python && sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && sudo chmod a+rx /usr/local/bin/youtube-dl && sudo a2enmod rewrite
[sudo] password for patrickh: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'php7.0-remctl' for regex 'php7.0'
Note, selecting 'php7.0-common' for regex 'php7.0'
Note, selecting 'php-remctl' instead of 'php7.0-remctl'
E: Unable to locate package libapache2-mod-php7.0
E: Couldn't find any package by glob 'libapache2-mod-php7.0'
E: Couldn't find any package by regex 'libapache2-mod-php7.0'
E: Unable to locate package php7.0-mysql
E: Couldn't find any package by glob 'php7.0-mysql'
E: Couldn't find any package by regex 'php7.0-mysql'
E: Unable to locate package php7.0-curl
E: Couldn't find any package by glob 'php7.0-curl'
E: Couldn't find any package by regex 'php7.0-curl'
E: Unable to locate package php7.0-gd
E: Couldn't find any package by glob 'php7.0-gd'
E: Couldn't find any package by regex 'php7.0-gd'
E: Unable to locate package php7.0-intl
E: Couldn't find any package by glob 'php7.0-intl'
E: Couldn't find any package by regex 'php7.0-intl'

The code does run if eliminate the libraries listed but the site failes to run. 

[Install LAMP, FFMPEG, and GIT on Ubuntu 16](https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x-For-YouPHPTube-version-4.x-or-newer)

**Comment by hersche** [comment]
like the title said, this is for ubuntu 16, not 18..

just for the future, please use 

apt search apache php

or ask google..

i have rechecked it, all 7.0 must be replaced with 7.1 or 7.2, depend on which version you want to use. i can recomend 7.1, since i'm using it.

**Comment by DanielnetoDotCom** [comment]
Agree with @hersche .

Probably php7.0 is not available for ubuntu 18 anymore

**Comment by hersche** [comment]
i made those sites:

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-YouPHPTube-version-4.x-or-newer

https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x---For-YouPHPTube-Encoder

so that should be good, also when we have no feedback - but because of inactivity and those copy-paste-articles, i close it.
