### ISSUE TITLE
video share Thumbnail 

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#67]
In sharing videos on faceboock and twittwer is generated it has cut the usual Thumbnail for all the videos then fix this please

**Comment by DanielnetoDotCom** [comment]
Hi, can you give me an example?
What is the website you are sharing?

**Comment by mikweb2017** [comment]
https://youtub.mikweb.eu/tube/video/applescript-tutorial-4

**Comment by DanielnetoDotCom** [comment]
You right i will fix this on the next release (I guess will come on next week)

**Comment by mikweb2017** [comment]
thank you very much
