### ISSUE TITLE
Black Video, various others - commit May 10

### ISSUE THREAD

**Issue by cbuchmannNM** [DanielnetoDotCom/YouPHPTube#672]
I'm having issues with the newest update; May 10 2018.
Only one video is shown for any specific category.
When played any video there is only a black screen.
![prob1](https://user-images.githubusercontent.com/38256644/39914450-608fa31e-5505-11e8-9b9f-5830154f6c79.PNG)
The database haven't been changed in any other way.
When downloaded per scp I can view the videos on my local machine.

**Comment by cbuchmannNM** [comment]
As you can see there is also no image for the change language button and I am not able to use the button, as there is nothing happening after a mouse click.

**Comment by cbuchmannNM** [comment]
Here is the log attached.
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/1994570/youphptube.log)

**Comment by DanielnetoDotCom** [comment]
I found a bug from last update, I will send a fix soon.

Very thanks for notice it

**Comment by cbuchmannNM** [comment]
5866c6a seems to fix the issue, gonna run a test over the weekend

**Comment by cbuchmannNM** [comment]
Working great, thank you.
