### ISSUE TITLE
Live video instead big video on home page

### ISSUE THREAD

**Issue by RisKatOr** [DanielnetoDotCom/YouPHPTube#673]
Hi,

How to make that if there is a live broadcast, then instead of a BigVideo was liveVideo ?

![bigvideo](https://user-images.githubusercontent.com/4102352/39915808-8e4ef79e-5511-11e8-850c-81b7341a122e.jpg)

**Comment by DanielnetoDotCom** [comment]
That will be a good idea. but is not possible yet

**Comment by RisKatOr** [comment]
Yes, it would be a good function, we will wait :)
