### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#676]
Update issue...

cd /var/www/html/YouPHPTube/ && sudo git pull

There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
    git pull <remote> <branch>
If you wish to set tracking information for this branch you can do so with:
    git branch --set-upstream-to=origin/<branch> master

**Comment by DanielnetoDotCom** [comment]
did you install YouPHPTube using Git?

check here https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x-For-YouPHPTube-version-4.x-or-newer

**Comment by hersche** [comment]
no feedback, so i close it..
