### ISSUE TITLE
google login

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#68]
https://youtub.mikweb.eu/user?error=Signed+API+request+has+returned+an+error.+HTTP+error+403.+Raw+Provider+API+response%3A+%7B%0A+%22error%22%3A+%7B%0A++%22errors%22%3A+%5B%0A+++%7B%0A++++%22domain%22%3A+%22usageLimits%22%2C%0A++++%22reason%22%3A+%22accessNotConfigured%22%2C%0A++++%22message%22%3A+%22Access+Not+Configured.+Google%2B+API+has+not+been+used+in+project+853512518643+before+or+it+is+disabled.+Enable+it+by+visiting+https%3A%2F%2Fconsole.developers.google.com%2Fapis%2Fapi%2Fplus.googleapis.com%2Foverview%3Fproject%3D853512518643+then+retry.+If+you+enabled+this+API+recently%2C+wait+a+few+minutes+for+the+action+to+propagate+to+our+systems+and+retry.%22%2C%0A++++%22extendedHelp%22%3A+%22https%3A%2F%2Fconsole.developers.google.com%2Fapis%2Fapi%2Fplus.googleapis.com%2Foverview%3Fproject%3D853512518643%22%0A+++%7D%0A++%5D%2C%0A++%22code%22%3A+403%2C%0A++%22message%22%3A+%22Access+Not+Configured.+Google%2B+API+has+not+been+used+in+project+853512518643+before+or+it+is+disabled.+Enable+it+by+visiting+https%3A%2F%2Fconsole.developers.google.com%2Fapis%2Fapi%2Fplus.googleapis.com%2Foverview%3Fproject%3D853512518643+then+retry.+If+you+enabled+this+API+recently%2C+wait+a+few+minutes+for+the+action+to+propagate+to+our+systems+and+retry.%22%0A+%7D%0A%7D%0A.

I saw your tutor but it does not work with google login ... youtube upload works fine

**Comment by DanielnetoDotCom** [comment]
You may miss something on google auth side
You must enable a couple API's for things to work as expected.
First go to https://console.developers.google.com and make sure under "APIs" that you have the  "Google+ API" enabled. Once that is done you should no longer see that error message.

**Comment by mikweb2017** [comment]
Thanks work fine!
 in your video did not have this information
