### ISSUE TITLE
Live URL is empty

### ISSUE THREAD

**Issue by RisKatOr** [DanielnetoDotCom/YouPHPTube#680]
Hi,

why is live url empty?

![ekran goruntusu_2018-05-13_15-34-47](https://user-images.githubusercontent.com/4102352/39967482-70d7e0ae-56c4-11e8-929a-acba8c1f0757.png)

**Comment by DanielnetoDotCom** [comment]
Sorry about that, I am working in a fix for this

**Comment by RisKatOr** [comment]
Hi,

Fixed, thanks...

![stream](https://user-images.githubusercontent.com/4102352/39994711-bb66f088-5782-11e8-8991-6c7521f1e2cf.jpg)

Streamkey instead username is normal ?

**Comment by DanielnetoDotCom** [comment]
Actually it is your temporary channel name, you can change it on My Account Menu

![image](https://user-images.githubusercontent.com/18009293/39994925-26edb436-5751-11e8-9d86-a4e2f656758f.png)

**Comment by RisKatOr** [comment]
All right, thank you.
