### ISSUE TITLE
Can't play video live streams

### ISSUE THREAD

**Issue by putrantosuryo** [DanielnetoDotCom/YouPHPTube#681]
Why can't play video live streams?
Anyone can help me please?

![capture](https://user-images.githubusercontent.com/33472201/39998016-ecac5ff8-57ae-11e8-9bc0-dc0d8938d483.PNG)

![capture2](https://user-images.githubusercontent.com/33472201/39998116-473955ac-57af-11e8-8ede-071a8e20accb.PNG)

**Comment by DanielnetoDotCom** [comment]
Looks like it is all fine.

Are you using HTTPS somewhere?

**Comment by putrantosuryo** [comment]
no I just use http,

![image](https://user-images.githubusercontent.com/33472201/39999233-c80797d6-57b2-11e8-8318-19c9c6b52c75.png)

**Comment by DanielnetoDotCom** [comment]
can you see your video on VLC with the player URL?

![image](https://user-images.githubusercontent.com/18009293/40001081-c5651278-5763-11e8-993b-6e7eb35e25ce.png)

**Comment by putrantosuryo** [comment]
![image](https://user-images.githubusercontent.com/33472201/40042121-70ca12bc-584a-11e8-9a68-c57ace0fd169.png)
seems not work :( 
are my configuration wrong ? at this 
![image](https://user-images.githubusercontent.com/33472201/40042164-a3b3fcec-584a-11e8-8a03-cb967ef914b1.png)

**Comment by putrantosuryo** [comment]
OMG, sorry but i found that still block port 8888. thanknyou for everthing mr Netto 💃

**Comment by DanielnetoDotCom** [comment]
Wow, great, it works

**Comment by hersche** [comment]
cool, here is feedback and seems to be fine, so i also close this ;)
