### ISSUE TITLE
Add seek button and next button 

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#683]
Hi..
Please add button seek button and next button embeded video link from YouTube

**Comment by hersche** [comment]
enable the seek-button-plugin and the next-button-plugin

**Comment by gujarraju** [comment]
already enabled seek-button-plugin and the next-button-plugin
but not working if i add video link from youtube.

**Comment by gujarraju** [comment]
I upload video direct it will work

**Comment by gujarraju** [comment]
![issue1](https://user-images.githubusercontent.com/35865505/40058369-0193d6b8-5862-11e8-846a-9942749716cb.jpg)

**Comment by gujarraju** [comment]
![issue1](https://user-images.githubusercontent.com/35865505/40058450-3f0147c4-5862-11e8-95d0-d10cdb9e64b3.jpg)

**Comment by hersche** [comment]
@DanielnetoDotCom 
maybe we can use this for youtube-specific videos?
https://github.com/videojs/videojs-youtube

**Comment by hersche** [comment]
i was wrong, here it is. not perfect yet (there are weird js-errors), but it works good. you can also disable it via adancedcustom-stuff..

https://demo.codebea.ch/video/-weird-al-yankovic-amish-paradise

**Comment by gujarraju** [comment]
Thanks working fine....

**Comment by gujarraju** [comment]
But some time error
"No compatible source was found for this media."

**Comment by hersche** [comment]
mh, yes, i was hope, this was gone with the js-exceptions..
problem: the libary seems to be not supported anymore. or making a break.. i've not a idea yet, where it's coming from.

but, if you like to change back for the moment, you can do this with the advancedcustomisation-plugin.

**Comment by gujarraju** [comment]
thanks

**Comment by hersche** [comment]
closed, because it should be solved, but there's no feedback.

**Comment by finesofttest** [comment]
can we change the control buttons position?
I want to place play pause button between seek and next button

**Comment by DanielnetoDotCom** [comment]
I can't tell you that. 

we use the default video.js buttons


but probably you can change/add some code in the plugin and video.js
