### ISSUE TITLE
Encoder generating 404 thumbnails from uploaded videos

### ISSUE THREAD

**Issue by nospi** [DanielnetoDotCom/YouPHPTube#684]
First of all cheers for the brilliant product. Secondly I just realised I posted this on the streamer repo not the encoder - many apologies. Please let me know if I should close and move this thread.

Just to be clear I'm NOT using direct uploads, this is entirely related to uploading to the encoder.

I've found that when using  the encoder to download from YouTube, thumbnails are generating properly. However, whenever a video is uploaded to the encoder, it always results in the 404 Not Found error being generated for the video.

Initially I thought that there was a folder permissions error and that the images were not being created for each video. Upon closer inspection I can see that each video has indeed had an image generated for it, though that image is the actual 404 image.

I'm guessing that this is coming from ffmpeg? Or is it passing a call to youtube-dl even for videos that are uploaded?

Here's a copy of the image being generated:

![image](https://user-images.githubusercontent.com/19985451/40033362-7273cdce-583b-11e8-8534-583a01fa6cbc.png)

I'm still looking to find where these are generated so apologies if i'm missing something simple. I can't seem to find anyone else having this exact issue with the encoder. 

> The encoder Max File Size is: 2.93GB 
> The Streamer Max File Size is: 2.93GB 
> The Streamer Max Video Storage Limit is: Unlimited 
> The Streamer Current Video Storage is: 28.30 Minutes

This is occurring with all file sizes, which are well under those limits. And with mp3's which is obviously to be expected.

**Comment by hersche** [comment]
this is not a bug, this is a commercial plugin, i think (the preview-picture make it a little unclear, but i think it's also valid for upload via encoder): MP4ThumbsAndGif @ https://easytube.club

but @DanielnetoDotCom , can you confirm this works also for uploaded via encoder?

**Comment by nospi** [comment]
I believe that plugin is _only_ for automatically extracting from direct uploads. The encoder is supposed to perform this function automatically. It is performing it at some stage, otherwise the images wouldn't have been generated in the videos directory.

I was under the assumption that this function wasn't being executed, and that when an img src was missing, a 404 replaced it. This is not the case though - each video does indeed have a respecitive image file, however that image file itself is the 404 image posted above.

Whatever process is attempting to get the thumbs from the video file (ffmpeg?) is having some issue there and resorting to the 404 image.

Quite probably a PHP module or setting I don't have.

**Comment by nospi** [comment]
My apologies, this should be on the encoder issue tracker.

Found the function:

`static function getImage($pathFileName, $seconds = 5) {`
`        ...`
`        eval('$ffmpeg ="ffmpeg -i {$pathFileName} -ss {$duration} -vframes 1 -y {$destinationFile}";');`
`        exec($ffmpeg . " < /dev/null 2>&1", $output, $return_val);`
`        if ($return_val !== 0) {`
`            return $global['systemRootPath'] . "view/img/notfound.jpg";`
`        } else {`
`            return $destinationFile;`
`        }`

The issue is this part here:

>  exec($ffmpeg . " **<** /dev/null 2>&1", $output, $return_val);

Should be:

>  exec($ffmpeg . " **>** /dev/null 2>&1", $output, $return_val);

I think the **<** should be **>**. I've got slow internet so once I test an upload I'll update this.

**Comment by hersche** [comment]
just rechecked it, you're right with the plugin, it's not needed. my wrong.

that's great when it works, i just tried and it generate me the pictures (can not reproduce it), but maybe that would be nice as a pull-request instead of a issue on youphptube-encoder? :)

**Comment by nospi** [comment]
I've found a few little ones like that here and there so once I've gotten
them together I'll submit a pull request.

Is it worth putting these changes in a branch?

**Comment by hersche** [comment]
when you find some of them, it sounds to me, like it is worth to make a fork. there, it's unimportant, if you are on the master-branch or create a new.

but it's definently worth to commit them. you can also edit in github directly, but then you do a PR for every file automatic (as well as one fork and there a branch for every PR).

**Comment by nospi** [comment]
I really should have forked it to be honest.

I'm interested in adding image support as well, but think this might be
more usable to the community as a plugin. I haven't really looked at the
plugin system yet; do you think it will be able to achieve what I'm
thinking?

Basically I'd like to be able to upload (directly or via the encoder) high
res images and view them in place of the video player. Similar to flickr or
deviantart.

I'm happy to start poking about in source code but a plug-in would be ideal.

**Comment by hersche** [comment]
nope, you have 0 repos yet :) just click on the "Fork"-button..

to be honest, i cant really imagine how to place it.

the plugin-structure allows a lot, and i think you would be able doing a plugin for another startpage or adding a link to new site (picture-gallery for example) easily. also entrys to admin-menus are partialy possible.

on the other hand, there's a lot of infos about the type, in category and on media, but only for audio/video.. why not add picture/image there (in the core)?

or just modify a plugin like youphpflix..

that decision is up to you :)

**Comment by nospi** [comment]
Yeah sorry I mean forking it would have been a better decision earlier on.

Cheers for the tips, I'll have a look at some other plugins and see what's
possible.

**Comment by mcuix** [comment]
How do I replace the 404 thumbnails which have already been generated by the Encoder?

**Comment by DanielnetoDotCom** [comment]
Edit it on the videos manager (streamer site)

**Comment by BartManX** [comment]
I have this problem too

**Comment by DanielnetoDotCom** [comment]
@BartManX you have to provide some details,

make sure you have the latest version and provide us your log file at the moment the error occurs
