### ISSUE TITLE
How to translate labels from the JS file ?

### ISSUE THREAD

**Issue by RisKatOr** [DanielnetoDotCom/YouPHPTube#685]
Hi,

I want to translate labels from [bootgrid.js](https://github.com/DanielnetoDotCom/YouPHPTube/blob/bffed8708859d0b51e882dc2545a886324544c0c/view/js/bootgrid/jquery.bootgrid.js) how can i do this ?

> labels: {
            all: "**All**",
            infos: "**Showing {{ctx.start}} to {{ctx.end}} of {{ctx.total}} entries**",
            loading: "**Loading...**",
            noResults: "**No results found!**",
            refresh: "**Refresh**",
            search: "**Search**"
        },
>

with `<?php echo __('No results found!'); ?>` it does not work.

**Comment by DanielnetoDotCom** [comment]
Sorry about that I am not sure yet. maybe we need to find a solution on google.

**Comment by hersche** [comment]
yeah, i was also think about this.. maybe a solution would be to handle it like bootgrid.js.php, so the php gets intepreted.. that would need a change in including and maybe also in the way to combine files (the combined file should also end with .php for example).

also updating those, external, libs would getting much more difficult and it could cause (new) bugs, when we make a fault, which would be tested already by the lib-creators.

specialized for bootgrid, there are methods from bootgrid to update the labels (search, no results found, etc) with individual text. when this methods from bootgrid itself are used for translation, it would be the absolut best solution.

**Comment by hersche** [comment]
solved @ #700

**Comment by RisKatOr** [comment]
Really, you are the King. then we will wait for the merged, thank you very much.

**Comment by hersche** [comment]
thanks.. if you like to translate to your languages, examples are here:
https://github.com/hersche/YouPHPTube/blob/unstable/view/managerUsers.php#L148
also, i just did the translation of data-tables in chart.. example:
https://github.com/hersche/YouPHPTube/blob/unstable/view/report2.php#L53
