### ISSUE TITLE
Add To and Share

### ISSUE THREAD

**Issue by afnieves** [DanielnetoDotCom/YouPHPTube#690]
Is there any way to disable the add to and share buttons on each video?  I purchased the ShareSocialButtonsOnEmbed (ShareSocial plugin bu that does not seem to do this.

**Comment by hersche** [comment]
i added it to the CustomizeAdvanced-plugin-settings.. so after the next PR (in a day or two), you should be able to disable them.

**Comment by hersche** [comment]
since it's merged, it should be possible for you do disable those buttons. can you confirm it works?

**Comment by hersche** [comment]
like i said, it is there since about 17 days, but withouth a answer, i close it because of inactivity.
