### ISSUE TITLE
Has anyone got YouPHPTube and YouPHPTube-Encoder to run on Nginx?

### ISSUE THREAD

**Issue by afnieves** [DanielnetoDotCom/YouPHPTube#691]
I get stuck on the AllowOverride None to AllowOverride All but this does not apply to Nginx?

**Comment by DanielnetoDotCom** [comment]
AllowOverride is an apache parameter.

there are some Nginx help on the issues here, try to search it.

**Comment by patriclougheed** [comment]
I have the encoder and streaming site working together with nginx. Attached is my conf for the encoder.
[encoder.txt](https://github.com/DanielnetoDotCom/YouPHPTube/files/2021126/encoder.txt)

**Comment by DanielnetoDotCom** [comment]
Thanks @patriclougheed

**Comment by afnieves** [comment]
Thanks can you share the streamer conf?

**Comment by patriclougheed** [comment]
Sure... I have worked out most issues but a few plugins are giving me 500 errors. Will be upgrading this further once I get around to compiling nginx with mp4 and rtmp support.

[streamer.txt](https://github.com/DanielnetoDotCom/YouPHPTube/files/2028789/streamer.txt)

**Comment by afnieves** [comment]
Thanks again!

**Comment by patriclougheed** [comment]
Small update... I solved the 500 errors I received from some of the plugins by removing the plugin rewrite:

location /plugin {
 rewrite ^/plugin/([A-Za-z0-9-_.]+)/(.*)?$ /plugin/$1/$2;
}

NginX handles this internally just fine.

**Comment by DanielnetoDotCom** [comment]
That is great :)

**Comment by hersche** [comment]
the php-router is in the official branch for a while. also, i have documented the nginx-setup here:

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Admin-manual

in the install-section. if someone like to test the router with nginx, that still would be great, but there is another solution anyway now. reopen if you feel it's needed.

**Comment by fa305757** [comment]
I tried to follow the instructions to use a storage other than the default one by moving the videos folder out of the / var / www / html / AVideo folder and replacing a symbolic link pointing to the videos folder but the graphic layout is unreadable with problems by css
