### ISSUE TITLE
not issu but question

### ISSUE THREAD

**Issue by KazeroG** [DanielnetoDotCom/YouPHPTube#695]
Hello mate thanks for you hard work.

i juste want to know can you list all stuff avalaible i mean what is free and what isn't ? im little bit confused ...

thanks again.

**Comment by KazeroG** [comment]
for stream channel need to pay ? 

nice work but do you found more affordable to people if you merge some plugin like subtitle switcher and resolution switcher ?

**Comment by DanielnetoDotCom** [comment]
You don't have to pay to stream.
you can have as many as stream channels as you want.

**Comment by stevenj** [comment]
So, is it correct, if I want soft subtitles I need the paid subtitle plugin?

**Comment by DanielnetoDotCom** [comment]
Yes , subtitle plugin is paid

**Comment by hersche** [comment]
i made a small section about paid plugins exist in the wiki..
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Admin-manual

also i think, the question is answered. reopen if not.
