### ISSUE TITLE
User video watching tracking

### ISSUE THREAD

**Issue by afnieves** [DanielnetoDotCom/YouPHPTube#696]
Is there a way to track how much of each video a user watched? 

For example on video XYZ User 1 and User 2 watched 100% User 3 and 4 only watched 30 seconds of it.

**Comment by hersche** [comment]
@afnieves i have made a plugin for this, it is not finished yet, but it collects already data :)

it is based on track seconds, but out of this i can calculate percents..

e-mail me at vinzenz.hersche@gmail.com if you are still interessted in this feature.
