### ISSUE TITLE
Allow MySQL connection in non default port

### ISSUE THREAD

**Issue by tiagostutz** [DanielnetoDotCom/YouPHPTube#70]
I'm trying to configure YouPHPTube on my environment which is shared among a lot of folks, and each one has his own port range, so I cannot run MySQL at default 3306 port. 
It would be useful to have one more parameter in the install page for us to specify the MySQL port. This field would come with the default value (3306)

**Comment by tiagostutz** [comment]
Working on this feature right now.

**Comment by tiagostutz** [comment]
Will be fixed by #69

**Comment by DanielnetoDotCom** [comment]
Thanks :)
