### ISSUE TITLE
Php mailer 

### ISSUE THREAD

**Issue by Nisarg22** [DanielnetoDotCom/YouPHPTube#701]
Whenever I try to test my email It always shows
![screenshot_20180518-110218](https://user-images.githubusercontent.com/39002772/40217624-5ac737f4-5a8b-11e8-9e05-8aaaa938e74b.jpg)
![screenshot_20180518-110335](https://user-images.githubusercontent.com/39002772/40217636-669f5fc0-5a8b-11e8-9191-62dc43bf2fc0.jpg)

**Comment by RisKatOr** [comment]
Hi,

[https://myaccount.google.com/lesssecureapps](https://myaccount.google.com/lesssecureapps)

Make sure you turn it on

**Comment by DanielnetoDotCom** [comment]
same error again?

get a screen shot of your configurations

**Comment by Nisarg22** [comment]
![opera snapshot_2018-06-06_080553_nisargpathak36 000webhostapp com](https://user-images.githubusercontent.com/39002772/41012716-9d616862-6960-11e8-96f7-a0c37760cce2.png)

**Comment by DanielnetoDotCom** [comment]
I mean this screenshot

![image](https://user-images.githubusercontent.com/18009293/41042194-63c7d43a-6977-11e8-8aab-36420409f07a.png)

**Comment by Nisarg22** [comment]
![screenshot_20180607-003824](https://user-images.githubusercontent.com/39002772/41059768-222ceb36-69eb-11e8-84d6-71b6c2e64c77.jpg)

**Comment by DanielnetoDotCom** [comment]
instead ssl use tls and port 587

![image](https://user-images.githubusercontent.com/18009293/41060076-d45f12a8-69a4-11e8-929e-ab3b1de91ac3.png)

**Comment by hersche** [comment]
@Nisarg22 does it work with @DanielnetoDotCom 's hint?

**Comment by hersche** [comment]
no response, i assume this is done, so i close it.
