### ISSUE TITLE
live not working

### ISSUE THREAD

**Issue by goldeniws** [DanielnetoDotCom/YouPHPTube#702]
![screenshot_2](https://user-images.githubusercontent.com/21250274/40250144-a84dd470-5ad5-11e8-8fb0-46517c877f57.png)
![screenshot_3](https://user-images.githubusercontent.com/21250274/40250145-a87f22aa-5ad5-11e8-8b58-b95dd68bda0f.png)
![screenshot_4](https://user-images.githubusercontent.com/21250274/40250196-d97f70ee-5ad5-11e8-9ab4-258155ac1371.png)
![screenshot_5](https://user-images.githubusercontent.com/21250274/40250197-d9aeb71e-5ad5-11e8-876c-c757683fda99.png)
![screenshot_6](https://user-images.githubusercontent.com/21250274/40250253-06a4305a-5ad6-11e8-8a9e-020a353394fc.png)
![screenshot_7](https://user-images.githubusercontent.com/21250274/40250314-33fb394a-5ad6-11e8-8981-f11a559a4d0c.png)

**Comment by goldeniws** [comment]
![screenshot_8](https://user-images.githubusercontent.com/21250274/40250381-5fbb2c34-5ad6-11e8-92a8-1c2bdc60cc39.png)

**Comment by DanielnetoDotCom** [comment]
How is your /usr/local/nginx/conf/**nginx.conf** file?

make sure those are accessible using http NOT https

```
on_publish http://localhost/YouPHPTube/plugin/Live/on_publish.php;
on_play http://localhost/YouPHPTube/plugin/Live/on_play.php;
on_record_done http://localhost/YouPHPTube/plugin/Live/on_record_done.php;
```

**Comment by goldeniws** [comment]
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}

**Comment by DanielnetoDotCom** [comment]
I can't see your hls configuration on your nginx conf

**Comment by goldeniws** [comment]
can you help me sir i use plesk i want use nginx rtmp without problem in plesk panel

**Comment by goldeniws** [comment]
call me prive i can give you access root
call me with email : goldeniws@gmail.com

**Comment by DanielnetoDotCom** [comment]
You can hire me to install it for you on https://www.youphptube.com/services

Also plesk or any kind of controll panel is not recommended

**Comment by DanielnetoDotCom** [comment]
Important Information

Streamer can be installed on any Server, including Windows, but the encoder and Livestream should work fine on any Linux distribution. However we recommend Ubuntu 16 or 17 without any kind of control panel. The problem with cPanel, Plesk, Webmin, VestaCP, etc. It's because we need full root access to install some libs, and maybe compile them. Another important point is that to make Livestream work, we need to compile Nginx and the control panels often prevent us from running the commands forcing the installation available only on your panel.

**Comment by goldeniws** [comment]
i have 2 vps ( vps (plesk) , vps (icecast) )

**Comment by DanielnetoDotCom** [comment]
Will be a regular installation, you will just need to change the parameters on the plugins and site  configurations

**Comment by goldeniws** [comment]
/usr/local/nginx/conf/nginx.conf file

#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}


error_log  logs/error.log debug;
    
    events {
        worker_connections  1024;
    }
    http {
        include       mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;
        server {
            listen       8080;
            server_name  localhost;
            # sample handlers
            #location /on_play {
            #    if ($arg_pageUrl ~* localhost) {
            #        return 201;
            #    }
            #    return 202;
            #}
            #location /on_publish {
            #    return 201;
            #}
            #location /vod {
            #    alias /var/myvideos;
            #}
            # rtmp stat
            location /stat {
                rtmp_stat all;
                rtmp_stat_stylesheet stat.xsl;
            }
            location /stat.xsl {
                # you can move stat.xsl to a different location
                root /usr/build/nginx-rtmp-module;
            }
            # rtmp control
            location /control {
                rtmp_control all;
            }
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   html;
            }
        }
    }
    rtmp {
        server {
            listen 1935;
            ping 30s;
            notify_method get;
            application myapp {
                live on;
                # sample play/publish handlers
                #on_play http://localhost:8080/on_play;
                #on_publish http://localhost:8080/on_publish;
                # sample recorder
                #recorder rec1 {
                #    record all;
                #    record_interval 30s;
                #    record_path /tmp;
                #    record_unique on;
                #}
                # sample HLS
                #hls on;
                #hls_path /tmp/hls;
                #hls_sync 100ms;
            }
            # Video on demand
            #application vod {
            #    play /var/Videos;
            #}
            # Video on demand over HTTP
            #application vod_http {
            #    play http://localhost:8080/vod/;
            #}
        }
    }

**Comment by DanielnetoDotCom** [comment]
Try this https://tutorials.youphptube.com/cat/default/video/10-min-youphptube-stream-server-installation

**Comment by goldeniws** [comment]
vps (1)
website : http://showtuber.giws.pw
ip : 54.37.155.128

vps (2)
nginx rtmp : 54.38.242.71

**Comment by DanielnetoDotCom** [comment]
fell free to hire us on https://www.youphptube.com/services

Or try to follow the tutorial

**Comment by DanielnetoDotCom** [comment]
I just fix a very similar problem on a costumer.

the problem was because he added a redirect rule on .htaccess, so he redirects everything to his www URL.

After removing the redirect rule it starts to work perfectly
