### ISSUE TITLE
newUsersCanStream issue

### ISSUE THREAD

**Issue by RisKatOr** [DanielnetoDotCom/YouPHPTube#703]
Hi,

newUsersCanStream disabled (not selected) but new user can broadcast live stream.

How can I prevent the new member from being able to broadcast live?

(Sorry for my -Google Translate- English)

**Comment by DanielnetoDotCom** [comment]
Hi, it now suppose to happened.

please check your user manager and see if the user has the switch button activated

![image](https://user-images.githubusercontent.com/18009293/40324361-ab922650-5d0e-11e8-95de-69c17572e6c6.png)

**Comment by RisKatOr** [comment]
Hi,

Solved, thank you...
