### ISSUE TITLE
Some mvideos issues

### ISSUE THREAD

**Issue by RisKatOr** [DanielnetoDotCom/YouPHPTube#704]
![adsiz](https://user-images.githubusercontent.com/4102352/40302697-a88b0dd4-5cf8-11e8-974a-76301e06b18f.jpg)

**Comment by hersche** [comment]
the point with the star at least is solved in the PR #700

**Comment by RisKatOr** [comment]
Very well, then we will wait for the merger, thank you very much.

**Comment by hersche** [comment]
mmh, better reopen it, i only speak about the right part, the missing symbol beside the eye (which is a star)..

the unicode-problem on the left site is maybe still there (i did not see it yet).

**Comment by DanielnetoDotCom** [comment]
I have send a fix for the star, also chek the CustomizeAdvanced plugin tor UTF8 options 
 Make sure you select only one of them, Encode or Decode option.

![image](https://user-images.githubusercontent.com/18009293/40324620-70522e86-5d0f-11e8-9a38-7d441888da70.png)

**Comment by RisKatOr** [comment]
Hi,

Thank you very much, same problem when selected Encode or Decode but when i uncheck Encode and Decode problem solved.
