### ISSUE TITLE
Clear Cache Directory issue

### ISSUE THREAD

**Issue by RisKatOr** [DanielnetoDotCom/YouPHPTube#707]
Hi,

Site Configurations -> Advanced Configuration -> Clear Cache Directory

When I click on the Clear Cache Directory button, it remains on the Processing screen, the cache directory can not be cleared after latest update. The error log is as follows.

> #0 /var/www/html/objects/configuration.php(46): Configuration->load()
#1 /var/www/html/objects/include_config.php(18): Configuration->__construct()
#2 /var/www/html/videos/configuration.php(17): require_once('/var/www/html/o...')
#3 /var/www/html/objects/user.php(5): require_once('/var/www/html/v...')
#4 /var/www/html/objects/configurationClearCache.json.php(22): require_once('/var/www/html/o...')
#5 {main}
  thrown in /var/www/html/objects/configuration.php on line 56
[22-May-2018 12:12:11 Europe/Moscow] PHP Fatal error:  Uncaught Error: Class 'sqlDAL' not found in /var/www/html/objects/configuration.php:56
Stack trace:
#0 /var/www/html/objects/configuration.php(46): Configuration->load()
#1 /var/www/html/objects/include_config.php(18): Configuration->__construct()
#2 /var/www/html/videos/configuration.php(17): require_once('/var/www/html/o...')
#3 /var/www/html/objects/user.php(5): require_once('/var/www/html/v...')
#4 /var/www/html/objects/configurationClearCache.json.php(22): require_once('/var/www/html/o...')
#5 {main}
  thrown in /var/www/html/objects/configuration.php on line 56
[22-May-2018 12:19:06 Europe/Moscow] PHP Fatal error:  Uncaught Error: Class 'sqlDAL' not found in /var/www/html/objects/configuration.php:56
Stack trace:
#0 /var/www/html/objects/configuration.php(46): Configuration->load()
#1 /var/www/html/objects/include_config.php(18): Configuration->__construct()
#2 /var/www/html/videos/configuration.php(17): require_once('/var/www/html/o...')
#3 /var/www/html/objects/user.php(5): require_once('/var/www/html/v...')
#4 /var/www/html/objects/configurationClearCache.json.php(22): require_once('/var/www/html/o...')
#5 {main}
  thrown in /var/www/html/objects/configuration.php on line 56

**Comment by DanielnetoDotCom** [comment]
For some reason I could not reproduce it, and it works fine here

**Comment by RisKatOr** [comment]
Hi,

Solved after update ( Updating 5328d82..835eb0c ) Thanks.
