### ISSUE TITLE
Thumbnail and RSS feed

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#71]
-  It would be great if you could chose, upload personal  Thumbnail for video.
- Could you  enable RSS feed?

**I love this project**

**Comment by DanielnetoDotCom** [comment]
Thank you :) we are happy you like it.

**Comment by DanielnetoDotCom** [comment]
> It would be great if you could chose, upload personal Thumbnail for video.
I am thinking about it, I want to do that I just didnt have time yet
> Could you enable RSS feed?
Maybe in future release

**Comment by DanielnetoDotCom** [comment]
About the thumbnail the newest version already support it
