### ISSUE TITLE
A Few Questions

### ISSUE THREAD

**Issue by drtokegyi** [DanielnetoDotCom/YouPHPTube#716]
1) Possible to make front theme design 4/5 rows Gallery style instead of 6 rows? It is too small to look in 6 rows. Front design similar to plugins store page? https://i.imgur.com/hBkhnQY.jpg
Or where can I buy custom theme for YouPHPTube?

2) Possible to use multi storage servers and stream videos in main site?

For example;
example.com (main site)
encoder.example.com (encoder)
storage1.example.com, storage2.example.com, etc... (store encoded videos files and stream in main site)

Videos uploaded to encoder and sent encoded videos to storage servers (storage1.example.com or storage2.example.com).

And then, video streaming from storage server serve to main site (example.com).

Thanks

**Comment by DanielnetoDotCom** [comment]
Hi

I think you mean 4 or 5 cols instead "rows".

For now the default theme does not support it. But yes, you can hire us to customize it at developer@youphptube.com

about the servers Yes, you can have 
example.com (main site)
encoder.example.com (encoder)

but to store file for now we support only S3 servers (Amazon for example) and it will work similar as you describe.
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Use-AWS-S3-on-YouPHPTube

**Comment by drtokegyi** [comment]
S3 server costs too much. I would like to use dedicated server for storage.
Maybe FTP server fine.

Do you have a plan to do this?

**Comment by DanielnetoDotCom** [comment]
S3 is cheaper the host your files on a dedicated server

**Comment by drtokegyi** [comment]
I don't think so. They also charge for bandwidth. As it is video streaming, bandwidth usage will be a lot and it will cost over $1000 per month.

So you do not have a plan to do for multi server?

**Comment by DanielnetoDotCom** [comment]
No I dont, sorry

**Comment by hersche** [comment]
hey @drtokegyi 

since a while, there is a new video-type called linkVideo. i don't think, ftp will be possible for this, but http or https should work (just don't mix http(s)).

you can find a usage here, under add video:

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/User-manual

hope, this solves your problem as well.

**Comment by hersche** [comment]
questions seems answered, so i close it.
