### ISSUE TITLE
problematic isAdmin=0

### ISSUE THREAD

**Issue by fheuer** [DanielnetoDotCom/YouPHPTube#717]
When editing user details in the user form it is a bit problematic that the admin user defaults to isAdmin=0. This is causing a circumstance of editing user details in the database.

It is not really an issue but rather a feature request. :)

**Comment by DanielnetoDotCom** [comment]
Hi @fheuer 

What are you saying is that isAdmin default should be 1?

**Comment by DanielnetoDotCom** [comment]
Thanks for notice, it is fixed

**Comment by fheuer** [comment]
Great, i'll try it ASAP and close

**Comment by fheuer** [comment]
@DanielnetoDotCom the fix works! Bet the same comparator is troublesome for the other two toggles which are using integers. I am not a php Dev but I guess this is the reason. 

source: https://secure.php.net/manual/en/language.operators.comparison.php
