### ISSUE TITLE
Problem with .htaccess

### ISSUE THREAD

**Issue by Gustavo131997** [DanielnetoDotCom/YouPHPTube#719]
Toma el .htaccess de la pagina principal, pero muestra  la pagina principal en blanco, busque una pagina para probar el .htaccess (https://htaccess.madewithlove.be?share=2e9eaa14-b4bb-5288-a5df-43cca78b5d50) y me tira muchos errores RewriteRules, es la pagina entre parentesis.

**Comment by hersche** [comment]
> errores RewriteRules

can you write in english? if you have errors with the rewrite-rules, did you do
`
sudo a2enmod rewrite`

like in https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x-For-YouPHPTube-version-4.x-or-newer

?

**Comment by hersche** [comment]
no clue what's going on there, need feedback, i close it because of inactivity..
