### ISSUE TITLE
encoding of large mkv/mp4 fails

### ISSUE THREAD

**Issue by Ceelight** [DanielnetoDotCom/YouPHPTube#720]
Hi!

I have youphptube and youphptube-encoder installed on Debian. Both are up and running. I want to upload a quite large video file >5GB. I have set the upload size to 6GB in php.ini.

It fails with mkv , mp4 and mp3 (extracted audio). Please find attached the youphptube.log, encoder.log and current php.ini.
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2039851/youphptube.log)
[encoder.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2039852/encoder.log)
[php.ini.txt](https://github.com/DanielnetoDotCom/YouPHPTube/files/2039858/php.ini.txt)

Could you please have a look? Do you find something strange happening? Any idea what the problem could be? Any more info needed? Thanks!

`$ free -h
             total       used       free     shared    buffers     cached
Mem:          1.5G       682M       831M        65M        67M       371M
-/+ buffers/cache:       244M       1.2G
Swap:         3.0G        51M       2.9G
`

`$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Core(TM)2 CPU         T5600  @ 1.83GHz
stepping	: 6
microcode	: 0x48
cpu MHz		: 1000.000
cache size	: 2048 KB
fdiv_bug	: no
f00f_bug	: no
coma_bug	: no
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx lm constant_tsc arch_perfmon pebs bts aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm lahf_lm dtherm tpr_shadow
bogomips	: 3657.42
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
`

**Comment by DanielnetoDotCom** [comment]
The issues I have seen encoding/uploading large files is the folowing

You will need double memory RAM as your file size.

For example, if you want to upload a 6GB File, you will need to have a 12GB RAM to be able to process, less then that you will get a memory leak "Allowed memory size of # bytes exhausted"
