### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#721]
Hi Daniel,

Please check this link and try to make smiler android app
https://play.google.com/store/apps/details?id=com.streamhash.streamtube

**Comment by DanielnetoDotCom** [comment]
Hi, thanks for share this 

we also have an app https://play.google.com/store/apps/details?id=mobile.youphptube.com

but what do you mean "make smiler android app"

**Comment by hersche** [comment]
maybe similiar?

**Comment by gujarraju** [comment]
Not simler next video not showing only one video and also need description minimize

**Comment by DanielnetoDotCom** [comment]
@gujarraju please give more details

**Comment by gujarraju** [comment]
![img1528389165427](https://user-images.githubusercontent.com/35865505/41113326-61a3efd8-6a92-11e8-8bd1-eb75539a5b1e.jpg)



Please check booth screen

**Comment by gujarraju** [comment]
first youphptube and second other player
