### ISSUE TITLE
compatible with Twitch ?

### ISSUE THREAD

**Issue by KazeroG** [DanielnetoDotCom/YouPHPTube#722]
i juste want to know if the script is compatible with twitch **with some little and simple modifications** of the API setting etc... 

**thanks** 

_if yes do want to work with me i have a big project for who already in run ..._

**Comment by DanielnetoDotCom** [comment]
Do you mean the live or the embed?

embed suppose to work, you can try it on demo site.

**Comment by KazeroG** [comment]
yep ! embed and live why not at same  

and i want it to show the streaming only when on LIVE !

**Comment by bgmeet** [comment]
I love to get twitch live working too :)

**Comment by DanielnetoDotCom** [comment]
You should be able to embed twitch links
