### ISSUE TITLE
A new request ... if possible a new plug ...

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#724]
Many like me ... use a control panel to have multiple domains on the same server ... Twice a week I set up a backup function that creates files for all sensitive information. The problem is that this mine site that has at the base YouPHPTube,  has already hosted 4867 minutes of movies ... that creates me backup file difficult to move and store, like 140GB data ... (there would not be a problem if maybe subdiviso in more smaller archives ... but the control panel does not know how to do it and manage them ... so a single file that has more to grow over time and very difficult to manage and very easy to corrupt while it is copied.

I wanted to ask if this plug ... "AWS S3"  (or maybe another one)  can also manage private NAS ... like FreeNAS / NAS4Free for video / audio ... It would be much easier to keep them in NAS and when i do a server restore, all the videos there I'm already safe with RAID-like technologies ...
 
Then if you could tell me when the "Unlisted video" system will be implemented.

Thanks again.

**Comment by tgd1973** [comment]
Thank you for the realization of the "unlisted video" function.

If you can also tell me about the possibility of using a NAS system for the vodeos folder ... maybe with the help of a completion of a similar plugin to AWS_S3 ... it would be wonderful ... because I can climb to "infinity",  with a NAS server, by adding the HDD to RAID as they are filled with video/audio ...

A big thanks.

**Comment by hersche** [comment]
i can think about a solution using a modified encoder, that only sends a link of the stored video, so the video is in streamer, but stored on the encoder's site.

if you are interessted in this, i would like to do so as a paid job. but on the other hand, that would be cool to be open source (i would welcome those changes in the official core).

you (or other interessted) can email me at vinzenz.hersche@gmail.com for further info, if it's paid by more than one person, i would make it transparent on request. also, you can ask daniel here: https://www.youphptube.com/services (we are in contact, so doesn't matter much).

**Comment by tgd1973** [comment]
Thanks for the idea of ​​changing the encoder.
My problem, but maybe also many others,  is that they can not have 2 public IPs of home conection, one for the server and another for the encoder ... Personally in my server I have loaded in the same directory "public_html" the files of the "streamer" and also of the "encoder" and at the same time in  the same server also the NgiNx-Rtmp for live streaming. 
Having everything on the same server would not make sense to move the video files from the streamer to the encoder folder,  because the control panel of the server makes equal the backup of all files on the server, and then assuming that it happens unexpectedly and the server goes down ... I can not recover the videos if I do not backup before ... so I always get the same problem as before, ... ideas to have an NFS RAID, separate from the server ...

My idea was to use another FreeNAS server (for example) NAS/NFS: 
https://www.backblaze.com/blog/backblaze-storage-pod-4/
connected to the server via a 10GB fiber connection that creates another NFS virtual directory in the server (similar with HLS/live for livestraming) , then the encoder by uploading video to this NFS virtual directory, will be  the server NFS software to take care of moving everything on the NAS. The "encoder" should load in the "streamer" however the gif of the video (it does not take up much space) but also the symlinks with the exact address where the "streamer" can read the video files from the NAS.
So it would be a good idea that from the conf of the "encoder" can specify if can use the NAS-NFS system ... so that one can configure it if it needs, if not ... leave it default disactivated.
Must also see the plugin recorder if it can work in this system.

What interests me is to modify the file: "encoder> objects> Encoder.php" so that it can create the symlink in streamer but to be able to load it elsewhere in a virtual directory NFS on the server, where, the NFS software, of the server , will do everything, of course, leave the part of the loading of the other files (gif, jpg, thumbs.jpg) intact that the encoder currently does them. It should not be very difficult but not being a professional programmer I prefer to leave this committee to those who do it, of job ...

**Comment by hersche** [comment]
i only overflow it (i will readwrite more clear later)

- NFS: thats a idea, but users will use shell-access to be able to use NFS.
   - sshfs: when we have a shell anyway, ssh would be better
   - ftp: better compatibility to all hosts

then, the thing with only one public ip: that's good to know for me, but not drastic in my solution.

- you can have nginx in the front and decide yourself, which domain is going to which internal server
- or you would be able to use port-forwarding to various machines.

with the NFS-solution, the streamer would serve all data and stream it via NFS from the encoder/storage internal - do i get that right?

**Comment by tgd1973** [comment]
To make more clarity for the server I have as control panel Vestacp which in itself has Apache server on 8080 with Nginx as a proxy server from 8080 to 80 ... then there is the second nginx-rtmp which is on 445 ...
For now everything seems to be fine ... apart from the backups that are already "astronomical" due to videos in YouPHPTube . 

The part with Nginx as proxy works up to the point in which one has to go from one SSL certified site to another SSL site ... (from the streamer to the encoder).

**Comment by hersche** [comment]
I think instead of using ports only, you can also use internal ip's in nginx to distribute to the diffrent servers in background, so nginx bundle all. For making the diffrent of services public, you can use diffrent (sub)domains for diffrent services then.

**Comment by tgd1973** [comment]
ok but in this case the servers behind the proxy do not have to use ssl ... I have already tried to proxate another server from ESXi through the server with NGINX but if the internal server has its https (ssl) the proxy does not baypasse correctly the connection because even the primary server has its own SSL ...

**Comment by hersche** [comment]
When your tests work and you agree with the solution, the encoder would send a usual link to the mp4-file (but with a stranger domain). On the streamer, this can be done with small changes that also would allow federating videos like in diaspora, but thats a complete other topic then (i go offtopic)

For a price, i would like to have a talk with daniel also and may do this via email then..

**Comment by hersche** [comment]
i am underway, so my answers are a bit limited atm.

> to not create Lag in the loading of pages I would like to pass only the videos in NFS

yeah, but the streamer has all the php-files on its own, get / download the videos via NFS and serve / upload them in streamer to the user.

with a "link-solution", it's only downloaded once, direct from the nas to the user, while php is server by the streamer itself.

but for this, nginx has to work this way. i have to extend the nginx-part a bit, so it's maybe more clear what i mean, but have to move again now ;)

btw, email is vinzenz.hersche@gmail.com

**Comment by hersche** [comment]
so, for the nginx-config, i would recommend this part:

https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

forwarding all the header-info can be tricky, but necessary (i'm not shure how). this is the internal LAN-part i mean.

http://nginx.org/en/docs/http/server_names.html

is for make diffrent url's go to the diffrent proxys.

Some people made nginx-configs avaible, for using it instead of apache.. maybe this can help you also, but it's a diffrent use case.

**Comment by tgd1973** [comment]
Tested and for what concerns the proxy part it works to bypass the "encoder" on the output of a subdomain of the "streamer" domain with the public ip . Only problem I found is that even if the primary connection from the subdomain of output with public ip (with the proxy) has SSL ... when I enter to the encoder from the outside gives me an error: "the connection from this site is not completely protected " 
 and I think this is because the internal part can not be covered by https (SSL) and the browser notices it in some way.

If you can tell me how to done, in somehow to hide  what's behind the proxy ... it would be a great thing.

Now the part with the video storage in the encoder remains to be solved.

Thanks again.

**Comment by hersche** [comment]
you can let nginx do ssl:
http://nginx.org/en/docs/http/configuring_https_servers.html

when your home-network is only used by you, i would do the internal maybe unencrypted.

so, for the public address, we have ssl that's handled by nginx. then proxify to http:// / port 80.

it should also be possible to do internal with ssl, but it's a while ago since my last nginx-use.

>  the nginx-rtmp part must stay in the "encoder"

for a first, why not. later, you can also took a 3. server only for rtmp :)

**Comment by tgd1973** [comment]
Maybe I have not explained well ... the inside is without SSL ... but the browsers that are from the outside, through proxy  realize that the inside is not encrypted ... and the certificate did not mark more green  (Let's Encrypt can not be done on an internal IP)  ... then for now that I have then more than 20 - 30 people watching the Live .... there are no problems but I think that in the future can not stay in that way ... through the proxy ... If it goes down the primary server with the proxy is down my entire network ... I prefer to make the system with NFS that is less complex ... if it does not synchronize with the NFS no longer online just a one site (YouPHPTube)

**Comment by hersche** [comment]
> Let's Encrypt can not be done on an internal IP on the second server "encoder" being internal without domain

it should have the ip of the proxy and should be handled by the proxy completly.

> If it goes down the primary server with the proxy is down my entire network

that's true, in a server-farm you would do that redundant to be shure it always works.

> I prefer to make the system with NFS that is less complex ... if it does not synchronize with the NFS no longer online just a one site (YouPHPTube)

i don't know NFS very well, but when you say SYNCHRONIZE, then i think to this like rsync.

that would be a good solution to you, maybe: just let the code of streamer and encoder completly be, so the videos go to the streamer-site. on the streamer site, sync to the NAS/"encoder" and done. so if the NAS crashes, streamer (including all videos) still works. maybe i repeat you a bit until here.

the point is - when it's done this way, no symlinks or any other kind of mod will be needed. that should be completly intependend from the rest then.

**Comment by tgd1973** [comment]
It would be a good thing if you could create the streamer and encoder systems so that you can choose from the conf file, where to save the videos ... in the encoder now you are transcoding the files in this folder (videos) but if you also choose to store them as suggested at the beginning (because it resides on another PC so as not to mess up the streamer's backup) .... no longer understand what file mp4 must remain and which must be deleted ...
What I would ask from you is if perhaps posible to make videos in the encoder and make sure that the streamer can read them from the encoder (being another pc).
Thank you.

**Comment by hersche** [comment]
> in the encoder now you are transcoding the files in this folder (videos) but if you also choose to store them as suggested at the beginning (because it resides on another PC so as not to mess up the streamer's backup) 

well, it would work a bit another way, what is even more independed (i hope i repeat not too much, just for clearence)..

you can think the whole thing withouth a encoder first; you use the direct upload on streamer, the video goes to the streamer's server, you sync to your NAS with rsync in the ssh/ftp/whatever-protocol that's default anyway.. there's a raid, proper backup, only new, not backuped, files will generate traffic. code to change: 0. only contra: you eventually need a bigger hd for the server or a simple setup with a raid 0 or 10, unshure, mirroring, and 2 hd's. the big pro by this: if the NAS has any outtake, streamer will still be there. if the streamer is out, nothing will be reachable anyway in any solution.

with the encoder, you can also handle it very usual, since this would send the videos to the streamer, where they're backuped (so the encoder has less fallout-secure-prio)

> no longer understand what file mp4 must remain and which must be deleted ...

as i seen for now, in streamer, there's basicly only one mp4 per movie or maybe three with the various resolutions, but not more. also, you should be able to delete the files
a) in the encoder's interface
b) anyway, after they where send to the streamer (where it's less a mess)

> What I would ask from you is if perhaps posible to make videos in the encoder and make sure that the streamer can read them from the encoder (being another pc).

if the above (free & "hacking") solution is still not, what you search, then we can do a solution like this with the encoder, but like said earlier, i would do this as a paid job, we can discuss this for a first via e-mail: vinzenz.hersche@gmail.com

btw, if you like and use a solution with rsync/nfs, then a tutorial about it would be a great donation ;)

**Comment by hersche** [comment]
since version 5.5, there are two new media-types that may interesst you: linkVideo and linkAudio - with this, you event don't need a encoder, you can point to external mp4-videos with direct links (so apache alone would be enough). only thing: if you use ssl, use it on both servers. also, for this solution, both servers have to be reachable in public.

**Comment by tgd1973** [comment]
This solution is perfect for listing Live TV from other sites.
Thank you for thinking about this LiveLink ... It could not have happened a better thing about the possibility of listing WebTVs. You could still work if it is LiveTV in a way to categorize the menu at the top ... As long as there are 2 - 3 Live there are no problems but when (I hope) there will be more than a hundred you can not find with the same speed that you are looking for.

As I also said in the other open request ... there is this serious problem with sites that have SSL and those that do not have it. But I have seen many sites that use the encrypt of communications only in certain situations ... but as regards Live TV I do not believe that it is needed. also because there are many sites that using Wowza or other platforms, it is a more complex can to be realized with the SSL system, so the streams are from http ... at least from my part of the Earth there are many sites made in this way .. so it would be good to take a look at the redirect when you browse the plugins area regarding the LiveLinks in order to switch to http ... then return to https when navigating to other areas.

Regarding the request, which I did here, I would like to write in privat to request a change so that I can host all the videos in the encoder rather than in the streamer ... of course loading in the streamer automatically the link from where I can be seen the video downloaded from YT or previously loaded with the encoder. 
This would help when you make a load distribution module with multiple encoders and a single streamer ... to not weigh down the streamer (the same does YT (distribute the movies on multiple servers) ... that I had proposed for some time, and Daniel said yes but then maybe he forgot.
For now, a big thanks !!!
