### ISSUE TITLE
New install error

### ISSUE THREAD

**Issue by apeironian** [DanielnetoDotCom/YouPHPTube#725]
Fresh install of youPHPTube, getting error on install page:

"Connect Error (2002) No such file or directory"

From what I can tell, all paths are correct, db port is correct, db user and pass are correct, permissions are all blown wide open. I can't find any errors in system logs (maybe not looing in the right place). I'm stuck - please help.

This is on a Synology running 6.1 (php 5.6 and MariaDB 10) if that makes any difference.

Thanks a lot.

MC

<img width="1364" alt="screen shot 2018-05-28 at 12 29 28 pm" src="https://user-images.githubusercontent.com/39495806/40626317-6a9aa810-627d-11e8-94bf-fc9e6de4d9f2.png">
[Install YouPHPTube.pdf](https://github.com/DanielnetoDotCom/YouPHPTube/files/2045921/Install.YouPHPTube.pdf)

**Comment by DanielnetoDotCom** [comment]
Hi, can you please check your error log?

**Comment by apeironian** [comment]
I would love to check my error log, but I can't find the right one. Should
I be looking for httpd error log, or php error log? Any idea where that
might live on a synology install with those packages installed by synology
package manager?

I looked in all the error logs I could find that looked relevant in
/var/log and found nothing interesting. I even tried configuring a custom
error log path in php.ini and that resulted in nada.

MC

**Comment by DanielnetoDotCom** [comment]
Try this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by apeironian** [comment]
The only httpd error I got remotely recently is this, from yesterday:

2018-05-27T23:11:35-05:00 ClerviStation [Sun May 27 23:11:35.388244 2018]
[proxy_fcgi:error] [pid 6883:tid 1101001792] [client 10.8.0.6:50835]
AH01071: Got error 'PHP message: PHP Warning:  mkdir(): Permission denied
in /volume1/web/video/objects/functions.php on line 108\n'

But nothing from today.

And I don't have any log file in my videos folder, as you can see below.

root@ClerviStation:/volume1/web/YouPHPTube# ll
total 96
drwxrwxrwx 14 root       root   4096 May 28 12:01 .
drwxr-xr-x  7 root       root   4096 May 28 11:59 ..
-rwxrwxrwx  1 root       root     18 May 27 21:46 CNAME
drwxrwxrwx  2 root       root   4096 May 27 21:46 docker
-rwxrwxrwx  1 root       root   1427 May 27 21:46 Dockerfile
drwxrwxrwx  2 root       root   4096 May 27 21:46 feed
drwxrwxrwx  9 root       root   4096 May 27 21:46 google
-rwxrwxrwx  1 apeironian users 11055 May 28 12:01 .htaccess
-rwxrwxrwx  1 root       root   3797 May 27 21:46 index.php
drwxrwxrwx  2 root       root   4096 May 27 21:46 install
-rwxrwxrwx  1 root       root   1144 May 27 21:46 LICENSE
drwxrwxrwx  2 root       root   4096 May 27 21:46 locale
drwxrwxrwx  2 root       root   4096 May 27 21:46 nbproject
drwxrwxrwx  5 root       root   4096 May 28 11:56 objects
drwxrwxrwx 23 root       root   4096 May 27 21:46 plugin
-rwxrwxrwx  1 root       root   6227 May 27 21:46 README.md
-rwxrwxrwx  1 root       root    231 May 27 21:46 robots.txt
drwxrwxrwx  2 root       root   4096 May 27 21:46 update
drwxrwxrwx  2 apeironian users  4096 May 27 23:12 videos
drwxrwxrwx  8 root       root   4096 May 27 21:46 view
drwxrwxrwx  3 root       root   4096 May 27 21:56 YouPHPTube
root@ClerviStation:/volume1/web/YouPHPTube# ll -a videos/
total 8
drwxrwxrwx  2 apeironian users 4096 May 27 23:12 .
drwxrwxrwx 14 root       root  4096 May 28 12:01 ..

**Comment by hersche** [comment]
https://stackoverflow.com/questions/11657829/error-2002-hy000-cant-connect-to-local-mysql-server-through-socket-var-run?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

i assume, you have mysql-server installed?

**Comment by apeironian** [comment]
You are right. I had already configured the default mysql socket for php
5.6 to the correct value, and that wasn't working, so I replicated all
those settings to my php 7, and low and behold:




Thanks guys for your help you can close this ticket.


MC

**Comment by felipe5512** [comment]
![IMG-20191022-WA0036](https://user-images.githubusercontent.com/51463977/67315136-522a5800-f4dc-11e9-96b6-f75be5835b8b.jpg)

Youphptube v4.0


How to solve it?

**Comment by DanielnetoDotCom** [comment]
we are in version 7.7 please use the latest version.

**Comment by felipe5512** [comment]
I have version 7.6 and the same error as version 4.0

Em Ter, 22 de out de 2019 15:07, YouPHPTube <notifications@github.com>
escreveu:

**Comment by DanielnetoDotCom** [comment]
I have never seen this, I am pretty sure the error is in your mysql

what mysql version are you using?

are you sure your user has rights to create tables?

what is your server provider? for some reason looks like for me you are using a shared server

**Comment by felipe5512** [comment]
php version 7.3.10

I'm using 000webhost

Em Ter, 22 de out de 2019 15:50, YouPHPTube <notifications@github.com>
escreveu:

**Comment by DanielnetoDotCom** [comment]
000webhost is a shared server, NOT recommended, you should go to a VPS.

you have a predefined database name and I am not sure if you can create databases.

try to look into your mysql and apache log files

**Comment by felipe5512** [comment]
Strange I've seen videos on YouTube successfully installing youphptube
on 000webhost just for me that is giving error 😭


Em Ter, 22 de out de 2019 16:21, YouPHPTube <notifications@github.com>
escreveu:

**Comment by 4bucksdigitizing** [comment]
Hi,
I have installed on my hosting services but it is not connecting DB getting errors although DB and password is fine what should I DO? 
check in screen shots.  also I bought a vps but first I will install on this and then I transfer It to my vps.


![1 pic](https://user-images.githubusercontent.com/63563551/79632697-75c41780-817a-11ea-9ab7-9c897663238b.png)
![3 pic](https://user-images.githubusercontent.com/63563551/79632701-78bf0800-817a-11ea-9bc3-9bb882e6411a.png)
![4 pic](https://user-images.githubusercontent.com/63563551/79632702-79579e80-817a-11ea-821f-2d0fdb66e4a7.png)


![2 pic](https://user-images.githubusercontent.com/63563551/79632699-78267180-817a-11ea-9a57-c565a8c133f3.png)

**Comment by DanielnetoDotCom** [comment]
It is clear for me you are NOT using a VPS or a Dedicated server, which is strongly recommended.

but looks like you need to manage your credentials, to let it connect into it.

**Comment by Igmam21** [comment]
tengo el mismo problema. No puedo pasar de la primera pagina de instalacion... arroja el siguiente mensaje de error:    Sorry!
Unknown error! usando un vps

I have the same problem. I can't get past the first installation page... it throws the following error message: Sorry!
unknown error!  using in vps

**Comment by DanielnetoDotCom** [comment]
> tengo el mismo problema. No puedo pasar de la primera pagina de instalacion... arroja el siguiente mensaje de error: Sorry! Unknown error! usando un vps
> 
> I have the same problem. I can't get past the first installation page... it throws the following error message: Sorry! unknown error! using in vps

https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform#if-the-error-is-during-the-installation
