### ISSUE TITLE
upload works, public encoder works, but site won't play videos and can't download

### ISSUE THREAD

**Issue by apeironian** [DanielnetoDotCom/YouPHPTube#726]
Just got this site running. I can upload an mp4, or encode a file with public encoder. They both show up in my videos list. Verified all derivative files created by encoder got delivered to my server. Permissions are wide open.

BUT

I can't play a video, and I can't download anything from the download links in the video list. Screenshots attached. What am I missing??

<img width="615" alt="download_error" src="https://user-images.githubusercontent.com/39495806/40632718-964abd1a-62af-11e8-8057-c1f065e3fa41.png">
<img width="1332" alt="video_list" src="https://user-images.githubusercontent.com/39495806/40632719-9666f30e-62af-11e8-9e35-57ac5a160591.png">

Thanks again for the support.

MC

**Comment by hersche** [comment]
good question, can you do a ls / show me the content of the videos-folder? i can reach that server, but did not get the problem for the moment..

can you also make shure to update again (via git pull)? a lot of stuff should be fixed, that was not before.

**Comment by apeironian** [comment]
I will try updating with git pull. This is a fresh install from yesterday
though so I can't imagine there are that many changes.

when you say you "don't get the problem for the moment" does that mean that
the videos play for you successfully on my site??

root@ClerviStation:/volume1/web/YouPHPTube/videos# ll
total 48512
drwxrwxrwx  4 apeironian users     4096 May 28 19:18 .
drwxrwxrwx 13 root       root      4096 May 28 16:47 ..
drwxrwxrwx  2 http       http      4096 May 28 19:10 cache
-rwxrwxrwx  1 http       http       516 May 28 19:06 configuration.php
-rwxrwxrwx  1 http       http   1238912 May 28 19:09
dvlconsole_5b0c9a47eeb8d6.42246703.mp4
drwxrwxrwx  2 http       http      4096 May 28 17:49 userPhoto
-rwxrwxrwx  1 http       http     14151 May 28 19:41 youphptube.log
-rwxrwxrwx  1 http       http     21868 May 28 19:11
_YPTuniqid_5b0c9ab5e42b85.82028856.gif
-rwxrwxrwx  1 http       http  24127147 May 28 19:14
_YPTuniqid_5b0c9ab5e42b85.82028856_HD.mp4
-rwxrwxrwx  1 http       http     65551 May 28 19:11
_YPTuniqid_5b0c9ab5e42b85.82028856.jpg
-rwxrwxrwx  1 http       http   8268283 May 28 19:14
_YPTuniqid_5b0c9ab5e42b85.82028856_Low.mp4
-rwxrwxrwx  1 http       http  15894970 May 28 19:14
_YPTuniqid_5b0c9ab5e42b85.82028856_SD.mp4
-rw-rw-rw-  1 http       http      3910 May 28 19:18
_YPTuniqid_5b0c9ab5e42b85.82028856_thumbs.jpg
-rw-rw-rw-  1 http       http      1627 May 28 19:18
_YPTuniqid_5b0c9ab5e42b85.82028856_thumbsSmall.jpg

**Comment by apeironian** [comment]
root@ClerviStation:/volume1/web/YouPHPTube# git pull
Already up-to-date.

**Comment by apeironian** [comment]
Thank you for the help so far, much appreciated.

I will take a crack at this myself first, and hire you if I can't figure it
out.

MC

**Comment by hersche** [comment]
maybe this helps you, it's my file for the enocder-part (should work for streamer too)

https://pastebin.com/kSjBGgun

line 28 and 29 can be interessting to you ;)

**Comment by apeironian** [comment]
@hersche yes that helped thanks, but that was not all. Synology overwrites all httpd related .conf files on service restart, so you have to make your own, which it will append at service start. So I had this:

<Directory /volume1/web/YouPHPTube>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
        Order allow,deny
        allow from all
        Header set Access-Control-Allow-Origin "*"
        Header set Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS"
        Header set Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization, Client-Security-Token, Accept-Encoding"
</Directory>


And that did not work. 

Please note that /volume1/web/YouPHPTube is the ACTUAL path (not a symlink).

So on a hunch, I changed it to:

<Directory /var/services/web/YouPHPTube>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
        Order allow,deny
        allow from all
        Header set Access-Control-Allow-Origin "*"
        Header set Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS"
        Header set Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization, Client-Security-Token, Accept-Encoding"
</Directory>

note the symlinking:

lrwxrwxrwx   1 root root   12 May 21 11:34 web -> /volume1/web
root@ClerviStation:/var/services# pwd
/var/services

I restarted httpd and lo and behold, the dang thing works.

If someone can explain why this works, you get a gold star. I'm just happy it works and thankful for the help I got here.

Peace.

MC

**Comment by hersche** [comment]
phuu, there i have no clue about synology, where this seems to be specific.. anyway cool it works :+1:
