### ISSUE TITLE
Uploading customize plugin brokes the website

### ISSUE THREAD

**Issue by digisquares** [DanielnetoDotCom/YouPHPTube#734]
I installed youphptube in Digitalocean VPS  and was working fine until I uploaded the customize plugin. Now website is not responding. In chrome console log below error is there. help me to solve this error.

Failed to load resource: net::ERR_NAME_NOT_RESOLVED
http://d2xvc2nqkduarq.cloudfront.net/zr/js/adrns.js#ST1000LM014-1EJ164_W382VB07XXXXW382VB07

**Comment by digisquares** [comment]
Below log I found
 [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'youPHPTube.extraConfig' doesn't exist<br>
SELECT * FROM extraConfig WHERE  id = ? LIMIT 1

**Comment by digisquares** [comment]
I solved by manually connecting to mysql and executing the sql scripts. Kindly fix the issue in customize plugin.

**Comment by DanielnetoDotCom** [comment]
Thanks

Sorry for that.

I just sent a fix for this, to not break the site if you miss to install the tables
