### ISSUE TITLE
Invalid CDN link

### ISSUE THREAD

**Issue by digisquares** [DanielnetoDotCom/YouPHPTube#735]
Pls let me know how to fix this CDN issue

Failed to load resource: net::ERR_NAME_NOT_RESOLVED
http://d2xvc2nqkduarq.cloudfront.net/zr/js/adrns.js#ST1000LM014-1EJ164_W382VB07XXXXW382VB07

**Comment by DanielnetoDotCom** [comment]
I don't know, maybe cloud flare is blocking .
It is an issue regarding your server, NOT YouPHPTube

**Comment by digisquares** [comment]
Thanks for your suport. Pls just one more clarification. cloudfront.net is Amazon CDN. Whether adrns.js file is used in youphptube. If so how I can change the url to my server instead of CDN.

**Comment by DanielnetoDotCom** [comment]
Hi

I don't know what is adrns.js is , sorry I can't help you with this

**Comment by hersche** [comment]
i searched in the whole project, but do not find anything..

https://github.com/DanielnetoDotCom/YouPHPTube/search?q=adrns&unscoped_q=adrns

(i also searched offline, same result)

do you have any details, or can it be something like a tracker or visit-counter from digital-ocean itself? 

can you search in your control-panel, if there's anything get injected? i had this expirienced in the past, from the provider (on a free account) for ad's.

**Comment by hersche** [comment]
does not seem we get a feedback here.. i even don't see, what is broken here.. (does it have any effect or is it just a js-file that cannot be loaded?)

reopen, if needed.
