### ISSUE TITLE
Blank page in chart section

### ISSUE THREAD

**Issue by Andiweb87** [DanielnetoDotCom/YouPHPTube#736]
after updatet in YouPHPTube version 5.4 the chart page show only a blank page.

**Comment by hersche** [comment]
any errors in logs, under videos/youphptube.log?

also, did you do the database-upgrade after updating the files? for quick, i can not reproduce it.

**Comment by Andiweb87** [comment]
no i have not make an database upgrade i think., how can i do that ?

**Comment by hersche** [comment]
most direct:

your youphptube-adress and add /update to the end of the address/url.

or, in menu (you need to be admin), it's called "Update version"

if it worked, you can close this :)

**Comment by Andiweb87** [comment]
i have update this Your system is up to date

bu still the chart page is white, looks somthing is missing

**Comment by hersche** [comment]
ok, thanks for try.

what's possible too, is that you have to clear videos/cache.

also a look into the file videos/youphptube.log would be good :)

**Comment by Andiweb87** [comment]
sent you an email with link where is the youphptube.log because im not able to find the issue

thank you
