### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Kickassd** [DanielnetoDotCom/YouPHPTube#74]
Would be great if we had the option in admin to set all new uploaded videos to a certain user group. My site is private and I need to manually edit all uploads to assign them into the private group I have created.

CPU

If we had the ability to choose amount of threads used via the FFMpeg -threads option that would be awesome as we can then save some CPU for the rest of the site / server.

Delete Originals

An option to delete originals after encoding or on a once per 24 hour basis would be nice. Easy enough to manage via cron job but also would be handy to have in admin section.

Nice work thus far! @DanielnetoDotCom

**Comment by oyjcmyn** [comment]
This seems to be in the site settings Session Timeout in seconds can set the time.

**Comment by DanielnetoDotCom** [comment]
Hi I lile all your ideas...

- set all new uploaded videos to a certain user group.
I is a good feature, may be add in nextrelease

- choose amount of threads used via the FFMpeg -threads 
You can change the FFMPEG code on the advanced configurations
![image](https://user-images.githubusercontent.com/18009293/28670043-4d76856c-72ad-11e7-81d4-bc48ed1d3398.png)

- Delete Originals
Also may be in future releases

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
