### ISSUE TITLE
microsft buying github will kill the project ?

### ISSUE THREAD

**Issue by KazeroG** [DanielnetoDotCom/YouPHPTube#741]
Microsoft's takeover of GitHub raises concerns among developers
The developers fear that the platform, which hosts the source code of many free software, is denatured by Microsoft.

"If they plan to use the same revenue as for Skype or LinkedIn [bought by Microsoft], it promises ...", grumbled a developer on Twitter. Another is more radical: "I release all my projects and close my GitHub account. Like them, many developers disapprove of the purchase of GitHub by Microsoft, official Monday, June 4. They fear that the digital giant will denature the famous platform for hosting and sharing computer code.

what you think ? what are your thoughts about it ?

**Comment by hersche** [comment]
i really like https://about.gitlab.com/ .. this is also possible for self-hosting. sad what github do now.. :s

**Comment by DanielnetoDotCom** [comment]
Hi

We will keep this project open source.
We don't have problem to move this project to a different source controll platform if needs

**Comment by hersche** [comment]
i just found a plattform, that can be more interessting to us, because it looks easier for self-hosting and more free:

https://gitea.io/

i think, hold a git-mirror here would be a acceptable solution for a while (when we decide to move definently)
