### ISSUE TITLE
spam in encoder youphptube ?

### ISSUE THREAD

**Issue by jgtube** [DanielnetoDotCom/YouPHPTube#742]
spam? virus? see screenshots please at http://inscripciones.vetjg.es/screenshots

**Comment by DanielnetoDotCom** [comment]
You are not processing anything on your encoder.

check your encoder log file.

probably a problem on your FFMPEG

**Comment by Criptos** [comment]
I got the same issue. I set up the encoder and the streamer on the same VPS, but ONLY updated /etc/hosts for the streamer. 
Try adding 127.0.0.1 to your encoder fqdn at /etc/hosts

**Comment by hersche** [comment]
>  I set up the encoder and the streamer on the same VPS, but ONLY updated /etc/hosts for the streamer.

in the settings, you simply can set the encoders address. changing the hosts-file for this sounds a bit like (unnecessary) hacking, but if you prefer this way, i would make shure, the server is pointing the right way.
also, the encoder's address is often used direct in the browser, so on the client's site - there, your /etc/hosts-change have no influence and you will reach the (real) public encoder (with "spam") again.

**Comment by Criptos** [comment]
No I didn't express myself correctly. 
Encoder do: 
Fetch 
Encode
Submit  
 
Fetching of 'local submitted files' is done with the fqdn internally. So if you don't edit the /etc/hosts of the VPS to point the fqdn of the encoder, it makes a dns request, and that makes a request to the external ip address, but without forwarding no nat rules apply and the request is lost.  
The encode is done with ffmpeg and the is submitted to the streamer site. 

Have you seen in the database who submitted to encoding those files?

**Comment by hersche** [comment]
> Have you seen in the database who submitted to encoding those files?
according to the screenshots: http://clipeye.online/
there's a usual youphptube-installation as well.. but the link from the screenshot also says it's on encoder.youphptube.com, that's the official encoder anyone can use.

as i understand, you, @Criptos , use a own domain for your encoder, but you have this also in /etc/hosts , so your's is not encoder.youphptube.com?

but you have spam in your very own encoder? did you restrict the websites to your domain only? if all those questions can be answered for shure with yes, that's bad. but if the "spam" is only on the public encoder, it doesn't wonder me..

**Comment by hersche** [comment]
or did i completly misunderstood and the encoder is sending these movies to your streamers?

**Comment by hersche** [comment]
no response nor activity here.. i close it. reopen if you feel it's needed.
