### ISSUE TITLE
Content, external mix m3u8 (http) together with the https of the site, blocked by the browser 

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#743]
How can I force a passage to http, only for the plug "LiveLinks" to avoid having mixed content blocked in the browser ... I have many links of sites with live TV that transmit on http ... I can not make proxy_pass 
 for viewing on https ...
This is the part of code of the index.php of the plug:

`<!DOCTYPE html>`
`<html lang="<?php echo $_SESSION['language']; ?>">`
    `<head>`
       `<title><?php echo $config->getWebSiteTitle(); ?>  :: Live Links</title>`
        `<?php`
        `include $global['systemRootPath'] . 'view/include/head.php';`
        `?>`
There are sites that at the time of watching the WebTV player automatically switch to http ...  for not having problems with the contents ...  Thanks.

**Comment by DanielnetoDotCom** [comment]
If you are using https in your web site, you can NOT use http content on it.

if you are using http in your web site, you can use http or https content on it.

**Comment by tgd1973** [comment]
I know, and this is precisely why I ask here a redirect system to http only for the LiveLink module
more or less how it works on this site ... https://alfaomega.tv/   when you click on live tv https://alfaomega.tv/canal-tv/alfa-omega-tv

**Comment by hersche** [comment]
this is technical difficult i think. i never tried "LiveLinks", but i assume they are external links providing a video so you cant change to ssl there.

something like a proxy that @tgd1973 can use standalone and that forward the http to https would be a proper solution, i think.

there, i found this, the name looks perfect for the problem: https://packagist.org/packages/geekality/php-cross-domain-proxy but this needs to be integrated in code. nginx can do the same (with proxy).

**Comment by tgd1973** [comment]
with the risk of passing all the video traffic through the personal server, I already tried to do the nginx proxy in the same way as I did for my nginx-rtmp. while the proxy from your streaming works, streaming from an external server I think it is not supported because there is so called crossdomain origin that blocks.

**Comment by DanielnetoDotCom** [comment]
@tgd1973 I dont think it is possible , it is a browser limitation/security NOT a script/server configuration

**Comment by tgd1973** [comment]
With the risk of repeating, please enter this site and see how it reacts
  when you go to the live tv section ... that's what I wanted. (maybe I do it, just me, on my site).
I know it's a browser problem and I think that the only possibility is to redirect, when you surf LiveLink, to an Http page, to have no problem with the browser, then when you go to other areas of the site to return on Https.

https://alfaomega.tv    when you click on live tv   https://alfaomega.tv/canal-tv/alfa-omega-tv

**Comment by DanielnetoDotCom** [comment]
Understood, it is a good idea.
Thanks we may improve it in the future and change it

**Comment by DanielnetoDotCom** [comment]
but now you are using http instead https on the live link section.

Your users may be logged off when you switch between http and https
