### ISSUE TITLE
Plugin: VideoThumbnails works only for short videos

### ISSUE THREAD

**Issue by TLCReuver** [DanielnetoDotCom/YouPHPTube#744]
Hello,

I installed the plugin VideoThumbnails (UUID: 28e74f9a-a2ef-4644-86f0-40234ae7c1b5) and it work properly only for videos which are shorten than 4 minutes, With bigger videos it creates a thumbssprit file with zero bytes.  What is going worong here ? Thankz for reading this message,

Specs:
YouPHPTube installed on vhost with plugin "SecureVideosDirectory" installed.
Apache/2.4.25, PHP 7.0.27-0+deb9u1, post_max_size is 4096M,  upload_max_filesize is 4096M.

**Comment by DanielnetoDotCom** [comment]
please check your streamer log file, should be some glue there

**Comment by TLCReuver** [comment]
Hello Daniel,

Here are my log-files... there seem to be an error from PHP.

Thankz for watching for my problem.


[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2077524/youphptube.log)
[youphptube.js.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2077525/youphptube.js.log)
[apache2.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2077528/apache2.log)
[access.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2077542/access.log)

**Comment by DanielnetoDotCom** [comment]
Can you please also get the log from encoder?

**Comment by TLCReuver** [comment]
Hi Daniel,

I think that the file you need is in YouPHPTube-Encoder/videos/youphptube.log

[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2077632/youphptube.log)

**Comment by DanielnetoDotCom** [comment]
I cant find anything there, can you please delete the log file the try to use the plugin again . then send the log again?.

we may get a cleaner log file

**Comment by TLCReuver** [comment]
Done, but no error found.
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2077707/youphptube.log)

**Comment by DanielnetoDotCom** [comment]
So no errors and no Thumbs extracted?

Are you using any CDN or firewall?

**Comment by DanielnetoDotCom** [comment]
Question, is your encoder up to date?

**Comment by TLCReuver** [comment]
In the folder videos there are lots of folders with imiges out001.png till out101.png

![snap2](https://user-images.githubusercontent.com/39981177/41058799-40b0b67c-69ba-11e8-995a-2e66c839e769.jpg)

**Comment by DanielnetoDotCom** [comment]
This does not make difference 

Can you please check if your encoder files are updated?

**Comment by TLCReuver** [comment]
Tomorrow I make a clean install of the encoder and also the plugin. You hear from me. Thankz till now.

**Comment by DanielnetoDotCom** [comment]
thanks, let me know if it is working fine.

**Comment by TLCReuver** [comment]
Hi Daniel,
I make a clean install off the encoder with a clean SQL and installed the last plugin but have the same result (max 4 minute videos). Because i'm a newby on Linux i tried to increase the default_socket_time from 60 to 3200 seconds in php.ini with results.  Videos from 45 minutes have no problems but videos above 1 hour create no thumbsspirits and the folder with  images from out001.png till out101.png are not deleted.

![snap4](https://user-images.githubusercontent.com/39981177/41084598-2fb5a584-6a24-11e8-91e7-b811c4445d93.jpg)

**Comment by DanielnetoDotCom** [comment]
I am not sure what is going on, I guess it may be a memory leak. I have no problem to create in on long videos, but the servers I have doing it have 32 GB RAM.
I am not sure if this is the problem

**Comment by TLCReuver** [comment]
I think too that it is a memory leak but i'm happy that it work now. I'll split the long videos into 2 parts, that's no problem. Thank you very much for your help.

**Comment by DanielnetoDotCom** [comment]
Ok, thanks for your feedback
