### ISSUE TITLE
cant login to admin or user after a few hours,it just loads and goes back to homepage. and new signup returns wrong captcha, what might be the problem? 

### ISSUE THREAD

**Issue by pavlikdee** [DanielnetoDotCom/YouPHPTube#747]

**Comment by hersche** [comment]
do you respect that the captcha is using lower-case and upper-case?

to go back to the homepage is usual, if it not worked, you should see a error.

if the installation is in public, can you provide a address, so we can recheck it?

**Comment by pavlikdee** [comment]
thanks @hersche . my host had a problem. my hdd was full and after freeing up some space i got in.
