### ISSUE TITLE
Play List

### ISSUE THREAD

**Issue by willtsuru** [DanielnetoDotCom/YouPHPTube#749]
Hi 
1) I need know please if its possible to have a playlist to be executed indefinitely maybe must i need make some modification? I mean that i need that the playlist don't stop at last video but go to the first video and start again.

2) Its possible to edit an playlist adding or removing videos direct from my video list?

thanks and advance

**Comment by DanielnetoDotCom** [comment]
Unfortunately for now it is not possible, but is possible to be implemented.

If you are willing to pay for that you can contact us on developer@youphptube.com to get a quotation

**Comment by hersche** [comment]
this is in discussion/work via email, so i think we can close it here
