### ISSUE TITLE
GNU AGPL v3

### ISSUE THREAD

**Issue by maverick74** [DanielnetoDotCom/YouPHPTube#75]
This is a great idea.
Finally someone done it.

However, and while i like a lot of the GPL3 license, i believe AGPL 3 would serve the project a lot better!

**Comment by DanielnetoDotCom** [comment]
I do not know, AGPL 3, what is the difference.
PS I dont mind to change the license

**Comment by maverick74** [comment]
Hi,

i'm not a lawyer, but basically AGPL3 is equal to GPL3, but it says that making the service available over a network is considered "distribution" of the product.

GPL3 says that if you choose to distribute your software, you have to share the code, but there was a loophole and, if the software was used over a network, it was not clear if it was considered "distribution" or not.

Example: imagine you built OpenOffice. 
If you pick up a CD and share the software, it was considered "distribution".
But, if you installed the software on your server and let others use the software thru your server it was not clear if it was distribution or not (apparently, some companies thought they did not have to share the code/improvements of their apps, since they where not giving away the binaries but letting users access their server)

AGPL3 came to change/clarify that. It says that if you let others use the software that you have over a network it is considered distribution and, as such, they have to comply and share the code/improvements they made.

it is, in my opinion, the best way/license to guarantee that you/your project benefit from other peoples' improvements.

I'm not sure, but i also think that if you intent to change the license your contributors have to agree with it, or you have to remove their code.

more at: [https://www.gnu.org/licenses/agpl-3.0.en.html](https://www.gnu.org/licenses/agpl-3.0.en.html)

**Comment by DanielnetoDotCom** [comment]
I do not have much problem to upgrade to this license, what should i do to change it? just change the license file?

**Comment by maverick74** [comment]
I believe so, but i'm not sure. 
I know that the other developers have to agree to it, or their code has to be removed. But has to change the Licence i believe it's just by changing the file or configs in the github project preferences... but i'm not sure!

however, this is just my advice from what i know of licences: it's your project, so it's your call :D. I'm not an expert on this subject ;)

**Comment by DanielnetoDotCom** [comment]
The only license options I have are those 
![image](https://user-images.githubusercontent.com/18009293/30275062-5cf9f08a-96d6-11e7-9be2-788925b3ae52.png)

**Comment by maverick74** [comment]
It's the GNU Affero General Public License V3.0 ( = GNU AGPL v3) ;)

**Comment by DanielnetoDotCom** [comment]
Done it

**Comment by maverick74** [comment]
:) Nice to see you agree with it (as well as the other devs)!

I think this can be marked as done as well.

_(by the way... i liked a lot of that "**First Thing...**" from the "README.md" ;)_

**Comment by DanielnetoDotCom** [comment]
Thanks, to Him be glory for ever
