### ISSUE TITLE
Main Purpose of YPTWallet

### ISSUE THREAD

**Issue by CharlesChidozie** [DanielnetoDotCom/YouPHPTube#750]
Hello, i want to know the main purpose and advantage of the YPTWallet, and how it works.

**Comment by DanielnetoDotCom** [comment]
Hi @CharlesChidozie check this ...
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/YPTWallet-Usage

**Comment by hersche** [comment]
this looks answered.. i close it.
