### ISSUE TITLE
Live Links issue ?

### ISSUE THREAD

**Issue by Andiweb87** [DanielnetoDotCom/YouPHPTube#755]
Hi again, i dont know if an issue or not but i have a problem about Live Links plugin , when i put links they show in main and is ok,  when my friend (admin also) put the link is not show in main page, how is possible ? its seems only me can put links there and not other admin's

**Comment by DanielnetoDotCom** [comment]
check your server date, maybe is different from your PC date

**Comment by Andiweb87** [comment]
the issue is about other admins when add links , mine is ok , i have not a problem like this.

**Comment by DanielnetoDotCom** [comment]
there is no relation between admins.
all of them have the same right.

the only thing may be related in the client time and server time. the time you choose on the Live Link is the server time.
