### ISSUE TITLE
"Update to ver 2.0"  what is this?

### ISSUE THREAD

**Issue by brajeshrgupta** [DanielnetoDotCom/YouPHPTube#756]
Hi

On every Page view we are getting this message . All visiter are getting this message.

Why this message is showing to all visiters.

You can check live site on  https:;/ tv.newstracklive.com

Please take this on high priority. This is very bad user experience.

Regards 

Brajesh Gupta

**Comment by DanielnetoDotCom** [comment]
this is what i got from your site
![image](https://user-images.githubusercontent.com/18009293/41194802-c4bb5762-6bf7-11e8-9c3a-039924263418.png)

I am not sure what have you done, please give us more details of what did you done to get this

**Comment by hersche** [comment]
this seems solved? at least, i didn't found such messages anymore..

**Comment by brajeshrgupta** [comment]
This message is showing for 1-2 hr continually and after that disappeared.

Can you provide details for what you have coded this.message.

For which query or action?

**Comment by hersche** [comment]
those messages are not from us directly.. we have not coded them. in this case, they came from mysqli, the database-driver.

Are you shure, you have not changed anything, like doing a database-upgrade or something meanwhile?

**Comment by hersche** [comment]
i have documented it here:

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Mysql-Troubleshooting

so i close it now.
