### ISSUE TITLE
Unknow user at channel after last update..

### ISSUE THREAD

**Issue by Criptos** [DanielnetoDotCom/YouPHPTube#757]
I found that the name and background was missing: 

![image](https://user-images.githubusercontent.com/4574233/41198483-19557244-6c43-11e8-8b4f-c4e10aa61bc0.png)

And found that in channel.php line 31 $user is defined, at line 49 head.php is included. 

In head.php there is a new declaration of user 
`        $user = new User($video['users_id']);
        echo $user->getAnalytics();`
overwriting the $user object...

**Comment by DanielnetoDotCom** [comment]
Agree, thanks for the fix
