### ISSUE TITLE
Error in downloading/encoding flv format ...

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#759]
Hello! 
I can not download from any site and then transcoding the flv format ...
Also tried on your demo site ...

https://www.sample-videos.com/video/flv/720/big_buck_bunny_720p_1mb.flv

My Log:

[10-Jun-2018 14:11:39 Europe/Berlin] Getting from Youtube DL /usr/local/bin/youtube-dl  --force-ipv4 --no-check-certificate -k -o /tmp/youtubeDlJ9bram.mp4 -f 'mp4' https://www.sample-videos.com/video/flv/720/big_buck_bunny_720p_1mb.flv
[10-Jun-2018 14:11:41 Europe/Berlin] /usr/local/bin/youtube-dl  --force-ipv4 --no-check-certificate -k -o /tmp/youtubeDlJ9bram.mp4 -f 'mp4' https://www.sample-videos.com/video/flv/720/big_buck_bunny_720p_1mb.flv

![error_download_flv](https://user-images.githubusercontent.com/15127860/41201474-1e4c5bca-6cb9-11e8-8874-3cc10976437a.jpg)

**Comment by tgd1973** [comment]
Thanks for the reply. I expected something more ... 
If I introduce a site with the hidden link youtube-dl can find the link but if I offer it without hidden anything can not ... this thing seems very strange. Then I have so many files of 1 - 2 GB ... it would be a great help if I do not have to download then upload ... just think about the waste of time ...
My opinion is that there is something wrong with the encoder ... or maybe done on purpose ...

**Comment by DanielnetoDotCom** [comment]
@tgd1973 you may looking for a youtube-dl upgrade, you can suggest it on their repository https://github.com/rg3/youtube-dl

**Comment by tgd1973** [comment]
Try asking a question to them.
Thank you very much

**Comment by DanielnetoDotCom** [comment]
Anyway, I was thinking if some one is interesting to update the encoder code, it can be done using wget.

**Comment by tgd1973** [comment]
Unfortunately I have to say that I did the test, and you can do it too ... in command line it works to download ...
So there is a problem in the encoder.

![youtube-dl-k](https://user-images.githubusercontent.com/15127860/41205985-75d7e2bc-6cfd-11e8-8757-06e8d2f729a5.jpg)

**Comment by hersche** [comment]
can you try the same with

sudo -u www-data

in front of the command? because root can mostly do things and write folders, www-data can't.. maybe it gives you a error with this user..

**Comment by tgd1973** [comment]
It does not give me error, but also to the demo software ... so to the whole platform ... Try it too because even your youphpTube should give the same problem .

**Comment by DanielnetoDotCom** [comment]
I just make a debug and I know why it is happening.


```
youphptube@youphptube:/var/www/html/YouPHPTube-Encoder$  /usr/local/bin/youtube-dl  --force-ipv4 --no-check-certificate -k -o /tmp/youtubeDl4ldSs1.mp4 -f 'mp4' https://www.sample-videos.com/video/flv/720/big_buck_bunny_720p_1mb.flv
[generic] big_buck_bunny_720p_1mb: Requesting header
ERROR: requested format not available
youphptube@youphptube:/var/www/html/YouPHPTube-Encoder$

```

By default the encoder try to download the .mp4 format.
the link you used is a .flv only

so for now you cant direct download video files using youtube.dl

**Comment by tgd1973** [comment]
I would not bother with my questions but I would like to know when you solve this problem because as far as I know ffmpeg can convert flv to mp4, then youtube-dl can also download flv format to convert with ffmpeg to add it to the streamer archive ... it's just an encoder problem ... but I do not know where to start to debug the encoder.
I'm waiting for help from you.
Thanks in advance.
