### ISSUE TITLE
Slack Chat For YouPHPTube

### ISSUE THREAD

**Issue by Dradden** [DanielnetoDotCom/YouPHPTube#76]
Hi,

I have started a Slack chat channel for the purpose of chat and helping people out with YouPHPTube. You can get yourself invited here:

https://join.slack.com/t/youphptube/shared_invite/MjE3NzQ5MDU2Mjc3LTE1MDEwMTkzMzktZWQyZGJkNzY0Ng

**Comment by DanielnetoDotCom** [comment]
Very thanks, I will appreciate

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
