### ISSUE TITLE
recent changes

### ISSUE THREAD

**Issue by Nisarg22** [DanielnetoDotCom/YouPHPTube#762]
after recent changes my site have a common problem
![opera snapshot_2018-06-11_202445_nisargpathak36 000webhostapp com](https://user-images.githubusercontent.com/39002772/41239651-477bfa8e-6db6-11e8-8c03-32d311a55c69.png)
this error appears when i try to open configuration page
check my site
username and password are admin
Version 5.6 has many problems please fix it
About page is blank
Contact page shows error 500

**Comment by DanielnetoDotCom** [comment]
can you please check the error log

**Comment by DanielnetoDotCom** [comment]
BTW this morning, we fixed a lot of issues, you may want to pull the changes

**Comment by hersche** [comment]
yeah, today a weird merge was happening by me. i wanted to update the php-router-branch here:
https://github.com/DanielnetoDotCom/YouPHPTube/pull/761

there, it is alright, but somehow i've merged it into the master-branch, i am sorry for this.

right after this was clear, we did kind of a reset (for the new rewrite) and fixes, so update is a good idea.

**Comment by hersche** [comment]
i have found some stuff and fixed it some seconds ago, so i really please you to update again..

**Comment by Nisarg22** [comment]
Visit my site nisargpathak36.000webhostapp.com
Error 500 comes
