### ISSUE TITLE
Embeded video loading in the background

### ISSUE THREAD

**Issue by eZweblogic** [DanielnetoDotCom/YouPHPTube#764]
I realized that embedded videos despite it's idle looks it actually starts loading at the background. This is not an ideal situation. It should not load unless the user clicks the play button.

I disabled auto play in the hope that it will stop the behavior but no change. If there are several videos on one page (Embedded in wordpress website) then they will all load at the background.

How can I stop video loading or pre loading or buffering?

Thanks

**Comment by hersche** [comment]
`<video preload="auto|metadata|none"> `

https://www.w3schools.com/tags/att_video_preload.asp

there's no simple "all", so that's up to the browser and we already have it on auto (which is most like "all" or "on")

**Comment by eZweblogic** [comment]
Thank you hersche,

I went with metadata which does what I wanted to happen.

Appreciate your prompt response

**Comment by hersche** [comment]
maybe we can make that optional / choose-able..
