### ISSUE TITLE
Permanent Link not working

### ISSUE THREAD

**Issue by ChrisSlS** [DanielnetoDotCom/YouPHPTube#765]
Hello,

Permanent links no longer work, for when I upgraded to version 5.5, it worked. Then when version 5.6 was done, it did not work anymore, and I can not understand why.

for example, let's take this link to the demo site : 
https://demo.youphptube.com/v/263

Alright, it works perfectly.

And take the links to my site:
https://canalgx.fr/v/35

The result is identical to version 5.4 and lower.

Can you help me please ?

**Comment by hersche** [comment]
yesterday, we had a bigger restructuring, so when it works in the demo, maybe another git pull can help? but i think, you are on the newest (not only version, but git/files).

if daniel is not faster, i will have time in latest 6-7h, to review this. permalinks is something i never directly dealed with until yet.

**Comment by ChrisSlS** [comment]
You were right, everything was updated a few minutes ago as well as the cache cleaning.

Thank you so much for responding so quickly !

**Comment by hersche** [comment]
i tried to reproduce it and have a look for errors here

https://demo.codebea.ch/v/2

but found nothing.

but i found this in your log:

> [12-Jun-2018 16:03:54 Europe/Berlin] Failed to connect to canalgx.fr port 444: Connection refused

is this the livestreamer-part? basicly i don't think it's in context to the bug, but i am really unshure for now if this had weird side-effects or not in older issues.

something else confuses me.. 

https://canalgx.fr/v/35

differs from

https://canalgx.fr/v/36

(other "mainvideo") very unshure why and how this is handled by the gallery, but it reacts somehow..

can you try around with plugins or options (in gallery-plugin)? or paste the config-json from gallery, so i may can reproduce..

**Comment by hersche** [comment]
i can reproduce it..
https://rewrite.codebea.ch/v/1

as you can see, here the subdomain is not demo. it's weird, basicly this is for the new.htaccess, but at the moment, the classic rewrites are active there and the issue is the same.. no idea why it's not on demo (should be identical atm). i even checked it out again, but let the db and videos-folder be.

**Comment by ChrisSlS** [comment]
> [12-Jun-2018 16:03:54 Europe / Berlin] Impossible de se connecter au port 444 de canalgx.fr: Connexion refusée

Yes, is this the livestreamer. It has been a long time in the log file, but I do not know where it comes from, and that does not cause any problem to my knowledge.

/v/35 & /v/36 are different ? What do you mean ?

regarding config-json, here it is (is it this ?):

`{"BigVideo":true,"Description":false,"CategoryDescription":false,"DateAdded":true,"DateAddedRowCount":"12","MostWatched":true,"MostWatchedRowCount":"12","MostPopular":true,"MostPopularRowCount":"12","SortByName":false,"SortByNameRowCount":"12","SubscribedChannels":true,"SubscribedChannelsRowCount":"12","sortReverseable":false,"SubCategorys":false,"showTags":false}`

I tried to change certain values and disable plugins but that does not change anything, except that I disable the gallery mode obviously.

**Comment by hersche** [comment]
oh wow, the commit closed the issue automaticly.. 

ehm, thanks for your response, i still don't know why it worked at the demo-url's, but i found what's failing.. :)

> regarding config-json, here it is (is it this ?):

yep, that i meaned

> /v/35 & /v/36 are different ? What do you mean ?

the first shown, big video was another. also, if the id was wrong, it gives a message "there are no videos avaible" - but the message was still from gallery-plugin and therefore wrong.

please try and confirm then, git pull only should be enough..

**Comment by ChrisSlS** [comment]
You too hard guy, it works thank you very much !

@hersche

**Comment by CorpCaleCloud** [comment]
I raised this issue/question and it's not fixed for me, can you investigate?

https://github.com/DanielnetoDotCom/YouPHPTube/issues/949 

![hide video url like yourube](https://user-images.githubusercontent.com/25417743/44006769-cbd5be0e-9e81-11e8-99f4-3b5367827cf3.PNG)

**Comment by ChrisSlS** [comment]
@hersche hey, can you edit the posts where you wrote the links to my site please?
