### ISSUE TITLE
http and https problem

### ISSUE THREAD

**Issue by Andiweb87** [DanielnetoDotCom/YouPHPTube#766]
Hello, i have see an problem about when typing www.yourwebsite.com , the page does not go under the https but remain only in the domain typed and also in the page icones and some other stuff missing.

i think need to make somthing when a visitor type www.yourwebsite.com the site redirect in https:// automatically and not manually.

thank you

**Comment by tgd1973** [comment]
This option can be done from the control panel if it has ISPConfig ... or alternatively if it has no panel, it must try from .htaccess.
However if the same server also has the encoder + module nginx-rtmp for live streaming is not advisable to continue with the automatic redirect ... because nginx-rtmp can work only on http ... not ssl.

**Comment by Andiweb87** [comment]
so what do you suggest ? 

thank you

**Comment by hersche** [comment]
i would say, this can always be done in the webserver, also by direct set configs.. there are lots of tutorials for this, you can find on google.

https://stackoverflow.com/questions/4083221/how-to-redirect-all-http-requests-to-https
this is for apache, first answer with htaccess, second with direct apache-config.

but there would be even tutorials for nginx.

if we change it for all users, we rectrict flexibility (for internal use or limited systems). but you can modify your site without problems. like said, this is more a part of admin's work / job for the webserver.

i may will write a small howto later, in the wiki

**Comment by Andiweb87** [comment]
thank you hersche , i will wait for that.

**Comment by hersche** [comment]
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Redirect-http-to-https

I would recommend you the .htaccess-solution, it's the most simple. I hope this helps and i am interessted if it worked for you.

**Comment by Andiweb87** [comment]
Hi Hersche  thank you about this , technically works , i have follow the steps but something is not going to good, i send you an email.

thank you again

**Comment by hersche** [comment]
yep, in your case, a redirection for www.server.com -> server.com would be needed.

i extended the .htaccess-section in the above article with a little description for this use-case.
