### ISSUE TITLE
Increase Session Time

### ISSUE THREAD

**Issue by Dradden** [DanielnetoDotCom/YouPHPTube#77]
Session time at the moment is really short and I constantly have to log back in, and on long uploads I get logged out and it fails.

Increasing sessions to something like 4 hours with an option to "Stay logged In" would be much appreciated.

**Comment by DanielnetoDotCom** [comment]
Did you try the configuration on advanced configuration?
![image](https://user-images.githubusercontent.com/18009293/28669739-bf26c7dc-72ab-11e7-8dea-a354959392d9.png)

**Comment by Dradden** [comment]
I completely missed that, thanks!
