### ISSUE TITLE
ERROR With LIVE Broadcast

### ISSUE THREAD

**Issue by cespa92** [DanielnetoDotCom/YouPHPTube#772]
When I try do a Live I get this error on OBS.... Thanks!
![image](https://user-images.githubusercontent.com/40332413/41513067-725f8ad2-725b-11e8-9c3c-bbc6d2c16460.png)

![image](https://user-images.githubusercontent.com/40332413/41513070-85f9a67c-725b-11e8-82c9-8e71d9888197.png)

**Comment by DanielnetoDotCom** [comment]
This is hard to say, you have to make sure your NGINX is working, also if youe RTMP module is working
Did you compile NGINX with RTMP correct?

**Comment by cespa92** [comment]
Are there a tutorial for that... I used this: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Set-up-my-own-Stream-Server

**Comment by hersche** [comment]
i am not shure if this configuration-part is already respected in the tutorial:

https://github.com/DanielnetoDotCom/YouPHPTube/issues/632

does this help?

**Comment by hersche** [comment]
@devioustho you become that via e-mail? no clue ^^

@cespa92 maybe one of those can help you? there are 3 issues, which seems fixed..

https://github.com/DanielnetoDotCom/YouPHPTube/issues/432

if it fixes it, can you tell us the concrete issue was breaking it? then we can correct / expand it in the doc's :)

**Comment by cespa92** [comment]
@hersche appears an error when I try install appear this ERROR: sorry I am really newbie... :( 
cespa@portalvideo2018:~$ sudo apt-get install apache2 php7.0 libapache2-mod-php7.0 php7.0-mysql php7.0-curl php7.0-
gd php7.0-intl mysql-server mysql-client ffmpeg git libimage-exiftool-perl && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube.git && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube-Encoder.git && sudo apt-get install python && sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && sudo chmod a+rx /usr/local/bin/youtube-dl && sudo a2enmod rewrite
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libimage-exiftool-perl is already the newest version (10.10-1).
apache2 is already the newest version (2.4.18-2ubuntu3.8).
git is already the newest version (1:2.7.4-0ubuntu1.4).
libapache2-mod-php7.0 is already the newest version (7.0.30-0ubuntu0.16.04.1).
mysql-client is already the newest version (5.7.22-0ubuntu0.16.04.1).
mysql-server is already the newest version (5.7.22-0ubuntu0.16.04.1).
php7.0 is already the newest version (7.0.30-0ubuntu0.16.04.1).
php7.0-curl is already the newest version (7.0.30-0ubuntu0.16.04.1).
php7.0-gd is already the newest version (7.0.30-0ubuntu0.16.04.1).
php7.0-mysql is already the newest version (7.0.30-0ubuntu0.16.04.1).
ffmpeg is already the newest version (7:2.8.14-0ubuntu0.16.04.1).
php7.0-intl is already the newest version (7.0.30-0ubuntu0.16.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
}Setting up nginx-full (1.10.3-0ubuntu0.16.04.2) ...
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.servic
e" and "journalctl -xe" for details.
invoke-rc.d: initscript nginx, action "start" failed.
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-06-18 01:42:04 UTC; 7ms ago
  Process: 12732 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=1/FAILURE)
  Process: 12722 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS
)
Jun 18 01:42:02 portalvideo2018 nginx[12732]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
Jun 18 01:42:03 portalvideo2018 nginx[12732]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address alread...use)
Jun 18 01:42:03 portalvideo2018 nginx[12732]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
Jun 18 01:42:03 portalvideo2018 nginx[12732]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address alread...use)
Jun 18 01:42:03 portalvideo2018 nginx[12732]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
Jun 18 01:42:04 portalvideo2018 nginx[12732]: nginx: [emerg] still could not bind()
Jun 18 01:42:04 portalvideo2018 systemd[1]: nginx.service: Control process exited, code=exited status=1
Jun 18 01:42:04 portalvideo2018 systemd[1]: Failed to start A high performance web server and a reverse pro...rver.
Jun 18 01:42:04 portalvideo2018 systemd[1]: nginx.service: Unit entered failed state.
Jun 18 01:42:04 portalvideo2018 systemd[1]: nginx.service: Failed with result 'exit-code'.
Hint: Some lines were ellipsized, use -l to show in full.
dpkg: error processing package nginx-full (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 nginx-full
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by hersche** [comment]
looks like something in the conf is wrong, caused nginx to crash on start..

can you paste your modified nginx-configs?

**Comment by cespa92** [comment]
@hersche Here part of nginx conf
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://104.196.137.193/YouPHPTube/plugin/Live/on_publish.php;
                            on_play http://104.196.137.193/YouPHPTube/plugin/Live/on_play.php;
                            on_record_done http://104.196.137.193/YouPHPTube/plugin/Live/on_record_done.php;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';
                            # CORS setup

**Comment by cespa92** [comment]
@hersche a fool error, I forgot the Firewall Rules, and I changed it, and now the live is working... 
The next question is How I can enable the chat, appears the error Chat connection fail... Thanks!
![image](https://user-images.githubusercontent.com/40332413/41526405-c3849f94-72a9-11e8-89be-c01a6ff2acfd.png)

**Comment by cespa92** [comment]
@mikweb2017 Nothing, appears Chat connection fail

**Comment by mikweb2017** [comment]
have you activated the live chat plugin and installed the tables?

**Comment by cespa92** [comment]
@mikweb2017 Yes I activated, but doesn't work... thanks!

**Comment by DanielnetoDotCom** [comment]
@cespa92 try this and check if your port 8888 is opened 

`lsof -i :8888`

Also make sure you install all the tables (LiveChat)

you also may want to try run this with out nohup

`php /[path-to-YouPHPTube]/plugin/LiveChat/chat-server.php`

leave that open and try to connect using a telnet to it 

`telnet 104.196.137.193 8888`

and see if get connected.

**Comment by cespa92** [comment]
@DanielnetoDotCom Appears the next info

cespa@instance-1:~$ telnet 104.196.137.193 8888
Trying 104.196.137.193...
telnet: Unable to connect to remote host: Connection refused
cespa@instance-1:~$

**Comment by DanielnetoDotCom** [comment]
Looks like your command `php /[path-to-YouPHPTube]/plugin/LiveChat/chat-server.php` is not working or you have something blocking port 8888 (a firewall or a proxy)

**Comment by cespa92** [comment]
Yes is my IP... What Can I do for solve it?

**Comment by cespa92** [comment]
I solved the problem, thanks @hersche @DanielnetoDotCom @mikweb2017
