### ISSUE TITLE
CHANGE http://ipserver/YouPHPTube to http://mydomain.com

### ISSUE THREAD

**Issue by cespa92** [DanielnetoDotCom/YouPHPTube#775]
Hello, 
- I installed YouPHPTube here: http://35.237.194.67/YouPHPTube/ - Now I want change that URL with IP to my domain http://video.mydomain.com

- And too change the encoder URL http://35.237.194.67/YouPHPTube-Encoder, http://encoder.mydomain.com

I use for DNS Managament of my domain: Cloudflare -  Really Thanks!

**Comment by hersche** [comment]
For both installations, check "videos/configuration.php" and replace the ip with your domain there.

**Comment by cespa92** [comment]
@hersche I see

- I changed the streamer url to http://videos.peruanosdecorazon.pe/YouPHPTube/ and I can't do a live video with that (Error on OBS: Failed to connect server) - and How can I change to only http://videos.peruanosdecorazon.pe

- I changed the encoder url to http://encoder.peruanosdecorazon.pe/YouPHPTube-Encoder/ It works, but I deleted from Allowed sites from Panel and only added http://videos.peruanosdecorazon.pe/YouPHPTube/ - and now I can not see the admin panel with all the tabs (For example for edit Allowed sites) How can I restore the admin panel -  and for end How can I change to only url http://encoder.peruanosdecorazon.pe

With that changes I can open the encoder and streamer with both domains at the same time http://videos.peruanosdecorazon.pe and http://encoder.peruanosdecorazon.pe - How can I solve that too?

Thanks,

**Comment by hersche** [comment]
> I can't do a live video with that (Error on OBS: Failed to connect server)
i personaly do not use the live-stuff, but do you edit the parameters at http://videos.peruanosdecorazon.pe/plugins again? they eventualy need to be same as streamer-url? not shure.

> It works, but I deleted from Allowed sites from Panel and only added

there is a allowed sites-part in the configuration.php (the one you found) - but there are also database-rows for the users of the encoder - and there, you have to change the url also, i think.

**Comment by cespa92** [comment]
@hersche I reinstalled all, and nothing, doesn't work the LIVE and The Chat...

**Comment by cespa92** [comment]
Hello again, I desactivated ''DNS and HTTP Proxy (CDN)'' from Cloudflare, and now it's working... Well, it's solved!... thanks @hersche

**Comment by hersche** [comment]
> I desactivated ''DNS and HTTP Proxy (CDN)'' from Cloudflare

thanks for that feedback, cloudflare seemed to make problems once, if this is solving them, that's great.

before i close the commit: can you do a quick test if you can change the avatar of your user?
it seemed to fail once, with cloudflare, maybe out of another reason, but that would be nice to know.

**Comment by mikeshoe** [comment]
Is it not possible to rerun the install setup wizard?

**Comment by DanielnetoDotCom** [comment]
Try this https://tutorials.youphptube.com/video/fix-youphptube-url-after-move-server-location-and-ip

**Comment by cespa92** [comment]
@hersche Sorry, I didn't see your reply... but I can change the avatar image--- really thanks friend!

**Comment by Zixim** [comment]
So, I followed the video as posted by @DanielnetoDotCom .
After the change of URL, the admin user is no longer admin for Encoder.
How to correct this plz ?

**Comment by Zixim** [comment]
![image](https://user-images.githubusercontent.com/7814664/47952998-83caac00-df77-11e8-9347-1f88a5d346df.png)

Never thought of looking at the streamers table ...
hmm...so i should delete id 1 & id 2, right ?

**Comment by DanielnetoDotCom** [comment]
you can delete or make the isAdmin = 1 and you will be fine

**Comment by DanielnetoDotCom** [comment]
For those who want to use CDN/Cloudflare https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Using-CDN-for-Videos-Only

**Comment by kemoi-kiptoo** [comment]
Hi @DanielnetoDotCom I didn't understand how this was done.. could you kindly give a step by step procedure on how to go about?
