### ISSUE TITLE
How Can I Install FFmpeg on my Wamp Server?

### ISSUE THREAD

**Issue by CharlesChidozie** [DanielnetoDotCom/YouPHPTube#776]
I have tried to install FFmpeg with the command Line provided but it seems the command line only works in Linux/Ubuntu.

**Comment by hersche** [comment]
From the README
    Streamer can be installed on any Server, including Windows, but the encoder and Livestream should work fine on any Linux distribution.

FFmpeg is part of the encoder, so we do not support this, because it can get difficult and buggy.
