### ISSUE TITLE
cheaper long term storage options for s3 plugin

### ISSUE THREAD

**Issue by OhioVR** [DanielnetoDotCom/YouPHPTube#777]
Greetings! I noticed you have an s3 storage plugin and I have some questions. I'm not really very familiar on how s3 storage works but I noticed it had some lower cost options like glacier storage. It would be cool if I could have video files that are seldom watched put in the cheaper glacier storage as long as it is possible to retrieve it fast enough that the user doesn't run away. I'm not really sure how all this works so maybe the very nature of this is impossible but would be great if it were possible!

**Comment by DanielnetoDotCom** [comment]
For now, if you choose S3 storage, all your videos will he hosted there. also they will be played direct from there.
and yes this plugins support any server S3 compatible. also it was tested with success on https://wasabi.com/, but for your information, the connection was intermittent, that is why I always recommend Amazon S3

**Comment by OhioVR** [comment]
Does the plugin have any way of archiving inactive videos? I haven't used the plugin or s3 I am curious about its capabilities.

**Comment by OhioVR** [comment]
I see glacier storage can be quite complex and the billing for it can be disastrous if miscalculated. https://medium.com/@karppinen/how-i-ended-up-paying-150-for-a-single-60gb-download-from-amazon-glacier-6cb77b288c3e

So then, maybe forget that option. My question though is this: is s3 storage and retrieval costs competitive besides the "bottomless" aspect of it? How much does it really cost in practice? What kind of 'gotchas' could there be?

**Comment by DanielnetoDotCom** [comment]
To be honest AWS S3 is unpredictable, but is cheaper then a large storage.

But I have costumers being billed 3 USD month, and I have costumers with a bill about 50 USD month it depends.

Wasabi has the best prices out there, but I think they need to be more stable.

**Comment by OhioVR** [comment]
Thanks Daniel! $50 isn't much money.. Could I see a link to that site? If not no biggie

**Comment by DanielnetoDotCom** [comment]
The 50 USD was this one https://youtubehw.com he has over 150 k small videos . I think the price was regarding the number of objects . So he decides to use the hard drive instead the S3

**Comment by OhioVR** [comment]
Ok thanks for your help!

**Comment by OhioVR** [comment]
BTW if the link you gave is no longer s3 based can I see a website that is s3 based so I can gauge it's performance? Thanks!

**Comment by DanielnetoDotCom** [comment]
Yes as I have mention above he decides to move it back

**Comment by OhioVR** [comment]
At this time s3 is the cheapest for "bottomless" storage. It might not offer decent enough performance to be practical but perhaps a special cdn could speed it up.

**Comment by DanielnetoDotCom** [comment]
Do you guys know https://www.backblaze.com/?

I am working in a plugin for it (Like S3 plugin)

looks like a cheaper solution then S3

**Comment by OhioVR** [comment]
Hey that's a cool idea. I heard about backblaze but didn't think it could be practical for something like video. Maybe it can be accelerated with a cdn.

**Comment by OhioVR** [comment]
Oh didn't realize how expensive CDNs are. It would still be great if you could stash unpopular videos in Backblaze and then retrieve them on demand (user sees a progress bar as it is being called up). Your ssd storage could be more like a video cache than simply storage for videos.
