### ISSUE TITLE
NGINX live streaming performance questions

### ISSUE THREAD

**Issue by OhioVR** [DanielnetoDotCom/YouPHPTube#778]
I know this is really an NGINX question more than it is a YouPHPTube question but I assume this community has experience with the matter. If I have one live stream, how many clients can I get on a typical industry standard vcpu like from DigitalOcean (like a 720p stream). Also is it harder for the server to handle multiple different live streams than just one besides the obvious bandwidth costs?

**Comment by DanielnetoDotCom** [comment]
I had experience that when you got to much connections watching a live stream, it consumes memory RAM, not only bandwidth

**Comment by OhioVR** [comment]
Good to know. So it is more memory constrained than CPU constrained?

**Comment by DanielnetoDotCom** [comment]
For Livestream I think so

**Comment by OhioVR** [comment]
I recently read somewhere that an nginx rtmp server can serve perhaps upto 600 streams with a 2 VCPUs and a gig of ram. right now I'm streaming one stream and its just using 2% of a core and 10 megs of ram. So pretty good actually. It takes a lot of effort to come up with more than a couple hundred viewers for a unique live stream. I made apps for a local tv station and he rarely gets more than 10 concurrent users.
