### ISSUE TITLE
one video quality only

### ISSUE THREAD

**Issue by OhioVR** [DanielnetoDotCom/YouPHPTube#779]
Can I enforce a single, medium video quality, for playback and encoding? I want to save on storage costs.

**Comment by DanielnetoDotCom** [comment]
yes, go to customized advanced plugin and disable the other solutions

![image](https://user-images.githubusercontent.com/18009293/41726211-092501a6-7548-11e8-8679-ea004b191725.png)

**Comment by OhioVR** [comment]
Thank you very much!

**Comment by DanielnetoDotCom** [comment]
great :)
