### ISSUE TITLE
Remember Page When Editing

### ISSUE THREAD

**Issue by Dradden** [DanielnetoDotCom/YouPHPTube#78]
Currently, if you edit a video on page 4 and save it forces you back to page one which is a bit of a hassle. Would be great if you stay on the same page when saving an edit.

**Comment by DanielnetoDotCom** [comment]
This is a limitation of bootgrid component, I want that too but we could not fix it yet

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
