### ISSUE TITLE
a quick plugin mod request please

### ISSUE THREAD

**Issue by joey2354** [DanielnetoDotCom/YouPHPTube#780]
The plugin VideoLogoOverlay has the same size image on desktop as it does mobile, meaning it doesn't go mobile responsive with the vid and looks huge ! 

Could i get a mod on this please ? i'm no coder but i can add stuff to my php templates etc if needed if that will be easier.

I'm thinking just **#main-video > div:nth-child(3){width:20%;}** will work but i don't know where to put it in css templates. 

thank you

**Comment by hersche** [comment]
that's not my plugin(not know it), but for a first, you can place it in your header via 

siteconfiguration -> script code -> head code (textfield)

for a first.

it would look like this:

`<style>#main-video > div:nth-child(3){width:20%;}</style>`

the style-tags are needed. hope that help you for workaround it.

**Comment by joey2354** [comment]
thanks buddy but that didn't work, i tried getting the other selectors 
#main-video > div:nth-child(3) > a > img
#main-video > div:nth-child(3) > a

but none worked ... i put !important in but no joy ..... any other ideas ?

**Comment by DanielnetoDotCom** [comment]
I sent an update, update your youphptube files and the logo overlay should be responsible

**Comment by joey2354** [comment]
thank you .. but how do i update them please  ?






[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
06/27/18,
5:02:05 PM

**Comment by hersche** [comment]
replace everything except your videos-folder with the files from github.

since it's done, i close it.
