### ISSUE TITLE
Non public video still listed on frontpage.

### ISSUE THREAD

**Issue by Criptos** [DanielnetoDotCom/YouPHPTube#781]
Correct me if I'm wrong. 
The idea of the public swith is that, if off, doens't show on public lists... 
![image](https://user-images.githubusercontent.com/4574233/41737567-491aab3c-7555-11e8-84aa-0a311d6b3b62.png)
I see the post: 
public:true
doesn't matter if I turn off the switch, but I did't find any reference to 
$_POST['public'] in 
videoAddNew.json.php  
 
How does it  should work

**Comment by Criptos** [comment]
OOOOOOooooo... I understand... 
When you make a video 'private' it doesn't really is private, you must assign it to a group... 

Can I modify it so you don't need to assign it to a group, but also get a 'private'  now that we have routes outside .httaccess ? :)

**Comment by DanielnetoDotCom** [comment]
I see, sure it need some tweeks
