### ISSUE TITLE
Any ideas of how to share the video player like youtube to facebook?

### ISSUE THREAD

**Issue by Criptos** [DanielnetoDotCom/YouPHPTube#782]
Currently, when you share to facebook, you share an image, and that image takes you back to the site and then play the video. 

Does anyone know or have an idea how to embed  it? 
 
I belive is another 'can't do' because facebook doens't want to... 
if it so? is there a way to share de 'gif' ?

**Comment by DanielnetoDotCom** [comment]
maybe there is an option to upload videos to youtube, I dont think is a good idea because you will take off users from your site, I think people wants to use facebook to drag visitors from there.

About the GIF, is possible to use animated gifs on facebook? I dont think so.
