### ISSUE TITLE
Navigation numbers missing

### ISSUE THREAD

**Issue by Andiweb87** [DanielnetoDotCom/YouPHPTube#783]
In specific category the navigation bar with numbers like the home page is missing.

**Comment by DanielnetoDotCom** [comment]
Hi, I am not sure what is missing, can you please screen shot to help up?

**Comment by Andiweb87** [comment]
the pagination numbers from 1 to 10 in categorys section , like the main page

**Comment by DanielnetoDotCom** [comment]
Can you please share your link here?

**Comment by Andiweb87** [comment]
https://www.ustream.al/cat/world-cup-2018/

**Comment by DanielnetoDotCom** [comment]
It is working here, 

https://demo.youphptube.com/cat/music

Please try to update your version and see if it works

**Comment by Andiweb87** [comment]
ok, the update fixed the issue . thank you all :)

**Comment by DanielnetoDotCom** [comment]
Great
