### ISSUE TITLE
Missing: "Report spam"-button

### ISSUE THREAD

**Issue by chinli12** [DanielnetoDotCom/YouPHPTube#787]
It is good for video to have flag option which anable viewers to report inappropriate content

**Comment by hersche** [comment]
mh, you mean like "your age needs to be 16+ for this video" or 18+?

i am not shure if this is better done as plugin or as core-change..

**Comment by chinli12** [comment]
To report sex content, or abusive videos by user

**Comment by hersche** [comment]
ah, ok, that can be done as a plugin

**Comment by chinli12** [comment]
Please do it fast is very important for video sharing website
