### ISSUE TITLE
Maximum file size and upload error

### ISSUE THREAD

**Issue by alialpha123** [DanielnetoDotCom/YouPHPTube#79]
how to increase maximum file size which is 64mb by default and its stuck here from past 2 hours
http://prntscr.com/g5b13k

**Comment by DanielnetoDotCom** [comment]
You need to change the php.ini file

For example, to increase the limit on uploaded files to 100 MB:
Add the below to the relevant php.ini file (recommended, if you have access). Note that for some hosts this is a system-wide setting. 
```
upload_max_filesize = 100M
post_max_size = 100M
```

**Comment by alialpha123** [comment]
i changed values from php.ini still this is coming when i open uploader
Your maximum file size is: 64.00MB

**Comment by DanielnetoDotCom** [comment]
Did you restart apache?

**Comment by alialpha123** [comment]
yes

**Comment by alialpha123** [comment]
im using xampp atm

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by miaoichi** [comment]
Still come across the issue. please help.

upload_max_filesize = 1024M
post_max_size = 1024M
![image](https://user-images.githubusercontent.com/5718907/135602980-a5bd09d2-4081-434a-a727-0e5a0176c444.png)

**Comment by DanielnetoDotCom** [comment]
Definitely, you are missing something. maybe reboot apache

**Comment by miaoichi** [comment]
Try reboot the ubuntu and apache, still can see. Any further action needed? Thx.

**Comment by miaoichi** [comment]
Found the root cause, there are two php.ini files in my system. Thanks.

/etc/php/7.4/apache2/php.ini <--- wrong one.
/etc/php/7.4/fpm/php.ini <--- correct one.
