### ISSUE TITLE
Several blank pages

### ISSUE THREAD

**Issue by MarkOnDuty** [DanielnetoDotCom/YouPHPTube#797]
Installed on a fresh Ubuntu 16.04 container, I'm seeing several blank pages where I'm expecting more. The most troublesome is the siteConfigurations page for YouPHPTube.

I'm also having no luck creating new accounts.

Is there something obvious that could be causing these problems?

**Comment by hersche** [comment]
can you provide a address of your installation and the videos/youphptube.log-file?

also, did you read the Troubleshoot-guide at

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Admin-manual

?

**Comment by hersche** [comment]
and also, did you do those steps for shure?

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Message-when-rewrite-is-not-set

**Comment by MarkOnDuty** [comment]
Unfortunately, it's being installed on a private network.

I've read through the troubleshooting guide.

Just worked through an install on 18.04. With the exception of having to set the root MySQL user's passphrase, everything worked. There are no blank pages and I'm able to create users. I'm not sure what I did on the 16.04 install to get it munged up. If I get a chance, I'll try it again.

I consider this issue closed.

**Comment by MarkOnDuty** [comment]
Yes, I'm sure that I did. I'll try to repeat the install, carefully, and see if I can get the problem to manifest. If it doesn't, all is well.

**Comment by hersche** [comment]
is the problem still exists?

can you provide me your videos/youphptube.log-file?

**Comment by MarkOnDuty** [comment]
If I get a chance over the next day or two, I'll repeat a 16.04 install and check. I did not run into it on an 18.04 install.

**Comment by hersche** [comment]
in #799 it worked the same way, so i think, it was the bug that's solved now.

feel free to retry it, but don't make yourself too much work/stress with this.
