### ISSUE TITLE
Search for channels

### ISSUE THREAD

**Issue by zoxee** [DanielnetoDotCom/YouPHPTube#798]
Dear Daniel, Lieber Hersche,

First off, Congratulations to both on the outstanding job on this script!
After setting up my nginx super ubuntu server, the installation of YPT was flawless.
Everything is just working as it f*cking should. A masterpiece of well-written,
well designed object oriented PHP code I love it so much that i thought
i'd support you both, so i bought all the plugins last week :)
I miss only one crucial function though, the ability to search for a specific channel
outside of having to browse through all of them or finding it by luck.
Could one of you add (complete maybe) the db query of the top search so
channel names could be searched for, or maybe add a second search input
at the top to search for channels and send it to me ?

Thanks in advance
Cheers,
zox

**Comment by hersche** [comment]
Thanks for the compliments, nice when everything works as it should :+1: 

> Could one of you add (complete maybe) the db query of the top search so
channel names could be searched for, or maybe add a second search input
at the top to search for channels and send it to me ?

That make sense and is possible, but there's also another question to me: do you use the livesearch-plugin or the classic search (press enter, load a new site)? both searches should be kind of same in the end, but for a first, the usual search is much easier / faster for implement, i think.

**Comment by zoxee** [comment]
Exactly. I started using the live search, but it's a mess on a phone :/
So now i'm back on the standard search. Could you do that for me quick ?

It's the only function i need before launching the site.
After me spending almost 250 bucks, that would be awesome of you
if you could do it fast.

Cheers,
zox

**Comment by hersche** [comment]
>  I started using the live search, but it's a mess on a phone :/

that's good to know.. i will get a closer look there.

> After me spending almost 250 bucks, that would be awesome of you
if you could do it fast.

anyway, it's a new feature-request - but it's usefull for the open project. should be a small thing, so i will have a look there soon (1-3 days).

> PS: If you need all the PayPal transaction ID's proving that i purchased, just tell me :)

that's difficult, because it works via @DanielnetoDotCom . 

> By the way, you are from Switzerland right ? We can talk German or French if you prefer

yes :) i talk basicly german, but that can make it difficult to other readers. For discussions in german, i would prefer e-mail (vinzenz.hersche@gmail.com), we can bring the conclusions back here in en..

**Comment by zoxee** [comment]
Fantastisch, sende dir gleich eine email so das du mir zurückschreiben kannst.
Ich bin echt froh dich getroffen zu haben und bin dankend für deine Willigkeit
mir so kurzdristig zu helfen. Schöne Grüße und bis die Tage.

**Comment by hersche** [comment]
passt, kein ding und bis gleich ;)

**Comment by mikweb2017** [comment]
es wird deutsch gesprochen  hier? sehr  gut zu wissen

**Comment by hersche** [comment]
yes, but since here are people from all over the world, i prefer to still speak english here.

but nice to know we can speak more direct together.

**Comment by hersche** [comment]
do i assume right, most people are using the gallery-plugin here? that's a important point for me to start it.

**Comment by zoxee** [comment]
Oh i missed your question, so much work here  :(
Yes i use the gallery plugin to display my content.

**Comment by hersche** [comment]
ok. Daniel said he would like to do this, on the gallery-plugin and in this week. Hope, this is fine for you :)

**Comment by DanielnetoDotCom** [comment]
Ok, the basic search now searches on Gallery (name and about) as well

**Comment by zoxee** [comment]
Fantastic! :)

**Comment by DanielnetoDotCom** [comment]
Great
