### ISSUE TITLE
offline installation possible?

### ISSUE THREAD

**Issue by bytepoet** [DanielnetoDotCom/YouPHPTube#80]
I installed 4.0Alpha in a virtual machine and it was great!  The streamer and encoder worked flawlessly (from what i could see) but then my internet died out, as it normally does, and the youPHPtube seemed to be reaching out for assets via the internet.  

Is there any intention to make this youPHPTube sustainable offline, or will there always be a dependence on assets from the internet to display the web page and view offline videos?

**Comment by DanielnetoDotCom** [comment]
Hi

Instead install 4.0Alpha install  the master branch it is already a newest version 4.
it suppose to work offline, can you give me more details why it was not working?
but for not public websites you need to install your own [encoder](https://github.com/DanielnetoDotCom/YouPHPTube-Encoder) in your private network

**Comment by bytepoet** [comment]
git cloning the master branch leaves me with a 3.4 installation.  Going to
the update menu and clicking "update now" spills out Alter table commands
that appear to fail, yet the upgrade seems to have succeeded to 4.0.

**Comment by DanielnetoDotCom** [comment]
I see, I fixed it couple hours ago
