### ISSUE TITLE
HOWTO: Getting rid of the URL path

### ISSUE THREAD

**Issue by MarkOnDuty** [DanielnetoDotCom/YouPHPTube#802]
Let's say I've set up YouPHPTube to be accessible at `tube.example.org/YouPHPTube` and the encoder at `tube.example.org/YouPHPTube-Encoder`. Let's also say that I want them at `tube.example.org` and `tube-encoder.example.org`, with no path in the URLs.

I think I've got this working. 

For the streamer, I had to do the following:

- add a `ServerName` of `tube.example.org` to the virtual host and change the `DocumentRoot` to `/var/www/html/YouPHPTube`
- change the `webSiteRootURL` in `YouPHPTube/videos/configuration.php` to `http://tube.example.org/`
- in the configuration page, on the advanced configuration tab, changed the Encoder URL to `http://tube-encoder.example.org/`

For the encoder, I've done the following:

- added a new `VirtualHost` with a `ServerName` of `tube-encoder.example.org` and a `DocumentRoot` of `/var/www/html/YouPHPTube-Encoder`.
- changed the `webSiteRootURL` in `YouPHPTube-Encoder/videos/configuration.php` to `http://tube-encoder.example.org/`
- created a CNAME record pointing from `tube-encoder.example.org` to `tube.example.org`
- use whatever you like to edit the `youPHPTube-Encoder` database, changing the `siteURL` column in the `streamers` table to `http://tube.example.org` and `http://tube.example.org/` (notice the slash), and the `allowedStreamersURL` column to `http://tube.example.org/` in the configurations table.

The streamers seems to work fine after this procedure. I'm about to upload a test video to the encoder to make sure it works.

Do you see anything that I've missed?

**Comment by hersche** [comment]
mh, i would simply move the whole content of YouPHPTube into the root-folder

    mv /var/www/html/YouPHPTube/* /var/www/html/
    mv /var/www/html/YouPHPTube/.htaccess  /var/www/html/
    mv /var/www/html/YouPHPTube/.git  /var/www/html/ # hidden files sometimes get lost

    rm -r /var/www/html/YouPHPTube # clean up

but as you start to edit the configuration, this maybe does not work at the moment (need to reset the apache-config's).

anyway, that's just one solution, doing it via config is simply another way, but i have no direct answer to that.. 

> The streamers seems to work fine after this procedure.

so, is there any problem or you simply wanted to recheck? recheck your apache-configs is basicly not our job ;)

there are lots of tutorials for such things.. specialy for apache..

**Comment by MarkOnDuty** [comment]
Sure, moving the contents of YouPHPTube into /var/www/html/ could work.

There's no real problem here. I guess it would be nice to see something in the documentation to cover this. I couldn't find anything really related to it, so I wanted to at least make sure that it was covered in an issue for anyone struggling.

Once I've confirmed that it works, I'll close the issue.

**Comment by hersche** [comment]
it's just a stupid of me, as i didn't see the HOWTO in the title.

i will integrate it into our docs, i think, thanks for the manual :+1: 

maybe i will provide both solutions, not shure. both are kind of proper :)

**Comment by MarkOnDuty** [comment]
No worries. We're all in it together.

YouPHPTube-Encoder was failing after uploading a file. I was getting an error in the log that pointed me to an issue with name resolution. I've changed the procedure above with that in mind.

I've got an issue with the "Download video" feature. The browser complains that the file is not found. However, I'm not sure if that worked before I made the above changes. For my purposes, I can just turn it off, but I'm happy to look into it further, perhaps in another issue.

**Comment by hersche** [comment]
> I've got an issue with the "Download video" feature.

do you have the video-resolution-switcher-plugin enabled?

maybe i have to modify the download-button to respect this. as i implemented it, i didn't know / tried my things with that plugin.
