### ISSUE TITLE
Disable logout or increase logout time

### ISSUE THREAD

**Issue by elotidesigns** [DanielnetoDotCom/YouPHPTube#803]
Please how can I disable logout or increase logout time. Was uploading a video and before it finished, I was already logged out which means I have to start afresh again.
It's not nice at all.

Please how can I disable logout or increase logout time 

Thanks.

**Comment by hersche** [comment]
go to site-configuration -> advanced configuration (tab) and edit the option **Session Timeout in seconds**.

with this, you can increase the time until it's logging your users of. 

but i agree, it need kind of refresh (visit a site = refresh the timer till logoff) and also a "remember me"-checkbox on the login would be nice.

**Comment by elotidesigns** [comment]
I have actually increased it from there. But to no avail. Logs out after about 20 mins. Increased it to one day but still logs out after about 20 mins.
