### ISSUE TITLE
Can i add VideoResolutionSwitcher to live stream 

### ISSUE THREAD

**Issue by 3bkry** [DanielnetoDotCom/YouPHPTube#804]
can i add VideoResolutionSwitcher to live stream ?
How to do it ?

**Comment by DanielnetoDotCom** [comment]
Sorry, the live stream does not support multiple resolutions yet

**Comment by ashrafpro** [comment]
I vote up for VideoResolutionSwitcher for live stream, I am streaming in 4K and some audience still using 3G mobile connections.

**Comment by DanielnetoDotCom** [comment]
hi, the livestream user HLS, what by default has only one resolution.

the VideoResolutionSwitcher is for MP4 videos only.

but you can configure the adaptive bitrate to have multiple resolutions on your livestream.

please check this...
https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Hello Daniel , I've been using it for the first day you implemented this function , working fine . I was wondering if it's possible to integrate '' Automatic encoding process (HLS Only) '' on it . https://github.com/WWBN/AVideo/wiki/VideoHLS-Plugin#automatic-encoding-process-hls-only
