### ISSUE TITLE
Not reading .ini file

### ISSUE THREAD

**Issue by Starwide** [DanielnetoDotCom/YouPHPTube#805]
One of the requirements that the script asks is to change the .ini file from 5mb to at least 500mb. Yet after several attempts it simply says that it has yet to read that it has happened. It won't allow any videos to be uploaded until it dose.

**Comment by DanielnetoDotCom** [comment]
Sorry what is the problem?

**Comment by hersche** [comment]
is it about php.ini?

1. that's on your admin-part, so consider read tutorials of your concrete system
2. did you tried to restart your apache? if you are on ubuntu or debian, maybe **service apache2 restart** helps?
3. we need more info - what system or host you use, what file you have edited (path), which concrete line you edited and how it looks now. which concrete error leads you to what? if we don't know what concrete you talk about, we cannot help you.
