### ISSUE TITLE
backup-plugin

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#807]
usually kopie the site with the plesk utility I just have to change the parameters in the config.php

then the first page and exact copy of the other but if I use the backup plugin something always  does not work

{"error":true,"msg":"The URL is Inactive","url":"https:\/\/you-tube.eu\/","key":"9c308e4c4fe71c4561034b71cd64d0bb","sqlFile":""}
things I was wrong?

original
https://you-tube.eu
kopie
https://live.mikweb.eu/

maybe i not understand how this plugin works :(

**Comment by DanielnetoDotCom** [comment]
Hi

This plugin is under development I will release a documentation and the final release soon

**Comment by DanielnetoDotCom** [comment]
@mikweb2017 please update your files and read this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Clone-Site-Plugin

and please tell me that do you think

**Comment by DanielnetoDotCom** [comment]
ok i will add the popup

**Comment by mikweb2017** [comment]
![bildschirmfoto 2018-06-30 um 22 03 55](https://user-images.githubusercontent.com/30271757/42128691-9cfaa2ee-7cb1-11e8-869d-55eb4d126c49.png)

thank you

**Comment by DanielnetoDotCom** [comment]
Great
