### ISSUE TITLE
( Request feature)

### ISSUE THREAD

**Issue by loso20p** [DanielnetoDotCom/YouPHPTube#809]
any chance you guys can add a feature to the player or plugin  for would you like to resume where you left off on this video.

so basically a resume popup so users can continue where they left off on a video

**Comment by hersche** [comment]
i have this done with offline-storage (not even need a login) and works for multiple videos.

i would sell it in kind of presale, where you i can use also your feedback about. for that, e-mail me via vinzenz.hersche@gmail.com

a demo is here: https://rewrite.codebea.ch/cat/default/video/tut-eine-schusswunde-weh-wer-nicht-fragt-stirbt-dumm-arte-

start the video, click on the button under the video (blue, "Save position local"),

then it should be shown in the dropdown beside the logo (on top).

for load or delete a video, choose it from the list beside the logo.

only one position per video can be saved.

the save is bound to the browser (offline-storage), not to a user. if you use another device, there is no entry (or others). on this point, the pro is: when the user lost connection, he still can save (tested). the contra is the mobility (respective various devices).

with all that points, if you are interessted in it, e-mail me
