### ISSUE TITLE
Version 4.0

### ISSUE THREAD

**Issue by mariu1986** [DanielnetoDotCom/YouPHPTube#81]
Hello, how i can download version 4.0 ?
I downloaded it today and i got version 3.4 ...

**Comment by DanielnetoDotCom** [comment]
Download it here https://github.com/DanielnetoDotCom/YouPHPTube

**Comment by mariu1986** [comment]
File name is "YouPHPTube-master"
Shouldn't be "YouPHPTube-4Alpha" ?

**Comment by DanielnetoDotCom** [comment]
YouPHPTube-master is fine, it is the latest update, 4Alpha was an test version

**Comment by mariu1986** [comment]
Thanks !

**Comment by mariu1986** [comment]
Error during instalation:

Cannot delete or update a parent row: a foreign key constraint fails (`mar1986`.`configurations`, CONSTRAINT `fk_configurations_users1` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)

**Comment by DanielnetoDotCom** [comment]
What are you trying to install, the encoder or the streamer?
Could you please drop the database and try again?

**Comment by RadekHavelka** [comment]
I am getting following errors (installed this morning, so current versions both encoder and streamer) :

```
[12-Aug-2017 17:06:00 UTC] YouPHPTube-Encoder reading file from /YouPHPTube/YouPHPTube-Encoder/videos/3_tmpFile_converted.webm
[12-Aug-2017 17:06:00 UTC] YouPHPTube-Streamer answer {"error":true,"msg":"Permission denied to receive a file: Array\n(\n)\n"}
```

and in another file 

```
[12-Aug-2017 16:56:40 UTC] stdClass Object
(
    [error] => 1
    [msg] => Execute code error Array
(
)

```

MyVideos page shows another error
`Warning: A non-numeric value encountered in /YouPHPTube/objects/functions.php on line 278`

what am I doing wrong?

**Comment by DanielnetoDotCom** [comment]
about this error "Permission denied to receive a file" i have update the streamer couple hours ago, regarding this error. I recommend you to update the code

**Comment by mariu1986** [comment]
I copied all files from link https://github.com/DanielnetoDotCom/YouPHPTube to my FTP serwer,
during instalation i have errors, instalation you can see on link 👍 
http://mar1986.nazwa.pl/install/index.php
database name and user is mar1986
database pass is Mar1986!

**Comment by DanielnetoDotCom** [comment]
I will try here

**Comment by DanielnetoDotCom** [comment]
Can you please update your files again, I found something

**Comment by mariu1986** [comment]
update all wiles on FTP or only some ? i am asking because copying all new files is about ... 1 hour

**Comment by mariu1986** [comment]
*files

**Comment by RadekHavelka** [comment]
automatic update doesnt work, doesnt detect new version ...

**Comment by RadekHavelka** [comment]
there might be an error in setting up the encoder, as in the bottom of the install page you fill in the name and password of the streamer site, the password get saved to the database unencrypted.

**Comment by RadekHavelka** [comment]
when you try to "DOWNLOAD" an empty video URL, you get an error 

`"We could not get the title of your video (WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.) go to https://github.com/DanielnetoDotCom/YouPHPTube/wiki/youdtube-dl-failed-to-extract-signature to fix it"`

I suggest user will not be able to click on the button unless the URL is entered so no horrible error message appears :)

**Comment by RadekHavelka** [comment]
it doesnt work ... i download a video, it gets converted, and then nothing, its either not posted to the streamer site, or it appears in my videos, but shows "status: encoding" ... log still shows that 

`Permission denied to receive a file: Array\n(\n)\n`

error :(

**Comment by DanielnetoDotCom** [comment]
What is your website URL?

**Comment by RadekHavelka** [comment]
I am trying to debug, but somehow I'm stuck on the posting of parameters between encoder and streamer. it seems to me it is not working correctly (not saying the code itself is wrong, Im on Centos 7 which might be somehow different from your environment). I am pretty sure clicking on the SEND NOTIFY button in encoder doesnt work (as there is only ID of the video passed, but no credentials, so the USER object cannot be created from username and password). I will try to debug it completly and let you know.

**Comment by RadekHavelka** [comment]
If I might have several comments to the security of the code
- get rid of MD5 hash, its not secure any more. See http://php.net/manual/en/faq.passwords.php#faq.passwords.fasthash
- use params in mysqli code. Do not join strings like username, password directly into SQL command, its also insecure.

**Comment by DanielnetoDotCom** [comment]
Ok, we will take care of it, thanks
