### ISSUE TITLE
Autoupdate  Git Repo?

### ISSUE THREAD

**Issue by mikweb2017** [DanielnetoDotCom/YouPHPTube#812]
can you add an automatic update option
with a button or the like or otherwise a cron job to update via git repo?

**Comment by DanielnetoDotCom** [comment]
I think it will be perfect but in most of the cases we will need sudo rights.
I did not test it yet, but I fell like it will not work.

**Comment by mikweb2017** [comment]
you're right with php you have to have sudo rights.
I solved it with a shell script and cron job

**Comment by DanielnetoDotCom** [comment]
Great

**Comment by timmayy** [comment]
@mikweb2017 

care to share the script??
