### ISSUE TITLE
Direct video link mkv file

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#813]
Hi 
it is possible to play mkv file to direct video link.

**Comment by hersche** [comment]
hey,

no, it's simple not possible. we use html-5 videos and they only support mp4 and webm for video. thats a default, we can't change, sorry.

**Comment by gujarraju** [comment]
its ok thanks

**Comment by hersche** [comment]
ok, i close it then :)
