### ISSUE TITLE
Browser rendering issues

### ISSUE THREAD

**Issue by ThatCubedPerson** [DanielnetoDotCom/YouPHPTube#814]
https://i.imgur.com/ui5N66p.png This is what happens when another person opens up my YouPHPTube page. I need help fixing this. Can anybody help me?

**Comment by ThatCubedPerson** [comment]
That didn't work... thanks for the solution though.

**Comment by ThatCubedPerson** [comment]
I figured out something... I got an error 404 in all of the CSS files when I switched over to the network tab. What can I do to fix this?

**Comment by ThatCubedPerson** [comment]
![image](https://user-images.githubusercontent.com/37851079/42136008-8e2480b0-7d19-11e8-9c2f-5acafc85dd14.png)

**Comment by hersche** [comment]
i see it!

you are on the IP-address only, but it try to get it from /YouPHPTube/-subfolder..

do you may have the url wrong in **videos/configuration.php**

can you recheck this and remove YouPHPTube from the url?

**Comment by ThatCubedPerson** [comment]
I decided to do a complete reinstall of YouPHPTube entirely, do I just take "YouPHPTube" out of the URL?

**Comment by hersche** [comment]
in videos/configuration.php replace

    $global['webSiteRootURL'] = 'http://10.0.0.109/YouPHPTube/';

with 


    $global['webSiteRootURL'] = 'http://10.0.0.109/';

or, if you reinstall, install it from begin in the root-directory..

**Comment by ThatCubedPerson** [comment]
If I were to reinstall it it says that the site URL is wrong whenver I change it to http://localhost/

**Comment by hersche** [comment]
it will remember the url you used to install, so better don't use localhost to install..

if you want to reinstall, you need to remove the videos-folder and config.

we can also provide support for this, for example via teamviewer and email (mine is vinzenz.hersche@gmail.com)

**Comment by ThatCubedPerson** [comment]
What's your teamviewer? Just in case.

**Comment by hersche** [comment]
i mean, you have to type the ip in your browser, not localhost, even if it's your maschine.

this is because it set the url in the config-file to the url you have used as you install.

if you install it with localhost in your browser, it will try get the ressources from localhost for all users, also those which are not on your computer.

for teamviewer, please email me, because this is a support-job then.

**Comment by ThatCubedPerson** [comment]
Ok. Thank you.

**Comment by hersche** [comment]
no problem, i hope you get it. let us know :)
