### ISSUE TITLE
html template

### ISSUE THREAD

**Issue by Criptos** [DanielnetoDotCom/YouPHPTube#815]
Is there a base html template to use to add more views?

**Comment by hersche** [comment]
you can use youphpflix, fbtube and gallery-plugin as a kind of template. youphpflixhybrid is to merge two "template-plugins", so depend on the site, it choose gallery or youphpflix.

if you do a such plugin, hold in mind we are working on upgrade to boostrap4 (there's a branch with that name), there is some stuff diffrent.

**Comment by Criptos** [comment]
OK, thanks... I'll wait for the update, then update the work I'm doing...
I'll user actualy user.php as a template, is relatively clean...

**Comment by hersche** [comment]
yeah, but with a plugin, you can easier update for example.

if it helps you, i think it's the most easiest to copy youphpflix to a new directory name (lets say **newplugin**), change the **YouPHPFlix.php** to **newplugin.php**, same for it's content, and after this, clear **view/firstpage.php** and rewrite it as you like..

**Comment by Criptos** [comment]
Thanks...
