### ISSUE TITLE
Thumbnails not displaying in themes

### ISSUE THREAD

**Issue by dforthman** [DanielnetoDotCom/YouPHPTube#824]
Thumbnails are not displaying when the following plugins are enabled:

Gallery
YouPHPFlix
Gallery+YouPHPFlix+YouPHPFlixHybrid

**Comment by DanielnetoDotCom** [comment]
I just try it on demo site and it works fine

**Comment by dforthman** [comment]
Could it be some of the plugins you have enabled? I did a fresh clone and install this morning and I'm still having the same issue.
http://www.ratstick.com/

**Comment by DanielnetoDotCom** [comment]
Looks like you have an error on resolution switch plugin, please download it again on easytube, there are some updates

**Comment by DanielnetoDotCom** [comment]
Another thing, are you sure your apache can write on your videos directory?
The file 
http://www.ratstick.com/videos/_YPTuniqid_5b3a78e48250f9.09791983_thumbsV2.jpg
is missing or maybe you have an error on the GD script. check your streamer log file
