### ISSUE TITLE
The automatic login in Encoder ... no longer executes it

### ISSUE THREAD

**Issue by tgd1973** [DanielnetoDotCom/YouPHPTube#828]
With the latest updates I can no longer login automatically in Encoder from Streamer...
What has changed in the code? I tried to look at your demo site ... Even if no additional code appears in the address bar from browser  ... login does it.
At my site / server it does not. Need to enable something else on the server?
My streamer and the encoder are two different servers.  The streamer is installed on server with VestaCP + CSF Firewall.
Thanks.

**Comment by mikweb2017** [comment]
I have the same request and in my case streamer and encoder are in the same server

**Comment by DanielnetoDotCom** [comment]
Hi

still automatic login, but you need to update the encoder.

**Comment by DanielnetoDotCom** [comment]
@mikweb2017 on demo site, I just tested and it is working with no problem

**Comment by mikweb2017** [comment]
@DanielnetoDotCom on demo site check if you log whit neu user oder whit social login

**Comment by mikweb2017** [comment]
ok after  update  work again for me

**Comment by tgd1973** [comment]
After updating the encoder it works also for me,  so you can consider it solved.
Thanks again.

**Comment by DanielnetoDotCom** [comment]
Great
