### ISSUE TITLE
In video ads, logo, avatars not saving.

### ISSUE THREAD

**Issue by itsflashpoint** [DanielnetoDotCom/YouPHPTube#830]
Hey there,

I seem to have an issue with saving.

Video ads:
I made a new campaign but when I press "Add video" the video URL link is disabled, and if I press "Add video" again nothing happens.

Logo/user avatars:

These don't save either. The picture does show up on the preview but when I click "Save" and refresh the page it goes back to the old YouPhpTube logo.

**Comment by DanielnetoDotCom** [comment]
Does the same happened on demo site?

Please check your javascript console.

**Comment by DanielnetoDotCom** [comment]
Hi

I mean with demo site this one https://demo.youphptube.com/

user: admin

pass: 123

about the Javascript check the console. I dont know why I can see many different ports on your code.

**Comment by itsflashpoint** [comment]
Yes. Sames issues on the demo website as well. Can't save logos, or set advertising videos.

**Comment by DanielnetoDotCom** [comment]
It  works for me on demo site, are you sure you are not using any script blocking ? What browser and version are you using?

**Comment by itsflashpoint** [comment]
Google Chrome Version 67.0.3396.99 (Official Build) (64-bit).

No scripts are blocked either.

**Comment by hersche** [comment]
i know you said no scripts are blocked. i think you have ad-blocker in mind?

it fooled me once and took me some hours..

**Comment by DanielnetoDotCom** [comment]
I think you have to look into your side, it is working here.

can you try in another computer in another network?

**Comment by itsflashpoint** [comment]
Nope adblock is disabled on my website.
