### ISSUE TITLE
Please how do i set up my AWS s3 amazone plugins

### ISSUE THREAD

**Issue by hypedboss** [DanielnetoDotCom/YouPHPTube#832]
Please how do i set up my AWS s3 amazone plugins
i have tried but don't know how to

**Comment by DanielnetoDotCom** [comment]
Please check https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Use-AWS-S3-on-YouPHPTube

**Comment by DanielnetoDotCom** [comment]
Hi, what do you mean S3 self host?

**Comment by hersche** [comment]
https://www.minio.io/

seems to be a open s3-variant.. fast-setup with docker, nice..

**Comment by abamilod** [comment]
https://www.minio.io/
For those who wants to deploy Amazon S3 compatible object storage on your own server (alternative to wasabi or amazon S3). Cheaper solution.

**Comment by DanielnetoDotCom** [comment]
@abamilod I have tested the S3 plugin with wasabi https://wasabi.com but they are not as efficient as AWS

**Comment by abamilod** [comment]
@DanielnetoDotCom yes wasabi traffic unlimited too many users abuse its bandwidth therefore the speed is not impressive. Please test the plugin with minio sever when you have the time. Any s3 client(android & win) seems working fine with minio.

**Comment by DanielnetoDotCom** [comment]
@abamilod 

minio, is not clear for me, I dont hire them to host the files correct? I have to install their app on my server, and I will manage the storage, is that right?

**Comment by abamilod** [comment]
@DanielnetoDotCom Yes correct. 
Minio is just an open source object storage server application. We can install it on our own server at no cost. The idea is on re-using s3 object storage api to our own server without changing existing application code which integrated with s3 service.
