### ISSUE TITLE
Password stored in plain text in youphptube encoder.

### ISSUE THREAD

**Issue by MPTMG** [DanielnetoDotCom/YouPHPTube#834]
After installing YouPHPTubeEncoder on Debian 9 Stretch I reviewed what was stored in the streamers table after setup. It has two entries reflecting the same site url and user but one entry has the password stored in plain text and the other stored as a hashed value.

Is this the way it is supposed to be or is there a bug?

**Comment by DanielnetoDotCom** [comment]
Hi

Probably the first login , for the first user (admin), it stores it plain (it is a bug and should be fixed)
But the next logins it will be stored encrypted

**Comment by MPTMG** [comment]
Okay. Thanks for the prompt response.

**Comment by nospi** [comment]
Just to add to this, for those who are security conscious it may be worth swapping out the MD5 encryption for SHA1 or SHA256.

**Comment by hersche** [comment]
we already discussed that and we will upgrade everything on oauth2 directly.. then, the use of scrypt-like algorythms for hashing is no problem, because we don't have to transmit any kind of password anymore.
