### ISSUE TITLE
Error sending emails

### ISSUE THREAD

**Issue by BoopMe** [DanielnetoDotCom/YouPHPTube#836]
Sending a test email from the configuration page gives me this error:
![hkkmvd2](https://user-images.githubusercontent.com/40902794/42403046-d9fdc60e-817e-11e8-9d62-ee380d59ab85.png)

All SMTP settings are correct as far as I can tell:
![vj7ryyu](https://user-images.githubusercontent.com/40902794/42403084-0d49fb22-817f-11e8-8e54-0e0eccb8afb7.png)

Even when trying to send an activation email to an account, an error gets thrown:
![vtczvrz](https://user-images.githubusercontent.com/40902794/42403095-255ac390-817f-11e8-99d5-1b5601495c5c.png)

I have no idea what's going on, and would love anyone's help

**Comment by DanielnetoDotCom** [comment]
Try TLS port 567
