### ISSUE TITLE
Uploading large files MKV = error

### ISSUE THREAD

**Issue by Hasharack** [DanielnetoDotCom/YouPHPTube#840]
Hi, Trying to upload large files (1gb) with 2gb memory size. 
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2174249/youphptube.log)

What I need to do?

**Comment by Hasharack** [comment]
This post I fixed when I do LOGOFF and LOGIN again on my control panel. The last post I think my videos uploads just wait on encoding

**Comment by itsflashpoint** [comment]
So this is resolved?
