### ISSUE TITLE
Error deleting configuration: Table 'youPHPTube.configurations' doesn't exist

### ISSUE THREAD

**Issue by pappupick** [DanielnetoDotCom/YouPHPTube#841]

**Comment by DanielnetoDotCom** [comment]
you need to provide more details

**Comment by itsflashpoint** [comment]
Sounds like your configurations table is missing from the database. What were you trying to do?

**Comment by pappupick** [comment]
thanks the problem is solved

**Comment by hersche** [comment]
ok, then i close it
