### ISSUE TITLE
i have problems to upload a video (encoder)

### ISSUE THREAD

**Issue by facostapv** [DanielnetoDotCom/YouPHPTube#842]
im trie to upload a video whit my local encoder to the streamer site. but i recive an error. i tried with 3 diferent videos and the same result. here a log from encoder:

[09-Jul-2018 19:31:43 America/Halifax] MP4 All
[09-Jul-2018 19:31:43 America/Halifax] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
[09-Jul-2018 19:31:43 America/Halifax] YouPHPTube-Encoder sending file to http://clsarrvvtubep01/youPHPTubeEncoder.json
[09-Jul-2018 19:31:43 America/Halifax] YouPHPTube-Encoder reading file from
[09-Jul-2018 19:31:43 America/Halifax] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/renta-encoder/objects/Encoder.php:691
Stack trace:
#0 /var/www/html/renta-encoder/view/upload.php(74): Encoder::sendFile('', 0, 'mp4', Object(Encoder))
#1 {main}
  thrown in /var/www/html/renta-encoder/objects/Encoder.php on line 691

**Comment by DanielnetoDotCom** [comment]
for sure you need to fix this "Call to undefined function curl_init()"

> If you're on Windows:
> 
> Go to your php.ini file and remove the ; mark from the beginning of the following line:
> 
> ;extension=php_curl.dll
> After you have saved the file you must restart your HTTP server software (e.g. Apache) before this can take effect.
> 
> For Ubuntu 13.0 and above, simply use the debundled package. In a terminal type the following to install it and do not forgot to restart server.
> 
> sudo apt-get install php-curl
> Or if you're using the old PHP5
> 
> sudo apt-get install php5-curl

https://stackoverflow.com/questions/6382539/call-to-undefined-function-curl-init

just one thing, if you are using PHP7, you may use this command: `sudo apt-get install php7.0-curl`

**Comment by hersche** [comment]
it is also documented here:

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-YouPHPTube-version-4.x-or-newer

**Comment by facostapv** [comment]
Daniel,

Thanks!!! After install “apt-get install php-curl” i have resolve the problem. Thanks for you flash answer ☺

regards

Felipe A. Acosta Díaz | Administrador de Plataforma
(56-2) 560 3400 – Anexo 3528 | www.PENTAVIDA.cl<http://www.pentavida.cl/>
Av. El Bosque Norte 500, piso 3 - Las Condes - Santiago - Chile
[Descripción: Descripción: cid:image001.jpg@01CECFE2.9CEC8D70]
[Descripción: Descripción: cid:image006.png@01CEB2F3.CF53DD60]Imprima solo si es necesario.

De: YouPHPTube [mailto:notifications@github.com]
Enviado el: lunes, 9 de julio de 2018 18:38
Para: DanielnetoDotCom/YouPHPTube
CC: Felipe Andres Acosta Diaz; Author
Asunto: Re: [DanielnetoDotCom/YouPHPTube] i have problems to upload a video (encoder) (#842)


for sure you need to fix this "Call to undefined function curl_init()"

If you're on Windows:

Go to your php.ini file and remove the ; mark from the beginning of the following line:

;extension=php_curl.dll
After you have saved the file you must restart your HTTP server software (e.g. Apache) before this can take effect.

For Ubuntu 13.0 and above, simply use the debundled package. In a terminal type the following to install it and do not forgot to restart server.

sudo apt-get install php-curl
Or if you're using the old PHP5

sudo apt-get install php5-curl

https://stackoverflow.com/questions/6382539/call-to-undefined-function-curl-init

just one thing, if you are using PHP7, you may use this command: sudo apt-get install php7.0-curl
