### ISSUE TITLE
Is it possible to insert Videos from other cloud sharing platforms?

### ISSUE THREAD

**Issue by RapFan89** [DanielnetoDotCom/YouPHPTube#845]
On my server i have limited space, so my idea is to upload all videos to google drive, which i pay, and then insert the link in YouPHPTube, is that possible?

Thank u.

**Comment by DanielnetoDotCom** [comment]
I dont think so, GDrive does not gives you a direct access to the video file (MP4 File).

You can try the AWS_S3 plugin for a dynamic storage

**Comment by RapFan89** [comment]
I can generate a direct download link with this website. https://sites.google.com/site/gdocs2direct/

**Comment by DanielnetoDotCom** [comment]
this is a download link, NOT a direct file access link

**Comment by RapFan89** [comment]
But on mediadrop (another softwaree just like yours, but dead) it was possible and worked. I've had no files on my server they where streamed from gdrive. The question is: can i upload a video somwhere and use the link to stream the video through youPHPTube?

**Comment by DanielnetoDotCom** [comment]
yes, direct MP4 link works with no problem, but download links from google drive does not

**Comment by hersche** [comment]
a description about this is also here:

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/User-manual

under chapter "Add video"
