### ISSUE TITLE
Subtitle Switcher Problem?

### ISSUE THREAD

**Issue by roquirawnez** [DanielnetoDotCom/YouPHPTube#846]
Hello,

i've bought the Subtitle Plugin and activated it in the plugin manage.I've encoded a video with Audio, but there is now subtitle option in the player.

Did i miss something?

**Comment by DanielnetoDotCom** [comment]
Hi

When you edit the video you should see a subtitle button to upload your subtitle file

![image](https://user-images.githubusercontent.com/18009293/42519805-3595a77a-843b-11e8-8461-d614ca18598f.png)

**Comment by roquirawnez** [comment]
Hey thanks for your quick response.
Is the subtitle automaticly generated from the Audio or how does the subtitle File Workshop?

**Comment by DanielnetoDotCom** [comment]
No, it is not automatic, you need to upload a srt or vtt file

**Comment by roquirawnez** [comment]
Will there be an automatic audio recognition in the future?
And do you know a open source software which could create automated from the sound an srt?

**Comment by DanielnetoDotCom** [comment]
Hi, A while ago I had researched for it, but I didnt fine any good enough
