### ISSUE TITLE
No videos table after installation

### ISSUE THREAD

**Issue by deivisonmoraes** [DanielnetoDotCom/YouPHPTube#85]
SELECT u.*, v.*, c.iconClass, c.name as category, c.clean_name as clean_category, v.created as videoCreation, (SELECT count(id) FROM video_ads as va where va.videos_id = v.id) as videoAdsCount FROM videos as v LEFT JOIN categories c ON categories_id = c.id LEFT JOIN users u ON v.users_id = u.id WHERE 1=1 AND v.status IN ('a','xmp4','xwebm','xmp3','xogg') having videoAdsCount = 0 AND v.users_id = 1\nError : (1146) Table 'youPHPTube.videos' doesn't exist

MariaDB [youPHPTube]> SHOW TABLES ;
+------------------------+
| Tables_in_youPHPTube   |
+------------------------+
| categories             |
| comments               |
| configurations         |
| likes                  |
| playlists              |
| playlists_has_videos   |
| subscribes             |
| users                  |
| users_groups           |
| users_has_users_groups |
| video_ads              |
| video_ads_logs         |
| video_documents        |
| videos_group_view      |
| videos_statistics      |

The installation seems incomplete because there are also no options in the settings tab...

**Comment by deivisonmoraes** [comment]
My url is http://IP-SERVER/YouPHPTube

**Comment by DanielnetoDotCom** [comment]
Hi, it not suppose to happened,
Can you drop your database delete videos/configuration.php file and try to install again?

**Comment by deivisonmoraes** [comment]
I imported the database.sql file directly and returned this error: ERROR 1071 (42000) at line 47: Specified key was too long; max key length is 767 bytes
Line 47 speaks exactly from the table videos... Can I help me?! tks

**Comment by deivisonmoraes** [comment]
I added at the end of the sql table videos: ROW_FORMAT = DYNAMIC and the file imported normally.


CREATE TABLE IF NOT EXISTS `videos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `clean_title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `views_count` INT NOT NULL DEFAULT 0,
  `status` ENUM('a', 'i', 'e', 'x', 'd', 'xmp4', 'xwebm', 'xmp3', 'xogg', 'ximg') NOT NULL DEFAULT 'e' COMMENT 'a = active\ni = inactive\ne = encoding\nx = encoding error\nd = downloading\nxmp4 = encoding mp4 error \nxwebm = encoding webm error \nxmp3 = encoding mp3 error \nxogg = encoding ogg error \nximg = get image error',
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  `users_id` INT NOT NULL,
  `categories_id` INT NOT NULL,
  `filename` VARCHAR(255) NOT NULL,
  `duration` VARCHAR(15) NOT NULL,
  `type` ENUM('audio', 'video') NOT NULL DEFAULT 'video',
  `videoDownloadedLink` VARCHAR(255) NULL,
  `order` INT UNSIGNED NOT NULL DEFAULT 1,
  `rotation` SMALLINT NULL DEFAULT 0,
  `zoom` FLOAT NULL DEFAULT 1,
  `youtubeId` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videos_users_idx` (`users_id` ASC),
  INDEX `fk_videos_categories1_idx` (`categories_id` ASC),
  UNIQUE INDEX `clean_title_UNIQUE` (`clean_title` ASC),
  INDEX `index5` (`order` ASC))
ENGINE = InnoDB ROW_FORMAT=DYNAMIC;

Stayed like this

Tks!

**Comment by deivisonmoraes** [comment]
I will test again...

**Comment by deivisonmoraes** [comment]
Now, it works! Tks!

**Comment by DanielnetoDotCom** [comment]
great, i hope you enjoy
