### ISSUE TITLE
Ouestion

### ISSUE THREAD

**Issue by Nisarg22** [DanielnetoDotCom/YouPHPTube#850]
There is no smtp in demo site still account verification contact page and everything works how can u please tell me

**Comment by DanielnetoDotCom** [comment]
I set up postfix send mail

**Comment by Nisarg22** [comment]
How did u do that

**Comment by DanielnetoDotCom** [comment]
I use https://www.mailgun.com/

**Comment by Nisarg22** [comment]
Can I use elastic email does it support

**Comment by Nisarg22** [comment]
And wanted to ask about firebase authentication and email

**Comment by DanielnetoDotCom** [comment]
Sorry I am not an email expert , will be better if you ask this on their forum or support contact

**Comment by Nisarg22** [comment]
Ok thanks for your help
