### ISSUE TITLE
 Changed rights not saved

### ISSUE THREAD

**Issue by Fitz22** [DanielnetoDotCom/YouPHPTube#853]
Hello,

When a change rights on a user, they are not saved.

![image](https://user-images.githubusercontent.com/30529737/42616354-3695749c-85ae-11e8-8946-0e2499a463f1.png)
![image](https://user-images.githubusercontent.com/30529737/42616368-4ca36f32-85ae-11e8-92b1-4126f7edf673.png)
![image](https://user-images.githubusercontent.com/30529737/42616377-5b3dc6e6-85ae-11e8-9aee-875159f3db62.png)

And if I modify an existing user, even ADMIN, he loses all rights
The only way to change the rights is to go through the database directly.

I followed the wiki / git procedure for the installation and no errors appeared.

Thanks.

**Comment by hersche** [comment]
cool, it seems at least, you have expirience with databases. there where some incomplete 'db-version-situations', can you recheck if https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/updatedb/updateDb.v5.8.sql was applied?

there should be a column 'externalOptions' on the 'users'-table. if it does not exist, the upgrade was broken somehow.

also, can you do another git pull? maybe it's something that's fixed meanwhile.

**Comment by Fitz22** [comment]
Hi and thank you for your reply. I have "externalOptions" in the users table.

![image](https://user-images.githubusercontent.com/30529737/42635362-2ebc2b16-85e6-11e8-9e8a-52c592983b74.png)

**Comment by DanielnetoDotCom** [comment]
@Fitz22 what is in your log file when you try to save it?

**Comment by DanielnetoDotCom** [comment]
Also maybe @Criptos can help with it

**Comment by Fitz22** [comment]
Hello! Where can I find the log file?

**Comment by Criptos** [comment]
Here I'm... can you show us the logs and aslo, if there is something at your javascript console? 
control-shift-i at chrome browser.

**Comment by itsflashpoint** [comment]
I think you need to press like 5 times to make it save, if it doesn't work login, logout and save. I think that's what I did to make my shit save.

**Comment by Fitz22** [comment]
Hi!  
![image](https://user-images.githubusercontent.com/30529737/42680575-b0250340-8685-11e8-940d-2ceb6a97bc95.png)

**Comment by Criptos** [comment]
Can you show us the parameter and the response for userAddNew.json.php please?

**Comment by Fitz22** [comment]
![image](https://user-images.githubusercontent.com/30529737/42690720-bccc01b4-86a5-11e8-89a7-2414113659c5.png)

**Comment by hersche** [comment]
can you please update and retry?

there was one situation which is fixed meanwhile and could maybe solve your problem..

**Comment by Fitz22** [comment]
That's good. I think the problem is solved

Merci
