### ISSUE TITLE
to visit in windows 

### ISSUE THREAD

**Issue by venumm** [DanielnetoDotCom/YouPHPTube#854]
i`ve install the youphptube in ubuntu 16.04 already ,but i can`t open it in windows ,what should i do?
![default](https://user-images.githubusercontent.com/41148833/42627388-7df93142-85ff-11e8-8ae4-56b798e9f2e3.PNG)

**Comment by hersche** [comment]
is the url in videos/configuration.php matching your used url? for me it looks like that

give a link of your installation or access or hire me here: vinzenz.hersche@gmail.com 

and did you read the troubleshoot-guide here? https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Admin-manual
