### ISSUE TITLE
Unable to reset the admin password.

### ISSUE THREAD

**Issue by Rudra296425** [DanielnetoDotCom/YouPHPTube#856]
Hi,

I have given a password at the time of configuring.
That admin password is not accepted by YouPHPTube.

So I tried reset the password using, 'I forgot password'.

But that throughs me end loop of processing.

Is there any alternate way to reset the password.?

I am not able to Sign up too.

**Comment by hersche** [comment]
can you do a update and retry? there's a fix now.
