### ISSUE TITLE
AVCHD .MTS or .M2TS upload on YouPHPTube

### ISSUE THREAD

**Issue by tuxtechno** [DanielnetoDotCom/YouPHPTube#859]
Hi,
I am using YouPHPTube for video recording which we upload to our intranet server, but our camcorder gives output on .MTS / .M2TS (AVCHD) format, which YouPHPTube doesnt support, could you please help me 
1) does YouPHPTube-Encoder supports uploading on .MTS / .M2TS AVCHD files, as i have checked ffmpeg supports but when i try to upload file to YouPHPTube encoder it shows it doesnt support type of file ?
2) how can i upload these videos to YouPHPTube without converting them to .MP4 ?

**Comment by DanielnetoDotCom** [comment]
Hi

You should have a configuration.php file on your encoder

add the extension that you need on the $global['allowed'] variable, so your config should be like that


```
<?php
$global['webSiteRootURL'] = 'http://127.0.0.1/YouPHPTube-Encoder/';
$global['systemRootPath'] = '/home/daniel/Dropbox/htdocs/YouPHPTube-Encoder/';

$global['disableConfigurations'] = false;
$global['disableBulkEncode'] = false;

$mysqlHost = 'localhost';
$mysqlUser = 'root';
$mysqlPass = '*****';
$mysqlDatabase = 'youPHPTube-Encoder';

$global['allowed'] = array('mp4', 'avi', 'mov', 'mkv', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv', 'mpg', 'mpeg', 'mts', 'm2ts');
/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';
```

**Comment by tuxtechno** [comment]
I have successfully able to use .mts .m2ts after the change, but now when i try to use bulk upload option, it doesn't list my .mts files, if i point it to another folder where .mp4 files are exist, it shows list.
I guess there is one more modification required to get bulk upload work, please suggest how to get it done
