### ISSUE TITLE
video is not getting uploaded & admin's advance configuration settings.

### ISSUE THREAD

**Issue by rohitnehra** [DanielnetoDotCom/YouPHPTube#86]
How to set up own encoder locally?
![screenshot from 2017-08-17 16 37 18](https://user-images.githubusercontent.com/31066431/29409607-a96c6b66-836a-11e7-991f-ba88d3a4ac39.png)

**Comment by DanielnetoDotCom** [comment]
This screen is very strange, in version 4.0 you suppose to upload videos thru the encoder site (https://github.com/DanielnetoDotCom/YouPHPTube-Encoder)
Take a look on demo site how it works
