### ISSUE TITLE
Adding New User Details Problem - Please Help

### ISSUE THREAD

**Issue by hypedboss** [DanielnetoDotCom/YouPHPTube#861]
I added new details form on sign up page and i added it in objects/userCreate.json. If i enter details and click on Sign up button it will just be loading the ajax loader without sending to db or even giving message of error or success
But if i did not put all data it will tell me to put all before proceeding
Please help

**Comment by DanielnetoDotCom** [comment]
Sorry, I don't understand what you want to do, but probably that is not the proper way to do.

**Comment by hypedboss** [comment]
Example: Sign up page includes Name, Username, Email, Password, Confirm Password, Captcha.
Now i want to add additional details there

**Comment by Nisarg22** [comment]
can u leave your site link

**Comment by hypedboss** [comment]
https://webbiwood.com

**Comment by Nisarg36** [comment]
I r trying to say that if user don't fill all the information he can't register

**Comment by Nisarg36** [comment]
Sorry u need to add details in view/signup.php then it will be there

**Comment by hypedboss** [comment]
I did it on my localhost, after adding the details, i added them again to /objects/userCreate.json but its not adding to db and registration will just be loading the ajax without sending details or error

**Comment by Nisarg22** [comment]
Did u create a table for that in your database

**Comment by DanielnetoDotCom** [comment]
Hi @hypedboss 

If you want to change the code, you should be able to debug it and find what is missing.

Probably something on the user.php class

**Comment by hypedboss** [comment]
Thanx
