### ISSUE TITLE
YouPHPTube Encoder speed

### ISSUE THREAD

**Issue by tuxtechno** [DanielnetoDotCom/YouPHPTube#862]
I have installed encoder locally i have uploaded 4 GB file in AVCHD format, and selected HD only in type of formats to be uploaded, but it took around 30 minutes to get it encoded, how can i increase speed of encoding by assigning more CPU / Memory resources to the encoder ?

As i have i5 CPU, 12 GB Ram, ubuntu 16.04, when encoding was happening i have checked CPU use was around 5% only and memory used was 1.26 GB out of 12 GB, I guess if i allot more resources for encoding, it will speed up the time required

**Comment by DanielnetoDotCom** [comment]
Hi

The encode process is about FFMPEG command, to speed up the encode process you will need to speedup ffmpeg.

Maybe the ffmpeg threads help you with that https://superuser.com/questions/792525/how-to-change-ffmpeg-threads-settings

change your ffmpeg commands on the configuration menu on encoder 

![image](https://user-images.githubusercontent.com/18009293/42755594-36b25502-88cf-11e8-915f-72e16908a4d7.png)
