### ISSUE TITLE
Trouble accessing streamer via encoder on local server

### ISSUE THREAD

**Issue by jeffkerby** [DanielnetoDotCom/YouPHPTube#863]
I am having an issue with accessing the streamer via the encoder on my local Antsle server. When I select the login button on the encoder landing page I am receiving this message 

"Sorry! We could not found your streamer site!" 

I have updated my PHP.ini as directed in the wiki and restarted my apache server. 

See the attached log file. 
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2195350/youphptube.log)

**Comment by DanielnetoDotCom** [comment]
you have this

`PHP Warning:  file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/html/YouPHPTube-Encoder/objects/Login.php on line 40`

Looks like you are not resolving your DNS name properly
