### ISSUE TITLE
Add live link m3u8 not working on Chrome and firefox...

### ISSUE THREAD

**Issue by benx3** [DanielnetoDotCom/YouPHPTube#867]
I got an error when Add Live Link m3u8: 

![image](https://user-images.githubusercontent.com/40012684/42742133-a32e4bf6-88e2-11e8-8a2d-42178d43f765.png)

Could you help me?
It's working on ios but on chrome and firefox window it fails.

**Comment by DanielnetoDotCom** [comment]
You have to configure cors properly on your playlist.m3u8 host
