### ISSUE TITLE
I got error accessing from other computer in same LAN

### ISSUE THREAD

**Issue by boom02456** [DanielnetoDotCom/YouPHPTube#868]
I would like to ask for the problem I found and cannot solve it,

	I open YouPHPTube in UBUNTU 18.10 VM, and get IP 192.168.0.90

	Since I tried to access it from local pc, which is in the same LAN

	I got problem from other computer that the website call localhost/js file

	Could you please suggest me to fix this problem?

	I need to do the demo to my team first, so they can decide to buy plugins from you

	Thank you in advance,

**Comment by boom02456** [comment]
<img width="1439" alt="screen shot 2561-07-16 at 17 12 34" src="https://user-images.githubusercontent.com/36606195/42754348-5b1dfb68-891e-11e8-8998-edfa9e8f3c9c.png">

**Comment by boom02456** [comment]
I got the resolved for the main website, but the Encoder I cannot access the main website

**Comment by boom02456** [comment]
<img width="861" alt="screen shot 2561-07-16 at 17 49 28" src="https://user-images.githubusercontent.com/36606195/42754940-9f0cd90a-8920-11e8-9ab9-09b78f2fd0bf.png">

**Comment by DanielnetoDotCom** [comment]
I can see you installed it using localhost, now you want to access using the ip 192.168.0.90

You have 2 options, 

1. drop the database and delete the videos/configuration.php file and install it again accessing the site using 192.168.0.90 or ...
1. try to fix the database and configuration.php file  https://tutorials.youphptube.com/video/fix-youphptube-url-after-move-server-location-and-ip
