### ISSUE TITLE
Logo, confirmation and Loading issues

### ISSUE THREAD

**Issue by LucasCain2** [DanielnetoDotCom/YouPHPTube#869]
I change the sites logo using the admin panel and the site will tell me it was successful, but when I reload the page it's blank where the logo should be.

I also have to refresh twice when I use any of the side links for the page to come up.

Finally, E-mail confirmation doesn't show up in users mail box but mine for when i change the admin password. How do I fix this, and how do i edit what they receive in the confirmation E-mail itself?

(I would like to add no error codes or messages have come up. The script runs smoothly other than the above problems.)

**Comment by Nisarg22** [comment]
Can u drop your site link

**Comment by DanielnetoDotCom** [comment]
Hi

> I change the sites logo using the admin panel and the site will tell me it was successful, but when I reload the page it's blank where the logo should be.

Did you clear your browser cache after change the logo?

> I also have to refresh twice when I use any of the side links for the page to come up.

What does it mean?

> Finally, E-mail confirmation doesn't show up in users mail box but mine for when i change the admin password. How do I fix this, and how do i edit what they receive in the confirmation E-mail itself?

What email confirmation?

**Comment by LucasCain2** [comment]
what? Email confirmation means only one thing and I even stated what it is in my question. When a user registers on your site they have to verify the email. They receive a message in their Email.

But my issue is that the user does not receive the email. Nothing goes in their inbox. At all. I would also if able like to change the message they receive but I need to have the email sent to them first before any of that.

Also refresh twice is also explaned, I have to constantly refresh twice to get pages to load. I have plenty of bandwidth and other essentials in the backend so  have no idea why it's doing that. I'm assuming it may be some issue with one of the files.

**Comment by LucasCain2** [comment]
Not my inbox, the Email isn't showing up in the Users inbox. As in a new user that wants to register and upload on the site is supposed to receive an eail to verify their account. The E-mail doesn't show up on their account.

As for the logo it's just an empty blank space.

**Comment by LucasCain2** [comment]
Also video thumbnails have a 404 error picture on them but the videos them-self work fine.

**Comment by LucasCain2** [comment]
Any suggestions? @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
The 404 image, if you are uploading a direct MP4 file, you will need a plugin to extract the image from the video **MP4ThumbsAndGif**

![image](https://user-images.githubusercontent.com/18009293/42830449-daf47468-89c1-11e8-81e1-1fb1e2df011e.png)


For now, when they singup they do not receive and email validation (It may be change in the future), they need to request it on the "My Account"

![image](https://user-images.githubusercontent.com/18009293/42830617-5a60c080-89c2-11e8-8544-ca8bef00f5b3.png)

**Comment by LucasCain2** [comment]
What? As I said they don't receive the e-mail in their inbox. I'm the only one that gets E-mail in the inbox a I said. Them clinking on that does not send them the E-mail.

There are no errors the page shows the logo I uploaded but if I refresh/logoff/or another user looks at the site the logo is blank.

**Comment by DanielnetoDotCom** [comment]
If you receive the email, and they dont, you need to check your email server configuration (SMTP or sendmail) . this is nothing related to YouPHPTube, sometimes the email does not rises an Apache or PHP error. maybe you get an syslog error.

about the logo error, can you reproduce it on demo site?

**Comment by LucasCain2** [comment]
These are my SMTP settings so I need to edit something here?
![rwrwr](https://user-images.githubusercontent.com/41306494/42839734-9fffd620-89d2-11e8-9e0d-fd0c7e0dab61.png)

Also as i said before, there is no error when I do the logo. It shows up and confirms the logo change then as soon as I leave the page it's blank and when i go back to the settings it shows the picture as blank as well.

Edit: of course now the logo works all the time now so whatever that was must have been something wrong with the script and it fixed itself? Eh. 

But anyway I guess all i need now are the email settings.

**Comment by LucasCain2** [comment]
What should I change in smtp settings @DanielnetoDotCom ?

**Comment by DanielnetoDotCom** [comment]
It depends who is your smtp provider .
Try to Google for smtp configuration

**Comment by hersche** [comment]
> But my issue is that the user does not receive the email. Nothing goes in their inbox.

> What should I change in smtp settings @DanielnetoDotCom ?

this is NOT our issue!

we are a developer-project, doing php-code. if you would setup a wordpress or similiar, you would need the same information and also email would not work.
what you do then? asking wordpress to install your installation?

or, when i buy a game for windows, from, for example ubisoft - do i go to ubisoft then and ask, how to install my windows, how to install the drivers etc? i don't think so, this is the problem of microsoft, not the game! Apache, smtp, mysql is the same for ypt.

there is a reason, why there are sys-admins and developers. If you want to setup ANY php-script, you need some expirience in the sys-admin-part.

read the docs, use google, review and ask your hoster. if you want our help for thing like that, we provide a commercial support.

**Comment by LucasCain2** [comment]
it is not your issue.

yet that screen shows your product.

You also don't have any advertising for "your" product that E-mail does not automatically send when a user signs up either. Which is misleading. Which again is your issue but ok.

In any caee you guys linked me to the read me on the other topic so I'll just try to see if I can replicate the tutorials not on Cpanel with Cpanel since it seems I'm not getting any real help here in setting things up I already got everything almost done.

Or you know the layout and settings of the script. You would think you guys would you know, help people understand what they're looking at in YOUR script but eh.

Also asking wordpress to install your installation? What? Did you read what you typed/ What does that even mean?

(Also ubisoft does help with the drivers but ok. That's not even what i'm asking here anyway. I wanted an explanation at what the settings in that screen shot of your product where never got it oh well))

**Comment by hersche** [comment]
> You also don't have any advertising for "your" product that E-mail does not automatically send when a user signs up either. 

does wordpress have this? it's just logic, php supports smtp like the official standart it is.

or do we have any description it does send emails withouth any configuration?

i don't think so. also wordpress, own/nextcloud, phpbb, friendica, etc, have no "you have to configure e-mail before this works". because it is part of a admins work.

> I'm not getting any real help here in setting things up

well, that's the point. we DEVELOP for FREE. people with knowledge about admin-work just know, how to fill the smtp-infos for example. so SETUP is ADMIN-work. we (or at least me) provide commercial support for such general topics (while we create the software, like said, for free)

> Also asking wordpress to install your installation?

this is a example to compare.

> Also ubisoft does help with the drivers but ok.

so if i have a bluescreen related to windows, they help me, because i buyed a simple game?
sorry, i don't think so. windows is related to microsoft, not ubisoft.

i just mean: there are a lot of tutorials on google, in your hoster, you should find infos about that.

btw, out of section "Important Information", in the README:

> However we recommend Ubuntu 16 or 17 without any kind of control panel. The problem with cPanel, Plesk, Webmin, VestaCP, etc. It's because we need full root access to install some libs, and maybe compile them.

**All this is just my opinion, how i personal see this**. If anyone else like to help you for free, that's fine. but i absolutly understand 

> try google

as the right answer for that topic. good luck for your setup.

**Comment by LucasCain2** [comment]
You know I can see the original post through E-mail right? But ok if you want to be disingenuous. 

Anyway I'll be looking through the help fiels thank you.
