### ISSUE TITLE
Sharing on FB - wrong facebook metatags

### ISSUE THREAD

**Issue by RadekHavelka** [DanielnetoDotCom/YouPHPTube#87]
When sharing the video on facebook, I get different image preview (from another video). It seems that tags

```
og:image
og:image:alt
```

are not being filled in correctly. Also facebook debuger reports

```
Missing Properties
The following required properties are missing: fb:app_id
```

this would be great if it can be added into the admin page.
Thank you

**Comment by RadekHavelka** [comment]
ps. video metatags for direct sharing on facebook would be even better
https://developers.facebook.com/docs/sharing/webmasters

**Comment by DanielnetoDotCom** [comment]
I have take a look on that before, and I still not figure out what is wrong.
do you have any idea what tag should be added?

**Comment by RadekHavelka** [comment]
yes. First you need to add metatags og:video:url (with url to the video file, ideally in https format), og:video:secure_url (this has to be in https format), og:video: type (i suggest to use "video/mp4" and video mp4 url), og:video:width (width of the video) and og:video:height (height of the video). I suggest you store those in the database, i added this quick and dirty code to the Encoder.php

```
static function getDimensionsFromFile($file) {
        // get movie dimension WIDTH:HEIGHT
        if (!file_exists($file)) {
            error_log('{"status":"error", "msg":"getDimensionsFromFile ERROR, File (' . $file . ') Not Found"}');
            return "EE:EE";
        }
        $file = str_replace('webm', 'mp4', $file);

        eval('$cmd="ffprobe -i {$file} -v quiet -print_format json -show_format -show_streams";');
        exec($cmd . ' 2>&1', $output, $return_val);
        if ($return_val !== 0) {
            error_log('{"status":"error", "msg":' . json_encode($output) . ' ,"return_val":' . json_encode($return_val) . ', "where":"getDuration", "cmd":"' . $cmd . '"}');
            $duration = "EE:EE";
        } else {
            $output_json = json_decode(implode(chr(10), $output));
            $dimensions = $output_json->streams[0]->width . ':' . $output_json ->streams[0]->height;
        }
        error_log("Dimensions founded: {$dimensions}");
        return $dimensions;
    }
```
and of course some other files needs to be modified as well, so the dimensions of the video bubble up to the database.

use the facebook debuger to see if the output is correct

https://developers.facebook.com/tools/debug/sharing/

you put ther video page url and it will parse all tags out of it and shows you the result. Use "scrape again" to refresh, as facebook caches all pages visited for a long time, so changes do not propagate there unless you scrape again.

**Comment by DanielnetoDotCom** [comment]
I gess it is fixed now, thanks
