### ISSUE TITLE
Editing video from playback page doesn't save results

### ISSUE THREAD

**Issue by nospi** [DanielnetoDotCom/YouPHPTube#870]
If i navigate to My Videos from the menu bar on the left, then edit the video then all changes are saved successfully.

However if I'm on the video playback page and hit the 'Edit Video' button, it directs me to `/mvideos?video_id=X` which appears to work correctly, however any changes made don't appear to be saved.

I've made a lot of changes so I guess the first question is, can anybody else reproduce the issue? 

I'm moderating all content at this stage so it's not a huge issue but may be affecting others who have end users managing their own content.

Cheers,

Jerad

**Comment by DanielnetoDotCom** [comment]
@nospi can you reproduce it on demo site?
