### ISSUE TITLE
Category Issue // Wrong default video displayed

### ISSUE THREAD

**Issue by idealsud** [DanielnetoDotCom/YouPHPTube#871]
Hello,

I created 3 Categories but when I click one category, i always have the default video displayed, not the first one from the Category i chose.

Example here : https://vid01.ideal-hosting.fr/thea-tv-58

**Cat 1** - Movie 1 : How Do You Edit an Animated Film 
            Move 2 : Jacques Tati- Where to Find Visual Comedy
**Cat 2** - Steven Spielberg- Moments of Humanity
**Cat 3** - No movie in this category

I've always the last embedded video **(Steven Spielberg- Moments of Humanity - Cat 2)** display no matter which category i choose.

Thanks for your help.
Kind Regards.
Christophe

**Comment by DanielnetoDotCom** [comment]
Try to change your site to gallery mode (Enable Gallery Plugin), I think Category will work better there

**Comment by idealsud** [comment]
Thanks, It's okay in Gallery mode but i need to use Regular Mode. Is it possible to fix it ?

**Comment by DanielnetoDotCom** [comment]
when you say default video on regular mode, what video are you talking about?

**Comment by hersche** [comment]
>  Is it possible to fix it ?

the point here is: we do not sortt the videos on a page by the categoryname. we take the newest video, the videos sort by name, etc, not the category..

i think this is what you meaned?

**Comment by DanielnetoDotCom** [comment]
I see what you mean, but the video name overwrite the channel selected.

this is because some times you share a video using the SEO URL, and for some reason you change the video category. If the video name does not overwrite the category the shared link will be broken.

So for now, if in the link there is a video name. this video will be displayed

**Comment by idealsud** [comment]
Thanks Daniel
I don't need to share videos, is it possible to not overwrite the selected category and get only the category list without the last uploaded video, in the "Regular mode"?
Many thanks

**Comment by DanielnetoDotCom** [comment]
Sorry, for now we cant change this rule.
