### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by Shivamn1987** [DanielnetoDotCom/YouPHPTube#872]
The requested URL /YouPHPTube/user was not found on this server.
Apache/2.4.29 (Ubuntu) Server at 127.0.0.1 Port 80.

kindly help

**Comment by DanielnetoDotCom** [comment]
@Shivamn1987 

We need a lot more details on your question.

this does not say much

**Comment by Shivamn1987** [comment]
what are the details you need

**Comment by Shivamn1987** [comment]
[
![capture](https://user-images.githubusercontent.com/41330157/42816410-52474394-89e8-11e8-91a6-0d6614e3b8c9.PNG)
](url)

**Comment by DanielnetoDotCom** [comment]
Or you really missing a file or your Apache mode Rewrite is not enabled. also make sure you have the .htaccess file on the site root

**Comment by LucasCain2** [comment]
@Shivamn1987 Hey there. where you have classic.htcaccess and new.htcaccess, move the classic.htaccessfile to a different folder, rename to just .htaceess, and then move it back (or if your editor allows you to rename it in the same spot do that to skip a step). That should resolve the issue.

**Comment by hersche** [comment]
theres a litte more, you need to enable the modules.

read this: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Message-when-rewrite-is-not-set

**Comment by Nisarg22** [comment]
I think he has deleted install folder

**Comment by Nisarg22** [comment]
Because if mode is not writable then simply site would not install

**Comment by hersche** [comment]
install-folder doesn't matter in this context, you need to have

- **.htaccess** in place
- rewrite-modules for apache enabled

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Message-when-rewrite-is-not-set

i am pretty shure, it's not the first time we have this issue..
