### ISSUE TITLE
Move footer, live streaming, video encoder

### ISSUE THREAD

**Issue by LucasCain2** [DanielnetoDotCom/YouPHPTube#873]
So I have a couple other issues. How do I set up live streaming/ What are the steps needed?

Secondly, the footer, I don't want to customize the footer (there's a plugin for that) what i want to do is move the location of the footer because the rest of that bar at the bottom that has nothing in it takes up space where my site design places links.

Also how do I install the public encoder? It redirects me to a login page.

**Comment by DanielnetoDotCom** [comment]
Try this for your live stream https://tutorials.youphptube.com/video/10-min-youphptube-stream-server-installation

You can try to add some css on the header to move the footer

**Comment by LucasCain2** [comment]
Ok, but how do I install the "public" video encoder for video uploads?

**Comment by DanielnetoDotCom** [comment]
You can find all of this on the tutorial page or on the readme file

**Comment by LucasCain2** [comment]
I don't have the readme file, link to tutorial?

**Comment by LucasCain2** [comment]
@DanielnetoDotCom Also I need to clarify, i don't have that virtual thing that's show in the videos I'm using Cpanel.

**Comment by DanielnetoDotCom** [comment]
Again please read the readme file, because cpanel is not recommended , you must have ssh root access

**Comment by LucasCain2** [comment]
Where is the readme file? I asked this.

**Comment by DanielnetoDotCom** [comment]
https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/README.md

**Comment by hersche** [comment]
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Admin-manual

or you can ask us for set it up for you, as a paid support.

**Comment by LucasCain2** [comment]
No nice try though.

I'm using Cpanel if you know how to do this using Cpanel then i if would would help me with those instructions that would be cool.

Also still haven't gotten an answer for the footer css.

**Comment by LucasCain2** [comment]
thanks
