### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Nisarg22** [DanielnetoDotCom/YouPHPTube#874]
If I want to have live streaming then it is compulsory to have ssh root access or it will work without it
And what's the use of "usePermalinks" in customize advance module

**Comment by DanielnetoDotCom** [comment]
ssh root access is for you install/compile your own native live server.
If you use external live servers you can use the LiveLinks plugin

"usePermalinks" will replace the SEO link (that can change depends on your video title), for a permanent link URL (never changes)

**Comment by Nisarg22** [comment]
If I try to pause video it gets stopped instead of been pause and we have to start it from beginning

**Comment by DanielnetoDotCom** [comment]
Sorry but I am not aware about it, the pause works properly here, we can not reproduce it

**Comment by Nisarg22** [comment]
Sorry it was my mistake I want to ask you that if u try to watch it in full screen then its not rotating the video remains in same angle

**Comment by DanielnetoDotCom** [comment]
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Ad-Server-Plugin

**Comment by Nisarg22** [comment]
And what about video rotation

**Comment by DanielnetoDotCom** [comment]
Video rotation is not full supported yet

**Comment by Nisarg22** [comment]
Ok but there are many problems in adserver plug in I m not able to edit my ads or even delete them or they r not even appearing in videos can u check that

**Comment by DanielnetoDotCom** [comment]
there is an Javascript error?

**Comment by Nisarg22** [comment]
Did you solve that

**Comment by DanielnetoDotCom** [comment]
Sorry, slove what?

**Comment by Nisarg22** [comment]
Javascript error

**Comment by DanielnetoDotCom** [comment]
That is why I am asking to see yours JS Log errors,  I dont know what is happening.

The demo site is fine

**Comment by Nisarg22** [comment]
Can u check that as I m not able to check as I m quite busy for some days as I m going to have my startup with youphptube
My site nisargpathak36.000webhostapp.com

**Comment by DanielnetoDotCom** [comment]
I took a look, I could not see any ads being loading.

Make sure you add videos on your campaign

**Comment by Nisarg22** [comment]
I have already add u can check yourself id and pass is admin

**Comment by DanielnetoDotCom** [comment]
Looks like is working, but I recommend you to update your files to the latest files on github.

Maybe there are some fixes regarding the Ads

![image](https://user-images.githubusercontent.com/18009293/43077348-a7f0b5b8-8e5d-11e8-977c-456467ae4645.png)

**Comment by Nisarg22** [comment]
I m using Google chrome and not even having ad blocker still it's not working

**Comment by DanielnetoDotCom** [comment]
I am also on google chrome, but any way, get the latest files

**Comment by Nisarg22** [comment]
Sure

**Comment by Nisarg22** [comment]
Does that ad server support mobile

**Comment by DanielnetoDotCom** [comment]
yes

**Comment by Nisarg22** [comment]
There are only 2 videos I uploaded and one is ad then how both of them are available other one should not be there

**Comment by DanielnetoDotCom** [comment]
If you want it to not be there, make it unlisted 

![image](https://user-images.githubusercontent.com/18009293/43080002-075e1b10-8e65-11e8-918a-92adbe28e96a.png)

**Comment by Nisarg22** [comment]
How remove ads from some videos in which owners don't want ads

**Comment by DanielnetoDotCom** [comment]
For now, it is not possible

**Comment by Nisarg22** [comment]
Can u make a plugin of adserver which was there before this was

**Comment by DanielnetoDotCom** [comment]
does the plugin ads (Old one) support to show the ads for some specific user groups?

**Comment by Nisarg22** [comment]
Yes

**Comment by Nisarg22** [comment]
It will be great if we can have ads on vides only we wants not on all

**Comment by DanielnetoDotCom** [comment]
If you are willing to pay for that upgrade please contact me on developer@youphptube.com

**Comment by Nisarg22** [comment]
If u want I can try to make for this project just send me codes of that old ad server I m also a Cs student

**Comment by Nisarg22** [comment]
My email address nisargpathak36@gmail.com

**Comment by DanielnetoDotCom** [comment]
All the codes , include the old one is on GitHub

**Comment by Nisarg22** [comment]
Ok I will check

**Comment by Nisarg22** [comment]
Do you want me to do that

**Comment by Nisarg22** [comment]
I mean u don't have any problem

**Comment by Nisarg22** [comment]
Can u just paste a link of that version which was having old adserver

**Comment by DanielnetoDotCom** [comment]
I don't remember but the release 5 should have it , look into releases

**Comment by Nisarg22** [comment]
I just got it just wanted to ask about the database name used in that

**Comment by Nisarg22** [comment]
It will be great if u help me with database table

**Comment by DanielnetoDotCom** [comment]
In my opinion, instead of handle 2 ads manager, we should improve the current ad server to handle ads on specific groups.

but this is not the priority now, but may be made in the future

**Comment by Nisarg22** [comment]
But I m going to start my startup it will help me a lot
