### ISSUE TITLE
Contact for install

### ISSUE THREAD

**Issue by OSGAJim** [DanielnetoDotCom/YouPHPTube#876]
Hello Daniel.

I purchased the install package from the YouPHPTube website last week. I have not heard from you as far as doing the installation. I have the PayPal receipt. On Monday 7/16, I emailed you asking for the next steps as we have had no correspondence since we made the purchase. Please let us know what steps to take and how to get your product professionally installed by you.

Thanx
Jim

**Comment by DanielnetoDotCom** [comment]
Hi

Sorry for this, I sent couple emails to servi...@...sportstrivia.com
And I got no answer.

Please contact me on developer@youphptube.com

**Comment by DanielnetoDotCom** [comment]
I found your email in spam . And I sent you couple other emails. Please check your spam box to check if you receive mine

**Comment by OSGAJim** [comment]
Thank you Daniel!!

**Comment by DanielnetoDotCom** [comment]
I still not receive any email from you

**Comment by DanielnetoDotCom** [comment]
I dont hear from you for a while, please let me know any update
