### ISSUE TITLE
encoder question

### ISSUE THREAD

**Issue by LucasCain2** [DanielnetoDotCom/YouPHPTube#877]
the encoder available to download here. Does that go into public-html like with the rest of the files?

**Comment by DanielnetoDotCom** [comment]
Sorry, what?

For the encoder, you will also need apache mod rewrite

**Comment by LucasCain2** [comment]
I'm talking about the .zip file with the folders

**Comment by DanielnetoDotCom** [comment]
You have to check with your host provider where to put the files, but probably is on the public-html
Remember, the encoder is another site, different from the streamer, so they cannot be hosted on the same directory.

**Comment by LucasCain2** [comment]
I'm aware, thanks for the info
