### ISSUE TITLE
Linebreaks in video description

### ISSUE THREAD

**Issue by RadekHavelka** [DanielnetoDotCom/YouPHPTube#88]
Adding new lines in description of video via enter / shift+enter gets replaced after save with characters "\n" which are visible in the video description on the live page :(

**Comment by DanielnetoDotCom** [comment]
Really, do you have a link for me to take a look?

**Comment by RadekHavelka** [comment]
Just go to edit the video description, add some text, then add new lines (enter or shift+enter) and some text again, and save it. In my environment, it glues all text together, and where newlines were are now just \n, which is character for newline, in text. But not in html, it needs to be replaced with '<br>'. Its probably caused by escaping the string via real_escape_string - this escaping makes more troubles, for example if you save "somebody's" it will become "somebody\'s" (see the backslash). I suggest to change mysql to use bind parameters (which takes care of the sanitization of the values). See http://php.net/manual/en/mysqli.prepare.php where it is described. It is better and safer.

**Comment by DanielnetoDotCom** [comment]
I Guess it is fixed now
