### ISSUE TITLE
How could I use KeyCDN instead of S3?

### ISSUE THREAD

**Issue by jeffkerby** [DanielnetoDotCom/YouPHPTube#882]
I recently moved all my videos to KeyCDN as it was a lower cost option then Amazon S3 and Cloudfront. How could I configure the system to use KeyCDN instead?

Thanks

**Comment by DanielnetoDotCom** [comment]
If It is S3 compatible you can

**Comment by jeffkerby** [comment]
Would I purchase and use the s3 plugin?

**Comment by DanielnetoDotCom** [comment]
As I can see KeyCDN is a CDN provider (for traffic only).

you will still need S3 to store your files

https://www.keycdn.com/support/aws-s3-cdn-integration/

**Comment by jeffkerby** [comment]
My files are stored on KeyCDN and they provide both a CDN and storage. I guess I can buy the plugin and try it to see if it works.

**Comment by DanielnetoDotCom** [comment]
humm, is it is S3 compatible, it will work :)
