### ISSUE TITLE
Customize edits hang on "Processing" after clicking "Save"

### ISSUE THREAD

**Issue by roc-lone** [DanielnetoDotCom/YouPHPTube#884]
Bought and uploaded the customize.zip. Tried to edit the "About" and the "Footer" but after clicking "Save" the page sticks on "Processing" with the progress bar moving. After a long period of time and several attempts I refresh the page to get out of it but no changes were saved.

**Comment by DanielnetoDotCom** [comment]
On plugin menu, did you click on the install tables button?

If still the problem after click, please check your log file

**Comment by roc-lone** [comment]
Where is the plugin menu you're speaking about? Might as well tell me where I can find the log file as well just in case. Thank you
![plugin_7-22-2018](https://user-images.githubusercontent.com/41485208/43048816-3be47e0e-8db3-11e8-8bf1-57c44a4cc925.jpg)
![plugin_menu_7-22-2018](https://user-images.githubusercontent.com/41485208/43048817-3bf8bed2-8db3-11e8-9389-953f52b10947.jpg)

**Comment by DanielnetoDotCom** [comment]
looks like you miss a directory or file on your customize plugin 

![image](https://user-images.githubusercontent.com/18009293/43049091-5da7f7ea-8dc8-11e8-9616-66fd5ef998a8.png)


check on the image what button you suppose to have

![image](https://user-images.githubusercontent.com/18009293/43049072-1e31e4ea-8dc8-11e8-816d-3d212c119d58.png)

**Comment by DanielnetoDotCom** [comment]
What about the install button?
It suppose to appear. Make sure you have your system up to date and the directory has at least read permitions

**Comment by roc-lone** [comment]
Earlier screen shot I sent shows a blue "Customize Site" button after the plugin was installed and that is the only button. You can see the system is up to date.
 ![system_version_7-22-2018](https://user-images.githubusercontent.com/41485208/43050820-e02cf402-8dd4-11e8-92ac-afa56895bc7a.jpg)

**Comment by DanielnetoDotCom** [comment]
So is it working now?

**Comment by roc-lone** [comment]
No, nothing has changed. There is no "Install Tables" button.

**Comment by DanielnetoDotCom** [comment]
You need to change the file and the dir permission, try to put it 777

**Comment by roc-lone** [comment]
I changed permissions as you suggested with the directories Customize, Install, Objects, and page to 777 and all files in those directories to 777. The result is the same with no changes and no "Install tables" button. Each time I checked I even log out and back in as the admin.

**Comment by DanielnetoDotCom** [comment]
Ok, you can manually run the content of the install.sql file.

But the best is you to try find out what is going on, you can try to look the log file when you access the plugin page.

**Comment by roc-lone** [comment]
1. When I go to "Plugins" from the Admin Menu I do not see how to access a log file. When I click "Customize Site" of the "Customize" plugin I do not see how to access a log file. Please provide steps on accessing the log file. 
2. You will need to tell me how to manually run the install.sql file.

Thank you for the help,
roc

**Comment by DanielnetoDotCom** [comment]
How to find log file: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

You can import it on your PHPMyAdmin, but install it manually is not a good solution, the button should appear for you

**Comment by roc-lone** [comment]
Here is the log. As you know the button does not appear, so do you want me to run it manually?
[youphptube.js.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2224425/youphptube.js.log)

**Comment by DanielnetoDotCom** [comment]
That is the JS log, we need the youphptube.log

**Comment by roc-lone** [comment]
Ok lets try that again.
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2224442/youphptube.log)

**Comment by DanielnetoDotCom** [comment]
there are many things there, lets try to filter.
we need to find out why the button is not appearing for you.

delete the youphptube.log file , access the plugins manager page and share yout log file.

(You dont need to do anything else, dont ender on the edit page)

**Comment by roc-lone** [comment]
Here it is.
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2224471/youphptube.log)

**Comment by DanielnetoDotCom** [comment]
very stranger. I cant see why the button is not appearing for you.

try to run the sql commands in the plugin install.sql file on your PHPMyAdmin

**Comment by roc-lone** [comment]
Well I'm not exactly sure how to do it. Do I use the "Import" tab or the "SQL" tab that indicates "Run SQL query/queries on server "localhost":? If you step me along the process showing the contents of the install.sql file then I can do it.

**Comment by DanielnetoDotCom** [comment]
you should have no problem to find it on google https://www.google.com/search?client=ubuntu&channel=fs&q=inmport+sql+with+phpmyadmin&ie=utf-8&oe=utf-8

**Comment by roc-lone** [comment]
Still no button.
![phpmyadmin_import_install_7-24-2018](https://user-images.githubusercontent.com/41485208/43153450-f747467a-8f36-11e8-9628-4d3b392fd554.jpg)

**Comment by DanielnetoDotCom** [comment]
The button is not appearing for other reason (I dont know).

But you plugin should work now

**Comment by roc-lone** [comment]
Oh yes I can now edit the About and footer. Where does the "Description" display?

**Comment by DanielnetoDotCom** [comment]
Description is a meta tag 

`<meta name="description" content="The Best YouTube Clone Ever - YouPHPTube">`

**Comment by roc-lone** [comment]
Ok, gotcha, thank you for your help. I hope when I buy more plugins the buttons show up hehe. I did not know there was supposed to be a button. Thanks again.
roc

**Comment by DanielnetoDotCom** [comment]
I am glad it is working, but we have to paid attention why this button is not showing.
