### ISSUE TITLE
Change video name / title after encoding/uploading

### ISSUE THREAD

**Issue by tuxtechno** [DanielnetoDotCom/YouPHPTube#885]
Is there any way to change video title / description after uploading is done,

I found the way in database directly but, it would be easy to do so if it is there edit video option too...

**Comment by Nisarg22** [comment]
Theres edit button

**Comment by DanielnetoDotCom** [comment]
you can find an edit button in any video or in the video manager

![image](https://user-images.githubusercontent.com/18009293/43049131-f3720e0a-8dc8-11e8-9baf-69fb25e08f67.png)

![image](https://user-images.githubusercontent.com/18009293/43049154-26613ed0-8dc9-11e8-9b3e-49f57955e035.png)

![image](https://user-images.githubusercontent.com/18009293/43049160-45aa9912-8dc9-11e8-9579-2da1c06907a7.png)

**Comment by tuxtechno** [comment]
Thanks got it, there was browser issue due to which scroll bar was not visible
