### ISSUE TITLE
Auto play wont work on direct Link Videos

### ISSUE THREAD

**Issue by DedSec002** [DanielnetoDotCom/YouPHPTube#886]
Auto play wont work on direct Link Videos. Website says its in compatible on each video ends and restarts the same played video.

This is very annoying :(

**Comment by DedSec002** [comment]
This issue ticket was opened 8 hrs ago.. any help is appreciated.

**Comment by DanielnetoDotCom** [comment]
Hi

Let me understand if you disable the autoplay, the video works but if you enable it to say it is an incompatible video correct?

**Comment by DedSec002** [comment]
Hello Brother,

Link video works fine but if i try to enable the client side autoplay,

the next link video wont start at the current video ends instead it says on top middle screen "No compatible source" and it just replays the current video once again.

I need help on correcting the issue, autoplay works l\fine with embed Youtube videos one after other but not on link video.

Awaiting your response.

**Comment by DanielnetoDotCom** [comment]
Can you please share a sample link and your site?

**Comment by DedSec002** [comment]
Hello,

Here is the setup link:  [https://videobee.in/]

Example links : 

https://www.w3schools.com/htmL/mov_bbb.mp4
http://techslides.com/demos/sample-videos/small.webm

Please enable client side autoplay to understand the problem.

Awaiting your response.

**Comment by DedSec002** [comment]
Hello Brother,

I am currently testing with PHPVibe but I am interested to use YouPHPtube.

Please look into this issue and advise further.

Thank you

**Comment by DanielnetoDotCom** [comment]
Please update your files and try again

**Comment by DedSec002** [comment]
Hi Brother,

The issue is now fixed.

I appreciate your work.

Thank you

**Comment by DanielnetoDotCom** [comment]
Great
