### ISSUE TITLE
Database encoding

### ISSUE THREAD

**Issue by RadekHavelka** [DanielnetoDotCom/YouPHPTube#89]
please add default encoding setting to SQL create scripts. If used on server that is not using UTF-8 as default, streamer and encoder databases are created with the local encoding, which might (and will) cause troubles with usernames, descriptions etc.

**Comment by DanielnetoDotCom** [comment]
What you mean with that?
Does the script need to let the admin choose if the strings need to be encoded or not? is that what you mean?

**Comment by RadekHavelka** [comment]
nope, the database has some "preset" encoding (collation), in which it stores data. Someone has latin1_swedish_ci, someone utf8_general_ci and so on. So I suggest you use 

CREATE DATABASE `whatevername` /*!40100 COLLATE 'utf8_general_ci' */

to create the database in utf8 collation. Else, if you import values that are not in the same encoding, they are either not stored (replaced by ? for example) or are doing weird errors.

**Comment by lysleung** [comment]
I have got the same problem on Chinese (Traditional) characters. Suggest to use collation utf8_general_ci too for MariaDB

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by arveo** [comment]
You don't know what character encoding means? or why do you pretend you never heard?

https://i.imgur.com/EDv30je.jpg

**Comment by BMTTeam** [comment]
I am sorry for beating dead horse, but this is still an issue with languages different from English. For example Cyrillic.

**Comment by DanielnetoDotCom** [comment]
I use, Portuguese by my self and it works fine

**Comment by BMTTeam** [comment]
OK, I am running out of ideas.
The DB is utf8_unicode_ci 
The tables are utf8_unicode_ci 
The SQL connection is (set in my.cnf) - utf8_unicode_ci 
The text in the DB (videos tables) is saved correctly. The problem is when the page is loaded this "тест" turns into this "ÑÐµÑÑ"
Any ideas or clues where to look for?

Also I've checked the whole server if there is somewhere (especially for Apache) if char encoding is being enforced. 

Cheers,
-Tiho

**Comment by DanielnetoDotCom** [comment]
Did you try check or uncheck it ?

![image](https://user-images.githubusercontent.com/18009293/53901342-89b3c500-401d-11e9-9d62-e784c31ba503.png)


did you try it on demo site to see if works?

**Comment by BMTTeam** [comment]
Holy sh*t! That did the trick. Unchecking utf8 (both check marks) and having DB and tables with utf8_unicode_ci, things are like they should be.

Thanks Daniel. :1st_place_medal:  Finally can put the dead horse at rest :)

Cheers,
-Tiho

**Comment by DanielnetoDotCom** [comment]
I am glad it works
