### ISSUE TITLE
i try to update from 5.3 to latest 5.8 version

### ISSUE THREAD

**Issue by karen20ced4** [DanielnetoDotCom/YouPHPTube#890]
Hello, i try to update  from 5.3 to latest 5.8 ver. 

i used ftp winscp to overwrite all files
after overwriting files, i can't login anymore. i look over logs and i find this error. 
[aEC] JS-Err: Uncaught ReferenceError: modal is not defined @ line 349 in file https://mysite.us/user

also the video player is not loading , i see only a black rectangle.
thanks for any help.

**Comment by DanielnetoDotCom** [comment]
make sure when you update you don't skip any update.

also if you getting a blank screen check your log file

**Comment by diroots** [comment]
hello here. 
i am actually on an old version (4.5) and the internal update system tells me I run the latest version

I want to update by copying the next version and then update, but I can't find all the releases. 
Here : 
https://github.com/DanielnetoDotCom/YouPHPTube/releases
and 
https://github.com/DanielnetoDotCom/YouPHPTube/tags
I seem to only find major releases. for example 4.0.2 and then 5.0. Where can i find all versions to go one by one ? (4.6, 4.7, 4.8,..... until latest 5.6)?
If I go with a git pull within the installed directory, i'll only get the latest, right?

**Comment by DanielnetoDotCom** [comment]
if you download the latest version, you will find all the updates there.
just don't miss any update

**Comment by karen20ced4** [comment]
hello, Danie

l. i tried to update 4 site until now, no success. 1 of them is not let me login anymore with admin, so i can't do update from menu. 

the other 3 sites, after i login to admin, i update all steps from menu/update version/   but all my videos are gone. there are still on directory /videos but are not show in myvideos menu or in site.

**Comment by DanielnetoDotCom** [comment]
You have to make sure you don't miss any update, do not skip any of them.

If you already skip, you will need to change the database configuration table, and roll back the version field manually

**Comment by karen20ced4** [comment]
ok, i manage to upgrade from 5.3 to 5.6 with success. (i put versionm 5.4 then upgrade db, 5.5 and 5.6) 
but when i write 5.7 files over 5.6 from hdd,  the video player is no more show the video. seems that video player is not loading

i delete the videos/cache/  but no success until now. 

in FireFox console i have this error:
ReferenceError: videojs is not defined 
VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead

**Comment by DanielnetoDotCom** [comment]
check your streamer log file
