### ISSUE TITLE
Youtube import

### ISSUE THREAD

**Issue by LucasCain2** [DanielnetoDotCom/YouPHPTube#891]
How do I turn off the Youtube Import option/icon? I don't want my site to import from youtube.

**Comment by DanielnetoDotCom** [comment]
Check your site configuration 
![image](https://user-images.githubusercontent.com/18009293/43102137-b09142d0-8ea0-11e8-972a-6fabefcea31d.png)

**Comment by LucasCain2** [comment]
That isn't in the version I have.

**Comment by DanielnetoDotCom** [comment]
that is the latest version, you should update your files
