### ISSUE TITLE
How do i cancel an encoding job that's hung?

### ISSUE THREAD

**Issue by jeffkerby** [DanielnetoDotCom/YouPHPTube#894]
It appears an encoding request is hung, how do I cancel it?

**Comment by DanielnetoDotCom** [comment]
Make sure you are an encoder admin, and delete it from queue job

![image](https://user-images.githubusercontent.com/18009293/43143790-06ab4f12-8f32-11e8-81a0-e6823ff167ed.png)

**Comment by timmayy** [comment]
i had the same problem.

i did exactly this, however it still shows in the queue

queue log tab is empty...

**Comment by DanielnetoDotCom** [comment]
If queue log tab is empty it was deleted , just refresh your page

**Comment by timmayy** [comment]
tried that it still shows.

when any other user log is same thing.

tried refreshing a million times still shows...

**Comment by DanielnetoDotCom** [comment]
Let me understand, it is not on Query Log tab anymore, but it is on Encoding queue?

if yes, it makes no sense

**Comment by timmayy** [comment]
answer is yes...

1. query log tab says "no results" even for admin
2. grey status bar with video title remains on encoding queue screen
3. any user that logs in can see this grey bar

can i refresh the encoder somehow?

**Comment by timmayy** [comment]
yup im admin

easiest way to reinstall encoder?

**Comment by DanielnetoDotCom** [comment]
If you are not admin, you can change it on the database, on the streamer table

**Comment by timmayy** [comment]
got it.

found it in the encoder queue table of database, said something about error downloading original file.  (it was a link form youtube)

**Comment by DanielnetoDotCom** [comment]
if you want to find out, share your encoder log here

**Comment by ccarlile1** [comment]
I have this exact same problem. Was there a fix for this. Video is not listed in the queue log tab but shows in the sharing queue and is stuck at 61% and I can't encode other videos. How can I clear this out?
