### ISSUE TITLE
An error occurred. Please try again later.

### ISSUE THREAD

**Issue by roc-lone** [DanielnetoDotCom/YouPHPTube#896]
Hello,
Currently in my testing I am only using the share link from youtube. I select Embeded in the "Video Form". I have a problem on two videos that can play on youtube with no error but trying to play on my video site I get the error and it will not work on different computers, different locations, or mobile phones. The links will work in any browser but will not work on my YouPHPTube site.
https://youtu.be/I-66U_8l37c
https://youtu.be/h7ZD-66EiP0 
Thank you,
roc
![youtube_error_7-25-2018](https://user-images.githubusercontent.com/41485208/43206058-694090e8-8fea-11e8-9842-2f76baac2bfb.jpg)
![video_form_7-25-2018](https://user-images.githubusercontent.com/41485208/43206066-6c2f4ab0-8fea-11e8-8860-c0c0702ee239.jpg)

.

**Comment by DanielnetoDotCom** [comment]
Instead link https://youtu.be/I-66U_8l37c

Use the link

https://www.youtube.com/watch?v=I-66U_8l37c&feature=youtu.be

**Comment by roc-lone** [comment]
Ok that worked for that link but what about the other link https://youtu.be/h7ZD-66EiP0 and how do I find those links? 
How will a guest know how to get that kind of link when adding a video?

**Comment by roc-lone** [comment]
I understand and it works. What do you do if a guest/user does not know that? We must fix the ones that the guest do and will not work?

**Comment by DanielnetoDotCom** [comment]
It may be improved in the future

**Comment by roc-lone** [comment]
Thanks for the help.
