### ISSUE TITLE
Change Favicon

### ISSUE THREAD

**Issue by xCumSlut** [DanielnetoDotCom/YouPHPTube#898]
i'm usingYouPHPTube as my cms, i can change the logo but there's no option to change the favicon.. can somebody help me?

**Comment by Nisarg22** [comment]
Sorry can u show image of what u mean

**Comment by xCumSlut** [comment]
![desktop screenshot](https://user-images.githubusercontent.com/41649330/43228721-2d610742-9017-11e8-8100-a87b43670204.png)
i wanna change that icon

**Comment by hypedboss** [comment]
Same with me bro, Please how can i change the favicon? or should i naked the script and edit it in head.php?

**Comment by DanielnetoDotCom** [comment]
You will need to replace the file on the server https://<your-site>/view/img/favicon.png

**Comment by gchenfly** [comment]
I have delete the favicon.png. and replace a new one.
But it is still the origin one.

**Comment by DanielnetoDotCom** [comment]
Make sure it is not in your browser cache
