### ISSUE TITLE
Twitter card with large image

### ISSUE THREAD

**Issue by xCumSlut** [DanielnetoDotCom/YouPHPTube#899]
hy.. i want to share my videos on twitter with large image not just summery card.. can somebody help me doing it?

**Comment by DanielnetoDotCom** [comment]
Sorry but you can not use YouPHPTube on porn sites

**Comment by Nisarg22** [comment]
I think that he is not asking about porn he wants to share his videos on twitter just like we share directly to YouTube using youphptube

**Comment by DanielnetoDotCom** [comment]
But his site is a porn site , he not even should being using this app

**Comment by Nisarg22** [comment]
How did you get it

**Comment by Nisarg22** [comment]
Which have you seen his site

**Comment by DanielnetoDotCom** [comment]
Just google for xCumSlut

**Comment by Nisarg22** [comment]
Fuck

**Comment by xCumSlut** [comment]
hahaha.. sorry guys.. but don't worry i just uninstalled it.. sorry for
being such a dick..

**Comment by DanielnetoDotCom** [comment]
@xCumSlut thanks
