### ISSUE TITLE
Encoder queue log size switch is not working correctly

### ISSUE THREAD

**Issue by RadekHavelka** [DanielnetoDotCom/YouPHPTube#90]
On Encoder page, QUEUE LOG, if you have like 50 videos, and you select to display 10, 20, 50, it works as expected. If you select to display ALL, just some 12 are being shown. Refreshing doesn't help.

**Comment by DanielnetoDotCom** [comment]
I will take a look on that soon, thanks for notify that

**Comment by DanielnetoDotCom** [comment]
It is fixed now, thanks
