### ISSUE TITLE
Thumbnail upload issues

### ISSUE THREAD

**Issue by idealsud** [DanielnetoDotCom/YouPHPTube#901]
Hello everyone,

i just configured a new youphptube demo here last week : https://www.welovevideo.fr/demo/

I'm trying to upload a thumbnail for every Vimeo Video i embed.
Upload is ok (green status) and the image is stored in the videos folder but i can't display in the backoffice and the frontoffice viewer.
If i choose to display directly on browsers (direct url) , i ve got a blank screen on  Chrome and error on Firefox.
Example here : https://www.welovevideo.fr/demo/videos/_YPTuniqid_5b5b1956597db0.90052950.jpg?0.8769544485547125

Firefox message : L’image « https://www.welovevideo.fr/demo/videos/_YPTuniqid_5b5b1956597db0.90052950.jpg?0.8769544485547125 » ne peut être affichée car elle contient des erreurs.

I've got another YouPHPTube on this server who actually works perfectly so i don't think it's a server issue, maybe rights when i upload ?

Thanks for your help.
Kind regards, Chris.

**Comment by DanielnetoDotCom** [comment]
Yes, it looks like a permission.
looks like a server miss configuration.
check your apache access.log at the time you try to see an image directly.

**Comment by idealsud** [comment]
Ok solved it was a vhost misconfiguration for this folder.
