### ISSUE TITLE
Direct Video-Link (webm or mp4)

### ISSUE THREAD

**Issue by gujarraju** [DanielnetoDotCom/YouPHPTube#903]
Hi Daniel,
Please check Embed video link "Direct Video-Link (webm or mp4)'' file download  error 
File not found 
Check the file name for capitalization or other typing errors.
Check to see if the file was moved, renamed or deleted.

**Comment by DanielnetoDotCom** [comment]
What video links are you using?

**Comment by gujarraju** [comment]
Direct Video-Link
.mp4 file

**Comment by DanielnetoDotCom** [comment]
but what is the exact link you trying to add and is not working?
