### ISSUE TITLE
Mouse over gif view on video

### ISSUE THREAD

**Issue by honeyfairy** [DanielnetoDotCom/YouPHPTube#904]
The mouse over gif shows on the video listing. 
But it does not show on the video player, it does show the download gif button though.

How can I enable the mouose over gif on the large video player?

**Comment by DanielnetoDotCom** [comment]
can you screen shot what video player are you talking about?

**Comment by honeyfairy** [comment]
![nomouseovergif](https://user-images.githubusercontent.com/17691989/43353646-f30bb2aa-9245-11e8-8b90-ae7b4906301d.PNG)

**Comment by DanielnetoDotCom** [comment]
I see, I think is possible to do that.
but the gif is a low-resolution image, maybe will not have a nice look on this big video
but may be implemented in the future

**Comment by honeyfairy** [comment]
I do not mind if it is a low res image. 
How would this be done?

**Comment by DanielnetoDotCom** [comment]
This needs some code, if you are willing to pay, feel free to contact us on developer@youphptube.com

**Comment by totenkopf83** [comment]
anyád picsája
