### ISSUE TITLE
VideoResolutionSwitcher Plugin?

### ISSUE THREAD

**Issue by afnieves** [DanielnetoDotCom/YouPHPTube#907]
Is there a way to set which video quality is the default? (HD, SD, LOW)?

**Comment by DanielnetoDotCom** [comment]
For now, that is not possible but maybe we will upgrade it in the future

**Comment by CorpCaleCloud** [comment]
There is a plugin you can purchase for that check https://easytube.club/ scroll down the list and you see the below plugin

![resolution](https://user-images.githubusercontent.com/25417743/43991438-bf035b6e-9d64-11e8-88b1-7073874c668a.PNG)

**Comment by idealsud** [comment]
Hi,
Is it possible to set HD by default with the plugin ?

**Comment by DanielnetoDotCom** [comment]
Sorry for now we do not have this option

**Comment by razyalov** [comment]
+1 for this feature

**Comment by SaliC-re** [comment]
still +1 :)

**Comment by ronaldod** [comment]
+1 for me or auto.
