### ISSUE TITLE
How do I edit the Country Codes?

### ISSUE THREAD

**Issue by honeyfairy** [DanielnetoDotCom/YouPHPTube#908]
I would like to change the Country selection from US,TR,TK etc to ENGLISH, TURKISH etc.

How is this done?

Changing the codes in `jquery.flagstrap.js` has no effect

**Comment by DanielnetoDotCom** [comment]
Just create a file with the country code name here https://github.com/DanielnetoDotCom/YouPHPTube/tree/master/locale

for example, tr.php, tk.php, etc

**Comment by honeyfairy** [comment]
I renamed sa.php to ARABIC.php and us.php to ENG.php but there are 2 issues
1. It still shows US even though I cleared the cache and my local cache
2. It does not show the country flag
