### ISSUE TITLE
Suggestion - disable reload of queue page after SEND NOTIFY click

### ISSUE THREAD

**Issue by RadekHavelka** [DanielnetoDotCom/YouPHPTube#91]
When you have more than one page of videos, and you paginate to desired page, and you click on SEND NOTIFY button of one of those videos, the page reloads and you are back on page one. This is from user point of view very annoying behavior, would be better to return the user back to the page where he was.

**Comment by DanielnetoDotCom** [comment]
Yeah, it is an bootgrid (tird party script) that I still not figure out hoe to fix it
I need help for that

**Comment by RadekHavelka** [comment]
yeah, happens on other places as well (if you edit description of the video etc), this will need to be fixed. If i get some time, i will try to find it.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
