### ISSUE TITLE
Download Video" Button

### ISSUE THREAD

**Issue by timmayy** [DanielnetoDotCom/YouPHPTube#910]
site works perfectly except this. awesome job!!

when user click "download Video" button it says "file not found"

path to video file ends like this "234_SD.mp4"
path to "download Video" button like this "234.mp4"

ALL videos on site are SD

how to correct path for "download Video" button?

thanks!

**Comment by DanielnetoDotCom** [comment]
the download button is not 100% yet, it may be fixed in the future, or maybe @hersche can help

**Comment by timmayy** [comment]
for now my solution is after clicking "play" the user can right click and download because that provides correct link. just an fyi

**Comment by DanielnetoDotCom** [comment]
yeah, this is the solution I suggest temporarily

**Comment by hersche** [comment]
i've done a first part in the bootstrap4-branch, but it need some more work (exclude thumbs + dropdown). may i do it later.

**Comment by timmayy** [comment]
thank you both for any and all work you do!!

**Comment by DanielnetoDotCom** [comment]
Latest version you can use a right click.

![image](https://user-images.githubusercontent.com/18009293/45750077-24d9ef00-bbe4-11e8-9231-6c1c4fbb6111.png)

**Comment by weesnaw1** [comment]
Mobile iOS users cannot do this

So in essence there is no way for a mobile user to download a video

**Comment by DanielnetoDotCom** [comment]
sorry, we dont have that for now.
