### ISSUE TITLE
Not Found - 500 Internal Server Error. after git pull

### ISSUE THREAD

**Issue by bgmeet** [DanielnetoDotCom/YouPHPTube#913]
Hello,
i try to upgrade my YouPHPYube but after sudo git pull http://video.lexpoker.tv/update show me blank page. Everything works except update.
Any suggestions ?

Kind Regards

**Comment by DanielnetoDotCom** [comment]
check your log file please

**Comment by bgmeet** [comment]
which log please ?

**Comment by bgmeet** [comment]
Hello,
user login also do not work after git pull

**Comment by DanielnetoDotCom** [comment]
Follow this to get the log file https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by bgmeet** [comment]
Fixed, after upgrade dir right was return to default. change to sudo chown -R admin:admin *
All work perfect now.

Kind Regards

**Comment by DanielnetoDotCom** [comment]
Great
