### ISSUE TITLE
Thumbnails Plugin Portrait Issue 

### ISSUE THREAD

**Issue by md97** [DanielnetoDotCom/YouPHPTube#914]
Scripts working great and installed the thumbnail plugin yesterday. 
Landscape videos works perfectly.
Only problem is with portrait videos... the thumbnail is stretched. 
is there any way to fix this? Aside from manually taking a JPG image from the video...

**Comment by DanielnetoDotCom** [comment]
The portrait videos should have the JPEG correctly, only the gif is stretched
