### ISSUE TITLE
Emeded live stream from youtube

### ISSUE THREAD

**Issue by bgmeet** [DanielnetoDotCom/YouPHPTube#915]
Hello,
i try to get working live stream from youtube channel. For example https://www.youtube.com/watch?v=sQ1tkEIidSk 
which is live, but when i add it to "Add A Live Link" do not work. 
Any suggestion how to make that work ?

Kind Regards

**Comment by bgmeet** [comment]
The link working as ebeded video but do not work with LIVE option that was my mean.
Can "Add A live Link" be modify to use all sourses ? Not only HLS and M3U8 ? Can work with normal url ?

**Comment by DanielnetoDotCom** [comment]
Hi

Live Links is for HLS and M3U8 only, usually, this link comes from your private Live server (Like Wowza or NGINX)

**Comment by bgmeet** [comment]
OK, can then embeded live videos can be marked as Live Status ?  
That will be an option to solve that problem :)
On STATUS you can add LIVE. its that possible ?

Kind Regards

**Comment by DanielnetoDotCom** [comment]
We don't have this feature yet.
may be implemented in the future.
