### ISSUE TITLE
Warning in live links

### ISSUE THREAD

**Issue by Andiweb87** [DanielnetoDotCom/YouPHPTube#916]
Hi , when i enter in live links show this warning

DataTables warning: table id=exampleLinks - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

**Comment by Andiweb87** [comment]
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2245285/youphptube.log)

**Comment by DanielnetoDotCom** [comment]
What about?
```
what link are you entering?
can you reproduce it on demo site? (https://demo.youphptube.com/)
```

**Comment by DanielnetoDotCom** [comment]
I can see this ...

`Prepare failed: (1146) Table 'youPHPTube.LiveLinks' doesn't exist`

Click on the LiveLinks install table on plugin menu

**Comment by Andiweb87** [comment]
its not showing anymore , thank you :)

**Comment by DanielnetoDotCom** [comment]
Great
