### ISSUE TITLE
can i add my site to cloudflare

### ISSUE THREAD

**Issue by joey2354** [DanielnetoDotCom/YouPHPTube#917]
is it ok to add my site to cloudflare or have you already got this sorted ? 

thank you

**Comment by DanielnetoDotCom** [comment]
The limitation for Cloudflare is not from YouPHPTube, the problem with it is regarding your video uploads

Depending on the plan your domain is subscribed to, Cloudflare limits data uploads to the following sizes:

- 100MB Free
- 100MB Pro
- 200MB Business
- 500MB Enterprise

In my opinion even 500MB is not enough for a video site

**Comment by joey2354** [comment]
Ok I see ... thank you

**Comment by timmayy** [comment]
Daniel,

do you have any suggestion for DDOS protection?

**Comment by DanielnetoDotCom** [comment]
Usually the VPS Company I hire to host YouPHPTube they offer DDOS
protection
You may find the same on any company

Em qua, 1 de ago de 2018 02:12, timmayy <notifications@github.com> escreveu:

**Comment by mikweb2017** [comment]
Failtoban ist free and easy to install

**Comment by DanielnetoDotCom** [comment]
For those who want to use CDN/Cloudflare https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Using-CDN-for-Videos-Only
