### ISSUE TITLE
SQL datbase

### ISSUE THREAD

**Issue by timmayy** [DanielnetoDotCom/YouPHPTube#919]
how safe is it to install myphpadmin?

is there a guide/wiki/tutorial?

need to edit SQL database.

thanks!

**Comment by DanielnetoDotCom** [comment]
Sorry but we don't support Phpmyadmin .

Youphptube should handle all his SQL queries, so you don't need it

**Comment by timmayy** [comment]
so Ifi need to edit lets say the "view count" on a set of videos I have to query them individually via command line???

**Comment by DanielnetoDotCom** [comment]
If you can install PHPMyAmin, that is fine, we just don't teach the installation.

but also you can query it manually

**Comment by timmayy** [comment]
is there any extra security risk to adding phpmyadmin? obviously I will use a secure passphrase

**Comment by DanielnetoDotCom** [comment]
I don't know

**Comment by DanielnetoDotCom** [comment]
If you change the SQL password, you need to change it also on the videos/configuration.php file

**Comment by ChrisSlS** [comment]
Oh, thank you @DanielnetoDotCom !

**Comment by timmayy** [comment]
phpmyadmin installed on 3 seperate environments without any fail using this guide. feel free to close.

https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-phpmyadmin-on-ubuntu-16-04
