### ISSUE TITLE
Facebook login issue

### ISSUE THREAD

**Issue by abamilod** [DanielnetoDotCom/YouPHPTube#920]
Please remove 'publish_actions' from parameter for Facebook login API.

**Comment by DanielnetoDotCom** [comment]
Do you have your files up to date?

We fixed a similar problem a while ago.

**Comment by DanielnetoDotCom** [comment]
Do you have your files up to date?

We fixed a similar problem a while ago.

**Comment by abamilod** [comment]
if I remove the 'publish_actions' from parameters in url then its ok. By the way I always keep YPT uptodate using 'git pull'.

**Comment by mikweb2017** [comment]
i same issue

**Comment by mikweb2017** [comment]
http://you-tube.eu/faceboockissue.png

**Comment by DanielnetoDotCom** [comment]
I think is fixed now

**Comment by abamilod** [comment]
thank you. it works now.
