### ISSUE TITLE
help in installation

### ISSUE THREAD

**Issue by Chibuzor12** [DanielnetoDotCom/YouPHPTube#922]
after moving youphptube file and folders to var/www/html,
if i want to install it to my server i will have this error massage

 It appears that either something went wrong or the mod rewrite configration is not correct.

If you don't use apache, just let .htaccess stay or create a empty file - then this check will pass.

We need to allow Apache to read .htaccess files located under the /var/www/html directory. You can do this by editing the Apache configuration file:

Find the section <directory /var/www/html> and change AllowOverride None to AllowOverride All

sudo nano /etc/apache2/apache2.conf

After editing the above file your code should be like this:

<Directory /var/www/>
          Options Indexes FollowSymLinks
          AllowOverride All
          Require all granted
  </Directory>

In order to use mod_rewrite you can type the following command in the terminal:

sudo a2enmod rewrite

Restart apache2 after

sudo /etc/init.d/apache2 restart

or

sudo service apache2 restart

i have don all the requirement in my server still not work

**Comment by DanielnetoDotCom** [comment]
Is not clear what is not working, but you can hire us to install it for you here: https://www.youphptube.com/services

**Comment by Chibuzor12** [comment]
it show error i have configure it but still yet

**Comment by DanielnetoDotCom** [comment]
Probably your mod rewrite is wrong.
Try google to properly configure it

**Comment by Chibuzor12** [comment]
after enabeling mod rewrite and install the script it give this error  


Content Encoding Error

The page you are trying to view cannot be shown because it uses an invalid or unsupported form of compression.

    Please contact the website owners to inform them of this problem.

**Comment by DanielnetoDotCom** [comment]
Ok, I am aware of this error, but your script was successfully installed,  please remove the **install/index.php** and you should be all set.

this error will be fixed soon

**Comment by Chibuzor12** [comment]
ok

**Comment by Chibuzor12** [comment]
i have don it it return 404 error when i click on any page you can check it
 http://158.69.204.208/YouPHPTube/

**Comment by DanielnetoDotCom** [comment]
Looks like working for me

![image](https://user-images.githubusercontent.com/18009293/43528195-c7373db6-957e-11e8-8252-4fd45462b5c5.png)

**Comment by Chibuzor12** [comment]
click log in

**Comment by DanielnetoDotCom** [comment]
So you may be missing some files, make sure you upload them all

**Comment by Chibuzor12** [comment]
let me dellet and renstall

**Comment by DanielnetoDotCom** [comment]
make sure you use **git clone** command, as described on the tutorial

**Comment by hersche** [comment]
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Message-when-rewrite-is-not-set

**Comment by Chibuzor12** [comment]
it work on my domain/youphptube
but after moving it to my var/www/html the error massage appear

**Comment by DanielnetoDotCom** [comment]
make sure you moved all files (including .htaccess) and you properly changed the videos/configuration.php 

also check here https://tutorials.youphptube.com/video/fix-youphptube-url-after-move-server-location-and-ip

**Comment by Chibuzor12** [comment]
after successful installation it took too long to laod upload page like 3minutes
check http://158.69.204.208/upload

**Comment by DanielnetoDotCom** [comment]
You will need to check your browser console and see what is taking too long to load

**Comment by Aditya16429** [comment]
http://localhost/AVideo-master/install/
Write install/ after your url if you are using domain or localhost
