### ISSUE TITLE
Problem installing encoder on CentOS 7 (exiftool)

### ISSUE THREAD

**Issue by siteleas** [DanielnetoDotCom/YouPHPTube#923]
I have the main site installed and am now working on getting the encoder site working. The problem is that I am running CentOS 7 and trying to get the libimage-exiftool-perl requirement resolved. All other requirements check out from the install script, but that one problem seems to be preventing the encoder from installing (even though exiftool is installed on the server). So when I attempt to install the encoder, I get a white rounded rectangle that sits there like a dead duck for what seems to be an eternity and so far it has not gone away. How do I diagnose and resolve this problem so that I can get our service up and running?

![image](https://user-images.githubusercontent.com/658069/43553014-4f3b82fa-95aa-11e8-9e7e-ed5b54bdf8da.png)

**Comment by siteleas** [comment]
I have double checked and in fact no tables have been created in the MySQL database even though credentials were provided to the script, so whatever is hanging the script up appears to be happening prior to the tables being created.

**Comment by DanielnetoDotCom** [comment]
Hi

Maybe you have no problem with the missing libimage-exiftool-perl, just ignore it.

on the image there is not much information what is going on, you may want to check your apache log
