### ISSUE TITLE
clone site tutorial

### ISSUE THREAD

**Issue by timmayy** [DanielnetoDotCom/YouPHPTube#925]
video link broken

https://tutorials.youphptube.com/video/backup-or-clone-your-site

UPDATE: seems to only work in chrome..

**Comment by DanielnetoDotCom** [comment]
This is odd, this is also happening on my side, and I still not detected what is wrong

**Comment by DanielnetoDotCom** [comment]
I found this 

```
A mídia https://tutorials.youphptube.com/videos/_YPTuniqid_5b3b8285f03757.94872174_Low.mp4 não pôde ser decodificada, erro: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)
Details: auto __cdecl mozilla::SupportChecker::AddMediaFormatChecker::<lambda_999535078a112c9fd6d76606f38e80ee>::operator ()(void) const: Decoder may not have the capability to handle the requested video format with YUV444 chroma subsampling.
```

Looks like I use the wrong codec on that.

**Comment by DanielnetoDotCom** [comment]
For now, I am lost, does not matter what coded I use on it, it keeps the same error

**Comment by timmayy** [comment]
strange, even safari on my phone doesnt work only chorme desktop...

thanks for looking into it

**Comment by Nisarg22** [comment]
![screenshot_20180803-061908](https://user-images.githubusercontent.com/39002772/43618328-2f57f216-96e5-11e8-9870-c639f452e314.jpg)
This is what I found in chrome

**Comment by DanielnetoDotCom** [comment]
I tried to use FFMPEG to encode with different codecs and it does not work
I dont know what I did with this video

**Comment by Nisarg22** [comment]
If problem is with only this video u can re-upload it but u should check other videos also

**Comment by DanielnetoDotCom** [comment]
I did, and it is only in this video. I re-upload.

**Comment by Nisarg22** [comment]
![screenshot_20180803-070845](https://user-images.githubusercontent.com/39002772/43619545-1b46b30a-96ec-11e8-8416-2e6358e28251.jpg)
Problem continues

**Comment by Nisarg22** [comment]
There are many plugins not available either free or paid from the list of.gitignore

**Comment by Nisarg22** [comment]
R they coming in future?

**Comment by DanielnetoDotCom** [comment]
Which plugin are you interested?

**Comment by DanielnetoDotCom** [comment]
FYI, some of them are for a specific customer, some others are already ready to use, but I will release in the future.

**Comment by DanielnetoDotCom** [comment]
@timmayy I did that and still the same problem

**Comment by abamilod** [comment]
this happens when you use s3 storage with the video.

**Comment by DanielnetoDotCom** [comment]
It will copy the videos locally.
