### ISSUE TITLE
Comment without Registration

### ISSUE THREAD

**Issue by md97** [DanielnetoDotCom/YouPHPTube#927]
Is it possible to set it up to allow comments without user registration? 
I've tried editing videocomments.php but can't quite get it to post... any suggestions? Potential future plugin?
Any help is greatly appreciated.

**Comment by DanielnetoDotCom** [comment]
Non logged users cant comment.

I don't understand the issue with edit comments

**Comment by Nisarg22** [comment]
He means that he wants everyone can comment either that person has account in site or not doesn't matter

**Comment by DanielnetoDotCom** [comment]
It is not possible, only logged users can comment

**Comment by CorpCaleCloud** [comment]
why would you want this? it would encourage spanner and porn ads on your page. not a good option
