### ISSUE TITLE
Site Is Blank and Am Unable To Sign-In

### ISSUE THREAD

**Issue by bbyrdhouse** [DanielnetoDotCom/YouPHPTube#928]
Hi,

You performed an install for me 2 days ago and I have slowly been getting used to everything. Yesterday the site was working nicely until I tried to upload a video from my local machine. It failed to upload both times, so I just closed things down and went to bed. This morning when I tried again, I went to my site and was presented with a blank page that said no videos (even the ones I had imported from Youtube were gone).

I tried to sign-in and was presented with an error saying I needed to upgrade to version 2.13. I then tried to sign in and it did not recognize my username/password

I notice that the logo has reverted back to the YouphpTube logo instead of the one I had added. The site title is gone ... 

What could have happened and how to prevent it from happening again.

https://boomvu.com

Thanks
Gary

**Comment by DanielnetoDotCom** [comment]
I am supporting you on the email developer@youphptube.com

**Comment by DanielnetoDotCom** [comment]
on your server 
![image](https://user-images.githubusercontent.com/18009293/43636728-4ef91b50-96e9-11e8-9fe7-7ae147e2a80c.png)

MySQL Fail, have you done something on it? I cant start

**Comment by DanielnetoDotCom** [comment]
I tried this solution https://stackoverflow.com/questions/44573776/mysql-wont-start-anymore 
It does not work

![image](https://user-images.githubusercontent.com/18009293/43637072-3c9ba490-96ea-11e8-95df-f92994361e74.png)

Why so low space?
Why I am root and I can't edit `/etc/apparmor.d/usr.sbin.mysqld` ?

**Comment by DanielnetoDotCom** [comment]
Ok, I could access /etc/apparmor.d/usr.sbin.mysqld and does not work.

You need to tell me what did you change on the server

**Comment by DanielnetoDotCom** [comment]
Ok, got it you are out of space

![image](https://user-images.githubusercontent.com/18009293/43637688-4e277d18-96ec-11e8-8b60-56fd24016ebd.png)

**Comment by bbyrdhouse** [comment]
I didn't do anything ... honestly ... I can't log-in and wouldn't even try to without Plesk or some other type of GUI.

**Comment by DanielnetoDotCom** [comment]
I dont know why you have so low space on a dedicated server

**Comment by bbyrdhouse** [comment]
How can I be out of space? There are only like 4-5 videos on the whole site

**Comment by DanielnetoDotCom** [comment]
you have max 6GB drive, it is really not enough.

you should have at least 50 GB even if you store your videos on S3

**Comment by bbyrdhouse** [comment]
The server has 60Gb ...

**Comment by DanielnetoDotCom** [comment]
Where is it? the largest drive you have is 5.9 Gb

![image](https://user-images.githubusercontent.com/18009293/43637813-c06a56d4-96ec-11e8-8b08-520563d553fb.png)

**Comment by DanielnetoDotCom** [comment]
If you want, rebuild the server, create a partition with at least 50 GB I will reinstall for you.

**Comment by bbyrdhouse** [comment]
Sigh ... I don't know ... I re-imaged the server the other day before you installed your script, so it should have been a clean slate ...

**Comment by DanielnetoDotCom** [comment]
try to reimage it again. but paid attention on the drives and partitions

**Comment by bbyrdhouse** [comment]
they are repartitioning right now for me and will have 512 Gb of storage ... this should do until I can purchase the S3 plugin ... they Sid it will take about 10 minutes

**Comment by bbyrdhouse** [comment]
Ok, that was the issue because once the main partition size was increased then everything is working again.

**Comment by DanielnetoDotCom** [comment]
I see, so no need to reinstall correct?

**Comment by bbyrdhouse** [comment]
correct
