### ISSUE TITLE
email setup issue

### ISSUE THREAD

**Issue by Chibuzor12** [DanielnetoDotCom/YouPHPTube#929]
after setting up my gmail smt i have this error
![erro](https://user-images.githubusercontent.com/41998938/43647426-798619ec-96ec-11e8-8b5d-749107029e6d.png)
![error](https://user-images.githubusercontent.com/41998938/43647427-79d2af96-96ec-11e8-9b98-bc9b1ba2a54f.png)

**Comment by Chibuzor12** [comment]
any help please

**Comment by DanielnetoDotCom** [comment]
That is how I have at home and it works fine, the only difference I see is that I use tls in lower case.

also make sure to save the changes before test it

![image](https://user-images.githubusercontent.com/18009293/43664080-f07a0f72-9741-11e8-95cd-aaa4aef38af6.png)

**Comment by Chibuzor12** [comment]
i changed it to small latter but it still showing the error

**Comment by Chibuzor12** [comment]
![eror 2](https://user-images.githubusercontent.com/41998938/43674029-eaf15232-9781-11e8-8019-f3f6c708eeee.png)
![erro 1](https://user-images.githubusercontent.com/41998938/43674031-eb74529a-9781-11e8-89a8-15b2f84c1629.png)

**Comment by DanielnetoDotCom** [comment]
I am not sure what is wrong, check if your server is not blocking any output port
