### ISSUE TITLE
Raw PHP Code

### ISSUE THREAD

**Issue by joevotto** [DanielnetoDotCom/YouPHPTube#93]
Hello, I have followed your video step by step with no problems until 08:14. When I restart the service, and refresh the page instead of seeing the YouPHPTube webpage wth the install script screen, I instead see raw PHP code, so I am unable to move on. How can I resolve this? Thanks﻿ Screenshot included  
![screenshot](https://user-images.githubusercontent.com/11413118/29522980-8ab6d69e-8648-11e7-8fe7-6bdd06417e5a.png)

**Comment by DanielnetoDotCom** [comment]
It looks like your PHP is not installed correctly

**Comment by joevotto** [comment]
What would you recommend as to how to properly install it? I know when I input the command the terminal was unable to find libapache2-mod-php7.0. Is that the correct name of the package?

**Comment by DanielnetoDotCom** [comment]
What is your linux version?
You may not have PHP7.0 on your apt-get, check what version you have available
Try google an tutorial how to install LAMP

**Comment by joevotto** [comment]
I am not running Linux, I am using the Virtual Machine from Amazon ECS to install the script.

**Comment by DanielnetoDotCom** [comment]
You can choose to install linux Ubuntu on that

**Comment by DanielnetoDotCom** [comment]
Try to run this command to see what PHP do you have available

`apt-cache search php`

**Comment by joevotto** [comment]
I am running 7.0.22 and I am using the tutorial I found on I believe your Youtube channel to install it on Ubuntu virtual machine via Amazon.

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
