### ISSUE TITLE
there was an error message when i using AD_server plugin

### ISSUE THREAD

**Issue by FunnyRyan** [DanielnetoDotCom/YouPHPTube#931]
there was an error message when i using AD_server plugin "DataTables warning: table id=campaignTable - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1"

**Comment by FunnyRyan** [comment]
and i can't create Campaign

**Comment by DanielnetoDotCom** [comment]
make sure you clicked on the install tables button on the plugin menu 

![image](https://user-images.githubusercontent.com/18009293/43664246-a3fd0dba-9742-11e8-8c20-60097952710b.png)

**Comment by roc-lone** [comment]
![plugins_no_install_tables_8-3-2018](https://user-images.githubusercontent.com/41485208/43667636-7bfdec52-973e-11e8-8a4d-e046fba42978.jpg)
Daniel remember I cannot see the "Install tables" on the Customize (Customize) I purchased and still don't see it. Well I see in the screen shot that I should have "Install tables" for the AD_Server (AD_Server) plugin. I do not have "Install tables" on any of my plugins and do not have AD_Server_Location (Ad_Server_Location) or AWS_S3 (AWS_S3) showing in my plugins.

**Comment by DanielnetoDotCom** [comment]
OMG, you are the only user that report you can't see the button.

But if you manually install the install.sql file you should be fine

**Comment by roc-lone** [comment]
Perhaps I'm the only one because others don't know they are suppose to have the buttons. I did not know until I purchased the one plugin it should be there. I will do it manually again but perhaps you should tell me all the plugins I will need to do it manually for since I have no buttons.

Thank you,
roc

**Comment by DanielnetoDotCom** [comment]
> Perhaps I'm the only one because others don't know they are suppose to have the buttons.
If the plugin have "install button" it will not work untill you install it.

Also, some free plugins have install buttons.

If there is the install directory on the plugin you should have the install button.

check on demo site, all plugins that have install buttons

**Comment by CorpCaleCloud** [comment]
I have installed the AD manger and it works for me, first I enabled then installed the table and the admin option appeared I suggest disabling, restarting the server and enable and see if the option appears if not then restart the server and check again whilst its enabled. let us know how you get on.

![ad plugin working](https://user-images.githubusercontent.com/25417743/44077934-202a3f36-9f9d-11e8-92b3-364f8c6a0b29.PNG)

**Comment by CorpCaleCloud** [comment]
also check the edit parameters to make sure it's started
its the first tick box on the menu (check against mine in the image)

![ad plugin working 2](https://user-images.githubusercontent.com/25417743/44078061-78219db0-9f9d-11e8-8528-52856e7b78ce.PNG)

**Comment by DanielnetoDotCom** [comment]
@CorpCaleCloud  sorry but I don't understand what is the issue
