### ISSUE TITLE
All videos in My videos available to Admin & Regular user

### ISSUE THREAD

**Issue by roc-lone** [DanielnetoDotCom/YouPHPTube#932]
I have another user testing with me and they are registered as a Regular user. When the Regular views videos under My videos they are able to not only see their videos but the video that was placed under the Admin's My videos. They can also edit and delete videos that they did not input. Can you please advise as to how to restrict Regular users from having access to the videos of the Admin?

Thank you,
roc

**Comment by DanielnetoDotCom** [comment]
If you user is not an Admin, he does not suppose to edit somebody else videos.
Make sure he is not an Admin, regular users can only edit his own videos.

**Comment by roc-lone** [comment]
Yes, I did verify that the user is a Regular user. I can send you screen shots if you need to see for yourself. I tested that the Regular user was able to delete a video. All the videos I am talking about are embedded.

**Comment by roc-lone** [comment]
Please disregard this ticket until I do more testing. I will answer back.

Thank you,

**Comment by roc-lone** [comment]
Got it figured out. May have been user error.

Thank you for your time.
