### ISSUE TITLE
clone site not working

### ISSUE THREAD

**Issue by timmayy** [DanielnetoDotCom/YouPHPTube#933]
when I use clone site it only copies admin account and videos

not all other user accounts..

**Comment by DanielnetoDotCom** [comment]
It supposes to copy all accounts

**Comment by timmayy** [comment]
i know but is only copies admin account.
0 photos
0 users

its like  it copies all the videos but not the database

**Comment by DanielnetoDotCom** [comment]
something is wrong, it copy all your database

maybe it does not made the clone correctly

**Comment by timmayy** [comment]
can i manually copy sql database?

**Comment by DanielnetoDotCom** [comment]
I don't think it will be enough, the script will copy the database and media files.

check your log file for the Master and for the Slave clone

**Comment by timmayy** [comment]
it copies the media including videos and logo,

but database stays blank

**Comment by timmayy** [comment]
ill check log and report back

**Comment by DanielnetoDotCom** [comment]
Make sure on the slave side the database user has rights to create table

**Comment by timmayy** [comment]
for now i 
1. installed phpmyadmin
2. secured .htaccess
3.exported entire database
4. imported databse into clone

seems to be working now...

**Comment by rob-lindman** [comment]
timmayyyyyyyyyy! 

On 2018-08-04 17:36, timmayy wrote:

> for now i 
> 
> * installed phpmyadmin
> 
> * secured .htaccess
> 3.exported entire database     * imported databse into clone
> 
> seems to be working now... 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1]
https://github.com/DanielnetoDotCom/YouPHPTube/issues/933#issuecomment-410479114
[2]

**Comment by DanielnetoDotCom** [comment]
@timmayy , so the database is exporting and importing now correct?

**Comment by timmayy** [comment]
using site clone is moves media and photos only

i manually installed phpmyadmin and exported the database from master then imported to slave.

**Comment by DanielnetoDotCom** [comment]
It may work also, but will be good if you try to figure out why it does not import the database
