### ISSUE TITLE
APP unavailable

### ISSUE THREAD

**Issue by timmayy** [DanielnetoDotCom/YouPHPTube#934]
unable to get the app to load in browser at all.

from iphone is says "unavailable in US store...."

https://itunes.apple.com/us/app/youphptube/id1337322357

**Comment by DanielnetoDotCom** [comment]
Here is your answer

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/About-Mobile-app

**Comment by timmayy** [comment]
ahh okay thanks
