### ISSUE TITLE
livestream does not work - NET::ERR_CERT_DATE_INVALID involved ?

### ISSUE THREAD

**Issue by ChrisSlS** [DanielnetoDotCom/YouPHPTube#935]
Hello,

The problem is pretty simple, but I'm stuck. This comes from the expired ssl certificate only on the page https://domain.com:444/stat

Normally certbot autorenews the certificates, and it does, except on this page. impossible to execute the command "cerbot renew" this returns an error :

`Could not automatically find a matching server block for domain.com. Set the `server_name` directive to use the Nginx installer.. Skipping`

I'm not sure I understand. @DanielnetoDotCom had done my installation and everything worked fine until the last update (but I think it does not come from that)

**Comment by DanielnetoDotCom** [comment]
@ChrisSlS contact on the email developer@youphptube.com with your server credentials and YouPHPTube admin pass I will update your SSL for you.

I don't know if you change something but `cerbot renew` should work with no problem
