### ISSUE TITLE
Play problem 

### ISSUE THREAD

**Issue by rullzor** [DanielnetoDotCom/YouPHPTube#936]
when I uploaded a movie, it is not possible to press play it does not even load what has i done for errors

**Comment by DanielnetoDotCom** [comment]
can you please check your browser developer tools if there is an error?

also the source code to find out if the video file exists

**Comment by CorpCaleCloud** [comment]
Do you get an encoder error when the video has uploaded? check my video once the files has uploaded in in the time session if it say's "EE:EE:EE" then there is an error with the encoding I have had serval files. 

what software are you using to download? try this one is real good but remember to set the file type to the one on YouTube e.g., 720p HD

https://mrs0m30n3.github.io/youtube-dl-gui/ YouTube DLG (open source YouTube Downloader)

see image below - the files is 1080pHD so I set the MP4 file to the same add to queue then download. I done load in batch my 1080p HD and 720p HD. you can extra audio add all the meta data etc so its all good.

![1080p](https://user-images.githubusercontent.com/25417743/43991803-dc82d820-9d6b-11e8-81cf-fd6b1cf978d3.PNG)

**Comment by DanielnetoDotCom** [comment]
maybe the EE:EE:EE was regarding a memory leak/crash regarding the file size

**Comment by CorpCaleCloud** [comment]
could be I changed mine to 5GB upload by editing the php.ini


edit the php.ini in two location, one for the file size and the other edits the text indicating the file size on the upload menu: PostMax and UploadMax

location of the PHP.INI file to edit
![php ini size increase](https://user-images.githubusercontent.com/25417743/44053561-f4b1cd8e-9f37-11e8-94d7-ffd45a282426.PNG)

change the file size to 5GB - 108p HD is 4GB max I find
![upload image error 2](https://user-images.githubusercontent.com/25417743/44053562-f4e2b9bc-9f37-11e8-9ce1-12967faf103f.PNG)

change the text so it displays 5GB in the upload menu
![upload image error 3](https://user-images.githubusercontent.com/25417743/44053564-f50d80b6-9f37-11e8-8979-442f6ceddeb3.PNG)

that's it your all done

**Comment by DanielnetoDotCom** [comment]
There is a script calculation..., your maximum file size can be only 50% of your RAM memory, because the script needs to copy files between locations and handles it on the virtual memory.

In Example, if you want to upload a 4GB file you will need to have at least 8 GB Ram on the server other wise you will have a Memory Leaks - Allowed memory size of # bytes exhausted error.
