### ISSUE TITLE
FB Login Error

### ISSUE THREAD

**Issue by md97** [DanielnetoDotCom/YouPHPTube#940]
Set up FB login with the plugin but when I try to login, facebook gives the error:

Invalid Scopes: user_friends, publish_actions. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

any suggestions?

**Comment by DanielnetoDotCom** [comment]
Make sure you have the latest branch, it was fixed here 
https://github.com/DanielnetoDotCom/YouPHPTube/issues/920

**Comment by md97** [comment]
So I tried deleting user_friends, publish_actions from the facebook.php file... and now I get this error when I click the button...
HTTP 500 error
That’s odd...  the website can’t display this page
The site may be under maintenance or could have a programming error.
--
any suggestions?

**Comment by DanielnetoDotCom** [comment]
If you read the full issue you will notice this error was fixed and you no longer need to delete anything . Just update your files and you will be good

**Comment by ChrisSlS** [comment]
I have the same problem, and this also happens on the demonstration site https://demo.youphptube.com
Here is my log file : 

`[10-Aug-2018 03:47:15 Europe/Berlin] Start Login Request
[10-Aug-2018 03:47:15 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function currentVersionLowerThen() on array in /var/www/html/YouPHPTube/objects/user.php:336
Stack trace:
#0 /var/www/html/YouPHPTube/objects/user.php(802): User->save()
#1 /var/www/html/YouPHPTube/objects/login.json.php(82): User::createUserIfNotExists('***@***....', '****...', 'User name', '***@***....', 'https://graph.f...')
#2 {main}
  thrown in /var/www/html/YouPHPTube/objects/user.php on line 336`

I am currently looking for the problem. I have tried various settings of the API but nothing works.

**Comment by DanielnetoDotCom** [comment]
@ChrisSlS what do you mean this happened on demo site?

your log file is regarding a database error.

check your MySQL server

**Comment by ChrisSlS** [comment]
if i want to connect using Facebook, on my site or on the demo site, it does not work. What's strange with this bug is that it only affects two or three users. Facebook login otherwise works on my site (but 500 error for some people), but not at all on the demo site, look:

![bgu](https://user-images.githubusercontent.com/37787071/43970991-b0a4d538-9ccf-11e8-85f8-3966f1606453.png)

Thank you for your answer, I will see in the database.

**Comment by DanielnetoDotCom** [comment]
I see, 

So it happened with some specifics users right?

should be an error regarding this on YouPHPTube side.

I will be glad if you can track what error is this on your side.

I am asking this because I can not reproduce this error on my side.

**Comment by DanielnetoDotCom** [comment]
I see, the problem is regarding username change, humm.

Maybe I will need do deny OAuth users change their usernames
