### ISSUE TITLE
News feed/rss

### ISSUE THREAD

**Issue by weesnaw1** [DanielnetoDotCom/YouPHPTube#943]
Any way to add a news feed/ticker/rss ?

**Comment by DanielnetoDotCom** [comment]
You can just add /feed/ on your URL and you will be fine 

https://demo.youphptube.com/feed/

**Comment by weesnaw1** [comment]
True but I want to add a simple ticker to the homepage for people to read while clicking through pages...

**Comment by DanielnetoDotCom** [comment]
What do you mean?

**Comment by weesnaw1** [comment]
![3ed4828d-7f8a-4d5d-861f-1e62ec0e160d](https://user-images.githubusercontent.com/34515699/43850129-f743fbda-9aeb-11e8-8939-f8a2b21ce750.jpeg)


For example circled in red.

**Comment by DanielnetoDotCom** [comment]
So you want to add a banner with some external or internal rss sources on youphptube?

If yes, we don't have it done

**Comment by DanielnetoDotCom** [comment]
We don't have that but we can build if you are willing to pay
