### ISSUE TITLE
Changed Password, need to change server url parameters ... 

### ISSUE THREAD

**Issue by bbyrdhouse** [DanielnetoDotCom/YouPHPTube#944]
Hi, 
I have changed my user password and need to change the server url parameters so that I can use live streaming again. Please tell me where I can do this.

The problem I am having is that OBS is failing to connect to the server when trying to Livestream. The only change I made to anything was changing my password from the default "123" to something different.

Thank you

**Comment by DanielnetoDotCom** [comment]
Check your live menu for the new parameters 

![image](https://user-images.githubusercontent.com/18009293/43954059-71ede61c-9c71-11e8-80b7-dc4a42d3aef0.png)

**Comment by DanielnetoDotCom** [comment]
I see

did you reboot the server?
I just checked your server, looks like NGINX was not running.

I just start NGINX again with this command 

`/usr/local/nginx/sbin/nginx`

You should be fine now, can you please try again?

**Comment by bbyrdhouse** [comment]
It is working again ... what would have caused NGINX top running?

**Comment by bbyrdhouse** [comment]
What about the Chat Connection failing to connect?

**Comment by DanielnetoDotCom** [comment]
I dont know, why it stops.

It suppose to start in any reboot.

I just run the chat command

`nohup php /var/www/html/YouPHPTube/plugin/LiveChat/chat-server.php &`

It should be fine again

**Comment by bbyrdhouse** [comment]
thnx ... bookmarking this page so I won't have to ask again ... Now if I can just sort out recording a stream and sending it to the encoder ... I wish that the plugins cam with a bit more instructions

**Comment by DanielnetoDotCom** [comment]
Did you see this? https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Record-Live-Stream

What it does is to send your recorded live stream to the encoder when it is done

**Comment by bbyrdhouse** [comment]
thank you ... I just needed to edit the NGINX file ... it is working now

**Comment by DanielnetoDotCom** [comment]
Great
