### ISSUE TITLE
User_Location (User_Location)

### ISSUE THREAD

**Issue by timmayy** [DanielnetoDotCom/YouPHPTube#945]
1. ran command
2. installed tables
3.turned on plugin
4."edit parameters box" says: the following

![plugin](https://user-images.githubusercontent.com/41845310/43924479-9c7639a4-9bd9-11e8-88de-573ba787c390.JPG)

how do I actually "use" the plugin?

**Comment by DanielnetoDotCom** [comment]
Please check this 

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/User_location-Plugin

**Comment by timmayy** [comment]
that does not explain anything about my issue.

for example.
1. what do I click to actually see the IP addresses?
2.what significance is the edit parameters box

**Comment by DanielnetoDotCom** [comment]
> 1. what do I click to actually see the IP addresses?

You cant see the IP address, it is used internally 

> 2. what significance is the edit parameters box

There is nothing to edit
