### ISSUE TITLE
Login Page Sticking

### ISSUE THREAD

**Issue by mrtick2002** [DanielnetoDotCom/YouPHPTube#947]
I'm having an issue with the login page sticking. http://prntscr.com/kh4zxi

**Comment by DanielnetoDotCom** [comment]
Please check your log file

**Comment by CorpCaleCloud** [comment]
I had the same issue when I changed the admin username to my own account name and it's get confused still thinking its the admin account even though you changed the account details. if that's the case login with another account (if created) and rename back to admin, then create a new account with admin rights using the name you want to use as per the image. 

If its a new account created and your just logging in to test a account after creation within a few second of creating completion then it might need time to create the account update the system. So refresh the browser or restart the host server or apache2 server and try again, I know its it sounds drastic but it worked for me as I'm self hosting.

Now, I only work from the new admin account and don't touch the default one and as the system is stable I deleted the admin account and its all good as gold.

**Comment by DanielnetoDotCom** [comment]
I could not reproduce this error

**Comment by Andiweb87** [comment]
same issue , i checked the log file and have only this 

[13-Aug-2018 03:11:45 America/New_York] PHP Fatal error:  Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:8888": Address already in use in /var/www/html/YouPHPTube/plugin/LiveChat/ratchet/react/socket/src/TcpServer.php:164
Stack trace:
#0 /var/www/html/YouPHPTube/plugin/LiveChat/ratchet/react/socket/src/Server.php(31): React\Socket\TcpServer->__construct('tcp://0.0.0.0:8...', Object(React\EventLoop\StreamSelectLoop), Array)
#1 /var/www/html/YouPHPTube/plugin/LiveChat/ratchet/cboden/ratchet/src/Ratchet/Server/IoServer.php(59): React\Socket\Server->__construct('0.0.0.0:8888', Object(React\EventLoop\StreamSelectLoop))
#2 /var/www/html/YouPHPTube/plugin/LiveChat/chat-server.php(20): Ratchet\Server\IoServer::factory(Object(Ratchet\Http\HttpServer), '8888')
#3 {main}
  thrown in /var/www/html/YouPHPTube/plugin/LiveChat/ratchet/react/socket/src/TcpServer.php on line 164

**Comment by Andiweb87** [comment]
i have just refreshed the page and im in now after some minutes of Proccesing , when i log out is ok , seems only when login have this issue

**Comment by CorpCaleCloud** [comment]
like I as said " Address already in use in " so seem like a conflict of interest error did you change the admin account name e.g. admin to andiweb or something hence the confusion. try creating a new user with admin rights and login as that account. now log out and in as the new account a few times to check the process, if this works keep using the new account and delete the old one or keep it up to you. but you need a fail safe just encase you cant login or it freezes up I'm not saying it will but best to safe then locked out.

**Comment by Andiweb87** [comment]
hi i made an update 2 days ago , maybe something create this issue, i used this account from the begining with no problems, this issue show up only after the update ......

**Comment by DanielnetoDotCom** [comment]
@Andiweb87 your error is regarding the LiveChat

if you are not using it you should not worry, or just restart your server you should be fine.

**Comment by Andiweb87** [comment]
the issue ish show up again
