### ISSUE TITLE
image Quality Distorsion on Site Config page - Home Button logo

### ISSUE THREAD

**Issue by CorpCaleCloud** [DanielnetoDotCom/YouPHPTube#948]
When I upload and image to YouPHPTube to edit my home icon (top left corner) the quality is good until its save, then quality changes to distorted can anyone explain why? ( I refresh after saving to see the changes)

created the image using MS Publisher (not paying for Photoshop) and saved as a 300 dpi jpeg or png, etc whatever I use the quality changes to distorted once saved but only on this page when I edit my account page it resolve without issue all good quality. once the image is saved it appears in the top right hand corner as a home button link

Distorted after saving see top left hand corner and the image upload box also distorts
![errorwithimage01](https://user-images.githubusercontent.com/25417743/43991363-47b586be-9d63-11e8-9df7-11951c6dfd2a.jpg)

**Comment by DanielnetoDotCom** [comment]
The app resample the image and make it smaller to fit on the left side without waste bandwidth regarding the image size.
So the feature is working like was expecting

**Comment by CorpCaleCloud** [comment]
if you gave use the dimensions under the You Logo we could create a good logo without fear of losing quality as you have the resize slider so basically we use the slider and it resizes losing quality and looks bad. If we knew the dimensioned then we could create the image according to the dimensions and not lose quality. is it possible to know the dimension so eliminate this error?

**Comment by CorpCaleCloud** [comment]
thank you, I managed to download a copy of the logo and it indicates 671 x 146 depth 32 however you update it I use that sizing, thanks

![logodimen](https://user-images.githubusercontent.com/25417743/44040224-a3f97330-9f12-11e8-83a5-e830ccc2a667.PNG)

**Comment by CorpCaleCloud** [comment]
pending edit of dimensions on the server but closing as I trust this will get done.
