### ISSUE TITLE
Hide Video URL like YouTube

### ISSUE THREAD

**Issue by CorpCaleCloud** [DanielnetoDotCom/YouPHPTube#949]
is it possible to hide the video url like YouTube as per the image example below

![hide video url like yourube](https://user-images.githubusercontent.com/25417743/43997528-bc3615b8-9dd5-11e8-8997-e4497777c6f0.PNG)

as you can see it has https://www.youtube.com/ (" this is the hidden part **"watch?v=PmZjaYdS3fA**"~) a the end of the video link is this possible to do on YouPHPTube??

**Comment by CorpCaleCloud** [comment]
it say "By Default you have now a PermaLink on share option" but I'm not sharing so it show the full url or am I miss understanding? is it generic for all share content e.g. user watching the video or just when you share the link to others?

**Comment by DanielnetoDotCom** [comment]
If you check that options all your links will be a permalink instead a SEO link

**Comment by CorpCaleCloud** [comment]
configured it but it didn't work even after restarting the server
![per didnt work](https://user-images.githubusercontent.com/25417743/43997642-3a6c1524-9dd9-11e8-8eb4-1b8363ec2502.PNG)

**Comment by CorpCaleCloud** [comment]
confused???? i'm just trying to hind the info after the domain name so does this option do that or not? the info provided incited that was the case so just trying to understand if it works or not and how to achieve is possible, thanks

**Comment by CorpCaleCloud** [comment]
I checked the demo site and its not fixed there either

![demo site not fixed](https://user-images.githubusercontent.com/25417743/44006806-5184025e-9e82-11e8-9779-d2ebf71b97c5.PNG)

**Comment by DanielnetoDotCom** [comment]
Confirmed I will send a fix

**Comment by CorpCaleCloud** [comment]
thank you
