### ISSUE TITLE
Configurar grupo e categoria padrão para vídeos enviados.

### ISSUE THREAD

**Issue by deivisonmoraes** [DanielnetoDotCom/YouPHPTube#95]
É possível alterar a configuração para mandar os novos vídeos para um grupo e uma categoria padrão?

**Comment by DanielnetoDotCom** [comment]
Infelizmente ainda não temos esta opção, mas é algo que certamente será desenvolvido para as próximas versões

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
