### ISSUE TITLE
Edit the site info when send via social media or whattsapp

### ISSUE THREAD

**Issue by CorpCaleCloud** [DanielnetoDotCom/YouPHPTube#950]
When i send the link to others via social media or messaging apps e.g. WhatsApp under the Site name the info for YouPHPTube appears informing user of what I'm using as a backend system is there anyway to remove or edit this information as I don't what to let them know what I'm using

"The Best YouTube Clone Ever" - YouPHPTube" I want to edit or remove this info in the description

![edit send info](https://user-images.githubusercontent.com/25417743/44002409-c72800b2-9e39-11e8-8df5-ffd29cbfa754.PNG)

**Comment by ChrisSlS** [comment]
You need to go here to edit manually : /view/include/head.php
4th line.

**Comment by CorpCaleCloud** [comment]
Yeah, that fixed it, thanks, topman 5 Stat General, we salute you
