### ISSUE TITLE
Livesearch Images & Footer

### ISSUE THREAD

**Issue by SpinDry77** [DanielnetoDotCom/YouPHPTube#952]
Hello Vinzenz and Daniel,

I bought the live search plug in for my site and the images are not working, its looking for thumbs.jpg and all I have back from the encoder is various other thumbs like thumbsV2.jpg. 

Also its messing up my footer by adding {imgURL} {category} {title} to it. 
![screen shot 2018-08-13 at 12 24 21 am](https://user-images.githubusercontent.com/42334838/44015720-589b6a16-9e8f-11e8-9306-b74f93c7d3be.png)

My site is at clipmet.com

I can comment this out of the footer.php and it fixes that issue but not sure what else commenting that out will break down the road.
![screen shot 2018-08-13 at 1 00 32 am](https://user-images.githubusercontent.com/42334838/44017059-57a1e982-9e94-11e8-9f01-5a279a3c868d.png)

Thanks,
Grant

**Comment by DanielnetoDotCom** [comment]
@hersche  may help you better than me
can you please check your log file to see if we can find any clue

**Comment by SpinDry77** [comment]
There is nothing being written in the youphptube.log its clean right now, I tried to turn it off and on and use it to get something to trigger.

**Comment by SpinDry77** [comment]
I also went though each plugin and turned them on and off so see if anything else what making that change.

**Comment by DanielnetoDotCom** [comment]
do you have the latest youPHPTube ?

**Comment by SpinDry77** [comment]
I do have the latest as of 4 days ago. updates say I'm good. 
Hersche I can test it out before upload if you like.

**Comment by DanielnetoDotCom** [comment]
I update the easytube.club download with @hersche  update

Please download it again

**Comment by SpinDry77** [comment]
Thanks that seems to have fixed it, you guys rock. 
I have a few other problems I'm trying to see if its on my end or a script I may need you again.

**Comment by DanielnetoDotCom** [comment]
Great
