### ISSUE TITLE
Uploading image and Gif error on videos once add to video manager

### ISSUE THREAD

**Issue by CorpCaleCloud** [DanielnetoDotCom/YouPHPTube#953]
I cannot update the video image any more, tried on a few videos however I know get and error

![upload image error 5](https://user-images.githubusercontent.com/25417743/44055342-0d4ad656-9f3d-11e8-85c1-fb625d443d94.PNG)
![upload image error](https://user-images.githubusercontent.com/25417743/44055344-0d79b3ae-9f3d-11e8-92f6-1d7970294687.PNG)

can you explain please, thanks

**Comment by DanielnetoDotCom** [comment]
Check your streamer log file, maybe an writing permission issue

**Comment by CorpCaleCloud** [comment]
where is the stream log please?

**Comment by CorpCaleCloud** [comment]
Here is the log file

![php log](https://user-images.githubusercontent.com/25417743/44145317-04e196e8-a083-11e8-9b53-f01fc0b0660a.PNG)

**Comment by DanielnetoDotCom** [comment]
please attach the log file or show the last lines of it, right after you try to change the image

**Comment by CorpCaleCloud** [comment]
[youphptube.log](https://github.com/DanielnetoDotCom/YouPHPTube/files/2290082/youphptube.log)
see attached

**Comment by DanielnetoDotCom** [comment]
Please, delete your log file, try to change the image and share the log file again right after fail

**Comment by CorpCaleCloud** [comment]
ok

**Comment by DanielnetoDotCom** [comment]
the only thing I can see is the  

```
(mysqlnd) Prepare failed: () <br>
SELECT * FROM plugins WHERE uuid = ? 
```

should be something about your MySQL connection

did you change something on your site that may cause it?

**Comment by CorpCaleCloud** [comment]
I only use the interface not the backend, I did install PHPMyAdmin

**Comment by DanielnetoDotCom** [comment]
I can not reproduce it on my side.
also the mysql error is very strange, must be something!
can you share an admin account of your site to check if there are some JS errors?

**Comment by CorpCaleCloud** [comment]
fixed

**Comment by DanielnetoDotCom** [comment]
Just for Record It was a directory permission issue
