### ISSUE TITLE
VideoThumbnails Plugin?

### ISSUE THREAD

**Issue by SpinDry77** [DanielnetoDotCom/YouPHPTube#954]
Hello,

When the video is done encoding it sends it over to the streaming site but my issue is why doesn't it take care of the sprits during encoding time. When you click on the video it pulls getSpiritsFromVideo.php then you have to wait for FFmpeg to run while the video is waiting to load in the browser for it to create the thumbsSprit.jpp It seems to never create thumbsSprit.jpp until you click on the video. It can take longer to encode the sprit then the video so you can be waiting for the video to load for a while.  I did speed it up a bit by adding -preset ultrafast to the FFmpeg command in getSpiritsFromVideo.php

Is this normal behavior for the plugin, or is something not running right? I don't have any errors in the logs on the encoder server or the streaming server two different servers. The only thing thats odd to me is on the encoding server videos folder I end up with tailxxxxx folders that stay there with a bunch of .png files that never get removed.

Thanks,
Grant

**Comment by SpinDry77** [comment]
My small 5 second test files work fine for giving me the thumbsSprite.jpg but now I am trying real files they all are 0kb in size and I am getting this on the streaming site logs. 

failed to open stream: HTTP request failed!  in /var/www/html/plugin/VideoThumbnails/VideoThumbnails.php(14) : eval()'d code(1) : eval()'d code on line 138

**Comment by DanielnetoDotCom** [comment]
You should find an error on encoder log file about the 0kb file.

also, the spirits are extracted only for the first time the videos are accessed.

**Comment by SpinDry77** [comment]
I have tracked it down more, its producing the png files fine and I can manually covert them to a jpg ok on the server. The thumbsSprit is where is a 0kb file, I'm not sure whats going on but thats the code I can't look at is in the plugin. 

The only log I get any errors out of is the apache error log and it show this, it doesn't mean anything to me. 

video:1814kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

**Comment by TLCReuver** [comment]
I have also 0 bytes thumbsSprits in the past and increased the default_socket_time from 60 to 3200 seconds in php.ini with results. 

Success

**Comment by SpinDry77** [comment]
That did the trick, I had to do it on the encoding server and the streaming server for it to work. Makes sense and explains why I wasn't getting any errors. 

Any ideas on how to speed up the process, it uses next to no CPU and takes 5 times longer then encoding? The video I had took 10 minutes to encode and an hour for the thumbSprite before I could play it.

**Comment by DanielnetoDotCom** [comment]
you can try to improve the FFMPEG command. try to google for it
