### ISSUE TITLE
Excuse me,when does the program support multiple stream server for load balancing?

### ISSUE THREAD

**Issue by FunnyRyan** [DanielnetoDotCom/YouPHPTube#955]
Do you have this plan?
Just like KVS system  to using different  server to strong the same videos for high traffic?

**Comment by DanielnetoDotCom** [comment]
Do you mean for Livestream or VOD?

**Comment by FunnyRyan** [comment]
VOD

**Comment by DanielnetoDotCom** [comment]
You have 2 options:

- Use a CDN (be careful CDN limits the upload)
- Clone the sites and manage it by your self https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Clone-Site-Plugin

**Comment by FunnyRyan** [comment]
i think this plan must be better
see the image below:
http://xiaohost.com/wp-content/uploads/newimg_20180814_120841_55.png

website only for vist

Using multi server for traffic balance

**Comment by FunnyRyan** [comment]
How much does it cost to develop such a plugin?

**Comment by DanielnetoDotCom** [comment]
I am not sure how to do it yet, but email me we can discuss about it.

developer@youphptube.com

**Comment by Ezerbeth** [comment]
Another option is round-robin DNS. My encoder.domain.com redirects to 4 different encoders. It's not real load balancing but it does a decent job.

**Comment by DanielnetoDotCom** [comment]
check this for load balancing, https://network.youphptube.com/

This project is here https://github.com/DanielnetoDotCom/YouPHPTube-Encoder-Network

![image](https://user-images.githubusercontent.com/18009293/44408176-391fc300-a536-11e8-8214-ca1135e10f4f.png)

![image](https://user-images.githubusercontent.com/18009293/44408207-4fc61a00-a536-11e8-9011-3e894f768bcb.png)
