### ISSUE TITLE
Channel Profile Error: My channel page is incorrect what's happened??? 

### ISSUE THREAD

**Issue by CorpCaleCloud** [DanielnetoDotCom/YouPHPTube#956]
When users view my channels (not logged) and when I view it (logged in) I see this preview video with user profile picture and my email address present which is not listed on any user profiles. this is incorrect.
viewable when you go to channel then browse channels this incorrect channel loads

How do I remove this as this is not correct? I have no idea how this came about and want to remove it. also the videos are missing on this channel it foolishness??

Invalid channel profile (what's all this photo and email nonsense I don't want it)
![channel error](https://user-images.githubusercontent.com/25417743/44099409-7550378a-9fda-11e8-954c-b9b6fffff9ee.PNG)

correct channel: I thought this is what users would sees (scroll down to view videos) not the above
![channel error 2](https://user-images.githubusercontent.com/25417743/44099899-9a83941a-9fdb-11e8-8a70-2160a8af43d1.PNG)

how do I fix this? ASAP please

**Comment by DanielnetoDotCom** [comment]
can you share the URL you are talking about?

**Comment by CorpCaleCloud** [comment]
http://www.audiofraternitytube.uk:8080/channels

Just browse channel on the websites when you click the hamburger menu on the left, there's only one channel

Sent from my Windows 10 phone

**Comment by DanielnetoDotCom** [comment]
I see I guess you are talking about the way the app uses your name to identify you correct?

try this 

![image](https://user-images.githubusercontent.com/18009293/44119986-40f4a130-9ff1-11e8-8af1-06cd0b1b5d5f.png)

**Comment by CorpCaleCloud** [comment]
Still the same even htough I ticked the boxes and restarted the server

 



 

 

 

Ticked recommended boxes (I will updated GutHub)

**Comment by DanielnetoDotCom** [comment]
What options did you check?
Is not your username the email?

**Comment by DanielnetoDotCom** [comment]
I just checked and it is working on my side.
do you have the CustomizeAdvanced  plugin enabled?

**Comment by CorpCaleCloud** [comment]
Yes I sent you a screen shot

**Comment by CorpCaleCloud** [comment]
ok this is the admin channel not my AudioFraternity, I figured it out the menu is crazy and inconsistence 



 

Below is the browser channel and its shout the audioadmin and AudioFraternity however it look like one change with the profile picture enable when its not it two sperate channels. This needs to be tidy up considerably

 

 

The top one is audio admin which I don’t use and is showing a preview of a file upload on audiofraternity which is incorrect as don’t use this channel. The bottom is AudioFraternity which is my main channel and has all the videos. It’s a mess and confusing as hell. There needs to be some form of separation between each channel. Its crazy but I get it now. 

 

I try and tidy it up and remove the channel but keep the account.

**Comment by CorpCaleCloud** [comment]
OK

 

I have disabled the account and tried to remove the audioadmin channel and it’s still present even after restarting the server



 

Even though the account is disable it is still showing a active channel above how do I remove the channel audioadmin?

**Comment by DanielnetoDotCom** [comment]
I think I understand now, 

you are saying if you disable the account is still showing a channel right?

**Comment by CorpCaleCloud** [comment]
Yes 

 

However I figured it and I think I have a fix for you

 

This is how it should look and I managed to get it looking like this be deleting all content associated with audioadmin account. 

 



 

Basically it set to if you have content it show the channel, even if the account is disabled which is incorrect it need to be if account is disabled then channel is disable as the channel is link to the account which would solve this problem

**Comment by CorpCaleCloud** [comment]
all resolved. but need some work on the Channel interface so as to be able to more clearly distinguish each induvial channel. 

Channels should not be live be default the should be disabled and should have a enable channel on/off slider on the account or my channel page as this 
(1) This allow user to get content before going live and setup the page correctly before people see it and
(2) new user will be able to do the same so the channel interface is not overloaded with content which is not ready and 
(3) more importantly if content has errors e.g. will not playback, cannot update images , etc you can take the channel offline to fix issues if it to much content is effect with errors which compromising your brand and lose follows as content is not working.

Having an channel offline option would be very beneficial. These are just me suggestion on how to have a better UI and user interaction. 

**Potential Code (I'm no coder)**

If user account is = <new> then <channel> is = hide; if <channel> is equal = unihide then <ShowChannel> is enables; 
else if
;if <channel> is equal =<hide> or <unhide> show option <EnableChannelButton> in <MyAccount>;

;Content is equal = <pubic> if <channel> is equal On else <channel> is equal to <private> if <channel> is = <hide>;

I have no idea if this is correct or not but basically by default the channel is hidden until user enables it once they are happy with the content and if its already live and needs they need to edit due to errors with content user can hind the channel if needed fix e.g. reupload content check and then enable channel.

**Comment by CorpCaleCloud** [comment]
all resolved. but need some work on the Channel interface so as to be able to more clearly distinguish each individual channel.

Channels should not be live be default the should be disabled and should have a enable channel on/off slider on the account or my channel page as this
(1) This allow user to get content before going live and setup the page correctly before people see it and
(2) new user will be able to do the same so the channel interface is not overloaded with content which is not ready and
(3) more importantly if content has errors e.g. will not playback, cannot update images , etc you can take the channel offline to fix issues if it to much content is effect with errors which compromising your brand and lose follows as content is not working.

Having an channel offline option would be very beneficial. These are just me suggestion on how to have a better UI and user interaction.

Potential Code (I'm no coder)

If user account is = ; then is = hide; if is equal = unihide then is enabled;
else if
;if is equal = or show option in ;

; is = if is equal On else is equal to if is = ;

I have no idea if this is correct or not but basically by default the channel is hidden until user enables it once they are happy with the content and if its already live and needs they need to edit due to errors with content user can hind the channel if needed fix e.g. reupload content check and then enable channel.
