### ISSUE TITLE
Remove the stupid scrolling vid window when playing a vid and scrolling down

### ISSUE THREAD

**Issue by jorgen41** [DanielnetoDotCom/YouPHPTube#957]
ADD an option to disable the crap video window that scrolls with the page....
Remove the stupid scrolling vid window when playing a vid and scrolling down WHY is it even there ?

**Comment by DanielnetoDotCom** [comment]
Next time please be more polite 
Look for the FloatVideo plugin, it is a commercial plugin, but I guess you are looking for it

**Comment by jorgen41** [comment]
Thank you and sorry for my bad comment. Other than that window great script.

Regards
Jörgen

**Comment by DanielnetoDotCom** [comment]
Ok thanks
