### ISSUE TITLE
www goes to wrong page

### ISSUE THREAD

**Issue by VlogMe** [DanielnetoDotCom/YouPHPTube#958]
If i type in the WWW.mydomaindotcom instead of https://mydomaindotcom it goes to a default page that says "Ubuntu Logo Apache2 Ubuntu Default Page"

**Comment by DanielnetoDotCom** [comment]
fixed check your site

**Comment by VlogMe** [comment]
It goes to Not Secure? Instead of SSL

**Comment by DanielnetoDotCom** [comment]
it should go SSL only

**Comment by VlogMe** [comment]
Nope. I even cleared my cache/browsing etc on my PC and still goes to not secure

**Comment by DanielnetoDotCom** [comment]
try now again
