### ISSUE TITLE
Gmail Mailer problems

### ISSUE THREAD

**Issue by VlogMe** [DanielnetoDotCom/YouPHPTube#961]
Gmail has rejected my admin email address as the sender, looks like phptube has been blacklisted.

How do I set up an admin@mydomain address?

I have always used cpanel for almost 20 years, this is all new to me :(

**Comment by DanielnetoDotCom** [comment]
It is not blacklisted I used gmail in many sites include in my personal

**Comment by VlogMe** [comment]
So we can't have a real @domain email? Sorry I am not sure why Gmail, that's unprofessional, I don't mean to be rude.

**Comment by DanielnetoDotCom** [comment]
I use https://www.mailgun.com/ for myself, maybe you like it.

**Comment by VlogMe** [comment]
I am failing to understand why we can not have a @domain mailer? People dont like a non domain mail, breaks down trust factor. Imagine Facebook send you email from gmail...

**Comment by DanielnetoDotCom** [comment]
You can, but the email configuration has nothing on YouPHPTube, you have to deal your server and domain

**Comment by VlogMe** [comment]
This is going to far, PLEASE explain to me how to make an admin@mydomain on my current hosting account? I only know cpanel sorry. I am not trying to be hard, please understand, I need this now because all the members are waiting to resign back up!

**Comment by VlogMe** [comment]
Can someone else on here tell me how to install mail on a vps please?

**Comment by VlogMe** [comment]
I dont want mailgun or stupid gmail from admin i WANT PROFESSIONAL REAL BUSINESS EMAIL LIKE ADMIN@MYDOMAIN!!! ANYTHING ELSE IS STUPID!!!!!!!!!!

**Comment by DanielnetoDotCom** [comment]
calm down and use https://www.mailgun.com/. with it you will have your ADMIN@MYDOMAIN mail

**Comment by VlogMe** [comment]
I will attach GoDaddy email system instead. Since the domain is registered there it will have lightning speed. Only 6.99 a month too, way cheaper than railgun after 50 thousand members!

**Comment by DanielnetoDotCom** [comment]
GoDaddy email system is fine

**Comment by VlogMe** [comment]
Yes, I have been with them since they launched, spent over ten k in domains, lol
