### ISSUE TITLE
Header Tags removal?!

### ISSUE THREAD

**Issue by VlogMe** [DanielnetoDotCom/YouPHPTube#962]
I just found when loading the page in facebook for instance, it pulls the header keywords "The Best YouTube Clone Ever - YouPHPTube" I need to remove this right away.

Filezilla doesnt work can anyone recommend a program for editing files?

**Comment by DanielnetoDotCom** [comment]
look for Customize plugin

![image](https://user-images.githubusercontent.com/18009293/44160083-abecf200-a08f-11e8-9088-e1cfaa0c03b5.png)

**Comment by VlogMe** [comment]
I bought that, I have been trying for four hours to figure out where to change it. Advanced or? So little information its frustrating.

**Comment by VlogMe** [comment]
Never mind, close this chat , i found where.

**Comment by VlogMe** [comment]
Installed and working thanks.
