### ISSUE TITLE
CentOS 7 Then you can set the permissions (www-data means apache user).

### ISSUE THREAD

**Issue by alejo1521** [DanielnetoDotCom/YouPHPTube#963]
Hi YouPHPTube Team. Been loving the platform. I installed on a Ubuntu no problem but now I want to use CentOS as i work most of the time whit it. 
But having a problem installing the Application getting (Then you can set the permissions (www-data means apache user).)
![capture1](https://user-images.githubusercontent.com/3569954/44183610-b03dfd00-a0d9-11e8-8c45-3dc97403280e.PNG)
I add the www-data user and group assing it to apache and /videos 
![capture2](https://user-images.githubusercontent.com/3569954/44183707-0874ff00-a0da-11e8-9ae9-9bc308254910.PNG)   
![capture3](https://user-images.githubusercontent.com/3569954/44183708-0b6fef80-a0da-11e8-8672-a0ba4cd6b8d2.PNG)

![capture](https://user-images.githubusercontent.com/3569954/44184099-dd8baa80-a0db-11e8-90ab-fbfc2294b7cc.PNG)

Can you please let me know what to do. And if I need to change anything else on CentOs to run it

Thank you in advanced.

**Comment by DanielnetoDotCom** [comment]
Www-data is the Ubuntu apache user .

You will need to check what is the apache user of your system and replace

**Comment by DanielnetoDotCom** [comment]
Also if the videos directory is writable you can ignore this error

**Comment by alejo1521** [comment]
Daniel,
Thank you for your reply. The httpd user was apache and i was getting the same error. So i created the www-data and assing httpd to it and still having the problem. Will retry again today. Thank you

**Comment by DanielnetoDotCom** [comment]
I think you can install even if it warn the error

**Comment by jayjieh** [comment]
Follow this:
# Ownership
sudo chown apache:apache -R /data/www/html/sites/mysite
cd /data/www/html/sites/mysite
 
# File permissions, recursive
find . -type f -exec chmod 0644 {} \;
 
# Dir permissions, recursive
find . -type d -exec chmod 0755 {} \;
 
# SELinux serve files off Apache, resursive
sudo chcon -t httpd_sys_content_t /data/www/html/sites/mysite -R
 
# Allow write only to specific dirs
sudo chcon -t httpd_sys_rw_content_t /data/www/html/sites/mysite/logs -R
sudo chcon -t httpd_sys_rw_content_t /data/www/html/sites/mysite/uploads -R

**Comment by kikismach** [comment]
Hi @alejo1521, I am trying to install it in CentOs 7 but I have an error with the shell_exec and/or php-fpm, the problem is that ffmpeg and youtube-dl is in red and can't be executed. Do you installed in CentOs? 

![image](https://user-images.githubusercontent.com/6398022/91123494-a228fc80-e662-11ea-9ac2-b16d59bbf91c.png)
