### ISSUE TITLE
Portrait video issues

### ISSUE THREAD

**Issue by md97** [DanielnetoDotCom/YouPHPTube#964]
So there are two issues I'm having when uploading a video in portrait mode...

If you upload MP4 directly, the thumbnail is stretched... But the video is good. 

And if you upload through the encoder, the thumbnail is good... but the video is stretched.

Any suggestions?

**Comment by DanielnetoDotCom** [comment]
We need to improve the portrait format.
We will review it in the future

**Comment by DanielnetoDotCom** [comment]
One thing ....

How is your encoder configuration (ffmpeg commands )?
Is the video from encoder stretched in all reslutions?

Maybe you can change something on the ffmpeg command to fix it
