### ISSUE TITLE
Ads Server Plugin

### ISSUE THREAD

**Issue by Code-Able** [DanielnetoDotCom/YouPHPTube#965]
With the ads server plugin- Once the admin creates the campaign and ads the video, where are the videos displayed?  Before user videos are played?  Please advise.

**Comment by DanielnetoDotCom** [comment]
it will appear as an ad before play a video.

look on demo site, we have vast ads on it (pre-roll, mid-roll and post-roll)

**Comment by Andiweb87** [comment]
and how can i change the ads ?

**Comment by DanielnetoDotCom** [comment]
the video ads must be a video on your YouPHPTube (NOT Embed), you can search them on the video field

**Comment by DanielnetoDotCom** [comment]
check this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Ad-Server-Plugin
