### ISSUE TITLE
PHP Warning: Error while sending QUERY packet. (encoder fails on 2.41 gb mkv file)

### ISSUE THREAD

**Issue by OhioVR** [DanielnetoDotCom/YouPHPTube#967]
Dear Daniel Neto and friends,

I am trying to encode a large full length movie to test my encoder and it is failing with the message

PHP Warning: Error while sending QUERY packet.

in the logs

I have tried running mysql with the following options set:

wait_timeout = 1024
max_allowed_packet_size = 256M

I didn't find the error string in this github issue tracker.

**Comment by DanielnetoDotCom** [comment]
check this https://github.com/DanielnetoDotCom/YouPHPTube/issues/543

**Comment by OhioVR** [comment]
I think I was setting mine too high (4096M) setting it to 512M fixed it (looks like 1G is the max)
