### ISSUE TITLE
Remove Floating Video Preview

### ISSUE THREAD

**Issue by VlogMe** [DanielnetoDotCom/YouPHPTube#968]
When someone visits a members video page to watch the video, a floating video follows you down, obstructing the view.

Do I uncheck/check something in "CustomizeAdvanced (CustomizeAdvanced)"

**Comment by DanielnetoDotCom** [comment]
Look for the FloatVideo plugin, it is a commercial plugin, but I guess you are looking for it

**Comment by VlogMe** [comment]
I think that should be a free option, in fact it should be the other way around to be fair.

If some people want the floating video,. then they could buy.

So we have to buy plugins to make site normal like youtube, c/mon Daniel

You need to specify this on sellers page then, youphptube is not functioned like youtube unless you buy plug-ins.

Then we would know, I have been designing websites, some I can show still working from ten years ago, and this feels like trickery to me. 

I would glady make a donation instead than tricked to buy this.

Please think.

**Comment by DanielnetoDotCom** [comment]
I will think

**Comment by VlogMe** [comment]
Yes, don't burn out from it lol :)
