### ISSUE TITLE
Any Coders Know The Answer?

### ISSUE THREAD

**Issue by VlogMe** [DanielnetoDotCom/YouPHPTube#971]
Hi, do any of you know how to remove the floating video that follows on load of a page?

It distorts and makes the pages unreadable on a small device and I am not willing to buy a plugin for this.

I don't like that it is a really bad feature, yet I have to pay to have it removed. 

Your help would be appreciated.

**Comment by VlogMe** [comment]
Yes Microsoft another powerful company puts all the small people out, so what.

We can make it a great script and claim it as our own once it is modified by our own DEV team(s), like Youtube, no one even Microsoft can touch it. 

It was open source when we took it, and any and all modifications are ours, and maybe we can make it better than anything on Earth.

So, I want to make this script for ourselves work without the floating video.

We are launching USA too next year.

**Comment by abamilod** [comment]
if you are launching is USA as opensource too (with your own modification) then that is good. But if you are launching it as your own (close coded) than you better hire good programmers (disable floating video is not that hard).

**Comment by VlogMe** [comment]
I am sure Danial and others will be around to work :) 

BUT for now, I just think that floaty nightmare should go away :)

I have modified easier scripts over the earlier years, this one is way out of my league.

I worked with simple member sites, just modify the simple code, but i don't have time to spend five years on this.

I spent two years on boonex / dolphin software, it is and always will be a nightmare.

Glad to drop it for good.

**Comment by VlogMe** [comment]
So, can you tell me how to get rid of it @abamilod ? It has to go away, the more plugins that are installed, the slower the site.

**Comment by VlogMe** [comment]
@bobbybark can you tell me how, please? PM me .

**Comment by bobbybark** [comment]
@ VlogMe - I am new to Github, i see no way to contact you

**Comment by bobbybark** [comment]
@VlogMe - WOW very sad, i could had helped you, you have sorry metal issues,
http://diamondbuild.xyz - you look at top of my page i have my own comment page, not part of YouPHPTube..

**Comment by VlogMe** [comment]
@bobbybark WOW!~ looks like you are on collaboration with some people, YOU are very sad....third world idiots...
