### ISSUE TITLE
Safari browser problem or?

### ISSUE THREAD

**Issue by VlogMe** [DanielnetoDotCom/YouPHPTube#972]
I have a member that says : 

"""I click on forgot password and page is stuck on processing."""

She has tried several times, and it keeps sticking and she is using Safari browser.

**Comment by OhioVR** [comment]
I have seen this behavior before. But if I refresh the page, it appears to have logged in.

**Comment by VlogMe** [comment]
On just safari or other too?

**Comment by CorpCaleCloud** [comment]
web browser is the issue, use another browser and you should never have this issue again. i had the same error with users and informed the same. no emails from them since
