### ISSUE TITLE
Pagination doesn't work after latest update (git pull)

### ISSUE THREAD

**Issue by fwn0** [DanielnetoDotCom/YouPHPTube#979]
The requested URL /YouPHPTube/v/179/page/2 was not found on this server.

**Comment by DanielnetoDotCom** [comment]
can you please show us this error on demo site?

**Comment by fwn0** [comment]
select and click next page, select and click video in widget area, result with error message.

 [https://cloud.multibits.eu/s/SKjDQCmps4HeFSR](url)

**Comment by DanielnetoDotCom** [comment]
I need to ask you again if you can reproduce it on demo site.

**Comment by fwn0** [comment]
I have updated YphpT with git pull again. I have still this bug, only the first page is working. I have very old YphpT installation (maybe 2 years), I can fresh install tommorow your nice progie on other VPS.
Hier ist video: 
https://cloud.multibits.eu/s/ZRfwfSDWLCtd344

**Comment by fwn0** [comment]
I found the bug.
First, I don't enabled mods - headers and expires. (I did check .htaccess now).
The problem is the wrong link to video in widgetsarea.
First site works fine - for example: http://178.63.169.66/YouPHPTube/v/499
All other next sites in paginationstask have a wrong links - for example: http://178.63.169.66/YouPHPTube/v/417/page/9 - right link is: http://178.63.169.66/YouPHPTube/v/417

**Comment by DanielnetoDotCom** [comment]
I mean make sure you have the right .htaccess

**Comment by fwn0** [comment]
OK, my wrong error (I do git pull as root). All .htaccess(es) (classic, new and .) was from root owned, but now are all www-data (full directory) and still it doesn't work. I think this issue is my wrong apache configuration, maybe plugins. I did a fresh installation with encoder on other server and - all works perfect :).
