### ISSUE TITLE
Block download by user

### ISSUE THREAD

**Issue by mariu1986** [DanielnetoDotCom/YouPHPTube#98]
Hi, how i could block all possibilites of downloading movies by users ?

**Comment by DanielnetoDotCom** [comment]
There is no option on YouPHPTube to download link/button but on the web there is several tools that allow expert users to download any video (Like we do on youtube with youtube-dl)
So if you want to prevent any user to download your video I do not think it is 100% guarantee.

**Comment by mariu1986** [comment]
When i right-click on video, movie on YouPHPTube i have option "Save video as..." - it is fast and easy way to download movie, is possible to block this option ?

**Comment by DanielnetoDotCom** [comment]
I just release an version witha simple solutionremove the right-click "save" option from the html5 videos
We can slow them down but we can't stop them.

**Comment by mariu1986** [comment]
WOW, great, it works, you are amazing
i must donate you !

**Comment by DanielnetoDotCom** [comment]
Thanks that will be great :)
