### ISSUE TITLE
Critical! Share link doesn't work in forums etc

### ISSUE THREAD

**Issue by VlogMe** [DanielnetoDotCom/YouPHPTube#981]
Our forums have the capability of drag and drop video links from probably every major source on the internet, except for this script.

That's, not an insult it is just a fact that needs fixing.

And forums can't use HTML tags for the iframe embed for the member side as that is a major security risk.

**Comment by DanielnetoDotCom** [comment]
I don't know about your forum, but maybe that is something that needs to be implemented on the forum side.

if is any tag we should add on youphptube side, just let us know we will do it.
