### ISSUE TITLE
Mail Configuration Issue (SMTP connect() failed)

### ISSUE THREAD

**Issue by roquirawnez** [DanielnetoDotCom/YouPHPTube#983]
I try to connect to my own exchange server, but receive
the error "SMTP Connect() failed".
User credentials, domain,dns etc. are right and i can connect via telnet to this server.
Is there something special about a connection to an exchange server?

<img width="776" alt="phpmailer" src="https://user-images.githubusercontent.com/41065691/44334284-5fc7f600-a471-11e8-96ab-b5cdfb583e75.PNG">

**Comment by DanielnetoDotCom** [comment]
I only can say to you it is working with many other SMTP server.

please make sure the credentials/port/protocol are right, also make sure the server where you host youphptube can see your SMTP server

**Comment by roquirawnez** [comment]
Yes everythin is fine there.
Do i need to change something in the php.ini or so?

**Comment by DanielnetoDotCom** [comment]
I dont think so.

**Comment by tvmanus** [comment]
Do you have SELinux or similar enabled?

**Comment by DanielnetoDotCom** [comment]
I saw problems with ffmpeg and youtube-dl in servers with AppArmor
