### ISSUE TITLE
Large files don't encode properly

### ISSUE THREAD

**Issue by Ezerbeth** [DanielnetoDotCom/YouPHPTube#986]
I've been trying to encode a few 2.5GB .mkv files that I created myself from the Bluray disks. Every time, they fail with a slightly different video length.

If I check the mkv with media info:
Duration                                 : 1 h 24 min

If I check the youphplogs:
    [duration:Video:private] => 1:10:22

The upload to YouPHPTube completes to 100% so I'm not sure what it does to truncate the file length. But obviously the video is unplayable after it's been processed. I tried with 3 different mkv files, and they all fail with randomly truncated times, some as much as half the movie is missing.

Any idea what's wrong?

ffmpeg version 4.0.2
YouPHPTube: latest github
PHP 5.6.37
Your post_max_size is 51250M
Your upload_max_filesize is 51200M

**Comment by DanielnetoDotCom** [comment]
You will need to check your log file for errors

How much RAM memory do you have?

There is a script calculation..., your maximum file size can be only 50% of your RAM memory, because the script needs to copy files between locations and handles it on the virtual memory.

In Example, if you want to upload a 4GB file you will need to have at least 8 GB Ram on the server other wise you will have a Memory Leaks - Allowed memory size of # bytes exhausted error.

**Comment by Ezerbeth** [comment]
I have 32GB. While it's not dedicated to encoding, the RAM is mostly free

```
# top -b
last pid: 97837;  load averages:  0.10,  0.05,  0.01  up 7+20:56:28    10:34:28
110 processes: 1 running, 108 sleeping, 1 zombie

Mem: 305M Active, 17G Inact, 759M Laundry, 9618M Wired, 1092M Buf, 3887M Free
ARC: 5433M Total, 1783M MFU, 2335M MRU, 424K Anon, 83M Header, 1232M Other
     3500M Compressed, 7422M Uncompressed, 2.12:1 Ratio
Swap: 16G Total, 94M Used, 16G Free

```

**Comment by DanielnetoDotCom** [comment]
so check your log file to see if you can find errors

also try to manually encode the mkv video ffmpg and check the output

**Comment by Ezerbeth** [comment]
There is no errors in the logs. Converting manually works fine:

```
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : mp4a-40-2
Duration                                 : 1 h 24 min
```

**Comment by DanielnetoDotCom** [comment]
with out an error i have no clue how to find this error.

**Comment by Ezerbeth** [comment]
Ok I was looking at the main logs not the encoder logs. I see this which should be relevant:
`[22-Aug-2018 09:03:52 America/New_York] PHP Warning:  file_get_contents(): content truncated from 2645409336 to 2147483647 bytes in /usr/local/www/videos-encoder/objects/functions.php on line 28`

I've double-checked by php.ini and nothing is set to 2GB (2147483647 / 1024 / 1024 / 1024)

```
# php -i |egrep 'memory_limit|upload_max_filesize|post_max_size'
memory_limit => 16384M => 16384M
post_max_size => 51250M => 51250M
upload_max_filesize => 51200M => 51200M
```

**Comment by Ezerbeth** [comment]
Excuse my ignorance, but how do I dedicate memory to the encoder? I was under the impression it used available system memory, which is more than 28GB free.

**Comment by DanielnetoDotCom** [comment]
I am asking because sometimes you are using smaller containers that limit the memory usage and other server resources.

So one app is not able to consume all server resource.

If you have something similar enabled that may be blocking your php to use your full memory

**Comment by Ezerbeth** [comment]
Ah, thanks for the suggestion but no, it's a fully dedicated FreeBSD box, no containers or virtualization. I'll keep playing around, see if I can figure it out. Thanks for the help, appreciated.

**Comment by Ezerbeth** [comment]
I've narrowed it down to a bug/problem with PHP 5.6.

First I created a dummy file with file_get_contents and a dummy 3GB file, and the problem appeared immediately so it ruled out this script.

So I then created a new VM, with a fresh install (not a clone or template) and installed php 5.6. The exact same problem happened. So I preserved my php.ini, upgraded to PHP 7.2 and everything works as it should.

I will close the issue.

Thank you.

**Comment by DanielnetoDotCom** [comment]
I see, so it is a PHP5.6 problem correct?

**Comment by Ezerbeth** [comment]
As far as I can tell yes. I've upgraded my product box to 7.2 and it works perfectly now. I'm not sure if it's limited to FreeBSD or a general PHP problem however.

**Comment by DanielnetoDotCom** [comment]
I see thanks
