### ISSUE TITLE
Make the player embed private

### ISSUE THREAD

**Issue by youry55** [DanielnetoDotCom/YouPHPTube#988]
During a live streaming on another site, I happened to see player embed, that if I want take the code and insert it in my site, the player doesn't work. This is just what I would do, but during a live with YouPHPTube when I include the player, it is easily withdrawable with inspector and can be included in any site, I don't want this!

The code of example that I taken in other site is this:

<video data-html5-video="" preload="metadata" src="blob:https://whostreams.net/afd3fa83-6dcc-4b27-9f48-9d4c0ee6db3c"></video>

How can I make the player private?

**Comment by DanielnetoDotCom** [comment]
For the live stream, you can not make it private yet, we will improve it in the future.

For VOD videos it is possible with the plugin SecureVideosDirectory
