### ISSUE TITLE
cant install windows server with apache

### ISSUE THREAD

**Issue by NOPENN** [DanielnetoDotCom/YouPHPTube#99]
cant install windows server with apache

i know you must use linux, if there is a windows version me and about 120.000 people
will use it.

**Comment by DanielnetoDotCom** [comment]
You can install the streamer on windows. but the encoder must be on linux

**Comment by DanielnetoDotCom** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by NOPENN** [comment]
ok how use a external encoder?

**Comment by DanielnetoDotCom** [comment]
Please take a look on this: https://tutorials.youphptube.com/video/streamer-and-encoder
And this: https://tutorials.youphptube.com/video/first-video-using-the-video-encoder-version-4-x
