### ISSUE TITLE
[5.6 - 5.8] Comment encoding problem (below a video)

### ISSUE THREAD

**Issue by ChrisSlS** [DanielnetoDotCom/YouPHPTube#990]
![comment](https://user-images.githubusercontent.com/37787071/44443428-ebf42d80-a5d7-11e8-809e-41cfd5946202.png)

In connection with #616 , maybe ?

**Comment by DanielnetoDotCom** [comment]
Can you type here what characters did you enter?

I will try to simulate it here

**Comment by ChrisSlS** [comment]
`l'été il était préférable`

**Comment by DanielnetoDotCom** [comment]
thanks, I will test it

**Comment by DanielnetoDotCom** [comment]
Update and try again please

**Comment by ChrisSlS** [comment]
Hey, it works, thanks !

But now there are no more user images, nor the date of publication :

![maj](https://user-images.githubusercontent.com/37787071/44496987-3e385b80-a677-11e8-9ebd-2d9ffb6ea342.png)

**Comment by DanielnetoDotCom** [comment]
Sorry you right, I miss that

**Comment by DanielnetoDotCom** [comment]
Try again

**Comment by ChrisSlS** [comment]
Thank you again, it works :)

**Comment by ChrisSlS** [comment]
Hi @DanielnetoDotCom , the problem seems to be here too : (when typing category name)

![amp](https://user-images.githubusercontent.com/37787071/44997611-06eb7800-afb0-11e8-8681-4c08a41c37ca.png)

When accents, and '' &' '' its present this happens.
Take your time, it's not disturbing

**Comment by ChrisSlS** [comment]
Thank you all the same. It did not work on my side, either for "&" or an apostrophe.

**Comment by DanielnetoDotCom** [comment]
I just test it here and it is working fine 
![image](https://user-images.githubusercontent.com/18009293/45046257-02749d00-b04c-11e8-94fa-ac6a5718e0bf.png)

**Comment by ChrisSlS** [comment]
It's strange, if I put an apostrophe, it adds "&" and "` "(not an apostrophe, normaly is ' not `).

As I said, it's not annoying for me, but it's strange because it worked well before ^^

**Comment by DanielnetoDotCom** [comment]
The image I am showing above I have ' and " .

Are you sure you update all your files?

**Comment by ChrisSlS** [comment]
Yes of course, I even checked at the moment on the demo site, the problem is the same if we add an apostrophe

**Comment by DanielnetoDotCom** [comment]
Please try again

**Comment by ChrisSlS** [comment]
It works, thanks :+1:

**Comment by ChrisSlS** [comment]
Hello @DanielnetoDotCom 

![editcom](https://user-images.githubusercontent.com/37787071/45985270-c5f1fb00-c065-11e8-86d8-519a9d80b689.png)

When editing a comment, the problem and the same as at the beginning. Can not save it as is.

**Comment by DanielnetoDotCom** [comment]
thanks for noticing it, please try now

**Comment by ChrisSlS** [comment]
100% functional, thanks to you !

**Comment by ChrisSlS** [comment]
Hi, it's me again :dancer: 

![test](https://user-images.githubusercontent.com/37787071/46592945-a0cea500-cac7-11e8-8828-140654c2d70f.png)

How to correct this please ?

**Comment by DanielnetoDotCom** [comment]
Detected and fixed, thanks

**Comment by ChrisSlS** [comment]
@DanielnetoDotCom With version 6.0 (on the demo site in 5.9 it works), there is the same problem as before, when editing:

![comment](https://user-images.githubusercontent.com/37787071/46624468-23d81580-cb31-11e8-9292-d029028dcab5.png)

Also, how to make sure that the true apostrophe is correctly treated ? Because ` is not '.

**Comment by DanielnetoDotCom** [comment]
Sorry you right.

Try now

**Comment by ChrisSlS** [comment]
@DanielnetoDotCom Strangely with version 6.1, some comments can not be posted.

For example, this does not work :

**C'est** `ça, limité à 100 daprès elle :/ Mais il est dispo ici maintenant, pourquoi attendre ? Le site risque de ramer toute la nuit, nous rencontrons quelques soucis... Pas` **d'inquiétude** `donc ^^`

I do not know where exactly the problem comes from, but by removing some accents, it works. Like this :

**Cest**  ```
ça, limité à 100 daprès elle :/ Mais il est dispo ici maintenant, pourquoi attendre ? 
Le site risque de ramer toute la nuit, nous rencontrons quelques soucis... Pas
``` **dinquiétude** `donc ^^`

**Comment by DanielnetoDotCom** [comment]
@ChrisSlS I just test it and it does work for me

**Comment by ChrisSlS** [comment]
@DanielnetoDotCom On version 6.1 ?

**Comment by DanielnetoDotCom** [comment]
Yes, I also just try it on demo site

![image](https://user-images.githubusercontent.com/18009293/47015215-c4769880-d122-11e8-87a7-da4dd5d7c8b3.png)

**Comment by ChrisSlS** [comment]
It's really strange, it does not work on my site. I'll try to see what's wrong, and I'll come back here.

**Comment by ChrisSlS** [comment]
![warningsql](https://user-images.githubusercontent.com/37787071/47195113-c2971a00-d35a-11e8-87dd-324413482dbd.png)

**Comment by DanielnetoDotCom** [comment]
Sorry, I don't understand this error on phpmyadmin

is it related to youphptube? 

I have never seen this before

**Comment by ChrisSlS** [comment]
@DanielnetoDotCom I do not know at all. I realized when I installed the encoder (repaired thanks
to [that](https://devanswers.co/problem-php-7-2-phpmyadmin-warning-in-librariessql-count/)), errors have appeared but the site works very well. The error is displayed on several tables, but it works well, so it's not a problem in itself.

Maybe the comments do not work well because of that, but I do not know, hence my question.

**Comment by DanielnetoDotCom** [comment]
try to repair the tables.

I am not sure how, but I know that there is a command line to do that.

maybe you have that function on phpmyadmin

**Comment by ChrisSlS** [comment]
Okay.

I will investigate and try any viable solution.

**Comment by DanielnetoDotCom** [comment]
Please let me know if there is any progress
