### ISSUE TITLE
The media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by mdeepd** [DanielnetoDotCom/YouPHPTube#991]
I have installed YouPHPTube as described in tutorial. But my live is not working.
Please help.

**Comment by DanielnetoDotCom** [comment]
you need to collect more information, this information is not enough

**Comment by mdeepd** [comment]
Well after a lots of searching ,I fixed it. Now everything is working properly.

**Comment by DanielnetoDotCom** [comment]
Can you please share what was wrong?

**Comment by mdeepd** [comment]
I was getting error on this command
Error-1
sudo /usr/local/nginx/sbin/nginx

nginx: [emerg] bind() to [::]:443 failed (98: Address already in use)

Error-2
Page not found on ..
http://192.168.0.1:8080/stat

So I just try this commands..
/etc/init.d/apache2 stop
systemctl stop nginx
then,,
systemctl start nginx
/etc/init.d/apache2 start
