### ISSUE TITLE
config nginx for server stream

### ISSUE THREAD

**Issue by benx3** [DanielnetoDotCom/YouPHPTube#993]
Hi support team.
Follow [this tutorial](https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Set-up-my-own-Stream-Server) at step 7 when start nginx `sudo /usr/local/nginx/sbin/nginx` i got this error:
![image](https://user-images.githubusercontent.com/40012684/44498739-84f37900-a6aa-11e8-9782-c7831d616d37.png)

Could you help me?
Here my config:
![image](https://user-images.githubusercontent.com/40012684/44498777-be2be900-a6aa-11e8-8aa9-6c8e5dc001d2.png)

**Comment by mikweb2017** [comment]
the configuration for SSL is missing

 listen 444 ssl ???

**Comment by DanielnetoDotCom** [comment]
That is a NGINX limitation, the on_publish, play and record can not be https, must be http

**Comment by benx3** [comment]
Yes @mikweb2017 i using https for my website. i change to http in nginx.conf then nginx start well but i can not using LIVE function(error mess: connect to server fail). 
Live chat working good. 
Here my nginx config: 
` worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://mydomain.com/plugin/Live/on_publish.php;
                            on_play http://mydomain.com/plugin/Live/on_play.php;
                            on_record_done http://mydomain.com/Live/on_record_done.php;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';
                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';
                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }
            }
    }
`
is this right? @mikweb2017 
thank you!

**Comment by benx3** [comment]
Here my plugin config:
![image](https://user-images.githubusercontent.com/40012684/44560948-6198fe80-a77c-11e8-9a82-0f89b5ff2138.png)

**Comment by DanielnetoDotCom** [comment]
@benx3 what is your nginx https port?

You will need https for the live / YouPHPTube integration, but you cant use https on the on_publish parameter

**Comment by OhioVR** [comment]
I found when my port 80 was occupied by letsencrypt I was able to still get YouPHPTube livestreaming to work if I made a location duplicate at port 2000 (or something like that) for the whole streamer site. But my setup is a bit unusual at this time.
