### ISSUE TITLE
Hotkeys for videos not work with GoogleAds_IMA

### ISSUE THREAD

**Issue by ChrisSlS** [DanielnetoDotCom/YouPHPTube#994]
![google-ima](https://user-images.githubusercontent.com/37787071/44509594-6f824d00-a6b2-11e8-93d5-5fe27cbebb1a.png)

Works well on the demo site. I think it happened after a git pull.

**Comment by DanielnetoDotCom** [comment]
It is strange, did you delete your cache dir?

**Comment by ChrisSlS** [comment]
Yeah that's weird, I cleaned the cache a few times (and a full reboot)

**Comment by DanielnetoDotCom** [comment]
I didnt test it, and you are saying this is not happening on demo site?

**Comment by ChrisSlS** [comment]
Yes exactly, I do not know why it affects me, it seems to me that it worked a few days ago.

**Comment by DanielnetoDotCom** [comment]
I am not sure, but try to download again your google IMA, maybe there is an update on it

**Comment by ChrisSlS** [comment]
I tried both methods as explained here: https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-To-Install-a-new-Plugin

But the same error messages appear :/

I specify that this is a recent purchase of the plugin, I do not know if it worked with older versions of PHPTube.

**Comment by DanielnetoDotCom** [comment]
But did you download the pulgin again on easytube.club?

**Comment by ChrisSlS** [comment]
Yes, I re-dl the file.

**Comment by DanielnetoDotCom** [comment]
If you have all files up to date and it is working on demo site, I can't reproduce it. so I cant fix

**Comment by ChrisSlS** [comment]
On the demo site, there is just that :

(before activation GoogleAds_IMA)
![withot](https://user-images.githubusercontent.com/37787071/44615874-7345d900-a844-11e8-904b-519ca486067a.png)

(after activation  GoogleAds_IMA)
![with](https://user-images.githubusercontent.com/37787071/44615875-79d45080-a844-11e8-8d7a-f6b44529b544.png)

I made a git sweater before retesting everything but it does not work.

By the way, I do not know if GoogleAds_IMA works because Google still have not processed my request.

It's strange. It is impossible for me to modify the file "jquery-3.3.1.min.js" because the file crashes every time, I can not: /

Do you have an alternative idea to propose to me, or where to start ?

**Comment by ChrisSlS** [comment]
Not working :(

![error](https://user-images.githubusercontent.com/37787071/44621584-e4b77300-a8a8-11e8-85de-fae79a1e8574.png)

**Comment by DanielnetoDotCom** [comment]
I am not sure what happened, but I update some files for newer versions.

You will need to update your YouPHPTube files and the Google_IMA plugin.

It is already on easytube.

Please let me know if it works

**Comment by ChrisSlS** [comment]
Thank you very much, but it still does not work. (some things seem to have changed, but the same messages come back)

It does not matter, if IMA works well. besides this propo, how do I know if the test page works? I do not see any ads once activated

**Comment by DanielnetoDotCom** [comment]
Hi

I just double check on demo site and it is working.

You need to disable the AD_Server plugin and enable the GoogleAds_IMA

![image](https://user-images.githubusercontent.com/18009293/44729926-3a149f80-aab6-11e8-8222-6c55bb7a0bfb.png)

**Comment by ChrisSlS** [comment]
Thank you, I just checked on the demo website and it works.

IMA is the only one to be activated on my site, but it does not seem to work after 2 days active without ads, the link used is the one you share.

Regarding the basic issue, I just noticed something strange. In galery mode (like the demo site), hotkeys works well without IMA, but once activated, only the big video cooperates with hotkeys (and even disabled! Strange), all the others do not work.
I want to make it clear that once logged in admin mode, hotkeys do not work at all with IMA.

**Comment by DanielnetoDotCom** [comment]
On your server, if you disable Hotkeys, does your IMA plugin works?

**Comment by ChrisSlS** [comment]
I had already tried, and alas no. I just disable it again to see the result.

Regarding hotkeys, what I said on the big video is no longer viable, nothing is functional with IMA activated

**Comment by ChrisSlS** [comment]
No problem, I understand perfectly.

I managed to get two problem with IMA on the demo site, but no relationship with hotkeys.

Screen 1: If an ads is paused, the player freezes.
![adserror](https://user-images.githubusercontent.com/37787071/44812320-3b89b900-abd7-11e8-98ce-52b6dfd38da8.png)


Screen 2: After advertising player, the player loads without the video works, the player is also frozen.
![adserror-fixplayer](https://user-images.githubusercontent.com/37787071/44812327-404e6d00-abd7-11e8-925d-ec15b9f503e8.png)


These are not the same mistakes as on my site, but it can help ^^

**Comment by DanielnetoDotCom** [comment]
strange it, the pause works on my side

**Comment by DanielnetoDotCom** [comment]
Sure will be a pleasure, but I can't reproduce this error where I am I will need to make tests on your environment.

my email developer@youphptube.com

**Comment by ChrisSlS** [comment]
Hello @DanielnetoDotCom 

No relation to the old problem (hotkey + ima), but since the update 5.9, here is what happens: (also in 5.8 the problem was already present for some days)

![errorvideo](https://user-images.githubusercontent.com/37787071/45715222-fcc29f80-bb93-11e8-9e6a-cabd62c41b4b.png)

In addition, IMA does not work properly anymore. over twenty readings, only one ad appears.

That said, thanks for this update, we appreciate adding the number of content in the category list :)

**Comment by DanielnetoDotCom** [comment]
I sent some tweeks, but the problem on that video is regarding a corrupted video file.

**Comment by ChrisSlS** [comment]
Thank you @DanielnetoDotCom 

It does not seem to work, here is the error that is returned :

![errorvideo2](https://user-images.githubusercontent.com/37787071/45753629-b879e280-bc19-11e8-8f43-f096fa01c04e.png)

On the demo site it apparently works, but not on mine

**Comment by DanielnetoDotCom** [comment]
But that looks like be a problem on the quantserve.com

Try this URL instead the one you have now:

https://googleads.g.doubleclick.net/pagead/ads?ad_type=video&client=ca-video-pub-4968145218643279&videoad_start_delay=0&description_url=http%3A%2F%2Fwww.google.com&max_ad_duration=40000&adtest=on

this is the Google test URL

**Comment by ChrisSlS** [comment]
Thank you, but I already work only with the google test link. I just edited my previous post, maybe it can help you

**Comment by DanielnetoDotCom** [comment]
About the load start I could not find a final solution yet.

I follow exactly what they asked to do but sometimes this error still loads.

when this error appears the ad does not display.

**Comment by ChrisSlS** [comment]
@DanielnetoDotCom Another thing, how can I, from the IMA plugin, activate it only for a single video and not the whole site ?

**Comment by DanielnetoDotCom** [comment]
Sorry, we dont have that option yet

**Comment by ChrisSlS** [comment]
I see. Apart from the plugin, I guess I'm able to do it ?

**Comment by ChrisSlS** [comment]
Hello @DanielnetoDotCom 

I post here because it is related to IMA.

I think I know why the validation of Google has not followed up, but after visiting this[ link](https://support.google.com/adsense/answer/3522024?visit_id=636735946306523679-2308803444&rd=1&hl=en), especially this [one](https://support.google.com/adsense/answer/1348695?hl=en), I think that comes from that.

Can you confirm if adding a "Privacy policy" section could fix this? The cookie alert message does not seem to be enough if the site is monetized.

If so, could TopMenu suffice? I was wondering if adding a new rubric next to "about" will do the trick.

**Comment by DanielnetoDotCom** [comment]
@ChrisSlS 

you mean add the Privacy Police next to about?

![image](https://user-images.githubusercontent.com/18009293/46147010-9cd69380-c23a-11e8-8af9-8420435f0b76.png)

**Comment by ChrisSlS** [comment]
@DanielnetoDotCom  That's the idea, yes.

Will it be possible to have this in display, to have two possible choices (yes or no) ? : http://www.cookiechoices.org/ (this is a link proposed by google in their rule)

It's the same as the cookiealert, but with more detail and redirecting to "privacy policy".
