### ISSUE TITLE
Help with LDAP Plugin

### ISSUE THREAD

**Issue by dmongelli** [DanielnetoDotCom/YouPHPTube#995]
My experience with Ubuntu is limited, so I apologize if this is a stupid question.....

I have youphptube installed and functioning. I want to try the LDAP plugin. I followed instructions on 
https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Configure-LDAP-Plugin
I run apt-get install php-ldap with no errors.

How do I configure this? I don't see a plugin available on the plugins page: hrttp://192.168.1.1/YouPHPTube/plugins.
Do I have to modify or create a configuration file somewhere? If so, where?

I'd appreciate any direction. Thanks

**Comment by DanielnetoDotCom** [comment]
Hi

Please check this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-To-Install-a-new-Plugin

**Comment by mikeshoe** [comment]
dmongelli.  Once you buy the plugin, a download button will be available.  Download the plugin zip file to your computer and then navigate to the plugin section of YouPHPTube(while logged in as an admin) and choose the upload plugin feature.  Once you upload the plugin, it will show up in the list.  You will just have to turn it on and configure it.  Good luck!

**Comment by dmongelli** [comment]
Thank you so much!!!

   On Thursday, August 23, 2018, 8:41:47 AM EDT, YouPHPTube <notifications@github.com> wrote:  
 
 
Hi

Please check this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-To-Install-a-new-Plugin
