### ISSUE TITLE
LDAP Plug-In double Login

### ISSUE THREAD

**Issue by EatBananas** [DanielnetoDotCom/YouPHPTube#996]
Hello,
I just installed the LDAP Plug-In and now I realized, that there are two logins available after the activation of the plugin(Picture)
![selection_022](https://user-images.githubusercontent.com/27430069/44532785-408ccb00-a6f4-11e8-948a-1c72a1855c75.png)
The login on the top works for users created in YouPHPTube and the one on the bottom just works for LDAP-Logins. Is this normal and is there a way to combine them, that there is just one login like before?

**Comment by DanielnetoDotCom** [comment]
try this 
![image](https://user-images.githubusercontent.com/18009293/44538047-a702f080-a6d6-11e8-88d9-d61bf057ed8b.png)

**Comment by EatBananas** [comment]
Thanks, that reduced it to one login mask, but now i'm not able to login with the default administrator, who was created at the installation anymore, is there a way to prevent this behaviour?

**Comment by DanielnetoDotCom** [comment]
what you can do is to login with a user with LDAP, transform this user in admin, then disable the native sign in.

For now, you cant have 1 login form for both types of logins

**Comment by EatBananas** [comment]
Ok, that worked, thanks a lot

**Comment by EatBananas** [comment]
I just noticed, that LDAP-Accounts are not able to sign in to the encoder page, ist there solution for this or do you still need to use a YouPHPTube-Local-Admin to upload videos on the encoder?

**Comment by DanielnetoDotCom** [comment]
I am not sure if they can login directly into encoder, but they can login if they use the encoder button on the streamer site

**Comment by EatBananas** [comment]
Do you mean this button here?
![encoderlink](https://user-images.githubusercontent.com/27430069/44660648-99b47180-aa08-11e8-95cb-9a9645c82cbb.jpg)
For me it just works if I use the "Save password"-Option of the LDAP-Plugin, but then I get problems, when I change the password in the active directory.

**Comment by DanielnetoDotCom** [comment]
not encoder network, you should have a button like that 
![image](https://user-images.githubusercontent.com/18009293/44670384-eabc6980-a9f8-11e8-8cc6-2ff0c87575f5.png)

**Comment by EatBananas** [comment]
Thanks a lot, it worked fine!
