### ISSUE TITLE
Space white under player embedded

### ISSUE THREAD

**Issue by youry55** [DanielnetoDotCom/YouPHPTube#998]
When I embed the player in my site, I see a space white under player embedded.
Please see the image in attachment.
![white_space_under_player](https://user-images.githubusercontent.com/42590693/44549403-41882180-a721-11e8-8649-da3c94225701.png)

**Comment by DanielnetoDotCom** [comment]
try this to set a different color on the background 

![image](https://user-images.githubusercontent.com/18009293/44580177-5f7c7300-a76f-11e8-82b6-e7b127ed9c9e.png)

**Comment by youry55** [comment]
I don't want to change color, but I want to remove that white space. How can I remove that white space?
