### ISSUE TITLE
how i solve those isssues 

### ISSUE THREAD

**Issue by jamalmahmud** [DanielnetoDotCom/YouPHPTube#999]
1. How can I show logo one video 

2. URL. Is there anyway we can add  character on url to make the url unique . Because if we do same title for 2 post then url may not unique .

3. How can I set puter menus  

4. In the view sources of a post showing a different or default meta description not the original description of the post .

5. To submit on webmaster how can I activate and place the code

**Comment by DanielnetoDotCom** [comment]
@jamalmahmud 


>1.  How can I show logo one video

![image](https://user-images.githubusercontent.com/18009293/44580428-47f1ba00-a770-11e8-98e2-9a9978288ff8.png)


> 2. URL. Is there anyway we can add character on url to make the url unique . Because if we do same title for 2 post then url may not unique .

They always will be unique, but if you want an unchanged URL (Permlink)
![image](https://user-images.githubusercontent.com/18009293/44580482-753e6800-a770-11e8-8d64-6509ec47acf8.png)

> 3. How can I set puter menus

What is puter menu? but any way to customize menu you need a plugin
![image](https://user-images.githubusercontent.com/18009293/44580510-8edfaf80-a770-11e8-98be-2e872f936ad8.png)

That is how to use https://tutorials.youphptube.com/video/create-a-topmenu

>4.  In the view sources of a post showing a different or default meta description not the original description of the post .

What do you mean?

> 5. To submit on webmaster how can I activate and place the code

You can upload a file, or you can add some HTML code here 
![image](https://user-images.githubusercontent.com/18009293/44580591-d8c89580-a770-11e8-85cb-4aa36d428559.png)

**Comment by jamalmahmud** [comment]
thanks, i ddid buy most of the plugin


please see your invoices i did buy a lot of plugin and did you upload all
those to my site?

**Comment by DanielnetoDotCom** [comment]
I guess I did, if you feel like some are missing, please contact me

**Comment by jamalmahmud** [comment]
In the view sources of a post showing a different or default meta
description not the original description of the post .



example : view-source:
https://roartube.com/video/highlights-seahawks-vs-vikings-nfl-2018-preseason-week-3


here you see website meta data is showing for post metadata , but post meta
should be different that i use


and what is the sitemap , xml site map url for my website to add on google
webmaster

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/44619748-b793a200-a861-11e8-970b-a1e9f1e45b71.png)
The description seems fine to me, what are you expecting.

Sorry for now we don't have an automatic sitemap

**Comment by jamalmahmud** [comment]
1. description is not post description its website meta description .

2. can i installed sitemap plugin   ?

**Comment by DanielnetoDotCom** [comment]
> .description is not post description its website meta description . 

Sorry, I dont understand

> can i installed sitemap plugin

we dont have that plugin

**Comment by jamalmahmud** [comment]
when I check the disk space of the server I found that "/" directory almost
86%. WHen we upload video then it

should goes to "/home" directory but it also consume "/" directory. I guess
there is some configuration issue.

Please check it and help me to fix it.

[image: roartube disk issue.jpg]

**Comment by DanielnetoDotCom** [comment]
The directory problem I will fix for you later

**Comment by DanielnetoDotCom** [comment]
Looks like the root pass has changed, so I could not fix it.

you can resolve it with an symbolic link to the videos directory;

move the videos dir into the home dir,

`sudo mv /var/www/html/YouPHPTube/videos /home/videos`

 and create a symbolic link with the same name 

`sudo ln -s /home/videos /var/www/html/YouPHPTube/videos`

**Comment by jamalmahmud** [comment]
Every post getting website homepage meta description , not specific website
post description .

My post meta description is: <meta name="description" content="Roartube
stands for Sports Highlights for NFL, Cricket, football, College games,
MLB, NBA, Tennis, Golf, Rugby, Motor sports, Supercross, Boxing, UFC & More
">

but this code is showing on all post . but every post i have , with a
different description so that should come in place of home meta.

Thanks .

**Comment by jamalmahmud** [comment]
Every post getting website homepage meta description , not specific website
post description .

My post meta description is: <meta name="description" content="Roartube
stands for Sports Highlights for NFL, Cricket, football, College games,
MLB, NBA, Tennis, Golf, Rugby, Motor sports, Supercross, Boxing, UFC & More
">

but this code is showing on all post . but every post i have , with a
different description so that should come in place of home meta.

Thanks .

Also note it : view-source:
https://roartube.com/video/nfl-preseason-2018-week-3-highlights-cardinals-vs-cowboys
. this post meta description is not showing on view sources thats the
reason why website home meta description  is showing on post instead of
post meta description .

**Comment by DanielnetoDotCom** [comment]
Do you mean the meta description should be the video description, NOT the site description?

**Comment by jamalmahmud** [comment]
Correct .

Thanks

**Comment by jamalmahmud** [comment]
Thanks,

But its a very urgent issues . otherwise you will lose customer and your
website will be  treated as a spam website according to google .

Can u please . fix this issues urgent basis .

thanks

**Comment by jamalmahmud** [comment]
Any update about meta description?
Bro, its not a simple problem , without this seo will not work but will
show spam post . because all post meta is same .

thanks

**Comment by DanielnetoDotCom** [comment]
Hi Jamal, 

It will be updated in the future. but right now we are engaged in something else.

if you are willing to pay we can make this update faster.

Just hire us for 1-hour support, it should be enough to make it https://www.youphptube.com/services#service-prices

**Comment by DanielnetoDotCom** [comment]
Hi Jamal, you can do it on the services page or please email me on developer@danielneto.com

**Comment by jamalmahmud** [comment]
I forget with that i need xml site installed for google .

**Comment by DanielnetoDotCom** [comment]
Please email me, we will setup details

**Comment by jamalmahmud** [comment]
ok,

1. Google XML Sitemap
2. Meta Description problem fixing . so every post get on his own Meta
description as discussed .

IP address: 158.69.116.105
Port: 22
 Username: root
    Password: !Mb01715134811!

**Comment by DanielnetoDotCom** [comment]
Jamal please pay attention this is a public site, do not share your personal info here, I have edited it
If you have something personal, please use my email developer@youphptube.com

**Comment by jamalmahmud** [comment]
Thanks, New pass sent to your email

**Comment by DanielnetoDotCom** [comment]
Jamal, please check your email

**Comment by jamalmahmud** [comment]
50$ . its a huge man , i thought i will ask you to make it 20$ , i am not
so rich man . poor man .

Please make all 30$

And send an invoices of 30$ .  to my paypal admin@aspinternationalinc.com
